### ISSUE TITLE
Plotting triggering copy of view

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#1000]
Example using scanpy 9dd2e94846aa and anndata `762fdb924e757cdd758231`

```python
import scanpy as sc

pbmc = sc.datasets.pbmc3k_processed()
sc.pl.umap(pbmc, color="louvain")  # To make sure that "louvain_colors" has been made
bcells = pbmc[pbmc.obs["louvain"] == "B cells"]
# This line triggers a copy being made:
sc.pl.umap(bcells)
# /Users/isaac/github/anndata/anndata/_core/anndata.py:1120: ImplicitModificationWarning: # Initializing view as actual.
#   "Initializing view as actual.", ImplicitModificationWarning,
assert not bcells.is_view
```

Pretty sure that shouldn't be making a copy, since nothing should be modified in the view. To make sure:

```python
from anndata.tests.helpers import assert_equal

bcells_view =  pbmc[pbmc.obs["louvain"] == "B cells"]
assert_equal(bcells, bcells_view, exact=True)
```

This also seems to be happening with some of the other plotting functions, like `sc.pl.rank_genes_groups_dotplot`.

Elaborating a bit:

To me this is an issue since it will use quite a lot of memory for cases where it isn't needed. Why copy a large number of arrays when you don't need to?

**Comment by flying-sheep** [comment]
Also Issue #1000 woo!
