### ISSUE TITLE
sc.tl.louvain() function bugged in pandas 1.0.0

### ISSUE THREAD

**Issue by Hoa-Lab** [scverse/scanpy#1017]
sc.tl.louvain() works fine in pandas==0.25.3
but it shows error in new pandas==1.0.0:

TypeError: Expected unicode, got numpy.str_

**Comment by flying-sheep** [comment]
Fixed in #1015

**Comment by salwanbutrus** [comment]
I encountered the same problem but with leiden.

**Comment by LuckyMD** [comment]
@salwanbutrus This should be fixed from Scanpy version 1.4.5.1. You may need to update your Scanpy version.
