### ISSUE TITLE
sc.datasets.visium_sge uses adata.is_view (anndata>=0.7rc1)

### ISSUE THREAD

**Issue by mvonpapen** [scverse/scanpy#1027]
Loading data using `adata = sc.datasets.visium_sge('V1_Human_Lymph_Node')` with Anndata<0.7rc1 leads to error `'AnnData' object has no attribute 'is_view'`.
The reason is that the function name changed in version 0.7rc1 from `isview` -> `is_view`. I propose two possible solutions:
**Solution A**: Change requirements to `anndata>=0.7rc1`
**Solution B**: Add function to anndata:
```python
def isview(self):
    return self.is_view()
```
I think solution B is preferable as it provides back-compatibility of anndata.

---

```python
pip install git+https://github.com/theislab/scanpy.git@spatial
import scanpy as sc
adata = sc.datasets.visium_sge('V1_Human_Lymph_Node')
```

```pytb
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-59eff31dcd22> in <module>
      1 get_ipython().system('pip install git+https://github.com/theislab/scanpy.git@spatial')
      2 import scanpy as sc
----> 3 adata = sc.datasets.visium_sge('V1_Human_Lymph_Node')

/opt/conda/lib/python3.7/site-packages/scanpy/datasets/__init__.py in visium_sge(sample_id)
    368 
    369     # read h5 file
--> 370     adata = read_10x_h5(files['counts'])
    371     adata.var_names_make_unique()
    372 

/opt/conda/lib/python3.7/site-packages/scanpy/readwrite.py in read_10x_h5(filename, genome, gex_only)
    169         if gex_only:
    170             adata = adata[:, list(map(lambda x: x == 'Gene Expression', adata.var['feature_types']))]
--> 171         if adata.is_view:
    172             return adata.copy()
    173     else:

AttributeError: 'AnnData' object has no attribute 'is_view'
```

#### Versions:

> scanpy==1.4.5.post3.dev17+g09b9856 anndata==0.6.22.post1 umap==0.3.10 numpy==1.17.5 scipy==1.4.1 pandas==0.25.3 scikit-learn==0.22.1 statsmodels==0.11.0 python-igraph==0.7.1 louvain==0.6.1

**Comment by giovp** [comment]
Changed requirements in #1034 should be fixed now. Thanks for reporting!

**Comment by flying-sheep** [comment]
We have a backwards compatibility wrapper, I have no idea how this error can be possible:

https://github.com/theislab/anndata/blob/41eadb2a76d91ae455faf01afd2382143b9af4b2/anndata/_core/anndata.py#L2137-L2140
