### ISSUE TITLE
feature request: read multiple sheets from excel

### ISSUE THREAD

**Issue by dolleyj** [scverse/scanpy#103]
I have a feature request. Looking at [scanpy.api.read_excel](https://scanpy.readthedocs.io/en/latest/api/scanpy.api.read_excel.html#scanpy.api.read_excel), would it be possible to read an excel file that has multiple sheets, named 'expression', 'observations', and 'genes'? The sheets would be analogous to the the AnnData .X, .obs, and .var.  

Here is an example
[base_template.xlsx](https://github.com/theislab/scanpy/files/1804290/base_template.xlsx)

**Comment by falexwolf** [comment]
Hi Dustin!

Thank you for providing a template. You can easily read that template in with two additional lines of code:
```
import scanpy.api as sc
import pandas as pd
adata = sc.read_excel('./data/base_template.xlsx', sheet='expression').T
adata.obs = pd.read_excel('./data/base_template.xlsx', sheet_name='observations', index_col='observations')
adata.var = pd.read_excel('./data/base_template.xlsx', sheet_name='genes', index_col='gene_symbol')
```
I'm a bit hesitant to put all of this into `sc.read_excel`... it would add 4 new parameters and many people might not have organized their excel files this way? Or am I wrong with the last assumption? If it's something very common todo, I can add the two other lines and extend `read_excel`.

What do you think? Are the two further lines too much additional code?

**Comment by dolleyj** [comment]
Your example above works just fine. Thank you! 

My template is not a universal standard, at least not to my knowledge. For my use case, I'm just trying to provide users a template to populate with their data. At upload I'll convert the xlsx into an AnnData object.

Thanks again!
