### ISSUE TITLE
How to pull out a list of genes of one sample from one cluster

### ISSUE THREAD

**Issue by gabriellayi** [scverse/scanpy#1035]
...
Hi,

I'd like to look at the gene expression from WT and the mutant mice from an interesting cluster, I thought I could use 
sc.tl.rank_genes_groups(WT_Donuts, 'leiden', method='t-test', use_raw=False)
sc.pl.rank_genes_groups(WT_Donuts, n_genes=5, sharey=False),

Then I realized that it's only for getting the marker genes from clusters. 
Thank you for helping me with this issue!

-Yi

**Comment by LuckyMD** [comment]
Hi,

This can be done by subsetting your dataset to the cluster you're interested in and then using the `.obs` column where you store your condition information to do the differential testing. Something like this might work (note i didn't check for typos):

```
WT_Donuts_clust1 = WT_Donuts[WT_Donuts.obs.leiden.isin(['1'])]
sc.tl.rank_genes_groups(WT_Donuts_clust1, 'condition', method='t-test', groups=['mut'], reference='ctrl', key_added='mut_up_ctrl_down')
sc.pl.rank_genes_groups(WT_Donuts_clust1, n_genes=5, key='mut_up_ctrl_down')
```

This code makes the assumption that you have `adata.obs['condition']` which stores the categories `'mut'` and `'ctrl'`, and that you are interested in adata.obs['leiden'] == '1'`. Change these values to match your data.
In the above code you will get the top 5 genes that are up-regulated in `'mut'`  compared to `'ctrl'`. If you want the up-regulated genes in `'ctrl'` compared to `'mut'`, just switch around the keywords above. There are of course better, more sensitive tests for differential expression than a t-test, but if you just want a quick top 5... then this should be fine.

Also note that your use of `use_raw=False` may be dangerous. You should probably be doing a t-test on log-normalized data (not batch corrected, or scaled data, or data where any covariates were regressed out). The t-test assumes normally distributed data, which is approximated by log-normalization.

**Comment by gabriellayi** [comment]
Thank you so much for your explanation, I've tried your code, it's not working yet, I think I should go through my previous code, I'm sure something is wrong. But I understand what you said, I'll try to figure out the errors. 
Thanks again!

**Comment by LuckyMD** [comment]
No problem. 

To give you a quick example with some of the inbuilt datasets:

```
import scanpy as sc
adata = sc.datasets.pbmc68k_reduced()
adata_sub = adata[adata.obs.bulk_labels.isin(['Dendritic'])]
sc.tl.rank_genes_groups(adata_sub, 'phase', method='t-test', groups=['G1'], reference='S', key_added='g1_upreg') 
sc.pl.rank_genes_groups(adata_sub, key='g1_upreg')
```

This version actually works and was tested... just to rule out issues with the code I put above.

**Comment by gabriellayi** [comment]
Hi,
Thank you so much! It worked this time! I got a lot "Keyerror" before, but I tried your tested code, it worked perfectly! 
I really appreciate it!

**Comment by flying-sheep** [comment]
Hi, you should have seen the info about https://scanpy.discourse.group, it’s a better place to ask and answer questions
