### ISSUE TITLE
showing gene expression on umap not working

### ISSUE THREAD

**Issue by pchiang5** [scverse/scanpy#1039]
When I tried to plot the expression of a particular gene on umap map by the tutorial, it always showed the following error:
```
>>> sc.pl.umap(post_adata, color=['XKR4'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Miniconda3\lib\site-packages\scanpy\plotting\_tools\scatterplots.py", line 542, in umap
    return embedding(adata, 'umap', **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\scanpy\plotting\_tools\scatterplots.py", line 207, in embedding
    use_raw=use_raw, gene_symbols=gene_symbols,
  File "C:\ProgramData\Miniconda3\lib\site-packages\scanpy\plotting\_tools\scatterplots.py", line 865, in _get_color_values
    values = adata.raw.obs_vector(value_to_plot)
  File "C:\ProgramData\Miniconda3\lib\site-packages\anndata\core\anndata.py", line 413, in obs_vector
    idx = self._normalize_indices((slice(None), k))
  File "C:\ProgramData\Miniconda3\lib\site-packages\anndata\core\anndata.py", line 364, in _normalize_indices
    var = _normalize_index(var, self.var_names)
  File "C:\ProgramData\Miniconda3\lib\site-packages\anndata\core\anndata.py", line 155, in _normalize_index
    return name_idx(index)
  File "C:\ProgramData\Miniconda3\lib\site-packages\anndata\core\anndata.py", line 142, in name_idx
    .format(i))
IndexError: Key "XKR4" is not valid observation/variable name/index.

```
However, the gene XKR4 did exist in the var_names:
```
>>> post_adata.var_names
Index(['XKR4', 'RP1', 'SOX17', 'MRPL15', 'LYPLA1', 'TCEA1', 'RGS20', 'ATP6V1H',
       'OPRK1', 'NPBWR1',
       ...
       '2700089I24RIK', 'RAB11FIP2', 'E330013P04RIK', 'NANOS1', 'EIF3A',
       'FAM45A', 'SFXN4', 'PRDX3', 'GRK5', 'CSF2RA'],
      dtype='object', length=16249)
```

The anndata object looked as below and it was fine when I tried to show the louvain clusters:

```
>>> post_adata
AnnData object with n_obs × n_vars = 88291 × 16249
    obs: 'CellID', 'batch_indices', 'labels', 'local_means', 'local_vars', 'louvain', 'clusters'
    var: 'gene_id'
    uns: 'neighbors', 'louvain', 'louvain_colors'
    obsm: 'X_scVI', 'X_umap'

>>> sc.pl.umap(post_adata, color=['louvain'])
```

```python
...
```

#### Versions:
scanpy==1.4.5.post3 anndata==0.6.22.post1 umap==0.3.10 numpy==1.18.1 scipy==1.3.2 pandas==0.25.3 scikit-learn==0.22.1 statsmodels==0.11.0 python-igraph==0.7.1+5.3b99dbf6 louvain==0.6.1

**Comment by pchiang5** [comment]
The issue could be fixed by having identical post_adata.var_names and post_adata.raw.var_names. Please ignore this issue.

**Comment by LuckyMD** [comment]
Hi @pchiang5,

Just so you're aware `sc.pl.umap()` has `use_raw=True` as default so that you can only plot the genes that are in `adata.raw.var_names`. You can turn this off via `use_raw=False`.

**Comment by pchiang5** [comment]
Thank you for the information @LuckyMD

**Comment by aditisk** [comment]
@pchiang5 @LuckyMD what does it mean when a gene is present in adata.raw.var_names but not in adata.var_names ? I'm running into a key not found error because of the gene being in one list and not the other.

Thanks.

**Comment by LuckyMD** [comment]
@aditisk that depends on what you put in `adata.raw` ;). Initially `adata.raw` was used to store the full gene object when `adata.X` was filtered to only include HVGs or remove genes that aren't expressed in enough cells. Now, we just have a boolean mask in `adata.var['highly_variable']` for HVGs and so it's often not used anymore. I typically store my log-normalized expression data there if I do batch correction or regress anything out, as `adata.raw` is used as default to compute `rank_genes_groups` and to show expression values on an embedding plot.

**Comment by aditisk** [comment]
@LuckyMD thanks a lot for the detailed explanation.
