### ISSUE TITLE
Flipped y-axis in sc.pl.spatial without img_key 

### ISSUE THREAD

**Issue by emdann** [scverse/scanpy#1059]
Hi. When I use `sc.pl.spatial` to visualize the same data with or without the H&E staining image in the background, the y-axis is flipped if I don't set the `img_key` parameter. Is this expected? 

```python
import scanpy as sc
from matplotlib import rcParams

adata_vis = sc.datasets.visium_sge('V1_Human_Lymph_Node')

rcParams["figure.figsize"] = [8,8]

sc.pp.calculate_qc_metrics(adata_vis, inplace=True)
sc.pl.spatial(adata_vis, img_key = "hires",color=['total_counts'])
sc.pl.spatial(adata_vis,color=['total_counts'], size=100)

```
![Screenshot 2020-02-18 at 16 30 56](https://user-images.githubusercontent.com/32264060/74756365-538e4600-526c-11ea-89f7-46409cb03d3d.png)

**Comment by flying-sheep** [comment]
It kinda is yes, as an image coordinate system is differs in that way from normal plot coordinate system:

- Images are addressed as pixel row × pixel column, with pixel 1,1 in the top left corner, i.e. the coordinates mean ↓ then →
- Plots are done x×y, with position 0,0 to the bottom left of 1,1, i.e. the coordinates mean → then ↑

I assume we should add a parameter to vertically flip plots, and make `sc.pl.spatial` set this parameter by default.

A further idea: without an image we should probably plot the spots as hexagonal tiles.

**Comment by emdann** [comment]
Thanks for clarifying. 

> I assume we should add a parameter to vertically flip plots, and make sc.pl.spatial set this parameter by default.

I think this would be useful. I am alternating between visualising with and without the tissue image in the background and the flipping can cause quite some confusion, esp for "square" tissue sections. 

> A further idea: without an image we should probably plot the spots as hexagonal tiles.

or set a dark background.

**Comment by flying-sheep** [comment]
I also think it would be useful. @giovp what do you think?

**Comment by giovp** [comment]
You can just put `alpha_img = 0`
![image](https://user-images.githubusercontent.com/25887487/74839801-2bfbb400-5326-11ea-95c1-1a95b40766cf.png)
![image](https://user-images.githubusercontent.com/25887487/74839776-21411f00-5326-11ea-8b4e-f4098a7df079.png)

But yeah it's a functionality that should be supported, will have a look at it.
Also, I like the hexagonals @flying-sheep !
