### ISSUE TITLE
Rank gene groups math error in windows

### ISSUE THREAD

**Issue by pati-ni** [scverse/scanpy#1061]
Scanpy affecting most versions tested with 1.4.3

Python 3.6 throws `Math error` exception in windows system for in `rank gene_groups`.

_rank_gene_groups.py:313
```
scores = (scores - (n_active * (n_active + m_active + 1) / 2)) / sqrt(
                    (n_active * m_active * (n_active + m_active + 1) / 12))
```

Reason `sqrt` encounters integer overflow in: ` (n_active * m_active * (n_active + m_active + 1) / 12)` for large numbers.

Quick fix to avoid overflow: divide by 12 before scaling by ` (n_active + m_active + 1)`
_rank_gene_groups.py:313
```
scores = (scores - (n_active * (n_active + m_active + 1) / 2)) / sqrt(
                    (n_active * m_active * (1/12.0) *  (n_active + m_active + 1)))
```
Casting to float could work as well? Behavior in Unix/Linux not tested

**Comment by flying-sheep** [comment]
Hi, thank you for the report. However, you deleted

> Put a minimal reproducible example that reproduces the bug in the code block below

Please do that, so we can create a regression test from it:

```py
import numpy as np
import scanpy as sc
ad = AnnData(np.array([...]))
sc.tl.rank_genes_groups(ad)  # this line crashes without the fix
```

**Comment by pati-ni** [comment]
Since this is an overflow any data set with 1000's of cells I can use for this? I think it is Windows specific crash and how python implements sqrt() on windows which probably is a wrapper of the native math library in C. I may be wrong. So will the regression test work in this case?

**Comment by flying-sheep** [comment]
Uh, we don’t test on windows at the moment so it won’t. To create a data set, you could just have created one using some numpy random function or so.

But as it is we should probably just fix it the way you propose. Care to do a PR?

**Comment by pati-ni** [comment]
No problem
