### ISSUE TITLE
Implementing more normalization options

### ISSUE THREAD

**Issue by dpcook** [scverse/scanpy#107]
Hey guys,

I was wondering what your thoughts were on implementing more-sophisticated normalization options (like [scran](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-0947-7), or [SCnorm](https://www.nature.com/articles/nmeth.4263)). Would you rather just keep this out of scanpy and users can bounce the expression matrix into R for it if they want it?

**Comment by falexwolf** [comment]
Hi David,
it's currently not a focus, at least for me... Our general perspective is to replace all of the manual preprocessing with some "deep learning-based preprocessing"... We will soon have something on this... If it works, more advanced preprocessing becomes obsolete, I guess. If it doesn't, we'll definitely add more advanced stuff...

  Alex

**Comment by dpcook** [comment]
Sounds interesting. Looking forward to seeing it! I'll close this in the meantime. Thanks Alex
