### ISSUE TITLE
link to scVI in documentation

### ISSUE THREAD

**Issue by romain-lopez** [scverse/scanpy#1072]
Hi, 

This is a minor point. Thanks for linking to the scVI repo in your ecosystem page. However, would it be possible to put scVI in another category than "data integration" ? Since scVI can also do differential expression for example. 

Thanks, 
Romain

...

**Comment by ivirshup** [comment]
Hi. Thanks for the input. scVI can definitely be used for quite a lot of tasks. Do you have a recommendation for how it should be talked about on the ecosystem page? (a PR would be welcome of course 😄).

**Comment by Zethson** [comment]
@romain-lopez @adamgayoso could one of you please submit a PR for this?

**Comment by adamgayoso** [comment]
not sure this is necessary anymore as scvi-tools is on the ecosystem page
