### ISSUE TITLE
Read loom file warning

### ISSUE THREAD

**Issue by RM-SCB** [scverse/scanpy#1074]
Hi,

I am new to python and have no idea what this could imply but thought I could report it. I am reading a file convert from `seurat` using `as.loom`. This file works fine if I open it in `scvelo` using  `scv.read`, however, when starting from scanpy using
```
adata = sc.read_loom("seu.loom")
```
I get the following:
```
/Users/rmvl/miniconda3/envs/scanpy_env/lib/python3.7/site-packages/loompy/loom_layer.py:123: RuntimeWarning: invalid value encountered in not_equal
  nonzeros = np.where(vals != 0)
```
I have tried closing all kernels, reinstalling loompy, scanpy, but nothing changed.

#### Versions:

> scanpy==1.4.5.post1 anndata==0.6.22.post1 umap==0.3.10 numpy==1.18.1 scipy==1.4.1 pandas==1.0.1 scikit-learn==0.22.1 statsmodels==0.11.1 python-igraph==0.8.0 louvain==0.6.1

**Comment by flying-sheep** [comment]
1. This warning is produced by loompy. That means that either Seurat made a mistake writing the file or loompy has a bug regarding reading it
2. It’s just a warning, it doesn’t necessarily mean things don’t work. But if you’re worried, file a bug at loompy.
3. No idea why the warning is suppressed in scvelo. @VolkerBergen any idea?

PS: thank you for your excellent bug reports. They’d contain everything we’d need to know if we were in the position to fix them. Few people new to Python manage to do that! I’m sure the people at loompy can help you quickly.

**Comment by ivirshup** [comment]
Especially weird for since (at least for `scvelo 0.1.25`):

```python
import scanpy; import scvelo; import anndata
assert scvelo.read_loom == scanpy.read_loom == anndata.read_loom
assert scvelo.read == scanpy.read
```

**Comment by VolkerBergen** [comment]
At some point we moved scvelo's loom reading to anndata/scanpy and then simply called that one from within scvelo. 

`scvelo.read` and `scanpy.read` are ecaxtly the same. And `read_loom` is called internally within `read`.
