### ISSUE TITLE
dendrogram by genes

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/scanpy#1077]
- [ ] Additional function parameters / changed functionality / changed defaults?
- [ ] New analysis tool: A simple analysis tool you have been using and are missing in `sc.tools`?
- [ ] New plotting function: A kind of plot you would like to seein `sc.pl`?
- [ ] External tools: Do you know an existing package that should go into `sc.external.*`?
- [ ] Other?

...

**Comment by wangjiawen2013** [comment]
sc.pl.heatmap now can execute dendrogram by clusters, can it be extended to dendrogram by genes ?

**Comment by fidelram** [comment]
For this you can use `sc.pl.clustermap`. See: https://scanpy.readthedocs.io/en/stable/api/scanpy.pl.clustermap.html#scanpy.pl.clustermap
