### ISSUE TITLE
zero column/rows

### ISSUE THREAD

**Issue by chansigit** [scverse/scanpy#1083]
I ran filter_cells but still get a zero column

sc.pp.filter_cells(adata, min_genes=200)
sc.pp.filter_genes(adata, min_cells=3)
sc.pp.filter_cells(adata, min_counts=300)
sc.pp.filter_genes(adata, min_counts=1)
sc.pp.filter_cells(adata,max_counts=15000)

sc.pl.scatter(adata, x='nCount_RNA', y='percent.mt')
sc.pl.scatter(adata, x='nCount_RNA', y='nFeature_RNA')
sc.pl.highest_expr_genes(adata, n_top=20 )

print(np.any(adata.X.sum(axis=0) == 0)) # A gene's total UMI across all cells
print(np.any(adata.X.sum(axis=1) == 0)) # nUMI

```
True
False
...
```

#### Versions:

Running scvelo 0.1.25 (python 3.7.3) on 2020-03-04 08:24.
> ...

**Comment by LuckyMD** [comment]
check `adata.raw.X`. That's probably what `sc.pl.highest_expr_genes() is using by default. You should be able to turn this off via the `use_raw` parameter.

**Comment by chansigit** [comment]
> check `adata.raw.X`. That's probably what `sc.pl.highest_expr_genes() is using by default. You should be able to turn this off via the `use_raw` parameter.

My question actually is: 
After I ran sc.pp.filter_genes() and sc.pp.filter_cells(), why are there still zero rows or columns in the datasets, so that print(np.any(adata.X.sum(axis=0) == 0))  returns true?

Shouldn't these zero row/columns/ be eliminated during the pp.filter_X steps? (since they are inplace by default.)

**Comment by fidelram** [comment]
my guess is that if you first genes and then cells, some gene may now have zero counts. First do all the cell filtering and then do the gene filtering.

**Comment by chansigit** [comment]
Yes, by filtering cells first, the problem gets solved.
Thank you all.
