### ISSUE TITLE
Subset and Rescale?

### ISSUE THREAD

**Issue by chansigit** [scverse/scanpy#1089]
We often identify a subset of cells as irrelevant noise cells and hope to discard them during the analysis. I am a bit confused about how to perform such operations in Scanpy.

It's a common practice in other analysis tool like Seurat to do ScaleData across cells so that the relative expression level is adjusted without uninteresting cells' influences. 

Such operation is supported by Seurat by providing multiple "Assay", such as `counts`, `data`, and `scale.data`, which stores the raw UMI counts, column normalized data (across genes, log1p), and row normalized data (across samples, zscores). 

I noticed the scaled data are stored in `adata.X` in scanpy. With this design, how can we access the raw UMI count and do re-scaling if I hope to subset the data?

Looking forward your reply. Thanks.

**Comment by ivirshup** [comment]
The `layers` of an `AnnData` object are closest to the assays from Seurat. You should be able to store whatever transformations of the expression matrix you want in there. 

In general, I do something like:

```python
adata.layers["counts"] = adata.X.copy()
sc.pp.normalize_total(adata)
sc.pp.log1p(adata)
```

As a side note, I don't think we'd recommend using scaled data, but you can read more on that from these [tutorial notebooks](https://github.com/theislab/single-cell-tutorial) or [this related paper](https://www.embopress.org/doi/10.15252/msb.20188746).

**Comment by LuckyMD** [comment]
Hi @chansigit,
If you want to store the raw counts before filtering out cells/genes you can also do this in `adata.raw`. We're trying to reduce the use of this... but it will allow you to store data in a different dimension.

@ivirshup I guess use of scaling is up in the air. Some people like it, some people don't. I find it can be helpful for data integration/batch correction.

**Comment by chansigit** [comment]
Thanks for your help.
I double-checked my data and find scaling is not so important for clustering.

But I do hope to use scaled data for heatmaps, it would be much cleaner.
To achieve this, I hope to keep a layer that stores the scaled data.

Could you please add a 'layer' parameter for ’sc.pp.log1p‘ and ’sc.pp.scale‘ so that we could stores them and compute them without affecting the adata.X?
