### ISSUE TITLE
After slicing and normalizing index remains and PCA values remain(?)

### ISSUE THREAD

**Issue by oliviamr** [scverse/scanpy#109]
#**Here is an example:** 

adata.var.ix['Wfdc18']
result: 
gene_ids    ENSMUSG00000000983
n_cells                   2411
Name: Wfdc18, dtype: object

sc.pp.normalize_per_cell(adata, counts_per_cell_after=1e4)
filter_result = sc.pp.filter_genes_dispersion(
    adata.X, min_mean=0.0125, max_mean=3, min_disp=0.5)
sc.pl.filter_genes_dispersion(filter_result)

adata1 = adata[:, filter_result.gene_subset]
adata1.var.ix['Wfdc18']

KeyError                                  Traceback (most recent call last)
/usr/local/lib/python3.6/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2524             try:
-> 2525                 return self._engine.get_loc(key)
   2526             except KeyError:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'Wfdc18'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-53-fb4aad8315fd> in <module>()
      1 print (adata.var.ix['Wfdc18'])
----> 2 print (adata1.var.ix['Wfdc18'])

/usr/local/lib/python3.6/site-packages/pandas/core/indexing.py in __getitem__(self, key)
    125 
    126             key = com._apply_if_callable(key, self.obj)
--> 127             return self._getitem_axis(key, axis=axis)
    128 
    129     def _get_label(self, label, axis=None):

/usr/local/lib/python3.6/site-packages/pandas/core/indexing.py in _getitem_axis(self, key, axis)
   1106                     return self._get_loc(key, axis=axis)
   1107 
-> 1108             return self._get_label(key, axis=axis)
   1109 
   1110     def _getitem_iterable(self, key, axis=None):

/usr/local/lib/python3.6/site-packages/pandas/core/indexing.py in _get_label(self, label, axis)
    143             raise IndexingError('no slices here, handle elsewhere')
    144 
--> 145         return self.obj._xs(label, axis=axis)
    146 
    147     def _get_loc(self, key, axis=None):

/usr/local/lib/python3.6/site-packages/pandas/core/generic.py in xs(self, key, axis, level, drop_level)
   2342                                                       drop_level=drop_level)
   2343         else:
-> 2344             loc = self.index.get_loc(key)
   2345 
   2346             if isinstance(loc, np.ndarray):

/usr/local/lib/python3.6/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2525                 return self._engine.get_loc(key)
   2526             except KeyError:
-> 2527                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   2528 
   2529         indexer = self.get_indexer([key], method=method, tolerance=tolerance)

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'Wfdc18'

**Moreover, it still plots it?:** 

ax1 = sc.pl.pca_scatter(adata1, components='1,2', color=['Wfdc18'], right_margin=0.2)

![pca_adata1 001](https://user-images.githubusercontent.com/6422882/37835563-d56b07e6-2e86-11e8-8326-c730011de4d4.jpeg)

**Any input I would be most grateful. Many thanks, 
Olivia**

**Comment by falexwolf** [comment]
Dear Olivia,
as I understand, you get a
```
KeyError: 'Wfdc18'
```
when calling
```
adata1 = adata[:, filter_result.gene_subset]
adata1.var.ix['Wfdc18']
```
Right? So, 'Wfdc18' is no longer `adata1.var_names`. You can also check by typing
```
print('Wfdc18' in adata1.var_names)
```
which should print `False`.

Regarding plotting: as stated in the [basic tutorial](https://nbviewer.jupyter.org/github/theislab/scanpy_usage/blob/master/170505_seurat/seurat.ipynb) in box [22], you have to pass `use_raw=False` if you want to access `adata.X` in plotting if `adata.raw` has been set, otherwise it assumes that you want to plot the raw data.
```
sc.pl.pca(adata1, color='Wfdc18', use_raw=False)
```
which will throw an error after filtering if 'Wfdc18' is no longer there. Does this help and explain what you observe?

**Comment by oliviamr** [comment]
Dear Alex, 

Yes it does! 

Thank you for your input!

O.
