### ISSUE TITLE
sc.pl.scatter does not find gene names in adata.raw

### ISSUE THREAD

**Issue by liboxun** [scverse/scanpy#1097]
When I tried to use `sc.pl.scatter` with `use_raw=True` to plot genes whose names are found in adata.raw, but not adata (because they have been filtered out during processing), I got:

`ValueError: 'x', 'y', and potential 'color' inputs must all come from either '.obs' or '.var'`

Plotting genes found in both adata and adata.raw works. Plotting the troublesome genes with `sc.pl.umap` with `use_raw=True` also works. So it seems like a specific issue with the scatter plot function. Am I overlooking anything? Thanks in advance!

**Comment by esrice** [comment]
I'm having the same issue. My inkling is that it's looking in "obs" and "var" but not "var_names" where gene labels are. I'll take a look at it and see if I can fix it when I get a chance.
