### ISSUE TITLE
scanpy heatmap groupby leiden colobar not aligning to the heatmap

### ISSUE THREAD

**Issue by taopeng1100** [scverse/scanpy#1098]
Hi I did not have problems before till now. when I execute this function in  Scanpy:

sc.pl.heatmap(adata, marker_genes_dict, groupby='leiden')

The colorbars for individual leiden cluster do not align to the heatmap.

**Comment by ivirshup** [comment]
Hmm, there was a recent release of marplotlib that seemed to mess with a lot of our plots. Could you post an example of what you're getting and let us know your scanpy and matplotlib versions?

**Comment by taopeng1100** [comment]
When I import Scanpy, I go this output:
scanpy==1.4.4.post1 anndata==0.6.22.post1 umap==0.3.9 numpy==1.16.2 scipy==1.3.2 pandas==0.24.2 scikit-learn==0.21.1 statsmodels==0.10.1 python-igraph==0.7.1+5.3b99dbf6

When I import matplotlib & check version: 3.1.1.

When I execute this line:
sc.pl.heatmap(adata, marker_genes_dict, groupby='leiden')

Output is:
![image](https://user-images.githubusercontent.com/46505353/76695253-1aae7a80-663a-11ea-9fb6-5c4efbe11f3a.png)
GridSpec(2, 4, height_ratios=[0.15, 6], width_ratios=[0.2, 4.8, 0, 0.2])

I did not have the issue before, but after I installed several programs because they are needed for running pyVDJ, I go this issue.

**Comment by ivirshup** [comment]
I can reproduce this plotting issue with matplotlib `v3.1.1`.

I think upgrading to `v3.1.3` should fix your problem, i.e. `pip3 install "matplotlib==3.1.3"`. Unfortunately there's another bug in heatmaps introduced by `3.2.0` that just got fixed on scanpy master (#1090), and hasn't been in a release yet.

**Comment by taopeng1100** [comment]
It worked! I guess when I installed pyvdj, I got 3.1.1. Many thx!

**Comment by ivirshup** [comment]
No worries! Thanks for the bug report!
