### ISSUE TITLE
Highlight specific cells based on hard gene expression cut-offs

### ISSUE THREAD

**Issue by lemdcock** [scverse/scanpy#1120]
Dear Scanpy team, 

In the UMAP plot, I would like to highlight all cells that for instance have and CD3G expression > 2 and CD4 expression < 3. Cells that do not fulfill these two criteria would for instance be dark blue, while those that do are yellow. How would I go about doing this? 

I have tried to follow your advice from: https://github.com/theislab/scanpy/issues/532 . However, this is not exactly what I would wish to do and I am to unfamiliar with the design of the adata object to fix this myself. Could you point me in the right direction?

Kind regards, 
Laurenz De Cock

**Comment by fidelram** [comment]
A simple way to do it is by creating a new `.obs` categorical column as follows:

```python
adata = sc.datasets.pbmc68k_reduced()
# create new categorical column called `selection`
adata.obs['selection'] = pd.Categorical((adata.obs_vector('CD3G') > 2) & (adata.obs_vector('CD4') < 3))
# adjust colors
adata.uns['selection_colors'] = ['blue', 'yellow']
sc.pl.umap(adata, color='selection', add_outline=True, s=20)
```
![image](https://user-images.githubusercontent.com/4964309/77539317-75996a80-6ea1-11ea-8762-bb29b00d8e43.png)

**Comment by lemdcock** [comment]
That's exactly what I needed.
Thank you!

Kind regards,
Laurenz De Cock
