### ISSUE TITLE
AttributeError: 'AnnData' object has no attribute 'obsp'

### ISSUE THREAD

**Issue by shuyuzheng** [scverse/scanpy#1125]
I'm using the "scvelo" https://scvelo.readthedocs.io/getting_started.html for scRNA data analysis. It underlying called "scanpy" function "umap" for calculating the coordinates. I tried the release version "scanpy-1.4.4.post1-py_0". It can not be imported to Python. Error message: "ImportError: cannot import name '_Metric' from 'scanpy.neighbors' (/Users/shuzhe/anaconda3/lib/python3.7/site-packages/scanpy/neighbors/__init__.py)".

I finally switch to the developing version for "scanpy". When I run "umap", it gives me the error message below. I'm wondering what the ".obsp" is and how it is generated.
 

```python
scv.tl.umap(adata)
```

```pytb
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-22-391fc8667646> in <module>
----> 1 scv.tl.umap(adata)

~/scanpy/scanpy/tools/_umap.py in umap(adata, min_dist, spread, n_components, maxiter, alpha, gamma, negative_sample_rate, init_pos, random_state, a, b, copy, method, neighbors_key)
    125     start = logg.info('computing UMAP')
    126 
--> 127     neighbors = NeighborsView(adata, neighbors_key)
    128 
    129     if ('params' not in neighbors

~/scanpy/scanpy/_utils.py in __init__(self, adata, key)
    667             self._dists_key = self._neighbors_dict['distances_key']
    668 
--> 669         if self._conns_key in adata.obsp:
    670             self._connectivities = adata.obsp[self._conns_key]
    671         if self._dists_key in adata.obsp:

AttributeError: 'AnnData' object has no attribute 'obsp'
```

#### Versions:

> scanpy==1.4.7.dev26+gc255fa10 anndata==0.6.22.post1 umap==0.3.10 numpy==1.18.1 scipy==1.4.1 pandas==0.25.3 scikit-learn==0.21.2 statsmodels==0.11.0 python-igraph==0.7.1 louvain==0.6.1

**Comment by flying-sheep** [comment]
The dependencies of scanpy state that anndata>=0.7 are required, please update:

https://github.com/theislab/scanpy/blob/c255fa10fb75f607780ed7d9afc6683cbcecc38e/requirements.txt#L1

Pip would have fullfilled that requirement if you installed the development version using it, but I assume you cloned and installed it manually?
