### ISSUE TITLE
Incompatible function get.rank_genes_groups_df 

### ISSUE THREAD

**Issue by minhtran1309** [scverse/scanpy#1139]
- [ x] Additional function parameters / changed functionality / changed defaults?

...
It happened to me that when I use the function `sc.tl.rank_genes_groups(adata, groupby='groups_r0.2', key_added='rank_genes_r0.2')` the key `rank_genes_r0.2` is added to the attribute `.uns`. However, when I want to extract the coloumn `groups_r0.2` using the function  `sc.get.rank_genes_groups_df(adata, group="0",key='rank_genes_r0.2')` it doesn't work because of the error in ` d[k] = adata.uns["rank_genes_groups"][k][group]` the suggestion is to change the `rank_genes_groups` to `key`

**Comment by ivirshup** [comment]
I think you might be using an out of date version of scanpy. Try updating that. If that fails, please show your version info by running `sc.logging.print_versions()` and pasting the result here.

Probable duplicate of: #781

**Comment by minhtran1309** [comment]
After upgrading the package, the problem resolved. Thanks
