### ISSUE TITLE
AssertionError: Sizes of partitioned, $174.6 do not match on .../_qc.py

### ISSUE THREAD

**Issue by Ngort** [scverse/scanpy#1143]
Running Python 3.7 on Jupyter lab, with version 1.4.6 and also with 1.4.4.post1 (the version my friend can successfully run). When creating an AnnData object, and trying to run calculate_qc_metrics, I get the following error:

```pytb
AssertionError: Sizes of partitioned, $174.6 do not match on /home/$USER/miniconda3/lib/python3.7/site-packages/scanpy/preprocessing/_qc.py (397)

```

What I find most interesting, is that the adata.X object is a **CSR** matrix, whereas for my friend whose code works, adata.X is a **SparseCSRView**. Why is this the case? (same scanpy versions)

```python
batch='pool1'

adata = sc.read_mtx(folder.format(batch)+'matrix.mtx')
adata = adata.transpose()
adata.obs['barcodes'] = pd.read_csv(folder.format(batch)+'barcodes.tsv', sep = '\t', header = None).values
adata.var_names = pd.read_csv(folder.format(batch)+'features.tsv', sep = '\t', header = None)[0].values

sc.pp.calculate_qc_metrics(adata)

```

#### Versions:

> ...
**EDIT: Creating another environment with Python 3.6.1 fixes the issue... What could be wrong?**

**Comment by ivirshup** [comment]
Not sure what's going on here, but it sounds like your environment. Could you post your version info with `sc.logging.print_versions()`?

**Comment by flying-sheep** [comment]
Hi! Since there was no follow-up, I’m going to close this as not reproducible. Feel free to reply and we’ll happily reopen this!
