### ISSUE TITLE
sc.pl.spatial plots vertically flipped spots when  `img_key=None`

### ISSUE THREAD

**Issue by vitkl** [scverse/scanpy#1148]
sc.pl.spatial plots vertically flipped spots when  `sc.pl.spatial(..., img_key=None)`

Try comparing these in your lymph node demo notebook.
```python
# Plot orientation correct
sc.pl.spatial(adata, img_key = "hires", cmap='magma',
              color=['total_counts', 'n_genes_by_counts'])

# Now spots are flipped
sc.pl.spatial(adata, img_key = None, cmap='magma',
              color=['total_counts', 'n_genes_by_counts'])
```

#### Versions:
scanpy==1.4.6 anndata==0.7.1 umap==0.3.10 numpy==1.17.3 scipy==1.4.1 pandas==0.25.3 scikit-learn==0.22.1 statsmodels==0.10.2 python-igraph==0.7.1 louvain==0.6.1

**Comment by giovp** [comment]
Thanks for reporting. Until #1149 is merged, setting `alpha_img=0` should do the trick.

**Comment by vitkl** [comment]
The use case for me is to plot from a large object with many samples, so no image slot present in the object. At the same time I need to see the tissue in a consistent orientation. Thanks for fixing!
