### ISSUE TITLE
new AnnData `.is_view` causes error.

### ISSUE THREAD

**Issue by fidelram** [scverse/scanpy#1151]
PR #1056 added the new `is_view` property. Yet, some anndata, including those in the `sc.datasets` do not have this attribute set. 

```python
adata = sc.datasets.pbmc3k()
sc.pp.scale(adata)
```

```pytb
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-d1141fe2ca57> in <module>
----> 1 sc.pp.scale(adata)

/scanpy/scanpy/preprocessing/_simple.py in scale(data, zero_center, max_value, copy)
    910     if isinstance(data, AnnData):
    911         adata = data.copy() if copy else data
--> 912         view_to_actual(adata)
    913         # need to add the following here to make inplace logic work
    914         if zero_center and issparse(adata.X):

/scanpy/scanpy/_utils.py in view_to_actual(adata)
    377 
    378 def view_to_actual(adata):
--> 379     if adata.is_view:
    380         warnings.warn(
    381             "Revieved a view of an AnnData. Making a copy.", stacklevel=2,

AttributeError: 'AnnData' object has no attribute 'is_view'
```

#### Versions:

> Current scanpy master branch

**Comment by jipeifeng** [comment]
Exactly same error here.
info:
scanpy==1.4.6 anndata==0.6.22.post1 umap==0.3.10 numpy==1.17.5 scipy==1.3.1 pandas==1.0.0 scikit-learn==0.22.1 statsmodels==0.11.0 python-igraph==0.7.1 louvain==0.6.1

**Comment by flying-sheep** [comment]
How does that happen?

**Comment by ivirshup** [comment]
@jipeifeng, I believe this has to do with your version of anndata being out of date.

@fidelram, could this be the case for your environment too?

**Comment by fidelram** [comment]
Indeed this is an issue related to an older version of AnnData. Once AnnData is updated the problem is gone.
