### ISSUE TITLE
'tuple' object has no attribute 'tocsr'

### ISSUE THREAD

**Issue by KabitaBaral1** [scverse/scanpy#1154]
'tuple' object has no attribute 'tocsr'

```python
...
# neighborhood graph of cells (determine optimal number of PCs here)
sc.pp.neighbors(adata, n_neighbors=15, n_pcs=30)
# compute UMAP
sc.tl.umap(adata)
# tSNE
tsne = TSNE( n_jobs=20 )
adata.obsm['X_tsne'] = tsne.fit_transform( adata.X )
adata.write( f_anndata_path )
```

```pytb
computing neighbors
    using 'X_pca' with n_pcs = 30
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-38-e2dd1fe70ab9> in <module>
      6 sc.settings.n_jobs = 15
      7 with parallel_backend('threading', n_jobs=20):
----> 8     sc.pp.neighbors(adata, n_neighbors=15, n_pcs=30)
      9 
     10 #sc.settings.n_jobs = 15

~/miniconda3/envs/scanpy/lib/python3.6/site-packages/scanpy/neighbors/__init__.py in neighbors(adata, n_neighbors, n_pcs, use_rep, knn, random_state, method, metric, metric_kwds, copy)
     93         n_neighbors=n_neighbors, knn=knn, n_pcs=n_pcs, use_rep=use_rep,
     94         method=method, metric=metric, metric_kwds=metric_kwds,
---> 95         random_state=random_state,
     96     )
     97     adata.uns['neighbors'] = {}

~/miniconda3/envs/scanpy/lib/python3.6/site-packages/scanpy/neighbors/__init__.py in compute_neighbors(self, n_neighbors, knn, n_pcs, use_rep, method, random_state, write_knn_indices, metric, metric_kwds)
    681                 knn_distances,
    682                 self._adata.shape[0],
--> 683                 self.n_neighbors,
    684             )
    685         # overwrite the umap connectivities if method is 'gauss'

~/miniconda3/envs/scanpy/lib/python3.6/site-packages/scanpy/neighbors/__init__.py in compute_connectivities_umap(knn_indices, knn_dists, n_obs, n_neighbors, set_op_mix_ratio, local_connectivity)
    322     distances = get_sparse_matrix_from_indices_distances_umap(knn_indices, knn_dists, n_obs, n_neighbors)
    323 
--> 324     return distances, connectivities.tocsr()
    325 
    326 

AttributeError: 'tuple' object has no attribute 'tocsr'
```

#### Versions:

scanpy==1.4.4.post1 anndata==0.6.22.post1 umap==0.4.0 numpy==1.18.1 scipy==1.4.1 pandas==1.0.3 scikit-learn==0.22.2.post1 statsmodels==0.11.1 python-igraph==0.8.0 louvain==0.6.1

> ...
Could you please help me resolve it? I looked up older issues but could not find solution to this. Thank you very much

**Comment by Koncopd** [comment]
Hi, @KabitaBaral1. These happens because of changes in umap 0.4. Please update scanpy to solve this problem.

**Comment by KabitaBaral1** [comment]
Hi Thank you for getting back to me.

I updated it and now when I try to import scanpy as sc I get the following error:

LookupError                               Traceback (most recent call last)
~/miniconda3/envs/scanpy/lib/python3.6/site-packages/anndata/__init__.py in <module>
     89 
---> 90     __version__ = get_version(root="..", relative_to=__file__)
     91     del get_version

~/miniconda3/envs/scanpy/lib/python3.6/site-packages/setuptools_scm/__init__.py in get_version(root, version_scheme, local_scheme, write_to, write_to_template, relative_to, tag_regex, fallback_version, fallback_root, parse, git_describe_command)
    142     config = Configuration(**locals())
--> 143     return _get_version(config)
    144 

~/miniconda3/envs/scanpy/lib/python3.6/site-packages/setuptools_scm/__init__.py in _get_version(config)
    146 def _get_version(config):
--> 147     parsed_version = _do_parse(config)
    148 

~/miniconda3/envs/scanpy/lib/python3.6/site-packages/setuptools_scm/__init__.py in _do_parse(config)
    117         "https://github.com/user/proj/archive/master.zip "
--> 118         "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
    119     )

LookupError: setuptools-scm was unable to detect version for '/Users/kabitabaral/miniconda3/envs/scanpy/lib/python3.6/site-packages'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
~/miniconda3/envs/scanpy/lib/python3.6/site-packages/anndata/compat.py in pkg_version(package)
     56     try:
---> 57         from importlib.metadata import version as v
     58     except ImportError:

ModuleNotFoundError: No module named 'importlib.metadata'

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-11-495a6d84c058> in <module>
      1 import os
----> 2 import scanpy as sc
      3 import numpy as np
      4 import pandas as pd
      5 import loompy as lp

~/miniconda3/envs/scanpy/lib/python3.6/site-packages/scanpy/__init__.py in <module>
      1 # some technical stuff
      2 import sys
----> 3 from .utils import check_versions, annotate_doc_types
      4 from ._version import get_versions  # version generated by versioneer
      5 

~/miniconda3/envs/scanpy/lib/python3.6/site-packages/scanpy/utils.py in <module>
     17 from pandas.api.types import CategoricalDtype
     18 
---> 19 from ._settings import settings
     20 from . import logging as logg
     21 import warnings

~/miniconda3/envs/scanpy/lib/python3.6/site-packages/scanpy/_settings.py in <module>
      7 from typing import Tuple, Union, Any, List, Iterable, TextIO, Optional
      8 
----> 9 from . import logging
     10 from .logging import _set_log_level, _set_log_file, RootLogger
     11 

~/miniconda3/envs/scanpy/lib/python3.6/site-packages/scanpy/logging.py in <module>
      7 from typing import Optional
      8 
----> 9 import anndata.logging
     10 
     11 

~/miniconda3/envs/scanpy/lib/python3.6/site-packages/anndata/__init__.py in <module>
     93     from .compat import pkg_version
     94 
---> 95     __version__ = pkg_version(__name__)
     96     del pkg_version

~/miniconda3/envs/scanpy/lib/python3.6/site-packages/anndata/compat.py in pkg_version(package)
     57         from importlib.metadata import version as v
     58     except ImportError:
---> 59         from importlib_metadata import version as v
     60     return version.parse(v(package))
     61 

ModuleNotFoundError: No module named 'importlib_metadata'

And, when I try to install the module, it says that I already installed it.

Thank you

**Comment by aheravi** [comment]
Hello,
I am also getting the "'tuple' object has no attribute 'tocsr'" error and appreciate your help with that.

I am using the latest scanpy and numpy:

scanpy==1.4.4.post1
numpy==1.18.2

The full command and error:
```
adata_pp = adata.copy()
sc.pp.normalize_per_cell(adata_pp, counts_per_cell_after=1e6)
sc.pp.log1p(adata_pp)
sc.pp.pca(adata_pp, n_comps=15)
sc.pp.neighbors(adata_pp)
sc.tl.louvain(adata_pp, key_added='groups', resolution=0.5)
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-50ed2ff29926> in <module>
      4 sc.pp.log1p(adata_pp)
      5 sc.pp.pca(adata_pp, n_comps=15)
----> 6 sc.pp.neighbors(adata_pp)
      7 sc.tl.louvain(adata_pp, key_added='groups', resolution=0.5)

/Anaconda_python3/lib/python3.7/site-packages/scanpy/neighbors/__init__.py in neighbors(adata, n_neighbors, n_pcs, use_rep, knn, random_state, method, metric, metric_kwds, copy)
     93         n_neighbors=n_neighbors, knn=knn, n_pcs=n_pcs, use_rep=use_rep,
     94         method=method, metric=metric, metric_kwds=metric_kwds,
---> 95         random_state=random_state,
     96     )
     97     adata.uns['neighbors'] = {}

Anaconda_python3/lib/python3.7/site-packages/scanpy/neighbors/__init__.py in compute_neighbors(self, n_neighbors, knn, n_pcs, use_rep, method, random_state, write_knn_indices, metric, metric_kwds)
    681                 knn_distances,
    682                 self._adata.shape[0],
--> 683                 self.n_neighbors,
    684             )
    685         # overwrite the umap connectivities if method is 'gauss'

/Anaconda_python3/lib/python3.7/site-packages/scanpy/neighbors/__init__.py in compute_connectivities_umap(knn_indices, knn_dists, n_obs, n_neighbors, set_op_mix_ratio, local_connectivity)
    322     distances = get_sparse_matrix_from_indices_distances_umap(knn_indices, knn_dists, n_obs, n_neighbors)
    323 
--> 324     return distances, connectivities.tocsr()
    325 
    326 

AttributeError: 'tuple' object has no attribute 'tocsr'
```

**Comment by Koncopd** [comment]
Hi, @aheravi .

scanpy==1.4.4.post1 is not the latest version, the latest version is 1.4.6.

**Comment by aheravi** [comment]
Thanks, @Koncopd.

**Comment by KabitaBaral1** [comment]
Hi @Koncopd I tried updating scanpy, but it does not let me update from 1.4.4.post1. How do I update it to 1.4.6 using conda?

Thank you

**Comment by aheravi** [comment]
Hi @KabitaBaral1 ,
You can update it using:
```
pip install --upgrade scanpy
```

**Comment by ilibarra** [comment]
> Hi @KabitaBaral1 ,
> You can update it using:
> 
> ```
> pip install --upgrade scanpy
> ```
in conda
```
conda install -c bioconda scanpy=1.4.6
```

**Comment by sztankatt** [comment]
I get same error as @KabitaBaral1 after updating to scanp==1.4.6, namely: `AttributeError: module 'cairo' has no attribute 'version_info'` also see the issue #1166

**Comment by ivirshup** [comment]
@Koncopd, do you think the initial problem with `connectivities` somehow being a tuple has been resolved?

**Comment by Koncopd** [comment]
@ivirshup Yes, it was solved in scanpy 1.4.5.

**Comment by ivirshup** [comment]
Great! I'm going to close this then, since the discussion seems to be more about installation issues now.

**Comment by Flope** [comment]
I am getting this error when I run scanpy.pp.neighbors(adata)
As far as I know, I have the latest packages mentioned here.
anndata                   0.7.6                    pypi_0    pypi
louvain                   0.7.0            py38h9dedd22_1    conda-forge
pandas                    1.1.3            py38hb1e8313_0
python-igraph             0.9.1            py38h3dab7cd_0    conda-forge
scanpy                    1.7.2                    pypi_0    pypi
scikit-learn              0.23.2           py38h959d312_0
scipy                     1.6.3            py38h431c0a8_0    conda-forge
statsmodels               0.12.0           py38haf1e3a3_0
umap-learn                0.5.1            py38h50d1736_0    conda-forge

Is there probably another package that is outdated?

**EDIT:  Not sure what module I updated but now it works. I use 'conda update --all' and others to do that.** 

thanks

**Comment by ahmedibatta** [comment]
I face the same problem. However I used latest version 
</scanpy==1.4.6 anndata==0.7.4 umap==0.5.1 numpy==1.20.3 scipy==1.6.3 pandas==1.2.4 scikit-learn==0.22.2.post1 statsmodels==0.11.1 python-igraph==0.8.2 , bbknn : 1.5.0
