### ISSUE TITLE
TypeError  in scanpy.external.tl.sam

### ISSUE THREAD

**Issue by mamonsterliu** [scverse/scanpy#1157]
Hi, I was trying to apply the SAM integration on a merged dataset of three example dataset from 10x homepage, in an attempt to compare the result to the PAGA and bbknn integrated umap.
I got a successful run on one of the PBMC dataset with no reprocessing.  However in any other case I kept bump into an error:

TypeError: some keyword arguments unexpected

Here is the record.

On the other hand, if I want to integrate bbknn with SAM, do I just apply bbknn after the run of SAM like this?

////
import scanpy.external as sce

sam_obj = sce.tl.sam(adata)
sc.pl.umap(sam_obj, color='Sample') 

bbknn.bbknn(adata,batch_key='Sample')
#does this change the umap? or do I need to make another call of tl.umap?

sc.pl.umap(sam_obj, color='Sample') 
////
i

```python
...
```

import scanpy.external as sce
for adata in adatalist:
    sam_obj = sce.tl.sam(adata)
    sce.pl.sam(adata,projection='X_umap')

```pytb
...

Self-assembling manifold
Running SAM
RUNNING SAM
Iteration: 0, Convergence: 0.016564277393631113
Iteration: 1, Convergence: 0.01278454723440345
Computing the UMAP embedding...
Elapsed time: 50.534051179885864 seconds
Self-assembling manifold
Running SAM
RUNNING SAM
Iteration: 0, Convergence: 0.022868878389371346


---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-17-4514ae92b370> in <module>
      1 import scanpy.external as sce
      2 for adata in adatalist:
----> 3     sam_obj = sce.tl.sam(adata)
      4     sce.pl.sam(adata,projection='X_umap')

~/.local/lib/python3.7/site-packages/scanpy/external/tl/_sam.py in sam(adata, max_iter, num_norm_avg, k, distance, standardization, weight_pcs, sparse_pca, n_pcs, n_genes, projection, inplace, verbose)
    216         projection=projection,
    217         sparse_pca=sparse_pca,
--> 218         verbose=verbose,
    219     )
    220 

~/anaconda3/lib/python3.7/site-packages/samalg/__init__.py in run(self, max_iter, verbose, projection, stopping_condition, num_norm_avg, k, distance, preprocessing, npcs, n_genes, weight_PCs, sparse_pca, proj_kwargs)
   1014 
   1015             W, wPCA_data, EDM, = self.calculate_nnm(
-> 1016                 n_genes, preprocessing, npcs, nnas, weight_PCs, sparse_pca,
   1017             )
   1018             new = W

~/anaconda3/lib/python3.7/site-packages/samalg/__init__.py in calculate_nnm(self, n_genes, preprocessing, npcs, num_norm_avg, weight_PCs, sparse_pca, update_manifold)
   1117 
   1118         if update_manifold:
-> 1119             edm = ut.calc_nnm(g_weighted, k, distance)
   1120             self.adata.uns["nnm"] = edm
   1121             EDM = edm.copy()

~/anaconda3/lib/python3.7/site-packages/samalg/utilities.py in calc_nnm(g_weighted, k, distance)
    448     if g_weighted.shape[0] > 8000:
    449         # only uses cosine
--> 450         nnm, dists = nearest_neighbors(g_weighted, n_neighbors=k, metric=distance)
    451         EDM = gen_sparse_knn(nnm, dists)
    452         EDM = EDM.tocsr()

~/anaconda3/lib/python3.7/site-packages/samalg/utilities.py in nearest_neighbors(X, n_neighbors, metric, metric_kwds, angular, seed, low_memory)
    175             leaf_array=leaf_array,
    176             n_iters=n_iters,
--> 177             verbose=False,
    178         )
    179 

TypeError: some keyword arguments unexpected
```

#### Versions:

> ...

**Comment by ivirshup** [comment]
@atarashansky, could you take a look at this?

**Comment by atarashansky** [comment]
A few things!

1. What version is UMAP and numba?

2. Can you post your full workflow? How are you generating the AnnData objects in `adatalist`? The convergence scores in your SAM output are suspicious. They should be something like 0.4, 0.1, 0.001,... Usually I get convergence scores like yours when I have an issue with the preprocessing of the data.
 
3. The tricky bit about applying SAM to batch-corrected data is that batch correction results in negative values in the data, whereas SAM requires non-negative data to calculate dispersion. In order to account for this, I use `adata.X` to calculate the manifold, and `adata.layers['X_disp']` to calculate the dispersions. The 'X_disp' layer should store the nonnegative expression values.

If you want to run SAM on batch corrected data, make sure that you set `adata.layers['X_disp']` to be the original non-negative expression values. If you don't assign `adata.layers['X_disp']` yourself, then it is automatically assigned to be equal to `adata.X`. If `adata.X` has negative expression values due to batch correction, then that'll cause problems for SAM. Not sure if it's related to this specific bug, but it's good to know anyway.

**Comment by mamonsterliu** [comment]
So it will only work on non-negative expression values without any pre-process?
I guess that make sense, thank you for the reply.

The version of the package:

scanpy==1.4.6 anndata==0.7.1 umap==0.4.0 numpy==1.18.1 scipy==1.4.1 pandas==1.0.3 scikit-learn==0.22.2.post1 statsmodels==0.11.1 python-igraph==0.8.0

The  AnnData objects were all read through same commands without any modification.

sc.read_10x_h5(filepath, gex_only=False)

the dataset I used to test them are:

https://support.10xgenomics.com/single-cell-vdj/datasets/2.2.0/vdj_v1_hs_nsclc_5gex
https://support.10xgenomics.com/single-cell-gene-expression/datasets/3.0.0/pbmc_10k_protein_v3
https://support.10xgenomics.com/single-cell-gene-expression/datasets/3.0.0/malt_10k_protein_v3

It appears to me that it only works on the v2 nsclc h5 data.

I was trying to merge the three data sets and run through SAM to compare with the result of BBKNN, didn't work.

So I tried to run each of them individually in the loop. I guess it won't work on CITESeq data without other processing?

I tried removed all the antibody read counts from adata.X and ran it once, still got same error message.

**Comment by atarashansky** [comment]
Can you give me the version information from all the packages in your environment (output of conda list)?

What operating system are you running?

**Comment by atarashansky** [comment]
I fixed this issue!

It should be all good in SAM version 0.7.2. Please update SAM using either pip or github. Let me know if there are still any other problems.
