### ISSUE TITLE
subsampling cells number

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/scanpy#1159]
sc.pl.heatmap and the related functions plot all the cells of each cluster at default. Sometimes cell number differ a lot among the clusters, so the heatmap becomes unblanced, some clusters take a lot of space, while some small clusters becomes unclear. So subsampling is necessary to sample an equal
number of data points from each cluster using a user-defined threshold while clusters lower than the threshold keep the same.

**Comment by ivirshup** [comment]
I'm not sure subsampling is the most straightforward solution here. If you want the area of the plot for each sample to take the same amount of space, why not just plot the mean for each group? If you want even use of space and an idea of the distribution, why not use something like a violin plot?

**Comment by wangjiawen2013** [comment]
Good idea, thanks!

**Comment by ivirshup** [comment]
This issue has been mentioned on **Scanpy**. There might be relevant details there:

https://scanpy.discourse.group/t/heatmap-max-number-of-cells-per-cluster/202/2
