### ISSUE TITLE
Switching to conda-forge?

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#1169]
@flying-sheep I'm thinking we should switch to using conda-forge for distributing scanpy.

Right now, we're having trouble maintaining the bioconda builds. We already use conda-forge for anndata, so I think it would reduce the maintenance burden to consolidate our build systems. Also, I find conda-forge's tooling and documentation much easier to follow.

I've started setting up a conda-forge recipe, which has gone pretty well. However I'm running into one issue with the tests. It looks like we don't bundle the `conftest.py` file at our project root with the rest of scanpy. This leads to the flaky internet tests being run when the conda package is built. Not sure how to deal with this at the moment.

Update: Also `test_regress_out_ordinal` seems to hang forever when testing the build.

**Comment by ivirshup** [comment]
Another example of bioconda causing issues: #1298

**Comment by ivirshup** [comment]
I would like to do this for the next release series.

**Comment by flying-sheep** [comment]
Fixed in conda-forge/staged-recipes#15083

**Comment by ivirshup** [comment]
Thanks @flying-sheep!
