### ISSUE TITLE
Question about neighbors and obsp

### ISSUE THREAD

**Issue by dawe** [scverse/scanpy#1176]
...
Since I'm writing an extension that performs some analysis on neighbor graph I'm a bit confused about the current status of scanpy's way to store that information. Will connectivity matrix always be stored into `adata.obsp` making `adata.uns['neighbors']['connectivities']` deprecated? I always need to access the connectivity sparse matrix, as far as I understand the path will be

```python
conn_key = adata.uns[neighbor_key][f'{neighbor_key}_connectivities']
adata.obsp[neighbor_key][conn_key]
```

except when no `neighbor_key` is given and matrix is `adata.obsp['connectivities']`, correct?

**Comment by Koncopd** [comment]
Yes, except for `conn_key`.
the right path is
```
conn_key = adata.uns[neighbor_key]['connectivities_key']
adata.obsp[conn_key]
```

**Comment by dawe** [comment]
Excellent, thank you. I'll patch my code accordingly.
