### ISSUE TITLE
Bug in _download_visium_dataset()

### ISSUE THREAD

**Issue by LiBuchauer** [scverse/scanpy#1184]
After creating a fresh conda environment on Mac OS Mojave and starting to replicate the "Analysis and visualization of spatial transcriptomics data" tutorial, after running

```python
adata = sc.datasets.visium_sge()
```
I get 

```pytb
FileNotFoundError: [Errno 2] No such file or directory: '/Users/lisa/data/V1_Breast_Cancer_Block_A_Section_1'
```
I figured it is because the intermediate folder "/data" is missing as well  - 

```python
sample_dir.mkdir(exist_ok=True)
```
in ```_download_visium_dataset()``` cannot create it, it would need the flag ```parents=True``` to do so (https://docs.python.org/3/library/pathlib.html#pathlib.Path.mkdir).

#### Versions:

scanpy==1.4.7.dev52+g590d4230 anndata==0.7.1 umap==0.4.1 numpy==1.18.1 scipy==1.4.1 pandas==1.0.3 scikit-learn==0.22.2.post1 statsmodels==0.11.1

**Comment by flying-sheep** [comment]
Thanks, just stumbled upon it myself. Fixed in #1185
