### ISSUE TITLE
TypeError with sc.pp.calculate_qc_metrics

### ISSUE THREAD

**Issue by preetida** [scverse/scanpy#1193]
... I am not sure it's bug or package error. I am getting Segmentation fault error with sc.pp.calculate_qc_metrics with my data. I tried running this on eg. data, and have the same error. I think this might be related to numba issue, but not sure. I did ran python debugger on the script, also attaching the output i got. 
[scanpylog.txt](https://github.com/theislab/scanpy/files/4567012/scanpylog.txt)

```python
#!/usr/bin/env python
import os, sys 
import scanpy as sc
import scanpy.external as sce
import scipy as sp
import numpy as np
import pandas as pd
os.getcwd()

#sc.settings.verbosity = 3             # verbosity: errors (0), warnings (1), info (2), hints (3)
#sc.logging.print_versions() #this also give segmentation fault error 

#1102  external eg file 
#curl -o pbmc_1k_v2_filtered_feature_bc_matrix.h5 -O http://cf.10xgenomics.com/samples/cell-exp/3.0.0/pbmc_1k_v2/pbmc_1k_v2_filtered_feature_bc_matrix.h5

#load file
ext_AD = sc.read_10x_h5('/home/pjb40/scratch/KimCarla_Timeseries_scRNAseq_lung_cancer_organoids_hbc03856_scrathDir/data/TimeSeries_epithelial_ScanpyNotebook/ext_data/pbmc_1k_v2_filtered_feature_bc_matrix.h5', gex_only = True)

ext_AD.var_names_make_unique()

print(ext_AD)

sc.pp.calculate_qc_metrics(ext_AD, inplace=True)

print (ext_AD)

...
```

```pytb
Traceback (most recent call last):
  File "timeseriesScanpy.py", line 65, in <module>
    sc.pp.calculate_qc_metrics(ext_AD, inplace=True)
  File "/home/pjb40/jupytervenv/lib/python3.7/site-packages/scanpy/preprocessing/_qc.py", line 274, in calculate_qc_metrics
    parallel=parallel
  File "/home/pjb40/jupytervenv/lib/python3.7/site-packages/scanpy/preprocessing/_qc.py", line 102, in describe_obs
    proportions = top_segment_proportions(X, percent_top, parallel)
  File "/home/pjb40/jupytervenv/lib/python3.7/site-packages/scanpy/preprocessing/_qc.py", line 355, in top_segment_proportions
    mtx.data, mtx.indptr, np.array(ns, dtype=np.int), parallel
  File "/home/pjb40/jupytervenv/lib/python3.7/site-packages/scanpy/preprocessing/_qc.py", line 383, in top_segment_proportions_sparse_csr
    return _top_segment_proportions_sparse_csr_cached(data, indptr, ns)
  File "/home/pjb40/jupytervenv/lib/python3.7/site-packages/numba/dispatcher.py", line 349, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/pjb40/jupytervenv/lib/python3.7/site-packages/numba/dispatcher.py", line 316, in error_rewrite
    reraise(type(e), e, None)
  File "/home/pjb40/jupytervenv/lib/python3.7/site-packages/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed at nopython (nopython frontend)
Unknown attribute 'partition' of type Module(<module 'numpy' from '/n/app/python/3.7.4-ext/lib/python3.7/site-packages/numpy/__init__.py'>)

File "../../../../../../../home/pjb40/jupytervenv/lib/python3.7/site-packages/scanpy/preprocessing/_qc.py", line 399:
def _top_segment_proportions_sparse_csr(data, indptr, ns):
    <source elided>
        elif (end - start) > maxidx:
            partitioned[i, :] = -(np.partition(-data[start:end], maxidx))[:maxidx]
            ^

[1] During: typing of get attribute at /home/pjb40/jupytervenv/lib/python3.7/site-packages/scanpy/preprocessing/_qc.py (399)

File "../../../../../../../home/pjb40/jupytervenv/lib/python3.7/site-packages/scanpy/preprocessing/_qc.py", line 399:
def _top_segment_proportions_sparse_csr(data, indptr, ns):
    <source elided>
        elif (end - start) > maxidx:
            partitioned[i, :] = -(np.partition(-data[start:end], maxidx))[:maxidx]
            ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new

...
```

#### Versions:

> ...

[Version](url) of the packages in path : 
scanpy                            1.4.4.post1
anndata                           0.6.22.post1
anndata2ri                        1.0.1
umap-learn                        0.3.10
numpy                             1.16.5
scipy                             1.3.1
pandas                            1.0.1
scikit-learn                      0.21.3
statsmodels                       0.10.1
python-igraph                     0.7.1.post6
louvain                           0.6.1

**Comment by ivirshup** [comment]
I don't think this is a segfault, but a `TypeError`. I believe this is due to using an out of date version of `numba`. Could you update that and let me know if the error persists?

**Comment by preetida** [comment]
Yups! that worked 👍 Thanks a ton!

**Comment by preetida** [comment]
This is not related, and most certainly separate issue. <can start a new thread > 
I am getting memory error with sc.tl.pca
What is your recommendation? 

Traceback (most recent call last):
  File "timeseriesScanpy.py", line 111, in <module>
    sc.tl.pca(adata, svd_solver='arpack') # svd_solver='arpack' is important for reproducibility
  File "/home/pjb40/jupytervenv/lib/python3.7/site-packages/scanpy/preprocessing/_simple.py", line 498, in pca
    X = adata_comp.X.toarray()  # Copying the whole adata_comp.X here, could cause memory problems
  File "/home/pjb40/jupytervenv/lib/python3.7/site-packages/scipy/sparse/compressed.py", line 1024, in toarray
    out = self._process_toarray_args(order, out)
  File "/home/pjb40/jupytervenv/lib/python3.7/site-packages/scipy/sparse/base.py", line 1186, in _process_toarray_args
    return np.zeros(self.shape, dtype=self.dtype, order=order)
MemoryError

**Comment by ivirshup** [comment]
I think that might be due to the dense array being to large to fit in memory on your machine. Just to be sure, how large is your dataset? And how much memory do you have?

For the current release, you could either try using the incremental PCA, using a subset of the data, or using a machine with more memory. In the next scanpy release, there will be a much more memory efficient PCA implementation.

**Comment by preetida** [comment]
Quite big! i have 8 samples with average of ~4000 cells. Total ~32K cells. 
merged AnnData 
AnnData object with n_obs × n_vars = 67948800 × 27998 
    obs: 'sample'
    var: 'gene_ids', 'feature_types', 'genome'

Also running this on cluster with 150GB mem.

**Comment by ivirshup** [comment]
I think you've got more than 32k cells in the object, looks like ~68 million (😮)? The number of `obs` is the cells, while the number of `vars` is the genes. 150GB should be more than enough memory for 32k cells. Probably not enough for 68 million.

Probably look through your code to figure out how you're getting so many observations?

**Comment by ivirshup** [comment]
I'm going to mark this as closed for the TypeError issue. I'm definitely interested to hear how you ended up with that many cells!
