### ISSUE TITLE
Error occurred when ReadH5AD('~/pca.h5ad') function from seurat3.1 taking scanpy(v1.4.6) h5ad file as inputting 

### ISSUE THREAD

**Issue by honghh2018** [scverse/scanpy#1198]
Hi all,
    Thanks to develop the great tools for singlecell analysis.

The h5ad file was generated by scanpy workflow using function write.h5ad(), nevertheless, 
as of taking the outputed file h5ad of scanpy as file imported Seurat package using  ReadH5AD triggerred error like below:
      Error in file [["obs"]] []: objects of category 'environment' cannot take a subset
 What happen in this situation? 
 and how to fix it?
  any advices would be grateful

```python
  Python 3.8.2 
```

```

#### Versions:
<!-- Output of scanpy.logging.print_versions() -->
scanpy 1.4.6
>

**Comment by LuckyMD** [comment]
Hi @honghh2018,

This might be an issue you have to raise with Seurat about their ReadH5AD function. From `AnnData` 0.7 the h5ad format has changed a little on disk, so maybe their function is not updated to this yet? Other ways you can go between Scanpy and Seurat are loom files or `anndata2ri` as shown [here](https://github.com/LuckyMD/Code_snippets/blob/master/Seurat_to_anndata.ipynb)
