### ISSUE TITLE
diffusion map "sigma"

### ISSUE THREAD

**Issue by ghost** [scverse/scanpy#120]
Is there documentation explaining how scanpy calculates diffusion maps?

In particular, I'm wondering how it estimates "sigma" and whether it's possible to vary this parameter within scanpy?

**Comment by falexwolf** [comment]
Hi! I added a more extensive explanation in the [docs](https://scanpy.readthedocs.io/en/latest/api/scanpy.api.tl.diffmap.html#scanpy.api.tl.diffmap). 

The line in the code where the sigmas are calculated is [here](https://github.com/theislab/scanpy/blob/e78062a0e4f02888cab080f8ed2571ff7764efc7/scanpy/neighbors/__init__.py#L725).

There is no explicit way of changing this parameter... you can only implicitly change it via the number of neighbors. See the [examples](https://scanpy.readthedocs.io/en/latest/examples.html#simple-pseudotime).

Does this help?

**Comment by ghost** [comment]
Thanks for the quick response. My understanding is that diffusion maps are extremely sensitive to sigma, so I'm curious why you don't allow direct control of this parameter?

I also notice the following comment in your source code:
"choose sigma, the heuristic here doesn't seem to make much of a difference"

Does this mean that in your tests, varying sigma doesn't make much of a difference? If so, I'm curious why this is because in my own tests using the destiny package, choice of sigma matters quite a bit.

**Comment by ghost** [comment]
From the documentation, it sounds like the default is to use an exponential kernel. Is this correct?

**Comment by falexwolf** [comment]
The "choice" mentioned in the source code regards how to compute sigma from the distances of the k nearest neighbors. In the default setting (sparse knn graph), this uses the median. In the completely different original dense and smooth setting of Coifman and Laleh's first diffmap paper, this uses the distance to the k-th neighbor divided by 4... Both of theses choices are completely ad hoc... The only goal that they should achieve is give you some smoothing already *among* the k nearest neighbors, and not just beyond (there are no further neighbors in the sparse setting).

In destiny, some additional flexibility is allowed. You can choose the number of nearest neighbors and the sigma. Even though in principle it's ok to have both parameters, from the interpretation view it's not very clear. Both parameters affect the size of your effective local neighborhoods. In the dense setting, varying sigma makes a huge difference in destiny as it controls the neighborhood size alone, you can achieve the same by varying `n_neighbors` in scanpy. In the sparse setting, sigma does not influence the result a lot any more, if you don't choose pathological values, but `k` (called `n_neighbors` in scanpy) dramatically determines the size of the local neighborhood. So Scanpy tries to not burden the user with a parameter sigma that might take some thinking to understand and destroys consistency between the sparse-dense setting.

Having said that, I'd generally recommend using umap or draw_graph for the things that you did with diffmap up to now... It's so much easier to have everything in 2 dimensions...

Does this help?

**Comment by falexwolf** [comment]
Ah, and yes, the default is the "exponential kernel" of UMAP [McInnes18]. While this is again kind of a detail and your results will probably be qualitatively the same when you change the kernel, we have made better experiences with the more recent thoughts of McInnes on measuring connectivity of manifolds...

**Comment by ghost** [comment]
Ah got it. Thanks for the quick response! Really appreciate the help. I am marking this as closed now.
