### ISSUE TITLE
Add transfer learning (TL) technique such as ProjectR to scanpy

### ISSUE THREAD

**Issue by jorvis** [scverse/scanpy#1205]
- [ ] Additional function parameters / changed functionality / changed defaults?
- [x] New analysis tool: A simple analysis tool you have been using and are missing in `sc.tools`?
- [ ] New plotting function: A kind of plot you would like to seein `sc.pl`?
- [ ] External tools: Do you know an existing package that should go into `sc.external.*`?
- [ ] Other?

We are increasingly using ProjectR as a transfer learning technique from one dataset onto others.  It would be great if this were part of the scanpy package, since most of the rest of what we do with single-cell uses scanpy.  I'm going to start working on integration of the two but doubt I have the data science experience currently to submit a PR to this project for it.

Are there any plans already in the works to pull in transfer-learning techniques such as this?

Relevant links:

- [Article in Bioinformatics](https://academic.oup.com/bioinformatics/advance-article-abstract/doi/10.1093/bioinformatics/btaa183/5804979?redirectedFrom=PDF)
- [Article in Cell](https://www.cell.com/cell-systems/pdf/S2405-4712(19)30146-2.pdf)
- [GitHub](https://github.com/genesofeve/projectR)

**Comment by giovp** [comment]
Hi @jorvis ,

ProjectR as far as I'm aware relies on some form of matrix decompositon (PCA, NMF) and do transfer learning with learnt weights. In some sense, it's similar to ingest. However, it would be a bit complicated to port it from R. 
It doesn't seem super complicated to have it in scanpy as an additional tool, but it's not really a priority now. If you have anything in mind and would want to try with submitting a PR, it would be very much appreciated and we would definitely have a look! 
I'll close this for now, but pls feel free to re-open if you want to continue discussion or would like to discuss implementation.
