### ISSUE TITLE
pca_variance_ratio does not return axis

### ISSUE THREAD

**Issue by HypoChloremic** [scverse/scanpy#1211]
https://github.com/theislab/scanpy/blob/2a7fb7cdf56ff44ef6338c7dba3b84b4b32d216c/scanpy/plotting/_tools/__init__.py#L120-L129

Is it meant that the `pca_variance_ratio` does not return the generated axis? There is no `return` in the function definition, in addition to it not handling the returned fig object from `ranking(...)`

**Comment by giovp** [comment]
I believe it is, pinging @Koncopd who probably knows more about it. If this is desired behaviour, we could close this.

**Comment by giovp** [comment]
Hi @HypoChloremic 

would something like this be useful for your question? https://scanpy.readthedocs.io/en/stable/api/scanpy.pl.pca_overview.html#scanpy.pl.pca_overview
https://scanpy.readthedocs.io/en/stable/api/scanpy.pl.pca_variance_ratio.html#scanpy.pl.pca_variance_ratio
?

**Comment by giovp** [comment]
will close this due to inactivity
