### ISSUE TITLE
Filtering cells with a high % of reads mapping to genes in the mitochondrial genome

### ISSUE THREAD

**Issue by P4sm** [scverse/scanpy#122]
Hi,

I noticed that Scanpy doesn't have a ready function for filtering cells with a high percentage of reads mapping to genes in the mitochondrial genome. Is there still some easy way to do this? Apparently this type of cells can be bad.

_In the absence of spike-in transcripts, the proportion of reads mapped to genes in the mitochondrial genome can also be used. High proportions are indicative of poor-quality cells (Islam et al. 2014; Ilicic et al. 2016), possibly because of loss of cytoplasmic RNA from perforated cells. The reasoning is that mitochondria are larger than individual transcript molecules and less likely to escape through tears in the cell membrane._

https://www.bioconductor.org/help/workflows/simpleSingleCell/#examining-gene-level-metrics

**Comment by falexwolf** [comment]
Hey!

We do it as they do in Seurat. See [here](https://nbviewer.jupyter.org/github/theislab/scanpy_usage/blob/master/170505_seurat/seurat.ipynb), available through the [examples page](http://scanpy.readthedocs.io/en/latest/examples.html):
```
adata = adata[adata.obs['percent_mito'] < 0.05, :]
```
in Box 8. Does this help you or do you need more?

Best,
  lex

**Comment by P4sm** [comment]
Oh, thank you. There it is. I was only aware of this example. https://nbviewer.jupyter.org/github/theislab/scanpy_usage/blob/master/170503_zheng17/zheng17.ipynb

**Comment by falexwolf** [comment]
Hm, how should I make the Seurat-style tutorial more prominent? It's the first on the examples webpage, but you somehow didn't see it? It's meant to be the thing that people should start with...
