### ISSUE TITLE
[tl.diffmap] ValueError: Can only assign an array of same length (43570), not of length 2056.

### ISSUE THREAD

**Issue by chriscainx** [scverse/scanpy#123]
Background: ~40k cells, umap, tsne, ... all had no problem. When running diffmap:
`sc.tl.diffmap(adata,n_comps=13)`

>/fastdata/chris/bin/anaconda3/lib/python3.6/site-packages/scanpy/neighbors/__init__.py:793: RuntimeWarning: divide by zero encountered in true_divide
  Q = scipy.sparse.spdiags(1.0/q, 0, W.shape[0], W.shape[0])
/fastdata/chris/bin/anaconda3/lib/python3.6/site-packages/scanpy/neighbors/__init__.py:803: RuntimeWarning: divide by zero encountered in true_divide
  self.Z = scipy.sparse.spdiags(1.0/z, 0, K.shape[0], K.shape[0])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-6472f1ef45f7> in <module>()
----> 1 sc.tl.diffmap(adata,n_comps=13)

/fastdata/chris/bin/anaconda3/lib/python3.6/site-packages/scanpy/tools/diffmap.py in diffmap(adata, n_comps, copy)
     49     dmap.compute_transitions()
     50     dmap.compute_eigen(n_comps=n_comps)
---> 51     adata.obsm['X_diffmap'] = dmap.eigen_basis
     52     adata.uns['diffmap_evals'] = dmap.eigen_values
     53     logg.info('    finished', time=True, end=' ' if settings.verbosity > 2 else '\n')

/fastdata/chris/bin/anaconda3/lib/python3.6/site-packages/anndata/base.py in __setitem__(self, key, arr)
    104             raise ValueError('Can only assign an array of same length ({}), '
    105                              'not of length {}.'
--> 106                              .format(self.shape[0], arr.shape[0]))
    107         # the following always allocates a new array
    108         # even if the key already exists and dimensions match

ValueError: Can only assign an array of same length (43570), not of length 2056.

What might be the problem here?

**Comment by falexwolf** [comment]
Seems like an "old" X_diffmap has only length 2056. But that should not be the case, of course, as that would be invalid.

I just learned about a bug in the storage of the graph `.uns['neighbors']['connectivities']` that appears when you do subsetting on an AnnData and want to access the original object.

That could explain what is happening...

I'll submit a bug for that in the next couple of hours.

**Comment by falexwolf** [comment]
If it's what I suspect it to be, it should be fixed with anndata 0.5.9. `pip install anndata==0.5.9`.
