### ISSUE TITLE
misleading docs: docs & docstring for sc.pp.pca incorrectly states pca_sparse as a keyword arg

### ISSUE THREAD

**Issue by alasla** [scverse/scanpy#1234]
Both the docs here: https://scanpy.readthedocs.io/en/stable/api/scanpy.pp.pca.html and the docstring on the function scanpy.pp.pca incorrectly states pca_sparse as a keyword arg.  It looks like maybe at one point in the PR that produced this that was the case (been tracking the sparse PCA PRs), but it now looks like it is just the default now.  

Should be removed from the docstring.

**Comment by ivirshup** [comment]
Thanks for pointing this out! Fix incoming.
