### ISSUE TITLE
d = sce.tl.palantir(adata) returns "None"

### ISSUE THREAD

**Issue by zmokhtari** [scverse/scanpy#1237]
Hi,
Thanks for providing an amazing platform for single-cell data analysis. 
I was trying to use palantir in scanpy and I just reran the example data. However, 
d = sce.tl.palantir(adata) 
always return None for any kind of data. Could you please comment on this?
I am using scanpy 1.5 and have updated Palantir to 0.2.6
Thanks in advance,
Zeinab

**Comment by kousaa** [comment]
I am facing the same issue. I have recently updated my scanpy to the latest version.
I think that it was working before that.

Here is rest of my software versions
scanpy==1.4.6 anndata==0.7.1 umap==0.3.9 numpy==1.17.4 scipy==1.3.1 pandas==0.25.3 scikit-learn==0.22 statsmodels==0.10.1 python-igraph==0.7.1 louvain==0.6.1

**Comment by gokceneraslan** [comment]
@awnimo can you have a look?

**Comment by awnimo** [comment]
@gokceneraslan 

A fix is provided here https://github.com/theislab/scanpy/pull/1245

In the meanwhile until this PR is merged into a new release you can follow this https://github.com/dpeerlab/Palantir/issues/34#issuecomment-632933449

**Comment by eroell** [comment]
Just came across this, look like it has been fixed - thanks everyone involved back then!
