### ISSUE TITLE
sc.tl.rank_genes_groups to rank only top 200 genes?

### ISSUE THREAD

**Issue by gabriellayi** [scverse/scanpy#1238]
...
Hi,  I'm using sc.tl.rank_genes_groups to rank genes from one cluster, but I realized that it can show a maximum of 200 genes, can I change this default setting? Or I should use totally different code to get a gene list more than 200.  
Thank you in advance! Yi

**Comment by ivirshup** [comment]
You can use the keyword argument `n_genes`.

If you call:

```python
sc.pp.rank_genes_groups(adata, group, n_genes=-1)
```

You'll get results for all genes.

**Comment by gabriellayi** [comment]
> You can use the keyword argument `n_genes`.
> 
> If you call:
> 
> ```python
> sc.pp.rank_genes_groups(adata, group, n_genes=-1)
> ```
> 
> You'll get results for all genes.

Thanks! That worked!
Best,
Yi
