### ISSUE TITLE
very slow when I run sc.tl.draw_graph

### ISSUE THREAD

**Issue by icml-compbio** [scverse/scanpy#1242]

**Comment by YubinXie** [comment]
same for sc.pp.neighbors. I noticed that only one core/cpu is used. Is this normal?

**Comment by ivirshup** [comment]
@icml-compbio The `draw_graph` function calls out to `forceatlas2` if you have it installed. This does seem slower than using UMAP.

@YubinXie I see some multithreading being used on my machine when I run `neighbors`. Is there none on yours? One thing I'd check first is to make sure UMAP is up to date and install `pynndescent`.

**Comment by YubinXie** [comment]
@ivirshup Thanks. will do a test. BTW, Does scanpy support python 3.8?

**Comment by YubinXie** [comment]
```
/home/miniconda3/envs/pytorch/lib/python3.8/site-packages/umap/spectral.py:4: NumbaDeprecationWarning: No direct replacement for 'numba.targets' available. Visit https://gitter.im/numba/numba-dev to request help. Thanks!
  import numba.targets
```

I got this warning and not sure if it is related

**Comment by ivirshup** [comment]
Python 3.8 should work. I think that warning just has to do with numba and pytorch.

**Comment by YubinXie** [comment]
@ivirshup pytorch is the environment name... the warning is from umap

**Comment by ivirshup** [comment]
Ah, my bad, I read the path wrong on my phone.

In general, the most recent numba release cycle had a lot of deprecations, so many packages are throwing numba warnings.

**Comment by YubinXie** [comment]
I did some checking. 

1. KNN works with multiple cores. 
2. Leiden clustering is fast.
3. It is sc.tl.draw_graph that is slow (fa2). But I am surprised that it takes 20+ min for 67k cells.

**Comment by fidelram** [comment]
`sc.tl.draw_graph` is much slower than UMAP. 20 mins for 67k cells does not surprise me.

draw_graph uses by default https://github.com/bhargavchippada/forceatlas2  You may want to search in that package if computations can be speed up.

**Comment by eroell** [comment]
We will close the issue for now, as based on the provided information and the discussion so far, it seems that the question has been addressed and hopefully useful insights obtained :)

However, please don't hesitate to reopen this issue or create a new one if you have any more questions or run into any related problems in the future.

Thanks for being a part of our community! :)
