### ISSUE TITLE
leiden install instructions are wrong

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#1243]
leiden install via conda code is wrong in the current page. it should be:

```
conda install -c conda-forge leidenalg 
```

_Originally posted by @YubinXie in https://github.com/theislab/scanpy/pull/1216#issuecomment-632506015_

**Comment by Zethson** [comment]
What is wrong with the current installation instructions?

`conda install -c conda-forge python-igraph leidenalg`

Is python-igraph not required? It's also bad practice to mix Conda and PyPI installations (yes it works). 

What about changing:
```
If you do not have a working installation of Python 3.6 (or later), consider installing Miniconda (see Installing Miniconda). Then run:

conda install seaborn scikit-learn statsmodels numba pytables
conda install -c conda-forge python-igraph leidenalg
```

to

```
If you do not have a working installation of Python 3.6 (or later), consider installing Miniconda (see Installing Miniconda). Then run:

conda install -c conda-forge scanpy python-igraph leidenalg
```

The other packages are already included in the recipe: https://bioconda.github.io/recipes/scanpy/README.html
