### ISSUE TITLE
sc.tl.pca() return TypeError: __init__() got an unexpected keyword argument 'rmatmat'

### ISSUE THREAD

**Issue by Linnas** [scverse/scanpy#1246]
...
![image](https://user-images.githubusercontent.com/39158851/82787725-a09c3c80-9e99-11ea-9a09-94e43c114185.png)
with adata like this:
![image](https://user-images.githubusercontent.com/39158851/82787817-d6412580-9e99-11ea-9fc6-2866402b668e.png)

and adata.X:
![image](https://user-images.githubusercontent.com/39158851/82787794-cc1f2700-9e99-11ea-9957-a1b37cbd7881.png)

```python
...
```

```pytb
...
```

#### Versions:

> ...
1.5.1

**Comment by ivirshup** [comment]
Thanks for the bug report! Could you include some version information about your environment?

**Comment by Linnas** [comment]
OS: Windows 10
Python version: 3.7.7
sc.logging.print_versions() gives
scanpy==1.5.1 anndata==0.7.1 umap==0.3.10 numpy==1.18.4 scipy==1.3.1 pandas==0.25.1 scikit-learn==0.21.3 statsmodels==0.10.1 python-igraph==0.7.1 louvain==0.6.1 leidenalg==0.7.0

**Comment by Linnas** [comment]
Maybe it's the upgrade to version 1.5.1 that leads to this bug, I can run this piece of code under 1.4.6.

**Comment by ivirshup** [comment]
Yes, it looks like we didn't update our dependency requirements correctly. It looks like the `rmatmat` argument for `LinearOperators` was only added as of `1.4`.

I believe using `scanpy 1.5.1` with `scipy>1.4` should fix this. Could you let me know if that solves your problem?

**Comment by Linnas** [comment]
Yes, it works! Thank you for your suggestion.
