### ISSUE TITLE
sc.tl.pca() return TypeError: __init__() got an unexpected keyword argument 'rmatmat' in ubuntu

### ISSUE THREAD

**Issue by iSinedeus** [scverse/scanpy#1252]
Hello,

I am having the same issue as issue #1246 but my version of scipy being used with scanpy is not updating. I don't know if this is related to my using an ubuntu server or what's causing this but I was wondering if there is a workaround to make scanpy use a more updated version? I have scipy 1.4.1 installed when I check the version but for some reason scanpy is using 1.01 and I don't know how to change this. I'm a bit new to python so I'm sorry if this is a novice question. I appreciate any help you can offer.

I am using an ubuntu server running python 3.6 with the following versions:
sc.logging.print_versions() 
scanpy==1.5.1 anndata==0.7.3 umap==0.4-dev numpy==1.15.0 scipy==1.0.1 pandas==0.23.3 scikit-learn==0.23.1 statsmodels==0.11.1

This is the error message:

```pytb
computing tSNE
WARNING: You’re trying to run this on 16872 dimensions of `.X`, if you really want this, set `use_rep='X'`.
         Falling back to preprocessing with `sc.pp.pca` and default params.
computing PCA
    with n_comps=50
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-65-c244be664e51> in <module>()
----> 1 sc.tl.tsne(adata, n_pcs = 50)
      2 # UMAP, first with neighbor calculation
      3 sc.pp.neighbors(adata, n_pcs = 50, n_neighbors = 20)
      4 sc.tl.umap(adata)

~/.local/lib/python3.6/site-packages/scanpy/tools/_tsne.py in tsne(adata, n_pcs, use_rep, perplexity, early_exaggeration, learning_rate, random_state, use_fast_tsne, n_jobs, copy)
     78     start = logg.info('computing tSNE')
     79     adata = adata.copy() if copy else adata
---> 80     X = _choose_representation(adata, use_rep=use_rep, n_pcs=n_pcs)
     81     # params for sklearn
     82     params_sklearn = dict(

~/.local/lib/python3.6/site-packages/scanpy/tools/_utils.py in _choose_representation(adata, use_rep, n_pcs, silent)
     41                     'Falling back to preprocessing with `sc.pp.pca` and default params.'
     42                 )
---> 43                 X = pca(adata.X)
     44                 adata.obsm['X_pca'] = X[:, :n_pcs]
     45         else:

~/.local/lib/python3.6/site-packages/scanpy/preprocessing/_pca.py in pca(data, n_comps, zero_center, svd_solver, random_state, return_info, use_highly_variable, dtype, copy, chunked, chunk_size)
    199 
    200         output = _pca_with_sparse(
--> 201             X, n_comps, solver=svd_solver, random_state=random_state
    202         )
    203         # this is just a wrapper for the results

~/.local/lib/python3.6/site-packages/scanpy/preprocessing/_pca.py in _pca_with_sparse(X, npcs, solver, mu, random_state)
    298         shape=X.shape,
    299         rmatvec=rmatvec,
--> 300         rmatmat=rmatmat,
    301     )
    302 

/usr/local/anaconda/lib/python3.6/site-packages/scipy/sparse/linalg/interface.py in __new__(cls, *args, **kwargs)
    131         if cls is LinearOperator:
    132             # Operate as _CustomLinearOperator factory.
--> 133             return _CustomLinearOperator(*args, **kwargs)
    134         else:
    135             obj = super(LinearOperator, cls).__new__(cls)

TypeError: __init__() got an unexpected keyword argument 'rmatmat'
```

**Comment by ivirshup** [comment]
Could you update your scipy with `pip install -U scipy`?

**Comment by iSinedeus** [comment]
When I do this it tells me I am using version 1.4.1 but when I run sc.logging.print_versions() it comes up as version 1.01. I assumed this is somehow related to the version installed with scanpy that it uses by default maybe? But I feel I am not proficient enough in python to determine that

**Comment by ivirshup** [comment]
Huh. It sounds like `pip` is installing to a different environment than the one you're using for scanpy. How are you starting the relevant python session? Also, are you sure you're restarted that session after updating scipy?

To check to see if you're in the same environment, these commands should tell you where scipy is installed:

```sh
pip show scipy

python -c "import scipy; print(scipy.__file__)"
```

**Comment by iSinedeus** [comment]
When I input pip show scipy I get:

Name: scipy
Version: 1.4.1
Summary: SciPy: Scientific Library for Python
Home-page: https://www.scipy.org
Author: None
Author-email: None
License: BSD
Location: /home/ubuntu/.local/lib/python3.6/site-packages
Requires: numpy
Required-by: umap-learn, statsmodels, scikit-learn, scanpy, xgboost, seaborn, mnnpy, loompy, Keras, Keras-Preprocessing, ggplot, gensim, anndata
You are using pip version 18.0, however version 20.2b1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

Typing in pip show scanpy returns:
Name: scanpy
Version: 1.5.1
Summary: Single-Cell Analysis in Python.
Home-page: http://github.com/theislab/scanpy
Author: Alex Wolf, Philipp Angerer, Fidel Ramirez, Isaac Virshup, Sergei Rybakov, Gokcen Eraslan, Tom White, Malte Luecken, Davide Cittaro, Tobias Callies, Marius Lange, Andrés R. Muñoz-Rojas
Author-email: f.alex.wolf@gmx.de, philipp.angerer@helmholtz-muenchen.de
License: BSD
Location: /home/ubuntu/.local/lib/python3.6/site-packages
Requires: packaging, h5py, joblib, legacy-api-wrap, tqdm, seaborn, setuptools-scm, statsmodels, numba, matplotlib, scipy, patsy, networkx, tables, natsort, pandas, umap-learn, scikit-learn, importlib-metadata, anndata
Required-by: 
You are using pip version 18.0, however version 20.2b1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

I have to use !pip install scanpy --user
when starting my session to have it work properly so I thought maybe it was an issue of being in a different directory but based on the location of each package when I look them up that doesn't appear to be the case? I tried using !pip install scipy -U --user but it tells me that the updated version is already present. sc.logging.print_versions() still shows scipy 1.0.1 as the version so I'm a bit confused. Is scanpy somehow defaulting to a different version for some reason? Is there a way to make it use the correct version?

**Comment by ivirshup** [comment]
That you are calling `!pip install scanpy --user` in your session definitely suggest you are not using the same environment as you were installing to before.

I don't think I can help too much with this, since it sounds like there are some deeper problems with your python environment. Looking back at the traceback from your previous example, it looks like your environment is in a very strange state. You're using `scanpy` installed to your user python site packages, but importing `scipy` that's been installed via `conda`.

If I were you, I think I would just try uninstalling everything and starting a new environment from scratch, possibly all through `conda`.

**Comment by iSinedeus** [comment]
It appears this was an issue related to anndata2ri- scipy 1.0.1 was being installed when installing anndata2ri. Installing scanpy first prevented this issue. 
I use pip install --user for scanpy because otherwise I receive an error message: 
Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
My workaround has been to use --user as a directory and add a path to import scanpy.
I'm sorry for the trouble thank you for the help.

**Comment by redafekry** [comment]
File "C:\Users\Reda\Anaconda3\lib\site-packages\hdbscan\hdbscan_.py", line 941, in fit_predict
    self.fit(X)
  File "C:\Users\Reda\Anaconda3\lib\site-packages\hdbscan\hdbscan_.py", line 919, in fit
    self._min_spanning_tree) = hdbscan(X, **kwargs)
  File "C:\Users\Reda\Anaconda3\lib\site-packages\hdbscan\hdbscan_.py", line 615, in hdbscan
    core_dist_n_jobs, **kwargs)
  File "C:\Users\Reda\Anaconda3\lib\site-packages\joblib\memory.py", line 352, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\Reda\Anaconda3\lib\site-packages\hdbscan\hdbscan_.py", line 274, in _hdbscan_boruvka_kdtree
    tree = KDTree(X, metric=metric, leaf_size=leaf_size, **kwargs)
  File "sklearn\neighbors\_binary_tree.pxi", line 1061, in sklearn.neighbors._kd_tree.BinaryTree.__init__
  File "sklearn\neighbors\_dist_metrics.pyx", line 289, in sklearn.neighbors._dist_metrics.DistanceMetric.get_metric
TypeError: __init__() got an unexpected keyword argument 'check_pickle'

How to fix this error?
