### ISSUE TITLE
multiple Visium sections in one adata object does not work with `sc.pl.spatial(img_key=None)`

### ISSUE THREAD

**Issue by vitkl** [scverse/scanpy#1254]
Does `scanpy==1.5.1` support multiple sections in one adata object? If I concatenate several anndata object I can't plot even with `sc.pl.spatial(img_key=None)`.

Try concatenating 3 mouse brain adata object and plotting:
```python
adata = adata1.concatenate([obj2, obj3], index_unique=None)
sc.pl.spatial(adata[adata.obs["sample"]==adata.obs["sample"].unique()[0], :], 
              color=["Rorb", "Vip"], img_key=None,
              vmin=0, cmap='magma',
              gene_symbols='SYMBOL')
```

This is the error I get:
```pytb
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-9-8c84185773ec> in <module>
      6               color=["Rorb", "Vip"], img_key=None,
      7               vmin=0, cmap='magma', #vmax=3.8,
----> 8               gene_symbols='SYMBOL'
      9              )

/nfs/team283/vk7/software/miniconda3farm5/envs/cellpymc/lib/python3.7/site-packages/scanpy/plotting/_tools/scatterplots.py in spatial(adata, img_key, library_id, crop_coord, alpha_img, bw, size, **kwargs)
    765     """
    766     if library_id is _empty:
--> 767         library_id = next((i for i in adata.uns['spatial'].keys()))
    768     else:
    769         if library_id not in adata.uns['spatial'].keys():

KeyError: 'spatial'
```

#### Versions:
scanpy==1.5.1 anndata==0.7.1 umap==0.3.10 numpy==1.17.3 scipy==1.4.1 pandas==0.25.3 scikit-learn==0.22.1 statsmodels==0.10.2 python-igraph==0.7.1 louvain==0.6.1 leidenalg==0.7.0

**Comment by ivirshup** [comment]
Much of the spatial data is stored in `uns`, which does not get combined by default.

There is an example of concatenating visium datasets [in the tutorial](https://scanpy-tutorials.readthedocs.io/en/latest/spatial/integration-scanorama.html#Data-integration) and more information on concatenating `.uns` [in the latest anndata docs](https://anndata.readthedocs.io/en/latest/concatenation.html#merging-uns).

**Comment by vitkl** [comment]
Nice, thanks for pointing me to that tutorial! Still would be good if plotting worked without `uns`.

**Comment by vitkl** [comment]
I get an error trying to merge multiples slides using the code in the tutorial. Is it possible to install the scanpy version the tutorial is using?

```python
adata = adata.concatenate(
    list(slides.values()),
    batch_key="sample",
    uns_merge="unique",
    batch_categories=list(sample_data['sample_name'].values), 
    index_unique=None
)
```

```pytb
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-fe8a54a66c17> in <module>
     40     uns_merge="unique",
     41     batch_categories=list(sample_data['sample_name'].values),
---> 42     index_unique=None
     43 )
     44 

TypeError: concatenate() got an unexpected keyword argument 'uns_merge'
```

**Comment by ivirshup** [comment]
I think you'll want to update your version of anndata for that.

**Comment by vitkl** [comment]
Nice, anndata==0.7.3 works. Thanks!

**Comment by ivirshup** [comment]
No problem!
