### ISSUE TITLE
Can't install fa2 in Windows 10

### ISSUE THREAD

**Issue by JayalalKJ** [scverse/scanpy#1256]
Hi.
I have a problem to install fa2 (pip install fa2) in windows 10 operating system and I am using python 3.7 version? 

Using Conda env 

**sc.tl.draw_graph(ds, init_pos='paga'),**
**drawing single-cell graph using layout 'fa'
WARNING: Package 'fa2' is not installed, falling back to layout 'fr'.To use the faster and better ForceAtlas2 layout, install package 'fa2' (`pip install fa2`).**

installation error

Collecting fa2
  Using cached fa2-0.3.5.tar.gz (435 kB)
Requirement already satisfied: numpy in c:\programdata\miniconda3\envs\jayalal_2_miniconda\lib\site-packages (from fa2) (1.18.4)
Requirement already satisfied: scipy in c:\programdata\miniconda3\envs\jayalal_2_miniconda\lib\site-packages (from fa2) (1.4.1)
Requirement already satisfied: tqdm in c:\programdata\miniconda3\envs\jayalal_2_miniconda\lib\site-packages (from fa2) (4.46.0)
Building wheels for collected packages: fa2
  Building wheel for fa2 (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\ProgramData\Miniconda3\envs\Jayalal_2_Miniconda\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xkalaj\\AppData\\Local\\Temp\\pip-install-golo7r_8\\fa2\\setup.py'"'"'; __file__='"'"'C:\\Users\\xkalaj\\AppData\\Local\\Temp\\pip-install-golo7r_8\\fa2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\xkalaj\AppData\Local\Temp\pip-wheel-yjh93oit'
       cwd: C:\Users\xkalaj\AppData\Local\Temp\pip-install-golo7r_8\fa2\
  Complete output (30 lines):
  Installing fa2 package (fastest forceatlas2 python implementation)

  >>>> Cython is installed?
  Yes

  >>>> Starting to install!

  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\fa2
  copying fa2\fa2util.py -> build\lib.win-amd64-3.6\fa2
  copying fa2\forceatlas2.py -> build\lib.win-amd64-3.6\fa2
  copying fa2\__init__.py -> build\lib.win-amd64-3.6\fa2
  running egg_info
  writing fa2.egg-info\PKG-INFO
  writing dependency_links to fa2.egg-info\dependency_links.txt
  writing requirements to fa2.egg-info\requires.txt
  writing top-level names to fa2.egg-info\top_level.txt
  reading manifest file 'fa2.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'fa2.egg-info\SOURCES.txt'
  copying fa2\fa2util.c -> build\lib.win-amd64-3.6\fa2
  copying fa2\fa2util.pxd -> build\lib.win-amd64-3.6\fa2
  running build_ext
  skipping 'fa2\fa2util.c' Cython extension (up-to-date)
  building 'fa2.fa2util' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for fa2
  Running setup.py clean for fa2
Failed to build fa2
Installing collected packages: fa2
    Running setup.py install for fa2 ... error

  ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Miniconda3\envs\Jayalal_2_Miniconda\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xkalaj\\AppData\\Local\\Temp\\pip-install-golo7r_8\\fa2\\setup.py'"'"'; __file__='"'"'C:\\Users\\xkalaj\\AppData\\Local\\Temp\\pip-install-golo7r_8\\fa2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\xkalaj\AppData\Local\Temp\pip-record-y21s2idm\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\ProgramData\Miniconda3\envs\Jayalal_2_Miniconda\Include\fa2'
         cwd: C:\Users\xkalaj\AppData\Local\Temp\pip-install-golo7r_8\fa2\
    Complete output (30 lines):
    Installing fa2 package (fastest forceatlas2 python implementation)

    >>>> Cython is installed?
    Yes

    >>>> Starting to install!

    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\fa2
    copying fa2\fa2util.py -> build\lib.win-amd64-3.6\fa2
    copying fa2\forceatlas2.py -> build\lib.win-amd64-3.6\fa2
    copying fa2\__init__.py -> build\lib.win-amd64-3.6\fa2
    running egg_info
    writing fa2.egg-info\PKG-INFO
    writing dependency_links to fa2.egg-info\dependency_links.txt
    writing requirements to fa2.egg-info\requires.txt
    writing top-level names to fa2.egg-info\top_level.txt
    reading manifest file 'fa2.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'fa2.egg-info\SOURCES.txt'
    copying fa2\fa2util.c -> build\lib.win-amd64-3.6\fa2
    copying fa2\fa2util.pxd -> build\lib.win-amd64-3.6\fa2
    running build_ext
    skipping 'fa2\fa2util.c' Cython extension (up-to-date)
    building 'fa2.fa2util' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\ProgramData\Miniconda3\envs\Jayalal_2_Miniconda\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xkalaj\\AppData\\Local\\Temp\\pip-install-golo7r_8\\fa2\\setup.py'"'"'; __file__='"'"'C:\\Users\\xkalaj\\AppData\\Local\\Temp\\pip-install-golo7r_8\\fa2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\xkalaj\AppData\Local\Temp\pip-record-y21s2idm\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\ProgramData\Miniconda3\envs\Jayalal_2_Miniconda\Include\fa2' Check the logs for full command output

**Comment by giovp** [comment]
hi @JayalalKJ , it's best if this question is addressed in the original repository https://github.com/metgem/forceatlas2
I'll close this for the moment

**Comment by hyjforesight** [comment]
install cython in anaconda jupyter lab for installing fa2
!pip install Cython

this scanpy trajectory tutorial needs package 'fa2' (not 'forceatlas2'), otherwise the plot made by sc.pl.draw_graph() is not right

install method 1
open Anaconda Powershell Promopt
> conda activate Py36R36 (Py36R36 is the enviroment you create in anaconda for scanpy)
> conda install -c conda-forge fa2
open Anaconda navigator
choose Py36R36
open Jupyter Lab
run scanpy trajectory

install method 2
open Anaconda navigator
choose Py36R36
open Jupyter Lab
open Terminal in Jupyter Lab
> conda install -c conda-forge fa2
run scanpy trajectory
