### ISSUE TITLE
Pip failed in the step 1

### ISSUE THREAD

**Issue by JayalalKJ** [scverse/scanpy#1257]
To set up a conda environment, the following instructions must be followed.

1.  Set up the conda environment from the sc_tutorial_environment.yml file.
conda env create -f sc_tutorial_environment.yml

![image](https://user-images.githubusercontent.com/40278254/83300088-a7a7af80-a1f7-11ea-88de-e8a1fe010dd7.png)

**Comment by picciama** [comment]
Assuming you're on a debian based linux, please check the following:
- `echo $PATH` shows your PATH variable.
- `which git` shows you the location of your git installation. If nothing is shown, you need to install it.
- `apt install git` if you haven't installed it yet.

**Comment by giovp** [comment]
thanks @picciama for answering this, will close this now.
