### ISSUE TITLE
Calculate neighbors with select principle components

### ISSUE THREAD

**Issue by ktravaglini** [scverse/scanpy#1267]
https://github.com/theislab/scanpy/blob/e33a2f338a4c63c794fe4bc5e03471d7c487cada/scanpy/tools/_utils.py#L52

Would it be possible to tweak this section so you can pass a list of principle components (e.g. [1,3,5,7]) when calculating neighbors?

**Comment by Koncopd** [comment]
Hi, you can always do
```
adata.obsm['X_pca_select'] = adata.obsm['X_pca'][:, [1,3,5,7]]
sc.pp.neighbors(adata, use_rep='X_pca_select')
```
