### ISSUE TITLE
Did newer versions change function names???

### ISSUE THREAD

**Issue by brianpenghe** [scverse/scanpy#1268]
I noticed that the pbmc tutorial changed a lot:
sc.pp.normalize_total
.var_names_make_unique()...
sc.pl.violin(adata, ['n_genes_by_counts', 'total_counts', 'pct_counts_mt'],
             jitter=0.4, multi_panel=True)

Is Scanpy going to change the names of its functions a lot? Why is that?

**Comment by giovp** [comment]
Sorry but the question is not clear. The plotting functions underwent a refactoring recently but that one should still work no? I'll close this for the moment, feel free to reopen it but please do so with a reproducible example, thank you!
