### ISSUE TITLE
.uns colors deleted??

### ISSUE THREAD

**Issue by brianpenghe** [scverse/scanpy#1269]
I copied a subset of adata into bdata, converted bdata to dataframe and plotted heatmap using Seaborn.
But when I checked adata again I realized that its .uns colors are gone (but log1p is still there)!

So there must be something that links adata and bdatas, and something that deletes the colors stored in .uns 

I'm using Scanpy 1.5.0 

Any suggestions?

**Comment by giovp** [comment]
this was probably fixed in https://github.com/theislab/anndata/pull/388 closing for now
