### ISSUE TITLE
sc.pl.violin ylabel and title

### ISSUE THREAD

**Issue by davidsebfischer** [scverse/scanpy#127]
I think it would be usedul to allow for manual setting of ylabel and title through the parameter list of sc.pl.violin()

**Comment by falexwolf** [comment]
Quick workaround: 
```
ax = sc.pl.violin(adata, show=False)
ax.set_title(..)
ax.set_ylabel(...)
pl.show()
```

**Comment by davidsebfischer** [comment]
Thanks!
and workaround for multipanel lists with some list of ids (called hgnc) and the corresponding ids used in adata.var_names (called ens here)
axs = sc.pl.violin(adata, keys=ensg, show=False)
for i,ax in enumerate(axs):
    ax.set_ylabel(hgnc[i])
plt.show()
