### ISSUE TITLE
pseudotime analysis on Seurat result

### ISSUE THREAD

**Issue by BenxiaHu** [scverse/scanpy#1272]
Hi,
   I used Seurat v3 to analyze scRNA-seq. Now I have obtained 5 clusters. But I can not define the cell-types without marker genes. My question is that how can I apply scanpy on those 5 clusters to analyze pseudotime?
Best,

**Comment by giovp** [comment]
Hi @benxiahu I invite you to have a look at the tutorial here: https://scanpy.readthedocs.io/en/stable/tutorials.html and discussions on the topics in our discourse channel https://scanpy.discourse.group/
Hope those pointers are useful!
Will close this for now
