### ISSUE TITLE
adata.write() -> cannot save

### ISSUE THREAD

**Issue by mvinyard** [scverse/scanpy#1275]
...Trying to use `adata.write()` to save a results file - running into the same issue over and over. I tried uninstalling and reinstall both scanpy as well as h5py. 

```
results_file = 'NG2019_MCF10A2.h5ad'
adata.write(results_file)
```

```
OSError: Unable to create link (name already exists)

Above error raised while writing key 'genes' of <class 'h5py._hl.group.Group'> from /.

Above error raised while writing key 'genes' of <class 'h5py._hl.group.Group'> from /.

Above error raised while writing key 'raw/var' of <class 'h5py._hl.files.File'> from /.
...
```

#### Versions:

> ...

**Comment by ivirshup** [comment]
Could you report your version numbers? Could you also show us the `repr` of your anndata object?

**Comment by mvinyard** [comment]
<img width="596" alt="Screen Shot 2020-06-19 at 8 10 37 AM" src="https://user-images.githubusercontent.com/47393421/85131254-6e65cc80-b204-11ea-9479-0551f05407ee.png">
<img width="1265" alt="Screen Shot 2020-06-19 at 8 10 52 AM" src="https://user-images.githubusercontent.com/47393421/85131263-7160bd00-b204-11ea-9a16-3741733ed919.png">

**Comment by ivirshup** [comment]
Oh, by version numbers I meant not just `anndata` but the dependencies as well. I'm wondering in particular about the version of `h5py`. The output of something like [`sinfo(dependencies=True)`](https://pypi.org/project/sinfo/) would be great

If you try writing to a different path, are you able too? It kind of looks like you're writing to a file that already exists, though that should just overwrite the file.

**Comment by mvinyard** [comment]
I am not sure what was causing this error, but it must be somewhat idiosyncratic as the issue is resolved in a fresh env. Thanks! Closing this.

**Comment by GouQiao** [comment]
> I am not sure what was causing this error, but it must be somewhat idiosyncratic as the issue is resolved in a fresh env. Thanks! Closing this.
Hi, I met same problem, how did you solve it?

**Comment by mvinyard** [comment]
Hi @GouQiao - it's been a while since this specific incident so I don't 100% remember / have the code anymore. However, I have run into this problem in general when using AnnData and it's usually resolved by one of two paths:

1. Check the version of `h5py` that you have installed and perhaps it is too new and an older version resolves the issue. 
2. Some components of AnnData are not implemented in the function, `.write_h5ad()`. One example that comes to mind is the umap or pca transformer. These objects are not handled well by `.h5py` (at least natively in my experience) and are better off saved independently as dictionaries using `pickle`. That being said, I think there is probably a more robust solution I am not aware of - I know in several instances transformers are able to be saved (e.g., the Scanpy tutorials). 

Does this help at all? Happy to be of further assistance if possible.

**Comment by liliay** [comment]
HI everyone,

Going through the exact same issue, BUT what you suggested does not work for me : 
1. h5py version I have allows me to save a different integrated dataset  in the same environment with the h5py==3.6.0
2. When comparing the Anndata structure / content of the 2 objects I am working on (the one i am failing to save vs. the one I have saved successfully) "pca" and "umap" are in both as you can tell from the screenshots.
![BBKNN_anndata_struct](https://user-images.githubusercontent.com/45742503/148416117-be1fe7cb-d24c-40bb-b04a-128aa2913489.png)
![mnn_corr_data_struct](https://user-images.githubusercontent.com/45742503/148416118-8992174d-c1ff-4cbe-9356-dd22f62dc440.png)


@GouQiao did you find a way to solve this ? 
Thank you @mvinyard for sharing your solution tho !

**Comment by liliay** [comment]
> 

1st screen (52844 x 1340) is the one for which the writing does not work...
