### ISSUE TITLE
Request: ability to set vmin / vmax in sc.pl.scatter()

### ISSUE THREAD

**Issue by sjfleming** [scverse/scanpy#1276]
I would love it if I could specify a `vmax` argument to `scanpy.pl.scatter()`, and have the color axis limited to that value.  (This was easy in scanpy 1.4.4.post1 where you could specify this in `plot_scatter()` from `from scanpy.plotting._tools import plot_scatter`, but things seem to be very differently reorganized now in scanpy 1.5.1)

**Comment by gokceneraslan** [comment]
Hi Stephen, I think https://scanpy.readthedocs.io/en/stable/api/scanpy.pl.embedding.html#scanpy.pl.embedding is what you are looking for.

**Comment by gokceneraslan** [comment]
There is also some relevant discussion at https://github.com/theislab/scanpy/issues/617.

**Comment by sjfleming** [comment]
Thanks so much!  I think that's exactly what I was looking for
