### ISSUE TITLE
Adding to the scanpy ecosystem

### ISSUE THREAD

**Issue by Marius1311** [scverse/scanpy#1282]
Hi all, there are three packages I would like to suggest adding to the [scanpy ecosystem](https://scanpy.readthedocs.io/en/stable/ecosystem.html):

- [CellRank](https://cellrank.readthedocs.io/en/latest/): computing root, final and intermediate metastable states as well as lineage probabilities bases on RNA velocity. Fully compatible with scanpy and scvelo, well documented and scales to large cell numbers
- [scachepy](https://github.com/theislab/scachepy): caching the output of expensive scanpy/scvelo computations. Works with different backends (pickle etc). This is handy in a typical data analysis workflow where I have a couple of commands in my jupyter notebook which take very long to compute. This is more convenient then storing each attribute manually (many scanpy commands write to different `AnnData` attributes`) and more memory efficient than saving the entire `AnnData` object
- [interactive plotting](https://github.com/theislab/interactive_plotting): offers a set of interactive plotting functions based on bokeh and holoviews. Fully compatible with scanpy and scales to large cell numbers thanks to holoviews. Basically, it's a way to interactively work with your data from within a jupyter notebook. 

Involved in the development of these three projects are @VolkerBergen , @michalk8  and myself.

**Comment by ivirshup** [comment]
That sounds like a good idea. Could you make a PR for this?

**Comment by Marius1311** [comment]
@ivirshup thanks for getting back to me, sure, will do. @michalk8 , could you take care of this? I would add three new subheadings to the `ecosystem` page in the docs, "Caching", "Interactive Plotting" and "Fate mapping" where I would link the respective packages.
