### ISSUE TITLE
Louvain module not found when using vtraag flavor

### ISSUE THREAD

**Issue by jamiexie** [scverse/scanpy#1283]
Hi I'm trying to run Louvain clustering but I'm getting a module not found error

```python
sc.tl.louvain(dge_E, flavor='vtraag', resolution=0.5
```

```pytb
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-43-d2a2f7b009fa> in <module>
----> 1 sc.tl.louvain(dge_E, flavor='vtraag', resolution=0.5)

c:\users\jamie\appdata\local\programs\python\python37\lib\site-packages\scanpy\tools\_louvain.py in louvain(adata, resolution, random_state, restrict_to, key_added, adjacency, flavor, directed, use_weights, partition_type, partition_kwargs, neighbors_key, obsp, copy)
    135             weights = None
    136         if flavor == 'vtraag':
--> 137             import louvain
    138             if partition_type is None:
    139                 partition_type = louvain.RBConfigurationVertexPartition

ModuleNotFoundError: No module named 'louvain'
```

#### Versions:

> ...

**Comment by LuckyMD** [comment]
just use `pip install louvain` to install the louvain package and use this functionality. 

@ivirshup @flying-sheep I noticed that the louvain install suggestion in the documentation has been replaced by a `pip install scanpy[leiden]` suggestion. However `louvain` is still the default in the tutorials. Maybe the louvain install should be added again?

**Comment by jamiexie** [comment]
Great that worked, thanks!

**Comment by onegoodguy-tnt** [comment]
zuozhebujiangwude,xiedaimabuxiubug

**Comment by Emiri-W** [comment]
I also have the same problem and I tried to use `pip install louvain`, but I cannot install the package and it says `legacy-install-failure`. The GitHub for the [louvain](https://github.com/vtraag/louvain-igraph/tree/master) says,

> Warning
> 
> This package has been superseded by the [leidenalg](https://github.com/vtraag/leidenalg) package and will no longer be maintained.

**Comment by flying-sheep** [comment]
Check out scanpy’s optional features:

https://github.com/scverse/scanpy/blob/21ca328672646d7d0ba42b64eee2823babc2d2ed/pyproject.toml#L133-L145

as you can see `scanpy[louvain]` will install it, while `scanpy[leiden]` will install the successor.

**Comment by Emiri-W** [comment]
Thank you for the comment. Do you mean these packages will be installed when we install Scanpy? Sorry that I don't understand. When I try to use `scanpy.tl.louvain`, it says `ModuleNotFoundError: No module named 'louvain'`, and I don't know how to solve it.

**Comment by flying-sheep** [comment]
As said: `pip install scanpy[leiden]`, and use `scanpy.tl.leiden()` instead.

See here for how to install scanpy and its dependencies: https://scanpy.readthedocs.io/en/stable/installation.html

**Comment by Emiri-W** [comment]
Do you mean that If I want to do use `scanpy.tl.louvain`, I can use `scanpy.tl.leiden` instead? I can `pip install scanpy[leiden]` but it will not change the error message in `scanpy.tl.louvain` with option `flavor='vtraag'`.

When I try `pip install scanpy[louvain]`, it has the error `legacy-install-failure`.

**Comment by flying-sheep** [comment]
louvain is deprecated. leiden is its successor. So unless you want compare different community detection methods, you should use leiden instead of louvain.

Just leave out the `flavor`.

**Comment by Emiri-W** [comment]
I understand that leiden is the newer method, but I want to reproduce the old analysis that is already done in the paper I am looking.

I will use diffenret `flavor` if I want to use louvain for now. Thank you for all the comment.
