### ISSUE TITLE
Probably wrong distance matrix used in sc.tl.dendrogram

### ISSUE THREAD

**Issue by jingxinfu** [scverse/scanpy#1288]
In the `sc.tl.dendrogram` module, I noticed that the correlation matrix was directly inputted into the `scipy.cluster.hierarchy.linkage`. That results in calculating the distance between samples by the Euclidean(X1_cor_with_others, X2_cor_with_others). Shouldn't the distance be the pure correlation value here? Please correct me if I didn't understand it correctly.

The one I would perfer
```python
df = 1-adata.uns['dendrogram_sample']['correlation_matrix']
data_linkage = hierarchy.linkage(ssd.squareform(
        df)
...
```
The one currently in sc.tl.dendrogram
```python
data_linkage = hierarchy.linkage(adata.uns['dendrogram_sample']['correlation_matrix'])
...
```

```pytb
...
```

#### Versions:

> ...

**Comment by giovp** [comment]
mmh true that should probably be 1-corr_matrix. I'll ping @flying-sheep he might have a better answer
