### ISSUE TITLE
documentation error for pl.violin

### ISSUE THREAD

**Issue by rboiarsky** [scverse/scanpy#1294]
In the documentation (https://scanpy.readthedocs.io/en/stable/api/scanpy.plotting.html) the figure given as an example for pl.violin does not match the actual output of pl.violin (rather, it's showing a stacked violin). If there's a more appropriate place for me to record errors in the documentation, please let me know. Thanks!

**Comment by rboiarsky** [comment]
sorry i think the bug label was a bit dramatic -- was choosing between the options presented and none really fit -- but now I don't see any way for me to change it.

**Comment by fidelram** [comment]
Thanks for pointing this out.

**Comment by fidelram** [comment]
Fixed in #1316
