### ISSUE TITLE
The legend overlap with figures in plot function 

### ISSUE THREAD

**Issue by YubinXie** [scverse/scanpy#1312]
When multiple plots in one figure, if the legend of one figure is comprehensive, there is no space left for the legend to be shown. The scanpy just overlap the next plot on it.

![25AD7E00-E9A8-4CC6-A347-C4C76177F770](https://user-images.githubusercontent.com/16257776/86968887-e0ae3a80-c13a-11ea-805c-8620a9557087.png)

```python
sc.pl.umap(adata, color=['sample_id','IMPACT_TMB']) 
```

**Comment by LuckyMD** [comment]
Hi @YubinXie ,

You can fix this by setting the `wspace` parameter in the plot.

**Comment by YubinXie** [comment]
> Hi @YubinXie ,
> 
> You can fix this by setting the `wspace` parameter in the plot.

Thank you for your quick response! Is there a way to do any automatic adjustments? something like tight_layout? Thanks!

**Comment by LuckyMD** [comment]
As far as I'm aware, this is currently not implemented. But @fidelram can say more here.

**Comment by fidelram** [comment]
It is difficult to find a one-size-fits-all solution. Depending on the number of legends, the length of the labels and the DPI used the space required will vary. Thus, I think is is better for the user to adjust the plots.

**Comment by flying-sheep** [comment]
I think it’s just a limitation in matplotlib. There’s no autoadjustment here. It would be great if there was anything that worked like a HTML table, i.e. that makes sure the plot areas are aligned and there’s just enough space for the widest/highest annotation.

But AFAIK there isn’t: You can select one gap width and that’s it.

**Comment by gokceneraslan** [comment]
Has anyone explored the new constrained layout https://matplotlib.org/3.1.1/tutorials/intermediate/constrainedlayout_guide.html ? it looks like there is a better layout manager this time, I wonder if we can take advantage of it.

**Comment by flying-sheep** [comment]
Yeah, sorry, that’s what my above comment was about.

**Comment by gokceneraslan** [comment]
This is different than tight layout and relatively new though, are you sure that it doesn't really help us at all?

**Comment by flying-sheep** [comment]
Not 100% of course, I could have overlooked something, but I couldn’t find a way to get it to do what we want. And yes, I am sure I’m talking about the new constrained layout.

**Comment by honghh2018** [comment]
Same question, had any advice for fix this issue?

**Comment by flying-sheep** [comment]
yeah: create a GridSpec ([examples](https://matplotlib.org/stable/gallery/userdemo/demo_gridspec03.html#sphx-glr-gallery-userdemo-demo-gridspec03-py)) and manage the gaps manually.

Then create your plots individually like

```py
for col, ax in zip(['sample_id', 'IMPACT_TMB'], axes):
    sc.pl.umap(adata, color=col, ax=ax)
```
