### ISSUE TITLE
get.obs_df and get.var_df produce an error when there is only 1 key

### ISSUE THREAD

**Issue by Mkebede** [scverse/scanpy#1315]
When trying to get the obs_df or the var_df, the function throws an error when there is a single key. In this case it iterates through the letters in the given key and causes a KeyError. 

```
pbmc = sc.datasets.pbmc68k_reduced()
sc.get.obs_df(pbmc, keys=('HES4'))
sc.get.var_df(pbmc, keys=('AAAGCCTGGCTAAC-1'))
```

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-60-663347265b80> in <module>
----> 1 sc.get.var_df(pbmc, keys=('AAAGCCTGGCTAAC-1'))

~/.conda/envs/scvelo_updated/lib/python3.8/site-packages/scanpy/get.py in var_df(adata, keys, varm_keys, layer)
    223             not_found.append(key)
    224     if len(not_found) > 0:
--> 225         raise KeyError(
    226             f"Could not find keys '{not_found}' in columns of `adata.var` or"
    227             " in `adata.obs_names`."

KeyError: "Could not find keys '['A', 'A', 'A', 'G', 'C', 'C', 'T', 'G', 'G', 'C', 'T', 'A', 'A', 'C', '-', '1']' in columns of `adata.var` or in `adata.obs_names`."
```

#### Versions:

> scanpy==1.5.1 anndata==0.7 umap==0.4.4 numpy==1.19.0 scipy==1.5.0 pandas==1.0.5 scikit-learn==0.23.1 statsmodels==0.11.1 python-igraph==0.8.2 louvain==0.7.0

**Comment by ivirshup** [comment]
In python `('HES4')` parses as a string, not as a tuple. You'd have to put `('HES4',)` to get a tuple, while you could write `['HES4']` to get a list.

The behavior here could be more straight-forward, but you should be able to get what you want by passing an iterable of strings.

**Comment by Mkebede** [comment]
that makes sense, thank you for the prompt response!
