### ISSUE TITLE
read_10x_h5 errors

### ISSUE THREAD

**Issue by Fougere87** [scverse/scanpy#132]
Hi, 
I can't manage to use the scanpy  read_10x_h5 errors as it raises an exception for the genome I want to use : 
`Exception: Genome GRCm38 does not exist in this file.`
But I'm sure it's this genome string in my file. 

Reading the same file with  
`mol_info = sc.read_hdf("./molecule_info.h5", key="genome_ids" )`
I obtain this error : `ValueError: could not convert string to float: 'GRCm38'`

Do you have any hint oin how to have it working ???
Thanks a lot !!

**Comment by falexwolf** [comment]
Hey, this is really strange... Can you, in your notebook, run
```
!h5ls ./molecule_info.h5
```
This should give you the output `GRCm38` if it's in the file. I have only seen 10x files that have the default genome `mm10` up to now... 

PS: On a command line, you'd do
```
h5ls ./molecule_info.h5
```

**Comment by Fougere87** [comment]
Hi and thank you for your answer !
 Actually I made a confusion between molecule_info.h5 and the count matrix in h5 format ! That's why it doesn't work !! It works fine with the count matrix if I provide GRCm38 as the genome ID !
