### ISSUE TITLE
AttributeError: module 'scanpy' has no attribute 'anndata'

### ISSUE THREAD

**Issue by AllenWu18** [scverse/scanpy#1322]
The bug is just like the title of issue, _AttributeError: module 'scanpy' has no attribute 'anndata'_, for I just wanna to load a h5ad file from Tabula-Muris dataset

```python
import scanpy as sc

data = sc.anndata.read_h5ad(''tabula-muris-senis-facs-processed-official-annotations-Bladder.h5ad')
```

```pytb
Traceback (most recent call last):

  File "<ipython-input-91-67a79760d7cb>", line 1, in <module>
    sc.anndata.read_h5ad('tabula-muris-senis-facs-processed-official-annotations-Bladder.h5ad')

AttributeError: module 'scanpy' has no attribute 'anndata'
```
#### Versions:

> scanpy==1.4.3 anndata==0.6.19 umap==0.3.10 numpy==1.14.6 scipy==1.1.0 pandas==0.23.4 scikit-learn==0.20.1 statsmodels==0.9.0 python-igraph==0.7.1 louvain==0.6.1

**Comment by chris-rands** [comment]
You need `sc.read_h5ad()` and not `sc.anndata.read_h5ad()`

**Comment by flying-sheep** [comment]
exactly
