### ISSUE TITLE
filter_rank_genes_groups() does not support rankby_abs

### ISSUE THREAD

**Issue by rboiarsky** [scverse/scanpy#1325]
Here is my use case: I run rank_genes_groups( ) with rankby_abs=True, as I want both upregulated and downregulated marker genes. Then I run filter_rank_genes_groups to set some thresholds, and all my downregulated genes disappear! 

I see two possible solutions
1) rankby_abs should be an argument for the filter_rank_genes_groups function as well; when rankby_abs=True, then min_fold_change should be interpreted as an absolute value threshold.
2) filter_rank_genes_groups should follow the behavior of rank_genes_groups. This could be easily implemented if min_fold_change is always used as an absolute value threshold -- if there are only positive fold changes in the .uns['rank_genes_groups'] slot to begin with, only positive fold changes will be returned, and otherwise, both upregulated and downregulated genes will be returned.

**Comment by rboiarsky** [comment]
I noticed this still isn't fixed in the latest version of scanpy. Is there a reason why not? Does my solution # 2 sound reasonable? I can attempt to create a pull request if so

**Comment by ivirshup** [comment]
Hi @rpeys, sorry for being slow on this.

What are you trying to do exactly? Are you looking to use scanpy plotting features afterwards, or just get tables of genes? If it's the latter, I would suggest using `sc.get.rank_genes_groups_df`, where you can do something like:

```python
de_df = sc.get.rank_genes_groups_df(adata, group="CD8")
de_df.query("abs(logfoldchanges) > 1")
```

You should then be able to use these genes to plot by passing the genes names to `var_names` parameter of the `rank_genes_groups` plotting functions.

To be honest, a lot of us on the team are not really happy with the differential expression API – but also haven't had the time to completely redo it. Progress on this area has generally been slow. @fidelram has commented on `filter_rank_genes_groups` in particular here: https://github.com/theislab/scanpy/pull/1529#issuecomment-738733928.

**Comment by rboiarsky** [comment]
Hi @ivirshup. Thanks for suggesting this workaround - I think that can work for my use case and I will go ahead using your suggestion. 

In the meantime while this is not fixed, I think it might be worthwhile to include a note in the description of the `rankby_abs` argument in `rank_genes_groups` warning users that if they use the filter function afterwards, only upregulated genes will be retained.

**Comment by Koncopd** [comment]
@ivirshup i can add `rankby_abs` to `filter_rank_genes_groups`, i don't think it is problematic.

**Comment by ivirshup** [comment]
@Koncopd, I'm not against that being added.

I think the broader question @fidelram has raised if we should deprecate `filter_rank_genes_groups`, which I'm inclined to agree with.

**Comment by rboiarsky** [comment]
Looks like this fix was made in a 2021 release - thanks! Will close the issue
