### ISSUE TITLE
Summer student from Pinello Lab at Harvard seeking help from Theis Lab

### ISSUE THREAD

**Issue by rebecca-c21** [scverse/scanpy#1326]
I'm unable to complete the [Nestrorowa et al. 2016](https://nbviewer.jupyter.org/github/theislab/paga/blob/master/blood/nestorowa16/nestorowa16.ipynb) paga tutorial. On ln[3] 

```
adata.raw = adata
sc.pp.recipe_weinreb17(adata, log=False)
sc.tl.pca(adata)
```

I keep getting this output:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-bfa4168a87e6> in <module>
      1 adata.raw = adata
----> 2 sc.pp.recipe_weinreb17(adata, log=False)
      3 sc.tl.pca(adata)

/opt/anaconda3/lib/python3.7/site-packages/scanpy/preprocessing/_recipes.py in recipe_weinreb17(adata, log, mean_threshold, cv_threshold, n_pcs, svd_solver, random_state, copy)
     48     )
     49     adata._inplace_subset_var(gene_subset)  # this modifies the object itself
---> 50     X_pca = pp.pca(
     51         pp.zscore_deprecated(adata.X),
     52         n_comps=n_pcs,

AttributeError: module 'scanpy.preprocessing._simple' has no attribute 'pca'
```

Versions:
`scanpy==1.5.1 anndata==0.7.4 umap==0.4.6 numpy==1.18.1 scipy==1.4.1 pandas==1.0.1 scikit-learn==0.22.1 statsmodels==0.11.0 python-igraph==0.8.2 louvain==0.7.0 leidenalg==0.7.0`

**Comment by ivirshup** [comment]
Hey! Just fixed this #1327. It looks like there was an incorrect import. Should be fixed now.

Thanks for the bug report!

**Comment by rebecca-c21** [comment]
Hi! Thank you for the quick response.

I tried running the tutorial just now and got the same `AttributeError`. 
Any information you could afford to share would be greatly appreciated.

**Comment by ivirshup** [comment]
Is this using the development version? The fix hasn't been in a release yet.

**Comment by rebecca-c21** [comment]
This is not using the development version.

**Comment by katherineio** [comment]
Hello! I'm getting the same AttributeError as well. Is the issue on my end or has the fix not been applied yet?

**Comment by LuckyMD** [comment]
The last minor release of Scanpy was version 1.5.1 in the end of May, so it hasn't been released yet. You would need to update scanpy to the development version on master. This can be done via `pip install git+https://www.github.com/theislab/scanpy@master` or by having a local copy of the scanpy repo, updating this and installing from source via `pip install .` :).
