### ISSUE TITLE
explain title please

### ISSUE THREAD

**Issue by galicae** [scverse/scanpy#1347]
Hi,

I was always a bit perplexed by Scanpy's logo (some sort of shrimp? ant?), since the name doesn't make me think of an animal. Would you mind explaining, @falexwolf? Is it, maybe, a pun on "scampi"? Because that would explain it.

thanks,
Niko

**Comment by fidelram** [comment]
Indeed is a pun on `scampi`. I also think that the body segments of the shrimp should resemble single cell clustering

![image](https://user-images.githubusercontent.com/4964309/89010761-7fc7eb80-d30f-11ea-9eda-616cd9661055.png)

**Comment by flying-sheep** [comment]
Yeah, Alex came up with the name and I came up with the idea to make the logo a shrimp. I think it was the logo’s designer [Daniela Barreto from südakzente](http://suedakzente.de/) who came up with the body-segments-are-cells idea, but it might also have been one of us, as we were floating ideas about combining something techy with something biological in the logo.

The logo page is here btw: https://scverse.org/scanpy/

**Comment by galicae** [comment]
great responses, thanks for closing the issue @flying-sheep.

**Comment by yubin-ai** [comment]
thanks for the question and the answer. I have been interpreting the logo as an ant for 7 years.
