### ISSUE TITLE
Are there paramters fixing range of colorbar in scanpy.pl.umap?

### ISSUE THREAD

**Issue by CadenZhao** [scverse/scanpy#1352]
- [x] Additional function parameters / changed functionality / changed defaults?
- [ ] New analysis tool: A simple analysis tool you have been using and are missing in `sc.tools`?
- [ ] New plotting function: A kind of plot you would like to seein `sc.pl`?
- [ ] External tools: Do you know an existing package that should go into `sc.external.*`?
- [ ] Other?

When we visualize gene expression, range of colorbar can be different.

![image](https://user-images.githubusercontent.com/30337666/89102749-a6d10b00-d43e-11ea-99f7-0867f3c31d13.png)

Usually, it's fine. But if we want to compare gene expression in control-treat experiment in single-cell level, sometimes this happens.

![image](https://user-images.githubusercontent.com/30337666/89102998-08927480-d441-11ea-9068-3d7f09ab26a3.png)![image](https://user-images.githubusercontent.com/30337666/89103003-1942ea80-d441-11ea-8a6f-091a6cd2f19b.png)

It's hard for us to estimate up or down regulation of this gene in different group of cells because colors with same value in the two figures are not consistent. Plotting the two figures with same colorbar range can solve it.

So, I want to know that are there parameters solving it  in scanpy.pl.umap or some matplotlib methods that can be integrated with Scanpy?

Thank you very much!

**Comment by LuckyMD** [comment]
Hi @CadenZhao,

Check out the `vmax` and `vmin` parameters.

**Comment by CadenZhao** [comment]
Thank you~
