### ISSUE TITLE
How to change font in UMAP's visualization result?

### ISSUE THREAD

**Issue by genecell** [scverse/scanpy#1353]
Hi,

I'd like to directly change the font in UMAP's visualization result, e.g., by setting the font to Arial or Helvetica. I have no ideas about how to do this, could you please help me with this? Thanks in advance!

**Comment by ivirshup** [comment]
You can set fonts directly through Matplotlib. For example, using serif fonts:

```python
import scanpy as sc
from matplotlib import pyplot as plt

pbmc = sc.datasets.pbmc3k_processed()

with plt.rc_context({"font.family": "serif"}):
    sc.pl.umap(pbmc, color="louvain")
```

![serif](https://user-images.githubusercontent.com/8238804/89146953-a8aee180-d598-11ea-8b01-9e9f867517fe.png)

There's more details about this scattered throughout the matplotlib docs, [like here](https://matplotlib.org/gallery/api/font_family_rc_sgskip.html)
