### ISSUE TITLE
Use Azure for CI?

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#1358]
We've been dealing with long queue times for CI builds. This is at least partially because for each PR four jobs start, each of which takes at least 12 minutes. Since travis gives us at most five concurrent jobs, only one PR can be built at a time. This becomes worse if a PR is based on a branch on the main repo, since CI runs on those too.

Azure offers 10 free concurrent jobs. Seems like an easy win.

* 10 free concurrent jobs
* Easier to do multiple checks per build (i.e. linting and testing can happen in the same build, but be independent checks)
* Output looks easy to navigate, has good integration with github
* We could test on windows (depending on how hard this is to set up)
* (possible) Some projects seem to use multiple cores for testing

Cons:

* New system, will take some time to learn
* Maybe microsoft will start being evil again

**Comment by flying-sheep** [comment]
As an alternative: GitHub actions. It’s pretty manual, and I had good experiences with Azure, so I just mention it for completeness’s sake.

**Comment by grst** [comment]
Just my 2cents: 
I made really good experiences with Github actions.
 * I find them easy to set-up and they run many (20-40?) jobs in parallel. 
 * Really good integration with Github (e.g. upload to PyPI on release) 
 * windows testing works well, but it is a pain to setup pycairo, see [here](https://github.com/icbi-lab/scirpy/blob/725664a22e6265643633d89a7f38ea3383ccab48/.github/workflows/test.yml#L34) and [here](https://github.com/pygobject/pycairo/issues/19#issuecomment-638716293). 

Here's the [github actions script for scirpy](https://github.com/icbi-lab/scirpy/blob/master/.github/workflows/test.yml).
