### ISSUE TITLE
Differential expression table

### ISSUE THREAD

**Issue by ghost** [scverse/scanpy#1360]
Hi, is there a way to get a table of the differentially expressed genes after running: sc.tl.rank_genes_groups?
Thank you.

**Comment by ivirshup** [comment]
Does `sc.get.rank_genes_groups_df` do what you're looking for?

**Comment by ghost** [comment]
Thank you!

**Comment by BrianLohman** [comment]
Hi @ivirshup,

This looks like a great function but it's not super clear what the ```group``` arg is. Is it supposed to be one of the levels of the ```groupby``` arg in ```sc.tl.rank_genes_groups```? I would guess so based on the example here: https://scanpy.readthedocs.io/en/stable/api/scanpy.get.rank_genes_groups_df.html but that does not work for me

```
# compare expression levels of mel vs all other cell types in pairwise manner
sc.tl.rank_genes_groups(noncycling_adult, groupby='class_1', groups = ['T-cell', 'eccrine', 'mel', 'dendritic', 'krt'], reference = 'mel', key_added='DE_results', method = 'wilcoxon')

results = sc.get.rank_genes_groups_df(noncycling_adult, key = 'DE_results', group = 'mel')

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-32-73add1f79f3a> in <module>
      1 # save as a data frame
      2 
----> 3 results = sc.get.rank_genes_groups_df(noncycling_adult, key = 'DE_results', group = 'mel')
      4 
      5 

~/software/pkg/miniconda3/envs/melanocyte_env/lib/python3.7/site-packages/scanpy/get.py in rank_genes_groups_df(adata, group, key, pval_cutoff, log2fc_min, log2fc_max, gene_symbols)
     53     d = pd.DataFrame()
     54     for k in ['scores', 'names', 'logfoldchanges', 'pvals', 'pvals_adj']:
---> 55         d[k] = adata.uns["rank_genes_groups"][k][group]
     56     if pval_cutoff is not None:
     57         d = d[d["pvals_adj"] < pval_cutoff]

~/software/pkg/miniconda3/envs/melanocyte_env/lib/python3.7/site-packages/numpy/core/records.py in __getitem__(self, indx)
    517 
    518     def __getitem__(self, indx):
--> 519         obj = super(recarray, self).__getitem__(indx)
    520 
    521         # copy behavior of getattr, except that here

ValueError: no field of name mel
```

Thanks for your help

**Comment by BrianLohman** [comment]
Also posted here: https://scanpy.discourse.group/t/sc-tl-rank-genes-groups-specify-groups-and-implementation-for-multiple-tests/328 to try to follow the issue submission guidelines. 

Expanded documentation on how to to use ```sc.tl.rank_genes_groups``` in conjunction with ```sc.get.rank_genes_groups_df``` would be much appreciated.

**Comment by aj95b** [comment]
@BrianLohman I struggled with this for a while. I get the dataframe by setting the `group` argument to 'None'
