### ISSUE TITLE
A bug about scanpy.pp.downsample_counts()

### ISSUE THREAD

**Issue by AllenWu18** [scverse/scanpy#1368]
- [ ] I have checked that this issue has not already been reported.
- [ ] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

I just use the function sc.pp.downsample_counts() to downsample the data, but after that I can't see any output from the Spyder IPython console.
### Minimal code sample (that we can copy&paste without having any data)

```python
# Your code here
```
import numpy as np
import scanpy as sc
import h5py

data = h5py.File('10X_PBMC.h5')

x = np.array(data['X'])
adata = sc.AnnData(x)

sc.pp.downsample_counts(adata, counts_per_cell=1000)

```pytb
[Paste the error output produced by the above code here]
```
after I run the above code, there isn;t any error.
But when I key in 'adata' or any other thing in the Spyder IPython console, it just shows:

/anaconda3/lib/python3.7/site-packages/ipykernel/ipkernel.py:448: DeprecationWarning: `input_splitter` is deprecated since IPython 7.0, prefer `input_transformer_manager`.
  status, indent_spaces = self.shell.input_splitter.check_complete(code)

and there is nothing about the output I want.
After that, my console can’t output anything, unless I exit Spyder and re-enter.

### Versions
Python 3.7.0
Scanpy 1.4.3
<details>

[Paste the output of scanpy.logging.print_versions() leaving a blank line after the details tag]
scanpy==1.4.3 anndata==0.6.19 umap==0.3.10 numpy==1.14.6 scipy==1.1.0 pandas==0.23.4 scikit-learn==0.20.1 statsmodels==0.9.0 python-igraph==0.7.1 louvain==0.6.1 
</details>

**Comment by ivirshup** [comment]
At first blush, this looks like an issue with spyder. I'd suggest trying to update your versions of installed packages (it looks like your scanpy and anndata are out of date) and trying again. If that fails, can you replicate in a different python environment?

**Comment by eroell** [comment]
As we haven't heard back after the follow-up we will close the issue for now, hopefully you obtained the expected behaviour in the end :)

However, please don't hesitate to reopen this issue or create a new one if you have any more questions or run into any related problems in the future.

Thanks for being a part of our community! :)
