### ISSUE TITLE
How to create a panel of plots when using, for example, tsne

### ISSUE THREAD

**Issue by fbrundu** [scverse/scanpy#137]
Hi,
Would it be possible to create a panel of plots using both rows and columns when plotting tsne?
I did something similar to this:
![tsne markers](https://user-images.githubusercontent.com/697622/39486721-19f44a02-4d4b-11e8-986e-d78079a06e0c.png)

Basically the code calls the matplotlib subplots method based on the number of plots:

```py
def _build_subplots(n):
  '''
  Build subplots grid
  n: number of subplots
  '''
  nrow = int(np.sqrt(n))
  ncol = int(np.ceil(n / nrow))
  fig, axs = plt.subplots(nrow, ncol, dpi=100, figsize=(ncol*5, nrow*5))

  return fig, axs, nrow, ncol
```

Then the plots are drawn:

```py
genes = [...list of gene symbols...]
fig, axs, nrow, ncol = _build_subplots(len(genes))

if type(axs) != np.ndarray:
  axs = [axs]
else:
  axs = axs.ravel()

for i in range(nrow*ncol):
  if i < len(genes):
    gene = genes[i]
    # df is the numpy array containing tSNE
    axs[i].scatter(df[:, 0], df[:, 1], ...)
```

Is it something that is already done, planned or that you don't want to integrate?

Thanks,
Francesco

**Comment by falexwolf** [comment]
Dear Francesco, 

sorry about the late response... These days are incredibly busy.

Currently this is not on the list of urgent things. If you find an elegant way of introducing this in all the plotting functions at once, happy to discuss some prototype code.

For now, you can just use your method

```py
for i in range(nrow*ncol):
  if i < len(genes):
    gene = genes[i]
    # df is the numpy array containing tSNE
    ax = sc.pl.scatter(ax=axs[i], show=False)
```

What do you think?
  Alex

**Comment by fbrundu** [comment]
Thanks @falexwolf ,
No worries. I'd like to contribute when I can, but I'd need some time to understand how the code is structured. For now I'll be using your suggestion. If I have time I'll provide a PR.

Thanks again for the library,
Francesco

**Comment by jamestwebber** [comment]
@falexwolf we just tried the solution you posted and it reveals a bug: when `ax` is not `None` you don't create the variable `axs` and thus throw an error here: https://github.com/theislab/scanpy/blob/master/scanpy/plotting/anndata.py#L634

Should be a simple fix (I think):

```python
if ax is None:
    axs, _, _, _ = setup_axes(ax=ax, panels=['x'] if groupby is None else keys, show_ticks=True, right_margin=0.3)
else:
    axs = [ax]
```

**Comment by falexwolf** [comment]
Yes, indeed! Should be fixed https://github.com/theislab/scanpy/commit/8fab0d1196a5ae878ee7c9ab55f44d930aca01b4

But there were no problems with `pl.scatter`, right?

**Comment by jamestwebber** [comment]
I didn't actually check, but @aopisco will tell you soon...

**Comment by aopisco** [comment]
yes, now it works for `pl.scatter` and `pl.violin`
