### ISSUE TITLE
Option for dot_ax.grid(True, linewidth = x) in sc.pl.dotplot()

### ISSUE THREAD

**Issue by salwanbutrus** [scverse/scanpy#1371]
- [ ] Additional function parameters / changed functionality / changed defaults?
- [ ] New analysis tool: A simple analysis tool you have been using and are missing in `sc.tools`?
- [ ] New plotting function: A kind of plot you would like to seein `sc.pl`?
- [ ] External tools: Do you know an existing package that should go into `sc.external.*`?
- [ x] Other?
s

...
In sc.pl.dotplot(), dot_ax.grid(False) is the default. Can an argument please be added to the function that allows the option of True: dot_ax.grid(True, linewidth = x) with linewidth as part of the argument?

Thank you!
Salwan

**Comment by fidelram** [comment]
Hi, after release 1.6 this is now partially possible. If you set the parameter `return_fig=True` then you have access to the `style()` method (see: https://scanpy.readthedocs.io/en/stable/api/scanpy.pl.DotPlot.style.html#scanpy.pl.DotPlot.style).

```PYTHON
adata = sc.datasets.pbmc68k_reduced()
marker_genes = ['S100A8', 'GNLY', 'NKG7', 'KLRB1', 'FCGR3A', 'FCER1A', 'CST3']
ax_dict = sc.pl.dotplot(adata,marker_genes,groupby='bulk_labels', return_fig=True).style(grid=True).show()
```
![image](https://user-images.githubusercontent.com/4964309/90759033-2a647600-e2e0-11ea-86e4-2a0e060955ad.png)

What is not possible is to change the linewidth.

**Comment by salwanbutrus** [comment]
Awesome, thanks!

**Comment by salwanbutrus** [comment]
Actually a quick follow-up. How can one control the spacing between the dots in the dot size legend? They're often too close to each other for me. Thank you!

**Comment by fidelram** [comment]
you can set the legend width. Using the previous example:
```PYTHON
sc.pl.dotplot(adata,marker_genes,groupby='bulk_labels', return_fig=True).style(grid=True).legend(width=1.8).show()
````

See: https://scanpy.readthedocs.io/en/latest/api/scanpy.pl.DotPlot.legend.html#scanpy.pl.DotPlot.legend

**Comment by salwanbutrus** [comment]
Thank you!

**Comment by guensen0** [comment]
Hi,

great options with the styles... just one comment/question... to me, it seems that the automatic detection of the background for the color of the dot is not working:

dot_edge_color : str, Tuple[float, …], None (default: 'black')
Dot edge color. When color_on='dot' the default is no edge. When color_on='square', edge color is white for darker colors and black for lighter background square colors.

in my case, all dots are black independent of the background color:

![image](https://user-images.githubusercontent.com/59560120/100715263-3c61b480-33b7-11eb-8874-2a85364acea4.png)

Stefan
