### ISSUE TITLE
igraph problems

### ISSUE THREAD

**Issue by fbrundu** [scverse/scanpy#138]
Hi,
I have some problems running Louvain clustering.
The first time I tried to run, it complains about missing library `igraph`.
I installed `igraph` but now this same library throws a `DeprecationWarning` when calling Louvain clustering.

```
---------------------------------------------------------------------------
DeprecationWarning                        Traceback (most recent call last)
<ipython-input-17-329d7c2ac26c> in <module>()
----> 1 sc.tl.louvain(adata)

~/.pyenv/versions/3.6.4/lib/python3.6/site-packages/scanpy/tools/louvain.py in louvain(adata, resolution, random_state, restrict_to, key_added, adjacency, flavor, directed, n_jobs, copy)
     79             directed = False
     80         if not directed: logg.m('    using the undirected graph', v=4)
---> 81         g = utils.get_igraph_from_adjacency(adjacency, directed=directed)
     82         if flavor == 'vtraag':
     83             import louvain

~/.pyenv/versions/3.6.4/lib/python3.6/site-packages/scanpy/utils.py in get_igraph_from_adjacency(adjacency, directed)
     92 def get_igraph_from_adjacency(adjacency, directed=None):
     93     """Get igraph graph from adjacency matrix."""
---> 94     import igraph as ig
     95     sources, targets = adjacency.nonzero()
     96     weights = adjacency[sources, targets]

~/.pyenv/versions/3.6.4/lib/python3.6/site-packages/igraph/__init__.py in <module>()
      6 __license__ = "MIT"
      7 
----> 8 raise DeprecationWarning("To avoid name collision with the igraph project, "
      9                          "this visualization library has been renamed to "
     10                          "'jgraph'. Please upgrade when convenient.")

DeprecationWarning: To avoid name collision with the igraph project, this visualization library has been renamed to 'jgraph'. Please upgrade when convenient.
```

I can work on a PR and change line 94 of `scanpy/utils.py` to:

```
import jgraph as ig
```

This should solve the issue afaik (and `jgraph` should be listed in the dependencies I think). Let me know if you accept PRs.

Thanks,
Francesco

**Comment by fbrundu** [comment]
I noticed now that the library is `python-igraph` and not `igraph` as explained in https://scanpy.readthedocs.io/en/latest/installation.html .
I am closing this issue since I've solved through the steps in the documentation.

**Comment by RicedeKrispy** [comment]
I've tried to work through the documentation, but am having the same issue as soon as I try to go past the Louvain clustering.

**Comment by LuckyMD** [comment]
The above issue was fixed by installing python-igraph and not igraph. Just run
`pip install python-igraph`

**Comment by RicedeKrispy** [comment]
Thanks for the response. I tried that several times, but couldn’t get the install to work:

“Cannot find the C core of igraph on this system using pkg-config” etc.

Any other advice would of course be appreciated greatly.

**Comment by Koncopd** [comment]
@RicedeKrispy 
Hi, if you are using Windows, you can try to install python-igraph from the wheel here
https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-igraph

**Comment by RicedeKrispy** [comment]
I just noticed that the reply I sent Saturday bounced due to ‘unknown error’.

I thought I should provide an update in case other Windows users encounter something similar. After identifying the correct version of the several on the link below, I noticed that it was also necessary to install Pycairo. I then found I needed to install the Louvain algorithm to resolve the issue. The vtraag website indicates this algorithm has been superseded by the Leiden algorithm, which I installed with no problem.

Thanks much for your reply within hours, on a weekend no less.

**Comment by ONeillMB1** [comment]
Hello,
I've gotten scanpy working on my local computer, but for memory reasons I need to move to our server (linux). I am running into the same errors as above - any advice is appreciated!

Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    running build_ext
    Cannot find the C core of igraph on this system using pkg-config.
    We will now try to download and compile the C core from scratch.
    Version number of the C core: 0.7.1.post6
    We will also try: 0.7.1
    
    Version 0.7.1.post6 of the C core of igraph is not found among the nightly builds.
    Use the --c-core-version switch to try a different version.
    
    Could not download and compile the C core of igraph.
