### ISSUE TITLE
StructDict.__getitem__ broken

### ISSUE THREAD

**Issue by flying-sheep** [scverse/scanpy#14]
* `struct_dict['k']` should return a simple 1D ndarray, not a `StructDict`
* `struct_dict[['a', 'b']]` should return a proper `StructDict` including all additional fields like `_keys`

both problems are visible in this test: https://travis-ci.org/theislab/scanpy/jobs/227216146#L224

but a test should be added for the second point once the first point is fixed

---

i would have fixed it, but i don’t have the slightest idea what all the “multicolumn” fields are for. also i don’t believe in too many caches and private fields, they get out of sync too easily. recomputing tiny things is fast, e.g. `self._keys` could simply be replaced with `self.dtype.names`

**Comment by falexwolf** [comment]
fixed in https://github.com/theislab/scanpy/commit/50b739cb4356cf7cf77f323612e223154c8b44f0

**Comment by flying-sheep** [comment]
great, thank you!
