### ISSUE TITLE
SettingWithCopyWarning on rank_genes_groups_violin()

### ISSUE THREAD

**Issue by fbrundu** [scverse/scanpy#140]
It is low-priority I think (the function should work anyway), but I get the following Warning when I execute `rank_genes_groups_violin()`:

```
/Users/user/.pyenv/versions/3.6.4/lib/python3.6/site-packages/scanpy/plotting/tools/__init__.py:1037: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df['hue'][df['hue'] != group_name] = 'rest'
```
The interested line is the following:

https://github.com/theislab/scanpy/blob/639dcd4c2385a24271733a8f05d838dbf70175e6/scanpy/plotting/tools/__init__.py#L1159

If I remember correctly Pandas API, such line should be rewritten as:

```python
df.loc[df['hue'] != group_name, 'hue'] = 'rest'
```

Francesco

**Comment by falexwolf** [comment]
Thank you very much! You're right, the line isn't good style... I'll correct that... for some reason, I don't get the warning...

**Comment by fbrundu** [comment]
I was working on a PR in the same function and I decided to include the fix in that. I don't know if it's appropriate.
