### ISSUE TITLE
Adapt name of UMAP coordinates according to used representation

### ISSUE THREAD

**Issue by WeilerP** [scverse/scanpy#1403]
- [x] Additional function parameters / changed functionality / changed defaults?

As of now, when using `umap` [here](https://github.com/theislab/scanpy/blob/f704f724529def21769ee6407f9b47b5c161564c/scanpy/tools/_umap.py#L17), the calculated UMAP coordinates are always stored in `adata.obsm` with the key `"X_umap"`. This key can be misleading IMO. For example, let's say we calculated a neighbor graph on a layer `"SOME_LAYER"`. Wouldn't it make more sense to the call the UMAP coordinates `"SOME_LAYER_umap"`?

**Comment by giovp** [comment]
This is related to #1301 , let's keep discussion there, I'll close this
