### ISSUE TITLE
values_to_plot argument of rank_genes_groups_dotplot is not shown in the documentation

### ISSUE THREAD

**Issue by gokceneraslan** [scverse/scanpy#1404]
`values_to_plot` should be shown between groupby and min_logfoldchange but it's not shown in the Parameters section at all:

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/1140359/92004375-28eb7280-ed10-11ea-92d7-fd0d1cbb6bdd.png">

**Comment by fidelram** [comment]
I will add this
