### ISSUE TITLE
sc.plt.umap save as pdf bug

### ISSUE THREAD

**Issue by YubinXie** [scverse/scanpy#1405]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---
I tried to save an umap result to a pdf, however, the dots in Umap are blurred and it just looks like png. Only the legend is in vector mode. I was wondering if this is a bug?

**Comment by gokceneraslan** [comment]
Thanks. Can you share the code that produces the error? Maybe also the image as well?

**Comment by YubinXie** [comment]
`sc.pl.umap(ad, color=['mt.count'],save='test.pdf') `

[umaptest.pdf](https://github.com/theislab/scanpy/files/5171583/umaptest.pdf)

**Comment by fidelram** [comment]
I think that we rasterize the scatter part because is usually impractical to have a pdf with thousands of dots.

I sugggest that you increase the DPI to get a better resolution image:
See https://scanpy.readthedocs.io/en/stable/api/scanpy.set_figure_params.html

**Comment by wflynny** [comment]
The real issue is probably `vector_friendly = True` which will rasterize the underlying scatterplot.  Setting `sc.settings.vector_friendly = False` should correct that.

**Comment by flying-sheep** [comment]
Seems like there are some approaches on how to solve this on the user side.

Feel free to suggest improvements to the docs!
