### ISSUE TITLE
var_names not being found by during plotting

### ISSUE THREAD

**Issue by bz520251** [scverse/scanpy#1406]
I tried import .loom file generate from Seurat into scanpy for drawing heatmap.
There is a gene "CD34", when I draw in R, it reported as "Warning: Could not find CD34 in the default search locations, found in RNA assay instead". but still work.
While in scanpy, it showed the following error: KeyError: "Values ['CD34'], from ..., are not valid obs/ var names or indices."
How can I fix it?

**Comment by giovp** [comment]
you can check if `adata.var.index`has that gene. Also, what's the command you are trying to run?

**Comment by kleurless** [comment]
Hi! Same issue here, but for me no plotting function works for any gene.

I have two Seurat object which I converted to .h5ad files using Seurat-disk, I have read them into scanpy and want to plot a few markers using a dotplot. For one dataset, I can plot any gene I want and it succeeds. For the other dataset, I can't plot **any** gene, in any type of plot (tsne, violin, dotplot, matrixplot, etc.)

```
adata_1 = sc.read_h5ad("path/to/file1.h5ad")
adata_2 = sc.read_h5ad("path/to/file2.h5ad")
```

```
#this works
sc.pl.dotplot(adata_1, adata_1.var_names[0:4], groupby='clusters', color_map = 'Reds')

#these do not
sc.pl.dotplot(adata_2, adata_2.var_names[0:4], groupby='celltype', color_map = 'Reds')
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-72-4fc81df5ca3f> in <module>
----> 1 sc.pl.dotplot(adata_2, adata_2.var_names[0:4], groupby='celltype', color_map = 'Reds')

~\Anaconda3\envs\UMCU\lib\site-packages\scanpy\plotting\_anndata.py in dotplot(adata, var_names, groupby, use_raw, log, num_categories, expression_cutoff, mean_only_expressed, color_map, dot_max, dot_min, standard_scale, smallest_dot, figsize, dendrogram, gene_symbols, var_group_positions, var_group_labels, var_group_rotation, layer, show, save, **kwds)
   1809         num_categories,
   1810         layer=layer,
-> 1811         gene_symbols=gene_symbols,
   1812     )
   1813 

~\Anaconda3\envs\UMCU\lib\site-packages\scanpy\plotting\_anndata.py in _prepare_dataframe(adata, var_names, groupby, use_raw, log, num_categories, layer, gene_symbols)
   2911         matrix = adata[:, var_names].layers[layer]
   2912     elif use_raw:
-> 2913         matrix = adata.raw[:, var_names].X
   2914     else:
   2915         matrix = adata[:, var_names].X

~\Anaconda3\envs\UMCU\lib\site-packages\anndata\_core\raw.py in __getitem__(self, index)
     94 
     95     def __getitem__(self, index):
---> 96         oidx, vidx = self._normalize_indices(index)
     97 
     98         # To preserve two dimensional shape

~\Anaconda3\envs\UMCU\lib\site-packages\anndata\_core\raw.py in _normalize_indices(self, packed_index)
    154         obs, var = unpack_index(packed_index)
    155         obs = _normalize_index(obs, self._adata.obs_names)
--> 156         var = _normalize_index(var, self.var_names)
    157         return obs, var
    158 

~\Anaconda3\envs\UMCU\lib\site-packages\anndata\_core\index.py in _normalize_index(indexer, index)
     91                 not_found = indexer[positions < 0]
     92                 raise KeyError(
---> 93                     f"Values {list(not_found)}, from {list(indexer)}, "
     94                     "are not valid obs/ var names or indices."
     95                 )

KeyError: "Values ['Rgs20', 'Oprk1', 'St18', 'Gm26901'], from ['Rgs20', 'Oprk1', 'St18', 'Gm26901'], are not valid obs/ var names or indices."

sc.pl.matrixplot(adata_2, adata_2.var_names[0:4], groupby='celltype') #same error
sc.pl.tsne(adata_2, color=adata_2.var_names[0:4]) #KeyError: 'Rgs20' 

```

Any help would be much appreciated!

**Comment by giovp** [comment]
can you paste the output of this:
```python
adata_2.var
```

**Comment by kleurless** [comment]
@giovp `adata_2.var`
![image](https://user-images.githubusercontent.com/60929679/95211155-829dfb80-07ec-11eb-819b-a4102b762a59.png)

**Comment by giovp** [comment]
mmh, I just tried with a random anndata and it works for me:

```python
sc.pl.dotplot(adata, adata.var_names[0:4], groupby="leiden", color_map="Reds")
```
![image](https://user-images.githubusercontent.com/25887487/95213441-1c66a800-07ef-11eb-8b4b-f754d14eb12c.png)

```python
print(f"anndata version: {anndata.__version__}, scanpy version: {sc.__version__}")
>>> anndata version: 0.7.4, scanpy version: 1.6.0
```

can you check your versions? Also, can you print shape of `adata.raw` and `adata.X`?

**Comment by kleurless** [comment]
```
sc.logging.print_versions()
scanpy==1.4.6 anndata==0.7.1 umap==0.3.10 numpy==1.18.1 scipy==1.4.1 pandas==1.0.1 scikit-learn==0.22.1 statsmodels==0.11.1 python-igraph==0.8.0 louvain==0.6.1
```

```
adata_2.raw.shape
> (5558, 2000)
adata_2.X.shape
> (5558, 2000)
```

**Comment by giovp** [comment]
ok, do you mind updating both scanpy and anndata and try again? There has been a major refactoring of plotting functions in 1.6.0 and it could address your issue

**Comment by kleurless** [comment]
Sorry, that isn't an option for me.. I guess I'll just revert back to Seurat

**Comment by giovp** [comment]
mmh can I help you with how to go wrt to update?

@bz520251 is this still an issue for you?

**Comment by Chenyanjuan1993** [comment]
I have the same problem. Updating both scanpy and anndata could not solve it.

**Comment by giovp** [comment]
@Chenyanjuan1993 thank you for reporting this. I think it's some typing problem with the var_names index, and so possibly regarding your anndata.

Can you share the list of commands that you run before that error? Like do you concat/merge? Also, could you run that with this anndata `adata = scanpy.datasets.pbmc3k()`

**Comment by liliblu** [comment]
I am having this same problem. I updated:
anndata     0.7.5
scanpy      1.6.0

It did not fix the problem for me. 

I can try with the pbmc data set, what should I use for the groupby?

**Comment by ivirshup** [comment]
@liliblu `"louvain"` would work.

@kleurless, sorry for such a late reponse to this! If you are still having this problem, does your `adata_2` have `.raw` set? `adata.raw.var_names` ca be different than `adata.var_names`, but is is used by default for plotting when available. Does your second call work with `sc.pl.dotplot(adata_2, adata_2.var_names[0:4], groupby='celltype', color_map = 'Reds', use_raw=False)`?

If this is the issue, we should at least have a more clear error in the next release (#1583).

**Comment by msalaciak** [comment]
Hi, Just wanted to comment that I had this issue. Converted from Seurat to h5ad using SeuratDisk.  `adata.raw.var_names` is different than  `adata.var_names`. As a result, I couldn't plot since none of my features were found (keys). Using `use_raw=False` worked.

**Comment by Qiuyanhe** [comment]
I encountered the same problem. I just followed the tutorial of preprocessing and clustering 3k PBMCs(https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html).  I can not figure out why the gene list of the result of sc.tl.rank_genes_groups is different from that of adata.var.index or adata.var_names. And when I tried to use sc.pl.dotplot to get the dotplot, there existed some marker genes chosen based on the result of sc.tl.rank_genes_groups not found in obs / var names or indices, especially when I set use_raw = False.

![图片](https://user-images.githubusercontent.com/32971171/117529616-0d590a00-b00b-11eb-9a3a-41ff95ec864d.png)

**Comment by ShaowenJ** [comment]
> Hi, Just wanted to comment that I had this issue. Converted from Seurat to h5ad using SeuratDisk. `adata.raw.var_names` is different than `adata.var_names`. As a result, I couldn't plot since none of my features were found (keys). Using `use_raw=False` worked.

Yep, I have the same problem, if you worked on a Seurat-converted h5ad adata.
Any solutions or updates on this? Or we have to use useRaw=False????

**Comment by hurleyLi** [comment]
The problem is really just that you're not able to directly edit `adata.raw.var_names`, but you can work around by convert `.raw` to a temporary `AnnData`, change the var_name to match with the `adata.var_names`, and convert back to `.raw`
```
tempAdata = adata.raw.to_adata()
tempAdata.var_names = adata.var_names
adata.raw = tempAdata
```

**Comment by hyjforesight** [comment]
@Qiuyanhe I have the same problem. If i set use_raw=false, then a lot of genes cannot be found.

**Comment by ivirshup** [comment]
`adata.raw.var_names` will have a different set of variables than `adata.var_names`, see #2018. This is by design, to allow you to have a reduced set of features in a dense matrix in `adata.X`, but have the full dataset in `adata.raw`.

**Comment by jlehrer1** [comment]
Can this just be inferred under the hood/raise a warning? It's a very frustrating error and not clear at all what the root issue for an end user.

**Comment by sreichl** [comment]
Maybe this helps someone who encounters this problem as well. 
Here is what worked for me: Set the var **indices** of both X and raw and thereby the respective var_names get set automatically.
```python
# load the adata object, converted using SeuratDisk
adata = sc.read_h5ad(object_path)

# Set the new variable names by setting the respective indices otherwise gene names are not found
adata.var.index = adata.var.features
adata.raw.var.index = adata.var.features

# convert the cell type label data to type category (otherwise some methods do not work)
adata.obs['cell_type'] = adata.obs['cell_type'].astype('category')
```

**Comment by domenico-somma** [comment]
Thanks, make sense for me
(I think you meant
`adata.raw.var.index = adata.raw.var.features`
)

**Comment by sreichl** [comment]
uhm for me the dimensions were the same and only the `adata.var.features` had the correct gene names stored...
But that might stem from a conversion from Seurat to scanpy object (adata) using SeuratDisk.

**Comment by paolaporracciolo** [comment]
I do not know if you still have the problem

While converting from Seurat, adata.raw.var went from being just an index with the varnames, (but 0 cols), to a df with a normal index and 1 col called _index with the varnames.

The following two lines worked for me: 

# Set column '_index' as new index
`adata.raw.var.set_index('_index', inplace=True)`
# Remove index name
`adata.raw.var.index.name = None`
