### ISSUE TITLE
Leiden doesn't save clusters in `adata.obs`

### ISSUE THREAD

**Issue by cartal** [scverse/scanpy#1410]
- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

I have been trying to cluster a manifold of around 100K cells computed from scVI using the `leiden` 
algorithm as follows: 

``` 
sc.tl.leiden(adata_latent, resolution = 1, random_state = 1786)
```
This works fine:

```
running Leiden clustering
Trying to set attribute `.obs` of view, copying.
    finished: found 17 clusters and added
    'leiden', the cluster labels (adata.obs, categorical) (0:07:14)
```

However, when I inspect the object where I just ran `leiden`, I can't see the `leiden` labels in `adata.obs`. 
Instead, it seems to be located in `adata.uns`. 

```
AnnData object with n_obs × n_vars = 106774 × 50
    obs:  'percent_mito', 'n_genes', 'n_counts'
    uns: 'neighbors', 'umap', 'sampleID_colors', 'batch_colors', 'status_colors', 'leiden'
    obsm: 'X_umap'
    obsp: 'distances', 'connectivities'
```

I have tried to downgrade `leidenalg` but there is no change. Do you have an idea what may be happening? 

#### Versions

<details>

scanpy==1.6.0 anndata==0.7.4 umap==0.4.6 numpy==1.19.1 scipy==1.5.2 pandas==1.1.1 scikit-learn==0.23.2 statsmodels==0.12.0 python-igraph==0.8.2 louvain==0.7.0 leidenalg==0.8.1

</details>

**Comment by LuckyMD** [comment]
Hi @cartal,

Could it be that you are using a subsetted anndata object on which you are running clustering? If you run an `adata_subset = adata_subset.copy()` You turn that from a view into an anndata object, which might avoid this. I'm however not sure why using a view would make the clustering results end up in `adata.uns`.

**Comment by cartal** [comment]
Thanks for the quick reply @LuckyMD!

This is the whole dataset, the only subsetting I've done is when I have filtered low quality cells.

**Comment by LuckyMD** [comment]
The line `Trying to set attribute `.obs` of view, copying.` suggests that your object is still a View. Could you check the output of just your `adata` object?

**Comment by cartal** [comment]
I see. 

The output for `adata` is:
```
AnnData object with n_obs × n_vars = 106774 × 33538
    obs: 'Cell', 'sampleID', 'sample_name', 'UMI_count', 'detectedGenesPerCell', 'percent_mito', 'data_set', 'IsPassed', 'batch', 'status', 'n_genes', 'n_counts', 'leiden', 'leiden_scVI'
    var: 'name'
    uns: 'log1p'
```

I can see that my attempts to `leiden`ing have ended up here in `adata.obs` ...

**Comment by LuckyMD** [comment]
This looks as though it is now no longer a view, or the respective warning is from a line of code in the `sc.tl.leiden()` function. Either way, it looks to be resolved now. Might the `adata.uns['leiden']` be the colours assigned to the clusters after plotting?

**Comment by cartal** [comment]
I tested this in a couple of machine and the pipeline works fine there. However, I just re-installed `leidenalg` and this is now resolved! 

Thanks a lot for the feedback.

**Comment by LuckyMD** [comment]
Great! Glad I could help.
