### ISSUE TITLE
In sc.pl.tracksplot, groupby is not worked

### ISSUE THREAD

**Issue by john-jiangyong** [scverse/scanpy#1414]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [x] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can copy&paste without having any data)

```python
ax = sc.pl.tracksplot(adata, markers, groupby = "seurat_clusters") 
adata.obs["seurat_clusters"].dtype.name != 'category'
```

```pytb
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-33-097156e92bcf> in <module>
----> 1 ax = sc.pl.tracksplot(adata, markers, groupby = "seurat_clusters")

D:\python\empty for python\lib\site-packages\scanpy\plotting\_anndata.py in tracksplot(adata, var_names, groupby, use_raw, log, dendrogram, gene_symbols, var_group_positions, var_group_labels, layer, show, save, figsize, **kwds)
   1304     if groupby not in adata.obs_keys() or adata.obs[groupby].dtype.name != 'category':
   1305         raise ValueError(
-> 1306             'groupby has to be a valid categorical observation. '
   1307             f'Given value: {groupby}, valid categorical observations: '
   1308             f'{[x for x in adata.obs_keys() if adata.obs[x].dtype.name == "category"]}'

ValueError: groupby has to be a valid categorical observation. Given value: seurat_clusters, valid categorical observations: []

Ture
```

#### Versions

<details>

[Paste the output of scanpy.logging.print_versions() leaving a blank line after the details tag]

</details>

**Comment by john-jiangyong** [comment]
when I detect the with adata.obs["seurat_clusters"].dtype.name != 'category'.  the resault  shows Ture

**Comment by LuckyMD** [comment]
Hi @john-jiangyong,

The error is that your covariate you group by should be a categorical, while it is not at the moment. You could run:
`adata.obs[‘seurat_clusters’] = adata.obs[‘seurat_clusters’].astype(‘category’)` To turn the covariate into a categorical.

Note the code above might not be 100% correct as i’m typing from my phone and haven’t verified.
