### ISSUE TITLE
Improve documentation for developers

### ISSUE THREAD

**Issue by WeilerP** [scverse/scanpy#1419]
## Description

For an easier start of potential contributors, it might be helpful to add a file such as `requirements-dev.txt` including all packages required to e.g. run unit tests locally. Otherwise, several packages (e.g. `leidenalg`, `louvain`, `scikit-misc`, `harmonypy`, `python-igraph`) have to be installed manually which is rather tedious:

```txt
-r requirements.txt

harmonypy
leidenalg
louvain
scitkit-misc
python-igraph
```

The wheels to install `python-igraph` under Windows can, for example, be found [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-igraph).

**Comment by WeilerP** [comment]
Realised this functionality is already available via `pip install ".[dev]"`. May be good to mention somewhere, though.

**Comment by fidelram** [comment]
This is indeed very valuable information. 

Do you mind adding a PR updating https://github.com/theislab/scanpy/blob/master/docs/installation.rst ?

**Comment by WeilerP** [comment]
Yes, no problem. I'll update it in a bit.

**Comment by WeilerP** [comment]
I had a look at scanpy's [setup file](https://github.com/theislab/scanpy/blob/master/setup.py) `setup.py` and realised that running

```bash
pip install -e .
pip install ".[dev]"
```

does neither install all packages used within Scanpy's code base nor packages required for documentation or testing.

IMO, these packages should be installed in a _developer installation_ as they are all part of the development cycle. Adding a file `requirements-dev.txt` including all needed packages would be an option to allow for an easy _developer installation_ via

```bash
pip install -e .
pip install -r requirements-dev.txt
```

Any thoughts on this?

**Comment by WeilerP** [comment]
Were there every any thoughts or discussions on adding pre-commit hooks? This would, for example, automatically enforce the black coding style prior to committing new changes.

The `.pre-commit-hooks.yaml` file could, for example, look as follows:

```yaml
# .pre-commit-hooks.yaml
repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
```

**Comment by giovp** [comment]
can we follow keep discussing on #1563 ? 
@WeilerP not sure if you ever submitted that PR, but otherwise we can close this

**Comment by WeilerP** [comment]
Sorry, no, I didn't open a PR since I hadn't heard back regarding above comments. Fine to close it in favour of #1563, although it only concerns pre-commit hooks, right? The original idea of this issue was to make the dev installation easier, i.e. installing all required packages to run the full code base, tests etc. This currently doesn't happen when installing through `pip install ".[dev]"`.

**Comment by giovp** [comment]
that's a very good point yes, I know there is also #1527 underway, can you guys comment on this @flying-sheep @ivirshup cause I'm not sure timing wise how is it going ?

**Comment by ivirshup** [comment]
I think #1527 is coming along nicely. It seems to mostly work now. It'd be great if some other team members could try it out and see if it works for them!

**Comment by WeilerP** [comment]
As far as I can tell, #1527 still doesn't install all packages in a dev installation required to run the entire code base and tests.

**Comment by ivirshup** [comment]
`flit install -s` by default would install everything, passing `--deps=develop` actually leads to fewer things being installed. I think this is weird behavior, but it's the way flit works.

**Comment by ivirshup** [comment]
I think this is has been covered by the "Contributing" section of the docs.
