### ISSUE TITLE
DCA integration

### ISSUE THREAD

**Issue by gokceneraslan** [scverse/scanpy#142]
I'd like to integrate DCA with scanpy and I need to ask some questions regarding that. 

There are two use cases for DCA so far. One is denoising as a preprocessing step and using denoised matrix in downstream analyses, especially in the ones that require original feature space such as differential expression. This seems to be a better fit for the `preprocessing` package i.e. `sc.pp.dca(adata)` which overwrites `adata.X` with the denoised matrix. Users can use `copy=True` to keep adata.X of original matrix unchanged.

The other use case is the low dimensional representations of cells produced by the encoder. This can also be used for the downstream analyses that do not require original feature space e.g. clustering, and visualization. This is more like `sc.tl.dca(adata)` which stores the new representation into `adata.obsm['X_dca']`. Optionally it can store dropout probabilities (pi matrix) and the dispersion, as well.

However, having both sc.tl.dca and sc.pp.dca might be confusing for the users. Any suggestions?

**Comment by falexwolf** [comment]
I'd make it a preprocessing step that has a parameter that allows to save the latent and/or the imputed representation of X. The latent one would go into `.obsm` as `'X_dca'` and would be an alternative to `'X_pca'` when analyzing the manifold using `neighbors` with param `use_rep='X_dca'`. The imputed one would directly overwrite `.X`. Meaningful default in my opinion: only store the late representation... but you're free to do this however you like.

**Comment by falexwolf** [comment]
Maybe it's also in idea to call the latent representation 'Z_dca'... until now, the `Z` nomenclature wasn't really necessary... but thinking about how to explain this in the docs of the dca tool, I guess it would add clarity. Even though, of course, we don't adopt this notation for PCA, for instance.

You can make a `mode` parameter: `mode='latent'`, etc... But it requires some thinking about how to do this in the most meaningful way...
