### ISSUE TITLE
Unit tests fail with latest version of seaborn

### ISSUE THREAD

**Issue by WeilerP** [scverse/scanpy#1420]
## Description

Using the `seaborn==0.11` makes `scanpy/tests/test_plotting.py:test_violin` and `scanpy/tests/notebooks/test_pbmc3k.py` fail. The warning

```bash
UserWarning: Vertical orientation ignored with only `x` specified.
```

is thrown by `seaborn` in the stack trace for the failed tests.

The problem seems to originate from [here](https://github.com/theislab/scanpy/blob/f704f724529def21769ee6407f9b47b5c161564c/scanpy/plotting/_anndata.py#L745) and [here](https://github.com/theislab/scanpy/blob/f704f724529def21769ee6407f9b47b5c161564c/scanpy/plotting/_anndata.py#L747), where `x` and `y` are not both specified.

See #1417 and especially [this](https://github.com/theislab/scanpy/pull/1417#issuecomment-693488428) comment by @fidelram for more details.

**Comment by fidelram** [comment]
@WeilerP Any idea on how to solve the problem? I thought that setting `orient='vertical'` was going to solve the issue but we already do that.

**Comment by WeilerP** [comment]
I skimmed through the code only briefly yesterday but I think the problem might be that both `x` and `y` need to be specified: The error message seems to indicate so and the two lines seemingly responsible for the problem are the only ones where `x` and `y` are **not** both specified.

I'll have a closer look at it in a bit.

**Comment by fidelram** [comment]
Looking at this function which is called by seaborn violin (https://github.com/mwaskom/seaborn/blob/cf8af7e1c4ffd5d0044d13323731fa5066c057c8/seaborn/_core.py#L1260) it seems that what we need to do is swap x and y.

**Comment by WeilerP** [comment]
Yes, I saw that too but I was hoping it could be prevented as it seems suboptimal to me and is probably confusing when looking at the code.

Is there a specific reason for using `seaborn.FacetGrid` instead of `seaborn.catplot` (see [here](https://seaborn.pydata.org/generated/seaborn.catplot.html#seaborn.catplot))? Replacing the lines

```python
# ...
kwds.setdefault('cut', 0)
kwds.setdefault('inner')

if multi_panel and groupby is None and len(ys) == 1:
    # This is a quick and dirty way for adapting scales across several
    # keys if groupby is None.
    y = ys[0]
    g = sns.FacetGrid(obs_tidy, col=x, col_order=keys, sharey=False)

    # don't really know why this gives a warning without passing `order`
    g = g.map(sns.violinplot, y, orient='vertical', scale=scale, order=keys, **kwds)
```

[here](https://github.com/theislab/scanpy/blob/f704f724529def21769ee6407f9b47b5c161564c/scanpy/plotting/_anndata.py#L736) by

```python
if multi_panel and groupby is None and len(ys) == 1:
    g = sns.catplot(y=y, data=obs_tidy, kind="violin", col=x, col_order=keys, sharey=False, order=keys, **kwds)
```

gives the desired plot (except for different size). The strip plot can be added on top by calling `seaborn.stripplot` afterwards:

```python
if multi_panel and groupby is None and len(ys) == 1:
    g = sns.catplot(y=y, data=obs_tidy, kind="violin", col=x, col_order=keys, sharey=False, order=keys, **kwds)
    if stripplot:
        sns.stripplot(y=y, data=obs_tidy, jitter=jitter, color="black")
```

At the moment, I am just unsure how to plot to each subplot of the new `g`. It might be possible to loop through the plot grid so not to add everything on top of the last plot.

![master_violin_multi_panel](https://user-images.githubusercontent.com/28675704/93460801-16626300-f8e4-11ea-8f46-ed7ff64d8efb.png)


Besides the not yet solved strip plot problem, would that be a valid alternative?

**Comment by fidelram** [comment]
There is not particular reason to use FacetGrid. If catplot does the job then it is ok.

**Comment by WeilerP** [comment]
The following code produces the desired plot (up to permutation of the subplots and the image size) in case of only one row of subplots:

```python
if multi_panel and groupby is None and len(ys) == 1:
    # This is a quick and dirty way for adapting scales across several
    # keys if groupby is None.
    y = ys[0]

    g = sns.catplot(y=y, data=obs_tidy, kind="violin", col=x, col_order=keys, sharey=False, order=keys, **kwds)

    if stripplot:
        grouped_df = obs_tidy.groupby(x)
        for ax_id, key in zip(range(g.axes.shape[1]), keys):
            sns.stripplot(y=y, data=grouped_df.get_group(key), jitter=jitter, size=size, color="black", ax=g.axes[0, ax_id], **kwds)
```

![master_violin_multi_panel](https://user-images.githubusercontent.com/28675704/93485925-e5922600-f903-11ea-9edb-0f7523a67c0d.png)


Seems a bit hacky to me. What do you think @fidelram?

**Comment by fidelram** [comment]
@WeilerP probably there is a more direct way to overlay the stripplot but I don't think that it makes any big difference. 

Can you make a PR to see how the tests work?
