### ISSUE TITLE
could not install louvain via conda 

### ISSUE THREAD

**Issue by goldfish500** [scverse/scanpy#143]
I tried to install louvain through conda
`conda install -c vtraag louvain`
but got error message:
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - louvain
  - python-igraph[version='>=0.7.1.0']

However I could install it by
`conda install -c conda-forge louvain`

Can you please update it on the webpage. Thanks!
[https://scanpy.readthedocs.io/en/latest/installation.html](url)

**Comment by falexwolf** [comment]
Thank you very much for this remark! I'll update the documentation!
