### ISSUE TITLE
ImportError: cannot import name 'read' from 'scanpy' (unknown location)

### ISSUE THREAD

**Issue by roofya** [scverse/scanpy#1433]
Hi

I  have successfully installed scanpy but 
ImportError                               Traceback (most recent call last)
<ipython-input-5-99fcf407c387> in <module>
----> 1 import scvelo as scv
      2 import scanpy as sc
      3 import numpy as np

~/anaconda3/lib/python3.7/site-packages/scvelo/__init__.py in <module>
     14     del version
     15 
---> 16 from .read_load import AnnData, read, read_loom, load, read_csv, get_df, DataFrame
     17 from .preprocessing.neighbors import Neighbors
     18 from .tools.run import run_all, test

~/anaconda3/lib/python3.7/site-packages/scvelo/read_load.py in <module>
     10 from scipy.sparse import issparse
     11 from anndata import AnnData
---> 12 from scanpy import read, read_loom
     13 
     14 

ImportError: cannot import name 'read' from 'scanpy' (unknown location)

Would you please help me to fix this problem.

Thank you

**Comment by giovp** [comment]
From the traceback, it'ss look like it's scvelo https://github.com/theislab/scvelo
Can you post this error with a reproducible example in scvelo repo ?

Will close this, feel free to reopen if problem persist

**Comment by roofya** [comment]
@giovp 

I solved the problem its scvelo and I have installed the package and now it works fine.

Thank you

**Comment by Portulaca666** [comment]
Hi ,I have  encountered the same  problem , I knew it is beacuse a  circular import ,but how can i fixed it ? can you help me ,please .
![image](https://github.com/scverse/scanpy/assets/70992194/445595ab-e15a-497f-aa93-6da339c8318c)
![Uploading image.png…]()
