### ISSUE TITLE
Insufficient explanation in docs about n_genes_by_counts variable

### ISSUE THREAD

**Issue by havardtl** [scverse/scanpy#1434]
Hi, 

Thanks for developing a good tool for analyzing scRNAseq data. In the process of learning scRNAseq analysis with scanpy I have come across a few places in the documentation that left me a bit confused. 

The most confusing is that I could not find a description for the variable `n_genes_by_counts` calculated by the function scanpy.pp.calculate_qc_metrics and mentioned in the tutorial https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html. 

I asked a question about this in [the discourse](https://scanpy.discourse.group/t/clarification-of-qc-metrics/295) and was asked to open a github issue. 

I guess an explanation for the docs could be something like `n_genes_by_counts: The number of genes with at least 1 count in a cell. Calculated for all cells.` 

Since I am writing this I might add that I did not understand exactly how the normalization function [scanpy.pp.normalize_total](https://scanpy.readthedocs.io/en/stable/api/scanpy.pp.normalize_total.html) works before I stumbled upon the description of the deprecated function with the same purpose: [scanpy.pp.normalize_per_cell](https://scanpy.readthedocs.io/en/stable/api/scanpy.pp.normalize_per_cell.html) . The deprecated function has a helpful line saying: `Normalize each cell by total counts over all genes, so that every cell has the same total count after normalization.` which at least helped me clear things up. Maybe this line should be added to the new version of the function?

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

**Comment by ivirshup** [comment]
This issue has been mentioned on **Scanpy**. There might be relevant details there:

https://scanpy.discourse.group/t/clarification-of-qc-metrics/295/4

Edit: This was a bot, bad bot

**Comment by LuckyMD** [comment]
@ivirshup that's the initial discourse thread that led here ;).

**Comment by ivirshup** [comment]
@havardtl, sorry for the late feedback, but this would be a great first PR.

**Comment by levinhein** [comment]
Just to be clear, is **n_genes** = `nFeature_RNA` and **n_genes_by_counts** = `nCounts_RNA `?
