### ISSUE TITLE
Incorrect pip install statement in documentation for contributors

### ISSUE THREAD

**Issue by WeilerP** [scverse/scanpy#1441]
## Description

The documentation in `CONTRIBUTING.md` states that all dependencies required for testing can be installed via `pip install scanpy[test]`. It should, however, be `pip install "scanpy[test]"`.

### Minimal code sample

```zsh
pip install scanpy[test]
zsh: no matches found: scanpy[test]
```

**Comment by adamgayoso** [comment]
I think this is a zsh issue. Try adding:

```
  alias pip='noglob pip'
  alias pip3='noglob pip3'
```

to your `.zshrc`.

**Comment by jhrdt** [comment]
I would suggest `scanpy\[test\]` . Works with BASH and ZSH.

**Comment by flying-sheep** [comment]
Noglob turns off all globbing though. Would be great if one could turn off just Extended globbing for a command.

After all, `pip install *.whl` could be useful.
