### ISSUE TITLE
Variance explained annotation for scanpy.pp.pca

### ISSUE THREAD

**Issue by bfurtwa** [scverse/scanpy#1445]
- [x] Additional function parameters / changed functionality / changed defaults?
- [ ] New analysis tool: A simple analysis tool you have been using and are missing in `sc.tools`?
- [ ] New plotting function: A kind of plot you would like to seein `sc.pl`?
- [ ] External tools: Do you know an existing package that should go into `sc.external.*`?
- [ ] Other?

Would it be possible to add a parameter 'annotate_var_explained' = True/False to the function scanpy.pp.pca to annotate the x- and y-axis of the PCA plot with the variance explained by the component? E.g. x-axis label = PC1 (29%) and y-axis label = PC2 (3%)

**Comment by giovp** [comment]
similar to #1211

**Comment by giovp** [comment]
Hi @bfurtwa ,

would something like this be useful for your question? https://scanpy.readthedocs.io/en/stable/api/scanpy.pl.pca_overview.html#scanpy.pl.pca_overview
https://scanpy.readthedocs.io/en/stable/api/scanpy.pl.pca_variance_ratio.html#scanpy.pl.pca_variance_ratio
?

**Comment by bfurtwa** [comment]
Hi @giovp ,

although these plots contain very similar information, I specifically need the variance explained annotation in the scatter plot.

**Comment by giovp** [comment]
Have you thought about just adding it to the axis like this?

```python
plt.xlabel(f"PC var: {adata.uns["pca"]["variance_ratio"][0]}")
```

Any scanpy function can return a matplotlib axis, that could be further manipulated, checkout the `return_axis` argument of e.g. pca plotting function https://scanpy.readthedocs.io/en/stable/api/scanpy.pl.pca.html

**Comment by giovp** [comment]
I don't think we'll prioritize adding such functionality, also because it doesn't really translate to other types of embedding. But if you think it's really necessary feel free to open a PR, I'd be happy to help with that!
