### ISSUE TITLE
sc.tl.filter_rank_genes_groups gene name with NA

### ISSUE THREAD

**Issue by jphe** [scverse/scanpy#1446]
- [ ] I have checked that this issue has not already been reported.
- [ ] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can copy&paste without having any data)

```python
sc.tl.rank_genes_groups(adata,'leiden', n_genes=10000,use_raw=False)
sc.tl.filter_rank_genes_groups(adata, min_fold_change=2,min_in_group_fraction=0.3,use_raw=False,key='rank_genes_groups')
sc.pl.rank_genes_groups_heatmap(adata, swap_axes=True, use_raw=False, cmap='bwr', dendrogram=True,n_genes=1000,
                                                standard_scale='var',key='rank_genes_groups_filtered')

df1=pd.DataFrame( {group + '_' + key[:1]: adata.uns['rank_genes_groups'][key][group]  for group in ['0','1'] for key in ['names','logfoldchanges']})
df2=pd.DataFrame( {group + '_' + key[:1]: adata.uns['rank_genes_groups_filtered'][key][group]  for group in ['0','1'] for key in ['names','logfoldchanges']})
```

<img width="721" alt="image" src="https://user-images.githubusercontent.com/34993687/95295823-56e14b00-08aa-11eb-9b8d-6bbbd4221d10.png">

Hi,

I have run sc.tl.filter_rank_genes_groups() succssfully, but I find some gene names in adata.uns['rank_genes_groups_filtered']['names'] is nan,  but all gene names in adata.uns['rank_genes_groups']['names'] are correct. So, how could this happern?

Thanks,
Jphe

#### Versions

<details>

</details>

**Comment by YubinXie** [comment]
I saw this error in my analysis as welll.

**Comment by MikeLiuAir00** [comment]
Exact same error also happened to me in my analysis, need a fix.

**Comment by kcArtemis** [comment]
In the main code, they have just filtered the gene names and they haven't done anything with the logFC,  thus they get left out. I have written the code which can take care of this, please do let me know if I can push this or not.
Besides this, the logFC can be negative but still they are equally significant as that of positive, so can we use **abs** so that the genes for which logFC < -threshold, also holds??

**Comment by sayali7** [comment]
@giovp this issue can be closed since the documentation already states that "To preserve the original structure of adata.uns[‘rank_genes_groups’], filtered genes are set to NaN." . Users can simply drop the NANs for each cluster column in the adata.uns[‘rank_genes_groups_filtered’] dataframe.

**Comment by giovp** [comment]
thanks @sayali7 , @scverse/scanpy this issue could be potentially closed

**Comment by flying-sheep** [comment]
OK!
