### ISSUE TITLE
sc.tl.filter_rank_genes_groups:   min_fold_change doesn't work

### ISSUE THREAD

**Issue by brianpenghe** [scverse/scanpy#1447]
Scanpy 1.5.0
Out of curiousity I set min_fold_change to different values but it didn't work. Even when I set min_fold_change=100 it doesn't shorten the gene list.

So is it because the filters are working in an OR logic? If that's the case, I don't think the default values for each filter should be the ones you set - they should be a very harsh condition to make sure customer-specified parameters are the bottleneck.

**Comment by fidelram** [comment]
Please check https://github.com/theislab/scanpy/issues/863
