### ISSUE TITLE
Filename prefix

### ISSUE THREAD

**Issue by fbrundu** [scverse/scanpy#145]
When I use `pl.tsne` with autosave, the figure is saved with the same name `tsne.png`, independent of the data displayed (for example, it has the same name either if you are displaying the colors from louvain in one single suplots, or the expression of several marker genes in different subplots).

Is there a way to define a prefix for the figure, in order to automatically execute `pl.tsne` without overwriting the last tsne result? Figure directory setting is not useful in this case, since I may want to display several tsne for the same project.

**Comment by falexwolf** [comment]
I'm improving on this whole organization... Right now you can set the global variable: `sc.settings.figdir = path_to_some_dir/prefix_` or you can use `save='_mysuffix.pdf'` in any plotting function.

Does this help?

**Comment by fbrundu** [comment]
Yes perfect, thanks.
