### ISSUE TITLE
Generate scanpy.pl.stacked_violin

### ISSUE THREAD

**Issue by ccruizm** [scverse/scanpy#1450]
Good day!

I have been looking at the nice core functions for plotting but could not find a way to generate the enclosed plot. Any suggestions on how to do it? Thanks in advance!! (Sorry I could not change the label to question)

<img width="256" alt="Screenshot 2020-10-10 at 10 41 05" src="https://user-images.githubusercontent.com/37718031/95650641-1d485400-0ae5-11eb-965f-963d17227ec8.png">

**Comment by giovp** [comment]
does this help?
https://scanpy.readthedocs.io/en/stable/api/scanpy.pl.stacked_violin.html

**Comment by ccruizm** [comment]
Thanks for the reply. I looked at that source but I am still not able to generate that plot. I can generate stacked violin plots, as in the core plotting vignette, but have not found a way to draw the plot like the one above (adding the barplot on top of the violin plot, etc.). Any additional advice on how to do it? Thanks again!

**Comment by fidelram** [comment]
The latest version of scanpy added the possibility to enhance the plots in multiple ways. For this you need to use the new classes documented here https://scanpy.readthedocs.io/en/stable/api/scanpy.plotting.html#classes

In particular you want to check the function `add_totals()`: https://scanpy.readthedocs.io/en/stable/api/scanpy.pl.StackedViolin.add_totals.html#scanpy.pl.StackedViolin.add_totals

For your case you can do:
```PYTHON
adata = sc.datasets.pbmc68k_reduced()
markers = {{'T-cell': 'CD3D', 'B-cell': 'CD79A', 'myeloid': 'CST3'}}
sc.pl.StackedViolin(adata, markers, groupby='bulk_labels').add_totals().show()
```

Other options using the function that you are familiar with is:

```PYTHON
# here return_fig=True is used
plot = sc.pl.stacked_violin(adata, markers, groupby='bulk_labels', return_fig=True)
plot.add_totals().show()
```

You can find further info here: https://github.com/theislab/scanpy/pull/1210

**Comment by ccruizm** [comment]
Thank you for your help! Super useful.
