### ISSUE TITLE
Not able to select subset from clustered data which is added externally (k-means)

### ISSUE THREAD

**Issue by saiteja-danda** [scverse/scanpy#1452]
My issue is...
1. I read the data into anndata and performed all preprocessed steps and then used data matrix to perform non-linear dimensionality reduction (DR).
2. I performed DR and k-means clustering.
3. I added back the data into one of the components (X_tsne)
4. Added KM labels also.

Now, I am not able to select the clusters based on the cluster.
I want to select one of the clusters and perform clustering on that.

Please find the code snippets below.

mlle_3d_data=pd.read_csv("C:/Users/saite/source/df.csv")
mlle_3dc_data=pd.read_csv("C:/Users/saite/source/dfc.csv")

adata.obsm['X_tsne']=np.asanyarray(mlle_3d_data)
adata.obs['km']=list(mlle_3dc_data['clusters'])
adata.obs['km']=adata.obs['km'].astype('category')
sc.pl.tsne(adata,color=['km'])

------------------
I am trying to select based on the cluster number how we do with leiden or louvain clustering, but I am not seeing any data.
Please help me.

**Comment by LuckyMD** [comment]
Hi @saiteja-danda,

I cannot reproduce your code above as I don't have your data. Could you try to generate a minimal reproducible example with data from e.g., `sc.datasets.pbmc68k_reduced()`?

In general, could you check the output of `adata.obs['km'].value_counts()` to check whether the covariate you added was correctly stored? What output are you getting? You didn't share an error message.

**Comment by eroell** [comment]
As we haven't heard back after the followup we will close the issue for now, hopefully you obtained the expected behaviour in the end :)

However, please don't hesitate to reopen this issue or create a new one if you have any more questions or run into any related problems in the future.

Thanks for being a part of our community! :)
