### ISSUE TITLE
Invert dendrogram order in matrix plot

### ISSUE THREAD

**Issue by LouisK92** [scverse/scanpy#1458]
I was trying to invert (/ mirror / reverse) the order of a dendrogram and correlation matrix when using `sc.pl.correlation_matrix()`. I didn't find a raised issue or a solution on that. Here is a (hacky) solution that solves the issue by applying the function `invert_dendrogram()`. Might be helpful if somebody runs into that issue. Maybe it could be interesting to add an "invert" option in the plotting functions?
   
Code example:
```
def invert_dendrogram(adata,key):
    u = adata.uns[f'dendrogram_{key}']
    u['categories_idx_ordered'] = u['categories_idx_ordered'][::-1]
    tmp = u['dendrogram_info']['icoord']
    u['dendrogram_info']['icoord'] = (np.max(tmp) + np.min(tmp)) - tmp

pbmc = sc.datasets.pbmc68k_reduced()
key = 'bulk_labels'
    
a = pbmc.copy()
sc.tl.dendrogram(a,key)
sc.pl.correlation_matrix(a,key,figsize=(5,3.5))

a = pbmc.copy()
sc.tl.dendrogram(a,key)
invert_dendrogram(a,key)
sc.pl.correlation_matrix(a,key,figsize=(5,3.5))
```

**Comment by giovp** [comment]
@LouisK92 is this related to #1300 ?
If so, there is a comment with solution, would that work?

**Comment by fidelram** [comment]
I don't quite understand what you want to do, but an easy solution is to invert the the ylim or xlim of the plot.

For example:

```PYTHON
aa = sc.datasets.pbmc68k_reduced()
rcParams['figure.figsize'] = 4,1
sc.tl.dendrogram(aa, groupby = 'bulk_labels')
ax = sc.pl.dendrogram(aa, groupby = ["bulk_labels"], show=False)
xmin, xmax = ax.get_xlim()
ax.set_xlim(xmax, xmin)
```

<img width="493" alt="image" src="https://user-images.githubusercontent.com/4964309/106350619-c904f200-62d6-11eb-912d-5744fc01c537.png">
