### ISSUE TITLE
Can't draw graph edges in sc.pl.embedding

### ISSUE THREAD

**Issue by emdann** [scverse/scanpy#1459]
Hi,
Seems like there is something wrong with the edge plotting on embeddings

```python
import scanpy as sc
adata = sc.datasets.pbmc3k_processed()
sc.pl.umap(adata, edges=True)
```

```pytb
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-ea865731ec82> in <module>
----> 1 sc.pl.umap(adata, edges=True)

~/.local/lib/python3.7/site-packages/scanpy/plotting/_tools/scatterplots.py in umap(adata, **kwargs)
    613     If `show==False` a :class:`~matplotlib.axes.Axes` or a list of it.
    614     """
--> 615     return embedding(adata, 'umap', **kwargs)
    616 
    617 

~/.local/lib/python3.7/site-packages/scanpy/plotting/_tools/scatterplots.py in embedding(adata, basis, color, gene_symbols, use_raw, sort_order, edges, edges_width, edges_color, neighbors_key, arrows, arrows_kwds, groups, components, layer, projection, img_key, crop_coord, alpha_img, bw, library_id, color_map, palette, size, frameon, legend_fontsize, legend_fontweight, legend_loc, legend_fontoutline, vmax, vmin, add_outline, outline_width, outline_color, ncols, hspace, wspace, title, show, save, ax, return_fig, **kwargs)
    425 
    426         if edges:
--> 427             _utils.plot_edges(ax, adata, basis, edges_width, edges_color, neighbors_key)
    428         if arrows:
    429             _utils.plot_arrows(ax, adata, basis, arrows_kwds)

~/.local/lib/python3.7/site-packages/scanpy/plotting/_utils.py in plot_edges(axs, adata, basis, edges_width, edges_color, neighbors_key)
    504                 ax=ax,
    505                 width=edges_width,
--> 506                 edge_color=edges_color,
    507             )
    508             edge_collection.set_zorder(-2)

~/.local/lib/python3.7/site-packages/networkx/drawing/nx_pylab.py in draw_networkx_edges(G, pos, edgelist, width, edge_color, style, alpha, arrowstyle, arrowsize, edge_cmap, edge_vmin, edge_vmax, ax, arrows, label, node_size, nodelist, node_shape, connectionstyle, **kwds)
    577     edge_pos = np.asarray([(pos[e[0]], pos[e[1]]) for e in edgelist])
    578 
--> 579     if not cb.iterable(width):
    580         lw = (width,)
    581     else:

AttributeError: module 'matplotlib.cbook' has no attribute 'iterable'
```
![Screenshot 2020-10-16 at 16 10 20](https://user-images.githubusercontent.com/32264060/96275744-ff3d9080-0fc9-11eb-8706-d398e3b08c79.png)

#### Versions

<details>

WARNING: If you miss a compact list, please try `print_header`!
-----
anndata     0.7.4
scanpy      1.6.0
sinfo       0.3.1
-----
PIL                 7.2.0
anndata             0.7.4
atomicwrites        1.3.0
attr                20.2.0
backcall            0.2.0
cffi                1.14.3
colorama            0.4.3
cycler              0.10.0
cython_runtime      NA
dateutil            2.8.1
decorator           4.4.2
defusedxml          0.6.0
future_fstrings     NA
get_version         2.1
google              NA
h5py                2.10.0
igraph              0.8.2
importlib_metadata  0.23
ipykernel           5.3.4
ipython_genutils    0.2.0
ipywidgets          7.5.1
jedi                0.17.2
joblib              0.14.0
kiwisolver          1.1.0
legacy_api_wrap     1.2
leidenalg           0.8.1
llvmlite            0.34.0
louvain             0.6.1+2.g8073db7
matplotlib          3.3.2
more_itertools      NA
mpl_toolkits        NA
natsort             6.0.0
networkx            2.3
numba               0.51.2
numexpr             2.7.0
numpy               1.19.1
packaging           20.4
pandas              1.1.2
parso               0.7.1
pexpect             4.8.0
pickleshare         0.7.5
pkg_resources       NA
pluggy              0.13.0
prompt_toolkit      3.0.7
psutil              5.7.2
ptyprocess          0.6.0
py                  1.8.0
pycparser           2.20
pygments            2.7.1
pyparsing           2.4.2
pytest              5.2.1
pytz                2019.2
scanpy              1.6.0
scipy               1.5.2
setuptools_scm      NA
simplejson          3.17.2
sinfo               0.3.1
six                 1.15.0
sklearn             0.21.3
sphinxcontrib       NA
storemagic          NA
tables              3.5.2
texttable           1.6.3
tornado             6.0.4
tqdm                4.36.1
traitlets           4.3.3
typing_extensions   NA
umap                0.3.10
wcwidth             0.2.5
xlrd                1.2.0
yaml                5.1.2
zipp                NA
zmq                 19.0.2
-----
IPython             7.18.1
jupyter_client      6.1.7
jupyter_core        4.6.3
notebook            6.1.4
-----
Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:25:08) [GCC 7.5.0]
Linux-4.4.0-190-generic-x86_64-with-debian-buster-sid
24 logical CPU cores, x86_64
-----
Session information updated at 2020-10-16 15:10

</details>

**Comment by giovp** [comment]
Hi,

you might have conflicts with matplotlib versions, googling raised this [issue](https://stackoverflow.com/questions/53421905/matplotlib-attributeerror-module-matplotlib-cbook-has-no-attribute-define-a)

I could reproduce the result
```python
import scanpy as sc
adata = sc.datasets.pbmc3k_processed()
sc.pl.umap(adata, edges=True)
```
![image](https://user-images.githubusercontent.com/25887487/96875694-cee96c80-1477-11eb-883f-bb1feb0d5f0e.png)

**Comment by giovp** [comment]
@emdann will close this for now, feel free to reopen if problem persist!
