### ISSUE TITLE
scanpy cannot be imported in my windows system

### ISSUE THREAD

**Issue by Sophia409** [scverse/scanpy#1468]
Hi,
I couldn't import scanpy due to an error: DLL load failed. I have checked pre-existing issues, but all of them seem to be an h5py issue. My error report seems different from them.
```
>>> import scanpy as sc
D:\Anaconda\lib\site-packages\dask\config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\yuhong\AppData\Roaming\Python\Python37\site-packages\scanpy\__init__.py", line 36, in <module>
    from . import tools as tl
  File "C:\Users\yuhong\AppData\Roaming\Python\Python37\site-packages\scanpy\tools\__init__.py", line 17, in <module>
    from ._sim import sim
  File "C:\Users\yuhong\AppData\Roaming\Python\Python37\site-packages\scanpy\tools\_sim.py", line 23, in <module>
    from .. import _utils, readwrite, logging as logg
  File "C:\Users\yuhong\AppData\Roaming\Python\Python37\site-packages\scanpy\readwrite.py", line 10, in <module>
    import tables
  File "C:\Users\yuhong\AppData\Roaming\Python\Python37\site-packages\tables\__init__.py", line 99, in <module>
    from .utilsextension import (
ImportError: DLL load failed: The specified procedure could not be found.

>>> print(sys.version)
3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]
```

**Comment by Koncopd** [comment]
Hi, if you use conda, try `conda install pytables`.
If you don't, try installing from the corresponding wheel here https://www.lfd.uci.edu/~gohlke/pythonlibs/#pytables

**Comment by Sophia409** [comment]
@Koncopd Hi, Thank you for the pointer. It seems to be a problem caused by pytables package. But I still couldn't import tables after installing and uninstalling pytables packages for many times. And I'm in Windows system.
(base) C:\Users\yuhong>python
```
(base) C:\Users\yuhong>conda list | grep pytables
pytables                  3.6.1            py37h14417ae_3    conda-forge  
Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 01:53:57) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tables
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\yuhong\AppData\Roaming\Python\Python37\site-packages\tables\__init__.py", line 99, in <module>
    from .utilsextension import (
ImportError: DLL load failed: The specified procedure could not be found.
```

**Comment by Koncopd** [comment]
You can also try creating a new conda environment and installing pytables there at first and try to import it.

**Comment by zzhmark** [comment]
`pytables` in pip is named `tables`, and scanpy `import tables` accordingly, so you have to separately install it using also pip, not conda. I suggest editing the [installation guide](https://scanpy.readthedocs.io/en/stable/installation.html).

Besides, my installing using `conda install -c bioconda scanpy` would always give conflicts with nvidia cuda versions, but changing the version makes nothing change except the conflict message. Is it a Windows feature?

**Comment by stefanpeidli** [comment]
I suspect it might be the same issue as in #454 , so a problem with building libraries for h5py (which pytables needs) since Windows misses a C++ compiler for it.
