### ISSUE TITLE
sc.datasets.pbmc3k_processed() returns 404

### ISSUE THREAD

**Issue by danielStrobl** [scverse/scanpy#1471]
The download of the anndata object of the pbmc_3k_processed dataset doesn't work, as the branch from which the object should be downloaded from changed from `master` to `main`.

https://github.com/theislab/scanpy/blob/256f5944cd03fc0b8b510d607502d7170f8e5813/scanpy/datasets/_datasets.py#L305

**Comment by giovp** [comment]
closed with #1472 , next time @danielStrobl you could just do `git commit -m "<commit-message> #1471"` and it would be automatically linked (and then closed if PR is merged)

**Comment by ivirshup** [comment]
Or have some text that says "Fixes #{issue_number}" in the initial PR comment.
