### ISSUE TITLE
Update function _download_visium_dataset

### ISSUE THREAD

**Issue by linanzhang** [scverse/scanpy#1475]
I noticed that 10x has released some new spatial gene expression datasets. Could you include them? It should be a simple change in this line [https://github.com/theislab/scanpy/blob/ab9247bdf8b7a3decc34a15b26fec813ea8fba0d/scanpy/datasets/_datasets.py#L323](url).

Also, I've encounter errors when using `scanpy.datasets.visium_sge`. It seems that the url is outdated. The link to the datasets is changed to be
`
https://support.10xgenomics.com/spatial-gene-expression/datasets/{version_id}/{sample_id}
`

Thank you!

**Comment by giovp** [comment]
yes! I've made a PR #1473 and waiting for approval, will keep you posted here!
