### ISSUE TITLE
set_figure_params() bug when running at command-line

### ISSUE THREAD

**Issue by sbridgett** [scverse/scanpy#1477]
- [X ] I have checked that this issue has not already been reported.
- [X ] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

When I run scanpy over an ssh connection to a remote Ubuntu Linux server (so not using the IPython notebooks), the scanpy "set_figure_params(...)" command just outputs an "In :", and I need to exit using [Ctrl][D]: 

### Minimal code sample (that we can copy&paste without having any data)
```
import scanpy as sc
sc.set_figure_params(figsize=(4, 4))
```
The output in console is:
```
In :

In :
```
and need to press [Crtrl][D] to exit, as otherwise this just loops "In :" repeatedly.

If I add "ipython_format=None":
```
sc.set_figure_params(figsize=(4, 4), ipython_format=None)
```
then this continues without any "In :", and I can continue with script.  

I think the reason for this is in the scanpy "_settings.py" file:
```
def set_figure_params(
    ......etc.....
    try:
        import IPython
        if isinstance(ipython_format, str):
                ipython_format = [ipython_format]
        IPython.display.set_matplotlib_formats(*ipython_format)
    except Exception:
        pass
    from matplotlib import rcParams
    .....etc......
```
where the:
```
    IPython.display.set_matplotlib_formats(*ipython_format)
```
produces this "In :" message loop.

I think this bug could be fixed by adding "if self._is_run_from_ipython():" before the "try: import IPython": 
```
def set_figure_params(
    ......etc.....
    if self._is_run_from_ipython():
        try:
            import IPython
            if isinstance(ipython_format, str):
                ipython_format = [ipython_format]
            IPython.display.set_matplotlib_formats(*ipython_format)
        except Exception:
            pass
```
The "try:" 
```
>>> import IPython
```
doesn't throw an exception, as IPython is installed:
```
$ pip show IPython
Name: ipython
Version: 7.18.1
Summary: IPython: Productive Interactive Computing
Home-page: https://ipython.org
Author: The IPython Development Team
Author-email: ipython-dev@python.org
License: BSD
Location: /slipstream/home/sbridgett/miniconda3/lib/python3.8/site-packages
Requires: pygments, jedi, prompt-toolkit, backcall, pexpect, setuptools, decorator, traitlets, pickleshare
Required-by: ipywidgets, ipykernel
```

whereas the _is_run_from_ipython() will correctly ``return False``, as ``__IPYTHON__`` gives an exception:
```
    def _is_run_from_ipython():
        """Determines whether run from Ipython.
        Only affects progress bars.
        """
        try:
            __IPYTHON__
            return True
        except NameError:
            return False
```

#### Versions

<details>

scanpy.logging.print_versions()
-----
anndata     0.7.4
scanpy      1.6.0
sinfo       0.3.1
-----
PIL                 8.0.0
anndata             0.7.4
cairo               1.20.0
cffi                1.14.0
colorama            0.4.4
cycler              0.10.0
cython_runtime      NA
dateutil            2.8.1
get_version         2.1
h5py                2.10.0
igraph              0.8.3
joblib              0.17.0
kiwisolver          1.2.0
legacy_api_wrap     1.2
leidenalg           0.8.2
llvmlite            0.34.0
matplotlib          3.3.2
mkl                 2.3.0
mpl_toolkits        NA
natsort             7.0.1
numba               0.51.2
numexpr             2.7.1
numpy               1.19.2
packaging           20.4
pandas              1.1.3
pkg_resources       NA
pyparsing           2.4.7
pytz                2020.1
scanpy              1.6.0
scipy               1.5.2
setuptools_scm      NA
sinfo               0.3.1
six                 1.14.0
sklearn             0.23.2
tables              3.6.1
texttable           1.6.3
typing_extensions   NA
wcwidth             0.2.5
-----
Python 3.8.3 (default, May 19 2020, 18:47:26) [GCC 7.3.0]
Linux-3.13.0-143-generic-x86_64-with-glibc2.10
32 logical CPU cores, x86_64
-----
Session information updated at 2020-11-01 11:37

</details>

**Comment by VolkerBergen** [comment]
Hey @ivirshup, 

`hasattr(__builtins__, "__IPYTHON__")` now seems to always return False, even if it's True when run from within the notebook. That causes figures to end up very blurry due to the missing png2x config. Am I missing anything?

**Comment by VolkerBergen** [comment]
[This](https://github.com/theislab/scvelo/blob/5aefd1e2d1157d92578698e5897b517e1a117cdb/scvelo/settings.py#L329) works, i.e. 
```
def _is_run_from_ipython(): 
    try:
        __IPYTHON__
        rreturn True
    except NameError:
        return False
```

**Comment by ivirshup** [comment]
> `hasattr(__builtins__, "__IPYTHON__")` now seems to always return False

I'm not seeing this behaviour, could you check what versions you're using?

<details>
<summary> My versions </summary>


```
-----
sinfo       0.3.1
-----
IPython             7.23.1
jupyter_client      6.1.11
jupyter_core        4.7.0
jupyterlab          2.2.9
notebook            6.3.0
-----
Python 3.8.9 (default, Apr  3 2021, 01:50:09) [Clang 12.0.0 (clang-1200.0.32.29)]
macOS-10.15.7-x86_64-i386-64bit
16 logical CPU cores, i386
-----
Session information updated at 2021-05-10 10:13
```

</details>

**Comment by VolkerBergen** [comment]
```
from scanpy._settings import ScanpyConfig
ScanpyConfig._is_run_from_ipython()
```
returns `False` when running from within a notebook (confirmed by 3 other colleagues), and causes non-vectorized figures.


<details><summary> Versions </summary>

```
sinfo       0.3.1
-----
IPython             7.23.1
jupyter_client      6.1.12
jupyter_core        4.7.1
jupyterlab          3.0.15
notebook            6.3.0
-----
Python 3.8.8 (default, Feb 24 2021, 21:46:12) [GCC 7.3.0]
Linux-5.4.0-1038-aws-x86_64-with-glibc2.10
16 logical CPU cores, x86_64
```
</details>

**Comment by ivirshup** [comment]
I think I see what's going on. I'm going to reclose this issue in favor of the two more specific ones I've opened on this.
