### ISSUE TITLE
Mismatching cluster color codes in sc.pl.heatmap

### ISSUE THREAD

**Issue by wkopp** [scverse/scanpy#1479]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

### Description
The issue is visible/reproducibe from the [plotting tutorial](https://scanpy-tutorials.readthedocs.io/en/latest/plotting/core.html#Heatmaps) in cell 23.
Here, as an example, Cluster 3/NK cells are associated with the marker genes GNLY and NKG7.
However, the cluster color code representing the rows and columns of the heatmap are mismatching. Cluster 3 is summarized using violet on the cell level (color bar below the heatmap) and using green for grouping Cluster 3 associated markers GNLY and NKG7 (color bar on the right). I would expect that these color codes match.

### Minimal code sample
Below are a few lines to reproduce this behaviour:
```python
import scanpy as sc

pbmc = sc.datasets.pbmc68k_reduced()
sc.tl.leiden(pbmc, key_added='clusters', resolution=0.5)

marker_genes_dict = {'NK': ['GNLY', 'NKG7'],
                     'T-cell': ['CD3D'],
                     'B-cell': ['CD79A', 'MS4A1'],
                     'Monocytes': ['FCGR3A'],
                     'Dendritic': ['FCER1A']}


sc.pl.heatmap(pbmc, marker_genes_dict, groupby='clusters', vmin=-2, vmax=2, cmap='RdBu_r', dendrogram=True, swap_axes=True)
```

**Comment by giovp** [comment]
Hi @wkopp 

you are defining group labels from this:
```python
marker_genes_dict = {'NK': ['GNLY', 'NKG7'],
                     'T-cell': ['CD3D'],
                     'B-cell': ['CD79A', 'MS4A1'],
                     'Monocytes': ['FCGR3A'],
                     'Dendritic': ['FCER1A']}
```

but none of those cluster labels are presents in `pbmc`.
If you run the function you'll also notice the warning

```
WARNING: Groups are not reordered because the `groupby` categories and the `var_group_labels` are different.
```
as in `adata.obs.clusters` there is no `NK` or `T-cell` category.

Try this, and you'll see that the warning disappear and plotting is consistent
```python
pbmc = sc.datasets.pbmc68k_reduced()
sc.tl.leiden(pbmc, key_added='clusters', resolution=0.1)

marker_genes_dict = {'1': ['GNLY', 'NKG7'],
                     '0': ['CD3D'],
                     '2': ['CD79A', 'MS4A1'],
                     '4': ['CD79A', 'MS4A1'],
                     '3': ['FCER1A']}


sc.pl.heatmap(pbmc, marker_genes_dict, groupby='clusters', vmin=-2, vmax=2, cmap='RdBu_r', dendrogram=True, swap_axes=True)
```

**Comment by wkopp** [comment]
Thank @giovp!
I have replaced the previous definition of `marker_genes_dict` with the one you suggested
```python
marker_genes_dict = {'1': ['GNLY', 'NKG7'],
                     '0': ['CD3D'],
                     '2': ['CD79A', 'MS4A1'],
                     '4': ['FCGR3A'],
                     '3': ['FCER1A']}
```
But I still seem to obtain inconsistent color codes. I also continue to obtain warnings

```
WARNING: dendrogram data not found (using key=dendrogram_clusters). Running `sc.tl.dendrogram` with default parameters. For fine tuning it is recommended to run `sc.tl.dendrogram` independently.
WARNING: Groups are not reordered because the `groupby` categories and the `var_group_labels` are different.
categories: 0, 1, 2, etc.
var_group_labels: 1, 0, 2, etc.
```

I have also tried to use different groupby arguments (`clusters` or `louvain`) and `dendrogram=True/False`, but this didn't seem to matter much regarding the color code matching. However, the warning disappear with `dendrogram=False`.

In all cases I observe that the ordering of the colors below the heatmap (from left to right) matches the ordering of the colors on the right (top to bottom). But that doesn't necessarily result in a correct matching of colors with respect to the cluster identities.

I am using `scanpy.__version__==1.5.1`

**Comment by giovp** [comment]
if you reproduce exactly this code, it still throws warning?
```python
pbmc = sc.datasets.pbmc68k_reduced()
sc.tl.leiden(pbmc, key_added='clusters', resolution=0.1)

marker_genes_dict = {'1': ['GNLY', 'NKG7'],
                     '0': ['CD3D'],
                     '2': ['CD79A', 'MS4A1'],
                     '4': ['CD79A', 'MS4A1'],
                     '3': ['FCER1A']}


sc.pl.heatmap(pbmc, marker_genes_dict, groupby='clusters', vmin=-2, vmax=2, cmap='RdBu_r', dendrogram=True, swap_axes=True)
```

The point about `groupby` argument is that the unique labels in that obs column need to match the ones in marker_genes_dict. So for instance, if
```python
adata.obs.clusters.unique() # ["foo","bar"]
marker_genes_dict = {
"foo":...,
"bar":...
}
```
if there is a mismatch, then the warning will be thrown

RE: colors, that as to do with whether you called any plotting function before that specific one. For whatever `adata.obs["your_feature"]`, the plotting functions look in `adata.uns` if there is a key `"your_feature_colors"`. If there is none, then a random one is picked. You'll see for pbmc you'll find one in e.g. "louvain" I believe, but for a new annotation (like yours with leiden) then you would have to call a plotting function before, or passing your own palette explictly

**Comment by wkopp** [comment]
Could you try to use `resolution=0.5`. For me, when using leiden clustering with `resolution=.1`, the issue/warning is not provoked, but with 0.5 it is, because there are more clusters identified.

**Comment by giovp** [comment]
exactly, the reason is that `resolution=0.5` returns more clusters than the one I listed above (from 0 to 4). Just include in the dictionary `marker_genes_dict` all of the clusters returned by res=1

**Comment by wkopp** [comment]
> all of the clusters returned by res=1

I'm not following. Do you mean I should add empty lists for clusters without known markers?

**Comment by giovp** [comment]
might complain with empty lists, but you could just add other markers
or, subset the anndata
```python
pbmc = sc.datasets.pbmc68k_reduced()
sc.tl.leiden(pbmc, key_added='clusters', resolution=1)

marker_genes_dict = {'1': ['GNLY', 'NKG7'],
                     '0': ['CD3D'],
                     '2': ['CD79A', 'MS4A1'],
                     '4': ['CD79A', 'MS4A1'],
                     '3': ['FCER1A']}


sc.pl.heatmap(
	pbmc[pbmc.obs.clusters.isin(["0", "2","1","4","3"]), :], 
	marker_genes_dict, 
	groupby='clusters', 
	vmin=-2, vmax=2, cmap='RdBu_r', dendrogram=True, swap_axes=True)
```

**Comment by wkopp** [comment]
Thank you, @giovp 

I see. So when using heatmap, the mapping of marker genes must represent all clusters.
It won't work if markers are supplied for only a subset of the clusters.

As far as I can tell, though, this is not apparent from the documentation of the function `help(sc.pl.heatmap)`.
Also, in the plotting tutorial, which I referred to in the beginning, only a subset of markers are supplied.
So, either the documentation and tutorial should be adjusted to make clear that markers must be supplied for all clusters. Or, which I would find great, heatmap could be adjusted to be able to display markers for a subset of the clusters, which I had assumed to be the case in the beginning.

Btw. from looking at the tutorial, I believe the same issue may apply to some other plotting functions, e.g. for [Tracksplot](https://scanpy-tutorials.readthedocs.io/en/latest/plotting/core.html#Tracksplot)

**Comment by giovp** [comment]
Mmh no, it does work as you expect, just need to turn the dendrogram off.
```python
pbmc = sc.datasets.pbmc68k_reduced()
sc.tl.leiden(pbmc, key_added="clusters", resolution=1)

marker_genes_dict = {
    "1": ["GNLY", "NKG7"],
    "0": ["CD3D"],
    "2": ["CD79A", "MS4A1"],
    "4": ["CD79A", "MS4A1"],
    "3": ["FCER1A"],
}


sc.pl.heatmap(
    pbmc,
    marker_genes_dict,
    groupby="clusters",
    vmin=-2,
    vmax=2,
    cmap="RdBu_r",
    dendrogram=False,
    swap_axes=True,
)
```

or just pass the list of markers (list, not mapping)
```python
pbmc = sc.datasets.pbmc68k_reduced()
sc.tl.leiden(pbmc, key_added="clusters", resolution=1)

marker_genes_list = ["GNLY", "NKG7"]


sc.pl.heatmap(
    pbmc,
    marker_genes_list,
    groupby="clusters",
    vmin=-2,
    vmax=2,
    cmap="RdBu_r",
    dendrogram=True,
    swap_axes=True,
)
```

If you pass a dict with incomplete annotation and request dendrogram, then it fails, and the warning says this clearly:
```
WARNING: Groups are not reordered because the `groupby` categories and the `var_group_labels` are different.
categories: 0, 1, 2, etc.
var_group_labels: 1, 0, 2, etc.
```
and it still produces a plot (yet unordered).

The `var_group_labels` is also described in `help(sc.pl.heatmap)` as you pointed out. I think the misunderstanding is that passing a mapping or a list the behaviour is different, although potentially expected since a mapping and a list are different things. This could probably be explained clearer in the `var_names` argument yes.

Just to go back to your original problem, in your case you were using as mapping categories that were not present in your `groupby` key altogether. This is a different issue, and probably the function should have thrown an error saying `var_group_labels` are not present in `categories`. 

If you feel like opening a PR for this, we would really appreciate!

**Comment by wkopp** [comment]
> Just to go back to your original problem, in your case you were using as mapping categories that were not present in your groupby key altogether. This is a different issue, and probably the function should have thrown an error saying var_group_labels are not present in categories.

Since I just copied the example from the tutorial, I think it would be great fix the handling of heatmap there. There, the problem is sort of two-fold: 1) as you mentioned, the groupby labels NK/T-cell etc. hadn't been defined before, and 2) that only markers for only a subset of the clusters are used (5 out of 9 clusters have markers) are used with `dendrogram=True`. Both of them independently provoke the warning/issue about the reordering.
Maybe an error would be appropriate not only for undefined groupby labels (as you suggested), 
but also for the case where cluster markers for only a subset of clusters are supplied, instead of delivering a warning and a potentially incorrect ordering.
In the latter case, an error with a message suggesting to use `dendrogram=False` would be worthwhile.

The danger with just printing a warning is that it might be 
missed/ignored by the user (e.g. if the function is used in a pipeline with lots of other outputs) 
and mismatching color codes might also not be apparent initially. 
For instance, it took me a while to even spot this issue, as i didn't notice the mismatching colors initially.
This confusion could be avoided if heatmap doesn't produce a plot at all when incorrect arguments are used.

I agree that your workarounds also work, but they don't fully serve as substitutes to make the plots as in the tutorial yet.

**Comment by giovp** [comment]
yes very good point, the tutorial needs to be fixed for sure because now it would fail.
trowing error in the heatmap is also probably the best way to go.
Thank you for reporting this! I'll have a look as soon as I have time
