### ISSUE TITLE
Issue with new h5py

### ISSUE THREAD

**Issue by michalk8** [scverse/scanpy#1480]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [x] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can copy&paste without having any data)

```python
# update to h5py e.g. as: pip install h5py==3.0.0
import scanpy as sc

adata = sc.datasets.blobs()
sc.read("foo.h5ad").obs_names  # names are bytes, not str
# Index([  b'0',   b'1',   b'2',   b'3',   b'4',   b'5',   b'6',   b'7',   b'8', ..., dtype='object', length=640)
```
When using `h5py==2.10.0`, it works as expected (i.e. the index type is str). The same happens for `.var_names` (I haven't check further). I'd recommend updating the requirements.txt oto `h5py<=2.10.0` for now.

Related h5py issue: https://github.com/h5py/h5py/issues/1732

Also, I've encoutered this bug when coming up with example (seems unrelated):
```python
import scanpy as sc

adata = sc.datasets.paul15()

sc.read('data/paul15/paul15.h5')
```
The last line raises:

```pytb
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-24-3d2f3a02bf09> in <module>
----> 1 sc.read('data/paul15/paul15.h5')

~/.miniconda3/envs/cellrank2/lib/python3.8/site-packages/scanpy/readwrite.py in read(filename, backed, sheet, ext, delimiter, first_column_names, backup_url, cache, cache_compression, **kwargs)
    110     filename = Path(filename)  # allow passing strings
    111     if is_valid_filename(filename):
--> 112         return _read(
    113             filename,
    114             backed=backed,

~/.miniconda3/envs/cellrank2/lib/python3.8/site-packages/scanpy/readwrite.py in _read(filename, backed, sheet, ext, delimiter, first_column_names, backup_url, cache, cache_compression, suppress_cache_warning, **kwargs)
    698     if ext in {'h5', 'h5ad'}:
    699         if sheet is None:
--> 700             return read_h5ad(filename, backed=backed)
    701         else:
    702             logg.debug(f'reading sheet {sheet} from file {filename}')

~/.miniconda3/envs/cellrank2/lib/python3.8/site-packages/anndata/_io/h5ad.py in read_h5ad(filename, backed, as_sparse, as_sparse_fmt, chunk_size)
    427     _clean_uns(d)  # backwards compat
    428 
--> 429     return AnnData(**d)
    430 
    431 

TypeError: __init__() got an unexpected keyword argument 'batch.names'


```

#### Versions

<details>

-----
anndata     0.7.4
scanpy      1.6.0
sinfo       0.3.1
-----
PIL                 8.0.1
absl                NA
anndata             0.7.4
autoreload          NA
backcall            0.2.0
cellrank            1.0.0
cffi                1.14.3
cycler              0.10.0
cython_runtime      NA
dateutil            2.8.1
decorator           4.4.2
docrep              0.3.1
future_fstrings     NA
get_version         2.1
h5py                2.10.0
igraph              0.8.3
ipykernel           5.3.4
ipython_genutils    0.2.0
jax                 0.2.5
jaxlib              0.1.56
jedi                0.17.2
joblib              0.17.0
kiwisolver          1.3.1
lapack              NA
legacy_api_wrap     1.2
leidenalg           0.8.1
llvmlite            0.34.0
louvain             0.7.0
matplotlib          3.3.2
mpl_toolkits        NA
natsort             7.0.1
numba               0.51.2
numexpr             2.7.1
numpy               1.19.4
opt_einsum          v3.3.0
packaging           20.4
pandas              1.1.4
parso               0.7.1
pexpect             4.8.0
pickleshare         0.7.5
pkg_resources       NA
progressbar         3.53.1
prompt_toolkit      3.0.8
psutil              5.7.3
ptyprocess          0.6.0
pygam               0.8.0
pygments            2.7.2
pyparsing           2.4.7
python_utils        NA
pytz                2020.4
scanpy              1.6.0
scipy               1.5.3
scvelo              0.2.2
setuptools_scm      NA
sinfo               0.3.1
six                 1.15.0
sklearn             0.23.2
sphinxcontrib       NA
storemagic          NA
tables              3.6.1
texttable           1.6.3
threadpoolctl       2.1.0
tornado             6.1
traitlets           5.0.5
wcwidth             0.2.5
wrapt               1.12.1
zmq                 19.0.2
-----
IPython             7.19.0
jupyter_client      6.1.7
jupyter_core        4.6.3
notebook            6.1.4
-----
Python 3.8.5 (default, Sep  4 2020, 07:30:14) [GCC 7.3.0]
Linux-5.8.0-3-amd64-x86_64-with-glibc2.10
8 logical CPU cores
-----
Session information updated at 2020-11-03 13:36

</details>

**Comment by galicae** [comment]
God bless you for this. It happens with all string fields everywhere (so `obs` and `var` columns, everything in `uns`).

**Comment by ivirshup** [comment]
Tracking this under https://github.com/theislab/anndata/issues/442

Basically, anndata does not work with h5py 3.0 at the moment.
