### ISSUE TITLE
`pip install -e .` raises LookupError: setuptools-scm was unable to detect version for '/home/ubuntu/code/scanpy'.

### ISSUE THREAD

**Issue by TheAustinator** [scverse/scanpy#1496]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [x] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

setuptools-scm can't find the package version when running `pip install -e` or `pip install .`. I stepped through `scanpy/_metadata.py`, and it does appear to be able to get `__version__` via `setuptools_scm.get_version` as opposed to using `._compat`. It seems like it may either be an issue with `setuptools_scm` itself or the combination of my environment and `pyproject.toml`. Any ideas?

### Minimal code sample (that we can copy&paste without having any data)

```bash
pip install -e .
```

```pytb
      File "/tmp/tmp7fu14tjf", line 280, in <module>
        main()
      File "/tmp/tmp7fu14tjf", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/tmp/tmp7fu14tjf", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-wb9dh0v3/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 161, in prepare_metadata_for_build_wheel        self.run_setup()
      File "/tmp/pip-build-env-wb9dh0v3/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 145, in run_setup
        exec(compile(code, __file__, 'exec'), locals())      File "setup.py", line 17, in <module>
        setup(
      File "/tmp/pip-build-env-wb9dh0v3/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/tmp/pip-build-env-wb9dh0v3/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 423, in __init__
        _Distribution.__init__(self, {
      File "/usr/lib/python3.8/distutils/dist.py", line 292, in __init__
        self.finalize_options()      File "/tmp/pip-build-env-wb9dh0v3/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 695, in finalize_options
        ep(self)
      File "/tmp/pip-build-env-wb9dh0v3/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 702, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/usr/local/lib/python3.8/dist-packages/setuptools_scm/integration.py", line 17, in version_keyword
        dist.metadata.version = _get_version(config)
      File "/usr/local/lib/python3.8/dist-packages/setuptools_scm/__init__.py", line 148, in _get_version
        parsed_version = _do_parse(config)
      File "/usr/local/lib/python3.8/dist-packages/setuptools_scm/__init__.py", line 110, in _do_parse        raise LookupError(
    LookupError: setuptools-scm was unable to detect version for '/home/ubuntu/code/scanpy'.
        Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
    
    For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj```
```
#### Versions

<details>

scanpy
problem is with installation, so scanpy.logging.print_versions()
commit: ef5a8ee57c2aef7778a069a49101a8998718e6d5

python
3.8.5

pip
20.0.2 

ubuntu
20.04

pip list
Package                   Version              Location                     
------------------------- -------------------- -----------------------------
analysaurus               0.0.1                /home/ubuntu/code/analysaurus
anndata                   0.7.5                
ansi2html                 1.5.2                
appdirs                   1.4.4                
argon2-cffi               20.1.0               
astroid                   2.4.2                
async-generator           1.10                 
attrs                     20.3.0               
autopep8                  1.5.4                
backcall                  0.2.0                
biopython                 1.78                 
black                     20.8b1               
bleach                    3.2.1                
bokeh                     2.2.3                
botocore                  1.19.18              
Brotli                    1.0.9                
cellforest                0.0.2                /home/ubuntu/code/cellforest 
certifi                   2019.11.28           
cffi                      1.14.3               
chardet                   3.0.4                
click                     7.1.2                
colorama                  0.4.4                
commonmark                0.9.1                
cycler                    0.10.0               
dash                      1.17.0               
dash-building-blocks      0.1.2                
dash-core-components      1.13.0               
dash-html-components      1.1.1                
dash-renderer             1.8.3                
dash-table                4.11.0               
dataclasses               0.6                  
dataforest                0.0.2                /home/ubuntu/code/dataforest 
dbus-python               1.2.16               
decorator                 4.4.2                
defusedxml                0.6.0                
distro-info               0.23ubuntu1          
entrypoints               0.3                  
fastcore                  1.3.5                
flake8                    3.8.4                
Flask                     1.1.2                
Flask-Compress            1.8.0                
future                    0.18.2               
get-version               2.1                  
gitdb                     4.0.5                
GitPython                 3.1.11               
h5py                      3.1.0                
hyperopt                  0.1.2                
idna                      2.8                  
importlib-metadata        2.0.0                
iniconfig                 1.1.1                
ipdb                      0.13.4               
ipykernel                 5.3.4                
ipympl                    0.5.8                
ipython                   7.19.0               
ipython-genutils          0.2.0                
ipywidgets                7.5.1                
isort                     5.6.4                
itsdangerous              1.1.0                
jedi                      0.17.2               
Jinja2                    2.11.2               
jmespath                  0.10.0               
joblib                    0.17.0               
json5                     0.9.5                
jsonschema                3.2.0                
jupyter-client            6.1.7                
jupyter-core              4.6.3                
jupyter-dash              0.3.1                
jupyter-lsp               0.9.2                
jupyterlab                2.2.9                
jupyterlab-code-formatter 1.3.6                
jupyterlab-git            0.23.1               
jupyterlab-latex          2.0.0                
jupyterlab-pygments       0.1.2                
jupyterlab-server         1.2.0                
jupyterlab-sql            0.3.3                
jupyterlab-templates      0.2.5                
jupytext                  1.6.0                
kiwisolver                1.3.1                
lazy-object-proxy         1.4.3                
legacy-api-wrap           1.2                  
llvmlite                  0.34.0               
markdown-it-py            0.5.6                
MarkupSafe                1.1.1                
matplotlib                3.3.3                
mccabe                    0.6.1                
mistune                   0.8.4                
mypy-extensions           0.4.3                
natsort                   7.0.1                
nbclient                  0.5.1                
nbconvert                 6.0.7                
nbdime                    2.1.0                
nbformat                  5.0.8                
nbresuse                  0.3.6                
nest-asyncio              1.4.3                
networkx                  2.5                  
notebook                  6.1.5                
numba                     0.51.2               
numexpr                   2.7.1                
numpy                     1.19.4               
packaging                 20.4                 
pandas                    1.1.4                
pandocfilters             1.4.3                
parso                     0.7.1                
path                      15.0.0               
pathspec                  0.8.1                
pathtools                 0.1.2                
patsy                     0.5.1                
peepdis                   0.1.13               
pexpect                   4.8.0                
pickleshare               0.7.5                
Pillow                    8.0.1                
pip                       20.0.2               
plotly                    4.12.0               
pluggy                    0.13.1               
prometheus-client         0.8.0                
prompt-toolkit            3.0.8                
psutil                    5.7.3                
ptvsd                     4.3.2                
ptyprocess                0.6.0                
py                        1.9.0                
pycodestyle               2.6.0                
pycparser                 2.20                 
pydocstyle                5.1.1                
pyflakes                  2.2.0                
Pygments                  2.7.2                
PyGObject                 3.36.0               
pylint                    2.6.0                
pymongo                   3.11.0               
pyparsing                 2.4.7                
pyrsistent                0.17.3               
pytest                    6.1.2                
python-apt                2.0.0+ubuntu0.20.4.1 
python-dateutil           2.8.1                
python-debian             0.1.36ubuntu1        
python-jsonrpc-server     0.4.0                
python-language-server    0.36.1               
pytoml                    0.1.21               
pytz                      2020.4               
PyYAML                    5.3.1                
pyzmq                     20.0.0               
regex                     2020.11.13           
requests                  2.22.0               
requests-unixsocket       0.2.0                
retrying                  1.3.3                
rich                      9.2.0                
rope                      0.18.0               
scikit-learn              0.23.2               
scikit-misc               0.1.3                
scipy                     1.5.4                
scriptedforms             0.10.1               
scvi-tools                0.7.1                
seaborn                   0.11.0               
Send2Trash                1.5.0                
setuptools                50.3.2               
setuptools-scm            4.1.2                
sinfo                     0.3.1                
six                       1.14.0               
smmap                     3.0.4                
snowballstemmer           2.0.0                
SQLAlchemy                1.3.20               
statsmodels               0.12.1               
stdlib-list               0.7.0                
tables                    3.6.1                
termcolor                 1.1.0                
terminado                 0.9.1                
testpath                  0.4.4                
threadpoolctl             2.1.0                
toml                      0.10.2               
torch                     1.7.0                
tornado                   6.1                  
tqdm                      4.51.0               
traitlets                 5.0.5                
typed-ast                 1.4.1 
typeguard                 2.10.0               
typing-extensions         3.7.4.3              
ujson                     4.0.1                
umap-learn                0.4.6                
unattended-upgrades       0.1                  
urllib3                   1.25.8               
watchdog                  0.10.3               
wcwidth                   0.2.5                
webencodings              0.5.1                
Werkzeug                  1.0.1                
wheel                     0.35.1               
widgetsnbextension        3.5.1                
wrapt                     1.12.1               
xeus-python               0.8.3                
xlrd                      1.2.0                
yapf                      0.30.0               
zipp                      3.4.0

</details>

**Comment by ivirshup** [comment]
@TheAustinator, can you replicate this in a fresh environment (e.g. conda)? It could help to limit the number of other installed packages.

@flying-sheep, any ideas?

**Comment by flying-sheep** [comment]
@TheAustinator does the `flit` branch work?

**Comment by TheAustinator** [comment]
Hey guys, thanks for getting back to me. @flying-sheep `pip install -e` isn't working on the flit branch because it doesn't have a `setup.py` -- is there another way to install?

**Comment by flying-sheep** [comment]
I merged it into master now. You can try a regular `pip install .` or `flit install -s` for an editable install (after installing flit) as described here: https://scanpy.readthedocs.io/en/latest/installation.html#development-version

Pip says that btw if you try `pip install -e .`

> A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.

**Comment by Zethson** [comment]
Guess this was solved? Feel free to reopen if not!
