### ISSUE TITLE
version problems

### ISSUE THREAD

**Issue by flying-sheep** [scverse/scanpy#15]
* installing the master branch via `pip3 install --user --upgrade git+https://github.com/theislab/scanpy.git` fails:

    ```
    UPDATING build/lib.linux-x86_64-3.5/None
    error: [Errno 2] No such file or directory: 'build/lib.linux-x86_64-3.5/None'
    ```
    
    maybe `_version.py` returns `None` instead of a version string for the master branch.

* installing the tag works: `pip3 install --user --upgrade git+https://github.com/theislab/scanpy.git@0.0` but the installed version will be `0.1`, not `0.0` as the tag says (i’m not sure 0.0 is a legal version anyway)

**Comment by falexwolf** [comment]
thanks! 

I think it's fixed, works for me now, was a bug in `setup.cfg`

**Comment by falexwolf** [comment]
0.0 is not a release, it's just a dummy tag.

if you upgrade now, the version will be `0.0+216.g2d10bdd`, where `0.0` marks the initial commit, `+216` one is 216 commits later, and `g2d10bdd` marks the installed commit

**Comment by falexwolf** [comment]
as soon as `0.1` is ready, this will be released and the version of the release will simply be `0.1`.

**Comment by falexwolf** [comment]
later development versions will then again show `0.1+NUMCOMMITS.gHASH` and it will be clear for the user which kind of version she/he uses

i think it makes sense, do you?

**Comment by flying-sheep** [comment]
jup, works and makes sense! thank you!
