### ISSUE TITLE
dpt didn't create a 'dpt_pseudotime' obs

### ISSUE THREAD

**Issue by chriscainx** [scverse/scanpy#150]
Hey guys! always write funny markdown so I just pasted a screenshot.

<img width="1052" alt="screen shot 2018-05-08 at 00 54 02" src="https://user-images.githubusercontent.com/8361080/39713705-52a13720-525a-11e8-96f2-1a88e7a7b4c5.png">

`sc.pl.dpt(mfdata)` yields same result.
Could this be a bug? Or did I miss some step?

Thanks++
Chris

**Comment by falexwolf** [comment]
Sorry about this, probably you didn't provide a `root` cell via `adata.uns['iroot'] = some_index`... My bad that this disappeared again from the docs... grrrmpf... I'll add it right away.

**Comment by falexwolf** [comment]
Ok, updated the docs... Sorry about that.

**Comment by chriscainx** [comment]
Thanks!
