### ISSUE TITLE
Better document `legend_loc=None` for embedding plots

### ISSUE THREAD

**Issue by dagarfield** [scverse/scanpy#1502]
- [x] Additional function parameters / changed functionality / changed defaults?
- [ ] New analysis tool: A simple analysis tool you have been using and are missing in `sc.tools`?
- [ ] New plotting function: A kind of plot you would like to seein `sc.pl`?
- [ ] External tools: Do you know an existing package that should go into `sc.external.*`?
- [ ] Other?

It is a lovely tool, but it would be great to be able to not plot figure legends in, e.g. sc.pl.umap, so that all plots (regardless of what annotation is being colored) are exactly the same size. Perhaps there is already a way to do this, but I've yet to find it. 

Thanks!

**Comment by ivirshup** [comment]
You can pass `legend_loc=None`.

Thanks for noting this. Looking at the docs, I can definitely see how this isn't clear.

```
legend_loc : str, optional (default: 'right margin')
    Location of legend, either `'on data'`, `'right margin'` or a valid keyword
    for the `loc` parameter of :class:`~matplotlib.legend.Legend`.
```

**Comment by dagarfield** [comment]
Tada! Works perfectly. 
Thanks for the tip, and may this GitHub comment serve as substrate to all future google searches on this issue.

**Comment by dagarfield** [comment]
So one small update here -- it works like a charm for categorical variables, but not for continuous variables.
e.g.
> sc.pl.umap(testData, save = fileName, color='CCL5',s=50,frameon=False,legend_loc = None)

Still gives something like a legend:
![image](https://user-images.githubusercontent.com/10536275/99786010-40234a80-2b1e-11eb-83ab-77c9341dab05.png)

Presumably this is because the color strip on the right is not actually a legend in the underlying matplotlib?

**Comment by aldakata** [comment]
This should be explicitly mentioned in the docs

**Comment by flying-sheep** [comment]
agreed, I’m doing a PR for it
