### ISSUE TITLE
Imaging Mass Cytometry data

### ISSUE THREAD

**Issue by pedrofale** [scverse/scanpy#1503]
Hi everyone,

Thank you for scanpy! I use it very frequently for my research. I am getting started with spatial data, and would like to ask if there is any prediction for when IMC data will be supported? You mention this in the [spatial transcriptomics tutorial](https://scanpy-tutorials.readthedocs.io/en/latest/spatial/basic-analysis.html) so I suppose it's coming soon -- but how soon?
If you have started something and need an extra pair of hands to get it done, I would be happy to contribute! 

Thanks,
Pedro

**Comment by giovp** [comment]
hi @pedrofale !
Thanks a lot for the interest! Yes indeed we are working on an extension that handles spatial data and should be public in ~1 month. I'll keep you posted here as soon as we have it ready.
question re: IMC. What's the data format that you are interested in importing to anndata? Is it something more elaborate than a feature matrix `(obs, features)` and spatial coordinates `(obs, coordinates)` ?

**Comment by eroell** [comment]
Just came across this open issue

I suppose with [SpatialData](https://spatialdata.scverse.org/en/latest/) and [squidpy](https://squidpy.readthedocs.io/en/stable/), this question has been addressed in the meanwhile. :)

We might close this issue soon, but please don't hesitate to reopen this issue or create a new one if you have more related questions.

Thanks for being a part of our community! :)

**Comment by pedrofale** [comment]
Indeed it has, thanks a lot!
