### ISSUE TITLE
Error exporting adata using sc.export_to.spring_project 

### ISSUE THREAD

**Issue by justinesjw** [scverse/scanpy#1510]
Hi, 

Thanks for the awesome tool!

May I know in which version can I find [`sc.export_to.spring_project`](https://scanpy.readthedocs.io/en/stable/external/scanpy.external.exporting.spring_project.html)? I have tried scanpy==1.6.0, 1.0.3, 1.1a1 but faced this error 

![image](https://user-images.githubusercontent.com/26448066/100419830-47b79600-30c0-11eb-9e08-b3ae1e18ea1b.png)

[This tutorial](https://nbviewer.jupyter.org/github/theislab/scanpy_usage/blob/master/171111_SPRING_export/SPRING_export.ipynb) indicates that it worked in scanpy==1.0.4, however, I failed to fix the bug to install version 1.0.4.

Any help will be great! 

Many thanks, 
Justine

**Comment by LuckyMD** [comment]
Hi @justinesjw,

As the help page you linked to suggests the function is called `scanpy.external.exporting.spring_project`

You could use:
```
import scanpy.external as sce
sce.exporting.spring_project(adata, project_dir=...)
```

**Comment by justinesjw** [comment]
Noted. Thanks for your help!
