### ISSUE TITLE
sc.pl.embedding with basis "spatial" has side-effects and is missing one row of points 

### ISSUE THREAD

**Issue by hspitzer** [scverse/scanpy#1534]
- [x] I have checked that this issue has not already been reported.
- [ ] I have confirmed this bug exists on the latest version of scanpy.
- [x] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

sc.pl.embedding with basis "spatial" behaves strangely. See code example below. 
- when "spatial" is an `unit` array, the resulting plot is missing the top row of points (I think there might be an overflow happening)
- when plotting edges and using basis "spatial", `adata.obsm["spatial"] is modified after calling `sc.pl.embedding`
@giovp 

### Minimal code sample (that we can copy&paste without having any data)

```python
import numpy as np
import anndata as ad
import scanpy as sc
import matplotlib.pyplot as plt
print(sc.__version__)

arr = np.array([[1888,   55],
       [1887,   54],
       [1888,   54],
       [1889,   54],
       [1887,   55],
       [1889,   55],
       [1887,   56],
       [1888,   56],
       [1889,   56]], dtype=np.uint8)
conn = np.array([[0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1., 0., 0., 0., 0.],
       [1., 1., 0., 1., 1., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 1., 1., 0.],
       [1., 0., 1., 1., 0., 0., 0., 1., 1.],
       [1., 0., 0., 0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1., 1., 1., 0., 1.],
       [1., 0., 0., 0., 0., 1., 0., 1., 0.]])
a = ad.AnnData(arr)
a.uns = {'spatial': {'connectivities_key': 'spatial_connectivities', 'distances_key': 'spatial_distances', 'params': {'n_neighbors': 8, 'coord_type': None, 'radius': 1.5}}}
a.obsp['spatial_connectivities'] = conn
a.obsm['coords'] = arr.copy()
a.obsm['spatial'] = arr.copy()

sc.pl.embedding(a, 'coords',  edges=True, neighbors_key = 'spatial')
print('coords', a.obsm['coords'])
sc.pl.embedding(a, 'spatial')
print('spatial no edges', a.obsm['spatial'])
sc.pl.embedding(a, 'spatial',  edges=True, neighbors_key = 'spatial')
print('spatial edges', a.obsm['spatial'])
```

produces following output:

- expected (when plotting "coords")
![image](https://user-images.githubusercontent.com/13350159/101187374-9206bd00-3654-11eb-9b7c-38b5870ab815.png)
```
coords [[96 55]
 [95 54]
 [96 54]
 [97 54]
 [95 55]
 [97 55]
 [95 56]
 [96 56]
 [97 56]]
```

- when plotting "spatial" without edges (obsm is not modified)
![image](https://user-images.githubusercontent.com/13350159/101187899-40aafd80-3655-11eb-9738-9899efba9d52.png)
```
spatial no edges [[96 55]
 [95 54]
 [96 54]
 [97 54]
 [95 55]
 [97 55]
 [95 56]
 [96 56]
 [97 56]]
```

- when plotting "spatial" with edges (obsm is modified)

![image](https://user-images.githubusercontent.com/13350159/101187963-5ae4db80-3655-11eb-9866-6824831b18a9.png)
```
spatial edges [[ 96 255]
 [ 95 254]
 [ 96 254]
 [ 97 254]
 [ 95 255]
 [ 97 255]
 [ 95   0]
 [ 96   0]
 [ 97   0]]
```

#### Versions

<details>

scanpy==1.6.1.dev70+g7f15d22d anndata==0.7.5 umap==0.4.6 numpy==1.19.4 scipy==1.5.3 pandas==1.1.4 scikit-learn==0.23.2 statsmodels==0.12.1 python-igraph==0.8.3 louvain==0.6.1 leidenalg==0.8.3

</details>

**Comment by giovp** [comment]
EDIT: the issue is that coordinate system in this case has origin bottom left, whereas coordinate system in visium is top left.
