### ISSUE TITLE
Can scanpy transform scATAC-seq peak matrix into "Gene activity matrix"?

### ISSUE THREAD

**Issue by xuebaliang** [scverse/scanpy#1539]
- [ ] Additional function parameters / changed functionality / changed defaults?
- [ ] New analysis tool: A simple analysis tool you have been using and are missing in `sc.tools`?
- [ ] New plotting function: A kind of plot you would like to seein `sc.pl`?
- [ ] External tools: Do you know an existing package that should go into `sc.external.*`?
- [ ] Other?

...
Sometimes we need to collapse the single cell ATAC-seq peak matrix to a "gene activity matrix", as same as in seurat, I wish the scanpy can also provide this function.

**Comment by LuckyMD** [comment]
Maybe this is more a feature request for [Episcanpy](https://github.com/colomemaria/epiScanpy)

**Comment by ivirshup** [comment]
@DaneseAnna, could you comment on whether this is something implemented in EpiScanpy?

**Comment by DaneseAnna** [comment]
Hi, yes there is such functionalities in episcanpy.
To transform a peak matrix into a gene activity matrix you can use epi.tl.geneactivity

**Comment by ivirshup** [comment]
Great, thanks for the info!
