### ISSUE TITLE
Hello All, I am trying to learn and create single cell RNA seq pipeline for my project. When I was doing quality control, I met this problem. Can anyone help me? Thank you a lot.

### ISSUE THREAD

**Issue by Pawan291** [scverse/scanpy#1559]
- [ ] I have checked that this issue has not already been reported.
- [ ] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can copy&paste without having any data)

```python
mito_genes = adata.var_names.str.startswith('mt-')
# for each cell compute fraction of counts in mito genes vs. all genes
# the `.A1` is only necessary as X is sparse (to transform to a dense array after summing)
adata.obs['percent_mito'] = np.sum(
    adata[:, mito_genes].X, axis=1).A1 / np.sum(adata.X, axis=1).A1
# add the total counts per cell as observations-annotation to adata
adata.obs['n_counts'] = adata.X.sum(axis=1).A1

print(sum(mito_genes))
```

```pytb
AttributeError                            Traceback (most recent call last)
<ipython-input-18-7f1a7fee3beb> in <module>
      2 # for each cell compute fraction of counts in mito genes vs. all genes
      3 # the `.A1` is only necessary as X is sparse (to transform to a dense array after summing)
----> 4 adata.obs['percent_mito'] = np.sum(
      5     adata[:, mito_genes].X, axis=1).A1 / np.sum(adata.X, axis=1).A1
      6 # add the total counts per cell as observations-annotation to adata

```

#### Versions

<details>
AttributeError: 'ArrayView' object has no attribute 'A1'

</details>

**Comment by LuckyMD** [comment]
Hi,

I guess this issue might be more appropriate in the [single-cell-tutorial github](https://github.com/theislab/single-cell-tutorial).

I assume that the AnnData object you are working with does not contain sparse data. In that case you can leave out the `.A1` from your commands. Also, you're currently working with an `ArrayView` rather than an AnnData object, which you can change with a `adata = adata.copy()` line.

**Comment by Pawan291** [comment]
Thank you very much for the help and link to tutorial. It works for me
