### ISSUE TITLE
matrixplot group order changes with pandas 1.2.0

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#1562]
@fidelram

The test `test_matrixplot_obj` fails if `pandas>1.2.0` as the groups order changes. These groups are meant to be sorted with `plot.add_totals(sort='descending')`. All groups have the same value here, so my assumption is this is fine. I'm going to change the test for now, but it'd be good to hear back from you on whether this is a bug or not.

It would probably be good if we could ensure a stable sort was used so this won't change in future.

**Comment by fidelram** [comment]
If I understand correctly, pandas > 1.2.0 `plot.add_totals(sort='descending')` returns a different sorting compared to previous version. However, most of the categories have the same number of cells and thus a different sorting is equally valid.

![image](https://user-images.githubusercontent.com/4964309/104478840-0a9d5980-55c3-11eb-94b0-b0e2092c55c3.png)

My suggestion is to use other dataset in which the number of cells per category is different and update the image.
