### ISSUE TITLE
split view

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/scanpy#1565]
Hi,
Cellranger supports split view according to smaples or clusters, they have the same x-axis range and y-axis range, then we can see the genes expression on split view. Does scanpy support this function ?
![split-view](https://user-images.githubusercontent.com/29703450/103519656-dfbf5100-4eb0-11eb-92a2-473fac842017.png)

**Comment by ivirshup** [comment]
Thanks for the suggestion. I believe this has been suggested before in #955, and is on the todo list.
