### ISSUE TITLE
hello, I am trying to use normalisation part of scanpy and encounter this error. I tried to install Louvain but it is not helping. could anyone please help me. Thank you  

### ISSUE THREAD

**Issue by Pawan291** [scverse/scanpy#1566]
- [ ] I have checked that this issue has not already been reported.
- [ ] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can copy&paste without having any data)

```python
#Perform a clustering for scran normalization in clusters
adata_pp = adata.copy()
sc.pp.normalize_per_cell(adata_pp, counts_per_cell_after=1e6)
sc.pp.log1p(adata_pp)
sc.pp.pca(adata_pp, n_comps=15)
sc.pp.neighbors(adata_pp)
sc.tl.louvain(adata_pp, key_added='groups', resolution=0.5)
```

```pytb
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-11-785c54721f17> in <module>
      8 sc.pp.pca(adata_pp, n_comps=15)
      9 sc.pp.neighbors(adata_pp)
---> 10 sc.tl.louvain(adata_pp, key_added='groups', resolution=0.5)

~\anaconda3\lib\site-packages\scanpy\tools\_louvain.py in louvain(adata, resolution, random_state, restrict_to, key_added, adjacency, flavor, directed, use_weights, partition_type, partition_kwargs, neighbors_key, obsp, copy)
    135             weights = None
    136         if flavor == 'vtraag':
--> 137             import louvain
    138             if partition_type is None:
    139                 partition_type = louvain.RBConfigurationVertexPartition

ModuleNotFoundError: No module named 'louvain'
```

#### Versions

<details>

[Paste the output of scanpy.logging.print_versions() leaving a blank line after the details tag]

</details>

**Comment by LuckyMD** [comment]
Hi @Pawan291, It seems `louvain` has not been properly installed in your environment. Could you post the output of `scanpy.logging.print_versions()` as suggested in the template? You should just need to `pip install louvain`.

**Comment by Pawan291** [comment]
I installed again louvain with this command (although i already tried this command 3 times) and it work for me now. Thank you very much for the help.

**Comment by LuckyMD** [comment]
Also, this code is from the single-cell-tutorial github. Thus, a better place to post an issue would be in that [github](https://github.com/theislab/single-cell-tutorial).
