### ISSUE TITLE
Kernel dies - sc.pp.neighbors

### ISSUE THREAD

**Issue by wicktir** [scverse/scanpy#1567]
Hi there.

Everytime I run the code _sc.pp.neighbors_ the kernel dies. Unfortunately, there is no error message or error code. It just dies while computing neighbors.

Other scanpy codes like _sc.pp.filter_cells_ and _sc.pp.filter_genes_ work without a problem.

I'm using:

- windows 10 64-bit 24 gb ram
- python 3.8.5 in jupyter notebook
- numpy 1.19.4
- scanpy 1.6.0

Is there someone who would be able to solve this issue?
Thank you very much!

**Comment by ivirshup** [comment]
Does this cause the same issue?

```python
import numpy as np
import umap

umap.UMAP().fit_transform(np.random.randn(10_000, 20))
```

And when you say "dies", is there a segfault message, or are you seeing a jupyter kernel failure message?

In general, this sounds like a numba issue. I'd recommend taking searching the `umap-learn` or `numba` repositories for similar issues.

**Comment by wicktir** [comment]
It causes exactly the same issue when I run:

```
import numpy as np
import umap
```
There is no segfault message. The jupyter kernel failure message is: 

_Kernel restarting. The kernel appears to have died. It will restart automatically._

**Comment by ivirshup** [comment]
First, make sure your versions of numba and umap are up to date.

Then running this without jupyter, just in python. I think jupyter is likely hiding whatever error the python process is crashing with. E.g.:

```sh
$ python3 -c "import numpy; import umap"
```

If this fails, I think you should be opening an issue upstream with numba or umap (if you can figure out which one is at fault).

I've had this sort of thing happen a few times. Some of the causes were:

* Multiple versions of C libraries being linked to
* Threading backends not working

I've been able to work around both of these in the past by using conda environments.

**Comment by LuckyMD** [comment]
sometimes the jupyter console logs give you an idea of what is happening as well. I've had this happen when you run out of memory.

**Comment by jnmark** [comment]
@wicktir Was there a solution for this problem that worked? I am running into the same issue.

**Comment by wicktir** [comment]
@jnmark Unfortunately, I haven't found a solution yet. I decided to run it on a different machine (macOS).

**Comment by fairliereese** [comment]
I didn't keep perfect track of the steps that I took to solve this or the exact versions of everything that I used but I'll try outlining what I did.

First I tried to upgrade numba and umap as suggested by the other individuals in the thread:
```bash
pip install --upgrade numba
pip install --upgrade umap-learn
```

Then I essentially reinstalled scanpy using the steps in their installation docs.

```bash
conda install seaborn scikit-learn statsmodels numba pytables
conda install -c conda-forge python-igraph leidenalg
pip install scanpy
```

I think I then ended up with a version of numpy that was incompatible with numba so I ran

```bash
pip install numpy==1.20
```

After each step, you should be able to run the code from above to check if your installations worked, which I used to pinpoint what still needed work in my environment:
```bash
python3 -c "import numpy as np; import umap; umap.UMAP().fit_transform(np.random.randn(10_000, 20))"
```

This seemed to fix my problems; I hope it's able to help others!

**Comment by ivirshup** [comment]
I would recommend creating fresh conda environments frequently, especially if you mix `conda` and `pip` installation. Upgrading them in finicky, and often results in a broken state.

**Comment by josephineyates** [comment]
I am running into the same issue and unfortunately running the steps as described here https://github.com/theislab/scanpy/issues/1567#issuecomment-968181500 does not solve my problem. My kernel systematically dies when I run `sc.pp.neighbors` (even with only 1,000 cells). What I am also confused about is that this used to work - I am guessing I updated a package somewhere that broke everything but I cannot identify what.

This is my config:
- MacBook Pro (13-inch, M1, 2020) - macOS Big Sur 11.5.2
- python 3.8.8
- numpy 1.20.0
- numba 0.51.2
- umap-learn 0.5.2

I have tried running the following code in Jupyter and then in a script to see if I could get more info on the bug:
```
unhealthy_cells = sc.read_h5ad("path/to/file")

unhealthy_cells.layers["counts"] = unhealthy_cells.X.copy()

sc.pp.normalize_total(unhealthy_cells,target_sum=10000)

sc.pp.log1p(unhealthy_cells)

sc.pp.scale(unhealthy_cells)

sc.tl.pca(unhealthy_cells)

sc.pp.neighbors(unhealthy_cells)
```
When I run it as a python script, I get the following error when getting to `sc.pp.neighbors` (everything else works): 
`zsh: illegal hardware instruction`

Is there anything I could do? 
Thank you for your help!

**Comment by brianpenghe** [comment]
I have the same issue even after updating numba, umap and scanpy :(

**Comment by brianpenghe** [comment]
> I didn't keep perfect track of the steps that I took to solve this or the exact versions of everything that I used but I'll try outlining what I did.
> 
> First I tried to upgrade numba and umap as suggested by the other individuals in the thread:
> 
> ```shell
> pip install --upgrade numba
> pip install --upgrade umap-learn
> ```
> 
> Then I essentially reinstalled scanpy using the steps in their installation docs.
> 
> ```shell
> conda install seaborn scikit-learn statsmodels numba pytables
> conda install -c conda-forge python-igraph leidenalg
> pip install scanpy
> ```
> 
> I think I then ended up with a version of numpy that was incompatible with numba so I ran
> 
> ```shell
> pip install numpy==1.20
> ```
> 
> After each step, you should be able to run the code from above to check if your installations worked, which I used to pinpoint what still needed work in my environment:
> 
> ```shell
> python3 -c "import numpy as np; import umap; umap.UMAP().fit_transform(np.random.randn(10_000, 20))"
> ```
> 
> This seemed to fix my problems; I hope it's able to help others!

I followed your instruction but it still threw errors:

<frozen importlib._bootstrap>:219: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject



Segmentation fault

**Comment by brianpenghe** [comment]
> I would recommend creating fresh conda environments frequently, especially if you mix `conda` and `pip` installation. Upgrading them in finicky, and often results in a broken state.

Creating a new environment and reinstalling everything worked for me. Thanks!

**Comment by FlyPythons** [comment]
`pip install -U pynndescent`
This fix my problems; I hope it's able to help others!

**Comment by deepcompbio** [comment]
conda install -c conda-forge pynndescent

This also fixed my problem. Thanks @FlyPythons for the hint.

**Comment by fenghuaxueyejhshyuu** [comment]
> conda install -c conda-forge pynndescent
> 
> This also fixed my problem. Thanks @FlyPythons for the hint.

Thanks!This also  work for me.
