### ISSUE TITLE
Embedding - set scatter colour when 'color' (by obs/var) is not used

### ISSUE THREAD

**Issue by Hrovatin** [scverse/scanpy#1568]
- [ x] Additional function parameters / changed functionality / changed defaults?
- [ ] New analysis tool: A simple analysis tool you have been using and are missing in `sc.tools`?
- [ ] New plotting function: A kind of plot you would like to seein `sc.pl`?
- [ ] External tools: Do you know an existing package that should go into `sc.external.*`?
- [ ] Other?

Add parameter for setting embedding/UMAP colour when the "color" parameter is not used - e.g. set one colour for all points. Currently, the only option to set colour for all cells seems to be to add additional constant obs feature and modify uns to set the colour for the new feature.

**Comment by ivirshup** [comment]
Soon, you can do:

```python
import scanpy as sc
pbmc = sc.datasets.pbmc68k_reduced()
sc.pl.umap(pbmc, na_color="purple")
```

<img width="752" alt="image" src="https://user-images.githubusercontent.com/8238804/103634345-0bb70100-4f9b-11eb-9557-44a94d8fc7cd.png">

Is this what you're looking for?

**Comment by ivirshup** [comment]
@Hrovatin, I think this has been addressed. Let me know if I should reopen this
