### ISSUE TITLE
Cluster content plot for integrated data

### ISSUE THREAD

**Issue by galicae** [scverse/scanpy#1573]
- [ ] Additional function parameters / changed functionality / changed defaults?
- [ ] New analysis tool: A simple analysis tool you have been using and are missing in `sc.tools`?
- [x] New plotting function: A kind of plot you would like to seein `sc.pl`?
- [ ] External tools: Do you know an existing package that should go into `sc.external.*`?
- [ ] Other?

I am integrating multiple datasets. In the integrated object I wanted to see for each cluster the percentage of each dataset it consisted of (also see [this question](https://scanpy.discourse.group/t/cluster-statistics/134) in the scanpy discourse group). I wrote code for it on my own, but am not sure which part of `sc.pl` you want it to go to, so here is the code for your consideration:

```python
import matplotlib.pyplot as plt
import scanpy as sc
import numpy as np

# given integrated object adata, clustered via the leiden algorithm and
# with the batch ID in the 'batch' slot, and a collection of batch_names:

# count the number of occurrences of each batch ID for each cluster ID
count_series = adata.obs.groupby(['leiden', 'batch']).size()
new_df = count_series.to_frame(name = 'size').reset_index()
# convert from multi index to pivot
constitution = new_df.pivot(index='leiden', columns='batch')['size']
# convert to %batch (but could be modified to show different things instead
perc_clust = np.array((constitution.T / np.sum(constitution.T, axis=0)))
# keep track of the batch, cluster IDs so we can use them for plotting
clusters = adata.obs.leiden.cat.categories
batches = adata.obs.batch.cat.categories

# actual plotting; basically stacked barplots
# replace styling with scanpy defaults probably?
fig, ax = plt.subplots()
ax.grid(False)
ax.bar(clusters, perc_clust[0], 0.6, yerr=0, label=platy_names[0])
bottom = np.zeros(clusters.shape)
for i, b in enumerate(batches):
    ax.bar(clusters, perc_clust[i], 0.6, bottom=bottom, yerr=0, label=batch_names[i])
    bottom += perc_clust[I]
    
# place legend not on top of the plot
ax.legend(loc='right', bbox_to_anchor=(1.2, 0.5));
```

End result should look something like this
![image](https://user-images.githubusercontent.com/1651067/104041019-ac463480-51d8-11eb-93ee-267deb4aa3f9.png)

**Comment by fidelram** [comment]
I have several plotting functions that allow to compare any two categorical columns in `.obs` to achieve similar output but never found the time to integrate them into scanpy. Is really quite some effort to add proper tests, documentation and code standards. I will be happy to share the code if other people is willing to help. 

One problem with the stacked bar plot is that with lot of samples it is difficult to compare the fractions. To solve this I had used the dot plot with good results, see for example a comparison of the `louvain` clusters and the `bulk labels` annotation from `sc.datasets.pbmc68k_reduced()`:

![image](https://user-images.githubusercontent.com/4964309/104466204-3e718280-55b5-11eb-9b87-ac3860af7979.png)

and 

![image](https://user-images.githubusercontent.com/4964309/104466234-49c4ae00-55b5-11eb-92c8-45140de9e107.png)

The dot plot also computes enrichment with respect to random expectations and sorts the rows and columns.

**Comment by eroell** [comment]
As we haven't heard back after the follow-up we will close the issue for now, hopefully you obtained the expected behaviour in the end :)

However, please don't hesitate to reopen this issue or create a new one if you have any more questions or run into any related problems in the future.

Thanks for being a part of our community! :)
