### ISSUE TITLE
Adding cell2location to the list of scRNA->spatial integration methods

### ISSUE THREAD

**Issue by vitkl** [scverse/scanpy#1574]
Hi!

I am wondering if you could add https://github.com/BayraktarLab/cell2location to your list of scRNA->spatial integration methods (https://scanpy-tutorials.readthedocs.io/en/latest/spatial/integration-scanorama.html).

Thanks!

**Comment by giovp** [comment]
Hi @vitkl !
that's a great idea yes, should be kept updated with most recent methods. 
Unfortuantely I don't have capacity now, do you mind opening an issue in https://github.com/theislab/scanpy-tutorials to keep as reminder? I will close this but of of course you could reference this in the tutorial repo.
Thank you!
