### ISSUE TITLE
Diff coverage

### ISSUE THREAD

**Issue by flying-sheep** [scverse/scanpy#1576]
@ivirshup https://stackoverflow.com/a/57222267/247482

`azurepipelines-coverage.yml`
```yaml
coverage:
  status:
    diff:
      target: 40%
```

**Comment by ivirshup** [comment]
Looks like this is not available for python yet ([docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/codecoverage-for-pullrequests?view=azure-devops#prerequisites))

> While you can collect and publish code coverage results for many different languages using Azure Pipelines, the code coverage for pull requests feature discussed in this document is currently available only for .NET and .NET core projects using the Visual Studio code coverage results format (file extension .coverage). Support for other languages and coverage formats will be added in future milestones.

**Comment by ivirshup** [comment]
Oh, but codecov is on now
