### ISSUE TITLE
shared high variable genes

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/scanpy#1578]
Hi,
Is it necessary to use only high variable genes for the downstream analysis ?
If an examperiment includes many batches, then each batch will give a different set of high variable genes, how to determine the shared high variable genes (intersection or union) when integrating the batches ? Does scany have any fucntion to get the  shared genes ?

**Comment by davidhbrann** [comment]
The `batch-key`option in `scanpy.pp.highly_variable_genes` provides this functionality, and adds `highly_variable_intersection` to `adata.var`. For more information, see the documentation: https://scanpy.readthedocs.io/en/stable/api/scanpy.pp.highly_variable_genes.html#scanpy.pp.highly_variable_genes.

**Comment by wangjiawen2013** [comment]
Please refer to this related issue:
https://github.com/10XGenomics/cellranger/issues/108#issuecomment-758455901
What about PCA in scanpy ?

**Comment by LuckyMD** [comment]
You don't have to use HVGs for downstream analysis, but it is typically done for two reasons (at least):
1. Using fewer genes is computationally less expensive for downstream analysis.
2. The signal-to-noise ratio is better with highly variable genes than in the full gene set.

The second point is usually particularly important, as even if one single gene doesn't contribute as much to the PCA if it has lower variance, if you have 15000 low-variance genes this does affect the embedding. If you'd like a rationale for why HVGs are used, please see our [best-practices review](http://msb.embopress.org/lookup/doi/10.15252/msb.20188746)

**Comment by wangjiawen2013** [comment]
Feature selection refers to excluding uninformative genes such as those which exhibit no meaningful biological variation across samples. Since scRNA-Seq experiments usually examine cells within a single tissue, only a small fraction of genes are expected to be informative since many genes are biologically variable only across different tissues (adopted from https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1861-6).
But, in fact some experimental design are very complex, such single-cell RNAseq of tissues from different development stage. The tissues can vary a log along the development timeline.
I find that the number of HVGs can affect data integration and batch effects correction. I've integrated seven cell samples collected at different development stage(1day, 2 day, 3 day, 4day, 5 day, 6 day, 7day after fertilization) with SCVI-tools, using 2000 HVGs, which then shows no "batch effect" (cells were mixed with no correlation among samples) left; on the other hand, using all genes, which shows still some extent of "batch effect" (some cells were clustered by time obviously) left. This could definitely affect the biological explaination, because the "batch effect" can be regarded as the difference of true biological difference at different development stage. The tissues are undergoing intensive differentiation process, so that the cell population are changing a lot during this process. Using only HVGs might lost these development process. 
In sum, HVGs are good for batch effect correction. The "batch effects" become less obvious when using less genes and more obvious when using more genes. However, more genes are good for discovery of new cell population. Does this make sense ?

**Comment by LuckyMD** [comment]
Yes, this makes a lot of sense. This is also what we found in our review of data integration methods and pre-processing decisions [here](https://www.biorxiv.org/content/10.1101/2020.05.22.111161v2).

I'm not sure I agree with "only a small fraction of genes are expected to be informative though". There is definitely a variable signal-to-noise ratio though.
