### ISSUE TITLE
Examples sections headings are wrong

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#1581]
From the `rank_genes_groups_matrixplot` docs:

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/8238804/104416321-b9439900-55c7-11eb-8690-f93312bef864.png">

The `Examples` heading is just showing up as text, should be styled.

**Comment by eroell** [comment]
Think this is fixed and can be closed right?

**Comment by flying-sheep** [comment]
The syntax was in place long ago, since https://github.com/scverse/scanpy/pull/1210

But yeah, we also made them render as `rubric`s I think, so they’re bold now.
