### ISSUE TITLE
Add build and `twine check` CI task

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#1585]
`twine check` is not great at telling you why it's failing. It would be easier to figure out what caused the break if we were continuously checking for this.

Inspired by finding out that `authors` can't have new lines, via an error that says `long_description` can't have section headings (which definitely isn't true).

**Comment by Zethson** [comment]
Currently being added to sfaira:
https://github.com/theislab/sfaira/pull/72/files#diff-de563ce0a02335898f4a4e1bca2fc074614122bfce30b980d7065142806e4defR38

Feel free to just copy the code.

**Comment by Zethson** [comment]
@ivirshup I've assigned myself and will do it this week.

**Comment by ivirshup** [comment]
That'd be great, thanks!

I was thinking it could replace this step in the test builds:

https://github.com/theislab/scanpy/blob/5fc12f4a918e21f0c57937b787d52040db046f01/.azure-pipelines.yml#L78-L81

And was thinking of using azure for it instead of actions, just to consolidate CI stuff a bit. I was thinking a build and check could just be a separate job? Open to suggestions on this however.

**Comment by Zethson** [comment]
Yeah, guess eventually we should settle on one CI service. Effectively we should get rid of Travis, since they have serious problems.

> I was thinking a build and check could just be a separate job?

Well you have to build the wheels to run the check anyways. But I did not have a look at the azure setup yet, so will see what I can come up with :)

**Comment by ivirshup** [comment]
> Well you have to build the wheels to run the check anyways

Oh, what I meant is that we sorta do a check in the same job as running the tests. I was thinking this should be separated out into a job which does "build and check" together, rather than including it in the testing job.

**Comment by Zethson** [comment]
Ahh, I see. Yeah, fine with me.
