### ISSUE TITLE
Default plotting order for cluster annotations

### ISSUE THREAD

**Issue by LuckyMD** [scverse/scanpy#1588]
- [x] Additional function parameters / changed functionality / changed defaults?

As this has come up several times (in my own work and in issue reports such as #891), I was wondering if it might be a good idea to have `sort_order=False` (or even better to use random ordering) as default for plotting any clustering result. That would require `sc.tl.louvain()` and `sc.tl.leiden()` to store a flag in `adata.uns` stating which columns are clustering columns, and `sc.pl.embedding()` to set `sort_order` according to this flag. 

I would argue it's inherently wrong to plot a particular cluster on top when looking at clustering results as this complicates the interpretation of a visualization and leads to misinterpretations when we have overlapping embedding locations of cells.

What do you think @ivirshup @fidelram?

**Comment by ivirshup** [comment]
I thought we didn't sort for categorical plots? Other than when there are "null" values, then `sort_order=True` puts non-null values on top, which `sort_order=False` disables.

https://github.com/theislab/scanpy/blob/1878644614ecba4b265241e68b07cc32ac13db4d/scanpy/plotting/_tools/scatterplots.py#L255-L262

Do you have examples of this not being the case?

I have been thinking about what we should do if there are cells from multiple clusters overlapping in a pixel. Some way of letting users know something is being hidden.

**Comment by LuckyMD** [comment]
Hmm, you're right. I think it must have been the that the ordering of cells in the `adata` object was also non-random. We had this quite a bit in the benchmarking data integration project while plotting batch. In several methods (e.g., scanorama), individual batch anndata objects are concatenated to generate the final output, which results in batch-ordered anndata objects. 

Maybe instead of just having `sort_order=False` it would be better to have randomized ordering for plotting categorical variables? Unless it is an ordered categorical I guess.

**Comment by ivirshup** [comment]
I was thinking it could make sense to have a `sort_order="random"` option, but then do we also need to start handling seeds?

Overall, I'm not sure random ordering is really a solution for overplotting. Smaller points, a faceted plot, or figuring out where there are overlapping groups seem like much more principled solutions.

**Comment by ivirshup** [comment]
Ha, I was looking through some notebooks about this and realized we have discussed this problem before: https://github.com/theislab/scanpy/issues/1263 😆.

Let's consolidate this to that issue
