### ISSUE TITLE
Where can I find log-fold change in gene expression for the markers

### ISSUE THREAD

**Issue by DoruMP** [scverse/scanpy#159]
Does scanpy store log fold change, p-value and marker type flag (negative vs positive) somewhere? It looked at scObj.uns["rank_genes_groups"] but found only 3 fields: params, scores and names.

**Comment by falexwolf** [comment]
No, it currently doesn't. Instead it uses the `scores`... usually some "differential z-score" that goes into the t-test. We will extend differential testing in the future.

**Comment by a-munoz-rojas** [comment]
Just wanted to bring this question back up - it would be great if we could get fold changes and p-values returned from the relevant methods for differential testing in scanpy. Thanks!

**Comment by falexwolf** [comment]
There now is a much more powerful differential testing package `diffxpy`, @davidsebfischer, which easily integrates into Scanpy.

@a-munoz-rojas Would you consider making a pull request that adds log-fold changes for t-test etc. in `rank_genes_groups`? My bandwidth is limited these days, I will certainly do it at some point, but it's faster if you do it.

**Comment by a-munoz-rojas** [comment]
@falexwolf Thanks for pointing out this package, I'll give it a try. I'll also give the pull request a shot - I'm still learning my way around this package but if I can do it I'll submit it for sure.

**Comment by wflynny** [comment]
@falexwolf Is there anyplace where we can read into `diffxpy`?  I've been benchmarking available marker gene detection algorithms and am interested to see what is included in this new package.

**Comment by a-munoz-rojas** [comment]
@davidsebfischer @falexwolf Also, where can we get this package? I tried doing a pip install, and while the package is listed the installation failed.

**Comment by flying-sheep** [comment]
@falexwolf you were a little quick: @davidsebfischer didn’t turn it public yet. maybe david would like to send it to you for beta testing?

**Comment by falexwolf** [comment]
Yes, he told me just yesterday that it's not public yet, but it will soon be.

**Comment by davidsebfischer** [comment]
Hi @a-munoz-rojas, diffxpy will be public very soon, once we finished running all benchmarks that we need for validation. I would be happy to help you set it up if you still want to give it a go then!

**Comment by a-munoz-rojas** [comment]
Hi @davidsebfischer, sounds great! Let me know and I'd be happy to give it a try. Thanks!
