### ISSUE TITLE
Bug when running PCA in chunked mode

### ISSUE THREAD

**Issue by parashardhapola** [scverse/scanpy#1590]
- [x] I have checked that this issue has not already been reported.
- [ ] I have confirmed this bug exists on the latest version of scanpy.
- [x] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

```python
sc.tl.pca(adata, svd_solver='arpack', use_highly_variable=True, chunked=True, chunk_size=1000)
```

```pytb
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'int'
```

I believe the error is due overwriting of `start` variable.
 It is declared in [line 116](https://github.com/theislab/scanpy/blob/master/scanpy/preprocessing/_pca.py#L116) but is overwritten by loop variable of same name in [line 172](https://github.com/theislab/scanpy/blob/master/scanpy/preprocessing/_pca.py#L172)

#### Versions

<details>

-----
anndata     0.7.5
scanpy      1.6.0
sinfo       0.3.1
-----
PIL                 8.1.0
anndata             0.7.5
asciitree           NA
cffi                1.14.3
cloudpickle         1.6.0
constants           NA
cycler              0.10.0
cython_runtime      NA
dask                2020.12.0
dateutil            2.8.1
fasteners           NA
get_version         2.1
h5py                3.1.0
highs_wrapper       NA
igraph              0.8.3
joblib              1.0.0
kiwisolver          1.3.1
legacy_api_wrap     1.2
leidenalg           0.8.3
llvmlite            0.35.0
matplotlib          3.3.3
mpl_toolkits        NA
msgpack             1.0.2
natsort             7.1.0
numba               0.52.0
numcodecs           0.7.2
numexpr             2.7.2
numpy               1.19.4
packaging           20.8
pandas              1.2.0
pkg_resources       NA
psutil              5.8.0
pyparsing           2.4.7
pytz                2020.5
scanpy              1.6.0
scipy               1.6.0
setuptools_scm      NA
sinfo               0.3.1
six                 1.15.0
sklearn             0.24.0
sparse              0.11.2
tables              3.6.1
tblib               1.7.0
texttable           1.6.3
tlz                 0.11.1
toolz               0.11.1
typing_extensions   NA
yaml                5.3.1
zarr                2.6.1
-----
Python 3.8.5 (default, Sep  4 2020, 07:30:14) [GCC 7.3.0]
Linux-3.10.0-1062.4.1.el7.x86_64-x86_64-with-glibc2.10
2 logical CPU cores, x86_64
-----

</details>

**Comment by ivirshup** [comment]
Thanks for the report! Should be fixed by #1592
