### ISSUE TITLE
Heatmap inconsistent order/swap_axes

### ISSUE THREAD

**Issue by michalk8** [scverse/scanpy#1591]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [x] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can copy&paste without having any data)

```python
import numpy as np
import pandas as pd
import scanpy as sc
from anndata import AnnData


a = AnnData(np.random.RandomState(42).normal(size=(50, 50)),
            obs={"foo": pd.Categorical(np.random.choice([0, 1, 2], size=50))})

sc.pl.heatmap(a, var_names=a.var_names[:5], groupby=None, swap_axes=True)  # is shifted to the left (fig. 1)
sc.pl.heatmap(a, var_names=a.var_names[:5], groupby="foo", swap_axes=True)  # see the tb (if there's only 1 category, in the group, it doesn't crash)

a.X[:16, :] = 10 + np.random.RandomState(42).normal(size=(16, 50))
a.X[16:32, :] = -10 + np.random.RandomState(42).normal(size=(16, 50))
a.obs['foo'].iloc[:16, :] = 0
a.obs['foo'].iloc[16:32, :] = 1
a.obs['foo'].iloc[32:, :] = 2
# wrong label-color mapping
sc.pl.heatmap(a, var_names=a.var_names[:50], groupby="foo", swap_axes=False, dendrogram=True)  # fig. 2
sc.pl.heatmap(a, var_names=a.var_names[:50], groupby="foo", swap_axes=False, dendrogram=False)  # fig. 3

# but not when there are colors in `.uns
a.uns['foo_colors'] = [(1, 0, 0), (0, 1, 0), (0, 0, 1)]
sc.pl.heatmap(a, var_names=a.var_names[:50], groupby="foo", swap_axes=False, dendrogram=True)  # fig. 4
sc.pl.heatmap(a, var_names=a.var_names[:50], groupby="foo", swap_axes=False, dendrogram=False)  # fig. 5
# xlabels are not centered + horizntal lines are slightly shifted downwards (really have to zoom in)
sc.pl.heatmap(a, var_names=a.var_names, groupby="foo", swap_axes=False, figsize=(50, 50))
```
If you look closely (e.g. between fig. 2 and fig.3, or fig. 4 and fig. 5), the within group order is also broken.

```pytb
TypeError                                 Traceback (most recent call last)
<ipython-input-56-f1ba710dac43> in <module>
      9 
     10 sc.pl.heatmap(a, var_names=a.var_names[:5], groupby=None, swap_axes=True)  # is shifted to the left (fig. 1)
---> 11 sc.pl.heatmap(a, var_names=a.var_names[:5], groupby="foo", swap_axes=True) 
     12 
     13 a.X[:16, :] = 0

~/.miniconda3/envs/cellrank/lib/python3.8/site-packages/scanpy/plotting/_anndata.py in heatmap(adata, var_names, groupby, use_raw, log, num_categories, dendrogram, gene_symbols, var_group_positions, var_group_labels, var_group_rotation, layer, standard_scale, swap_axes, show_gene_labels, show, save, figsize, **kwds)
   1220                 groupby_cmap,
   1221                 norm,
-> 1222             ) = _plot_categories_as_colorblocks(
   1223                 groupby_ax, obs_tidy, colors=groupby_colors, orientation='bottom'
   1224             )

~/.miniconda3/envs/cellrank/lib/python3.8/site-packages/scanpy/plotting/_anndata.py in _plot_categories_as_colorblocks(groupby_ax, obs_tidy, colors, orientation, cmap_name)
   2361         if len(labels) > 1:
   2362             groupby_ax.set_xticks(ticks)
-> 2363             if max([len(x) for x in labels]) < 3:
   2364                 # if the labels are small do not rotate them
   2365                 rotation = 0

~/.miniconda3/envs/cellrank/lib/python3.8/site-packages/scanpy/plotting/_anndata.py in <listcomp>(.0)
   2361         if len(labels) > 1:
   2362             groupby_ax.set_xticks(ticks)
-> 2363             if max([len(x) for x in labels]) < 3:
   2364                 # if the labels are small do not rotate them
   2365                 rotation = 0

TypeError: object of type 'int' has no len()
```
#### Figures
Fig. 1
![f0](https://user-images.githubusercontent.com/46717574/104822526-6544e880-5843-11eb-8324-261e84eb45e4.png)
Fig. 2
![f1](https://user-images.githubusercontent.com/46717574/104822449-d637d080-5842-11eb-853d-bb115cd014aa.png)
Fig. 3
![f2](https://user-images.githubusercontent.com/46717574/104822452-d9cb5780-5842-11eb-8606-f4a9a5c97893.png)
Fig. 4
![f3](https://user-images.githubusercontent.com/46717574/104822453-dcc64800-5842-11eb-827c-90db0525d4d4.png)
Fig. 5
![f4](https://user-images.githubusercontent.com/46717574/104822455-dfc13880-5842-11eb-9286-655b2210b182.png)
Fig. 6
![f6](https://user-images.githubusercontent.com/46717574/104822796-958d8680-5845-11eb-82e2-4b30597c6722.png)

#### Versions

<details>
-----
anndata     0.7.5
scanpy      1.7.0rc2.dev1+g2a123065
sinfo       0.3.1
-----
PIL                 8.0.1
anndata             0.7.5
asciitree           NA
backcall            0.2.0
cairo               1.20.0
cffi                1.14.4
cloudpickle         1.6.0
colorama            0.4.4
coverage            5.3
cycler              0.10.0
cython_runtime      NA
dask                2020.12.0
dateutil            2.8.1
decorator           4.4.2
fasteners           NA
future_fstrings     NA
get_version         2.1
h5py                2.10.0
igraph              0.8.3
ipykernel           5.4.2
ipython_genutils    0.2.0
jedi                0.17.2
joblib              0.17.0
kiwisolver          1.3.1
legacy_api_wrap     1.2
leidenalg           0.8.1
llvmlite            0.34.0
louvain             0.6.1
matplotlib          3.3.3
monotonic           NA
mpl_toolkits        NA
msgpack             1.0.0
natsort             7.0.1
numba               0.51.2
numcodecs           0.7.2
numexpr             2.7.1
numpy               1.19.4
packaging           20.8
pandas              1.1.4
parso               0.7.1
pexpect             4.8.0
pickleshare         0.7.5
pkg_resources       NA
prompt_toolkit      3.0.8
psutil              5.7.3
ptyprocess          0.6.0
pygments            2.7.3
pyparsing           2.4.7
pytz                2020.5
ruamel              NA
scanpy              1.7.0rc2.dev1+g2a123065
scipy               1.5.4
setuptools_scm      NA
sinfo               0.3.1
six                 1.15.0
sklearn             0.23.2
sparse              0.11.2
sphinxcontrib       NA
storemagic          NA
tables              3.6.1
tblib               1.7.0
texttable           1.6.3
tlz                 0.11.1
toolz               0.11.1
tornado             6.1
traitlets           5.0.5
typing_extensions   NA
wcwidth             0.2.5
yaml                5.3.1
zarr                2.6.1
zmq                 20.0.0
zope                NA
-----
IPython             7.19.0
jupyter_client      6.1.7
jupyter_core        4.7.0
notebook            6.1.5
-----
Python 3.8.5 (default, Sep  4 2020, 07:30:14) [GCC 7.3.0]
Linux-5.10.0-1-amd64-x86_64-with-glibc2.10
8 logical CPU cores
-----
Session information updated at 2021-01-16 21:28
</details>

**Comment by ivirshup** [comment]
Ping @fidelram

**Comment by fidelram** [comment]
Thanks for the nice report submission.

The code error is caused by the categories being integers when the code expect an 'str'. This is an easy fix. 

The mapping of labels to color being different when colors are not in `adata.uns` is because the mapping is not saved (Fig 2 and 3). It is also an easy fix but requires the modification of `adata.uns` to save the colors. This is already done in `sc.pl.embedding` so should be OK to do but I would like to know @ivirshup opinion.

For Fig 1. when there are more cells the problem is not there or maybe is simply not visible But I have some idea on how to address it.

For Fig 6 I really don't know.

**Comment by ivirshup** [comment]
> It is also an easy fix but requires the modification of adata.uns to save the colors.

This seems reasonable since we already do it. Can you make sure to use the same `_get_palette` function for this? Maybe that should be moved out of `scatterplots.py` to somewhere more general?

We should probably have some logic for not saving the colors if the object is a view. Would have to think about this.
