### ISSUE TITLE
PC2 has more variance than PC1 from scanpy.pp.pca

### ISSUE THREAD

**Issue by YubinXie** [scverse/scanpy#1605]
- [x ] I have checked that this issue has not already been reported.
- [x ] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

Hey, I noticed that after scanpy.pp.pca, I got a result with PC2 variance ratio larger than PC1. What could possibly be the reason for this?

![image (10)](https://user-images.githubusercontent.com/16257776/105540366-1922f980-5cc4-11eb-8d58-d0ffde9cc456.png)

**Comment by ivirshup** [comment]
Can you provide an example where this occurs? I'm having trouble replicating this.

**Comment by YubinXie** [comment]
Hi @ivirshup , I figured out that it seems the function that I used from other packages which called scanpy set the zero-centered as False!

**Comment by ivirshup** [comment]
Ah, thanks for the update!
