### ISSUE TITLE
Report pynndescent version in sc.logging.print_header

### ISSUE THREAD

**Issue by yuanx749** [scverse/scanpy#1613]
Hi,

Thank you for the great tool. I think this is not a bug. 

Recently I upgraded some packages and found my results were different from the previous runs. I figured out that it is caused by different versions of `pynndescent` (0.4.7 vs 0.5.1), which is recommended to use in UMAP. So I think `pynndescent` should be included in the output of `sc.logging.print_header()`.

#### Versions

<details>

-----
anndata     0.7.5
scanpy      1.6.1
sinfo       0.3.1
-----
PIL                 8.1.0
anndata             0.7.5
constants           NA
cycler              0.10.0
cython_runtime      NA
dateutil            2.8.1
get_version         2.1
h5py                3.1.0
highs_wrapper       NA
igraph              0.8.3
joblib              1.0.0
kiwisolver          1.3.1
legacy_api_wrap     1.2
leidenalg           0.8.3
llvmlite            0.35.0
louvain             0.7.0
matplotlib          3.3.3
mpl_toolkits        NA
natsort             7.1.1
numba               0.52.0
numexpr             2.7.2
numpy               1.19.5
packaging           20.8
pandas              1.2.1
pkg_resources       NA
pynndescent         0.5.1
pyparsing           2.4.7
pytz                2020.5
scanpy              1.6.1
scipy               1.6.0
setuptools_scm      NA
sinfo               0.3.1
six                 1.15.0
sklearn             0.24.1
statsmodels         0.12.1
tables              3.6.1
texttable           1.6.3
umap                0.4.6
-----
Python 3.8.5 (default, Sep  4 2020, 07:30:14) [GCC 7.3.0]
Linux-3.10.0-1160.11.1.el7.x86_64-x86_64-with-glibc2.10
40 logical CPU cores, x86_64

</details>

**Comment by ivirshup** [comment]
I would definitely recommend using the `sc.logging.print_versions` function for a more complete listing of dependencies, which does include `pynndescent`. That said, I'm not against adding it to the more compact version.
