### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by flying-sheep** [scverse/scanpy#162]
The tests started failing with 4499d9460b8fe6e08fffb3c4cae0948849d40586, which obviously changed nothing that could make tests fail.

So I’m sure some dependency updating is responsible (Travis started installing the newwer versions and the tests fail)

We need to investigate why that is and how to fix it.

**Comment by falexwolf** [comment]
I'm pretty sure it's the pandas 0.23 issue... same error message as the one encountered here: https://github.com/theislab/scanpy/issues/158

**Comment by flying-sheep** [comment]
OK! Please tell me if I should investigate or if you’re already in the process.

**Comment by flying-sheep** [comment]
Done! Tests fixed in 478e3dcb4706328bb3726fb674473e490f353a33
