### ISSUE TITLE
What is the random number generator used by scanpy?

### ISSUE THREAD

**Issue by thebyronlee** [scverse/scanpy#1626]
Hi,

I am specifically trying to test something with random_state in sc.tl.umap, and would like to get more info on what random number generator is used. The docs there say that np.random is used if random_state=None, but does not explicitly comment on what the random number generator is otherwise. Could you please help clarify this?

Thank you!
Byron

...

**Comment by ivirshup** [comment]
We are currently using `sklearn.utils.check_random_state` to validate the argument for `random_state` in most places. Sometime's (especially in external) we pass the argument directly to the wrapped tool.

In sklearn `0.24.1`, this looks like `np.random.RandomState` if you pass an integer.
