### ISSUE TITLE
Question about vst in highly_variable_genes

### ISSUE THREAD

**Issue by alitinet** [scverse/scanpy#1630]
Hi, 

When running `highly_variable_genes `with `flavor='seurat_v3'`, the method expects raw counts. But in Seurat tutorials e.g. [here](https://satijalab.org/seurat/archive/v3.0/pbmc3k_tutorial.html) or in [Symphony](https://github.com/immunogenomics/symphony) in their code [here](https://github.com/immunogenomics/symphony/blob/main/R/buildReference.R), they run the method on normalized counts. Could you please clarify this a little?

Thanks.

**Comment by LuckyMD** [comment]
@adamgayoso did you implement the vst method for HVG selection?

**Comment by adamgayoso** [comment]
Yes, looking at the source code, the `"vst"` method uses the counts slot.

https://github.com/satijalab/seurat/blob/69dbc46c82c5aaa5c2fd275a5d7bf28c04351c6a/R/preprocessing.R#L1817-L1825

In the unit tests, we test directly against the output of the Seurat method. The only known difference is how HVGs are aggregated across batches. I could not reproduce their results, as some of the R code was unclear to me. It would be helpful if someone fixed that at some point.

**Comment by alitinet** [comment]
Thanks @adamgayoso, it's clear now.

**Comment by LuckyMD** [comment]
Maybe the difference in outputs has to do with running on counts vs normalized expression data? I haven't really looked into vst much, so not sure how this should run.
