### ISSUE TITLE
Adding CellO to Scanpy

### ISSUE THREAD

**Issue by mbernste** [scverse/scanpy#1631]
Hi, 

I am hoping to open a pull request soon to add [CellO](https://www.cell.com/iscience/fulltext/S2589-0042(20)31110-X), a cell type classification tool, to Scanpy's external API. I notice that there currently are no cell type classification tools available in Scanpy's external API.  

I am wondering if there is an explicit reason no cell type classifiers have been added to date?  For example, I noticed some debate regarding how/whether to include expression imputation into Scanpy [https://github.com/theislab/scanpy/issues/189](https://github.com/theislab/scanpy/issues/189), and I just want to make sure there is no such reason why cell type classifiers have not been included yet.

Thank you!

Matt

**Comment by ivirshup** [comment]
Hi Matt,

No particular reason. We'd definitely like to have tools for this in our ecosystem!

**Comment by mbernste** [comment]
That's great, thank you for your response!
