### ISSUE TITLE
scrublet ignores threshold

### ISSUE THREAD

**Issue by fbnrst** [scverse/scanpy#1644]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

### Minimal code sample (that we can copy&paste without having any data)

```python
import scanpy as sc
adata = sc.datasets.pbmc3k()
sc.external.pp.scrublet(adata, threshold='I am ignored')
```

```pytb
/opt/conda/lib/python3.7/site-packages/scanpy/preprocessing/_normalization.py:138: UserWarning: Revieved a view of an AnnData. Making a copy.
  view_to_actual(adata)

Automatically set threshold at doublet score = 0.27
Detected doublet rate = 1.5%
Estimated detectable doublet fraction = 44.3%
Overall doublet rate:
	Expected   = 5.0%
	Estimated  = 3.4%

```

#### Versions

<details>

scanpy==1.7.0 anndata==0.7.5 umap==0.5.1 numpy==1.20.0 scipy==1.6.0 pandas==1.2.1 scikit-learn==0.24.1 statsmodels==0.12.2 python-igraph==0.8.3 louvain==0.7.0 leidenalg==0.8.3

</details>

**Comment by ivirshup** [comment]
Thanks for the repot!

@pinin4fjords, could you look into this? Also, there may be some other arguments which are not being passed correctly. For example, `n_prin_comps` and `use_approx_neighbors` are not passed from `scrublet` to `scrublet_call_doublets`. Is there any reason some of these aren't being passed, or should all common arguments be passed through?

**Comment by pinin4fjords** [comment]
@ivirshup Honestly don't know what I was thinking here- the parameters are clearly not passed through. Perhaps I broke things when rearranging logic in the PR. In in any case I'll submit a fix soon.

**Comment by pinin4fjords** [comment]
PR with fix submitted, thanks @fabianrost84 for the report.
