### ISSUE TITLE
cell type coloring in sc.pl.matrixplot

### ISSUE THREAD

**Issue by sevahn** [scverse/scanpy#1647]
Is there a way to select the coloring for the cell types in the "groupby" argument in sc.pl.matrixplot? 

I have a custom color palette based on continuity from my other plots in my other subfigures. equivalent to the row_colors argument in sns.clustermap, is there a way to specify the right side colors for the different clusters?
thank you!
...

**Comment by fidelram** [comment]
Hi, this is not supported. Only in heatmap. The reason colors are not supported is that I am partial color blind (as a significant portion of the population is), which make plots requiring matching colors hard to decode. Hence the use of labels instead.

If you need the colors for your plots you can try replacing the groupby labels ax by the colors you want but this is not trivial.

**Comment by sevahn** [comment]
thank you for the fast response and for the information! will adjust my own approach accordingly.
