### ISSUE TITLE
Intended way to set_figure_params for a single figure

### ISSUE THREAD

**Issue by grst** [scverse/scanpy#1648]
I was wondering, what is the intended way to temporarily set plotting parameters, e.g. figsize?

Say I want to increase the figsize just for a single UMAP plot. 

I could either temporarily `set_figure_params` and reset it manually afterwards
```python
sc.set_figure_params(figsize=(8, 8))
sc.pl.umap(adata, color="cell_type")
sc.set_figure_params(figsize=(4, 4)) # or whatever it was before...
```

Or create the figure separately:
```python
_, ax = plt.subplots(figsize=(8, 8))
sc.pl.umap(adata, color="cell_type", ax=ax)
```
<p><br></p>

Would it make sense to extend `set_figure_params` to act as a context manager?

```python
with sc.set_figure_params(figsize=(8, 8), frameon=False):
    sc.pl.umap(adata, color="cell_type")
```

But maybe there's a comparable way already?

**Comment by ivirshup** [comment]
You can use `matplotlib`'s `rc_context`. E.g.:

```python
with plt.rc_context({"figure.figsize": (8, 8), "figure.dpi": (300)}:
    sc.pl.umap(adata, ...)
```

**Comment by grst** [comment]
cool, thanks!
