### ISSUE TITLE
Adding further annotation to subset

### ISSUE THREAD

**Issue by huidongchen** [scverse/scanpy#165]
Hi, Alex, 

Fantastic package! As a python guy, I have become such a huge fan of Scanpy. 

I'm encountering an issue when trying to add further annotation to a subset, what I'm doing is basically:

```
adata = sc.read(filename)
adata.var_names = pd.read_csv('genes.tsv')
adata.obs_names = pd.read_csv('barcodes.tsv')

adata_subset = adata[ list_of_barcodes,:]
anno = pd.read_csv(filename_sample_annotation)
adata_subset.obs = anno
```

But unfortunately _**adata_subset.obs**_ didn't get updated (I checked the index of _**anno**_ and it's consistent with _**adata_subset.obs_names**_). 

It works only if I add the annotation column by column (In my case there are too many columns so it won't be ideal), e.g.

`adata_subset.obs['cell_groups'] = anno['cell_groups']`

Could you please help me figure it out? Many thanks!

Huidong

**Comment by falexwolf** [comment]
Hi Huidong,

thank you for the kind words!

`adata_subset` is a `view` on an `AnnData` object. Simply check the output when printing it. You can do
```
adata_subset = adata[ list_of_barcodes, :].copy()
```
to get an actual `AnnData`.

Of course, you as a user shouldn't have to care about making this copy. As soon as you want to modify the view, it should automatically make this copy itself. This is why all the attributes *listen* to whether you're modifying them or not. I just forgot to add the listener to the *full* `.obs` attribute. I'll do that very soon. In the meanwhile, call `.copy` yourself. ;)

Best,
  Alex

**Comment by huidongchen** [comment]
Thanks for the quick solution! It works perfectly. I'm closing the issue now. Thanks again!
