### ISSUE TITLE
how to export the normlized data not the scale data on h5ad anndata object?

### ISSUE THREAD

**Issue by honghh2018** [scverse/scanpy#1650]
Hi @ALL,
    I want that the object of annData to save the normalized expression matrix that exclude the scaling matrix to perform the pyscenic regulon analysis.but the code adata.to_df().to_csv(EXP_MTX_QC_FNAME) just save the scaling matrix that had the negative number in but just normalized d matrix.so i merely want to export the normlized matrix data and then imported to the pyscenic to analyize. So how can i do for this request?
    Any advice would be appreciated.
    Best,
    hanhuihong

**Comment by LuckyMD** [comment]
Hi @honghh2018,

Whatever is output depends on what you store in `adata.X`. If you don't want to output scaled data, then you can avoid calling `sc.pp.scale()` on your data. An alternative would be to save a version of your data before scaling in a different adata layer. For example, before scaling, you can just store a copy of your data by e.g., calling `adata.layers['normalized_unscaled] = adata.X`. You can export this data matrix by calling `adata.layers['normalized_unscaled'].to_csv(FILENAME)`.

Hope this helps!

**Comment by honghh2018** [comment]
Thanks @LuckyMD ,It was tremedously helpful for my case.
 Thanks again.

**Comment by LuckyMD** [comment]
glad it worked out!

**Comment by carmensandoval** [comment]
> For example, before scaling, you can just store a copy of your data by e.g., calling adata.layers['normalized_unscaled] = adata.X.

Why is .copy() not necessary here?

ie, adata.layers['normalized_unscaled] = adata.X.copy()
