### ISSUE TITLE
TypingError: Failed in nopython mode pipeline (step: nopython frontend)

### ISSUE THREAD

**Issue by gatocor** [scverse/scanpy#1652]
Hi, I am working with a big dataset over 100000 cells and I run into a problem when computing the neigbours. Find below an small example using a random matrix. 
Observations,
when I run N_cells = 8000 it works perfectly for gauss metric.
when running N_cells = 10000, the neighbors computation crashes.

The problem is even more dramatic for method="umap". 

### Minimal code sample (that we can copy&paste without having any data)

```python
import scanpy
import numpy

matrix = numpy.random.uniform(size=[10000,1000])

adata = scanpy.AnnData(matrix)

scanpy.pp.pca(adata,n_comps=10)
scanpy.pp.neighbors(adata,method="gauss",n_pcs=10)
```

```pytb
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-3-692f9d70cb0c> in <module>
      9 
     10 scanpy.pp.pca(adata,n_comps=10)
---> 11 scanpy.pp.neighbors(adata,method="gauss",n_pcs=10)

~/.local/lib/python3.9/site-packages/scanpy/neighbors/__init__.py in neighbors(adata, n_neighbors, n_pcs, use_rep, knn, random_state, method, metric, metric_kwds, key_added, copy)
    118         adata._init_as_actual(adata.copy())
    119     neighbors = Neighbors(adata)
--> 120     neighbors.compute_neighbors(
    121         n_neighbors=n_neighbors, knn=knn, n_pcs=n_pcs, use_rep=use_rep,
    122         method=method, metric=metric, metric_kwds=metric_kwds,

~/.local/lib/python3.9/site-packages/scanpy/neighbors/__init__.py in compute_neighbors(self, n_neighbors, knn, n_pcs, use_rep, method, random_state, write_knn_indices, metric, metric_kwds)
    732                 X = pairwise_distances(X, metric=metric, **metric_kwds)
    733                 metric = 'precomputed'
--> 734             knn_indices, knn_distances, forest = compute_neighbors_umap(
    735                 X, n_neighbors, random_state, metric=metric, metric_kwds=metric_kwds)
    736             # very cautious here

~/.local/lib/python3.9/site-packages/scanpy/neighbors/__init__.py in compute_neighbors_umap(X, n_neighbors, random_state, metric, metric_kwds, angular, verbose)
    273         # umap 0.5.0
    274         warnings.filterwarnings("ignore", message=r"Tensorflow not installed")
--> 275         from umap.umap_ import nearest_neighbors
    276 
    277     random_state = check_random_state(random_state)

~/.local/lib/python3.9/site-packages/umap/umap_.py in <module>
     45 )
     46 
---> 47 from pynndescent import NNDescent
     48 from pynndescent.distances import named_distances as pynn_named_distances
     49 from pynndescent.sparse import sparse_named_distances as pynn_sparse_named_distances

~/.local/lib/python3.9/site-packages/pynndescent/__init__.py in <module>
      1 import pkg_resources
      2 import numba
----> 3 from .pynndescent_ import NNDescent, PyNNDescentTransformer
      4 
      5 # Workaround: https://github.com/numba/numba/issues/3341

~/.local/lib/python3.9/site-packages/pynndescent/pynndescent_.py in <module>
     19 import heapq
     20 
---> 21 import pynndescent.sparse as sparse
     22 import pynndescent.sparse_nndescent as sparse_nnd
     23 import pynndescent.distances as pynnd_dist

~/.local/lib/python3.9/site-packages/pynndescent/sparse.py in <module>
    341     },
    342 )
--> 343 def sparse_alternative_jaccard(ind1, data1, ind2, data2):
    344     num_non_zero = arr_union(ind1, ind2).shape[0]
    345     num_equal = arr_intersect(ind1, ind2).shape[0]

~/.local/lib/python3.9/site-packages/numba/core/decorators.py in wrapper(func)
    216             with typeinfer.register_dispatcher(disp):
    217                 for sig in sigs:
--> 218                     disp.compile(sig)
    219                 disp.disable_compile()
    220         return disp

~/.local/lib/python3.9/site-packages/numba/core/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

~/.local/lib/python3.9/site-packages/numba/core/dispatcher.py in compile(self, sig)
    817             self._cache_misses[sig] += 1
    818             try:
--> 819                 cres = self._compiler.compile(args, return_type)
    820             except errors.ForceLiteralArg as e:
    821                 def folded(args, kws):

~/.local/lib/python3.9/site-packages/numba/core/dispatcher.py in compile(self, args, return_type)
     80             return retval
     81         else:
---> 82             raise retval
     83 
     84     def _compile_cached(self, args, return_type):

~/.local/lib/python3.9/site-packages/numba/core/dispatcher.py in _compile_cached(self, args, return_type)
     90 
     91         try:
---> 92             retval = self._compile_core(args, return_type)
     93         except errors.TypingError as e:
     94             self._failed_cache[key] = e

~/.local/lib/python3.9/site-packages/numba/core/dispatcher.py in _compile_core(self, args, return_type)
    103 
    104         impl = self._get_implementation(args, {})
--> 105         cres = compiler.compile_extra(self.targetdescr.typing_context,
    106                                       self.targetdescr.target_context,
    107                                       impl,

~/.local/lib/python3.9/site-packages/numba/core/compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    625     pipeline = pipeline_class(typingctx, targetctx, library,
    626                               args, return_type, flags, locals)
--> 627     return pipeline.compile_extra(func)
    628 
    629 

~/.local/lib/python3.9/site-packages/numba/core/compiler.py in compile_extra(self, func)
    361         self.state.lifted = ()
    362         self.state.lifted_from = None
--> 363         return self._compile_bytecode()
    364 
    365     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

~/.local/lib/python3.9/site-packages/numba/core/compiler.py in _compile_bytecode(self)
    423         """
    424         assert self.state.func_ir is None
--> 425         return self._compile_core()
    426 
    427     def _compile_ir(self):

~/.local/lib/python3.9/site-packages/numba/core/compiler.py in _compile_core(self)
    403                 self.state.status.fail_reason = e
    404                 if is_final_pipeline:
--> 405                     raise e
    406         else:
    407             raise CompilerError("All available pipelines exhausted")

~/.local/lib/python3.9/site-packages/numba/core/compiler.py in _compile_core(self)
    394             res = None
    395             try:
--> 396                 pm.run(self.state)
    397                 if self.state.cr is not None:
    398                     break

~/.local/lib/python3.9/site-packages/numba/core/compiler_machinery.py in run(self, state)
    339                     (self.pipeline_name, pass_desc)
    340                 patched_exception = self._patch_error(msg, e)
--> 341                 raise patched_exception
    342 
    343     def dependency_analysis(self):

~/.local/lib/python3.9/site-packages/numba/core/compiler_machinery.py in run(self, state)
    330                 pass_inst = _pass_registry.get(pss).pass_inst
    331                 if isinstance(pass_inst, CompilerPass):
--> 332                     self._runPass(idx, pass_inst, state)
    333                 else:
    334                     raise BaseException("Legacy pass in use")

~/.local/lib/python3.9/site-packages/numba/core/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

~/.local/lib/python3.9/site-packages/numba/core/compiler_machinery.py in _runPass(self, index, pss, internal_state)
    289             mutated |= check(pss.run_initialization, internal_state)
    290         with SimpleTimer() as pass_time:
--> 291             mutated |= check(pss.run_pass, internal_state)
    292         with SimpleTimer() as finalize_time:
    293             mutated |= check(pss.run_finalizer, internal_state)

~/.local/lib/python3.9/site-packages/numba/core/compiler_machinery.py in check(func, compiler_state)
    262 
    263         def check(func, compiler_state):
--> 264             mangled = func(compiler_state)
    265             if mangled not in (True, False):
    266                 msg = ("CompilerPass implementations should return True/False. "

~/.local/lib/python3.9/site-packages/numba/core/typed_passes.py in run_pass(self, state)
     90                               % (state.func_id.func_name,)):
     91             # Type inference
---> 92             typemap, return_type, calltypes = type_inference_stage(
     93                 state.typingctx,
     94                 state.func_ir,

~/.local/lib/python3.9/site-packages/numba/core/typed_passes.py in type_inference_stage(typingctx, interp, args, return_type, locals, raise_errors)
     68 
     69         infer.build_constraint()
---> 70         infer.propagate(raise_errors=raise_errors)
     71         typemap, restype, calltypes = infer.unify(raise_errors=raise_errors)
     72 

~/.local/lib/python3.9/site-packages/numba/core/typeinfer.py in propagate(self, raise_errors)
   1069                                   if isinstance(e, ForceLiteralArg)]
   1070                 if not force_lit_args:
-> 1071                     raise errors[0]
   1072                 else:
   1073                     raise reduce(operator.or_, force_lit_args)

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython mode backend)
Failed in nopython mode pipeline (step: nopython mode backend)
Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<function make_quicksort_impl.<locals>.run_quicksort at 0x7f455d24c280>) found for signature:
 
 >>> run_quicksort(array(int32, 1d, C))
 
There are 2 candidate implementations:
      - Of which 2 did not match due to:
      Overload in function 'register_jitable.<locals>.wrap.<locals>.ov_wrap': File: numba/core/extending.py: Line 150.
        With argument(s): '(array(int32, 1d, C))':
       Rejected as the implementation raised a specific error:
         UnsupportedError: Failed in nopython mode pipeline (step: analyzing bytecode)
       Use of unsupported opcode (LOAD_ASSERTION_ERROR) found
       
       File "../../../../.local/lib/python3.9/site-packages/numba/misc/quicksort.py", line 180:
           def run_quicksort(A):
               <source elided>
                   while high - low >= SMALL_QUICKSORT:
                       assert n < MAX_STACK
                       ^
       
  raised from /home/gabriel/.local/lib/python3.9/site-packages/numba/core/byteflow.py:269

During: resolving callee type: Function(<function make_quicksort_impl.<locals>.run_quicksort at 0x7f455d24c280>)
During: typing of call at /home/gabriel/.local/lib/python3.9/site-packages/numba/np/arrayobj.py (5007)


File "../../../../.local/lib/python3.9/site-packages/numba/np/arrayobj.py", line 5007:
    def array_sort_impl(arr):
        <source elided>
        # Note we clobber the return value
        sort_func(arr)
        ^

During: lowering "$14call_method.5 = call $12load_method.4(func=$12load_method.4, args=[], kws=(), vararg=None)" at /home/gabriel/.local/lib/python3.9/site-packages/numba/np/arrayobj.py (5017)
During: lowering "$8call_method.3 = call $4load_method.1(arr, func=$4load_method.1, args=[Var(arr, sparse.py:28)], kws=(), vararg=None)" at /home/gabriel/.local/lib/python3.9/site-packages/pynndescent/sparse.py (28)
During: resolving callee type: type(CPUDispatcher(<function arr_unique at 0x7f4574e5aa60>))
During: typing of call at /home/gabriel/.local/lib/python3.9/site-packages/pynndescent/sparse.py (41)

During: resolving callee type: type(CPUDispatcher(<function arr_unique at 0x7f4574e5aa60>))
During: typing of call at /home/gabriel/.local/lib/python3.9/site-packages/pynndescent/sparse.py (41)


File "../../../../.local/lib/python3.9/site-packages/pynndescent/sparse.py", line 41:
def arr_union(ar1, ar2):
    <source elided>
    else:
        return arr_unique(np.concatenate((ar1, ar2)))
        ^

During: resolving callee type: type(CPUDispatcher(<function arr_union at 0x7f4574e5ac10>))
During: typing of call at /home/gabriel/.local/lib/python3.9/site-packages/pynndescent/sparse.py (344)

During: resolving callee type: type(CPUDispatcher(<function arr_union at 0x7f4574e5ac10>))
During: typing of call at /home/gabriel/.local/lib/python3.9/site-packages/pynndescent/sparse.py (344)


File "../../../../.local/lib/python3.9/site-packages/pynndescent/sparse.py", line 344:
def sparse_alternative_jaccard(ind1, data1, ind2, data2):
    num_non_zero = arr_union(ind1, ind2).shape[0]
    ^
```

#### Versions

<details>
anndata     0.7.5
scanpy      1.7.0
sinfo       0.3.1
-----
PIL                 8.1.0
PyQt5               NA
anndata             0.7.5
appdirs             1.4.4
cffi                1.14.4
colorama            0.4.4
constants           NA
cycler              0.10.0
cython_runtime      NA
dateutil            2.8.1
get_version         2.1
google              NA
h5py                3.1.0
highs_wrapper       NA
joblib              1.0.1
kiwisolver          1.3.1
legacy_api_wrap     1.2
llvmlite            0.34.0
matplotlib          3.3.4
mpl_toolkits        NA
natsort             7.1.1
numba               0.51.2
numexpr             2.7.2
numpy               1.20.0
packaging           20.8
pandas              1.2.2
pkg_resources       NA
psutil              5.8.0
pyexpat             NA
pyparsing           2.4.7
pytoml              NA
pytz                2021.1
scanpy              1.7.0
scipy               1.6.0
setuptools_scm      NA
sinfo               0.3.1
sip                 NA
six                 1.15.0
sklearn             0.24.1
sphinxcontrib       NA
tables              3.6.1
yaml                5.3.1

</details>

**Comment by gatocor** [comment]
Found the problem.

I was running the library using python v3.9 with numba v0.51. Compatibility for python 3.9 is only available in the (currently) latest version of numba v0.53. 

This incompatibility generated the crash in the pynndescent library. Why it worked for certain sizes and no other remains a mistery...

**Comment by mr-september** [comment]
@gatocor I'm running into the same issue, how did you change to numba 0.53?

**Comment by gatocor** [comment]
Hi @mr-september , you have to install the prerelease version of Numba.

pip install -pre numba

**Comment by mr-september** [comment]
@gatocor Thanks, for me it worked with `pip install --pre numba`, 
terminal output:
```
Requirement already satisfied: numba in ./venv/lib/python3.9/site-packages (0.51.2)
Requirement already satisfied: llvmlite<0.35,>=0.34.0.dev0 in ./venv/lib/python3.9/site-packages (from numba) (0.34.0)
Requirement already satisfied: numpy>=1.15 in ./venv/lib/python3.9/site-packages (from numba) (1.20.1)
Requirement already satisfied: setuptools in ./venv/lib/python3.9/site-packages (from numba) (54.0.0)
```

Went back into Python Console, re-do `import numba`, `numba.__version__` still gives `'0.51.2'`. How do you force it to load a different version?

Update: Also tried the `force-reinstall` tag: `Successfully installed llvmlite-0.36.0rc2 numba-0.53.0rc2 numpy-1.20.1 setuptools-54.0.0`, but in Python Console it's still stuck at `numba.__version__ '0.51.2'`

**Comment by gatocor** [comment]
You have to first uninstall the version you have already installed of numba.
pip uninstall numba
pip install --pre numba

**Comment by mr-september** [comment]
@gatocor just tried it, but it says `Successfully uninstalled numba-0.53.0rc2`, then `Successfully installed numba-0.53.0rc2`. So it looks like my system/terminal has the right `numba` version, but I can't get Python Console to also see the new version?

**Comment by gatocor** [comment]
It is possible that you are installing it in a python pathway different than the one you are using to execute your code. I advise you to create a virtual environment (loot it up somewhere), and execute your single cell projects from it to make sure of the packages you have installed in each place.

**Comment by mr-september** [comment]
Yes, I made sure I was in the right venv. I found one workaround - open a new Python Console (and close the old one if you wish), this fresh Console will not have any previously imported modules, but new `import`s will be updated.

**Comment by RutBo** [comment]
> Hi, I am working with a big dataset and I run into a problem when computing the neigbours. Find below an small example using a random matrix. .
> 
> The problem is even more dramatic for method="umap".
> 
> ### Minimal code sample (that we can copy&paste without having any data)
> ```python
> import scanpy
> import numpy
> 
> matrix = numpy.random.uniform(size=[10000,1000])
> 
> adata = scanpy.AnnData(matrix)
> 
> scanpy.pp.pca(adata,n_comps=10)
> scanpy.pp.neighbors(adata,method="gauss",n_pcs=10)
> ```
> 
> The error I get:
> ---------------------------------------------------------------------------
> File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\errors.py", line 823, in new_error_context
    yield
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\lowering.py", line 293, in lower_block
    self.lower_inst(inst)
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\lowering.py", line 438, in lower_inst
    val = self.lower_assign(ty, inst)
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\lowering.py", line 624, in lower_assign
    return self.lower_expr(ty, value)
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\lowering.py", line 1159, in lower_expr
    res = self.lower_call(resty, expr)
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\lowering.py", line 889, in lower_call
    res = self._lower_call_normal(fnty, expr, signature)
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\lowering.py", line 1130, in _lower_call_normal
    res = impl(self.builder, argvals, self.loc)
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\base.py", line 1201, in __call__
    res = self._imp(self._context, builder, self._sig, args, loc=loc)
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\base.py", line 1231, in wrapper
    return fn(*args, **kwargs)
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\cpython\rangeobj.py", line 40, in range1_impl
    state.stop = stop
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\cgutils.py", line 164, in __setattr__
    self[self._datamodel.get_field_position(field)] = value
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\cgutils.py", line 188, in __setitem__
    raise TypeError("Invalid store of {value.type} to "
TypeError: Invalid store of i64 to i32 in <numba.core.datamodel.models.RangeModel object at 0x0000015592499520> (trying to write member #1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RUTBO\PycharmProjects\pvalue\single cell analysis.py", line 44, in <module>
    sc.pp.neighbors(tab, n_neighbors=10, n_pcs=40)
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\scanpy\neighbors\__init__.py", line 139, in neighbors
    neighbors.compute_neighbors(
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\scanpy\neighbors\__init__.py", line 808, in compute_neighbors
    self._distances, self._connectivities = _compute_connectivities_umap(
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\scanpy\neighbors\__init__.py", line 387, in _compute_connectivities_umap
    from umap.umap_ import fuzzy_simplicial_set
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\umap\__init__.py", line 2, in <module>
    from .umap_ import UMAP
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\umap\umap_.py", line 41, in <module>
    from umap.layouts import (
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\umap\layouts.py", line 39, in <module>
    def rdist(x, y):
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\decorators.py", line 219, in wrapper
    disp.compile(sig)
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\dispatcher.py", line 965, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\dispatcher.py", line 125, in compile
    status, retval = self._compile_cached(args, return_type)
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\dispatcher.py", line 139, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\dispatcher.py", line 152, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\compiler.py", line 693, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\compiler.py", line 429, in compile_extra
    return self._compile_bytecode()
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\compiler.py", line 497, in _compile_bytecode
    return self._compile_core()
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\compiler.py", line 476, in _compile_core
    raise e
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\compiler.py", line 463, in _compile_core
    pm.run(self.state)
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\compiler_machinery.py", line 353, in run
    raise patched_exception
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\compiler_machinery.py", line 341, in run
    self._runPass(idx, pass_inst, state)
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\compiler_machinery.py", line 296, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\compiler_machinery.py", line 269, in check
    mangled = func(compiler_state)
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\typed_passes.py", line 394, in run_pass
    lower.lower()
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\lowering.py", line 196, in lower
    self.lower_normal_function(self.fndesc)
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\lowering.py", line 250, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\lowering.py", line 279, in lower_function_body
    self.lower_block(block)
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\lowering.py", line 293, in lower_block
    self.lower_inst(inst)
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\errors.py", line 837, in new_error_context
    raise newerr.with_traceback(tb)
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: native lowering)
Invalid store of i64 to i32 in <numba.core.datamodel.models.RangeModel object at 0x0000015592499520> (trying to write member #1)

File "..\..\AppData\Local\Programs\Python\Python39\lib\umap\layouts.py", line 53:
def rdist(x, y):
    <source elided>
    dim = x.shape[0]
    for i in range(dim):
    ^

During: lowering "$20call_function.7 = call $16load_global.5(dim, func=$16load_global.5, args=[Var(dim, layouts.py:52)], kws=(), vararg=None, target=None)" at C:\Users\RUTBO\AppData\Local\Programs\Python\Python39\lib\umap\layouts.py (53)


I am running scanpy using python v3.9 with numba v0.55. 

_Originally posted by @gatocor in https://github.com/theislab/scanpy/issues/1652#issuecomment-779686831_

**Comment by ivirshup** [comment]
@RutBo, I think you are facing a different problem. Could you open up a new issue for this?
