### ISSUE TITLE
Add more links to `project_url`

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#1673]
- [ ] Additional function parameters / changed functionality / changed defaults?
- [ ] New analysis tool: A simple analysis tool you have been using and are missing in `sc.tools`?
- [ ] New plotting function: A kind of plot you would like to seein `sc.pl`?
- [ ] External tools: Do you know an existing package that should go into `sc.external.*`?
- [x] Other?

We should add more links to scanpy's [`project_url`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#project-urls) metadata. Docs, twitter, and discourse for sure.

**Comment by flying-sheep** [comment]
Fixed in #2452
