### ISSUE TITLE
make pinndescent as part of requirements? (or at least document better)

### ISSUE THREAD

**Issue by giovp** [scverse/scanpy#1675]
- [ ] I have checked that this issue has not already been reported.
- [ ] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

in the last months there's been several people raising issues about `sc.pp.neighbors` being very slow. After pointing them to installing `pynndescent` they noticed considerable improvements in run times.
pynndescent is still top of the benchmarks afaik https://github.com/lmcinnes/pynndescent

Problems are that:
- afaik there's nowhere in the docs where this is documented
- it might be a good idea to just add it as default?

pinging @Koncopd @ivirshup , happy to add a line about pynndescent, just need to know where.

**Comment by ivirshup** [comment]
I'd add the line as a `.. note` to `neighbors`, but I'd also be fine with adding pynndescent as a dependency. We'd just need to get rid of the code that works with non-pynndescent search.
