### ISSUE TITLE
Score of rank_genes_groups

### ISSUE THREAD

**Issue by hahia** [scverse/scanpy#1688]
Hello, I'm new to scanpy
Recently, I use scanpy on scRNA data, run 

```
sc.tl.rank_genes_groups(adata, 'marker_cluster', groups=['NK_ 8'], method='wilcoxon')
sc.pl.rank_genes_groups(adata, groups=['NK_ 8'], n_genes=20)
```

get the result
![image](https://user-images.githubusercontent.com/49113803/108975925-f79d9f00-76c1-11eb-93cb-3b854c484d59.png)

Can anyone tell me what's the score means here? How it be calculated?

**Comment by Koncopd** [comment]
Hi, for `method='wilcoxon'` this is [Wilcoxon rank-sum test](https://en.wikipedia.org/wiki/Mann%E2%80%93Whitney_U_test), and the scores are U_1 from methods in in the link. Higher absolute value of score -> lower p-value (more evidence the levels of expression between groups are different), higher score indicates higher expression, lower score -> lower expression.

**Comment by hahia** [comment]
> Hi, for `method='wilcoxon'` this is [Wilcoxon rank-sum test](https://en.wikipedia.org/wiki/Mann%E2%80%93Whitney_U_test), and the scores are U_1 from methods in in the link. Higher absolute value of score -> lower p-value (more evidence the levels of expression between groups are different), higher score indicates higher expression, lower score -> lower expression.

Thank you very much !!!

**Comment by suryadipto** [comment]
Hi, I had a quick question. So, when I run sc.tl.rank_genes_groups(), and then I save the names, scores, pvals, and pvals_adj: I do see that the names are ordered as per decreasing scores. However, the genes with the lowest pvalues are not the ones with the highest scores. In fact, quite the opposite--the ones with the highest scores are the most negative p-valued ones. I'm quite confused about this. Are the pvals and pvals_adjusted matrices not ordered as per the scores? Also, the description says that the scores are just the zscores of the pvalues, however that also doesn't quite seem to be the case. Can someone please explain how we go from pvalues to scores?

**Comment by eroell** [comment]
See a response here #2586.
