### ISSUE TITLE
Move from 88 to 120 characters with Black

### ISSUE THREAD

**Issue by Zethson** [scverse/scanpy#1694]
This will be the discussion that no one ever wants since developers like us tend to bring our mice and keyboards to fight when it comes to questions like these, but hey I thought at some point it should be had anyways haha

@ivirshup recently introduced black as the formatting standard for Scanpy. I am not a fan of blacks formatting, but the idea of consistent formatting for big open source projects is great! So +1 from me

Anyways, currently black formats with 88 characters per line, which makes, especially with black, for lots and lots of line breaks and encourages bad practices like unspecific short variable names etc. Modern Python programming is not C programming from the 80s. Have a read at Linus rant on the 80 character limit in the Linux kernel and why the Linux kernel does **not** enforce it: https://lkml.org/lkml/2020/5/29/1038 

Applying black with a 120 characters limit removes about 1500 lines. That's 1500 lines that you have to scroll less and in my opinion the result is more readable.

What do you think?

**Comment by flying-sheep** [comment]
yes, but

1. after the flit PR. not going to rebase this again.
2. we need to manually go through and check that we have no “magic commas” that keep lists exploded that can be inline. will remove even more lines.

**Comment by ivirshup** [comment]
Some ways I like to work with the code:

* Left side of screen is text editor, right side is terminal/ docs/ something else
  *  86 characters available if I have a side bar open,  95 without
* Split code browser
  * 84 columns with a side bar open, 95 without

120 is too long for this. Also this is a pretty wide laptop screen (16-inch). I believe Alex uses a MacBook Air with even more limited screen real estate.

**Comment by Zethson** [comment]
Closing because I don't think that I could convince people here although I still prefer 120 :)
