### ISSUE TITLE
Drop python 3.6 for 1.8

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#1697]
Numpy has dropped support for python 3.6 in 1.20.0, and have recommended that packages in the pydata ecosystem adopt a similar schedule for python versions ([NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html)). Should we follow this?

Some cool stuff we get by dropping 3.6:

* [Postponed evaluation of type annotations](https://docs.python.org/3/whatsnew/3.7.html#pep-563-postponed-evaluation-of-annotations)
* [`singledispatch` can register from type annotations](https://docs.python.org/3/whatsnew/3.7.html#functools)
* [Customized access to module attributes](https://docs.python.org/3/whatsnew/3.7.html#pep-562-customization-of-access-to-module-attributes)

Also, users will be pinned to old versions of numpy if they're using 3.6, and maybe we don't want to deal with that.

**Comment by Zethson** [comment]
AFAIK the newest Pandas version is also 3.7+ already.

**Comment by flying-sheep** [comment]
`__getattr__` on modules is in 3.7 already? nice!

And yeah, `from __future__ import annotations` is going to make a lot of import order sensitive submodules less … that.

**Comment by giovp** [comment]
random point but in #1715 noticed that 3.6 tests are failing due to missing `typing.Literal` import. We could fix it ad hoc but otherwise other good reason to drop 3.6

**Comment by ivirshup** [comment]
@giovp we do have a custom `Literal` thing in `compat` for this, but agree it would be nice to not have this.

**Comment by ivirshup** [comment]
Matplotlib 3.4 has dropped 3.6 support. Since matplotlib is our most painful dependency (reliably causes test failures when it updates), it's a great time to drop 3.6.

**Comment by pinin4fjords** [comment]
FYI having seen this I've been trying out conda deps, and multicore t-sne doesn't currently have a build for > 3.6, just so you know. I'm seeing if I can sort it out, but I'm not a conda forge wizard (see https://github.com/conda-forge/multicore-tsne-feedstock/pull/6).

**Comment by flying-sheep** [comment]
niiice!
