### ISSUE TITLE
diffmap - negative eigenvalues 

### ISSUE THREAD

**Issue by joshua-gould** [scverse/scanpy#170]
```py
import scanpy.api as sc
adata = sc.datasets.paul15()
sc.pp.neighbors(adata, n_neighbors=20, use_rep='X')
sc.tl.diffmap(adata, n_comps=60)
adata.uns['diffmap_evals']
```

**Comment by falexwolf** [comment]
Sorry for the late response, I was on holidays.

Computing 60 eigenvectors with Lanczos is terribly unstable. You shouldn't do that. I'm not astonished that some spurious negative eigenvalues arise.

Up to 20 or 30 max is OK.

**Comment by flying-sheep** [comment]
well, we should warn the user when they do something like this then. lanzcos is an implementation detail that our API hides, so it’s pure coincidence for an user to learn about it beforehand.

**Comment by falexwolf** [comment]
yes, this sanity check for `n_components` in diffmap definitely makes sense. makes sense for any parameter in any function. but is so much work! :wink: I'll add it for this case, soon...

**Comment by flying-sheep** [comment]
yeah, this one is hard to catch, because it’s not obvious why you shouldn’t be able to specify any number of eigenvectors from 0 to n_obs. most other parameters are kinda obvious (using k=0 makes for a bad number of nearest neighbors)
