### ISSUE TITLE
anndata.raw.var casting categoricals to integers

### ISSUE THREAD

**Issue by LuckyMD** [scverse/scanpy#171]
When an anndata object is saved to h5ad the categorical variables in the .raw.var are casted to integers so that e.g. gene names are lost when loading the anndata object again. This functionality is especially unfortunate as anndata allows adata and adata.raw to have different sizes in the .var dimension. Thus, if anndata represents for example a highly variable gene set, where anndata.raw is the whole data set, then we can no longer visualize the expression of genes that were filtered out unless we call them by var_name and not by 'gene_name'.

This bug is likely due to these lines:
https://github.com/theislab/anndata/blob/d9727cab88ba2100787e3e2ae0c6d72abd4d92b7/anndata/base.py#L1925-L1951

It would be good to add an uns_raw/ or raw_categories/ folder to the h5ad format which stores the categorical variables for raw.var.

**Comment by falexwolf** [comment]
Sorry for the long wait! I sent the final files for submission to Fabian in the middle of last night...

This should fix it in a backwards compat way: https://github.com/theislab/anndata/commit/8a48281fed5efe582329c05b3f7aaf1d1c7c3f07
https://github.com/theislab/anndata/commit/212adbdb8138e2a8cc1c80c8397346b264ef3448

**Comment by LuckyMD** [comment]
Great, thanks! I'll give it a spin soon.
