### ISSUE TITLE
Gitter for scanpy?

### ISSUE THREAD

**Issue by adamgayoso** [scverse/scanpy#1716]
- [ ] Additional function parameters / changed functionality / changed defaults?
- [ ] New analysis tool: A simple analysis tool you have been using and are missing in `sc.tools`?
- [ ] New plotting function: A kind of plot you would like to seein `sc.pl`?
- [ ] External tools: Do you know an existing package that should go into `sc.external.*`?
- [x] Other?

We started a [gitter](https://gitter.im/scvi-tools/development) at scvi-tools and surprisingly it has gotten more traction than our Discourse forum. Just putting it out there to gauge interest here. You could have a development room and a usage room. The pros are that it's more informal and less of a barrier of entry compared to github issues, cons include that it's not as searchable (though I'm a novice with it).

I feel that you might be able to get better community answers if gitter became actively used.

**Comment by Zethson** [comment]
Closing since this is a high level scverse issue and we went for zulip.
