### ISSUE TITLE
split by in sc.pl.dotplot 

### ISSUE THREAD

**Issue by FADHLyemen** [scverse/scanpy#1729]
in Surat, you can plot dot plot using group by and split by option. in scanpy only groupby option in sc.pl.dotplot function.
Any help, I need a dot plot for cell types in different condition.

**Comment by ivirshup** [comment]
This is already allowed, we just don't have a separate argument for it. Just pass a list of the variables you'd like to groupby. For example:

```python
import scanpy as sc, numpy as np

pbmc = sc.datasets.pbmc3k_processed().raw.to_adata()
genes = list(pbmc.uns["rank_genes_groups"]["names"][0])

pbmc.obs["batch"] = np.random.choice(["a", "b"], pbmc.n_obs)
sc.pl.dotplot(pbmc, genes, ["louvain", "batch"])
```

![tmp](https://user-images.githubusercontent.com/8238804/110577481-d30fef80-81b6-11eb-93f3-4adb2f269e78.jpg)

**Comment by FADHLyemen** [comment]
Thank you, ivirshup. How to subset cells in scanpy?
