### ISSUE TITLE
Doublet filtering function

### ISSUE THREAD

**Issue by yueqiw** [scverse/scanpy#173]
Hi,

I tried the [`DoubletDetection`](https://github.com/JonathanShor/DoubletDetection) Python library on my data and got some interesting result. As it can be run directly on a numpy array of count matrix (`adata.X`), I thought it would be an interesting feature for `scanpy`. 

```
clf = doubletdetection.BoostClassifier() 
doublets = clf.fit(adata.X).predict()
adata.obs['doublet'] = pd.Categorical(doublets.astype(bool))
```

**Comment by falexwolf** [comment]
Sorry for the late response, I was on holidays. I'm happy to merge a pull request for this, if the package appears solid. Would you want to add a file `scanpy/preprocessing/doubletdetection`? We should probably just ask @JonathanShor whether he's interested in an interface for easily accessing his package. If he is, he should also make the pull request, I'd say. :smile:

**Comment by JonathanShor** [comment]
Thanks to @yueqiw for the confidence. :)

@falexwolf We have no issue with our package being included here, but we wouldn't be able to create a custom API for your package right now, if that's what you were suggesting?

Given my quick overview of your package, two things you should note:
1. Our method expects the input count matrix to be from a single run. Performance takes a non-trivial hit on aggregate datasets.
2. Currently, our runtime will not satisfy those impressive metrics cited in your 1.0 announcement. This may possibly change in the future, as we haven't focused on hard optimization yet.

**Comment by falexwolf** [comment]
Hi @JonathanShor,

you don't need to create a custom API. One point of Scanpy is to provide convenient access via `anndata` to many single-cell packages around. The only thing needed for that is to provide a very simple interface like [this](https://github.com/theislab/scanpy/blob/master/scanpy/tools/phate.py#L8-L145) or [this](https://github.com/theislab/scanpy/blob/master/scanpy/preprocessing/mnn_correct.py#L4-L104) or several of the other tools... Simply click on the GitHub links in the Scanpy docs...

If your package works reliably, both the restrictions you mention should in principle not prevent adding your package. Of course, in the future, we want all elements of Scanpy to scale to millions of cells, not just the core tools. But for a lot of people, it's right now helpful to have a large number of tools available also for relatively small datasets.

The only problem is to avoid cluttering the Scanpy API with virtually any tool there is. Tools in the API should have passed a certain quality check.

Doublet detection is a difficult problem. Already last autumn, we played around with @swolock 's tool but didn't end up using it - it was good, but in our situation, it didn't seem to apply (are you eventually going to distribute a package for it @swolock ?). I myself quickly wrote a tool, too, but it didn't work well. Just yesterday, [this](https://www.biorxiv.org/content/early/2018/06/20/352484) appeared. Then there is also [this](https://www.biorxiv.org/content/early/2018/04/04/234872) on "empty cell detection". There are more tools out there, I think...

What I mean is: computationally detecting doublets is still something where the field has not agreed on a consensus. Just like batch correction. Therefore, I would not add a tool `tl.doublet_detection` or `tl.detect_doublets` to the API at this stage.

There are two options. Either we create a `.beta` module of the API for tools that don't even have a preprint and add your tool and similar cases in the future there. We could make a separate page for that entitled *Cutting Edge Beta Tools* which advertises these tools for people to try out and play around with it. When you have a solid preprint and/or publication or if you think that your tool should go in the main API anyways 😄, we should add your package as `tl.detect_doublets_ONEWORDDESCRIBGINGYOURALGORITHM`... 

@flying-sheep @gokceneraslan @fidelram @dawe anyone opinions on such cases?

**Comment by swolock** [comment]
Hi @falexwolf, yes I will be making my method available. A [rough version](https://github.com/swolock/woublet) is already on github, and I also played around with adding it to my [scanpy fork](https://github.com/swolock/scanpy) (though not the right way -- I added it to `tl` rather than `pp`). I'll hopefully clean it up and release something more official when I have the chance.

**Comment by falexwolf** [comment]
Good to hear! Looking forward to learning more about it.
PS: Having a doublet detection tool in `tl` would be fine, I'd say... `pp` and `tl` are just meant to give a rough orientation for users... in some cases, it's not completely clear what *preprocessing* and what *downstream* analysis is...

**Comment by ivirshup** [comment]
It looks like this may have stalled a bit. Is anyone currently working on making some form of doublet detection available from scanpy?

**Comment by swolock** [comment]
Hi @ivirshup, I've been meaning to get back to this. I've just started on an AnnData-compatible version of Scrublet which should be easy to hook up to Scanpy. Will keep you posted.

**Comment by cartal** [comment]
> Hi @ivirshup, I've been meaning to get back to this. I've just started on an AnnData-compatible version of Scrublet which should be easy to hook up to Scanpy. Will keep you posted.

Any updates on this?

**Comment by falexwolf** [comment]
I guess, we should ask @swolock. 🙂

**Comment by SamueleSoraggi** [comment]
I can apply pretty easily scrublet from the original python package, so I
guess a wrapper should be something fast to implement :) I was thinking
about doing it last week, but I am no expert in this kind of stuff :/

Den tir. 14. maj 2019 kl. 20.18 skrev Alex Wolf <notifications@github.com>:

**Comment by swolock** [comment]
@cartal @SamueleSoraggi 
For some reason I decided to integrate Scrublet using Scanpy's functions where possible, rather than making a simple wrapper. The core functionality is up and running in [this fork](https://github.com/swolock/scanpy), and now I just need to add documentation, make some of the code more Scanpythonic(?), and add an example.

**Comment by SamueleSoraggi** [comment]
Your way sounds sure better, many things into the scrublet algorithm are in
redundancy with components of scanpy. It will sure look great :)
Just one thing: in the scrublet paper they suggest always to just run the
simulation of doublets and look at the expected vs estimated fraction of
doublets before removing doublets. If those two values do not match, they
say one should rerun scrublet and tune the expected fraction.
Does your script only run simulation of doublets and output the doublets
score, or does it also remove doublets at once? If you do the latter, then
one is not able to simulate doublets more than once to adjust the expected
doublet fraction.
Cheers.

Den tor. 16. maj 2019 kl. 05.15 skrev Sam Wolock <notifications@github.com>:

**Comment by fidelram** [comment]
@swolock why don't you submit a PR? I just tested your code and seems to work.

**Comment by pinin4fjords** [comment]
How is this work going? We'd love to integrate Scrublet into our workflows, which are currently quite Scanpy-centric.

**Comment by fidelram** [comment]
@pinin4fjords Given that there is no response from @swolock I tried the following, which works well:

```PYTHON
import Scrublet as scr
scrub = scr.Scrublet(adata.raw.X)
adata.obs['doublet_scores'], adata.obs['predicted_doublets'] = scrub.scrub_doublets()
scrub.plot_histogram()
sc.pl.umap(adata, color='doublet_scores')
```

**Comment by pinin4fjords** [comment]
Thanks @fidelram, that will run the whole Scrublet workflow so will certainly do the trick. But I'd prefer a more Scanpy-integrated approach, which I think I can see how to do from @swolock's fork.

**Comment by Tolupeter** [comment]
I have problem installing and importing scrublet on windows please can you help me
Here is my code !pip install scrublet
PackagesNotFoundError: The following packages are not available from current channels:

  - annoy

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch
  - https://conda.anaconda.org/pytorch/win-64
  - https://conda.anaconda.org/pytorch/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org/

and use the search bar at the top of the page.

**Comment by flying-sheep** [comment]
I started work to move `scrublet` into scanpy (since the last commit was 3 years ago and it’s safe to assume it’s not maintained anymore)

https://github.com/scverse/scanpy/pull/2703
