### ISSUE TITLE
how to subset cells in scanpy

### ISSUE THREAD

**Issue by FADHLyemen** [scverse/scanpy#1730]
...
In seurat, I used subset to subset cells, how can I do it in scanpy?

**Comment by LuckyMD** [comment]
This might be a more appropriate question for the discourse group. In scanpy you can subset in the same way you would subset a pandas dataframe. For example:

`adata_sub = adata[adata.obs['cell type'].isin(['Type A', 'Type B'])]`

This gives you the set of cells that have a `'cell type'` value of `'Type A'` or `'Type B'`.

**Comment by FADHLyemen** [comment]
Thank you
