### ISSUE TITLE
UMAP: discrete cell type clusters tend to distort UMAP embeddings

### ISSUE THREAD

**Issue by yueqiw** [scverse/scanpy#174]
Hi,

UMAP gives me nice embeddings when the cell types are mostly continuous. But I couldn't get it to work well on a dataset with more discrete cell types. When I use smaller min_dist to separate the clusters better, the clusters tend to become very tiny and distant. When I set larger min_dist to make the clusters occupy more space, the spatial separation between coarse clusters is gone.  Adjusting other parameters such as n_neighbors, spread, gamma doesn't give me good results either. 

This issue is somewhat similar to the first two UMAP plots in this notebook before doing special initialization: https://github.com/theislab/paga/blob/master/planaria/planaria.ipynb

`min_dist=0.2, n_neighbor=15`: Clear separation between coarse clusters, but clusters become tiny with too much white space. The clusters on the left seem to be repelling those on the right. 
<img src=https://user-images.githubusercontent.com/5046690/41402335-46cf92c4-6f7f-11e8-9b72-48d23d553356.png width=50%>

`min_dist=0.4`: The coarse-level clusters on the right are intermingled (the continuity between cluster 4 and 6 is now broken)
<img src=https://user-images.githubusercontent.com/5046690/41402348-57054968-6f7f-11e8-8e24-696ad4afb243.png width=50%>

`min_dist=0.6`: Cells are distributed more smoothly, but the separation between coarse clusters are much less obvious. 
<img src=https://user-images.githubusercontent.com/5046690/41402394-7252b00c-6f7f-11e8-9ffb-2d09a03fc131.png width=50%>

t-SNE in this case gives me more evenly distributed clusters
<img src=https://user-images.githubusercontent.com/5046690/41403178-8257e722-6f81-11e8-9b64-be274e82eadc.png width=50%>

Is there a way to make the UMAP look more intuitive in this kind of situations? Thanks!

(I changed the original question as I feel that this one is more important.)

**Comment by falexwolf** [comment]
Yes, I also noticed this behavior.

I'd say that your `min_dist=0.6` result is essentially the same as the tSNE result. I'd take this result.

I'm not sure whether this is fundamentally solvable - optimizing an embedding is a very hard task and UMAP has the best approach to this so far - this is one of the reasons why we came up with PAGA, which is not affected by these problems. PAGA gives you the correct picture of what is connected and what isn't. Note the [updated preprint](https://rawgit.com/falexwolf/paga_paper/master/paga.pdf), which provides an indepth explanation of these issues. Will replace the current bioRxiv preprint or appear in a journal soon.

**Comment by falexwolf** [comment]
Regarding your previous question: Scanpy currently has its own UMAP version as we needed a few more things and wanted to freeze a version. In Scanpy 2, we might change this and use the then more evolved UMAP package instead.

**Comment by falexwolf** [comment]
PS: I answered too quickly and wrote the above before checking that you had opened the issue in the umap repo... :wink:

**Comment by yueqiw** [comment]
Thanks for the updated preprint! It really helps better understand the updated PAGA algorithm.
