### ISSUE TITLE
read_mtx obs and var mixed

### ISSUE THREAD

**Issue by simjbaum** [scverse/scanpy#1761]
Hi,
I was reading some mtx file from here: 
https://www.ebi.ac.uk/gxa/sc/experiments/E-HCAD-4/downloads

`adata = sc.read_mtx("./data/mtx/E-HCAD-4.aggregated_filtered_counts.mtx")`
`AnnData object with n_obs × n_vars = 25052 × 606606
`  
`sc.__version__`
`'1.7.1'`

when loading the mtx file the obs and vars are mixed up.   
That happened with another mtx file before. I was wondering if already a fix exists to specify the obs and vars (or switch them if necessary).  

Thanks   

</details>
![image](https://user-images.githubusercontent.com/7283790/112545551-a19f4280-8db8-11eb-8e0d-7d56ee0443b5.png)

**Comment by ivirshup** [comment]
You can transpose the anndata object with `adata.T` or `adata.transpose()`. The issue is the difference in convention between `R` defaulting to fortran order arrays (putting observations on the columns), while python defaults to `C` order arrays (observations on rows).
