### ISSUE TITLE
sc.datasets.pbmc68k_reduced() didn't contain all the genes in .raw

### ISSUE THREAD

**Issue by brianpenghe** [scverse/scanpy#1762]
I'm using Scanpy 1.5.0.
sc.datasets.pbmc68k_reduced() gave me a really small object.
I was trying to retrieve the full transcriptome by using .raw but it only stored 700 genes.
Is there any chance for Scanpy to add the raw data back in that object?

**Comment by ivirshup** [comment]
So, that dataset is used pretty extensively in the tests, and especially around plotting (plus it's actually shipped with the library). I don't think we're likely to modify it, given that it's used so heavily as a reference.

What do you need it for, and could you use `pbmc3k_processed` for that purpose?

**Comment by brianpenghe** [comment]
I was trying some integration methods between the two pbmc datasets. Maybe, could you add a sc.datasets.pbmc68k_full() where the whole transcriptome is included?

**Comment by ivirshup** [comment]
I'm not sure if we're going to be able to find a full, analyzed copy of that dataset (I personally do not have a copy). It also would have been analyzed a few years ago, so would not have been following current best practice.

If you just want the full transcriptome, I believe this is the raw data: https://support.10xgenomics.com/single-cell-gene-expression/datasets/1.1.0/fresh_68k_pbmc_donor_a.

**Comment by brianpenghe** [comment]
Thanks that works!
