### ISSUE TITLE
small datasets

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/scanpy#1764]
Hi,
Scanpy are designed to handle big datasets, while how about the performance on small datasets ? (such as as few as 50 cells from early embryo)

**Comment by Zethson** [comment]
Dear @wangjiawen2013,

what is the interest behind your question? Do you have many datasets with very few cells?
Scanpy itself can easily work with very small datasets, but you should always be aware of statistical limitations when performing statistical tests etc on very few cells.

**Comment by wangjiawen2013** [comment]
We knocked out a gene, then wanna to reveal the difference between KO embro cells and wild type embryo cells and illustrate the function of the gene in development process. The single cell data was generated using Smart-seq2 technology, which is a low throughput technology. And besides, there were only a few cells in eary embros because they are very small.

**Comment by Zethson** [comment]
All right. Guess my answer would be the same. Technically yes, but be aware of statistical limitations.
