### ISSUE TITLE
The axis-y limits of sc.pl.rank_genes_groups_violin()

### ISSUE THREAD

**Issue by storytc** [scverse/scanpy#1766]
Hi
Thanks for the brilliant tool! And my poblem is when I use sc.pl.rank_genes_groups_violin() function, the y axis limits of the output seems impalpable.Here's my output:
![image](https://user-images.githubusercontent.com/65101587/112634253-3a50b500-8def-11eb-84dd-28591804266b.png)
Can I modify the y axis limits? I'm sorry I haven't find the parameters yet.
And when I try to use `use_raw=False`,  I got error:
`ValueError: Data must be 1-dimensional`
`ValueError: Cannot set a frame with no defined index and a value that cannot be converted to a Series`
And my code:
`sc.tl.rank_genes_groups(merge_data, 'sampleID', groups=['WT_BM'], reference='KO_BM', method='wilcoxon',corr_method='bonferroni')`
and my version:
`scanpy==1.7.1 anndata==0.7.5 umap==0.4.6 numpy==1.19.1 scipy==1.5.4 pandas==1.2.0 scikit-learn==0.24.0 statsmodels==0.12.1 python-igraph==0.8.3 leidenalg==0.8.3`

Thank you. Hope for you answer!
Best,
Ariel.

**Comment by ivirshup** [comment]
Hmm, that definitely looks wrong! I'm not able to get any similar results, so my suspicion is that there may be a large outlier somewhere in that data.

However, you should be able to set the ylimits on the `Axes` returned by the plot. For example, something like:

```python
for ax in sc.pl.rank_genes_groups_violin(pbmc, ['B cells'], show=False)
    ax.set_ylim(0, 3)
```

**Comment by storytc** [comment]
Hi, 
thanks for your patience to reply!
Yes, I use the raw matrix to call DEGs, maybe that's the point.
And your codes definitely works! Thanks again!

Best, 
Ariel.
