### ISSUE TITLE
PEP 621/ 631 Metadata

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#1776]
Update `pyproject.toml` to use [PEP-621](https://www.python.org/dev/peps/pep-0621/) and [PEP-631](https://www.python.org/dev/peps/pep-0631/) metadata. Basically, simplify by removing most of the `tool.flit` stuff.

@flying-sheep, would you like to do this/ do you foresee any blockers?

**Comment by flying-sheep** [comment]
The Flit PR says that support is experimental, so maybe we should wait until it’s no longer marked as such?

Flit itself switched to that metadata format though and we should be able to verify if the packages are created correctly.

**Comment by ivirshup** [comment]
It seems to no longer be experimental

**Comment by astrojuanlu** [comment]
Also, consider setting `flit >=3.4` for editable installs via [PEP 660](https://www.python.org/dev/peps/pep-0660/) 😃
