### ISSUE TITLE
scvi.models needs to be changed to scvi.module in _scvi.py

### ISSUE THREAD

**Issue by dacianstremtan** [scverse/scanpy#1781]
- [x ] I have checked that this issue has not already been reported.
- [ x] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.
scvi does not have models class anymore to access VAE and LDVAE, please change it to use scvi.module

### Minimal code sample (that we can copy&paste without having any data)

```python
import scanpy as sc
sc.external.pp.scvi(adata, train_size=0.8, batch_key='batch')
```

```pytb
  File "/usr/local/apps/python/3.9.4/lib/python3.9/site-packages/scanpy/external/pp/_scvi.py", line 116, in scvi
    from scvi.models import VAE, LDVAE
ModuleNotFoundError: No module named 'scvi.models'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/lab/MCF7/for_PAGA/MCF7_batch_attempt1.py", line 140, in <module>
    sc.external.pp.scvi(adata, train_size=0.8, batch_key='batch')
  File "/usr/local/apps/python/3.9.4/lib/python3.9/site-packages/scanpy/external/pp/_scvi.py", line 120, in scvi
    raise ImportError(
ImportError: Please install scvi package from https://github.com/YosefLab/scVI

```

#### Versions
>>> scanpy.logging.print_versions() 
WARNING: If you miss a compact list, please try `print_header`!
-----
anndata     0.7.5
scanpy      1.7.1
sinfo       0.3.1
-----
PIL                 8.2.0
anndata             0.7.5
cffi                1.14.5
colorama            0.4.4
cycler              0.10.0
cython_runtime      NA
dateutil            2.8.1
get_version         2.1
google              NA
h5py                3.2.1
igraph              0.9.1
joblib              1.0.1
kiwisolver          1.3.1
legacy_api_wrap     1.2
leidenalg           0.8.3
llvmlite            0.36.0
matplotlib          3.4.1
mpl_toolkits        NA
natsort             7.1.1
numba               0.53.1
numexpr             2.7.3
numpy               1.20.2
packaging           20.9
pandas              1.2.3
pkg_resources       NA
pyexpat             NA
pyparsing           2.4.7
pytz                2021.1
scanpy              1.7.1
scipy               1.6.2
setuptools_scm      NA
sinfo               0.3.1
six                 1.15.0
sklearn             0.24.1
sphinxcontrib       NA
tables              3.6.1
texttable           1.6.3
typing_extensions   NA
wcwidth             0.2.5
yaml                5.3.1
-----
Python 3.9.4 (default, Apr  5 2021, 15:43:56) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
Linux-3.10.0-1160.11.1.el7.x86_64-x86_64-with-glibc2.17
56 logical CPU cores, x86_64
-----
Session information updated at 2021-04-06 12:14

</details>

**Comment by adamgayoso** [comment]
This is likely because you have [`scvi-tools`](https://scvi-tools.org/) and this wrapper supports our now deprecated `scvi` package.

This wrapper will be removed in the next release, so I recommend using scvi-tools directly.

**Comment by ivirshup** [comment]
Since the API being used here is deprecated, as is the wrapper, I'm inclined leave this as is.
