### ISSUE TITLE
low-resolution plots for the latest version

### ISSUE THREAD

**Issue by huidongchen** [scverse/scanpy#1791]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can copy&paste without having any data)

1) create a new env
```bash
conda create -n test_scanpy python=3.7 ipykernel scanpy -y
```

2) tutorial notebook
[test_scanpy.html.zip](https://github.com/theislab/scanpy/files/6272105/test_scanpy.html.zip)

**Comment by ivirshup** [comment]
The `dpi` for each plot is set in the third cell of the notebook with `sc.settings.set_figure_params(dpi=80, facecolor='white')`. If you'd like higher resolution images, you can increase the `dpi` value there.

**Comment by huidongchen** [comment]
Thanks very much for your reply.  

Yes, I am aware ‘dpi’ can help increase the resolution. However, I noticed that with the same ‘dpi’ , in the latest version of scanpy, the plots look more blurry than before. (You can easily see the difference between the notebook attached here and the tutorial on scanpy website.

on the other hand, simply increasing ‘dpi’ will also increase the plot size, which is not really wanted in most cases.

**Comment by ivirshup** [comment]
I'm not able to see any obvious difference on my machine. Maybe you could produce a side by side example? It would be good to make sure any differences you're observing aren't coming from different versions of matplotlib or seaborn.
