### ISSUE TITLE
Enable GPU accelerated CI Jobs

### ISSUE THREAD

**Issue by Zethson** [scverse/scanpy#1793]
A lot of computing will be GPU accelerated in the near and distant future. ScanPy is no exception as was recently demonstrated by NVIDIA. We got a nice PR (https://github.com/theislab/scanpy/pull/1533) to get started, but we are hesitant to merge it since we cannot yet cover GPU accelerated algorithms with our CI.

- [ ] Get machines with GPUs
- [ ] Set them up with CUDA etc
- [ ] Explore whether GA or Azure suits us better for a custom runner
- [ ] Hook up the custom runner with the ScanPy repository
- [ ] Investigate whether we should use custom triggers for GPU related PRs or just always run them
- [ ] Write GPU only tests

**Comment by Zethson** [comment]
Resources that may help:

- https://www.youtube.com/watch?v=rVq-SCNyxVc
- https://dvc.org/blog/cml-self-hosted-runners-on-demand-with-gpus

**Comment by LouisFaure** [comment]
In case this helps, all gpu accelerated code implemented in scanpy use rapids related packages, which can be easily deployed by using their [docker images](https://hub.docker.com/r/rapidsai/rapidsai-core) and are updated on a regular basis! There is the choice of multiple os and python versions, although windows is not present.

**Comment by aktech** [comment]
Hi @Zethson I am the creator of Cirun.io, "GPU" and "CI" caught my eye.

FWIW I'll share my two cents. I created a service for problems like these, which is basically running custom machines (including GPUs) in GitHub Actions: https://cirun.io/

It is used in multiple open source projects needing GPU support like the following:

https://github.com/pystatgen/sgkit/
https://github.com/qutip/qutip-cupy

It is fairly simple to setup, all you need is a cloud account (AWS or GCP) and a simple yaml file describing what kind of machines you need and Cirun will spin up ephemeral machines on your cloud for GitHub Actions to run. It's native to GitHub ecosystem, which mean you can see logs/trigger in the Github's interface itself, just like any Github Action run.

Also, note that Cirun is free for Open source projects. (You only pay to your cloud provider for machine usage)

**Comment by Zethson** [comment]
Hi @aktech,

thank you for your comment. I only see support for AWS, GCP and DO. For us it would be much easier to stick with our Azure setup (payments etc much easier). Is there a way to use it with Azure?

**Comment by aktech** [comment]
Thanks for your response. As of today that's correct: AWS, GCP and DO. Azure support is a work in progress at the moment. It should be available by the end of this month most likely. Do you have a hard deadline on this?

**Comment by Zethson** [comment]
> 
> 
> Thanks for your response. As of today that's correct: AWS, GCP and DO. Azure support is a work in progress at the moment. It should be available by the end of this month most likely. Do you have a hard deadline on this?

No we don't. But before using it Cirun I would have to look at more closely first.

**Comment by ghost** [comment]
Hi @Zethson,
I'm curious whether you have a status update on this. Would be really excited to have GPU-accelerated Leiden, but I understand the issues you mention here. Thanks!

**Comment by Zethson** [comment]
@maarten-hifibio we are indeed actively working on this again. Feel free to join our zulip https://scverse.zulipchat.com/login/ and ping me. I can add you to the conversation.

**Comment by LouisFaure** [comment]
@maarten-hifibio in the mean time if you need it I have just made some GPU wrappers available on the following gist:
https://gist.github.com/LouisFaure/9302aa140d7989a25ed2a44b1ce741e8

It includes one for leiden that would exactly act like sc.tl.leiden (it is part of my PR referenced here)

**Comment by ghost** [comment]
Thank you very much, @LouisFaure. This is super helpful!

**Comment by Zethson** [comment]
Closing in favor of https://github.com/scverse/rapids_singlecell 🚀
