### ISSUE TITLE
Hello I am trying to save the object with this command but it is not working. I used this command to save the objects before and it was working always.

### ISSUE THREAD

**Issue by Pawan291** [scverse/scanpy#1795]
- [ ] I have checked that this issue has not already been reported.
- [ ] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can copy&paste without having any data)

```python
## save command
adata.write(folder + "before_regression.h5ad")
```

```pytb
[Paste the error output produced by the above code here]
```

#### Versions

<details>

[Paste the output of scanpy.logging.print_versions() leaving a blank line after the details tag]

</details>

**Comment by Zethson** [comment]
Please provide more details. What is `folder` in your case and what is the error message? Follow the issue template, please.

**Comment by Pawan291** [comment]
Hello, I am using the folder where I store the raw data for the analysis. There is no error message when I run the command but it does not generate any file or object with this name or any name.

**Comment by Zethson** [comment]
What is the content of the variable `folder`? There must be an error message or else you are not executing the code.

**Comment by Pawan291** [comment]
The variable folder has one file in .h5ad format as input or raw data. No, I execute the code correctly because every time I run this command or move forward with other commands, the number on the kernel increases without any error message. But in a folder, no object is generated.

**Comment by Pawan291** [comment]
After spending a lot of time, I find out that the directory was changed somehow and the object was being saved in some other folder. So I changed the directory again to the destinated folder where I want to save these objects.
But I would like to thank you for the help. :)

**Comment by Zethson** [comment]
> I find out the solution. Thank You

Although I think that this is not an issue with Scanpy, it is usually common courtesy to post the solution to the corresponding issue. If other people search for the same error they can find your solution :)
