### ISSUE TITLE
sc.pl.umap ax argument not working

### ISSUE THREAD

**Issue by fteufel** [scverse/scanpy#1802]
I'm trying to plot UMAP plots on predefined axes in `plt.subplots`.
```
fig, ax = plt.subplots(1,3)
sns.boxplot(x="CytoTRACE", data=adata.obs, ax=ax[0])
sc.pl.umap(adata, color='Batch', ax=ax[1])
sc.pl.umap(adata, color='CytoTRACE', ax=ax[2])
```
However, after the first call, the axes argument does not seem to work anymore:
![image](https://user-images.githubusercontent.com/56223326/115447250-905f1f80-a218-11eb-8675-f1be00ea1e5e.png)

Is there any additional flag I am missing?

**Comment by davidhbrann** [comment]
I think if you add `show=False` to the `sc.pl.umap` commands it might work? 

Depending on the type grid and subplots, it could be easier to plot things manually with matplotlib (to have more control over things like legend placement etc)
