### ISSUE TITLE
dispersions_norm definition

### ISSUE THREAD

**Issue by moqri** [scverse/scanpy#1803]
...

How is the dispersions_norm defined in Scanpy?
--

**Comment by giovp** [comment]
@moqri bit difficult to answer this question. What are you referring to?

if you are referring to this: https://scanpy.readthedocs.io/en/stable/api/scanpy.pp.filter_genes_dispersion.html

then the docs are pretty clear: 
```
The normalized dispersion is obtained by scaling with the mean and standard deviation of the dispersions for genes falling into a given bin for mean expression of genes. This means that for each bin of mean expression, highly variable genes are selected.
```

**Comment by moqri** [comment]
Thanks @giovp! 
I am using this measure to get the genes with most varied expression in my sample. I was wondering if the exact formula used to calculate dispersions_norm is documented in the reference? I believe it is based on dividing std by mean expression and then normalizing it somehow but an exact definition or formula would be greatly helpful.

**Comment by giovp** [comment]
Ok so you are probably using this: https://scanpy.readthedocs.io/en/stable/api/scanpy.pp.highly_variable_genes.html

you can check the definition in the docs:
```
For the dispersion-based methods ([Satija15] and [Zheng17]), the normalized dispersion is obtained by scaling with the mean and standard deviation of the dispersions for genes falling into a given bin for mean expression of genes. This means that for each bin of mean expression, highly variable genes are selected.
```

this slightly changes according to the `flavour`, all citations are also mentioned in the docs (link above). does this help?
