### ISSUE TITLE
Address edge cases in gearys_c and morans_i

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#1806]
Ref https://github.com/theislab/scanpy/issues/1698#issuecomment-824634639, cut down in https://github.com/theislab/scanpy/issues/1698#issuecomment-826712541

Basically, `gearys_c`, `morans_i` can run into silent numba parallelization errors when all values for a variable are the same. We should specifically address these cases.

As suggested by @Hrovatin, `nan` and a warning is probably sufficient for this case. That said, it may take some work to consistently throw a warning

* Depending on the threading backend, this may error (solving the problem of incorrect values)
  * We may be able to control this, but how the parallel backend interacts with the `error_model` seems unclear
* I don't think we can throw a warning from numba code, let alone parallel numba code
* It would be nice if we could guarantee a `tbb` or `omp` threading backend, since they seem more consistent, but I personally have not been able to `pip install` these for a bit over a year now. This may be macOS specific.

**Comment by giovp** [comment]
@ivirshup checking for `np.nonzero(np.var(adata.X))` do you think it would be enough?
I agree that just throwing a warning and adding nan would be enough, could be done as an additional check in the function.

**Comment by ivirshup** [comment]
I think that we can be a bit more efficient than `var`. Also, as this has come up before (with `scale`) it's probably worth a utility function. I think I've got something.
