### ISSUE TITLE
sc.datasets.pbmc68k_reduced needs updating

### ISSUE THREAD

**Issue by bio-la** [scverse/scanpy#1816]
- [x] I have checked that this issue has not already been reported.
- [ ] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

### Minimal code sample 

```python
import scanpy as sc
import numpy as np
import pandas as pd
adata = sc.datasets.pbmc68k_reduced()
sc.pl.pca_loadings(adata, components = '1,2,3')

```

```pytb
ValueError: Axis limits cannot be NaN or Inf
```
**Note**:  recalculating pca solves the problem 

#### Versions

<details>

-----
anndata     0.7.5
scanpy      1.8.0.dev78+gc488909a
sinfo       0.3.1
-----
PIL                 7.2.0
anndata             0.7.5
appnope             0.1.0
attr                19.3.0
backcall            0.2.0
bottleneck          1.3.2
cffi                1.14.0
cloudpickle         1.5.0
colorama            0.4.3
cycler              0.10.0
cython_runtime      NA
cytoolz             0.10.1
dask                2.20.0
dateutil            2.8.1
decorator           4.4.2
get_version         2.1
h5py                2.10.0
idna                2.10
igraph              0.8.3
ipykernel           5.3.2
ipython_genutils    0.2.0
ipywidgets          7.5.1
jedi                0.17.1
jinja2              2.11.2
joblib              0.16.0
jsonschema          3.2.0
kiwisolver          1.2.0
legacy_api_wrap     1.2
llvmlite            0.33.0+1.g022ab0f
louvain             0.7.0
markupsafe          1.1.1
matplotlib          3.2.2
mkl                 2.3.0
mpl_toolkits        NA
natsort             7.1.0
nbformat            5.0.7
numba               0.50.1
numexpr             2.7.1
numpy               1.18.5
packaging           20.4
pandas              1.0.5
parso               0.7.0
pexpect             4.8.0
pickleshare         0.7.5
pkg_resources       NA
prometheus_client   NA
prompt_toolkit      3.0.5
psutil              5.7.0
ptyprocess          0.6.0
pvectorc            NA
pygments            2.6.1
pyparsing           2.4.7
pyrsistent          NA
pytz                2020.1
scanpy              1.8.0.dev78+gc488909a
scipy               1.5.0
seaborn             0.10.1
send2trash          NA
setuptools_scm      NA
sinfo               0.3.1
six                 1.15.0
sklearn             0.23.1
sphinxcontrib       NA
statsmodels         0.11.1
storemagic          NA
tables              3.6.1
tblib               1.6.0
texttable           1.6.3
tlz                 0.10.1
toolz               0.10.0
tornado             6.0.4
traitlets           4.3.3
typing_extensions   NA
wcwidth             0.2.5
yaml                5.3.1
zmq                 19.0.1
zope                NA
-----
IPython             7.16.1
jupyter_client      6.1.6
jupyter_core        4.6.3
jupyterlab          2.1.5
notebook            6.0.3
-----
Python 3.8.3 (default, Jul  2 2020, 11:26:31) [Clang 10.0.0 ]
macOS-10.15.7-x86_64-i386-64bit
4 logical CPU cores, i386
-----
Session information updated at 2021-04-27 11:22

</details>

**Comment by ivirshup** [comment]
`sc.datasets.pbmc68k_reduced` is very useful as an example of a very old anndata file, so I'd like to keep it around.

Could you use `pbmc3k_processed` for this? It hasn't had `highly_variable_genes` run on it anyways (though maybe it should).

**Comment by bio-la** [comment]
sure, makes sense, thanks!
