### ISSUE TITLE
scanpy fails in conda env with python 3.9.4

### ISSUE THREAD

**Issue by mughetto** [scverse/scanpy#1823]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

Apologies if this is issue is already know but I couldn't find it and the doc advertises python 3.6 so I figured I would report it.

---
### Minimal code sample (that we can copy&paste without having any data)

After following Anaconda installation instructions in a brand new conda env created with python 3.9.4:

```python
import scanpy as sc
```
returns:
```pytb
Illegal instruction (core dumped)
```

Another brand new env with 3.7 imports scanpy successfully. 

#### Versions
scanpy 1.7.2

**Comment by xgrau** [comment]
I have also encountered this bug with the same software versions (pyton 3.9.4, scanpy 1.7.2).

**Comment by ivirshup** [comment]
Closing as:

* The original issue looks like a numba related problem, which I believe didn't work with python 3.9 at the time.
* We're past the 1.7 release series and aren't supporting it anymore

**Comment by pranzatelli** [comment]
Please re-open this; currently receiving this error with Python 3.9.7 and scanpy 1.8.2. Just in case it's useful, CPU flags including instruction sets are pasted below.

fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt lwp fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb cpb hw_pstate ssbd ibpb vmmcall bmi1 arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold

**Comment by ivirshup** [comment]
@pranzatelli, could you open a new issue for this? In that issue, could you also report what versions of the dependencies you're using via `sc.logging.print_versions()`?
