### ISSUE TITLE
how to plot cell types, medication per cohort in one figure 

### ISSUE THREAD

**Issue by FADHLyemen** [scverse/scanpy#1824]
- [ ] Additional function parameters / changed functionality / changed defaults?
- [ ] New analysis tool: A simple analysis tool you have been using and are missing in `sc.tools`?
- [x] New plotting function: A kind of plot you would like to seein `sc.pl`?
- [ ] External tools: Do you know an existing package that should go into `sc.external.*`?
- [ ] Other?

...
I am wondering if scanpy has an option to plot three dimension of information in one plot such as stacked barplot. I need to show cell types distribution in absent/present of medication per each cohort.

**Comment by Zethson** [comment]
![image](https://user-images.githubusercontent.com/21954664/117554339-4919c100-b057-11eb-8684-e32e74ea9e14.png)

Would something like this suit?
You could use the sc-toolbox: https://sc-toolbox.readthedocs.io/en/latest/usage.html#sc_toolbox.api.plot.cluster_composition_stacked_barplot

**Comment by FADHLyemen** [comment]
This is wonderful @Zethson

**Comment by Zethson** [comment]
@FADHLyemen Think I forgot tell you how to calculate the relative frequencies. Here you go: https://sc-toolbox.readthedocs.io/en/latest/usage.html#sc_toolbox.api.calc.relative_frequencies

**Comment by FADHLyemen** [comment]
Thank you, do you have sankey plot also. another point, do you know which test to use to see which cell types are significant between groups?

**Comment by Zethson** [comment]
No, I don't have Sankey plots. 
Regarding significance we usually use https://github.com/theislab/diffxpy/

**Comment by FADHLyemen** [comment]
I do not want to compare cells based on genes, I  want to know which cell types are differ among groups

**Comment by LuckyMD** [comment]
Hey! You can check out [scCODA](https://github.com/theislab/scCODA) for differential composition analysis.

**Comment by dm8000** [comment]
do you mind if I pigback on your issue?

is this usage example correct?

```
relative_frequencies=sct.calc.relative_frequency_per_cluster(adata2, group_by='Author', xlabel='leiden_0.6', condition=None)
print(relative_frequencies)
sct.plot.cluster_composition_stacked_barplot(relative_frequencies, xlabel='Author', figsize=(6, 10), width=0.8, order=None, error_bar=None, label_size=15, tick_size=13, capsize=None, margins=(0.02, 0.04), cols=None, save=None)
```

I am getting this output
```

                    0         1         2         3         4         5  \
Benitez      0.087607  0.175214  0.076923  0.183761  0.059829  0.150997   
Rajbhandari  0.106852  0.079310  0.063879  0.098888  0.023395  0.243239   
Sarvari      0.078359  0.252695  0.120431  0.116487  0.224560  0.028662   
Sun          0.408022  0.163329  0.151518  0.108632  0.089583  0.009960   

                    6         7         8         9       Author  
Benitez      0.111111  0.133191  0.021368  0.000000      Benitez  
Rajbhandari  0.221171  0.011448  0.151485  0.000332  Rajbhandari  
Sarvari      0.033921  0.084407  0.021299  0.039180      Sarvari  
Sun          0.008545  0.056112  0.004245  0.000054          Sun  

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-44-a5b07a2bfb6d> in <module>
      6 relative_frequencies=sct.calc.relative_frequency_per_cluster(adata2, group_by='Author', xlabel='leiden_0.6', condition=None)
      7 print(relative_frequencies)
----> 8 sct.plot.cluster_composition_stacked_barplot(relative_frequencies, xlabel='Author', figsize=(6, 10), width=0.8, order=None, error_bar=None, label_size=15, tick_size=13, capsize=None, margins=(0.02, 0.04), cols=None, save=None)

/data04/projects04/MarianaBoroni/lbbc_members/lib/conda_envs/diogoamb/lib/python3.9/site-packages/sc_toolbox/api/plot/__init__.py in cluster_composition_stacked_barplot(relative_frequencies, xlabel, figsize, width, order, error_bar, label_size, tick_size, capsize, margins, cols, save)
    835     for i, typ in enumerate(reversed(cell_types)):
    836         fig = sb.barplot(
--> 837             data=plot_data, x=xlabel, y=typ, order=order, ci=ci, errcolor="black", color=cols[i], capsize=capsize
    838         )
    839         patches.append(mpatches.Patch(color=cols[i], label=typ))

TypeError: 'NoneType' object is not subscriptable


```

**Comment by Zethson** [comment]
@dm8000 could you please open an issue at https://github.com/schillerlab/sc-toolbox

I will check it out then. It's a sc-toolbox issue and not directly Scanpy related :)

**Comment by dm8000** [comment]
> @dm8000 could you please open an issue at https://github.com/schillerlab/sc-toolbox
> 
> I will check it out then. It's a sc-toolbox issue and not directly Scanpy related :)

sure! thank you, I will post there!

**Comment by Zethson** [comment]
I will close this issue because there is an external solution available. We may think about integrating this specific plot into Scanpy at some point, but I don't see it happening anytime soon.
