### ISSUE TITLE
Which  statistical test to use to see which cell types frequency  differ between cohorts?

### ISSUE THREAD

**Issue by FADHLyemen** [scverse/scanpy#1831]
- [ ] Additional function parameters / changed functionality / changed defaults?
- [ ] New analysis tool: A simple analysis tool you have been using and are missing in `sc.tools`?
- [ ] New plotting function: A kind of plot you would like to seein `sc.pl`?
- [ ] External tools: Do you know an existing package that should go into `sc.external.*`?
- [ ] Other?

Hi, 
If this is frequency table per cohort
which test to use to identify significant cell type per group? 
![image](https://user-images.githubusercontent.com/23288387/117582425-efa1a880-b0cf-11eb-8095-2f7ecacaf7b0.png)

...

**Comment by mdmanurung** [comment]
Hi @FADHLyemen,

You can export the raw count table (before calculating the percentage) into R for downstream analysis using `edgeR`. You can follow the following link to find further information: https://bioconductor.org/books/release/OSCA/multi-sample-comparisons.html#differential-abundance

Regards,
Mikhael

**Comment by LuckyMD** [comment]
Hey! Check out [scCoda](https://github.com/theislab/scCODA) for a differential abundance testing framework in python that is anndata compatible. As statistics are calculated on the sample level, you would however need more than 2 samples to be able to assess significance.
