### ISSUE TITLE
Project query dataset onto umap of existing reference dataset

### ISSUE THREAD

**Issue by 321356766** [scverse/scanpy#1847]
- [ ] Additional function parameters / changed functionality / changed defaults?
- [ ] New analysis tool: A simple analysis tool you have been using and are missing in `sc.tools`?
- [ ] New plotting function: A kind of plot you would like to seein `sc.pl`?
- [ ] External tools: Do you know an existing package that should go into `sc.external.*`?
- [X] Other?

Would it be possible to project a query dataset onto an existing reference umap, such that the reference dataset is not altered? The readout would be the existing reference umap with perhaps the density of query cells overlaid on top. Perhaps also quantification of the percentage of query cells falling into specific clusters on the reference data set?  Apologies if this already exists, I would be very interested to know how to do this using the anndata framework. Thanks.

**Comment by Koncopd** [comment]
https://scanpy-tutorials.readthedocs.io/en/latest/integrating-data-using-ingest.html
Hi, this should be relevant.

**Comment by 321356766** [comment]
Thank you.
