### ISSUE TITLE
Gradient color 

### ISSUE THREAD

**Issue by terooatt** [scverse/scanpy#185]
Hi,
I really like using scanpy for our large scale  single cell aging project. I am uploading several libraries from different age mice (8 time points) and concatinate them together (see example cmd I used below). I would like to control the color display so that I have a gradient color that changes with age and visualise in umap plot for example sc.pl.umap(adata, color= ['Age','louvain']). How could I do that? Thank you very for your help and for this wonderful package.

path = '/home/10XG6_ILC2_thirdrun/cellranger_count_results/13_mouse_IL33_8w_X/outs/filtered_gene_bc_matrices/mm10/'
adata_13_mouse_IL33_8w_X = sc.read(path + 'matrix.mtx', cache=True).transpose()
adata_13_mouse_IL33_8w_X.var_names = np.genfromtxt(path + 'genes.tsv', dtype=str)[:, 1]
adata_13_mouse_IL33_8w_X.obs_names = np.genfromtxt(path + 'barcodes.tsv', dtype=str)
adata_13_mouse_IL33_8w_X.obs['Tissue'] = 'X'
adata_13_mouse_IL33_8w_X.obs['Age'] = '8Weeks'
adata_13_mouse_IL33_8w_X.obs['State'] = 'IL33_activated'
sc.pp.filter_cells(adata_13_mouse_IL33_8w_X, min_genes=250)

path = '/home/10XG6_ILC2_thirdrun/cellranger_count_results/1_mouse_IL33_16w_X/outs/filtered_gene_bc_matrices/mm10/'
adata_1_mouse_IL33_16w_X = sc.read(path + 'matrix.mtx', cache=True).transpose()
adata_1_mouse_IL33_16w_X.var_names = np.genfromtxt(path + 'genes.tsv', dtype=str)[:, 1]
adata_1_mouse_IL33_16w_X.obs_names = np.genfromtxt(path + 'barcodes.tsv', dtype=str)
adata_1_mouse_IL33_16w_X.obs['Tissue'] = 'X'
adata_1_mouse_IL33_16w_X.obs['Age'] = '16Weeks'
adata_1_mouse_IL33_16w_X.obs['State'] = 'IL33_activated'
sc.pp.filter_cells(adata_1_mouse_IL33_16w_X, min_genes=250)

etc............

adata = adata_13_mouse_IL33_8w_X.concatenate([adata_1_mouse_IL33_16w_X, etc ....)

**Comment by falexwolf** [comment]
Numeric annotation is automatically visualized with a gradient color (`color_map` argument). String/ Categorical annotation is automatically visualized using palettes (`palette` argument, and `.uns['ANNO_colors']` annotation).

If you provide the 'Age' annotation as a numeric (e.g. an integer): `8` instead of `'8Weeks'`, everything will work out fine.

**Comment by terooatt** [comment]
That was easy. Thank you very much.
