### ISSUE TITLE
Use session_info instead of sinfo

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#1852]
[`sinfo` has been replaced](https://pypi.org/project/sinfo/) with [`session_info`](https://gitlab.com/joelostblom/session_info), which is definitely a better name. We should switch over to using this.

I think we'll be calling it like: `import session_info; session_info.show(dependencies=True, html=False, **extra_kwargs)`

**Comment by flying-sheep** [comment]
`html=False` would be quick, but we can actually benefit from `html=True`. I think in #2089, I’m doing it right
