### ISSUE TITLE
`key_added` to UMAP, tSNE, PCA

### ISSUE THREAD

**Issue by adamgayoso** [scverse/scanpy#1861]
- [x] Additional function parameters / changed functionality / changed defaults?
- [ ] New analysis tool: A simple analysis tool you have been using and are missing in `sc.tools`?
- [ ] New plotting function: A kind of plot you would like to seein `sc.pl`?
- [ ] External tools: Do you know an existing package that should go into `sc.external.*`?
- [ ] Other?

It would be great to manually specify the `.obsm` key generated by the `.tl` functions like UMAP, PCA, etc.

`sc.tl.umap(adata, key_added="X_custom_umap")`

**Comment by ivirshup** [comment]
Definitely been an abstract todo for a while. Tracking for 1.9

Some questions:

* What about methods where more than one element is added to the AnnData? E.g. for PCA we also add the variable loadings to `varm`
* How do these parameters get tracked in the `uns` metadata? Currently the key added there is largely fixed, but maybe it should vary too.

**Comment by TheAustinator** [comment]
In the interim, this pattern works
```
def pca(adata: AnnData, key_added: str, **kwargs):
    _adata = sc.pp.pca(adata, copy=True, **kwargs)
    adata.obsm[key_added] = _adata.obsm["X_pca"]
```

**Comment by ivirshup** [comment]
@adamgayoso, have you had any thoughts here about how we manage the `key` for variable loadings?

**Comment by adamgayoso** [comment]
maybe the option is something like `key_added_root="pca"` which adds `.obsm[f"X_pca_{key_added_root}"]` and `.varm[f"pca_loadings_{key_added_root}"`?

**Comment by ivirshup** [comment]
I'm not loving how long those are. Do you do anything similar in scvi-tools?

**Comment by adamgayoso** [comment]
We don't add anything into anndata automatically, so no.

**Comment by flying-sheep** [comment]
since we want to get rid of the `X_` prefix (see #3188), I went ahead with the most obvious design in #3184
