### ISSUE TITLE
sc.tl.pca too slow

### ISSUE THREAD

**Issue by brianpenghe** [scverse/scanpy#1865]
I noticed the calculating PCA only uses one core.
Is it possible to make it faster?

**Comment by ivirshup** [comment]
I think the level of threading can be dependent on BLAS/ LAPACK etc. However, it should generally be multithreaded. Does the issue persist in a conda environment?

If you still run into issues I'd be interested in seeing some details (e.g. what size and kind of matrix, cpu usage during computation). A counter example of a faster way to compute it could be useful to see too.

**Comment by ivirshup** [comment]
I would say, I have been noticing a few cases recently where the PCA is not as threaded as I would expect. I suspect this is correlated with denser data, e.g. the sparse SVD may be getting bottle necked at some single threaded point as the data becomes more dense. Possibly worth investigating a bit more.
