### ISSUE TITLE
rank_genes_groups p value decimal places

### ISSUE THREAD

**Issue by mvis1231** [scverse/scanpy#1869]
Hi,
Thank you for your amazing package!

I ran "sc.tl.rank_genes_groups" on Jupyter Notebook, and when I did: 

`pd.DataFrame(
    {group + '_' + key[:1]: result[key][group]
    for group in groups for key in ['names', 'pvals_adj', 'logfoldchanges']})`

I was only able to see 0.0 for p-values and adjusted p-values for all of the 2,000 highly variable genes, while logfoldchanges showed 6 decimal places like 1.816276. 

The version of Scanpy that I am using is 1.7.2, and I was wondering if there was a way to see more decimal places for p-values and adjusted p-values, like in the form of 3.642456e-222 in your tutorial.

If this is not a formatting problem, do you think the Wilcoxon test gave me 0.0 for all the highly variable genes? 
Based on sc.pl.rank_genes_groups, the scores for 25 genes per cluster are pretty high though (most of them are in a range of 100-200).

I am pretty new to python and scanpy, so your advice will be greatly helpful.
Thank you!

**Comment by ivirshup** [comment]
I believe formatting for values here would be controlled by [pandas](https://pandas.pydata.org/docs/user_guide/style.html) or whatever environment you're using to view them. If you could show some of the output that would be helpful, e.g. a screenshot or copy and pasting the text. `0.0` does seem pretty unlikely for those p-values.

Btw, you may want to use `sc.get.rank_genes_groups_df`, which is like that snippet you posted.

**Comment by eroell** [comment]
Thank you for bringing up this issue!

We will close the issue for now, as based on the provided information and the discussion so far, it seems that the question has been addressed and hopefully resolved :)

However, please don't hesitate to reopen this issue or create a new one if you have any more questions or run into any related problems in the future.

Thanks for being a part of our community! :)
