### ISSUE TITLE
filter based on expression cutoff for two genes

### ISSUE THREAD

**Issue by FADHLyemen** [scverse/scanpy#1870]
- [ ] Additional function parameters / changed functionality / changed defaults?
- [ ] New analysis tool: A simple analysis tool you have been using and are missing in `sc.tools`?
- [ ] New plotting function: A kind of plot you would like to seein `sc.pl`?
- [ ] External tools: Do you know an existing package that should go into `sc.external.*`?
- [ ] Other?

...
I need to filter the cells which  expressed 'A' and 'B' genes >1
 The below line  should work for one gene but how to do it for two genes?
`adata = adata[adata[: , 'A'].X > 1, :] `

**Comment by LuckyMD** [comment]
Hi @FADHLyemen,

You can string together conditions to subset an AnnData object as any other data structure in python. The following should work:
`adata = adata[(adata[: , 'A'].X > 1) & (adata[: , 'B'].X > 1), :]`

**Comment by JBreunig** [comment]
While the single command works `adata = adata[adata[: , 'A'].X > 1, :]`

The compound command gives me the following error: 
TypeError: unsupported operand type(s) for &: 'SparseCSRView' and 'SparseCSRView'

**Comment by zhou-1314** [comment]
> While the single command works `adata = adata[adata[: , 'A'].X > 1, :]`
> 
> The compound command gives me the following error: TypeError: unsupported operand type(s) for &: 'SparseCSRView' and 'SparseCSRView'

Have you solved it? I have a similar problem. 

My code:
adata = adata[(adata[: , 'A'].X > 0) & (adata[:, 'B'].X > 0), :]
# TypeError: unsupported operand type(s) for &: 'SparseCSRView' and 'SparseCSRView'

However, 
adata = adata[(adata[: , 'A'].X > 0), :]
It works greatly.
Hope to get help, thank you.

**Comment by JBreunig** [comment]
I can confirm that `adata[(adata[: , 'A'].X >1) & (adata[: , 'B'].X > 0),:].shape` and `adata3 = adata[(adata[: , 'A'].X >1) & (adata[: , 'B'].X > 1),:]` work without issues now.  Not sure what changed.
