### ISSUE TITLE
why there is not expression_cutoff in stacked violin plot

### ISSUE THREAD

**Issue by FADHLyemen** [scverse/scanpy#1871]
- [ ] Additional function parameters / changed functionality / changed defaults?
- [ ] New analysis tool: A simple analysis tool you have been using and are missing in `sc.tools`?
- [ ] New plotting function: A kind of plot you would like to seein `sc.pl`?
- [ ] External tools: Do you know an existing package that should go into `sc.external.*`?
- [ ] Other?

...
Hi
I am wondering Why there is not expression_cutoff in stacked violin plot as in the dot plot?

**Comment by ivirshup** [comment]
From the documentation for `dotplot`:

```
expression_cutoff : float, optional (default: 0.0)
    Expression cutoff that is used for binarizing the gene expression and
    determining the fraction of cells expressing given genes. A gene is
    expressed only if the expression value is greater than this threshold.
```

This doesn't really apply to the violin plots since the fraction of cells expressing a gene isn't represented in those plots.

Is there a different kind of expression cutoff you'd like to see?

**Comment by eroell** [comment]
As we haven't heard back after the follow-up we will close the issue for now, hopefully you obtained the expected behaviour in the end :)

Thanks for being a part of our community! :)
