### ISSUE TITLE
problem in latest version of scanpy (bbknn)

### ISSUE THREAD

**Issue by ahmedibatta** [scverse/scanpy#1872]
- I have checked that this issue has not already been reported.
- I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can copy&paste without having any data)

```python
import scanpy as sc
import bbknn
sc.logging.print_header()
adata = sc.read('pancreas.h5ad', backup_url='https://www.dropbox.com/s/qj1jlm9w10wmt0u/pancreas.h5ad?dl=1') 
sc.external.pp.bbknn(adata, batch_key='batch')  #error2
```

```pytb

 tuple' object has no attribute 'tocsr'
```

#### Versions
<bbknn : 1.5.0>
<scanpy:1.7.0>
 umap:  0.1.1
umap-learn:  0.5.1

[Paste the output of scanpy. logging.print_versions() leaving a blank line after the details tag]

</scanpy==1.4.6 anndata==0.7.4 umap==0.5.1 numpy==1.20.3 scipy==1.6.3 pandas==1.2.4 scikit-learn==0.22.2.post1 statsmodels==0.11.1 python-igraph==0.8.2>

**Comment by ivirshup** [comment]
Any idea why `scanpy. logging.print_versions()` is reporting a different version that you've reported above it? 

Could be that there's an issue with this environment. Can you replicate the issue in a fresh conda environment?

**Comment by ivirshup** [comment]
I'm assuming the :+1: means the issue is solved, please re-open if this isn't the case.
