### ISSUE TITLE
error: 'i' format requires -2147483648 <= number <= 2147483647  when  using de.test.wald()

### ISSUE THREAD

**Issue by QianjiangHu** [scverse/scanpy#1874]
Is there anybody meeting the same error with me?
I used de.test.wald() to do differentially expressed genes analysis with totally 47K cells.

### Minimal code sample (that we can copy&paste without having any data)

```python
test_sf = de.test.wald(
    data=adata.layers['counts'],
    formula_loc="~ 1 + disease + size_factors",
    factor_loc_totest="disease",
    as_numeric=['size_factors'],
    gene_names=adata.var_names,
    sample_description=adata.obs
)
```

```pytb
error: 'i' format requires -2147483648 <= number <= 2147483647
```

#### Versions

<scanpy==1.7.1 anndata==0.7.5 umap==0.4.6 numpy==1.19.2 scipy==1.5.2 pandas==1.1.3 scikit-learn==0.24.1 statsmodels==0.12.2 python-igraph==0.8.3 louvain==0.7.0 leidenalg==0.8.3>

**Comment by LuckyMD** [comment]
Hi @QianjiangHu,

It looks like this might be better fitting to the `diffxpy` [repo](https://github.com/theislab/diffxpy). I would imagine if you change your data to be stored not as `float32` but rather `float64`, this might already fix your issue though.

**Comment by QianjiangHu** [comment]
Dear @LuckyMD,
Thank you for your qucik reply. Could you please give me more details? in particular how I can transfer adata from `float32` to `float64`?

**Comment by LuckyMD** [comment]
Check out `adata.X.astype('float64')`. You should be able to determine float64 via that.

**Comment by QianjiangHu** [comment]
Thank you! @LuckyMD

**Comment by brianpenghe** [comment]
I have the same problem when running `sc.pp.regress_out`
Any ideas?
