### ISSUE TITLE
which data  type in adata.X

### ISSUE THREAD

**Issue by FADHLyemen** [scverse/scanpy#1875]
- [ ] Additional function parameters / changed functionality / changed defaults?
- [ ] New analysis tool: A simple analysis tool you have been using and are missing in `sc.tools`?
- [ ] New plotting function: A kind of plot you would like to seein `sc.pl`?
- [ ] External tools: Do you know an existing package that should go into `sc.external.*`?
- [ ] Other?

...
Hi,

In my h5ad object in adata.X, which data I should use for downstream analysis? counts, normalized or scaled one?
Can I have all them in my h5ad object and how to switch between them?
In seurat there is option called active assay to assign.

**Comment by ivirshup** [comment]
You can store different forms of the matrix in `layers` and often choose which one to use with the `layers` argument.

It really depends on the function whether it expects normalized or count data. Most functions should mention it in the documentation if the expect count data.

**Comment by FADHLyemen** [comment]
how to add the raw counts to my h5ad object?
Any idea how to convert the three data slot from Seurat [raw, data, scaled.data] to h5ad layers?

```
SeuratObject@assays$RNA@counts
SeuratObject@assays$RNA@data
SeuratObject@assays$RNA@scale.data
```
