### ISSUE TITLE
Add Cubé Gene Network Discovery To Scanpy Ecosystem

### ISSUE THREAD

**Issue by connerlambden** [scverse/scanpy#1878]
Hi, I would like to request Cubé be added to the Scanpy Ecosystem page (https://scanpy.readthedocs.io/en/stable/ecosystem.html)

Cubé (https://github.com/connerlambden/Cube/) is an intuitive network algorithm that searches for multiplicative combinations of genes that have high/low correlation and are members of a known biological pathway. Given an input gene1, Cubé searches for gene2 and gene3 such that the expression of gene1 ~= gene2 * gene3 only in cells that express all three genes. Let me know if you have any questions.

**Comment by ivirshup** [comment]
We'd be happy to include this! Could you open a PR adding this to the ecosystem?
