### ISSUE TITLE
high variable genes

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/scanpy#188]
Hi,
Scanpy detect high variable genes with normalized (but not logarithmized) data (refer to Clustering 3k PBMCs following a Seurat Tutorial), while Seurat do this by first normalize the raw data, then logarithmize the data and finally detect high variable genes, which one is better ? or both of them works well ?

**Comment by falexwolf** [comment]
Scanpy precisely reproduces Seurat's output as outlined in the first tutorial. You can also feed in logarithmized data by passing the parameter `log=True`.
