### ISSUE TITLE
How to convert  from Seurat  visium  to AnnData?

### ISSUE THREAD

**Issue by hzongyao** [scverse/scanpy#1882]
- [ ] Additional function parameters / changed functionality / changed defaults?
- [ ] New analysis tool: A simple analysis tool you have been using and are missing in `sc.tools`?
- [ ] New plotting function: A kind of plot you would like to seein `sc.pl`?
- [ ] External tools: Do you know an existing package that should go into `sc.external.*`?
- [ ] Other?

...
How to convert  from Seurat  visium  to AnnData?

**Comment by Zethson** [comment]
Please ask usage questions here: https://discourse.scverse.org/
