### ISSUE TITLE
Issue with sc.pl.paga_compare()

### ISSUE THREAD

**Issue by Bio-data-tricks** [scverse/scanpy#1887]
Hello everyone,

I encounter a problem with the sc.pl.paga_compare() function.  I have a very strange PAGA representation with edges that look messy. Do you have any idea about the source of the problem ?

```python
adata = ad.AnnData(DATA, var=GG)
sc.tl.pca(adata, svd_solver='arpack')
sc.pl.pca(adata)
sc.pp.neighbors(adata, n_neighbors= 25)
sc.tl.leiden(adata)
sc.tl.paga(adata, groups='leiden')
sc.pl.paga(adata)
```

![Capture3](https://user-images.githubusercontent.com/25744843/122538688-16d08b80-d027-11eb-9355-c3217e16316d.PNG)

```python
sc.tl.umap(adata, init_pos='paga')
sc.pl.umap(adata, groups='leiden')
sc.pl.paga_compare(adata, basis='umap')
```

![Capture1](https://user-images.githubusercontent.com/25744843/122538500-e852b080-d026-11eb-838e-c7e0e0faae73.PNG)

```python
fig1, ax1 = plt.subplots()
sc.pl.umap(adata, size=40, ax=ax1, show=False)
sc.pl.paga(adata, pos=adata.uns['paga']['pos'], show=False, node_size_scale=10,
           node_size_power=1, ax=ax1, text_kwds={'alpha':0}, threshold = 0)
```

![Capture2](https://user-images.githubusercontent.com/25744843/122538553-f6a0cc80-d026-11eb-88b0-056fcdf2b114.PNG)

 

thanks 

Nicolas

**Comment by ivirshup** [comment]
Thanks for the report. To me, it looks like `sc.pl.paga_compare` is incorrectly mapping positions to clusters, which leads to a jumbled plot.

Reproducing example (from current master):

```python
import scanpy as sc
from matplotlib import pyplot as plt

sc.settings.datasetdir = "/Users/isaac/data/"
sc.set_figure_params()
plt.rcParams["figure.facecolor"] = "white"

adata = sc.datasets.pbmc3k_processed()
sc.tl.paga(adata, groups="louvain")

# Homebrew paga_compare
with plt.rc_context({"figure.figsize": (10, 5)}):
    fig, (ax1, ax2) = plt.subplots(ncols=2)
    sc.pl.paga(adata, ax=ax2, show=False)

    sc.tl.umap(adata, init_pos="paga")  # paga pos only calculated on plotting
    sc.pl.umap(adata, color="louvain", legend_loc="on data", ax=ax1)
```

![image](https://user-images.githubusercontent.com/8238804/123214726-eeef9500-d50a-11eb-8f08-b17cf4ad4e01.png)


```python
sc.pl.paga_compare(adata, basis="umap")
```

![image](https://user-images.githubusercontent.com/8238804/123214756-f7e06680-d50a-11eb-9d0c-4e374af531f6.png)

Some nodes seem to have swapped positions:

* B Cells and CD14+ Monocytes
* NK Cells and CD8 T Cells

When positions are recalculated (to be based on medians in the projection space) their order is in the wrong somehow.
