### ISSUE TITLE
Bug in rank_genes_groups_violin 

### ISSUE THREAD

**Issue by naskomit** [scverse/scanpy#1888]
When the X matrix is not sparse, the `flatten` function is not applied  and the function fails with the error: 
```
ValueError: Data must be 1-dimensional
```

https://github.com/theislab/scanpy/blob/04987bd4290db411873236c9f6c662a0b445b76f/scanpy/plotting/_tools/__init__.py#L910

**Comment by ivirshup** [comment]
Closing as duplicate of #1199

This should be fixed on the `master` branch.
