### ISSUE TITLE
The saving plot had prefix

### ISSUE THREAD

**Issue by honghh2018** [scverse/scanpy#1889]
Hi,
    It still had the prefix in plot even though i set the :
    sc.settings.plot_suffix=""
    sc.settings.plot_prefix=""
 The saving plot name like:
    
![image](https://user-images.githubusercontent.com/41668708/122671142-dbd18200-d1f7-11eb-929b-a4e176010f43.png)
how can i fix it?
Best,
hanhuihong

**Comment by honghh2018** [comment]
Had anyone hear this?

**Comment by ivirshup** [comment]
Closing as duplicate of #1508.

This is the intended current behavior, though we are considering changing it. See previous discussions for more info.

**Comment by ACastanza** [comment]
Please stop forcing plots to have an unwanted prefix.
