### ISSUE TITLE
scipy mann-whitney U update breaks tests

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#1892]
The tests are currently failing as scipy has updated their implementation of Mann-Whitney U tests, which we use as a reference.

We should figure out what changed, and how to proceed (e.g. do we change our function, or pass different parameters to theirs in the test?)

ping: @Koncopd

**Comment by Koncopd** [comment]
Yes, i will check.

**Comment by ivirshup** [comment]
I think I've figured it out. `stats.mannwhitneyu` now returns `nan` when it used to raise a `ValueError`.

**Comment by Koncopd** [comment]
I see that it can process arrays now, i should check if it better to replace the custom implementation with the updated `stats.mannwhitneyu`.

**Comment by ivirshup** [comment]
> see that it can process arrays now, i should check if it better to replace the custom implementation with the updated stats.mannwhitneyu.

It still doesn't work with sparse arrays, and our version on a sparse array was much faster than theirs on a dense. I did not compare speeds for dense v dense.
