### ISSUE TITLE
painless C extensions with CFFI

### ISSUE THREAD

**Issue by flying-sheep** [scverse/scanpy#19]
so idk about you, but i think [CFFI] is pretty painless for interacting with C/C++ code:

* you simply compile a `.so` file, use `ffi.dlopen('….so')`, `ffi.cdef('void myfunc(…)')` and are able to call it from python.
* it works with PyPy
* it can be used with numpy ([example](https://gist.github.com/arjones6/5533938))

we just have to think if we need to pass complex data structures, but i assume a few dense and sparse matrices is all you need. we just have to figure that out beforehand, and how to create a sparse matrix from raw memory (AFAIK everything under the sun supports at least column compressed layout, we might want to switch `csr_matrix` → `csc_matrix`)

[CFFI]: https://cffi.readthedocs.io/en/latest

**Comment by falexwolf** [comment]
Seems cool to me. Let's give this a try as soon as there's a little bit of time.

**Comment by falexwolf** [comment]
As we don't have any extensions anymore we can close this for now. Also, many people start adapting numba. In the context of Scanpy this should usually be enough... let's talk again in case we need it.
