### ISSUE TITLE
What is the scanpy unit test dataset?

### ISSUE THREAD

**Issue by chris-rands** [scverse/scanpy#1908]
https://github.com/theislab/scanpy/tree/master/scanpy/tests/_data/10x_data/3.0.0 - this h5 object is 1107 cells by 507 genes but what is the data? Is it down-sampled pbmc3k or some other dataset? How was it generated?

I'm looking for a tiny h5 object like this for our own unit testing, but want to be clear on the data source, thanks

**Comment by ivirshup** [comment]
The PR which added it was #334, so @qianggong11 (who I believe works for 10X) may be able to tell you more about how it was generated.

**Comment by chris-rands** [comment]
Thanks @ivirshup - would really appreciate any details @qianggong11 or others?
