### ISSUE TITLE
Order clusters in pl.dotplot

### ISSUE THREAD

**Issue by brianpenghe** [scverse/scanpy#1914]
I have been using `sc.pl.dotplot` to summarize marker gene expression patterns. But it seems that this function always sorts the cell clusters in alphabetical order. Is there a way for me to specify the order of cell clusters? I'm using `scanpy 1.5.0`

**Comment by ivirshup** [comment]
You can use the `categories_order` argument, though would have to check which version that was added in.

Are you having issues with newer releases of scanpy?

**Comment by brianpenghe** [comment]
OK Thanks. I was using 1.5.0 which probably didn't have that option.
