### ISSUE TITLE
sc.pl.rank_genes_groups use_raw wrong error raised when use_raw=True

### ISSUE THREAD

**Issue by Bio-MingChen** [scverse/scanpy#1929]
- [√] I have checked that this issue has not already been reported.
- [√] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---
small bug report:
https://github.com/theislab/scanpy/blob/fb9e12f36b5c600913fa6243819d1575906c384e/scanpy/tools/_rank_genes_groups.py
line 538 wrong error raised when `use_raw=True`
```python
if use_raw is None:
        use_raw = adata.raw is not None
elif use_raw is True and adata.raw is not None:
        raise ValueError("Received `use_raw=True`, but `adata.raw` is empty.")
```
Second `not` should be removed ,Corrected codes should be
```python
if use_raw is None:
        use_raw = adata.raw is not None
elif use_raw is True and adata.raw is None:
        raise ValueError("Received `use_raw=True`, but `adata.raw` is empty.")
```
**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Versions
this bug appeard in v1.8.0

<details>

[Paste the output of scanpy.logging.print_versions() leaving a blank line after the details tag]

</details>

**Comment by ivirshup** [comment]
Thanks for the report!
