### ISSUE TITLE
pynndescent 0.5.3 breaking parallel numba stuff

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#1931]
Numba can’t correctly detect when a threading backend is available. This was fine in the past, since `pynndescent`/ `umap` were forcing a `workqueue` backend which is always available.

`pynndescent` 0.5.3 recently came out, and started favoring the `tbb` backend. This is a problem since numba thinks this backend is available on our CI (and on my HPC), but it’s actually not. I also can’t get tbb to even install in a way numba sees in on these systems. If tbb isn’t actually available, but numba detects it we get errors with horrible tracebacks anytime parallelized numba code is used https://github.com/lmcinnes/pynndescent/issues/129. These tracebacks are so horrible they break our CI further https://github.com/pytest-dev/pytest-nunit/issues/47.

So what do we do?

## Possible solutions:

* Pin pynndescent below 0.5.3.

This makes pynndescent a required dependency. We’ve previously avoided this since it would change results for people using `umap<0.4` (e.g. anyone with `scvelo` installed) who did not explicitly install pynndescent. However, given the lack of complaints around umap results changing as dependencies have increased, this may not be so bad.

It would be great if we could constrain the version without having it be a dependency. This would be similar to what's possible with `pip` and [constraints files](https://pip.pypa.io/en/stable/user_guide/#constraints-files), I don't see how one would be able to specify this for a package. I don't think it's possible, but maybe I'm missing something about the version string syntax.

* Make sure the numba threading layer is `“workqueue”` after pynndescent is imported

This is tricky. pynndescent<0.5.3 takes a long time to import, so we don’t want to do this at the top level. So we would need to add a check after everytiem pynndescent could possibly be imported to check that it didn’t set the threading backend to anything else. My understanding of the numba threading system is that once you’ve called for parallel compilation, you’re locked into the threading backend for that session.

* Make sure the threading layer is workqueue after pynndescent is imported, but make pynndescent import fast

A kinda simpler solution would be to require pynndescent 0.5.3, import it at the top level (boosts total import time by about ~0.2 seconds out of 3.3 total), and set the threading layer right there. This also has the advantage of letting users specify the threading layer after import scanpy and not having us interfere.

This also requires that pynndescent is installed, which hits the reproducibility issues again.

**Comment by flying-sheep** [comment]
We probably have two problems:

1. CI doesn’t run
2. Scanpy got harder to use for people.

I think the first [is easy to fix](https://github.com/numba/numba/blob/c13c840a8f1f038c1e78472db472a8f19a0bd564/numba/core/config.py#L309): We just `export NUMBA_THREADING_LAYER=workqueue` in our tests

The second is harder, but first I want to note something:

> This was fine in the past, since pynndescent/ umap were forcing a workqueue backend which is always available.

I wouldn’t call that situation *fine*, doing things at import time or even just requiring a certain value as configurable global state is bad behavior.

This means our solution for the second shouldn’t be that we hardcode a threading layer to use here. We could make it configurable on our end or something, but no import time global state change.

#1933 only fixes CI … also bad issue number, yikes!

**Comment by flying-sheep** [comment]
> Numba can’t correctly detect when a threading backend is available

Is there a numba issue for this?

**Comment by ivirshup** [comment]
> Is there a numba issue for this?

I haven't looked for a specific issue this time. I have seen this discussed in the past (around why umap and pynndescent specify the threading backend at all). Would be a useful reference to have if you find one.

**Comment by ivirshup** [comment]
> I wouldn’t call that situation fine, doing things at import time or even just requiring a certain value as configurable global state is bad behavior.

It was fine in that it made UMAP work more places than it would have otherwise.

> This means our solution for the second shouldn’t be that we hardcode a threading layer to use here. We could make it configurable on our end or something, but no import time global state change.

I don't really want to have to touch it, especially since I believe it's immutable after any parallel code is called – so we can't actually control in. Our hands are a little tied by having a dependency do this. I would like to know why this is still considered necessary for pynndescent.

**Comment by flying-sheep** [comment]
The way pynndescent does it looks simply wrong: They knew that one specific backend caused problems, but instead of changing it only when that backend is set, they do it indiscriminately, which is pretty rude.

I might be missiong something, though.

**Comment by ivirshup** [comment]
> > Numba can’t correctly detect when a threading backend is available
>
> Is there a numba issue for this?

https://github.com/numba/numba/issues/6108, This issue may be specific to `tbb`

**Comment by ivirshup** [comment]
> I might be missiong something, though.

I personally have only had problems with the intel backends on my MacBook. I see that pinning the parallel backend would be a good way to make the code work for more people. Especially if this used to be worse. I think the capabilities of the different threading layers have also been tweaked over time.

**Comment by ivirshup** [comment]
Fixed by reverting the change on pynndescent, so users should just get the new release when they install
