### ISSUE TITLE
Unordered Categoricals can only compare equality or not

### ISSUE THREAD

**Issue by Pawan291** [scverse/scanpy#1932]
- [ ] I have checked that this issue has not already been reported.
- [ ] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

Hello, I have a list of genes in an excel sheet. I selected few genes of interest and made a text document (only the name of the genes). I have successfully uploaded them in scanpy to generate a dot plot from this text document, but I am facing this error Please help me with this issue.

Thank you in advance.

### Minimal code sample (that we can copy&paste without having any data)

```python
sc.pl.dotplot(adata, genes, groupby = "louvain", figsize = (20, 6), dendrogram = True, use_raw= False, dot_max = 1)
```

```pytb
TypeError                                 Traceback (most recent call last)
<ipython-input-17-15b8850a67a5> in <module>
      1 #New dot plot (12 weeks feature genes)
----> 2 sc.pl.dotplot(adata, genes, groupby = "louvain", figsize = (20, 6), dendrogram = True, use_raw= False, dot_max = 1)

c:\users\pawandeep\appdata\local\programs\python\python37\lib\site-packages\scanpy\plotting\_dotplot.py in dotplot(adata, var_names, groupby, use_raw, log, num_categories, expression_cutoff, mean_only_expressed, cmap, dot_max, dot_min, standard_scale, smallest_dot, title, colorbar_title, size_title, figsize, dendrogram, gene_symbols, var_group_positions, var_group_labels, var_group_rotation, layer, swap_axes, dot_color_df, show, save, ax, return_fig, **kwds)
    930         dot_color_df=dot_color_df,
    931         ax=ax,
--> 932         **kwds,
    933     )
    934 

c:\users\pawandeep\appdata\local\programs\python\python37\lib\site-packages\scanpy\plotting\_dotplot.py in __init__(self, adata, var_names, groupby, use_raw, log, num_categories, categories_order, title, figsize, gene_symbols, var_group_positions, var_group_labels, var_group_rotation, layer, expression_cutoff, mean_only_expressed, standard_scale, dot_color_df, dot_size_df, ax, **kwds)
    151         # 1. compute fraction of cells having value > expression_cutoff
    152         # transform obs_tidy into boolean matrix using the expression_cutoff
--> 153         obs_bool = self.obs_tidy > expression_cutoff
    154 
    155         # compute the sum per group which in the boolean matrix this is the number

c:\users\pawandeep\appdata\local\programs\python\python37\lib\site-packages\pandas\core\ops\common.py in new_method(self, other)
     63         other = item_from_zerodim(other)
     64 
---> 65         return method(self, other)
     66 
     67     return new_method

c:\users\pawandeep\appdata\local\programs\python\python37\lib\site-packages\pandas\core\arraylike.py in __gt__(self, other)
     43     @unpack_zerodim_and_defer("__gt__")
     44     def __gt__(self, other):
---> 45         return self._cmp_method(other, operator.gt)
     46 
     47     @unpack_zerodim_and_defer("__ge__")

c:\users\pawandeep\appdata\local\programs\python\python37\lib\site-packages\pandas\core\frame.py in _cmp_method(self, other, op)
   5966 
   5967         # See GH#4537 for discussion of scalar op behavior
-> 5968         new_data = self._dispatch_frame_op(other, op, axis=axis)
   5969         return self._construct_result(new_data)
   5970 

c:\users\pawandeep\appdata\local\programs\python\python37\lib\site-packages\pandas\core\frame.py in _dispatch_frame_op(self, right, func, axis)
   6003         if not is_list_like(right):
   6004             # i.e. scalar, faster than checking np.ndim(right) == 0
-> 6005             bm = self._mgr.apply(array_op, right=right)
   6006             return type(self)(bm)
   6007 

c:\users\pawandeep\appdata\local\programs\python\python37\lib\site-packages\pandas\core\internals\managers.py in apply(self, f, align_keys, ignore_failures, **kwargs)
    423             try:
    424                 if callable(f):
--> 425                     applied = b.apply(f, **kwargs)
    426                 else:
    427                     applied = getattr(b, f)(**kwargs)

c:\users\pawandeep\appdata\local\programs\python\python37\lib\site-packages\pandas\core\internals\blocks.py in apply(self, func, **kwargs)
    376         """
    377         with np.errstate(all="ignore"):
--> 378             result = func(self.values, **kwargs)
    379 
    380         return self._split_op_result(result)

c:\users\pawandeep\appdata\local\programs\python\python37\lib\site-packages\pandas\core\ops\array_ops.py in comparison_op(left, right, op)
    227     if should_extension_dispatch(lvalues, rvalues):
    228         # Call the method on lvalues
--> 229         res_values = op(lvalues, rvalues)
    230 
    231     elif is_scalar(rvalues) and isna(rvalues):

c:\users\pawandeep\appdata\local\programs\python\python37\lib\site-packages\pandas\core\ops\common.py in new_method(self, other)
     63         other = item_from_zerodim(other)
     64 
---> 65         return method(self, other)
     66 
     67     return new_method

c:\users\pawandeep\appdata\local\programs\python\python37\lib\site-packages\pandas\core\arrays\categorical.py in func(self, other)
     75             if opname in ["__lt__", "__gt__", "__le__", "__ge__"]:
     76                 raise TypeError(
---> 77                     "Unordered Categoricals can only compare equality or not"
     78                 )
     79         if isinstance(other, Categorical):

TypeError: Unordered Categoricals can only compare equality or not
```

#### Versions

<details>

[Paste the output of scanpy.logging.print_versions() leaving a blank line after the details tag]

</details>

**Comment by ivirshup** [comment]
Thanks for the report! Could you let us know a little bit about your environment by showing the output of `sc.logging.print_versions()`?

**Comment by Pawan291** [comment]
Hello,
This command (sc.logging.print_versions()) gives me the error pasted below:
AttributeError                            Traceback (most recent call last)
c:\users\pawandeep\appdata\local\programs\python\python37\lib\site-packages\sinfo\main.py in sinfo(na, os, cpu, jupyter, dependencies, std_lib, private, write_req_file, req_file_name, html, excludes)
    194             try:
--> 195                 mod_version = _find_version(mod.__version__)
    196             except AttributeError:

AttributeError: module 'importlib_metadata' has no attribute '__version__'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-19-c71c26e11b3b> in <module>
----> 1 sc.logging.print_versions()

c:\users\pawandeep\appdata\local\programs\python\python37\lib\site-packages\scanpy\logging.py in print_versions(file)
    159     try:
    160         buf = sys.stdout = io.StringIO()
--> 161         sinfo(dependencies=True)
    162     finally:
    163         sys.stdout = stdout

c:\users\pawandeep\appdata\local\programs\python\python37\lib\site-packages\sinfo\main.py in sinfo(na, os, cpu, jupyter, dependencies, std_lib, private, write_req_file, req_file_name, html, excludes)
    196             except AttributeError:
    197                 try:
--> 198                     mod_version = _find_version(mod.version)
    199                 except AttributeError:
    200                     try:

c:\users\pawandeep\appdata\local\programs\python\python37\lib\site-packages\sinfo\main.py in _find_version(mod_version_attr)
     40         return joined_tuple
     41     elif callable(mod_version_attr):
---> 42         return mod_version_attr()
     43     else:
     44         # print(f'Does not support module version of type {type(mod_ver_attr)}')

TypeError: version() missing 1 required positional argument: 'distribution_name'

**Comment by ivirshup** [comment]
Hmm. I don't think I've seen that before.

Could you try this again in a fresh conda environment to make sure the existing conda environment hasn't gotten into a weird state?

**Comment by Pawan291** [comment]
Hello, 
I have run this command again in the fresh conda environment. Again I get the same error as before.

AttributeError                            Traceback (most recent call last)
c:\users\pawandeep\appdata\local\programs\python\python37\lib\site-packages\sinfo\main.py in sinfo(na, os, cpu, jupyter, dependencies, std_lib, private, write_req_file, req_file_name, html, excludes)
    194             try:
--> 195                 mod_version = _find_version(mod.__version__)
    196             except AttributeError:

AttributeError: module 'importlib_metadata' has no attribute '__version__'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-3-c71c26e11b3b> in <module>
----> 1 sc.logging.print_versions()

c:\users\pawandeep\appdata\local\programs\python\python37\lib\site-packages\scanpy\logging.py in print_versions(file)
    159     try:
    160         buf = sys.stdout = io.StringIO()
--> 161         sinfo(dependencies=True)
    162     finally:
    163         sys.stdout = stdout

c:\users\pawandeep\appdata\local\programs\python\python37\lib\site-packages\sinfo\main.py in sinfo(na, os, cpu, jupyter, dependencies, std_lib, private, write_req_file, req_file_name, html, excludes)
    196             except AttributeError:
    197                 try:
--> 198                     mod_version = _find_version(mod.version)
    199                 except AttributeError:
    200                     try:

c:\users\pawandeep\appdata\local\programs\python\python37\lib\site-packages\sinfo\main.py in _find_version(mod_version_attr)
     40         return joined_tuple
     41     elif callable(mod_version_attr):
---> 42         return mod_version_attr()
     43     else:
     44         # print(f'Does not support module version of type {type(mod_ver_attr)}')

TypeError: version() missing 1 required positional argument: 'distribution_name'

**Comment by ivirshup** [comment]
Okay, can you share the contents of the conda environment (e.g. `conda list`)? Could you also share the command you used to create it?

**Comment by eroell** [comment]
As we haven't heard back after the followup we will close the issue for now, hopefully you obtained the expected behaviour in the end :)

However, please don't hesitate to reopen this issue or create a new one if you have any more questions or run into any related problems in the future.

Thanks for being a part of our community! :)
