### ISSUE TITLE
sc.pp.regress_out segmentation fault  Mac OS X 10.13.3

### ISSUE THREAD

**Issue by Jordanpw23** [scverse/scanpy#194]
Anybody experience something similar? 

I'm attempting to regress out cell cycle gene information from a single cell dataset.

```
# 
#  # Part of the error message that probably matters most
# 

Crashed Thread:        0

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000110
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

VM Regions Near 0x110:
--> 
    __TEXT                 00000001039d0000-00000001039d1000 [    4K] r-x/rwx SM=COW  /Library/Frameworks/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS/Python

Application Specific Information:
*** multi-threaded process forked ***
crashed on child side of fork pre-exec

# 
# 
# 
```

Any ideas on what the problem could be?

**Comment by falexwolf** [comment]
Hm, sorry about that. How about trying to pass `n_jobs=1`?

**Comment by Jordanpw23** [comment]
Great, that worked! So, correct me if I'm wrong, by setting n_jobs=1 it forces the computer to handle one task at a time instead of many parallel processes which may have been crashing the program?

**Comment by falexwolf** [comment]
Yes, `n_jobs>2` will be faster as computations are done in parallel. But something in your installation doesn't seem to go well with this.

I now set the default number of jobs to 1, so in the next Scanpy release, you won't have to set it manually anymore.

**Comment by Jordanpw23** [comment]
Ok got it, thanks for the quick and informative response.
