### ISSUE TITLE
sc.pl.umap bug

### ISSUE THREAD

**Issue by hahia** [scverse/scanpy#1954]
hello, there is a bug

![image](https://user-images.githubusercontent.com/49113803/126420393-c1d56228-470a-439e-9b5f-bb1370f1e18b.png)
![image](https://user-images.githubusercontent.com/49113803/126420376-3986f6fd-ae17-4143-9106-5f78dc7f4899.png)

**Comment by HelloWorldLTY** [comment]
Could you please provide more information about his error? How do you create the scanpy tmp?

In addition, the result of sc.tl.umap is stored in the scanpy file as obsm['X_umap']. You can try to display these data.

**Comment by ryrl9703** [comment]
> hello, there is a bug
> 
> ![image](https://user-images.githubusercontent.com/49113803/126420393-c1d56228-470a-439e-9b5f-bb1370f1e18b.png)
> ![image](https://user-images.githubusercontent.com/49113803/126420376-3986f6fd-ae17-4143-9106-5f78dc7f4899.png)

Hello, I have the same problem. Have you solved it? Thank you.

**Comment by hahia** [comment]
> > hello, there is a bug
> > ![image](https://user-images.githubusercontent.com/49113803/126420393-c1d56228-470a-439e-9b5f-bb1370f1e18b.png)
> > ![image](https://user-images.githubusercontent.com/49113803/126420376-3986f6fd-ae17-4143-9106-5f78dc7f4899.png)
> 
> Hello, I have the same problem. Have you solved it? Thank you.

maybe you can try
`adata.obs.subtype = adata.obs.subtype.astype('category')`
then plot the figure

**Comment by eroell** [comment]
Since we haven't heard back after @HelloWorldLTY 's question, we will close the issue for now, hopefully you obtained the expected behaviour in the end :)

However, please don't hesitate to reopen this issue or create a new one if you have any more questions or run into any related problems in the future.

Thanks for being a part of our community! :)
