### ISSUE TITLE
sc.external.pp.scurblet normalization error

### ISSUE THREAD

**Issue by FlMai** [scverse/scanpy#1957]
- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

Hello, according to the documentation, the simulation of doublets with scrublet works best with un-normalized counts. The current wrapper implementation however uses a layer to hold the raw data, which then gets normalized anyway. 

Please have in mind, that this is the first issue I have ever opened. If I made any grievous mistakes please inform me of such. 

---

### Minimal code sample:

```python
import scanpy
adata = scanpy.datasets.pbmc3k()
scanpy.external.pp.scrublet(adata)
```
and around line 177 in scanpy.external.pp.scrublet we need to 'observe' the values:
```python
adata_obs.layers['raw'] = adata_obs.X
print(adata_obs.layers['raw'])
pp.normalize_total(adata_obs)  <--- currently normalizes all layers and X
print(adata_obs.layers['raw'])
```
---
### Impact
The 'raw' layer is later used in line 194 of scanpy.external.pp.scrublet to simulate doublets, however, it doesn't contain raw data anymore.

```python
adata_sim = scrublet_simulate_doublets(
            adata_obs,
            layer='raw',
            sim_doublet_ratio=sim_doublet_ratio,
            synthetic_doublet_umi_subsampling=synthetic_doublet_umi_subsampling,
        )
```

**Comment by pinin4fjords** [comment]
I'll take a look at this to make sure I've not messed up in writing this wrapper (I'm actually doing some more testing myself for production use right now). 

But you should know that what we've done here is mirror some of the internals of scrublet, but using Scanpy functions. Scrublet should be supplied with raw counts, but does do its own normalisations internally before doing the actual doublet prediction, which is what we're doing here.

**Comment by pinin4fjords** [comment]
Ahh, see what you mean though. Think I'd mis-interpreted the [docs](https://scanpy.readthedocs.io/en/stable/generated/scanpy.pp.normalize_total.html), where talks about normalising layers:

```
Layer to normalize instead of X. If None, X is normalized.
```

Implies that .X is the only thing that gets normalised, if you don't specify layers. 

**Edit:** 

Actually this is just due to references I think:

```
# Done as per current code
>>> ad = sc.read("read.h5ad")
>>> ad[1:5,1:5].X.todense()
matrix([[1., 4., 0., 0.],
        [0., 0., 0., 2.],
        [0., 1., 0., 0.],
        [0., 0., 0., 0.]], dtype=float32)
>>> ad.layers['raw'] = ad.X
>>> sc.pp.normalize_total(ad)
>>> ad[1:5,1:5].X.todense()
matrix([[0.07691469, 0.30765876, 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.16940302],
        [0.        , 0.10096962, 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ]], dtype=float32)
>>> ad[1:5,1:5].layers['raw'].todense()
matrix([[0.07691469, 0.30765876, 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.16940302],
        [0.        , 0.10096962, 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ]], dtype=float32)
        
# If we actually copy the matrix
>>> ad = sc.read("read.h5ad")
>>> ad.layers['raw'] = ad.X.copy())
>>> sc.pp.normalize_total(ad)
>>> ad[1:5,1:5].X.todense()
matrix([[0.07691469, 0.30765876, 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.16940302],
        [0.        , 0.10096962, 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ]], dtype=float32)
>>> ad[1:5,1:5].layers['raw'].todense()
matrix([[1., 4., 0., 0.],
        [0., 0., 0., 2.],
        [0., 1., 0., 0.],
        [0., 0., 0., 0.]], dtype=float32)
```

Shall I add the fix as part of what I'm doing in https://github.com/theislab/scanpy/pull/1965 @ivirshup ?
