### ISSUE TITLE
Converting a seurat object to anndata format

### ISSUE THREAD

**Issue by chlee-tabin** [scverse/scanpy#196]
Hi, I left an issue to seurat repository as well, but it might be of interest for scanpy:

https://github.com/satijalab/seurat/issues/604#issue-339640125

In my systems, as long as it has `Seurat` and `scanpy` (or `anndata` to be more specific) installed, the above one-liner command to convert a merged seurat object to anndata fails within the anndata python code (with the index out of range error), in the `convert_dictionary_to_structured_array` module.

I am not sure whether it is an issue with `Seurat` or `anndata`, but leaving here a link as well (actually curious whether the issue reproduces to anyone using the `scanpy`)

**Comment by davidhbrann** [comment]
I just encountered the same issue when trying to convert data that I had merged using `MergeSeurat`.

**Comment by flying-sheep** [comment]
I wrote something that’s able to convert between AnnData and SingleCellExperiment: https://github.com/flying-sheep/anndata2ri/

Maybe that’s helpful?
