### ISSUE TITLE
small spelling mistake

### ISSUE THREAD

**Issue by yotamcons** [scverse/scanpy#1973]
In the file scanpy/_utils/__init__.py on master branch, line 412 says:
"Revieved a view of an AnnData. Making a copy."
probably meaning "received"

**Comment by Zethson** [comment]
Thanks for the heads up! Would you be willing to file a quick pull request?

(Could do it myself, but happy to bring in new contributors)

**Comment by yotamcons** [comment]
Hi,
I got delayed by a few days, and saw you already created and fixed it.
Next time I’ll join :)

Yotam Constantini
Ph.D. Student, Nitzan Lab <https://mornitzan.wixsite.com/nitzan>
Hebrew University of Jerusalem
