### ISSUE TITLE
module 'umap' has no attribute '__version__'

### ISSUE THREAD

**Issue by spoookyghost** [scverse/scanpy#1978]
Hey!

I hope you are doing well.

I run into the error AttributeError: module 'umap' has no attribute '__version__' when running this code:

```
import pandas as pd
#pd.set_option("display.max_columns", None)
import numpy as np
import anndata
import scanpy as sc

%store -r df

adata = anndata.AnnData(df)
sc.pp.neighbors(adata, n_neighbors=10, n_pcs=40)
sc.tl.paga(adata)
sc.pl.paga(adata, plot=False)
sc.tl.umap(adata, init_pos='paga')
```

I am using Python 3.8 on Jupyter Notebooks on Mac M1.

Please find below the error in a more detailed fashion:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-7-7cfb2fb3103e> in <module>
----> 1 sc.tl.umap(adata, init_pos='paga')
      2 sc.pl.umap(adata)

~/opt/anaconda3/lib/python3.8/site-packages/scanpy/tools/_umap.py in umap(adata, min_dist, spread, n_components, maxiter, alpha, gamma, negative_sample_rate, init_pos, random_state, a, b, copy, method, neighbors_key)
    141         import umap
    142 
--> 143     if version.parse(umap.__version__) >= version.parse("0.5.0"):
    144 
    145         def simplicial_set_embedding(*args, **kwargs):

AttributeError: module 'umap' has no attribute '__version__'
```

Would you have any idea on how to solve this? I think it is a package dependency problem.

Thank you in advance for your help!

**Comment by Zethson** [comment]
Hi,

which umap package did you install? Which version is it?
Do you know whether the umap package already has support for Apple M1?

**Comment by LuckyMD** [comment]
This might be a case of a `pip install umap` rather than `pip install umap-learn`

**Comment by Zethson** [comment]
> This might be a case of a `pip install umap` rather than `pip install umap-learn`

Suspecting exactly that :)

**Comment by spoookyghost** [comment]
I uninstalled umap and made sure umap-learn was installed but it did not change anything. 

I would guess that the problem comes from modules dependency as I managed to make it work on pycharm.

**Comment by flying-sheep** [comment]
Why are we using `umap.__version__` instead of `importlib.metadata.version('umap-learn')`?

**Comment by ivirshup** [comment]
@flying-sheep, any idea why `__version__` wouldn't work? Are we sure `importlib.metadata.version('umap-learn')` works when `__version__` doesn't? I'd be worried if they were basing the reported version on different sources.

**Comment by ivirshup** [comment]
@hurleyLi, would you mind opening an issue over on umap that you're unable to get a `__version__` from it? It would be nice to have that fixed/ at least tracked down upstream.

**Comment by Zethson** [comment]
https://github.com/lmcinnes/umap/issues/46

it should already

https://github.com/lmcinnes/umap/blob/master/umap/__init__.py#L39

**Comment by hurleyLi** [comment]
> @hurleyLi, would you mind opening an issue over on umap that you're unable to get a `__version__` from it? It would be nice to have that fixed/ at least tracked down upstream.

Figure it out. In my case it's because I have both `umap` and `umap-learn` installed, see here: https://github.com/theislab/scanpy/issues/2045#issuecomment-963533994
