### ISSUE TITLE
sc.pl.scatter is not working with gene names (or anything in obs_names or var_names)

### ISSUE THREAD

**Issue by gokceneraslan** [scverse/scanpy#198]
`sc.pl.scatter(sc.datasets.paul15(), 'Gata1', 'Tal1')` is raising the following exception:

`x`, `y`, and potential `color` inputs must all come from either `.obs` or `.var`

It's true that genes are not in `obs` or `var`, but rather in `var_names`. So there should be a check for `obs_names` and `var_names` in https://github.com/theislab/scanpy/blob/master/scanpy/plotting/anndata.py#L107 I think.

**Comment by falexwolf** [comment]
Thank you! Is fixed in https://github.com/theislab/scanpy/commit/8c69fd408840a0ca4a7fd49089b92c6c727f021d

Still raises a deprecation via anndata, which is fixed via https://github.com/theislab/anndata/commit/1c052902a98e04502a36ce46a12b22500a785f50

**Comment by gokceneraslan** [comment]
Great!

**Comment by LuckyMD** [comment]
Sorry about that... I seem to have missed the obs_name and var_name checks.
