### ISSUE TITLE
AttributeError: 'str' object has no attribute 'mkdir'

### ISSUE THREAD

**Issue by gmoore5** [scverse/scanpy#1981]
- [ x] I have checked that this issue has not already been reported.
- [ x] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can copy&paste without having any data)

This code worked fine a couple of days ago but now it's not working at all not sure what happened. Figure is still produced just save path is all messed up?

**(1) when I do:** 
sc._settings.ScanpyConfig.figdir = 'path/folder/' 

sc.pl.umap(anndata,
           save = '_test2.png'
          )

I get an AttributeError: 'str' object has no attribute 'mkdir'
 
**(2) when I do:**
sc._settings.ScanpyConfig(figdir = 'path/folder/')

sc.pl.umap(anndata,
           save = '_test2.png'
          )
then nothing happens there is no error and the directory doesn't actually change.

```python
sc._settings.ScanpyConfig.figdir = 'Volumes/G_DRIVE_mobile/Lynch_Lab_Data_Drive/BroadCRC_AUG2020/Tcell_my_clustering_aug14_2021/'

sc.pl.umap(Tgd,
           save = '_test2.png'
          )




```

```pytb
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-fd106b753fe2> in <module>
----> 1 sc.pl.umap(Tgd,
      2            save = '_test2.png'
      3           )

~/opt/anaconda3/lib/python3.8/site-packages/scanpy/plotting/_tools/scatterplots.py in umap(adata, **kwargs)
    657     tl.umap
    658     """
--> 659     return embedding(adata, 'umap', **kwargs)
    660 
    661 

~/opt/anaconda3/lib/python3.8/site-packages/scanpy/plotting/_tools/scatterplots.py in embedding(adata, basis, color, gene_symbols, use_raw, sort_order, edges, edges_width, edges_color, neighbors_key, arrows, arrows_kwds, groups, components, layer, projection, scale_factor, color_map, cmap, palette, na_color, na_in_legend, size, frameon, legend_fontsize, legend_fontweight, legend_loc, legend_fontoutline, vmax, vmin, vcenter, norm, add_outline, outline_width, outline_color, ncols, hspace, wspace, title, show, save, ax, return_fig, **kwargs)
    447         return fig
    448     axs = axs if grid else ax
--> 449     _utils.savefig_or_show(basis, show=show, save=save)
    450     if show is False:
    451         return axs

~/opt/anaconda3/lib/python3.8/site-packages/scanpy/plotting/_utils.py in savefig_or_show(writekey, show, dpi, ext, save)
    310     show = settings.autoshow if show is None else show
    311     if save:
--> 312         savefig(writekey, dpi=dpi, ext=ext)
    313     if show:
    314         pl.show()

~/opt/anaconda3/lib/python3.8/site-packages/scanpy/plotting/_utils.py in savefig(writekey, dpi, ext)
    280         else:
    281             dpi = rcParams['savefig.dpi']
--> 282     settings.figdir.mkdir(parents=True, exist_ok=True)
    283     if ext is None:
    284         ext = settings.file_format_figs

AttributeError: 'str' object has no attribute 'mkdir'
```

#### Versions

scanpy==1.8.1 anndata==0.7.6 umap==0.5.1 numpy==1.18.5 scipy==1.6.2 pandas==1.1.5 scikit-learn==0.24.2 statsmodels==0.12.2 python-igraph==0.9.4 louvain==0.7.0 pynndescent==0.5.2

[Paste the output of scanpy.logging.print_versions() leaving a blank line after the details tag]

WARNING: If you miss a compact list, please try `print_header`!
The `sinfo` package has changed name and is now called `session_info` to become more discoverable and self-explanatory. The `sinfo` PyPI package will be kept around to avoid breaking old installs and you can downgrade to 0.3.2 if you want to use it without seeing this message. For the latest features and bug fixes, please install `session_info` instead. The usage and defaults also changed slightly, so please review the latest README at https://gitlab.com/joelostblom/session_info.
-----
anndata     0.7.6
scanpy      1.8.1
sinfo       0.3.4
-----
PIL                 8.3.1
anyio               NA
appdirs             1.4.4
appnope             0.1.2
attr                21.2.0
babel               2.9.1
backcall            0.2.0
bioservices         1.7.12
bottleneck          1.3.2
brotli              NA
bs4                 4.9.3
certifi             2021.05.30
cffi                1.14.6
chardet             4.0.0
cloudpickle         1.6.0
colorama            0.4.4
colorlog            NA
cycler              0.10.0
cython_runtime      NA
cytoolz             0.11.0
dask                2021.07.2
dateutil            2.8.2
decorator           5.0.9
defusedxml          0.7.1
docutils            0.17.1
easydev             0.11.1
fsspec              2021.07.0
gseapy              0.10.5
h5py                2.10.0
html5lib            1.1
idna                2.10
igraph              0.9.4
ipykernel           5.3.4
ipython_genutils    0.2.0
ipywidgets          7.6.3
jedi                0.17.2
jinja2              2.11.3
joblib              1.0.1
json5               NA
jsonschema          3.2.0
jupyter_server      1.4.1
jupyterlab_server   2.6.1
kiwisolver          1.3.1
leidenalg           0.8.4
llvmlite            0.36.0
louvain             0.7.0
lxml                4.6.3
markupsafe          2.0.1
matplotlib          3.4.2
mpl_toolkits        NA
natsort             7.1.1
nbclassic           NA
nbformat            5.1.3
numba               0.53.1
numexpr             2.7.3
numpy               1.18.5
packaging           21.0
pandas              1.1.5
parso               0.7.0
pexpect             4.8.0
pickleshare         0.7.5
pkg_resources       NA
prometheus_client   NA
prompt_toolkit      3.0.17
psutil              5.8.0
ptyprocess          0.7.0
pvectorc            NA
pycparser           2.20
pygments            2.9.0
pylab               NA
pynndescent         0.5.2
pyparsing           2.4.7
pyrsistent          NA
pytz                2021.1
requests            2.25.1
requests_cache      0.6.4
scipy               1.6.2
seaborn             0.11.1
send2trash          NA
six                 1.16.0
sklearn             0.24.2
sniffio             1.2.0
socks               1.7.1
soupsieve           2.2.1
sphinxcontrib       NA
statsmodels         0.12.2
storemagic          NA
tables              3.6.1
tblib               1.7.0
texttable           1.6.3
tlz                 0.11.0
toolz               0.11.1
tornado             6.1
traitlets           5.0.5
typing_extensions   NA
umap                0.5.1
url_normalize       1.4.3
urllib3             1.26.6
wcwidth             0.2.5
webencodings        0.5.1
wrapt               1.12.1
yaml                5.4.1
zmq                 20.0.0
zope                NA
-----
IPython             7.22.0
jupyter_client      6.1.12
jupyter_core        4.7.1
jupyterlab          3.0.14
notebook            6.4.0
-----
Python 3.8.11 (default, Aug  3 2021, 05:10:14) [Clang 10.0.0 ]
macOS-10.16-x86_64-i386-64bit
12 logical CPU cores, i386
-----
Session information updated at 2021-08-16 12:24

**Comment by xlancelottx** [comment]
Hi [gmoore5](https://github.com/gmoore5),

I assume this might be too late for you, but hopefully it's still useful for someone searching for this error.

I could resolve this by:
- Restarting the kernel
- Setting the directory using `sc.settings.figdir = "path/to/folder/"` (instead of sc._settings.ScanpyConfig.figdir = 'path/to/folder/')

**Comment by xlancelottx** [comment]
Closing for now. Please reopen, if not resolved with the above.
