### ISSUE TITLE
Difference between ‘distances’ and ‘connectivities’ in adata.obsp

### ISSUE THREAD

**Issue by alexmascension** [scverse/scanpy#1984]
I am currently working with `sc.pp.neighbours()`  and when obtaining the `adata.obsp['distances']` and `adata.obsp['connectivities']` matrices I see some differences that I would like to know why do they happen.

For instance, for the pbmc3k dataset, the results I get are:
`object_triku.obsp['distances']`
`<2700x2700 sparse matrix of type '<class 'numpy.float64'>'`
`with 37800 stored elements in Compressed Sparse Row format>`

and

`object_triku.obsp['connectivities']`
`<2700x2700 sparse matrix of type '<class 'numpy.float64'>'`
`with 61672 stored elements in Compressed Sparse Row format>`

Mainly, in distance matrix all elements are zero, except n_neighbors elements that are non zero. In connectivities matrices I see that the elements that are nonzero are in the same positions as the nonzero elements from the distance matrix, although sometimes they are more, sometimes they are fewer.

This is strange to me because there are cases where the elements in the distances are zero, but its connectivity value is 1.

From that point, my question is: which matrix should I value most to get the neighbour graph?

**Comment by redst4r** [comment]
also stumbled across this. I guess the `distances` are strictly the knn distances. I.e if you specify `sc.pp.neighbors(
    adata,  n_neighbors=15)` each row of `adata.obsp['distances']` should have exactly 15 non-zero entries.

`adata.obsp['connectivities']` comes from the UMAP algorithm itself. I can confirm that it has different sparsity structure than the knn-graph though...

Haven't looked at the implementation in detail, but I assume `connectivities` are derived from the locally scaled distance metrics that UMAP builds. Maybe someone with more insight into the details can help; from my basic understanding of UMAP, I don't see why the sparsity pattern would be different from the knn Graph. Maybe some hack to keep the entire graph as one connected component??

**Comment by alexmascension** [comment]
I guess both distance and connectivities matrices are full, and in order to get a sparse matrix, they apply a cutoff. I guess that that cutoff is a hard cutoff on distances, and a softer cutoff on connectivities. From some tests I've done for a particular project, in some datasets there are differences between distances and connectivities, and for others aren't. We'll have to wait to see the answer.

**Comment by Koncopd** [comment]
A short answer is that `distances` are from knn computation and `connectivities` are from a stage of the umap algorithm.
