### ISSUE TITLE
CPUDispatcher error with highly variable genes

### ISSUE THREAD

**Issue by kragrawa** [scverse/scanpy#1995]
- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can copy&paste without having any data)

```python
sc.pp.highly_variable_genes(
    adata,
    n_top_genes=4000,
    # subset=True, # to automatically subset to the 4000 genes
    layer="counts",
    flavor="seurat_v3"
)
```

```pytb
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: expected dtype object, got 'numpy.dtype[float64]'

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
<ipython-input-15-144c5f8e718e> in <module>
      4     # subset=True, # to automatically subset to the 4000 genes
      5     layer="counts",
----> 6     flavor="seurat_v3"
      7 )

~/anaconda3/lib/python3.7/site-packages/scanpy/preprocessing/_highly_variable_genes.py in highly_variable_genes(adata, layer, n_top_genes, min_disp, max_disp, min_mean, max_mean, span, n_bins, flavor, subset, inplace, batch_key, check_values)
    425             span=span,
    426             subset=subset,
--> 427             inplace=inplace,
    428         )
    429 

~/anaconda3/lib/python3.7/site-packages/scanpy/preprocessing/_highly_variable_genes.py in _highly_variable_genes_seurat_v3(adata, layer, n_top_genes, batch_key, check_values, span, subset, inplace)
     65         )
     66 
---> 67     df['means'], df['variances'] = _get_mean_var(X)
     68 
     69     if batch_key is None:

~/anaconda3/lib/python3.7/site-packages/scanpy/preprocessing/_utils.py in _get_mean_var(X, axis)
      6 def _get_mean_var(X, *, axis=0):
      7     if sparse.issparse(X):
----> 8         mean, var = sparse_mean_variance_axis(X, axis=axis)
      9     else:
     10         mean = np.mean(X, axis=axis, dtype=np.float64)

~/anaconda3/lib/python3.7/site-packages/scanpy/preprocessing/_utils.py in sparse_mean_variance_axis(mtx, axis)
     40         )
     41     else:
---> 42         return sparse_mean_var_minor_axis(mtx.data, mtx.indices, *shape, np.float64)
     43 
     44 

SystemError: CPUDispatcher(<function sparse_mean_var_minor_axis at 0x7fcea12550e0>) returned a result with an error set
```

#### Versions

<details>

-----
anndata     0.7.6
scanpy      1.8.1
sinfo       0.3.4
-----
PIL                 6.2.0
absl                NA
attr                19.2.0
backcall            0.1.0
beta_ufunc          NA
binom_ufunc         NA
bottleneck          1.2.1
cffi                1.12.3
cloudpickle         1.2.2
colorama            0.4.1
cycler              0.10.0
cython_runtime      NA
cytoolz             0.10.0
dask                2.5.2
dateutil            2.8.0
decorator           4.4.0
deprecate           0.3.0
fsspec              2021.08.1
google              NA
h5py                2.10.0
ipykernel           5.1.2
ipython_genutils    0.2.0
ipywidgets          7.5.1
jedi                0.15.1
joblib              0.13.2
kiwisolver          1.1.0
llvmlite            0.29.0
matplotlib          3.4.3
more_itertools      NA
mpl_toolkits        NA
natsort             7.0.1
nbinom_ufunc        NA
numba               0.45.1
numexpr             2.7.0
numpy               1.21.2
opt_einsum          v3.3.0
packaging           21.0
pandas              1.3.2
parso               0.5.1
pexpect             4.7.0
pickleshare         0.7.5
pkg_resources       NA
prompt_toolkit      2.0.10
psutil              5.6.3
ptyprocess          0.6.0
pycparser           2.19
pygments            2.10.0
pyparsing           2.4.2
pyro                1.7.0
pytorch_lightning   1.3.8
pytz                2019.3
rich                NA
scipy               1.7.1
scvi                0.13.0
seaborn             0.9.0
setuptools          41.4.0
setuptools_scm      NA
simplejson          3.17.2
six                 1.12.0
sklearn             0.24.2
skmisc              0.1.4
sphinxcontrib       NA
statsmodels         0.10.1
storemagic          NA
tables              3.5.2
tblib               1.4.0
tensorboard         2.6.0
threadpoolctl       2.2.0
toolz               0.10.0
torch               1.9.0
torchmetrics        0.5.1
tornado             6.0.3
tqdm                4.56.0
traitlets           4.3.3
typing_extensions   NA
wcwidth             NA
yaml                5.1.2
zipp                NA
zmq                 18.1.0
-----
IPython             7.8.0
jupyter_client      5.3.3
jupyter_core        4.5.0
jupyterlab          1.1.4
notebook            6.0.1
-----
Python 3.7.4 (default, Aug 13 2019, 15:17:50) [Clang 4.0.1 (tags/RELEASE_401/final)]
Darwin-20.5.0-x86_64-i386-64bit
8 logical CPU cores, i386
-----
Session information updated at 2021-09-08 10:28

</details>

**Comment by Koncopd** [comment]
It seems that there is a problem with numba. Could you try upgrading your numba package?

**Comment by kragrawa** [comment]
That worked, thank you for your help!
