### ISSUE TITLE
sc.pl.umap coustome color and bracket

### ISSUE THREAD

**Issue by jphe** [scverse/scanpy#200]
Hi, 

How can I change the sc.pl.umap color and color bar bracket by myself, by default it is [blue, red], in the middle is white, the white some times is a problem for some genes, as many cells are white which just like no cells on the plot for that cluster.

Thanks,
Jphe

**Comment by falexwolf** [comment]
Yes, sure! Use either the `color_map` parameter in any of [`pl.tsne`](http://scanpy.readthedocs.io/en/latest/api/scanpy.api.pl.tsne.html#scanpy.api.pl.tsne) or globally set the color map [here](http://scanpy.readthedocs.io/en/latest/api/scanpy.api.set_figure_params.html#scanpy.api.set_figure_params).
