### ISSUE TITLE
Dependencies missing in bioconda package

### ISSUE THREAD

**Issue by jfnavarro** [scverse/scanpy#2000]
Hi! I am wondering why `loompy` and `pybiomart` are not in the list of dependencies. As of now 
the package (at least in bioconda) is not fully functional and requieres some extra installation
steps if one wants to use certain functionalities provided.

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

### Minimal code sample (that we can copy&paste without having any data)
```bash
conda install -c bioconda scanpy
````

```python
import scanpy as sc
annot = sc.queries.biomart_annotations("mmusculus", ["ensembl_gene_id", "external_gene_name"])
```
```pytb
 line 108, in biomart_annotations
    return simple_query(org=org, attrs=attrs, host=host, use_cache=use_cache)
  File "/Users/jfnavarro/opt/anaconda3/envs/nf-core/lib/python3.7/site-packages/scanpy/queries/_queries.py", line 64, in simple_query
    "This method requires the `pybiomart` module to be installed."
ImportError: This method requires the `pybiomart` module to be installed.
```

```python
import scanpy as sc
adata = sc.datasets.pbmc3k()
adata.write_loom('dummy.loom')
```
```pytb
write_loom(filename, self, write_obsm_varm=write_obsm_varm)
  File "/Users/jfnavarro/opt/anaconda3/envs/nf-core/lib/python3.7/site-packages/anndata/_io/write.py", line 112, in write_loom
    from loompy import create
ModuleNotFoundError: No module named 'loompy'
```

#### Versions

<details>

WARNING: If you miss a compact list, please try `print_header`!
-----
anndata     0.7.6
scanpy      1.7.2
sinfo       0.3.1
-----
PIL                 8.3.1
anndata             0.7.6
beta_ufunc          NA
binom_ufunc         NA
bottleneck          1.3.2
cffi                1.14.6
colorama            0.4.4
cycler              0.10.0
cython_runtime      NA
dateutil            2.8.2
dunamai             1.6.0
get_version         3.5
h5py                2.10.0
joblib              1.0.1
kiwisolver          1.3.1
legacy_api_wrap     0.0.0
llvmlite            0.36.0
matplotlib          3.4.2
mkl                 2.4.0
mpl_toolkits        NA
natsort             7.1.1
nbinom_ufunc        NA
numba               0.53.1
numexpr             2.7.3
numpy               1.20.3
packaging           21.0
pandas              1.3.2
pkg_resources       NA
pyparsing           2.4.7
pytz                2021.1
scanpy              1.7.2
scipy               1.7.1
setuptools_scm      NA
sinfo               0.3.1
six                 1.16.0
sklearn             0.24.2
sphinxcontrib       NA
tables              3.6.1
tqdm                4.62.1
typing_extensions   NA
yaml                5.4.1
zipp                NA
-----
Python 3.7.11 (default, Jul 27 2021, 07:03:16) [Clang 10.0.0 ]
Darwin-20.4.0-x86_64-i386-64bit
12 logical CPU cores, i386
-----
Session information updated at 2021-09-15 10:41

</details>

**Comment by Zethson** [comment]
Dear @jfnavarro 

we recommend that you install the latest scanpy version from conda-forge. 
We are currently updating our installation instructions https://github.com/theislab/scanpy/pull/1974

**Comment by jfnavarro** [comment]
Hi @Zethson! Thanks for your reply. However, I get the same errors when pulling it from conda-forge.

**Comment by Zethson** [comment]
CC @flying-sheep

**Comment by ivirshup** [comment]
Those packages are optional dependencies, and also aren't installed with `pip install scanpy`. You'll need to specify those separately if you'd like to use the features that require them.
