### ISSUE TITLE
Increase pinned version of UMAP

### ISSUE THREAD

**Issue by Zethson** [scverse/scanpy#2012]
Recent discussions on speed demonstrated that UMAP >= 0.5 implementations increase the speed.
Should we increase the minimal version? https://github.com/theislab/scanpy/blob/master/pyproject.toml#L63

CC @le-ander

**Comment by ivirshup** [comment]
We should.

We also have code dating back to handling umap 0.3, which we should remove. It may take a little bit of an overhaul of `Neighbors`, but that's definitely worth doing. Could also open up the possibility of using different libraries for KNN construction.
