### ISSUE TITLE
Cluster No. ordering

### ISSUE THREAD

**Issue by brianpenghe** [scverse/scanpy#2016]
Currently, it seems that Scanpy is ordering clusters based on cluster size, which isn't informative to a biologist.
Is it possible to order clusters based on PAGA or other types of relatedness so that Cluster 0 and Cluster 1 at least belong to the same or adjacent lineages?

I know ArchR package already achieves that.

Thanks!

**Comment by ivirshup** [comment]
I'm not sure it makes sense for us do any additional processing on top of the clustering, since that starts to make assumptions about the data and adds complexity. I'd say the current approach is more "the way names are assigned to clusters is undefined".

What if it was just easier for you to relabel the clusters manually?

**Comment by brianpenghe** [comment]
Relabeling the clusters is doable but ruins the automatic nature of it. 

Assigning names is a different task since in the end we are going to give clusters names for cell types or cell states. But numbering the clusters can be a little smarter since we care more about the cluster relationships than cluster sizes. 

Current numbering system always names the largest cluster '0' and the second largest '1'. But if '0' and '1' are actually related cell types/states that would be very useful, just like what ArchR did.

**Comment by ivirshup** [comment]
Do you know how exactly ArchR does it? I'm dubious there's a foolproof way to consider cell states as related.

I'm also wondering if this is more appropriate as part of PAGA. Naively, I'd image you'd do this with a postorder traversal on a minimum spanning tree of the PAGA graph.

**Comment by brianpenghe** [comment]
Yes I think traversing a minimum spanning tree is good enough since you can never perfectly order cell states in one dimension while capturing all the key features.
ArchR's code to do clustering (addClusters) is here:
https://github.com/GreenleafLab/ArchR/blob/master/R/Clustering.R

What do you think?

**Comment by ivirshup** [comment]
[Here are the specific lines for their cluster ordering](https://github.com/GreenleafLab/ArchR/blob/6765ad962d4d8dcb292a326071c9b5c30c25918e/R/Clustering.R#L368-L383). They do a hierarchical clustering on the mean position of each cluster in the reduced dimensional space. We don't necessarily have access to that space (which may not even exist, e.g. BBKNN graph) at clustering time so we can't use this exact method.

### Current thoughts

My preferences in APIs lean towards modularity and shallowness. I like that the `leiden` function pretty much only computes `leiden` clusters, nothing else. I don't love the idea of adding complexity or computation on top of that. I also think "gives better label orderings" is a vague target which is hard to have meaningful tests for, so can be difficult to support.

I think this would be a little convenient, but I don't see it being very convenient. I would like to hear if other people would really like this feature. At the moment, I don't think it's utility outweighs it's downsides to me.

What I would be more for is some sort of `relabel_clusterings` utility function, which just does the relabelling and could have multiple ways of doing so.

**Comment by brianpenghe** [comment]
I see. Thanks for your reply.
I think I can try to use the dendrogram that Scanpy calculates to order the clusters.
Do you have any tips on how to convert the dendrogram linear order into a list?
That may be a quick fix to me!

Cheers

**Comment by amitlakhanpal** [comment]
Hi @brianpenghe 
I've been fiddling with this a little bit and this may be helpful for your request if you haven't come across it already, there is a 'categories_ordered' field in the dendrogram information that you can access as 
adata.uns[DENDROGRAM_NAME]['categories_ordered']
which I think gives what you would want

**Comment by brianpenghe** [comment]
Thanks for your idea. I can't find `adata.uns[DENDROGRAM_NAME]['categories_ordered']` but `adata.uns[f'dendrogram_celltype']['dendrogram_info']['ivl']` worked in a similar way.
