### ISSUE TITLE
KeyError when plotting gene expression 

### ISSUE THREAD

**Issue by DrLucyMac** [scverse/scanpy#2018]
Hello, 

Whenever I try to plot gene expression I get the following KeyError, regardless of the gene/plotting function. I have confirmed that all genes I have tried do exist in adata.var_names. Id like to highlight that my adata object was created from h5ad converted from seurat. How can I check the keys? 

Thank you!

Lucy

---

```python
sc.pl.draw_graph(myeloid, color=['SPP1'])
```

```pytb
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/software/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2645             try:
-> 2646                 return self._engine.get_loc(key)
   2647             except KeyError:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'SPP1'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-94-440b32bde3cc> in <module>()
----> 1 sc.pl.draw_graph(myeloid, color=['SPP1'])

/software/anaconda3/lib/python3.6/site-packages/scanpy/plotting/_tools/scatterplots.py in draw_graph(adata, layout, **kwargs)
    701         )
    702 
--> 703     return embedding(adata, basis, **kwargs)
    704 
    705 

/software/anaconda3/lib/python3.6/site-packages/scanpy/plotting/_tools/scatterplots.py in embedding(adata, basis, color, gene_symbols, use_raw, sort_order, edges, edges_width, edges_color, neighbors_key, arrows, arrows_kwds, groups, components, layer, projection, img_key, crop_coord, alpha_img, bw, library_id, color_map, palette, size, frameon, legend_fontsize, legend_fontweight, legend_loc, legend_fontoutline, vmax, vmin, add_outline, outline_width, outline_color, ncols, hspace, wspace, title, show, save, ax, return_fig, **kwargs)
    233             palette=palette,
    234             use_raw=use_raw,
--> 235             gene_symbols=gene_symbols,
    236         )
    237 

/software/anaconda3/lib/python3.6/site-packages/scanpy/plotting/_tools/scatterplots.py in _get_color_values(adata, value_to_plot, groups, palette, use_raw, gene_symbols, layer)
   1035         ]  # TODO: Throw helpful error if this doesn't work
   1036     if use_raw and value_to_plot not in adata.obs.columns:
-> 1037         values = adata.raw.obs_vector(value_to_plot)
   1038     else:
   1039         values = adata.obs_vector(value_to_plot, layer=layer)

/software/anaconda3/lib/python3.6/site-packages/anndata/_core/raw.py in obs_vector(self, k)
    168     def obs_vector(self, k: str) -> np.ndarray:
    169         # TODO decorator to copy AnnData.obs_vector docstring
--> 170         idx = self._normalize_indices((slice(None), k))
    171         a = self.X[idx]
    172         if issparse(a):

/software/anaconda3/lib/python3.6/site-packages/anndata/_core/raw.py in _normalize_indices(self, packed_index)
    159         obs, var = unpack_index(packed_index)
    160         obs = _normalize_index(obs, self._adata.obs_names)
--> 161         var = _normalize_index(var, self.var_names)
    162         return obs, var
    163 

/software/anaconda3/lib/python3.6/site-packages/anndata/_core/index.py in _normalize_index(indexer, index)
     72         return indexer
     73     elif isinstance(indexer, str):
---> 74         return index.get_loc(indexer)  # int
     75     elif isinstance(indexer, (Sequence, np.ndarray, pd.Index, spmatrix, np.matrix)):
     76         if hasattr(indexer, "shape") and (

/software/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2646                 return self._engine.get_loc(key)
   2647             except KeyError:
-> 2648                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   2649         indexer = self.get_indexer([key], method=method, tolerance=tolerance)
   2650         if indexer.ndim > 1 or indexer.size > 1:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'SPP1'


```

#### Versions

<details>

-----
anndata     0.7.6
scanpy      1.7.2
sinfo       0.3.4
-----
PIL                 8.4.0
backcall            0.1.0
bottleneck          1.2.1
cffi                1.11.5
cloudpickle         0.5.3
colorama            0.3.9
cycler              0.10.0
cython_runtime      NA
cytoolz             0.9.0.1
dask                0.17.5
dateutil            2.7.3
decorator           4.3.0
fa2                 NA
flaskext            NA
get_version         2.1
google              NA
h5py                2.10.0
igraph              0.9.7
ipykernel           4.8.2
ipython_genutils    0.2.0
ipywidgets          7.2.1
jedi                0.12.0
joblib              0.13.2
kiwisolver          1.0.1
legacy_api_wrap     1.2
leidenalg           0.8.8
llvmlite            0.34.0
louvain             0.6.1
lxml                NA
matplotlib          3.3.4
mpl_toolkits        NA
natsort             6.0.0
networkx            2.5.1
numba               0.51.2
numexpr             2.6.5
numpy               1.19.5
packaging           21.0
pandas              1.1.5
parso               0.2.0
pexpect             4.5.0
pickleshare         0.7.4
pkg_resources       NA
prompt_toolkit      1.0.15
psutil              5.4.5
ptyprocess          0.5.2
pycparser           2.18
pygments            2.2.0
pynndescent         0.5.0
pyparsing           2.2.0
pytz                2018.4
ruamel              NA
scipy               1.4.1
scvelo              0.2.4
setuptools_scm      NA
simplegeneric       NA
six                 1.11.0
sklearn             0.24.2
sphinxcontrib       NA
storemagic          NA
tables              3.4.3
texttable           1.6.2
toolz               0.9.0
tornado             5.0.2
tqdm                4.32.1
traitlets           4.3.2
typing_extensions   NA
umap                0.4.6
wcwidth             NA
yaml                5.1.2
zipp                NA
zmq                 17.0.0
-----
IPython             6.4.0
jupyter_client      5.2.3
jupyter_core        4.4.0
jupyterlab          0.32.1
notebook            5.5.0
-----
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) [GCC 7.2.0]
Linux-3.10.0-957.21.3.el7.x86_64-x86_64-with-centos-7.6.1810-Core
120 logical CPU cores, x86_64
-----

</details>

**Comment by ivirshup** [comment]
Is "SPP1" in your `adata.raw.var_names`? E.g. does `"SPP1" in myeloid.raw.var_names` return `True`?

If not, is it in your `adata.var_names`?

**Comment by DrLucyMac** [comment]
It is in adata.var_names but not adata.raw.var_names

**Comment by ivirshup** [comment]
Ah, this is a little bit of an API backwards compatibility gotcha, from when we assumed if `raw` was present `adata.X` was centered and scaled. If `raw` is present plotting functions look there by default.

Pass `use_raw=False`.

**Comment by jliu678** [comment]
very helpful answer thanks
