### ISSUE TITLE
sc.pl creates "Do not localize" message

### ISSUE THREAD

**Issue by jayypaul** [scverse/scanpy#202]
Let's say I start a new session and generate a plot, then save it. All is fine.

When I plot anything after the first save, a "Do not localize" message pops up and so does the previous "save as" window. The do not localize message window cannot be exited out of, and so I drag them to the upper right corner of the screen so they're out of the way. Then I exit out of the previous save as window, which by the way if you try to use it to save the current figure, it won't work. So I exit out of that window. But you can click the save button on the figure itself, then you can save.

As I continue to plot and save figures, the do not localize windows pile up, and the chain of previous save as windows continues to grow. If you can follow my explanation, you can probably get the sense of how bothersome this can be. I have to go through the process of dragging the accumulating do not localize windows to the corner, and exiting out of the accumulating save as windows as I continue to generate and save figures.

Has there been any similar experiences and if so how do I get rid of this situation?

**Comment by falexwolf** [comment]
Hm, I really don't know what you're talking about... 🙂 Are you using an ordinary Python shell? If yes, use a jupyter notebook if you want interactive plotting. If you want to stick with a Python script, turn off showing figures interacticely (`sc.settings.autoshow = False`) and save them instead (`sc.settings.autosave = True`).

**Comment by jayypaul** [comment]
Yeah I'm just using the shell. Jupyter notebook is probably the way to go. Thanks for the advice.
