### ISSUE TITLE
umap embedding not working as expected in umap-learn 0.5.2

### ISSUE THREAD

**Issue by cornhundred** [scverse/scanpy#2026]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

### Minimal code sample 

The UMAP embeddings appear incorrect using the 0.5.2 version of umap-learn Scanpy [pbmc3k tutorial example](https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html). These results can be reproduced using the Google Colab links. 

* colab notebook [scanpy_pbmc3k_umap-learn_0.5.1.ipynb](https://colab.research.google.com/drive/1kAPRClaUWoZdao458Q_6fwnxQaQ4xwsP?usp=sharing)

![Screen Shot 2021-10-29 at 4 25 46 PM](https://user-images.githubusercontent.com/8352840/139497658-454d28e8-1988-4e1e-8014-2d234348d271.png)

* colab notebook [scanpy_pbmc3k_umap-learn_0.5.2.ipynb](https://colab.research.google.com/drive/1_J5Kzx-Qja_rIvCW3ziAamgdagq2x0op?usp=sharing)
![Screen Shot 2021-10-29 at 4 25 52 PM](https://user-images.githubusercontent.com/8352840/139497674-93d80465-5c2c-4865-a0d3-04dde2a76b17.png)

```python
# we copied the code from the pbmc3k example: https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html
```

#### Versions

Scanpy 1.8.1

The issue seems to be the new version of umap-learn 0.5.2

We also raised this issue on the umap-learn repo here  https://github.com/lmcinnes/umap/issues/798

**Comment by ivirshup** [comment]
@Zethson re your comment (https://github.com/theislab/scanpy/pull/2028#issuecomment-956365435), what were you thinking for a patch?

Disallowing `0.5.2`? Or make a fix for that version?

**Comment by Zethson** [comment]
> @Zethson re your comment ([#2028 (comment)](https://github.com/theislab/scanpy/pull/2028#issuecomment-956365435)), what were you thinking for a patch?
> 
> Disallowing `0.5.2`? Or make a fix for that version?

Well, I'd accept the [PR](https://github.com/theislab/scanpy/pull/2028) that fixes this. It's targeted enough and I am happy to see people contributing.

**Comment by ivirshup** [comment]
Oh, whoops, thought that was a PR on umap at first glance. Sounds good.
