### ISSUE TITLE
pca() and tsne() different output when run more than once

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/scanpy#203]
Hi,

In scanpy 1.1, sc.pl.pca() and sc.tl.tsne() output changes (but still very similar) if they are executed more than once over an object. I have already set random_state value. I've tested that behavior in different installations in different operating systems. Is there a reason for that? I find that behavior baffling and I don't know which output should be trusted: the first time the functions are run or the following?

Thanks for your time.

**Comment by falexwolf** [comment]
Hm, strange. The others in the lab and I never experienced that behaviour... Without further details, I can't do anything...

**Comment by wangjiawen2013** [comment]
@falexwolf 
Is it caused by the parametter svd_solver ? Acorrding to the tl.pca() document ( svd_solver : str, optional (default: ‘auto’)SVD solver to use. Either ‘arpack’ for the ARPACK wrapper in SciPy (scipy.sparse.linalg.svds), or ‘randomized’ for the randomized algorithm due to Halko (2009). “auto” chooses automatically depending on the size of the problem.
The 'randomized' algorithm will give different result each time.
