### ISSUE TITLE
read_loom on HCA loom files returns error

### ISSUE THREAD

**Issue by ACastanza** [scverse/scanpy#2040]
- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can copy&paste without having any data)

Download HCA loom dataset (tested with data from: https://data.humancellatlas.org/explore/projects/0c3b7785-f74d-4091-8616-a68757e4c2a8/m/project-matrices)

```python
import scanpy
loomdata = scanpy.read_loom("path/bone-marrow-myeloma-human-hematopoeitic-10XV2.loom")

#I also tried:
loomdata=scanpy.read_loom("path/bone-marrow-myeloma-human-hematopoeitic-10XV2.loom", obs_names='CellID', var_names='ensembl_ids'

```

```pytb
scanpy.read_loom("/Users/acastanza/Downloads/bone-marrow-myeloma-human-hematopoeitic-10XV2.loom")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/lib/python3.8/site-packages/anndata/compat/__init__.py", line 253, in inner_f
    return f(*args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/anndata/_io/read.py", line 261, in read_loom
    with connect(filename, "r", **kwargs) as lc:
  File "/usr/local/anaconda3/lib/python3.8/site-packages/loompy/loompy.py", line 1140, in connect
    return LoomConnection(filename, mode, validate=validate, spec_version=spec_version)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/loompy/loompy.py", line 84, in __init__
    raise ValueError("\n".join(lv.errors) + f"\n{filename} does not appead to be a valid Loom file according to Loom spec version '{spec_version}'")
ValueError: Row attribute 'Gene' dtype object is not allowed
Row attribute 'ensembl_ids' dtype object is not allowed
Row attribute 'gene_names' dtype object is not allowed
Column attribute 'CellID' dtype object is not allowed
Column attribute 'cell_names' dtype object is not allowed
Column attribute 'input_id' dtype object is not allowed
For help, see http://linnarssonlab.org/loompy/format/
/Users/acastanza/Downloads/bone-marrow-myeloma-human-hematopoeitic-10XV2.loom does not appead to be a valid Loom file according to Loom spec version '2.0.1'
```

#### Versions

<details>

scanpy==1.8.1 anndata==0.7.6.dev49+g19ba44d umap==0.5.1 numpy==1.19.2 scipy==1.7.1 pandas==1.2.4 scikit-learn==0.24.2 statsmodels==0.11.1 python-igraph==0.9.6 pynndescent==0.5.4

</details>

**Comment by ivirshup** [comment]
We call out to `loompy` to read in loom files. I also am having trouble replicating using `loompy 3.0.6`. Could you try updating your loompy install and seeing if the problem persists?

**Comment by ACastanza** [comment]
Ah! That was it. I was stuck on loompy 2.0.16 for some reason.
Updating to loompy v3.0.6 resolved the issue. Thanks!
