### ISSUE TITLE
Adding use_raw=False create errors

### ISSUE THREAD

**Issue by hyjforesight** [scverse/scanpy#2046]
Hello Scanpy,
When I add parameter use_raw=False into sc.tl.rank_genes_groups() and sc.pl.rank_genes_groups_violin(), it generates errors as below.
![image](https://user-images.githubusercontent.com/75048821/140627341-b0c08fbd-53b1-4ed8-b12d-9be71a65a6a5.png)
![image](https://user-images.githubusercontent.com/75048821/140627351-09708fcd-39ea-4602-8609-eca85ea6b843.png)
![image](https://user-images.githubusercontent.com/75048821/140627356-7faf0462-c852-436e-b69d-22f337dabae6.png)

Another question is that, we shouldn't use the adata.raw for plotting becase the adata.raw doesn't regress out the mito gene expressions, should we?

Thanks!
Best,
YJ

**Comment by ivirshup** [comment]
I'm having trouble reproducing this error. Could you share what versions you have installed (ideally also try updating these to the latest releases) and see if you can replicate the issue on one of the datasets in `sc.datasets`?

I think you should probably do differential expression plots using the same values you used to compute the differential expression in most cases.

**Comment by hyjforesight** [comment]
@ivirshup 
Hello ivirshup, these error comes from the below environments. When I upgrade to py3.8 and use scanpy 1.8.2, everything works well. Thanks a lot!

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Yuanjian/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Yuanjian/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Package | Version
-- | --
Anaconda | 2.1.0
Python | 3.6.13
anndata | 0.7.6
anyio | 2.2.0
argon2-cffi | 20.1.0
async-generator | 1.1
attrs | 21.2.0
Babel | 2.9.1
backcall | 0.2.0
bleach | 4.0.0
brotlipy | 0.7.0
cached-property | 1.5.2
certifi | 2021.5.30
cffi | 1.14.6
charset-normalizer | 2.0.4
colorama | 0.4.4
contextvars | 2.4
**cryptography | 35.0.0**
cycler | 0.11.0
dataclasses | 0.8
decorator | 4.4.2
defusedxml | 0.7.1
entrypoints | 0.3
get-version | 2.1
h5py | 3.1.0
idna | 3.2
igraph | 0.9.8
immutables | 0.16
importlib-metadata | 4.8.1
ipykernel | 5.3.4
ipython | 7.16.1
ipython-genutils | 0.2.0
jedi | 0.17.0
**Jinja2 | 3.0.2**
joblib | 1.1.0
json5 | 0.9.6
jsonschema | 3.2.0
jupyter-client | 7.0.1
jupyter-core | 4.8.1
jupyter-server | 1.4.1
**jupyterlab | 3.2.1**
jupyterlab-pygments | 0.1.2
jupyterlab-server | 2.8.2
kiwisolver | 1.3.1
legacy-api-wrap | 1.2
leidenalg | 0.8.8
llvmlite | 0.36.0
MarkupSafe | 2.0.1
matplotlib | 3.3.4
mistune | 0.8.4
**natsort | 8.0.0**
nbclassic | 0.2.6
nbclient | 0.5.3
nbconvert | 6.0.7
nbformat | 5.1.3
nest-asyncio | 1.5.1
networkx | 2.5.1
notebook | 6.4.3
numba | 0.53.1
numexpr | 2.7.3
numpy | 1.19.5
packaging | 21
pandas | 1.1.5
pandocfilters | 1.4.3
parso | 0.8.2
patsy | 0.5.2
pickleshare | 0.7.5
Pillow | 8.4.0
pip | 21.2.2
prometheus-client | 0.11.0
prompt-toolkit | 3.0.20
pycparser | 2.2
Pygments | 2.10.0
pynndescent | 0.5.5
pyOpenSSL | 21.0.0
**pyparsing | 3.0.4**
pyrsistent | 0.17.3
PySocks | 1.7.1
python-dateutil | 2.8.2
python-igraph | 0.9.8
pytz | 2021.3
pywin32 | 228
pywinpty | 0.5.7
pyzmq | 22.2.1
requests | 2.26.0
scanpy | 1.7.2
scikit-learn | 0.24.2
scipy | 1.5.4
seaborn | 0.11.2
Send2Trash | 1.8.0
setuptools | 58.0.4
sinfo | 0.3.4
six | 1.16.0
sniffio | 1.2.0
statsmodels | 0.12.2
stdlib-list | 0.8.0
tables | 3.6.1
terminado | 0.9.4
testpath | 0.5.0
texttable | 1.6.4
threadpoolctl | 3.0.0
tornado | 6.1
tqdm | 4.62.3
traitlets | 4.3.3
typing-extensions | 3.10.0.2
**umap-learn | 0.5.2**
urllib3 | 1.26.7
wcwidth | 0.2.5
webencodings | 0.5.1
wheel | 0.37.0
win-inet-pton | 1.1.0
wincertstore | 0.2
xlrd | 1.2.0
zipp | 3.6.0



</body>

</html>

**Comment by ivirshup** [comment]
Thanks for letting me know!

If it's working in the newest version, there's not much for us to fix. Please let us know if you run into the error on the latest release!

**Comment by RinconFer** [comment]
I am using the latest version of scanpy, and this issue persists. My current processing of the anndata object is as follows:

```py
sc.pp.filter_cells(adata, min_genes=200)
sc.pp.filter_genes(adata, min_cells=3)
sc.pl.highest_expr_genes(adata, n_top=20, )

adata.raw = adata.copy()
sc.pp.normalize_total(adata, target_sum=1e4)
sc.pp.log1p(adata)

sc.pp.highly_variable_genes(adata, min_mean=0.0125, max_mean=6, min_disp=0.10)
sc.pl.highly_variable_genes(adata)

sc.pp.regress_out(adata, ['n_counts', 'percent_mito', 'percent_ribo', 'n_genes'], n_jobs=56)
sc.pp.scale(adata)

sc.tl.pca(adata, svd_solver='arpack', n_comps=100)
sc.pl.pca_variance_ratio(adata, log=True, n_pcs = 100)

sc.pp.neighbors(adata)
sc.tl.umap(adata)
sc.tl.leiden(adata)

sc.tl.rank_genes_groups(adata, 'leiden', method='wilcoxon', use_raw=False)
```

I have tried with and without "sc.pp.scale(adata)", which changes the umap embedding, but in both cases, the use of "use_raw=False" doesn't work. I mean, it generates the markers, but since it is working on a 0-centered matrix, there are no logFoldChange results (all values in the column are NaN). I have also tried to logarithmize the data just before analyzing the markers with "sc.pp.log1p(adata)", but that throws an error now that it is trying to work on the scaled data too. How should I preprocess the data if I want to do the DEG analysis with "use_raw=False"? Should I save the logaritmized counts in a different slot within the anndata object and force sc.tl.rank_genes_groups to work on that somehow?

**Comment by flying-sheep** [comment]
Hi, in order to help you, we need both the full list of versions you use and a traceback. The new issue form has help on how to fill both in!
