### ISSUE TITLE
standard_scale done twice if not None

### ISSUE THREAD

**Issue by zhangguy** [scverse/scanpy#2054]
Hi,

I was going over the dotplot code, and found standard_scale might have been done twice?

scanpy/plotting/_dotplot.py:

line 181-187
```
            if standard_scale == 'group':
                dot_color_df = dot_color_df.sub(dot_color_df.min(1), axis=0)
                dot_color_df = dot_color_df.div(dot_color_df.max(1), axis=0).fillna(0)
            elif standard_scale == 'var':
                dot_color_df -= dot_color_df.min(0)
                dot_color_df = (dot_color_df / dot_color_df.max(0)).fillna(0)
            elif standard_scale is None:
```

again in line 655-662:
```
        if standard_scale == 'group':
            dot_color = dot_color.sub(dot_color.min(1), axis=0)
            dot_color = dot_color.div(dot_color.max(1), axis=0).fillna(0)
        elif standard_scale == 'var':
            dot_color -= dot_color.min(0)
            dot_color = (dot_color / dot_color.max(0)).fillna(0)
        elif standard_scale is None:
            pass
```

**Comment by ivirshup** [comment]
Thanks for the report.

I don't think both of those will be called. As far as I can tell, `standard_scale` passed to `DotPlot.__init__` would not be passed to the `_dotplot` method, unless the user explicitly called it. I have confirmed this with some `print` statement debugging (`print(standard_scale)` at line 654 prints `None`).

Also, wouldn't the values be the same whether that normalization was applied once or twice?

**Comment by zhangguy** [comment]
> Thanks for the report.
> 
> I don't think both of those will be called. As far as I can tell, `standard_scale` passed to `DotPlot.__init__` would not be passed to the `_dotplot` method, unless the user explicitly called it. I have confirmed this with some `print` statement debugging (`print(standard_scale)` at line 654 prints `None`).
> 
> Also, wouldn't the values be the same whether that normalization was applied once or twice?

Thanks! Indeed the one in _dotplot is never run by _mainplot.
