### ISSUE TITLE
leiden UMAP becomes grey and cannot be changed back

### ISSUE THREAD

**Issue by hyjforesight** [scverse/scanpy#2058]
- [ ✔] I have checked that this issue has not already been reported.
- [✔ ] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can copy&paste without having any data)

```python 3.8
# Your code here
```sc.tl.pca(adata, svd_solver='arpack')
sc.pp.neighbors(adata, n_pcs=50, knn=True)
sc.tl.leiden(adata, resolution=10)
sc.tl.umap(adata)
sc.pl.umap(adata, color=['leiden'], legend_loc='on data', frameon=False, title='', use_raw=False)

```pytb
computing PCA
    on highly variable genes
    with n_comps=50
    finished (0:00:07)
computing neighbors
    using 'X_pca' with n_pcs = 50
    finished: added to `.uns['neighbors']`
    `.obsp['distances']`, distances for each pair of neighbors
    `.obsp['connectivities']`, weighted adjacency matrix (0:00:10)
running Leiden clustering
    finished: found 137 clusters and added
    'leiden', the cluster labels (adata.obs, categorical) (0:00:02)
computing UMAP
    finished: added
    'X_umap', UMAP coordinates (adata.obsm) (0:00:07)
the obs value 'leiden' has more than 103 categories. Uniform 'grey' color will be used for all categories.
```

#### Versions

<details>

scanpy==1.8.2 anndata==0.7.8 umap==0.5.2 numpy==1.20.3 scipy==1.7.2 pandas==1.3.4 scikit-learn==1.0.1 statsmodels==0.13.1 python-igraph==0.9.8 pynndescent==0.5.5

</details>

Hello Scanpy,
When I make >100 clusters, the 'leiden' becomes gray and cannot be changed back in the same notebook.
Could you please help me to solve this issue?
Thanks!
Best
YJ

**Comment by liuzj039** [comment]
Not the developer of scanpy. 
The reason for this is that scanpy will try to initialize the palette automatically if you do not provide it. 
Then this palette will be saved in `adata.uns` . When the number of clusters is large enough, scanpy cannot find a suitable palette, so all colors are initialized to grey.
After the number of clusters is reduced, you can just delete `adata.uns['leiden_colors']` to force the scanpy to reinitialize.

**Comment by ivirshup** [comment]
You can also specify the colormap to reset the colors.

Two reasonable changes in scanpy that could also prevent this:

* Running clustering again could reset the colors for the result clustering key
* Since there's no way the 100 color palette has 100 distinct colors, we could just start re-using colors past that instead of defaulting to grey.

**Comment by brianpenghe** [comment]
There's a way to plot more than 100 colors:

`sc.pl.umap(adata,color='leiden',palette=list(matplotlib.colors.CSS4_COLORS.values()))`

**Comment by nolarifi** [comment]
> There's a way to plot more than 100 colors:
> 
> `sc.pl.umap(adata,color='leiden',palette=list(matplotlib.colors.CSS4_COLORS.values()))`

Hello , please could tell me how I can store this plot in a file (png format for example)

**Comment by brianpenghe** [comment]
> > There's a way to plot more than 100 colors:
> > `sc.pl.umap(adata,color='leiden',palette=list(matplotlib.colors.CSS4_COLORS.values()))`
> 
> Hello , please could tell me how I can store this plot in a file (png format for example)

use the `save=`?
