### ISSUE TITLE
magic() error

### ISSUE THREAD

**Issue by doncarlos999** [scverse/scanpy#206]
Hi, I hit this error:

AttributeError                            Traceback (most recent call last)
<ipython-input-3-282f1d56354f> in <module>()
----> 1 sc.pp.magic(adata, verbose=2)

c:\scanpy\scanpy\scanpy\preprocessing\magic.py in magic(adata, name_list, k, a, t, n_pca, knn_dist, random_state, n_jobs, verbose, copy, **kwargs)
    148         # replace data with smoothed data
    149         adata.raw = adata
--> 150         adata.X = X_magic.X
    151 
    152     if copy:

AttributeError: 'numpy.ndarray' object has no attribute 'X'

I fixed it by changing line 150  from        adata.X = X_magic.X
to adata.X = X_magic

**Comment by falexwolf** [comment]
@scottgigante, could you field this one?

**Comment by doncarlos999** [comment]
I thought I had fixed it but it turns out that making that change didn't help.

Any ideas?

**Comment by scottgigante** [comment]
@doncarlos999 , can you please confirm that you have the latest version of MAGIC? You can do this by running
```
import magic
magic.__version__
```
MAGIC was only very recently (four days ago!) updated to support scanpy, so if you don't have version 1.1.0, I recommend reinstalling:
```
pip install --upgrade --user git+git://github.com/KrishnaswamyLab/MAGIC.git#subdirectory=python
```
Thanks for using MAGIC!

**Comment by doncarlos999** [comment]
I was on version 1.0.0. Updating to the newest version solved the problem.

Thanks a lot!
