### ISSUE TITLE
Illegal instruction with Python 3.9.7

### ISSUE THREAD

**Issue by pranzatelli** [scverse/scanpy#2062]
- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can copy&paste without having any data)

```python
import scanpy as sc
```

```pytb
Illegal instruction (core dumped)
```

#### Versions

<details>

Python 3.9.7 and scanpy 1.8.2.

CPU flags including instruction sets are pasted below.

fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt lwp fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb cpb hw_pstate ssbd ibpb vmmcall bmi1 arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold

I unfortunately cannot call scanpy.logging as I cannot import scanpy. I can, however, list the versions of all packages installed alongside scanpy.

anndata 0.7.8
cycler 0.11.0
fonttools 4.28.2
h5py 3.6.0
joblib 1.1.0
kiwisolver 1.3.2
llvmlite 0.37.0
matplotlib 3.5.0
natsort 8.0.0
networkx 2.6.0
numba 0.54.1
numexpr 2.7.3
numpy 1.20.3
pandas 1.3.4
patsy 0.5.2
pillow 8.4.0
pynndescent 0.5.5
python-dateutil 2.8.2
pytz 2021.3
scikit-learn 1.0.1
scipy 1.7.3
seaborn 0.11.2
setuptools-scm 6.3.2
sinfo 0.3.4
statsmodels 0.13.1
stdlib-list 0.8.0
tables 3.6.1
threadpoolctl 3.0.0
tqdm 4.62.3
umap-learn 0.5.2
xlrd-1.2.0

</details>

**Comment by ivirshup** [comment]
Thanks for opening a new issue for this, and the info.

Could you let me know a bit more about how you've installed scanpy? E.g. what OS, did you use conda or pip, etc.

My guess would be that this is numba related (which, from reporting the cpu flags, I'm guessing you suspect too).

Are you able to import `numba`? If so, what about `pynndescent` and `umap`? I'm trying to figure out if some code in scanpy is triggering the error, or if it's one of our dependencies.

---------------

Initially mentioned in https://github.com/theislab/scanpy/issues/1823#issuecomment-983551937

**Comment by pranzatelli** [comment]
I did successfully import all three dependencies and (just to make sure) still cannot import scanpy.
```
>>> import numba
>>> import pynndescent
>>> import umap
>>> import scanpy
Illegal instruction (core dumped)
```

**Comment by Zethson** [comment]
Does it work with other Python versions on your PC or is this issue 3.9.x(+) specific?

**Comment by Zethson** [comment]
Closed due to a lack of sufficient details. Please feel free to reopen!
