### ISSUE TITLE
Louvain installation is being difficult

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#2065]
Louvain is being difficult to build since a new setuptools release dropped any python2 compatibility https://github.com/vtraag/louvain-igraph/issues/57.

We've largely worked around this in #2063, by making louvain dependent tests optional. However, the paul15 PAGA test is difficult to extract louvian from. It checks hardcoded values based on the results of a louvain clustering. To adapt this test to use leiden, we would have to redo the tutorial and create new results. Or louvain building could be fixed, but the package is deprecated anyways.

**Comment by flying-sheep** [comment]
Fixed as vtraag/louvain-igraph#57 is done!

**Comment by flying-sheep** [comment]
We should get rid of any kind of reliance on louvain anyway, as you said.
