### ISSUE TITLE
sc.pl.heatmap: KeyError: "Values ['CD79A'], are not valid obs/ var names or indices.

### ISSUE THREAD

**Issue by DUAN-GAO** [scverse/scanpy#2068]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

Hello, after clustering I am trying to use heatmap to visualize the marker gene but got below error:
could anyone help, many thanks.
```python
ax = sc.pl.heatmap(adata,marker_genes_dict,groupby='louvain_r1',save="0.png")
```

```pytb
KeyError: "Values ['CD79A'], from ['CD79A', 'MS4A1', 'CD3D', 'CD8A', 'CD8B', 'GNLY', 'NKG7', 'CST3', 'LYZ', 'FCGR3A', 'FCER1A'], are not valid obs/ var names or indices."

```

#### Versions

<details>
anndata     0.7.5
scanpy      1.6.1
</details>

**Comment by hyjforesight** [comment]
I guess you use the HVGs, change use_raw=True

**Comment by Gloriacyy** [comment]
@hyjforesight I met similar problem, you're right!!  thanks a lot.  I have filterd hvgs before sc.tl.rank_genes_groups, adata= adata.raw.to_adata(), then pl.heatmap, it worked

**Comment by flying-sheep** [comment]
yup! genes you filtered out are not available unless you use `use_raw`
