### ISSUE TITLE
scikit-misc cannot be initiated when sc.pp.highly_variable_genes(adata, n_top_genes=5000, flavor='seurat_v3')

### ISSUE THREAD

**Issue by hyjforesight** [scverse/scanpy#2073]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [x] (optional) I have confirmed this bug exists on the master branch of scanpy.

---
**Hello Scanpy,
When I'm running sc.pp.highly_variable_genes(adata, n_top_genes=5000, flavor='seurat_v3'), it asks me to install scikit-misc, which is already installed. Please see the picture below.
Could you please help me to solve this issue?
Thanks!
Best,
YJ**
**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can copy&paste without having any data)

```python
# Your code here
```
![image](https://user-images.githubusercontent.com/75048821/145125005-64f8607e-9cb0-4740-8dca-7c80e35d30ef.png)

```pytb
[Paste the error output produced by the above code here]
```

#### Versions

<details>3.8

[Paste the output of scanpy.logging.print_versions() leaving a blank line after the details tag]

</details>scanpy==1.8.2 anndata==0.7.8 umap==0.5.2 numpy==1.20.3 scipy==1.7.2 pandas==1.3.4 scikit-learn==1.0.1 statsmodels==0.13.1 python-igraph==0.9.8 pynndescent==0.5.5
scvelo==0.2.4  scanpy==1.8.2  anndata==0.7.8  loompy==3.0.6  numpy==1.20.3  scipy==1.7.2  matplotlib==3.5.0  sklearn==1.0.1  pandas==1.3.4  
cellrank==1.5.0 scanpy==1.8.2 anndata==0.7.8 numpy==1.20.3 numba==0.54.1 scipy==1.7.2 pandas==1.3.4 pygpcca==1.0.2 scikit-learn==1.0.1 statsmodels==0.13.1 python-igraph==0.9.8 scvelo==0.2.4 pygam==0.8.0 matplotlib==3.5.0 seaborn==0.11.2

**Comment by davidhbrann** [comment]
In the "requirement already satisfied" it looks like "scikit-misc" is installed in a different location and not within the `site-packages` folder of the anaconda env listed on the line below for `numpy`. From within the `py38` env you could try to reinstall it with `pip install --user scikit-misc --force` and also delete the other one or remove it from your `$PYTHONPATH`? Installing things in the jupyter notebook might be using a different version of pip than the one in the environment (depending on how your kernels are set up) so I think it's sometimes safer to do these things from the command line.

**Comment by hyjforesight** [comment]
Hello @davidhbrann,
Thanks for the response.
I did pip install --user scikit-misc --force in the anaconda powershell, but this bug kept the same. Not solved.
Thanks!
Best,
YJ

**Comment by davidhbrann** [comment]
When I did `pip install --user scikit-misc` in my shell and then in python tried the line that errored for you `from skmisc.loess import loess`, everything worked fine for me. Also, depending on how conda is setup `pip install --user` might install it in your home directory, rather than the conda env. So you could also try activating the conda env and then running `pip install scikit-misc --force`. 

Can you print out the full traceback of what happens when you run `from skmisc.loess import loess`? If that was causing the `ImportError` it might be easier to see outside of the try/except block. You can also try `import skmisc; print(skmisc.__file__)` to see what that returns.

I also see some related issues (https://github.com/has2k1/scikit-misc/issues/12), which could indicate that it did not install correctly because it did not install the cython scripts properly on windows. The solution (install the numpy+mkl .whl first) in https://github.com/has2k1/scikit-misc/issues/4 might work?

**Comment by hyjforesight** [comment]
Hello @davidhbrann ,
Sorry for the late response.
I tried again without typing the `--user` in the Anaconda Powershell. Please see below.

Step1: install without force. Didn't work. Proceed to Step2.
```python
(base) C:\WINDOWS\system32>conda activate Python38
(Python38) C:\WINDOWS\system32>pip install scikit-misc
Requirement already satisfied: scikit-misc in c:\users\park_lab\appdata\roaming\python\python38\site-packages (0.1.4)
Requirement already satisfied: numpy in c:\users\park_lab\anaconda3\envs\python38\lib\site-packages (from scikit-misc) (1.20.3)
```
Step2: force install.
```python
(Python38) C:\WINDOWS\system32>pip install scikit-misc --force
Collecting scikit-misc
  Using cached scikit_misc-0.1.4-cp38-cp38-win_amd64.whl (142 kB)
Collecting numpy
  Downloading numpy-1.21.5-cp38-cp38-win_amd64.whl (14.0 MB)
     |████████████████████████████████| 14.0 MB 3.3 MB/s
Installing collected packages: numpy, scikit-misc
  Attempting uninstall: numpy
    Found existing installation: numpy 1.20.3
    Uninstalling numpy-1.20.3:
      Successfully uninstalled numpy-1.20.3
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\Park_Lab\\anaconda3\\envs\\Python38\\Lib\\site-packages\\~umpy\\.libs\\libopenblas.GK7GX5KEQ4F6UYO3P26ULGBQYHGQO7J4.gfortran-win_amd64.dll'
Consider using the `--user` option or check the permissions.
```
Step3: same errors.
```python
sc.pp.highly_variable_genes(adata, n_top_genes=5000, flavor='seurat_v3')
sc.pl.highly_variable_genes(adata)
ImportError                               Traceback (most recent call last)
~\anaconda3\envs\Python38\lib\site-packages\scanpy\preprocessing\_highly_variable_genes.py in _highly_variable_genes_seurat_v3(adata, layer, n_top_genes, batch_key, check_values, span, subset, inplace)
     52     try:
---> 53         from skmisc.loess import loess
     54     except ImportError:

~\AppData\Roaming\Python\Python38\site-packages\skmisc\loess\__init__.py in <module>
     50 """
---> 51 from ._loess import (loess, loess_model, loess_inputs, loess_control,
     52                      loess_outputs, loess_prediction,

ImportError: DLL load failed while importing _loess: The specified module could not be found.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_11028/1877627730.py in <module>
----> 1 sc.pp.highly_variable_genes(adata, n_top_genes=5000, flavor='seurat_v3')
      2 sc.pl.highly_variable_genes(adata)
      3 print(sum(adata.var.highly_variable))
      4 adata

~\anaconda3\envs\Python38\lib\site-packages\scanpy\preprocessing\_highly_variable_genes.py in highly_variable_genes(adata, layer, n_top_genes, min_disp, max_disp, min_mean, max_mean, span, n_bins, flavor, subset, inplace, batch_key, check_values)
    417 
    418     if flavor == 'seurat_v3':
--> 419         return _highly_variable_genes_seurat_v3(
    420             adata,
    421             layer=layer,

~\anaconda3\envs\Python38\lib\site-packages\scanpy\preprocessing\_highly_variable_genes.py in _highly_variable_genes_seurat_v3(adata, layer, n_top_genes, batch_key, check_values, span, subset, inplace)
     53         from skmisc.loess import loess
     54     except ImportError:
---> 55         raise ImportError(
     56             'Please install skmisc package via `pip install --user scikit-misc'
     57         )

ImportError: Please install skmisc package via `pip install --user scikit-misc
```
Step4: run `from skmisc.loess import loess`
```python
from skmisc.loess import loess
ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_11028/3052125001.py in <module>
----> 1 from skmisc.loess import loess

~\AppData\Roaming\Python\Python38\site-packages\skmisc\loess\__init__.py in <module>
     49    pp. 829--836. 1979.
     50 """
---> 51 from ._loess import (loess, loess_model, loess_inputs, loess_control,
     52                      loess_outputs, loess_prediction,
     53                      loess_confidence_intervals, loess_anova)

ImportError: DLL load failed while importing _loess: The specified module could not be found.
```
Step5: run `import skmisc; print(skmisc.__file__)`
```python
import skmisc; print(skmisc.__file__)
C:\Users\Park_Lab\AppData\Roaming\Python\Python38\site-packages\skmisc\__init__.py
```
Step6: due to Step4, I follow the solution (https://github.com/has2k1/scikit-misc/issues/4) to install Numpy with mkl.
```python
(base) C:\Users\Park_Lab>conda activate Python38
(Python38) C:\Users\Park_Lab>cd Downloads/
(Python38) C:\Users\Park_Lab\Downloads>pip install numpy-1.21.5+mkl-cp38-cp38-win_amd64.whl
Processing c:\users\park_lab\downloads\numpy-1.21.5+mkl-cp38-cp38-win_amd64.whl
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.5
    Uninstalling numpy-1.21.5:
      Successfully uninstalled numpy-1.21.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.54.1 requires numpy<1.21,>=1.17, but you have numpy 1.21.5+mkl which is incompatible.
Successfully installed numpy-1.21.5+mkl
```
Step7: check anaconda Python38 environment, numpy-1.21.5+mkl is successfully installed
![image](https://user-images.githubusercontent.com/75048821/147306587-eb94c188-5c18-40f0-add0-3a899872d786.png)

Step8: Scanpy import error. Numpy>v1.20 is conflicted with Scanpy
```python
import numpy as np
import pandas as pd
import scanpy as sc
import scanpy.external as sce
import scipy
sc.settings.verbosity = 3
sc.logging.print_header()
sc.set_figure_params(dpi=100, dpi_save=600)
    
import scvelo as scv
scv.settings.verbosity = 3
scv.settings.presenter_view = True
scv.logging.print_versions()

import cellrank as cr
cr.settings.verbosity = 3
cr.logging.print_versions()

import matplotlib.pyplot as pl
from matplotlib import rcParams
ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_13940/2696797780.py in <module>
      1 import numpy as np
      2 import pandas as pd
----> 3 import scanpy as sc
      4 import scanpy.external as sce
      5 import scipy

~\anaconda3\envs\Python38\lib\site-packages\scanpy\__init__.py in <module>
      4 
      5 if not within_flit():  # see function docstring on why this is there
----> 6     from ._utils import check_versions
      7 
      8     check_versions()

~\anaconda3\envs\Python38\lib\site-packages\scanpy\_utils\__init__.py in <module>
     27 from .. import logging as logg
     28 
---> 29 from .compute.is_constant import is_constant
     30 
     31 

~\anaconda3\envs\Python38\lib\site-packages\scanpy\_utils\compute\is_constant.py in <module>
      3 
      4 import numpy as np
----> 5 from numba import njit
      6 from scipy import sparse
      7 

~\anaconda3\envs\Python38\lib\site-packages\numba\__init__.py in <module>
    196 
    197 _ensure_llvm()
--> 198 _ensure_critical_deps()
    199 
    200 # we know llvmlite is working as the above tests passed, import it now as SVML

~\anaconda3\envs\Python38\lib\site-packages\numba\__init__.py in _ensure_critical_deps()
    136         raise ImportError("Numba needs NumPy 1.17 or greater")
    137     elif numpy_version > (1, 20):
--> 138         raise ImportError("Numba needs NumPy 1.20 or less")
    139 
    140     try:

ImportError: Numba needs NumPy 1.20 or less
```
Could you give me more suggestions?
Thanks!
Best,
YJ

**Comment by davidhbrann** [comment]
In the error it looks like numba requires numpy < 1.20, so you could try installing the `numpy‑1.19.5+mkl` whl from https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy before installing the scikit-misc one from https://www.lfd.uci.edu/~gohlke/pythonlibs/#scikit-misc? 

When you get the `Requirement already satisfied` error from `pip install`, you might need to first do `pip uninstall <pkg>` before installing

**Comment by hyjforesight** [comment]
Hello @davidhbrann,
Thanks for the suggestion.
I found that `numpy‑1.19.5+mkl‑cp36‑cp36m‑win_amd64.whl` only supports python 3.6, but the support of python 3.6 has been dropped by Scanpy. I didn't find `numpy-1.20.3+mkl-cp38-cp38-win_amd64.whl` by google yet, but I believe that your solution will work. It seems that `numpy‑1.21.5+mkl‑cp38‑cp38‑win_amd64.whl` is the only hope, but Scanpy requires numpy<=1.20. I think it's the compatibility issue. Hope Scanpy can solve this compatibility issue in the future.
Thanks!
Best,
YJ

**Comment by ghost** [comment]
I found a workaround that does not require downloading the `.whl` file for `numpy=1.19.5`. 
By default, MKL is included when you install numpy with conda. It's good to do this in a new environment.
```
conda create -n scanpy_env
conda activate scanpy_env
conda install numpy=1.19
conda install seaborn scikit-learn statsmodels numba pytables
conda install -c conda-forge python-igraph leidenalg
pip install scanpy==1.8.1
```
Now I can run `sc.pp.highly_variable_genes()` with no problem.

**Comment by jpcartailler** [comment]
@maarten-hifibio Thx for the recipe, it worked in a win10/Python-3.8 env't, for anyone else looking here.

**Comment by ghost** [comment]
> I found a workaround that does not require downloading the `.whl` file for `numpy=1.19.5`. By default, MKL is included when you install numpy with conda. It's good to do this in a new environment.
> 
> ```
> conda create -n scanpy_env
> conda activate scanpy_env
> conda install numpy=1.19
> conda install seaborn scikit-learn statsmodels numba pytables
> conda install -c conda-forge python-igraph leidenalg
> pip install scanpy
> ```
> 
> Now I can run `sc.pp.highly_variable_genes()` with no problem.

Update: this workaround does not seem to work anymore, at least for scanpy 1.8.2 (you'll need to `pip install scanpy==1.8.1`). 
During `pip install scanpy`,  a newer version of numpy is installed and version 1.19 is overwritten. This newer version does not have MKL, leading us back to square one. It's also not possible to `conda install numpy 1.19` as the very last step, because this leads to another error (it's related to the fact that scanpy needs to be compiled with the same version of numpy).

**Comment by maarten-hifibio** [comment]
I'd really encourage the scanpy devs to look into this. 
I have spent hours creating conda environments using different Python versions and different orders of installing packages, but I am willing to claim that it is currently not possible to install scanpy on Windows 10 in such a way that `sc.pp.highly_variable_genes()` works.

**Comment by ly15296191253** [comment]
It is 13 Jun ,2022 ,today.I need to creat a new evn ,in which I can run the code as **sc.pp.highly_variable_genes(adata, n_top_genes=5000, flavor='seurat_v3')****. I meet the question that I can't **Import skmisc.loess as loess** ,while the code works fine in my last computer. So，there is a solution can solve this question ,now?

**Comment by ly15296191253** [comment]
> I solve this question that can’t import skmisc.loess  as loess by chance。the solution is:  'python3.7'+'numpy-1.20.1+mkl-cp37-cp37m-win_amd64.whl'+'scipy==1.7.3'+'scikit-learn==1.0.2'+'scikit-misc==0.1.4'+'scanpy==1.9.1'



> It is 13 Jun ,2022 ,today.I need to creat a new evn ,in which I can run the code as **sc.pp.highly_variable_genes(adata, n_top_genes=5000, flavor='seurat_v3')****. I meet the question that I can't **Import skmisc.loess as loess** ,while the code works fine in my last computer. So，there is a solution can solve this question ,now?

**Comment by aqlkzf** [comment]
I met the same problem one day ago.  The methods suggested by Sanbomics may be helpful, but I solved it by changing the order of the installations of the packages. I run the following: 
conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch 
conda install scvi-tools -c conda-forge
conda install -c conda-forge scanpy python-igraph leidenalg 
It works fine now.

**Comment by aqlkzf** [comment]
I met the same problem one day ago.   I run the following: 
conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch 
conda install scvi-tools -c conda-forge
conda install -c conda-forge scanpy python-igraph leidenalg 
It works fine now.

**Comment by amssljc** [comment]
I've tried all above suggestions, but it still doesn't work.

**Comment by willyroqueb** [comment]
Having the same issue too, cant seem to resolve it with any of prior options.

**Comment by marwan-unipd** [comment]
i cant do it too and it giving me headache for days now

**Comment by allumik** [comment]
Had this problem, followed the `scikit-misc` package [issue](https://github.com/has2k1/scikit-misc/issues/12) on a related problem and installed the recommended patch with 
```
pip install -i https://test.pypi.org/simple/ "scikit-misc==0.2.0rc1"
```

Seems to work now for me.

**Comment by kukuxie** [comment]
sc.pp.highly_variable_genes(adata, flavor="seurat_v3", n_top_genes=3000)
error:Please install skmisc package via `pip install --user scikit-misc
I have the same problem as the blogger, so how should I solve it

**Comment by kukuxie** [comment]
sc.pp.highly_variable_genes(adata, flavor="seurat_v3", n_top_genes=3000)
error:Please install skmisc package via `pip install --user scikit-misc
I have the same problem as the blogger, so how should I solve it

**Comment by JinyunNiu** [comment]
I think maybe i found a solution to solve this problem.
Maybe this problem is caused by the version of scikit—misc，when you use pip install --user scikit-misc or pip install  scikit-misc，the system will install scikit-misc==0.1.4.
so,i try to install another verion of scikit-misc,you can use install -i https://test.pypi.org/simple/ "scikit-misc==0.2.0rc1.
In addition, this line of command needs to be used when python is greater than or equal to 3.8.

**Comment by HSvitina** [comment]
> Had this problem, followed the `scikit-misc` package [issue](https://github.com/has2k1/scikit-misc/issues/12) on a related problem and installed the recommended patch with
> 
> ```
> pip install -i https://test.pypi.org/simple/ "scikit-misc==0.2.0rc1"
> ```
> 
> Seems to work now for me.

Thank you. It just worked for me, in July 2024.
