### ISSUE TITLE
scanpy 1.8.2 KeyError: 'rank_genes_groups'

### ISSUE THREAD

**Issue by DUAN-GAO** [scverse/scanpy#2074]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

scanpy 1.8.2 KeyError: 'rank_genes_groups'

**Comment by Zethson** [comment]
Please provide more details.

**Comment by Zethson** [comment]
Closing due to a lack of details. Feel free to reopen if you have additional information.

**Comment by imet-k** [comment]
I solved it by adding the key (in my case  key="wilcoxon")
