### ISSUE TITLE
Running example with magics gives error

### ISSUE THREAD

**Issue by terooatt** [scverse/scanpy#208]
Hi,
I was trying to run the quick example described in the magic api cmd using datasets.paul15 but it keeps on giving me the same error. See below the code I used and the error it gives. 

import numpy as np
import pandas as pd
import scanpy.api as sc
import matplotlib.pyplot as pl
import phate
import magic

sc.settings.verbosity = 3  # verbosity: errors (0), warnings (1), info (2), hints (3)
sc.settings.set_figure_params(dpi=80)  # low dpi (dots per inch) yields small inline figures
sc.logging.print_version_and_date()
# we will soon provide an update with more recent dependencies
sc.logging.print_versions_dependencies_numerics()

Running Scanpy 1.2.2+72.gbc6661c on 2018-07-18 19:40.
Dependencies: anndata==0.6.5 numpy==1.14.3 scipy==1.1.0 pandas==0.23.0 scikit-learn==0.19.1 statsmodels==0.9.0 python-igraph==0.7.1 louvain==0.6.1 

adata = sc.datasets.paul15()

WARNING: In Scanpy 0.*, this returned logarithmized data. Now it returns non-logarithmized data.
... storing 'paul15_clusters' as categorical

sc.pp.normalize_per_cell(adata)
sc.pp.sqrt(adata)
adata_magic = sc.pp.magic(adata, name_list=['Mpo', 'Klf1', 'Ifitm1'], k=5)
adata_magic.shape

computing PHATE

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-79-129f35d34dbd> in <module>()
      2 sc.pp.normalize_per_cell(adata)
      3 sc.pp.sqrt(adata)
----> 4 adata_magic = sc.pp.magic(adata.X, name_list=['Mpo', 'Klf1', 'Ifitm1'], k=5)
      5 adata_magic.shape

~/software/scanpy/scanpy/preprocessing/magic.py in magic(adata, name_list, k, a, t, n_pca, knn_dist, random_state, n_jobs, verbose, copy, **kwargs)
    131                     n_jobs=n_jobs,
    132                     verbose=verbose,
--> 133                     **kwargs).fit_transform(adata,
    134                                             genes=name_list)
    135     logg.info('    finished', time=True,

TypeError: 'module' object is not callable

**Comment by falexwolf** [comment]
Maybe this helps https://github.com/theislab/scanpy/issues/206?

**Comment by terooatt** [comment]
Yes, It helped. I updated the magic version and it seems to be working fine now. 
Thanks a lot.
