### ISSUE TITLE
Can you please include CytoTRACE Trajectory Reconstruction Analysis into Scanpy?

### ISSUE THREAD

**Issue by danli349** [scverse/scanpy#2084]
Can you please include CytoTRACE Trajectory Reconstruction Analysis into Scanpy?
https://cytotrace.stanford.edu/
Thanks

**Comment by hyjforesight** [comment]
It's included in CellRank. Check these two https://cellrank.readthedocs.io/en/stable/beyond_rna_velocity.html and https://github.com/theislab/scvelo/issues/773

**Comment by danli349** [comment]
That is great! Thanks!
