### ISSUE TITLE
`flavor="seurat_v3"` HVG aggregation over batches not intended 

### ISSUE THREAD

**Issue by adamgayoso** [scverse/scanpy#2088]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [x] (optional) I have confirmed this bug exists on the master branch of scanpy.

In the test of the flavor, the sorting over batches is correct with respect to how Seurat actually does it:

https://github.com/theislab/scanpy/blob/83f90141fd18943a1795772d3d39f4e9eefd65c3/scanpy/tests/test_highly_variable_genes.py#L138-L142

First sort by number of batches it's called a HVG and then second break ties by the median rank.

In the actual function, it's the reverse:

https://github.com/theislab/scanpy/blob/83f90141fd18943a1795772d3d39f4e9eefd65c3/scanpy/preprocessing/_highly_variable_genes.py#L136-L143

I propose we put in the fix (which is currently being tested with high accuracy). The simplest solution would be to call it a new flavor. Ideally this would get in as soon as possible as this is a high volume function from what I understand.

**Comment by ivirshup** [comment]
Might be of interest to @gokceneraslan @jlause

**Comment by jlause** [comment]
I think this is related to #1733 (which I never followed up on, sorry about that!)

**Comment by adamgayoso** [comment]
I suppose we need to maintain backwards compatibility, so I still opt for the new flavor plus a userwarning on the old flavor

**Comment by adamgayoso** [comment]
Any ideas on how to handle this? It would be great to at least be consistent with what Seurat does (even if we haven't come to a conclusion on the ideal to gather across batches)

**Comment by adamgayoso** [comment]
@Zethson @ivirshup can we make this change? It's disappointing that this has been around for so long as users might not realize there's an inconsistency.

**Comment by flying-sheep** [comment]
OK, let’s close this in favor of #1733 and update that one with the newest information if necessary
