### ISSUE TITLE
Incorrect names on logistic regression gene ranking plot

### ISSUE THREAD

**Issue by mstubb** [scverse/scanpy#209]
When analysing a dataset, I can make gene ranking plots using either the t-test or the logistic regression method and everything looks sane (see image below)

<img width="1101" alt="screen shot 2018-07-19 at 21 59 09" src="https://user-images.githubusercontent.com/1142918/42969897-99896fc6-8b9f-11e8-8ae6-761b89d1e6f6.png">

However, if I then assign names to my clusters and do this again, the t-test version looks as expected but the plot using logistic regression data seems to mismatch the cluster names with their top-ranked genes. The plot titles do not match the genes that are plotted.

<img width="1102" alt="screen shot 2018-07-19 at 22 00 09" src="https://user-images.githubusercontent.com/1142918/42969968-dd19dfc8-8b9f-11e8-8b7f-f671eb42ed82.png">

Is this a bug or am I doing something wrong? 

Hope this makes sense, please let me know if you need any more information.

**Comment by falexwolf** [comment]
Oh man, sorry that I seem to have completely forgotten about this here. And even worse, it looks very much like a very strange bug. I could reproduce the behavior but need to look into it more closely tomorrow or during the next days...

**Comment by falexwolf** [comment]
Is fixed via  https://github.com/theislab/scanpy/commit/0ed304a64038f7d2c11b36fe5883ab9765ffba57. Thank you for posting this.
