### ISSUE TITLE
What are the limits of AnnData by number of cells and/or genes? 

### ISSUE THREAD

**Issue by apredeus** [scverse/scanpy#2091]
Hi, 

I'm trying to use `Scanpy` to analyze a recent dataset. It's been published on [GEO](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE156793) as a loom file that has about 4 million cells and 68k genes. I was wondering if that's possible according to the object architecture? And if yes, are there any estimates - how much RAM should say each 100k cells occupy? To have this estimate would be useful when planning analysis of big datasets. 

Thank you in advance.

**Comment by Zethson** [comment]
Scanpy was proven to run on 1.3 million datasets. More details with RAM usage numbers can be found here: https://github.com/theislab/scanpy_usage/tree/master/170522_visualizing_one_million_cells
