### ISSUE TITLE
Plot genes without highly_variable_genes

### ISSUE THREAD

**Issue by amufaamo** [scverse/scanpy#2098]
I'm new to scanpy, and I want to plot umap with some genes.

In this tutorial, it's written below

> sc.pl.umap(adata, color=['CST3', 'NKG7', 'PPBP'])

But, I could show only highly variable genes, because other genes were discarded by the code below

> adata = adata[:, adata.var.highly_variable]

So, how can I plot umap with genes without highly variable? How can I leave all genes in anndata?

**Comment by davidhbrann** [comment]
You can keep the genes in `adata.raw`, make a copy of the anndata object (`adata_old = adata.copy()`) before subsetting, or give the hvg one a new name like `adata_hvg = adata[:, adata.var.highly_variable].copy()`

**Comment by amufaamo** [comment]
OK, I try it. Thank you so much.
