### ISSUE TITLE
Wrong UMAP output 

### ISSUE THREAD

**Issue by flde** [scverse/scanpy#2101]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

Dear scanpy team, many thanks for your great work! I hope you can help me with an issue regarding sc.tl.umap() which does not produce accurate results. As a example I run your pbmc3k tutorial and attached the html as zip. Everything works as espected but the UMAP layout is strange. 

In addition, when trying to use the PAGA position with sc.tl.umap() the cells are placed in rectangles similar to #918 (no example attached). 

Do you have a idea what is going wrong? Any help is highly appreciated. Please let me know if I can provide further information. 

Best, 
Flo

Info: scanpy==1.7.2 anndata==0.7.8 umap==0.5.2

[pbmc3k.zip](https://github.com/theislab/scanpy/files/7815745/pbmc3k.zip)
![umap](https://user-images.githubusercontent.com/20926246/148239794-0ae37b2e-1a8c-47d1-ad09-232ad7164608.png)

**Comment by flde** [comment]
Okay, I solved the issue. In my environment, scanpy==1.7.2 does not work with umap==0.5.2. I pip uninstall scanpy and umap-learn. Next I installed umap-learn through conda which was umap==0.5.1. When installing scanpy again it works as expected. 

Not sure if its worth looking further into it but pip install scanpy also installs umap==0.5.2 (which does not work at least for me). 

Many thanks! 
![umap_0 5 1](https://user-images.githubusercontent.com/20926246/148250255-5ac00a46-cbc9-4608-a893-0472e32f5fb5.png)

**Comment by Zethson** [comment]
Hi,

If you solely `pip install scanpy` it will use the latest versions of both, Scanpy and umap-learn. These are certainly compatible. Scanpy 1.7.2 not being perfectly compatible with the latest umap-learn package is an artifact of us not pinning the dependencies too hard and being more on the lenient side.

I'd suggest to simply use the latest versions of both packages and you should not run into any problems.

**Comment by flde** [comment]
Many thanks for the clarification, Lukas!

**Comment by irislee1106** [comment]
Thanks for the solution and clarification. I'm having the same issue when running umap too, happy to find this thread!

**Comment by irislee1106** [comment]
I was having the same issue these days. Happy to find this thread.
Fixed the issue by simply using the latest version of scanpy. Thanks a lot!!
