### ISSUE TITLE
ImportError: DLL load failed while importing utilsextension

### ISSUE THREAD

**Issue by hyjforesight** [scverse/scanpy#2108]
- [✔] I have checked that this issue has not already been reported.
- [✔ ] I have confirmed this bug exists on the latest version of scanpy.
- [ ✔] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

Hello Scanpy,
I installed Scanpy, scVelo, CellRank, bbknn 2 months ago and never upgrade the packages. They were running very smoothly until I reimage my PC and reinstall Scanpy in anaconda today (Anaconda3-2021.05-Windows-x86_64, python3.8.12).
I tired `pip install scanpy[leiden]`. Tried `conda install seaborn scikit-learn statsmodels numba pytables`, `conda install -c conda-forge python-igraph leidenalg`. Tried installing `Java` and `visual C++ 2012-2022 redistributable`. Also tried rebuilding a new environment and reinstalled everything. Whatever I try, this bug still exists when I import Scanpy.
I guess it may be the incompatibility issue of packages. Some dependency packages which were upgraded by the developer in these months caused this incompatibility issue. Could you please help me with this bug?
Thanks!
Best,
YJ

### Minimal code sample (that we can copy&paste without having any data)

```python
import numpy as np
import pandas as pd
import scanpy as sc
import scanpy.external as sce
import scipy
sc.settings.verbosity = 3
sc.logging.print_header()
sc.set_figure_params(dpi=100, dpi_save=600)
    
import matplotlib.pyplot as pl
from matplotlib import rcParams
```

```pytb
ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_7844/2696797780.py in <module>
      1 import numpy as np
      2 import pandas as pd
----> 3 import scanpy as sc
      4 import scanpy.external as sce
      5 import scipy

~\.conda\envs\Python38\lib\site-packages\scanpy\__init__.py in <module>
     12     # (start with settings as several tools are using it)
     13     from ._settings import settings, Verbosity
---> 14     from . import tools as tl
     15     from . import preprocessing as pp
     16     from . import plotting as pl

~\.conda\envs\Python38\lib\site-packages\scanpy\tools\__init__.py in <module>
     15 from ._leiden import leiden
     16 from ._louvain import louvain
---> 17 from ._sim import sim
     18 from ._score_genes import score_genes, score_genes_cell_cycle
     19 from ._dendrogram import dendrogram

~\.conda\envs\Python38\lib\site-packages\scanpy\tools\_sim.py in <module>
     21 from anndata import AnnData
     22 
---> 23 from .. import _utils, readwrite, logging as logg
     24 from .._settings import settings
     25 from .._compat import Literal

~\.conda\envs\Python38\lib\site-packages\scanpy\readwrite.py in <module>
      8 import pandas as pd
      9 from matplotlib.image import imread
---> 10 import tables
     11 import anndata
     12 from anndata import (

~\.conda\envs\Python38\lib\site-packages\tables\__init__.py in <module>
     43 
     44 # Necessary imports to get versions stored on the cython extension
---> 45 from .utilsextension import get_hdf5_version as _get_hdf5_version
     46 
     47 

ImportError: DLL load failed while importing utilsextension
```

#### Versions

<details>

Package             Version
------------------- ---------
anndata             0.7.8
anyio               2.2.0
argon2-cffi         20.1.0
async-generator     1.10
attrs               21.2.0
Babel               2.9.1
backcall            0.2.0
bleach              4.1.0
Bottleneck          1.3.2
brotlipy            0.7.0
certifi             2021.10.8
cffi                1.15.0
charset-normalizer  2.0.4
colorama            0.4.4
cryptography        36.0.0
cycler              0.11.0
debugpy             1.5.1
decorator           5.1.0
defusedxml          0.7.1
entrypoints         0.3
fonttools           4.25.0
h5py                3.6.0
idna                3.3
igraph              0.9.9
importlib-metadata  4.8.2
ipykernel           6.4.1
ipython             7.29.0
ipython-genutils    0.2.0
jedi                0.18.0
Jinja2              3.0.2
joblib              1.1.0
json5               0.9.6
jsonschema          3.2.0
jupyter-client      7.1.0
jupyter-core        4.9.1
jupyter-server      1.4.1
jupyterlab          3.2.1
jupyterlab-pygments 0.1.2
jupyterlab-server   2.10.2
kiwisolver          1.3.1
leidenalg           0.8.8
llvmlite            0.37.0
MarkupSafe          2.0.1
matplotlib          3.5.0
matplotlib-inline   0.1.2
mistune             0.8.4
mkl-fft             1.3.1
mkl-random          1.2.2
mkl-service         2.4.0
mock                4.0.3
munkres             1.1.4
natsort             8.0.2
nbclassic           0.2.6
nbclient            0.5.3
nbconvert           6.1.0
nbformat            5.1.3
nest-asyncio        1.5.1
networkx            2.6.3
notebook            6.4.6
numba               0.54.1
numexpr             2.8.1
numpy               1.20.3
olefile             0.46
packaging           21.3
pandas              1.3.5
pandocfilters       1.4.3
parso               0.8.3
patsy               0.5.2
pickleshare         0.7.5
Pillow              8.4.0
pip                 21.2.2
prometheus-client   0.12.0
prompt-toolkit      3.0.20
pycparser           2.21
Pygments            2.10.0
pynndescent         0.5.5
pyOpenSSL           21.0.0
pyparsing           3.0.4
pyrsistent          0.18.0
PySocks             1.7.1
python-dateutil     2.8.2
python-igraph       0.9.9
pytz                2021.3
pywin32             302
pywinpty            0.5.7
pyzmq               22.3.0
requests            2.27.1
scanpy              1.8.2
scikit-learn        1.0.2
scipy               1.7.3
seaborn             0.11.2
Send2Trash          1.8.0
setuptools          58.0.4
sinfo               0.3.4
sip                 4.19.13
six                 1.16.0
sniffio             1.2.0
statsmodels         0.12.2
stdlib-list         0.8.0
tables              3.6.1
terminado           0.9.4
testpath            0.5.0
texttable           1.6.4
threadpoolctl       2.2.0
tornado             6.1
tqdm                4.62.3
traitlets           5.1.1
umap-learn          0.5.2
urllib3             1.26.7
wcwidth             0.2.5
webencodings        0.5.1
wheel               0.37.1
win-inet-pton       1.1.0
wincertstore        0.2
xlrd                1.2.0
zipp                3.7.0

</details>

**Comment by hyjforesight** [comment]
Here is the old package information, in which I run Scanpy very well before.
Windows 10 x64 bit, 20H2.

scanpy==1.8.2 anndata==0.7.8 umap==0.5.2 numpy==1.20.3 scipy==1.7.3 pandas==1.3.5 scikit-learn==1.0.1 statsmodels==0.13.1 python-igraph==0.9.8 pynndescent==0.5.5
scvelo==0.2.4 scanpy==1.8.2 anndata==0.7.8 loompy==3.0.6 numpy==1.20.3 scipy==1.7.3 matplotlib==3.5.1 sklearn==1.0.1 pandas==1.3.5
cellrank==1.5.0 scanpy==1.8.2 anndata==0.7.8 numpy==1.20.3 numba==0.54.1 scipy==1.7.3 pandas==1.3.5 pygpcca==1.0.2 scikit-learn==1.0.1 statsmodels==0.13.1 python-igraph==0.9.8 scvelo==0.2.4 pygam==0.8.0 matplotlib==3.5.1 seaborn==0.11.2

**Comment by Koncopd** [comment]
It seems to be a pytables problem. What happens if you install pytables in a fresh python 3.8 environment?
If `import tables` fails, you could also try uninstalling pytables and installing the package from conda-forge.
`conda install -c conda-forge pytables.`

**Comment by Koncopd** [comment]
@ivirshup It seems we have to get rid of tables.

**Comment by hyjforesight** [comment]
Hello @Koncopd ,
Thanks for the response!

Step 1: I created a fresh new environment (py3.8.12)
```python
!pip install scanpy[leiden]

Successfully installed anndata-0.7.8 cycler-0.11.0 fonttools-4.28.5 h5py-3.6.0 igraph-0.9.9 joblib-1.1.0 kiwisolver-1.3.2 leidenalg-0.8.8 llvmlite-0.38.0 matplotlib-3.5.1 natsort-8.0.2 networkx-2.6.3 numba-0.55.0 numexpr-2.8.1 numpy-1.21.5 pandas-1.3.5 patsy-0.5.2 pillow-9.0.0 pynndescent-0.5.5 python-igraph-0.9.9 scanpy-1.8.2 scikit-learn-1.0.2 scipy-1.7.3 seaborn-0.11.2 sinfo-0.3.4 statsmodels-0.13.1 stdlib-list-0.8.0 tables-3.7.0 texttable-1.6.4 threadpoolctl-3.0.0 tqdm-4.62.3 umap-learn-0.5.2 xlrd-1.2.0

import numpy as np
import pandas as pd
import scanpy as sc
import scanpy.external as sce
import scipy
sc.settings.verbosity = 3
sc.logging.print_header()
sc.set_figure_params(dpi=100, dpi_save=600)

ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_8256/1710492625.py in <module>
      1 import numpy as np
      2 import pandas as pd
----> 3 import scanpy as sc
      4 import scanpy.external as sce
      5 import scipy

~\.conda\envs\NewPy38\lib\site-packages\scanpy\__init__.py in <module>
     12     # (start with settings as several tools are using it)
     13     from ._settings import settings, Verbosity
---> 14     from . import tools as tl
     15     from . import preprocessing as pp
     16     from . import plotting as pl

~\.conda\envs\NewPy38\lib\site-packages\scanpy\tools\__init__.py in <module>
     15 from ._leiden import leiden
     16 from ._louvain import louvain
---> 17 from ._sim import sim
     18 from ._score_genes import score_genes, score_genes_cell_cycle
     19 from ._dendrogram import dendrogram

~\.conda\envs\NewPy38\lib\site-packages\scanpy\tools\_sim.py in <module>
     21 from anndata import AnnData
     22 
---> 23 from .. import _utils, readwrite, logging as logg
     24 from .._settings import settings
     25 from .._compat import Literal

~\.conda\envs\NewPy38\lib\site-packages\scanpy\readwrite.py in <module>
      8 import pandas as pd
      9 from matplotlib.image import imread
---> 10 import tables
     11 import anndata
     12 from anndata import (

~\.conda\envs\NewPy38\lib\site-packages\tables\__init__.py in <module>
     43 
     44 # Necessary imports to get versions stored on the cython extension
---> 45 from .utilsextension import get_hdf5_version as _get_hdf5_version
     46 
     47 

ImportError: DLL load failed while importing utilsextension
```
Step 2: Then I install tables
```python
!pip install tables

Requirement already satisfied: tables in c:\users\hyjfo\.conda\envs\newpy38\lib\site-packages (3.7.0)
Requirement already satisfied: packaging in c:\users\hyjfo\.conda\envs\newpy38\lib\site-packages (from tables) (21.3)
Requirement already satisfied: numpy>=1.19.0 in c:\users\hyjfo\.conda\envs\newpy38\lib\site-packages (from tables) (1.21.5)
Requirement already satisfied: numexpr>=2.6.2 in c:\users\hyjfo\.conda\envs\newpy38\lib\site-packages (from tables) (2.8.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\hyjfo\.conda\envs\newpy38\lib\site-packages (from packaging->tables) (3.0.4)

import tables

ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_8256/574719567.py in <module>
----> 1 import tables

~\.conda\envs\NewPy38\lib\site-packages\tables\__init__.py in <module>
     43 
     44 # Necessary imports to get versions stored on the cython extension
---> 45 from .utilsextension import get_hdf5_version as _get_hdf5_version
     46 
     47 

ImportError: DLL load failed while importing utilsextension
```
Step 3: As you recommend, I do `!pip uninstall tables` and `conda install -c conda-forge pytables`, then
```python
import tables    # pass

import numpy as np
import pandas as pd
import scanpy as sc
import scanpy.external as sce
import scipy
sc.settings.verbosity = 3
sc.logging.print_header()
sc.set_figure_params(dpi=100, dpi_save=600)

ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_15024/1710492625.py in <module>
      1 import numpy as np
      2 import pandas as pd
----> 3 import scanpy as sc
      4 import scanpy.external as sce
      5 import scipy

~\.conda\envs\NewPy38\lib\site-packages\scanpy\__init__.py in <module>
      4 
      5 if not within_flit():  # see function docstring on why this is there
----> 6     from ._utils import check_versions
      7 
      8     check_versions()

~\.conda\envs\NewPy38\lib\site-packages\scanpy\_utils\__init__.py in <module>
     19 from numpy import random
     20 from scipy import sparse
---> 21 from anndata import AnnData, __version__ as anndata_version
     22 from textwrap import dedent
     23 from packaging import version

~\.conda\envs\NewPy38\lib\site-packages\anndata\__init__.py in <module>
      5 if not within_flit():
      6     del within_flit
----> 7     from ._core.anndata import AnnData, ImplicitModificationWarning
      8     from ._core.merge import concat
      9     from ._core.raw import Raw

~\.conda\envs\NewPy38\lib\site-packages\anndata\_core\anndata.py in <module>
     15 from typing import Tuple, List  # Generic
     16 
---> 17 import h5py
     18 from natsort import natsorted
     19 import numpy as np

~\.conda\envs\NewPy38\lib\site-packages\h5py\__init__.py in <module>
     31         raise
     32 
---> 33 from . import version
     34 
     35 if version.hdf5_version_tuple != version.hdf5_built_version_tuple:

~\.conda\envs\NewPy38\lib\site-packages\h5py\version.py in <module>
     13 
     14 from collections import namedtuple
---> 15 from . import h5 as _h5
     16 import sys
     17 import numpy

h5py\h5.pyx in init h5py.h5()

ImportError: DLL load failed while importing defs
````
Step4: I do `!pip uninstall h5py` and `conda install -c conda-forge pytables h5py`, then
```python
import numpy as np
import pandas as pd
import scanpy as sc
import scanpy.external as sce
import scipy
sc.settings.verbosity = 3
sc.logging.print_header()
sc.set_figure_params(dpi=100, dpi_save=600)

ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_14912/1710492625.py in <module>
      1 import numpy as np
      2 import pandas as pd
----> 3 import scanpy as sc
      4 import scanpy.external as sce
      5 import scipy

~\.conda\envs\NewPy38\lib\site-packages\scanpy\__init__.py in <module>
      4 
      5 if not within_flit():  # see function docstring on why this is there
----> 6     from ._utils import check_versions
      7 
      8     check_versions()

~\.conda\envs\NewPy38\lib\site-packages\scanpy\_utils\__init__.py in <module>
     27 from .. import logging as logg
     28 
---> 29 from .compute.is_constant import is_constant
     30 
     31 

~\.conda\envs\NewPy38\lib\site-packages\scanpy\_utils\compute\is_constant.py in <module>
      3 
      4 import numpy as np
----> 5 from numba import njit
      6 from scipy import sparse
      7 

~\.conda\envs\NewPy38\lib\site-packages\numba\__init__.py in <module>
    198 
    199 _ensure_llvm()
--> 200 _ensure_critical_deps()
    201 
    202 # we know llvmlite is working as the above tests passed, import it now as SVML

~\.conda\envs\NewPy38\lib\site-packages\numba\__init__.py in _ensure_critical_deps()
    138         raise ImportError("Numba needs NumPy 1.18 or greater")
    139     elif numpy_version > (1, 21):
--> 140         raise ImportError("Numba needs NumPy 1.21 or less")
    141 
    142     try:

ImportError: Numba needs NumPy 1.21 or less
```
Step5: I do` !pip uninstall Numpy`, then
```python
!pip install numpy
Requirement already satisfied: numpy in c:\users\hyjfo\.conda\envs\newpy38\lib\site-packages (1.21.5)

import numpy as np
import pandas as pd
import scanpy as sc
import scanpy.external as sce
import scipy
sc.settings.verbosity = 3
sc.logging.print_header()
sc.set_figure_params(dpi=100, dpi_save=600)

AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_8308/1710492625.py in <module>
      1 import numpy as np
----> 2 import pandas as pd
      3 import scanpy as sc
      4 import scanpy.external as sce
      5 import scipy

~\.conda\envs\NewPy38\lib\site-packages\pandas\__init__.py in <module>
     20 
     21 # numpy compat
---> 22 from pandas.compat import (
     23     np_version_under1p18 as _np_version_under1p18,
     24     is_numpy_dev as _is_numpy_dev,

~\.conda\envs\NewPy38\lib\site-packages\pandas\compat\__init__.py in <module>
     12 import warnings
     13 
---> 14 from pandas._typing import F
     15 from pandas.compat.numpy import (
     16     is_numpy_dev,

~\.conda\envs\NewPy38\lib\site-packages\pandas\_typing.py in <module>
     82 # array-like
     83 
---> 84 ArrayLike = Union["ExtensionArray", np.ndarray]
     85 AnyArrayLike = Union[ArrayLike, "Index", "Series"]
     86 

AttributeError: module 'numpy' has no attribute 'ndarray'
```
It looks like an endless error. What's wrong with the `!pip install scanpy[leiden]`? It installed so many incompatible packages which never happened before.

**Comment by ivirshup** [comment]
#2064 should do it.

There seems to be some issues with recent builds of pytables. I've been having periodic trouble installing it, but had trouble reproducing the error when I tried. IIRC, the errors made me think it was some incompatibility between new versions of `pip`/ `setuptools` and old builds of `pytables` – but that wasn't on windows.

@MxMstrmn has also mentioned seeing some issues with pytables installing on windows.

**Comment by Koncopd** [comment]
@hyjforesight no, that is a mess.
Could you try please 3 things:

1. create fresh environment with python 3.8, install only pytables
`conda install pytables`
then run python and check
`import tables`
2. create fresh environment with python 3.8, install only pytables from conda-forge
`conda install -c conda-forge pytables`
then run python and check
`import tables`
3. create fresh environment with python 3.8 and install just scanpy (and nothing else)
`conda install -c conda-forge scanpy`
then run python and check
`import scanpy`

**Comment by hyjforesight** [comment]
Hello @Koncopd ,
1. New py3.8.12 environment
```python
conda install pytables
import tables    # pass
```
2. New py3.8.12 environment
```python
conda install pytables
import tables    # pass
```
3. New py3.8.12 environment
```python
conda install -c conda-forge scanpy
import scanpy    # pass
```
I can run the Scanpy pipeline now. However, I'm wondering whether your team did some slight changes for pca, neighboring, leiden, umap functions (not big enough to introduce a new release) inside of Scanpy v1.8.2.
Because now I rerun my data and I get the UMAP like below,
![image](https://user-images.githubusercontent.com/75048821/149594142-fcd6b1d1-7b9a-4713-9850-8b2d86a1ff61.png)

but it looks like this one month ago, run by the same version of Scanpy v1.8.2 with the same coding.
![image](https://user-images.githubusercontent.com/75048821/149593173-fc6caf3d-09e4-4b92-89ad-8cdfc1173f3c.png)

**Comment by hyjforesight** [comment]
pytables 3.7.0 is incompatible with Windows. Installing pytables 3.6.1 solves the problem.
For the UMAP, it's quite weird. Whether I restart anaconda between installing individual packages plays the trick.
It should be done in this way.
```python
!pip install tables==3.6.1

!pip install scanpy[leiden]
!pip install -U scvelo
!pip install tqdm
!pip install ipywidgets
!pip install cellrank

close Edge

run anaconda powershell prompt (anaconda3) as admin
conda activate HYJ_py38
conda install -y -c anaconda cytoolz
pip install pyscenic

restart anaconda3

!pip install adjustText openpyxl
```
