### ISSUE TITLE
Merging anndata.obs structure with another data frame 

### ISSUE THREAD

**Issue by jayypaul** [scverse/scanpy#211]
Essentially my problem is this. I have another dataframe (df) that I won't to merge with anndata.obs, via matching indices. Except df is a smaller length than anndata.obs. But I want the indices in which there isn't new information for (those missing values in df), to just appear as NaN. 

I've tried many functions: merge, join, pd.concat, concatenate, etc; and have tried many different combinations of parameters but none are able to do this, even though merge and join have documentation stating they should be able to. However, if I left join, all the added info becomes NaN. If I right join, the all of the left dataframe (anndata.obs) becomes NaN. Inner makes an empty matrix, outer makes everything NaN. 

Does anybody have a simple trick for this?

**Comment by falexwolf** [comment]
Sorry for the late response. Have you solved the problem?

**Comment by jayypaul** [comment]
No problem, and yes I did thanks! That's why I closed the issue. There was a slight discrepancy between my merging indices.

**Comment by Yemch** [comment]
Hi,

I have a similar problem here. I want to know how to merge two different anndata if I do the filtering separately first. Anyone knows?

**Comment by LuckyMD** [comment]
Check out `AnnData.concatenate()` [here](https://anndata.readthedocs.io/en/latest/anndata.AnnData.concatenate.html). However, you can only concatenate if the anndata objects have the same `adata.var_names`. So gene filtering cannot be done separately.
