### ISSUE TITLE
Could you please consider including CellPhoneDB?

### ISSUE THREAD

**Issue by danli349** [scverse/scanpy#2117]
Could you please consider including CellPhoneDB (https://github.com/ventolab/CellphoneDB)?
Thanks
Dan

**Comment by LuckyMD** [comment]
Hi @danli349,

Check out [squidpy](https://github.com/theislab/squidpy), which is part of the scanpy ecosystem. That has a sped-up implementation of CellPhoneDB right [here](https://squidpy.readthedocs.io/en/stable/api/squidpy.gr.ligrec.html).

**Comment by hyjforesight** [comment]
What I can tell is that all people in the Theis Lab are amazing genii! They embed CytoTRACE, CellPhoneDB and many packages into their ecosystem.

**Comment by LuckyMD** [comment]
Thanks for the flowers (on behalf of the people who did a lot of the work, not me ^^), but it's also the developers of some of these packages, who are ensuring that their packages are directly accessible via this ecosystem. The scanpy ecosystem can only work if everyone is involved. Please feel free to contribute future tools you are working on as well.

**Comment by LuckyMD** [comment]
But I'm sure @michalk8, @giovp and @Marius1311 will like seeing the above post :)
