### ISSUE TITLE
error as using "sc.pp.regress_out(adata, ['n_counts', 'percent_mito'])"

### ISSUE THREAD

**Issue by chengarthur** [scverse/scanpy#212]
follow the normal pipeline and only meet problems when  i use the function "sc.pp.regress"

it works well on R
system is windows 8.1
and use annaconda to manage environment
python 3.6.6

OverflowError                             Traceback (most recent call last)
<ipython-input-21-c0d016811ded> in <module>()
----> 1 sc.pp.regress_out(adata, ['n_counts', 'percent_mito'])

~\AppData\Local\conda\conda\envs\scanpy\lib\site-packages\scanpy\preprocessing\simple.py in regress_out(adata, keys, n_jobs, copy)
    777         import multiprocessing
    778         pool = multiprocessing.Pool(n_jobs)
--> 779         res = pool.map_async(_regress_out_chunk, tasks).get(9999999)
    780         pool.close()
    781 

~\AppData\Local\conda\conda\envs\scanpy\lib\multiprocessing\pool.py in get(self, timeout)
    636 
    637     def get(self, timeout=None):
--> 638         self.wait(timeout)
    639         if not self.ready():
    640             raise TimeoutError

~\AppData\Local\conda\conda\envs\scanpy\lib\multiprocessing\pool.py in wait(self, timeout)
    633 
    634     def wait(self, timeout=None):
--> 635         self._event.wait(timeout)
    636 
    637     def get(self, timeout=None):

~\AppData\Local\conda\conda\envs\scanpy\lib\threading.py in wait(self, timeout)
    549             signaled = self._flag
    550             if not signaled:
--> 551                 signaled = self._cond.wait(timeout)
    552             return signaled
    553 

~\AppData\Local\conda\conda\envs\scanpy\lib\threading.py in wait(self, timeout)
    297             else:
    298                 if timeout > 0:
--> 299                     gotit = waiter.acquire(True, timeout)
    300                 else:
    301                     gotit = waiter.acquire(False)

OverflowError: timeout value is too large

update:-----------------------------------------------------------------------------------------------------

when i used the n_jobs= 1 as a paramters ,seems like i lack a module named patsy
oduleNotFoundError                       Traceback (most recent call last)
<ipython-input-22-6ea7e0dee435> in <module>()
----> 1 sc.pp.regress_out(adata, ['n_counts', 'percent_mito'],n_jobs = 1)

~\AppData\Local\conda\conda\envs\scanpy\lib\site-packages\scanpy\preprocessing\simple.py in regress_out(adata, keys, n_jobs, copy)
    781 
    782     else:
--> 783         res = list(map(_regress_out_chunk, tasks))
    784 
    785     # res is a list of vectors (each corresponding to a regressed gene column).

~\AppData\Local\conda\conda\envs\scanpy\lib\site-packages\scanpy\preprocessing\simple.py in _regress_out_chunk(data)
    798 
    799     responses_chunk_list = []
--> 800     import statsmodels.api as sm
    801     from statsmodels.tools.sm_exceptions import PerfectSeparationError
    802 

~\AppData\Local\conda\conda\envs\scanpy\lib\site-packages\statsmodels\api.py in <module>()
      3 from . import tools
      4 from .tools.tools import add_constant, categorical
----> 5 from . import regression
      6 from .regression.linear_model import OLS, GLS, WLS, GLSAR
      7 from .regression.recursive_ls import RecursiveLS

~\AppData\Local\conda\conda\envs\scanpy\lib\site-packages\statsmodels\regression\__init__.py in <module>()
----> 1 from .linear_model import yule_walker
      2 
      3 from statsmodels import PytestTester
      4 test = PytestTester()
      5 

~\AppData\Local\conda\conda\envs\scanpy\lib\site-packages\statsmodels\regression\linear_model.py in <module>()
     46                                           cache_readonly,
     47                                           cache_writable)
---> 48 import statsmodels.base.model as base
     49 import statsmodels.base.wrapper as wrap
     50 from statsmodels.emplike.elregress import _ELRegOpts

~\AppData\Local\conda\conda\envs\scanpy\lib\site-packages\statsmodels\base\model.py in <module>()
     13 from statsmodels.tools.sm_exceptions import ValueWarning, \
     14     HessianInversionWarning
---> 15 from statsmodels.formula import handle_formula_data
     16 from statsmodels.compat.numpy import np_matrix_rank
     17 from statsmodels.base.optimizer import Optimizer

~\AppData\Local\conda\conda\envs\scanpy\lib\site-packages\statsmodels\formula\__init__.py in <module>()
      3 
      4 
----> 5 from .formulatools import handle_formula_data

~\AppData\Local\conda\conda\envs\scanpy\lib\site-packages\statsmodels\formula\formulatools.py in <module>()
      1 from statsmodels.compat.python import iterkeys
      2 import statsmodels.tools.data as data_util
----> 3 from patsy import dmatrices, NAAction
      4 import numpy as np
      5 

ModuleNotFoundError: No module named 'patsy'

**Comment by falexwolf** [comment]
Can you try running with `n_jobs=1`?

**Comment by fidelram** [comment]
I am not so sure, but you may get that error when the matrix contains columns of only ceros. Did you do any filtering of the data before?

Fidel Ramírez

**Comment by chengarthur** [comment]
I didn't use any filtering before the pipeline, but I read the barcode and gene names from index and columns  of the data frame. and i have a cuff-off of the cell for my own


update——————————————
The calculation is depends on module "patsy" and it is not in the dependency list of scanpy or I have some problems with installing that package. 
After I reinstalled and updated  "pasty", problem fixed

**Comment by fidelram** [comment]
I could not find an import for `patsy` (I think is patsy and not pasty) in the scanpy repo. I think this module is required by other package, probably sklearn.
