### ISSUE TITLE
tl.rank_genes_group: object has no attribute 'dtype'

### ISSUE THREAD

**Issue by baj12** [scverse/scanpy#2121]
I am following the SCENIC protocol (https://github.com/aertslab/SCENICprotocol/blob/master/notebooks/PBMC10k_SCENIC-protocol-CLI.ipynb) with an admittedly different data set, but still using 10x data of similar type.

I have to admit that I am relatively new to the python world and don't know yet where to turn to... 
haven't found any way to debug any further I conclude that this is a scanpy issue, at a minimal level at the error reporting stage as the information doesn't help me track down what is wrong.

thanks for your time! 

adata

```
AnnData object with n_obs × n_vars = 4578 × 3389
    obs: 'nGene', 'nUMI', 'n_genes', 'percent_mito', 'n_counts', 'louvain', 'leiden'
    var: 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'log1p', 'hvg', 'pca', 'neighbors', 'umap', 'louvain', 'leiden', 'louvain_colors', 'rank_genes_groups'
    obsm: 'X_pca', 'X_umap', 'X_tsne'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'
```

 my adata.raw.X looks like this:

```
<4578x18247 sparse matrix of type '<class 'numpy.float32'>'
	with 9236127 stored elements in Compressed Sparse Row format>
```

adatat.X

```
array([[ 0.23202083,  0.07064813, -0.05003222, ...,  1.4681866 ,
        -0.21488723,  2.620106  ],
       [ 0.09879599,  0.03607919, -0.08120057, ..., -0.3384455 ,
        -0.19780253,  2.0771198 ],
       [-0.5213845 , -0.1292537 , -0.1755099 , ..., -0.23126683,
        -0.10592338,  0.02626752],
       ...,
       [ 2.4987383 , -0.14190508, -0.20776471, ..., -0.20877847,
        -0.10354204,  0.14313072],
       [ 0.1960011 ,  0.06290449, -0.07691702, ..., -0.34954828,
         2.5718384 ,  2.468825  ],
       [-0.53571457, -0.13106212, -0.20085879, ..., -0.21621887,
        -0.10943384,  0.05686853]], dtype=float32)
```

### Minimal code sample (that we can copy&paste without having any data)

```python
# find marker genes
sc.tl.rank_genes_groups(adata, 'louvain', method='t-test', reference = 'rest')
```

```pytb
ranking genes
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-50-04ed1c1ca569> in <module>
      1 # find marker genes
      2 #pdb.set_trace()
----> 3 sc.tl.rank_genes_groups(adata, 'louvain', method='t-test', reference = 'rest')
      4 sc.pl.rank_genes_groups(adata, n_genes=25, sharey=False)
      5 

/usr/local/lib/python3.8/site-packages/scanpy/tools/_rank_genes_groups.py in rank_genes_groups(adata, groupby, use_raw, groups, reference, n_genes, rankby_abs, pts, key_added, copy, method, corr_method, tie_correct, layer, **kwds)
    581     logg.debug(f'with sizes: {np.count_nonzero(test_obj.groups_masks, axis=1)}')
    582 
--> 583     test_obj.compute_statistics(
    584         method, corr_method, n_genes_user, rankby_abs, tie_correct, **kwds
    585     )

/usr/local/lib/python3.8/site-packages/scanpy/tools/_rank_genes_groups.py in compute_statistics(self, method, corr_method, n_genes_user, rankby_abs, tie_correct, **kwds)
    376             if self.stats is None:
    377                 idx = pd.MultiIndex.from_tuples([(group_name, first_col)])
--> 378                 self.stats = pd.DataFrame(columns=idx)
    379 
    380             if n_genes_user is not None:

/usr/local/lib/python3.8/site-packages/pandas/core/frame.py in __init__(self, data, index, columns, dtype, copy)
    433             )
    434         elif isinstance(data, dict):
--> 435             mgr = init_dict(data, index, columns, dtype=dtype)
    436         elif isinstance(data, ma.MaskedArray):
    437             import numpy.ma.mrecords as mrecords

/usr/local/lib/python3.8/site-packages/pandas/core/internals/construction.py in init_dict(data, index, columns, dtype)
    237             else:
    238                 nan_dtype = dtype
--> 239             val = construct_1d_arraylike_from_scalar(np.nan, len(index), nan_dtype)
    240             arrays.loc[missing] = [val] * missing.sum()
    241 

/usr/local/lib/python3.8/site-packages/pandas/core/dtypes/cast.py in construct_1d_arraylike_from_scalar(value, length, dtype)
   1438     else:
   1439         if not isinstance(dtype, (np.dtype, type(np.dtype))):
-> 1440             dtype = dtype.dtype
   1441 
   1442         if length and is_integer_dtype(dtype) and isna(value):

AttributeError: type object 'object' has no attribute 'dtype'
```

#### Versions

<details>

WARNING: If you miss a compact list, please try `print_header`!
The `sinfo` package has changed name and is now called `session_info` to become more discoverable and self-explanatory. The `sinfo` PyPI package will be kept around to avoid breaking old installs and you can downgrade to 0.3.2 if you want to use it without seeing this message. For the latest features and bug fixes, please install `session_info` instead. The usage and defaults also changed slightly, so please review the latest README at https://gitlab.com/joelostblom/session_info.
-----
anndata     0.7.4
scanpy      1.6.0
sinfo       0.3.4
-----
MulticoreTSNE       NA
PIL                 8.0.1
appnope             0.1.2
attr                20.3.0
backcall            0.2.0
cffi                1.14.4
cloudpickle         2.0.0
colorama            0.4.4
cycler              0.10.0
cython_runtime      NA
cytoolz             0.11.2
dask                2022.01.0
dateutil            2.8.1
decorator           4.4.2
dunamai             1.7.0
fsspec              2022.01.0
get_version         3.5.3
google              NA
h5py                2.10.0
idna                2.10
igraph              0.9.6
ipykernel           5.3.4
ipython_genutils    0.2.0
ipywidgets          7.6.5
jedi                0.17.2
jinja2              2.11.2
joblib              1.0.1
jsonschema          3.2.0
jupyter_server      1.13.3
kiwisolver          1.3.1
legacy_api_wrap     1.2
leidenalg           0.8.0
llvmlite            0.38.0
loompy              3.0.6
louvain             0.7.0
markupsafe          1.1.1
matplotlib          3.3.3
mpl_toolkits        NA
natsort             7.1.1
nbformat            5.0.8
numba               0.55.0
numexpr             2.7.3
numpy               1.21.5
numpy_groupies      0.9.13
packaging           21.3
pandas              1.0.4
parso               0.7.1
patsy               0.5.2
pexpect             4.8.0
pickleshare         0.7.5
pkg_resources       NA
prometheus_client   NA
prompt_toolkit      3.0.8
psutil              5.9.0
ptyprocess          0.6.0
pvectorc            NA
pycparser           2.20
pygments            2.7.2
pyparsing           2.4.7
pyrsistent          NA
pytz                2020.4
scipy               1.4.1
seaborn             0.11.2
send2trash          NA
setuptools_scm      NA
sitecustomize       NA
six                 1.14.0
sklearn             0.22.2.post1
statsmodels         0.13.0rc0
storemagic          NA
tables              3.7.0
tblib               1.7.0
terminado           0.9.1
texttable           1.6.4
tlz                 0.11.2
toolz               0.11.2
tornado             6.1
traitlets           5.0.5
typing_extensions   NA
umap                0.3.10
wcwidth             0.2.5
yaml                5.3.1
zmq                 20.0.0
-----
IPython             7.19.0
jupyter_client      6.1.7
jupyter_core        4.7.0
jupyterlab          3.2.8
notebook            6.1.5
-----
Python 3.8.12 (default, Oct 22 2021, 18:39:35) [Clang 13.0.0 (clang-1300.0.29.3)]
macOS-12.1-x86_64-i386-64bit
12 logical CPU cores, i386
-----
Session information updated at 2022-01-25 07:11

</details>

**Comment by ivirshup** [comment]
Thanks for the report!

Would you be able to try again with a fresh environment using up to date packages? There are some fairly old package versions in there, which might lead to the bug you're running into.

**Comment by baj12** [comment]
After my hard drive and computer crashed (which is why I respond so late) I was able to update my python env. So far it is working. Thanks a lot!
