### ISSUE TITLE
`sc.datasets.pbmc3k()` link no longer exists

### ISSUE THREAD

**Issue by jacobkimmel** [scverse/scanpy#2124]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [x] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

The URL specified for the included `pbmc3k` data is throwing a 404.

URL: https://falexwolf.me/data/pbmc3k_raw.h5ad

I happen to use this data for lots of unit and regression tests (probably not the best idea on my part). 

Is there by chance a backup location I could mirror the same object from?

### Minimal code sample (that we can copy&paste without having any data)

```python
import scanpy as sc
adata = sc.datasets.pbmc3k()
```

```pytb
...

    'http', request, response, code, msg, hdrs)
  File "/home/jacob/bin/anaconda/envs/scnym_public/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/jacob/bin/anaconda/envs/scnym_public/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/jacob/bin/anaconda/envs/scnym_public/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

#### Versions

-----
anndata     0.7.4
scanpy      1.8.2
sinfo       0.3.4
-----
PIL                 8.4.0
cycler              0.10.0
cython_runtime      NA
dateutil            2.8.1
google              NA
h5py                2.10.0
igraph              0.9.7
joblib              1.1.0
kiwisolver          1.3.2
leidenalg           0.8.0
llvmlite            0.32.1
louvain             0.7.0
matplotlib          3.4.3
mpl_toolkits        NA
natsort             7.1.1
numba               0.49.1
numexpr             2.7.3
numpy               1.18.2
packaging           21.0
pandas              1.0.4
pkg_resources       NA
pyparsing           2.4.7
pytz                2021.3
scipy               1.4.1
setuptools_scm      NA
six                 1.14.0
sklearn             0.22.2.post1
tables              3.6.1
texttable           1.6.4
typing_extensions   NA
wcwidth             0.2.5
yaml                5.3.1
zipp                NA
-----
Python 3.7.10 | packaged by conda-forge | (default, Oct 13 2021, 21:01:18) [GCC 9.4.0]
Linux-4.15.0-142-generic-x86_64-with-debian-buster-sid
16 logical CPU cores, x86_64
-----
Session information updated at 2022-01-28 10:52

</details>

**Comment by mbernste** [comment]
I am experiencing this issue as well (with `paul15`, which looks to hit the same URL)

**Comment by giovp** [comment]
same here, we are having CI failing in squidpy cause we use the dataset, pinging @falexwolf

**Comment by falexwolf** [comment]
I'm looking into it!

**Comment by falexwolf** [comment]
I'm sorry about the problem! It should be fixed, now! Please let me know if you continue to have problems.

I'll also look into an alternative long-term solution!

**Comment by Zethson** [comment]
@falexwolf maybe a scverse/scanpy figshare?

**Comment by falexwolf** [comment]
Yes! Let's get the topic of data sharing on an scverse meeting agenda! I'll follow up with @ivirshup!

**Comment by mbernste** [comment]
Thank you!

**Comment by ivirshup** [comment]
How are the download speeds/ hosting for figshare? Do they mirror to different regions? I recall some painful download times from Australia. It's also probably pretty stable.

Could also use `scverse.org` for permanent URIs?

**Comment by grst** [comment]
It's also possible to attach files as assets to github releases. That's what I do for scirpy, e.g. 
https://github.com/icbi-lab/scirpy/releases/tag/d0.1.0

**Comment by jacobkimmel** [comment]
You all are quick, thanks @falexwolf !

**Comment by giovp** [comment]
> How are the download speeds/ hosting for figshare? Do they mirror to different regions? I recall some painful download times from Australia. It's also probably pretty stable.

the datasets we have in figshar for squidpy are fast to access (europe at least) but also traffic is probably much less than pbmc3k() 😅

**Comment by Zethson** [comment]
I'll close this issue since it was rather specific. We had a longer discussion on this whole topic at the hackathon and are tracking this elsewhere
