### ISSUE TITLE
Omit colorbar in embedding plots

### ISSUE THREAD

**Issue by asistradition** [scverse/scanpy#2127]
- [x] Additional function parameters / changed functionality / changed defaults?
- [ ] New analysis tool: A simple analysis tool you have been using and are missing in `sc.tools`?
- [ ] New plotting function: A kind of plot you would like to seein `sc.pl`?
- [ ] External tools: Do you know an existing package that should go into `sc.external.*`?
- [ ] Other?

Categorical legends can be removed from embedding plots by passing the argument `'none`' to `legend_loc` (e.g. `sc.pp.umap(adata, color="CellType", legend_loc='none')`.

It would be useful if the drawn colorbar is omitted when plotting continuous data if `legend_loc='none'` is passed.

**Comment by ivirshup** [comment]
Fixed by https://github.com/scverse/scanpy/pull/1821
