### ISSUE TITLE
Downsample_counts

### ISSUE THREAD

**Issue by julie-jch** [scverse/scanpy#2131]
Hello Team,
        I'm using the **sc.pp.downsample_counts** function on my adata in hopes of downsampling it to match that of another dataset. Running the function doesn't  give any errors or seem to fail but when I check the total counts, there seems to be no change. 

I'm wondering if there is a problem with my application or there is more going on.

`sc.pp.downsample_counts(adata, total_counts=6900, random_state=0, replace=False, copy=False)`

My average total counts before and after running the function is 10000.
Any inputs would be greatly appreciated

**Comment by ivirshup** [comment]
Thanks for the report!

I'm having some trouble reproducing this:

```python 
import scanpy as sc
adata = sc.datasets.pbmc3k()
sc.pp.filter_genes(adata, min_counts=1)
adata.X.sum()
```

```
 6390631.0
```

```python
sc.pp.downsample_counts(adata, total_counts=6900, random_state=0, replace=False, copy=False))
adata.X.sum()
```

```
6900.0
```

Do you get the same results as me with the example I've provided? Could you also report some version info about your environment?

**Comment by julie-jch** [comment]
Thank you very much for assisting with this.
Running the above generates the same results like yours.

Environment
Name: pandas, Version: 1.3.2
Name: scanpy, Version: 1.8.1
Python, 3.8.11
pip Version: 22.0.3

This means there is something up with my anndata file. Are there any requirements in how the adata needs to be processed in order for this function to work?

**Comment by ivirshup** [comment]
X should only contain positive integer values? Not sure otherwise.

Could you show me the output of the example, but run with your object?

Could you also show what type `X` is and some of the values?

**Comment by julie-jch** [comment]
So my X actually contained negative values. I removed my _scanpy.pp.scale_ step and tried this downsampling step earlier in my pipeline and its working. Thanks for taking time to help with this.

**Comment by DRSEI** [comment]
Hi @julie-jch ,
I am having same issues.

`import scanpy as sc
adata = sc. read(“cxxxxxx”)
sc.pp.filter_genes(adata, min_counts=1)
adata.X.sum() `

-254678


How can I turn into positive value ?  How did you removed the sc.pp.scale step ? 


appreciate your input .
