### ISSUE TITLE
Pictures not shown in docs

### ISSUE THREAD

**Issue by WeilerP** [scverse/scanpy#2132]
## Description

There are some pictures which are not being rendered [here](https://scanpy.readthedocs.io/en/stable/tutorials.html) in the tutorial section of the docs.

**Comment by ivirshup** [comment]
@falexwolf, do you still have those? We can definitely put them in a static folder here

**Comment by falexwolf** [comment]
I'm sorry, I wasn't aware I had used so much of my private webspace for Scanpy all these years back.

I migrated from some legacy infra a week ago, without trackers to links to external resources.

I'll fix this current instance by fixing the URLs and make a PR to have a copy of these images in the static folder in the docs, effective for the next release.

**Comment by falexwolf** [comment]
The display of the images on the current site got fixed 20 min ago.

And here is the longterm solution: https://github.com/theislab/scanpy/pull/2134

**Comment by falexwolf** [comment]
Thank you, @Zethson!
