### ISSUE TITLE
Scanpy import error

### ISSUE THREAD

**Issue by molecularsensei** [scverse/scanpy#2138]
I am trying to import scanpy but I am running into an error:

Also, a bit of a noob to python in general, but I think I have most required things installed.

```python
import scanpy as sc
```
I am using Python 3.7 in a virtual environment (potato37)
The above code gives me the following error:

```pytb
InvalidVersion                            Traceback (most recent call last)
/tmp/ipykernel_4345/4007328772.py in <module>
  ----> 1 import scanpy as sc
2 import anndata
3 from scipy import io
4 from scipy.sparse import coo_matrix, csr_matrix
5 import numpy as np

/data/personal_folders/user/potato37/lib/python3.7/site-packages/scanpy/__init__.py in <module>
  12     # (start with settings as several tools are using it)
13     from ._settings import settings, Verbosity
---> 14     from . import tools as tl
15     from . import preprocessing as pp
16     from . import plotting as pl

/data/personal_folders/user/potato37/lib/python3.7/site-packages/scanpy/tools/__init__.py in <module>
  15 from ._leiden import leiden
16 from ._louvain import louvain
---> 17 from ._sim import sim
18 from ._score_genes import score_genes, score_genes_cell_cycle
19 from ._dendrogram import dendrogram

/data/personal_folders/user/potato37/lib/python3.7/site-packages/scanpy/tools/_sim.py in <module>
  21 from anndata import AnnData
22 
---> 23 from .. import _utils, readwrite, logging as logg
24 from .._settings import settings
25 from .._compat import Literal

/data/personal_folders/user/potato37/lib/python3.7/site-packages/scanpy/readwrite.py in <module>
  8 import pandas as pd
9 from matplotlib.image import imread
---> 10 import tables
11 import anndata
12 from anndata import (
  
  /data/personal_folders/user/potato37/lib/python3.7/site-packages/tables/__init__.py in <module>
    51 from .unimplemented import UnImplemented, Unknown
  52 from .expression import Expr
  ---> 53 from .tests import print_versions, test
  54 
  55 
  
  /data/personal_folders/user/potato37/lib/python3.7/site-packages/tables/tests/__init__.py in <module>
    7 """
      8 
----> 9 from tables.tests.common import print_versions
     10 from tables.tests.test_suite import test, suite

/data/personal_folders/user/potato37/lib/python3.7/site-packages/tables/tests/common.py in <module>
     18 from tables.req_versions import min_blosc_bitshuffle_version
     19 
---> 20 hdf5_version = Version(tb.hdf5_version)
     21 blosc_version = Version(tb.which_lib_version("blosc")[1])
     22 

/data/personal_folders/user/potato37/lib/python3.7/site-packages/packaging/version.py in __init__(self, version)
    264         match = self._regex.search(version)
    265         if not match:
--> 266             raise InvalidVersion(f"Invalid version: '{version}'")
    267 
    268         # Store the parsed out pieces of the version

InvalidVersion: Invalid version: '1.10.0-patch1'
```

Any help will be appreciated :)

**Comment by ivirshup** [comment]
Thanks for opening the issue.

It looks like a problem with pytables, which we are removing as a dependency since it's starting to have problems like this.

Are you able to update the installation of pytables? Otherwise, you could try a dev version of scanpy.

**Comment by FionaMoon** [comment]
I meet the same problem when I want to install scanpy on my new laptop.
I run the same commands as I used to do on my old computer , but failed to import scanpy.
I've tried re-install of pytables and it still doesn't work.

**Comment by molecularsensei** [comment]
> Thanks for opening the issue.
> 
> It looks like a problem with pytables, which we are removing as a dependency since it's starting to have problems like this.
> 
> Are you able to update the installation of pytables? Otherwise, you could try a dev version of scanpy.

Thank you for pointing out the issue with pytables. Tried a couple things and it works now.
I don't know how this matters. I uninstalled pytables > tried importing scanpy > doesn't work (says tables module not found, which is expected I guess). I reinstalled pytables - now it decides to work. I can't see how that makes a difference since I had the same pytables version before.

**Comment by eroell** [comment]
Just came across this - is this still relevant @FionaMoon, or has this been resolved with the updated scanpy versions? :)
Glad to hear it worked out in your case @molecularsensei!
