### ISSUE TITLE
Development install via conda does not work

### ISSUE THREAD

**Issue by fbnrst** [scverse/scanpy#2144]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [x] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

I clone the scanpy repository and I am on commit b69015e. I follow the instructions for a developmental install here:
https://scanpy.readthedocs.io/en/stable/installation.html#dev-install-instructions 

### Minimal code sample (that we can copy&paste without having any data)

```bash
pip install beni
beni pyproject.toml > environment.yml
conda env create -f environment.yml
```

this is the error I get

```
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - seaborn-split
```

#### `environment.yml`

Here is the content of `environment.yml` which contains the strange package `seaborn-split`. So maybe the issue is upstream with beni?

<details>

```
channels:
- conda-forge
dependencies:
- pip:
  - flit
  - bbknn
  - scanpydoc>=0.7.4
  - harmonypy
  - magic-impute>=2.0
  - cudf>=0.9
  - cuml>=0.9
  - cugraph>=0.9
  - scanorama
  - scrublet
- python>=3.7
- pip
- anndata>=0.7.4
- numpy>=1.17.0
- matplotlib-base>=3.1.2
- pandas>=0.21
- scipy>=1.4
- seaborn-split
- h5py>=2.10.0
- pytables
- tqdm
- scikit-learn>=0.22
- statsmodels>=0.10.0rc2
- patsy
- networkx>=2.3
- natsort
- joblib
- numba>=0.41.0
- umap-learn>=0.3.10
- packaging
- sinfo
- setuptools-scm
- black>=20.8b1
- docutils
- sphinx<4.2,>=4.1
- sphinx_rtd_theme>=0.3.1
- python-igraph
- leidenalg
- louvain!=0.6.2,>=0.6
- scikit-misc>=0.1.3
- pytest>=4.4
- pytest-nunit
- dask-core!=2.17.0
- fsspec
- zappy
- - zarr
- profimp
- flit-core
name: scanpy
```

</details>

**Comment by ivirshup** [comment]
Huh, that is weird. Also weird that it's including every optional dependency by default. Any chance you know if there's a way to not do that?

**Comment by fbnrst** [comment]
seems like the `--deps` flag can be used to select dependencies. Default is all dependencies.

```bash
$ beni --deps production pyproject.toml
channels:
- conda-forge
dependencies:
- pip:
  - flit
- python>=3.7
- pip
- anndata>=0.7.4
- numpy>=1.17.0
- matplotlib-base>=3.1.2
- pandas>=0.21
- scipy>=1.4
- seaborn-split
- h5py>=2.10.0
- pytables
- tqdm
- scikit-learn>=0.22
- statsmodels>=0.10.0rc2
- patsy
- networkx>=2.3
- natsort
- joblib
- numba>=0.41.0
- umap-learn>=0.3.10
- packaging
- sinfo
name: scanpy
```

**Comment by fbnrst** [comment]
and `beni` makes use of these name mappings:
https://raw.githubusercontent.com/regro/cf-graph-countyfair/master/mappings/pypi/name_mapping.yaml
and there it is:
```
- conda_name: seaborn-split
  import_name: seaborn
  mapping_source: regro-bot
  pypi_name: seaborn
```
so, this seems to be an upstream issue of beni then.

**Comment by flying-sheep** [comment]
upstream, let’s follow there
