### ISSUE TITLE
Error with sc.pl.highest_expr_genes() ; 'SparseDataset' object has no attribute 'sum'

### ISSUE THREAD

**Issue by Nishant-Gupta-17** [scverse/scanpy#2147]
After going through the comment, _Originally posted by @LuckyMD in https://github.com/theislab/scanpy/issues/220#issuecomment-408332060_ , I have opened this issue.

I am facing problem with `sc.pl.highest_expr_genes(adata_orig, n_top=20)` as well. Attaching some details:
I started by reading in the file as:

`adata_orig = sc.read_h5ad('covid_portal_210320_with_raw.h5ad', backed = 'r')`

After printing the `adata_orig` object, i get the following output:

```
AnnData object with n_obs × n_vars = 647366 × 24929 backed at 'covid_portal_210320_with_raw.h5ad'
    obs: 'sample_id', 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'full_clustering', 'initial_clustering', 'Resample', 'Collection_Day', 'Sex', 'Age_interval', 'Swab_result', 'Status', 'Smoker', 'Status_on_day_collection', 'Status_on_day_collection_summary', 'Days_from_onset', 'Site', 'time_after_LPS', 'Worst_Clinical_Status', 'Outcome', 'patient_id'
    var: 'feature_types'
    uns: 'hvg', 'leiden', 'neighbors', 'pca', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    layers: 'raw'
```

After this, when I tried running the command:
`sc.pl.highest_expr_genes(adata_orig, n_top=20, )`

I get the following output:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-22-c4ab6dadfa42> in <module>
----> 1 sc.pl.highest_expr_genes(adata_orig )

C:\ProgramData\Anaconda3\lib\site-packages\scanpy\plotting\_qc.py in highest_expr_genes(adata, n_top, show, save, ax, gene_symbols, log, **kwds)
     65 
     66     # compute the percentage of each gene per cell
---> 67     norm_dict = normalize_total(adata, target_sum=100, inplace=False)
     68 
     69     # identify the genes with the highest mean

C:\ProgramData\Anaconda3\lib\site-packages\scanpy\preprocessing\_normalization.py in normalize_total(adata, target_sum, exclude_highly_expressed, max_fraction, key_added, layer, layers, layer_norm, inplace, copy)
    174         counts_per_cell = X[:, gene_subset].sum(1)
    175     else:
--> 176         counts_per_cell = X.sum(1)
    177     start = logg.info(msg)
    178     counts_per_cell = np.ravel(counts_per_cell)

AttributeError: 'SparseDataset' object has no attribute 'sum'
```
And when I run the command:
`type(adata_orig.X)`
I get the output as:
`anndata._core.sparse_dataset.SparseDataset`

After reading your comment, I feel that earlier the scanpy module was expecting the sparse dataset as the input, but you have changed it to expect the dense format , and maybe that's the reason for this error? I am just two days into the world of scanpy and any help would be highly appreciated, in order to make this error go away.

Also, to help you in debugging, I'd like to mention that the raw data in this dataset is present in the layer, which has the name 'raw' and the adata_orig.raw is set to null as of now. and when i try to run : `adata_orig.layers['raw'].sum(1)` it runs with no error. While running: `adata_orig.X.sum(1)` gives me the error as : 
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-23-951a31c71c45> in <module>
----> 1 adata_orig.X.sum(1)

AttributeError: 'SparseDataset' object has no attribute 'sum'
```

PS: I downloaded this` .h5ad` file from a published research paper to perform some analysis over it, would be happy to provide you the link to same if required. 

Also this is the environment that I am working in:
`scanpy==1.8.2 anndata==0.7.8 umap==0.5.2 numpy==1.20.1 scipy==1.6.2 pandas==1.2.4 scikit-learn==0.24.1 statsmodels==0.12.2 python-igraph==0.9.1 pynndescent==0.5.6`

Hello @LuckyMD, tagging you for just in case you might be knowing the resolution.

**Comment by ivirshup** [comment]
Thanks for opening an issue!

Many of the function in scanpy do not support being applied on a backed anndata. `highly_variable_genes` hasn't had support for out of core computation implemented, so it errors. Better out of core support is something we're working for.

Is it possible to load `X` into memory here?

**Comment by Nishant-Gupta-17** [comment]
Hello @ivirshup , Thanks for your reply. I figured that this might be an issue due to the anndata being read in backed mode. Although the file is large (7 gb in .h5ad format, and as soon as it gets read in memory, it blows up to 28 gb), but for now I have utilized a larger machine for performing my eda, and converted the sparse matrix to a dense one . Thanks for your clarification !
