### ISSUE TITLE
ValueError: h5 contains more than one genome, Available genomes are columns in the h5

### ISSUE THREAD

**Issue by johnsolk** [scverse/scanpy#2149]
Hello! This might seem like a basic question, but when I try to import the molecule_info.h5 file from this dataset:

https://cf.10xgenomics.com/samples/cell-exp/6.0.0/SC3_v3_NextGem_DI_Nuclei_5K_Multiplex/SC3_v3_NextGem_DI_Nuclei_5K_Multiplex_count_raw_molecule_info.h5

https://www.10xgenomics.com/resources/datasets/5-k-mouse-e-18-combined-cortex-hippocampus-and-subventricular-zone-nuclei-3-1-standard-6-0-0 

Using this function, 

```
scanpy.read_10x_h5(filename, genome=None, gex_only=True, backup_url=None)
```

I get the following error, 
```
ValueError: 'SC3_v3_NextGem_DI_Nuclei_5K_Multiplex_count_raw_molecule_info.h5' contains more than one genome. For legacy 10x h5 files you must specify the genome if more than one is present. Available genomes are: ['barcode_idx', 'barcode_info', 'barcodes', 'count', 'feature_idx', 'features', 'gem_group', 'library_idx', 'library_info', 'metrics_json', 'umi', 'umi_type']
```
and I don't know how to fix this. The dataset is only from mouse. This is not a legacy h5 file. The data are output from CR v6.0.0. Can you please assist? 

The "available genomes" suggested in the error message are not genome, but columns in the h5. Ideally, I want to import all of these. Are we really only allowed to select 1? Even selecting one, does not seem fix the problem. 

```
h5_info = scanpy.read_10x_h5(molecule_info_file,genome='umi_type')
```
```
TypeError: node ``/umi_type`` is not a group
```

- [X ] I have checked that this issue has not already been reported.
- [X ] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

### Minimal code sample (that we can copy&paste without having any data)

```python
h5_info = scanpy.read_10x_h5(molecule_info_file, backup_url="https://cf.10xgenomics.com/samples/cell-exp/6.0.0/SC3_v3_NextGem_DI_Nuclei_5K_Multiplex/SC3_v3_NextGem_DI_Nuclei_5K_Multiplex_count_raw_molecule_info.h5")
```

```pytb
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-2e1cefb9ad47> in <module>
----> 1 h5_info = scanpy.read_10x_h5(molecule_info_file)

~/miniconda3/envs/jupyter.py3/lib/python3.9/site-packages/scanpy/readwrite.py in read_10x_h5(filename, genome, gex_only, backup_url)
    194             adata = adata.copy()
    195     else:
--> 196         adata = _read_legacy_10x_h5(filename, genome=genome, start=start)
    197     return adata
    198 

~/miniconda3/envs/jupyter.py3/lib/python3.9/site-packages/scanpy/readwrite.py in _read_legacy_10x_h5(filename, genome, start)
    207             if not genome:
    208                 if len(children) > 1:
--> 209                     raise ValueError(
    210                         f"'{filename}' contains more than one genome. For legacy 10x h5 "
    211                         "files you must specify the genome if more than one is present. "

ValueError: 'SC3_v3_NextGem_DI_Nuclei_5K_Multiplex_count_raw_molecule_info.h5' contains more than one genome. For legacy 10x h5 files you must specify the genome if more than one is present. Available genomes are: ['barcode_idx', 'barcode_info', 'barcodes', 'count', 'feature_idx', 'features', 'gem_group', 'library_idx', 'library_info', 'metrics_json', 'umi', 'umi_type']
```

#### Versions

<details>

1.8.2

</details>

**Comment by ivirshup** [comment]
Thanks for the report!

`scanpy.read_10x_h5` is expecting the files for the count matrices, not the UMI info. So it's throwing a non-sensical error.

`read_10x_h5` is expecting files like `filtered_feature_bc_matrix.h5` or `raw_feature_bc_matrix_h5.h5`. For example:

https://cf.10xgenomics.com/samples/cell-exp/6.0.0/SC3_v3_NextGem_DI_Nuclei_5K_Multiplex/SC3_v3_NextGem_DI_Nuclei_5K_Multiplex_count_raw_feature_bc_matrix.h5

**Comment by johnsolk** [comment]
I see. Thanks, @ivirshup ! Is there any possibility of a new function in scanpy to read the molecule_info.h5 file, analogous to the DropletUtils function, [read10xMolInfo](https://rdrr.io/github/MarioniLab/DropletUtils/man/read10xMolInfo.html) ?

**Comment by ivirshup** [comment]
I'm not sure. Someone would have to propose functionality to go along with it. I also can't remember off the top of my head if there is `DropletUtils` like functionality in python already.

But it should be fairly straightforward to get the data out of those files yourself. For example, to get something like the `data` output of `DropletUtils` you could do:

```python
import h5py
import pandas as pd

PTH = "path/to/outs/molecule_info.h5"

def read_data(f: h5py.File) -> pd.DataFrame:
    data = {}
    columns = ["umi", "gem_group", "feature_idx", "reads"]
    data["barcode"] = pd.Categorical.from_codes(f["barcode_idx"][:], f["barcodes"].asstr()[:])
    for k in ["umi", "gem_group", "feature_idx", "count"]:
        data[k] = f[k][:]
    return pd.DataFrame(data)

with h5py.File(PTH) as f:
    data = read_data(f)
