### ISSUE TITLE
How to control/normalize for variability among samples?

### ISSUE THREAD

**Issue by FADHLyemen** [scverse/scanpy#2155]
...
Hi 
if samples contribute a different number of cells to my object, how to control for variability among samples? 
How to make sure that any difference between conditions I found is caused by biology and not because of samples variation? 

downsampling, upsampling, bootstrapping, robustness test 

Appreciate any feedback and any references for this issue

![image](https://user-images.githubusercontent.com/23288387/155648374-f0d6178f-7024-4ecd-88c0-37547c5e7e19.png)

**Comment by Zethson** [comment]
Dear @FADHLyemen 

we primarily use the issue tracker for development issues. I would like to kindly point you towards the Discourse: https://scanpy.discourse.group/
