### ISSUE TITLE
How can I export umap location csv file（Barcodes，X,Y）from AnnData object after sc.tl.umap？

### ISSUE THREAD

**Issue by mabaoweireadingene** [scverse/scanpy#2171]
- [ ] I have checked that this issue has not already been reported.
- [ ] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.
How can I export umap location csv file（Barcodes，X,Y）from AnnData object after sc.tl.umap？
thanks
---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can copy&paste without having any data)

```python
# Your code here
```

```pytb
[Paste the error output produced by the above code here]
```

#### Versions

<details>

[Paste the output of scanpy.logging.print_versions() leaving a blank line after the details tag]

</details>

**Comment by mabaoweireadingene** [comment]
Besides can i import other  umap location csv into AnnData object which I conducting？

**Comment by ivirshup** [comment]
For export, something like:

```python
pd.DataFrame(adata.obsm["X_umap"], index=adata.obs_names).write_table(...)
```

For import, something like:

```python
adata.obsm[key] = pd.read_table("file.tsv")
```

This is probably generally a better question for the discourse forum: https://discourse.scverse.org
