### ISSUE TITLE
UMAP not producing sensible results on tutorial example. 

### ISSUE THREAD

**Issue by markddesimone** [scverse/scanpy#2178]
- [ x] I have checked that this issue has not already been reported.
- [x ] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can copy&paste without having any data)

This is exactly the code on https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html using the dataset downloaded per the instructions. The umap step does not produce the correct result. tsne however produces sensible results.
```python
import numpy as np
import pandas as pd
import scanpy as sc

sc.settings.verbosity = 3             # verbosity: errors (0), warnings (1), info (2), hints (3)
sc.logging.print_header()
sc.settings.set_figure_params(dpi=80, facecolor='white')

results_file = 'write/pbmc3k.h5ad'  # the file that will store the analysis results

adata = sc.read_10x_mtx(
    'data/filtered_gene_bc_matrices/hg19/',  # the directory with the `.mtx` file
    var_names='gene_symbols',                # use gene symbols for the variable names (variables-axis index)
    cache=True)           

adata.var_names_make_unique()  # this is unnecessary if using `var_names='gene_ids'` in `sc.read_10x_mtx`

sc.pl.highest_expr_genes(adata, n_top=20, )

sc.pp.filter_cells(adata, min_genes=200)
sc.pp.filter_genes(adata, min_cells=3)

adata.var['mt'] = adata.var_names.str.startswith('MT-')  # annotate the group of mitochondrial genes as 'mt'
sc.pp.calculate_qc_metrics(adata, qc_vars=['mt'], percent_top=None, log1p=False, inplace=True)

sc.pl.violin(adata, ['n_genes_by_counts', 'total_counts', 'pct_counts_mt'],
             jitter=0.4, multi_panel=True)

sc.pl.scatter(adata, x='total_counts', y='pct_counts_mt')
sc.pl.scatter(adata, x='total_counts', y='n_genes_by_counts')

adata = adata[adata.obs.n_genes_by_counts < 2500, :]
adata = adata[adata.obs.pct_counts_mt < 5, :]

sc.pp.normalize_total(adata, target_sum=1e4)

sc.pp.log1p(adata)

sc.pp.highly_variable_genes(adata, min_mean=0.0125, max_mean=3, min_disp=0.5)

sc.pl.highly_variable_genes(adata)

adata.raw = adata

adata = adata[:, adata.var.highly_variable]

sc.pp.regress_out(adata, ['total_counts', 'pct_counts_mt'])

sc.pp.scale(adata, max_value=10)

sc.tl.pca(adata, svd_solver='arpack')

sc.pl.pca(adata, color='CST3')

sc.pl.pca_variance_ratio(adata, log=True)

adata.write(results_file)

sc.pp.neighbors(adata, n_neighbors=10, n_pcs=40)

sc.tl.umap(adata)

sc.pl.umap(adata, color=['CST3', 'NKG7', 'PPBP'])

sc.tl.tsne(adata)

sc.pl.tsne(adata, color=['CST3', 'NKG7', 'PPBP'])


```

![image](https://user-images.githubusercontent.com/5612966/158490622-dae4e20c-1e60-4f27-a844-9235fd77c0ea.png)

I would expect a umap like the sample on the website:
![image](https://user-images.githubusercontent.com/5612966/158491669-e4e256c9-edfd-4cd5-9390-3c09cac540bc.png)

I was having this problem with my own SC data:
![image](https://user-images.githubusercontent.com/5612966/158490800-bd710bb1-4fba-4e4f-be2d-d878ebb76d4a.png)

Therefore I reproduced the problem using the tutorial. I installed scanpy yesterday using:
```sh
conda install -c bioconda scanpy
```

#### Versions

<details>

WARNING: If you miss a compact list, please try `print_header`!
-----
anndata     0.7.8
scanpy      1.7.2
sinfo       0.3.1
-----
PIL                         9.0.1
anndata                     0.7.8
annoy                       NA
asttokens                   NA
backcall                    0.2.0
beta_ufunc                  NA
binom_ufunc                 NA
cffi                        1.14.5
colorama                    0.4.4
cycler                      0.10.0
cython_runtime              NA
dateutil                    2.8.2
debugpy                     1.5.1
decorator                   5.1.1
deepMNN                     NA
defusedxml                  0.7.1
dunamai                     1.10.0
entrypoints                 0.4
executing                   0.8.3
fbpca                       NA
get_version                 3.5.4
h5py                        3.6.0
hypergeom_ufunc             NA
intervaltree                NA
ipykernel                   6.9.2
ipython_genutils            0.2.0
ipywidgets                  7.6.5
jedi                        0.18.1
joblib                      1.1.0
kiwisolver                  1.3.2
legacy_api_wrap             0.0.0
llvmlite                    0.38.0
matplotlib                  3.3.2
matplotlib_inline           NA
metrics                     NA
mpl_toolkits                NA
natsort                     8.1.0
nbinom_ufunc                NA
numba                       0.55.1
numexpr                     2.8.0
numpy                       1.21.5
packaging                   21.3
pandas                      1.4.1
parso                       0.8.3
patsy                       0.5.2
pexpect                     4.8.0
pickleshare                 0.7.5
pkg_resources               NA
prompt_toolkit              3.0.27
psutil                      5.9.0
ptyprocess                  0.7.0
pure_eval                   0.2.2
pycparser                   2.21
pydev_ipython               NA
pydevconsole                NA
pydevd                      2.6.0
pydevd_concurrency_analyser NA
pydevd_file_utils           NA
pydevd_plugins              NA
pydevd_tracing              NA
pygments                    2.11.2
pynndescent                 0.5.6
pyparsing                   3.0.7
pytz                        2021.3
scanpy                      1.7.2
scipy                       1.8.0
seaborn                     0.11.2
setuptools                  60.9.3
setuptools_scm              NA
sinfo                       0.3.1
six                         1.16.0
sklearn                     0.23.2
sortedcontainers            2.4.0
sphinxcontrib               NA
stack_data                  0.2.0
statsmodels                 0.13.2
tables                      3.7.0
torch                       1.11.0
tornado                     6.1
tqdm                        4.63.0
traitlets                   5.1.1
typing_extensions           NA
umap                        0.5.2
wcwidth                     0.2.5
zipp                        NA
zmq                         22.3.0
-----
IPython             8.1.1
jupyter_client      7.1.2
jupyter_core        4.9.2
notebook            6.4.9
-----
Python 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:22:27) [GCC 9.3.0]
Linux-5.4.0-104-generic-x86_64-with-glibc2.10
24 logical CPU cores, x86_64
-----
Session information updated at 2022-03-15 16:53

</details>

**Comment by ivirshup** [comment]
I think I see the issue here. The bioconda distribution of scanpy is out of date and unsupported, please install it from condo-forge instead:

https://scanpy.readthedocs.io/en/latest/installation.html#anaconda

**Comment by markddesimone** [comment]
That was it, thank you!
