### ISSUE TITLE
How to specify color for each group with pl.tsne()

### ISSUE THREAD

**Issue by fbrundu** [scverse/scanpy#218]
Hi all,
I want to plot a tSNE plot with categorical groups.
I have already a palette that I need to use to maintain consistency across figures.
I tried to use the method `pl.tsne()` as the following:

```
sc.pl.tsne(adata_p, color='signature', size=15, palette=pal, groups=['Group1', 'Group2', 'Group3'])
```

Originally I set up a dictionary to use as a palette (using Seaborn), in particular it would be:

```
{'Group1': (0.06988755691850207, 0.2682780410742496, 0.405798717591302), 'Group2': (1.0, 0.4749019607843138, 0.4647058823529413), 'Group3': (0.8049999999999999, 0.8049999999999999, 0.8049999999999999)}
```

However, scanpy does not support a dictionary as argument for `palette` so I only used the values. But unexpectedly, the colors are assigned to each group not in alphabetic order (based on the name of the group). I can I assign directly the colors to each group, or make scanpy use the colors I want?

I tried to look into `adata.uns['signature']` but it contains only the list of the colors so I don't know exactly how to define it in the right order.

In particular, I noticed that the palette is in the right order, while the groups are not sorted in alphabetic order.

Thanks,
Francesco

**Comment by wflynny** [comment]
Won't this automatically lexicographically sort, among other things, the order of plot legend labels for all scatter plots now?  That is probably not desirable as default behavior;  the order of the categories should be defined at the data object level, and not altered during plotting.

There should instead maybe be a utility function to properly assigns a palette to your labels prior to plotting, then the actual plotting functionality can stay the same.

**Comment by fbrundu** [comment]
@wflynny actually I discovered that the behavior is a little more subtle: they are ordered based on the categories order.
Usually this is lexicographically. However, if you produce categories through [pandas.cut()](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.cut.html) they are ordered following the original bins - not lexicographically. I think that this original behavior is the more natural, so I think I'll close this issue and the linked PR.

Thanks,
Francesco

**Comment by falexwolf** [comment]
Dear @fbrundu,

very sorry for the late response. I took a couple of days off with the family.

Everything is dictated by the order in `.obs['mycategorical'].cat.categories`. If you're starting off from a string `.obs['mystring']` annotation, then this will default to `natsorted` categories. If you pandas `.reorder_categories` then this will be reflected, too.

Now, in `AnnData`, we have the additional possibility to store colors for each category. The corresponding array matches `.obs['mycategorical'].cat.categories` just that instead of the category names, it stores the colors.

Let me know if this clears things up for you.

**Comment by fbrundu** [comment]
No worries and thanks for the clarification.
I initially reworked part of the code because I thought the order was not reproducible. But then I discovered that it was like that because scanpy was using pandas categories, which is the correct implementation in my opinion.
