### ISSUE TITLE
Data to use for Cluster Markers

### ISSUE THREAD

**Issue by ThomasThaewel** [scverse/scanpy#2180]
Dear scanpy Team,
I am a little bit confused regarding the counts, that are used for computing marker genes for clusters for example. In your publication :Current best practices in single-cell RNA-seq analysis: a tutorial, in Table 1 you recommend to use raw data for this instance but in the implementation of rank_gene_groups and in your notebooks for the publication, log normalized counts were used for this purpose if I'm not mistaken. Could you maybe clarify what the best practice would be? 
Thank you so much!

**Comment by LuckyMD** [comment]
Hi @ThomasThaewel,
In the current best-practices paper the recommendation is to use "measured data" as input for marker gene detection. This includes both raw, normalized, and log-normalized data formats. If you are using a count modelling approach for differential expression analysis (e.g., negative binomial, poisson), then you should use raw data (not-normalized) and include size factors in the model. For non-parametric approaches like the ones implemented in `sc.tl.rank_genes_groups()` log-normalized data is better.

Hope that clarifies things.

**Comment by ThomasThaewel** [comment]
Awesome thank you so much for the response! Helps me out a lot
