### ISSUE TITLE
Unable to assign .raw object after subsetting rows

### ISSUE THREAD

**Issue by aditya-sarkar441** [scverse/scanpy#2188]
- [ Yes] I have checked that this issue has not already been reported.
- [ Yes] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can copy&paste without having any data)

```python
ncont =  ncont[ncont.obs.pct_counts_mt < 5, :]
ncont.raw = ncont
```

```pytb
[TypeError: cannot unpack non-iterable NoneType object]
```

#### Versions

scanpy==1.8.2 anndata==0.7.8 umap==0.5.2 numpy==1.21.5 scipy==1.7.1 pandas==1.3.2 scikit-learn==0.24.2 statsmodels==0.13.2 python-igraph==0.9.9 pynndescent==0.5.6

<details>

[WARNING: If you miss a compact list, please try `print_header`!
The `sinfo` package has changed name and is now called `session_info` to become more discoverable and self-explanatory. The `sinfo` PyPI package will be kept around to avoid breaking old installs and you can downgrade to 0.3.2 if you want to use it without seeing this message. For the latest features and bug fixes, please install `session_info` instead. The usage and defaults also changed slightly, so please review the latest README at https://gitlab.com/joelostblom/session_info.
-----
anndata     0.7.8
scanpy      1.8.2
sinfo       0.3.4
-----
PIL                 8.3.1
anyio               NA
attr                21.2.0
babel               2.9.1
backcall            0.2.0
beta_ufunc          NA
binom_ufunc         NA
celltypist          0.2.0
certifi             2021.05.30
cffi                1.14.6
charset_normalizer  2.0.4
cycler              0.10.0
cython_runtime      NA
dateutil            2.8.2
decorator           5.0.9
defusedxml          0.7.1
entrypoints         0.3
h5py                3.3.0
idna                3.2
igraph              0.9.9
ipykernel           6.2.0
ipython_genutils    0.2.0
jedi                0.18.0
jinja2              3.0.1
joblib              1.0.1
json5               NA
jsonschema          3.2.0
jupyter_server      1.10.2
jupyterlab_server   2.7.1
kiwisolver          1.3.1
leidenalg           0.8.9
llvmlite            0.38.0
markupsafe          2.0.1
matplotlib          3.4.3
matplotlib_inline   NA
mpl_toolkits        NA
natsort             8.1.0
nbclassic           NA
nbformat            5.1.3
nbinom_ufunc        NA
numba               0.55.1
numexpr             2.8.1
numpy               1.21.5
packaging           21.3
pandas              1.3.2
parso               0.8.2
pexpect             4.8.0
pickleshare         0.7.5
pkg_resources       NA
prometheus_client   NA
prompt_toolkit      3.0.19
ptyprocess          0.7.0
pvectorc            NA
pycparser           2.20
pyexpat             NA
pygments            2.10.0
pynndescent         0.5.6
pyparsing           2.4.7
pyrsistent          NA
pytz                2021.1
requests            2.26.0
scipy               1.7.1
seaborn             0.11.2
send2trash          NA
six                 1.16.0
sklearn             0.24.2
sniffio             1.2.0
statsmodels         0.13.2
storemagic          NA
tables              3.7.0
terminado           0.11.1
texttable           1.6.4
tornado             6.1
tqdm                4.63.0
traitlets           5.0.5
umap                0.5.2
urllib3             1.26.6
wcwidth             0.2.5
websocket           1.2.1
zmq                 22.2.1
-----
IPython             7.26.0
jupyter_client      6.1.12
jupyter_core        4.7.1
jupyterlab          3.1.7
notebook            6.4.3
-----
Python 3.9.6 (default, Aug 18 2021, 11:08:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Linux-3.10.0-1160.41.1.el7.x86_64-x86_64-with-glibc2.17
36 logical CPU cores, x86_64
-----
Session information updated at 2022-03-21 23:04]

</details>

**Comment by Zethson** [comment]
Please post the content of `ncont[ncont.obs.pct_counts_mt < 5, :]`. Is it None?

**Comment by aditya-sarkar441** [comment]
No, it was not none. 
However, I fixed the issue. Thanks :)
