### ISSUE TITLE
Jupyter Notebook vs Python/PyCharm

### ISSUE THREAD

**Issue by hansen7** [scverse/scanpy#2189]
Hi, there.

I am following the tutorial [here](https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html), it works perfectly with Jupyter Notebook, but I do encounter the following errors when running the code in command line or PyCharm.

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

### Minimal code sample (that we can copy&paste without having any data)

from https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html
```python
adata.var['mt'] = adata.var_names.str.startswith('MT-')
sc.pp.calculate_qc_metrics(adata, qc_vars=['mt'], percent_top=None, log1p=False, inplace=True)
```

```pytb
TypeError: calculate_qc_metrics() got an unexpected keyword argument 'log1p'
```

#### Versions

<details>

[Paste the output of scanpy.logging.print_versions() leaving a blank line after the details tag]

</details>

**Comment by Zethson** [comment]
Hi,

As requested in the issue template, what scanpy versions are you running?
Thanks.

**Comment by hansen7** [comment]
Thanks, I am running the version of `1.4.5.1`

**Comment by Zethson** [comment]
> Thanks, I am running the version of `1.4.5.1`

Assuming that it is one of 1.4.1 or 1.5.1 I would suggest that you upgrade to the latest scanpy version. What you are using is quite old. If the problem still occurs we can discuss it further.
