### ISSUE TITLE
Error in sc.pp.highly_variable_genes function

### ISSUE THREAD

**Issue by aditya-sarkar441** [scverse/scanpy#2193]
- [ Yes] I have checked that this issue has not already been reported.
- [ Yes] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can copy&paste without having any data)

```python
sc.pp.highly_variable_genes(
    ncase,
    n_top_genes=3000,
    # subset=True, # to automatically subset to the 4000 genes
    layer="counts",
    flavor="seurat"
)
```

```pytb
ValueError: cannot specify integer `bins` when input data contains infinity
```

#### Versions

<details>

WARNING: If you miss a compact list, please try `print_header`!
The `sinfo` package has changed name and is now called `session_info` to become more discoverable and self-explanatory. The `sinfo` PyPI package will be kept around to avoid breaking old installs and you can downgrade to 0.3.2 if you want to use it without seeing this message. For the latest features and bug fixes, please install `session_info` instead. The usage and defaults also changed slightly, so please review the latest README at https://gitlab.com/joelostblom/session_info.
-----
anndata     0.7.8
scanpy      1.8.2
sinfo       0.3.4
-----
PIL                                         8.3.1
aa8f2297d25b4dc6fd3d98411eb3ba53823c4f42    NA
absl                                        NA
anyio                                       NA
astunparse                                  1.6.3
attr                                        21.2.0
babel                                       2.9.1
backcall                                    0.2.0
beta_ufunc                                  NA
binom_ufunc                                 NA
celltypist                                  0.2.0
certifi                                     2021.05.30
cffi                                        1.14.6
charset_normalizer                          2.0.4
cycler                                      0.10.0
cython_runtime                              NA
dateutil                                    2.8.2
decorator                                   5.0.9
defusedxml                                  0.7.1
entrypoints                                 0.3
et_xmlfile                                  1.1.0
flatbuffers                                 2.0
gast                                        0.5.3
google                                      NA
h5py                                        3.3.0
idna                                        3.2
igraph                                      0.9.9
ipykernel                                   6.2.0
ipython_genutils                            0.2.0
jedi                                        0.18.0
jinja2                                      3.0.1
joblib                                      1.0.1
json5                                       NA
jsonschema                                  3.2.0
jupyter_server                              1.10.2
jupyterlab_server                           2.7.1
keras                                       2.8.0
keras_preprocessing                         1.1.2
kiwisolver                                  1.3.1
leidenalg                                   0.8.9
llvmlite                                    0.38.0
louvain                                     0.7.1
markupsafe                                  2.0.1
matplotlib                                  3.4.3
matplotlib_inline                           NA
mpl_toolkits                                NA
natsort                                     8.1.0
nbclassic                                   NA
nbformat                                    5.1.3
nbinom_ufunc                                NA
numba                                       0.55.1
numexpr                                     2.8.1
numpy                                       1.21.5
openpyxl                                    3.0.9
opt_einsum                                  v3.3.0
packaging                                   21.3
pandas                                      1.3.2
parso                                       0.8.2
pexpect                                     4.8.0
pickleshare                                 0.7.5
pkg_resources                               NA
prometheus_client                           NA
prompt_toolkit                              3.0.19
ptyprocess                                  0.7.0
pvectorc                                    NA
pycparser                                   2.20
pyexpat                                     NA
pygments                                    2.10.0
pynndescent                                 0.5.6
pyparsing                                   2.4.7
pyrsistent                                  NA
pytz                                        2021.1
requests                                    2.26.0
scipy                                       1.7.1
send2trash                                  NA
six                                         1.16.0
sklearn                                     0.24.2
sniffio                                     1.2.0
statsmodels                                 0.13.2
storemagic                                  NA
tables                                      3.7.0
tensorboard                                 2.8.0
tensorflow                                  2.8.0
termcolor                                   1.1.0
terminado                                   0.11.1
texttable                                   1.6.4
tornado                                     6.1
tqdm                                        4.63.0
traitlets                                   5.0.5
typing_extensions                           NA
umap                                        0.5.2
urllib3                                     1.26.6
wcwidth                                     0.2.5
websocket                                   1.2.1
wrapt                                       1.14.0
xlrd                                        1.2.0
zmq                                         22.2.1
-----
IPython             7.26.0
jupyter_client      6.1.12
jupyter_core        4.7.1
jupyterlab          3.1.7
notebook            6.4.3
-----
Python 3.9.6 (default, Aug 18 2021, 11:08:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Linux-3.10.0-1160.41.1.el7.x86_64-x86_64-with-glibc2.17
36 logical CPU cores, x86_64
-----
Session information updated at 2022-03-26 18:52

</details>

**Comment by aditya-sarkar441** [comment]
I have log normalised the data and have filtered out the genes. 

I have : 
1. adata.var[adata.var["n_cells"]==np.nan] - result is 0.
2. np.isinf(adata.X.todense()).sum() - result is 0.

Data I'm using is GSE158055. Link : https://drive.google.com/file/d/1TXDJqOvFkJxbcm2u2-_bM5RBdTOqv56w/view?usp=sharing

**Comment by ivirshup** [comment]
Thanks for opening the issue. Can you provide a full traceback with any warnings?

I can replicate this when passing count data, but the issue there seems to have to do with us assuming we're getting log transformed data. I do not see this error when I pass log normalized data. E.g. this works:

```python
import scanpy as sc
a = sc.read_h5ad("/Users/isaac/Downloads/GSE158055_covid19.h5ad")
sc.pp.log1p(a)
sc.pp.highly_variable_genes(a, n_top_genes=3000, flavor="seurat")
```

**Comment by aditya-sarkar441** [comment]
Thanks, it is working now.
