### ISSUE TITLE
Error pip installing

### ISSUE THREAD

**Issue by jhung0** [scverse/scanpy#22]
I got an error doing `pip3 install -e .`:

>     clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c scanpy/cython/utils_cy.c -o build/temp.macosx-10.11-x86_64-3.6/scanpy/cython/utils_cy.o
>     scanpy/cython/utils_cy.c:435:10: fatal error: 'numpy/arrayobject.h' file not found
>     #include "numpy/arrayobject.h"
>              ^
>     1 error generated.
>     error: command 'clang' failed with exit status 1
>     
>     ----------------------------------------
> Command "/usr/local/opt/python3/bin/python3.6 -c "import setuptools, tokenize;__file__='/Users/jyhung/Documents/scanpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1

It worked after I installed cython: `pip3 install cython`

**Comment by falexwolf** [comment]
Thanks for the note! I'll look into this and fix it.

**Comment by falexwolf** [comment]
I readded cython to the requirements: https://github.com/theislab/scanpy/commit/2ae826b71c1eefa16b165d4ff85de9f76fc9e62d. I thought it would be unnecessary when directly installing from the .c files, but evidently, it is not. Anyhow, this should fix it.
