### ISSUE TITLE
Error plotting the graph

### ISSUE THREAD

**Issue by rafsanlab** [scverse/scanpy#2208]
- [x] I have checked that this issue has not already been reported. 
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---
 
I am reproducing [3k PBMCs tutorial](https://github.com/scverse/scanpy-tutorials/blob/master/pbmc3k.ipynb), which I run with no problem previously in Google Colab. But suddenly this error pop up during plotting which I believe due to latest update 1.9.0. I verified by installing previous version, this is not an issue:

`!pip install scanpy==1.8.2 # work fine`

### Error code 

```python
# scatter plot in the PCA coordinates, but we will not use that later on.
sc.pl.pca(adata, color='CST3') # <-- this produces the error
```

```pytb
computing PCA
    on highly variable genes
    with n_comps=50
    finished (0:00:00)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-10-615d33c5cea9>](https://localhost:8080/#) in <module>()
      3 
      4 # scatter plot in the PCA coordinates, but we will not use that later on.
----> 5 sc.pl.pca(adata, color='CST3')
      6 
      7 '''

5 frames
[/usr/local/lib/python3.7/dist-packages/scanpy/plotting/_tools/scatterplots.py](https://localhost:8080/#) in pca(adata, annotate_var_explained, show, return_fig, save, **kwargs)
    870     if not annotate_var_explained:
    871         return embedding(
--> 872             adata, 'pca', show=show, return_fig=return_fig, save=save, **kwargs
    873         )
    874     else:

[/usr/local/lib/python3.7/dist-packages/scanpy/plotting/_tools/scatterplots.py](https://localhost:8080/#) in embedding(adata, basis, color, gene_symbols, use_raw, sort_order, edges, edges_width, edges_color, neighbors_key, arrows, arrows_kwds, groups, components, dimensions, layer, projection, scale_factor, color_map, cmap, palette, na_color, na_in_legend, size, frameon, legend_fontsize, legend_fontweight, legend_loc, legend_fontoutline, colorbar_loc, vmax, vmin, vcenter, norm, add_outline, outline_width, outline_color, ncols, hspace, wspace, title, show, save, ax, return_fig, **kwargs)
    451         elif colorbar_loc is not None:
    452             pl.colorbar(
--> 453                 cax, ax=ax, pad=0.01, fraction=0.08, aspect=30, location=colorbar_loc
    454             )
    455 

[/usr/local/lib/python3.7/dist-packages/matplotlib/pyplot.py](https://localhost:8080/#) in colorbar(mappable, cax, ax, **kw)
   2007     if ax is None:
   2008         ax = gca()
-> 2009     ret = gcf().colorbar(mappable, cax=cax, ax=ax, **kw)
   2010     return ret
   2011 colorbar.__doc__ = matplotlib.colorbar.colorbar_doc

[/usr/local/lib/python3.7/dist-packages/matplotlib/figure.py](https://localhost:8080/#) in colorbar(self, mappable, cax, ax, use_gridspec, **kw)
   2236                              'panchor']
   2237         cb_kw = {k: v for k, v in kw.items() if k not in NON_COLORBAR_KEYS}
-> 2238         cb = cbar.colorbar_factory(cax, mappable, **cb_kw)
   2239 
   2240         self.sca(current_ax)

[/usr/local/lib/python3.7/dist-packages/matplotlib/colorbar.py](https://localhost:8080/#) in colorbar_factory(cax, mappable, **kwargs)
   1683         cb = ColorbarPatch(cax, mappable, **kwargs)
   1684     else:
-> 1685         cb = Colorbar(cax, mappable, **kwargs)
   1686 
   1687     cid = mappable.callbacksSM.connect('changed', cb.on_mappable_changed)

[/usr/local/lib/python3.7/dist-packages/matplotlib/colorbar.py](https://localhost:8080/#) in __init__(self, ax, mappable, **kw)
   1228                 kw['alpha'] = mappable.get_alpha()
   1229 
-> 1230             ColorbarBase.__init__(self, ax, **kw)
   1231 
   1232     def on_mappable_changed(self, mappable):

TypeError: __init__() got an unexpected keyword argument 'location'
```

#### Versions

<details>

anndata     0.8.0
scanpy      1.9.0

PIL                                         7.1.2
aa8f2297d25b4dc6fd3d98411eb3ba53823c4f42    NA
absl                                        NA
astor                                       0.8.1
astunparse                                  1.6.3
bottleneck                                  1.3.4
cached_property                             1.5.2
certifi                                     2021.10.08
cffi                                        1.15.0
chardet                                     3.0.4
cloudpickle                                 1.3.0
cvxopt                                      1.2.7
cycler                                      0.10.0
cython_runtime                              NA
dask                                        2.12.0
dateutil                                    2.8.2
debugpy                                     1.0.0
decorator                                   4.4.2
dill                                        0.3.4
flatbuffers                                 2.0
gast                                        0.5.3
google                                      NA
google_auth_httplib2                        NA
googleapiclient                             NA
h5py                                        3.1.0
httplib2                                    0.17.4
idna                                        2.10
igraph                                      0.9.9
ipykernel                                   4.10.1
ipython_genutils                            0.2.0
ipywidgets                                  7.7.0
jax                                         0.3.4
jaxlib                                      0.3.2
joblib                                      1.1.0
keras                                       2.8.0
keras_preprocessing                         1.1.2
kiwisolver                                  1.4.0
leidenalg                                   0.8.9
llvmlite                                    0.34.0
matplotlib                                  3.2.2
mpl_toolkits                                NA
natsort                                     5.5.0
numba                                       0.51.2
numexpr                                     2.8.1
numpy                                       1.21.5
oauth2client                                4.1.3
opt_einsum                                  v3.3.0
packaging                                   21.3
pandas                                      1.3.5
patsy                                       0.5.2
pexpect                                     4.8.0
pickleshare                                 0.7.5
pkg_resources                               NA
portpicker                                  NA
prompt_toolkit                              1.0.18
psutil                                      5.4.8
ptyprocess                                  0.7.0
pyarrow                                     6.0.1
pyasn1                                      0.4.8
pyasn1_modules                              0.2.8
pycparser                                   2.21
pydev_ipython                               NA
pydevconsole                                NA
pydevd                                      2.0.0
pydevd_concurrency_analyser                 NA
pydevd_file_utils                           NA
pydevd_plugins                              NA
pydevd_tracing                              NA
pydot_ng                                    2.0.0
pygments                                    2.6.1
pynndescent                                 0.5.6
pyparsing                                   3.0.7
pytz                                        2018.9
requests                                    2.23.0
rsa                                         4.8
scipy                                       1.4.1
seaborn                                     0.11.2
session_info                                1.0.0
simplegeneric                               NA
sitecustomize                               NA
six                                         1.15.0
sklearn                                     1.0.2
socks                                       1.7.1
sphinxcontrib                               NA
statsmodels                                 0.10.2
storemagic                                  NA
tblib                                       1.7.0
tensorboard                                 2.8.0
tensorflow                                  2.8.0
tensorflow_probability                      0.16.0
termcolor                                   1.1.0
texttable                                   1.6.4
threadpoolctl                               3.1.0
toolz                                       0.11.2
tornado                                     5.1.1
tqdm                                        4.63.0
traitlets                                   5.1.1
tree                                        0.1.6
typing_extensions                           NA
umap                                        0.5.2
uritemplate                                 3.0.1
urllib3                                     1.24.3
wcwidth                                     0.2.5
wrapt                                       1.14.0
yaml                                        3.13
zipp                                        NA
zmq                                         22.3.0

IPython             5.5.0
jupyter_client      5.3.5
jupyter_core        4.9.2
notebook            5.3.1

Python 3.7.13 (default, Mar 16 2022, 17:37:17) [GCC 7.5.0]
Linux-5.4.144+-x86_64-with-Ubuntu-18.04-bionic

Session information updated at 2022-04-04 17:56

</details>

**Comment by ivirshup** [comment]
Thanks for the report. It looks like we needed to bump the minimum version of matplotlib for that feature.

Is there any reason you're using an old version of matplotlib here?

**Comment by rafsanlab** [comment]
> 

No spesific reason, I just use the one come pre-installed. Thank you anyways.

**Comment by canergen** [comment]
Bumping matplotlib needs updating of google Colab's default matplotlib. As Colab imports matplotlib on start-up this means you have to restart the runtime after installing scanpy. For production I think it's fine, tutorials would require to restart after installing scanpy.
You can see this behavior in scverse tutorials using Colab, e.g. https://docs.scvi-tools.org/en/stable/tutorials/notebooks/api_overview.html

**Comment by rafsanlab** [comment]
> Bumping matplotlib needs updating of google Colab's default matplotlib. As Colab imports matplotlib on start-up this means you have to restart the runtime after installing scanpy. For production I think it's fine, tutorials would require to restart after installing scanpy. You can see this behavior in scverse tutorials using Colab, e.g. https://docs.scvi-tools.org/en/stable/tutorials/notebooks/api_overview.html

Noted!

**Comment by rboiarsky** [comment]
I am getting this same error, namely when I run `sc.pl.umap(adata, color='pid')` I see `UserWarning: No data for colormapping provided via 'c'. Parameters 'cmap' will be ignored` and then `adata.uns['pid_colors']` all gets set to gray, and my whole UMAP plot looks gray instead of being color by 'pid.'

I am using scanpy 1.9.1 and matplotlib 3.6.3. Can someone advise me what I need to upgrade to avoid this error, or how I can work around it with my current package versions?  I see that #2212 upped the required matplotlib to 3.4, but since I'm at 3.6.3 I thought I should be okay. Thanks!
