### ISSUE TITLE
Add CI run with minimal dependencies

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#2211]
#2210 is triggered by not having dask installed. Our current CI setup can't test for this.

This should be addressed with a CI run that uses minimal dependencies.

**Comment by ivirshup** [comment]
Would be good to know if there's any nice tooling around this, as this could make fixtures and parametrized tests a bit difficult.

For example, not installing `dask` makes test collection fail in the `test_normalization.py` file.

<details>
<summary> Error </summary>

```pytb
_______________________ ERROR collecting scanpy/tests/test_normalization.py ________________________
ImportError while importing test module '/Users/isaac/github/scanpy/scanpy/tests/test_normalization.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../miniconda3/envs/scanpy-minimal/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
scanpy/tests/test_normalization.py:5: in <module>
    import dask.array as da
E   ModuleNotFoundError: No module named 'dask'
```

</details>

**Comment by flying-sheep** [comment]
Do you also mean minimal dependency versions? Because Rust’s cargo e.g. has `carg update -Z minimum-versions` which allows people to figure out if their minimum version bounds are truthful or lies (i.e. to be raised)

**Comment by ivirshup** [comment]
That would also be nice, and catch things like #2208.

**Comment by ivirshup** [comment]
But I think it's a little different. It's probably easier to implement since we still have all dependencies available at collection time.

**Comment by flying-sheep** [comment]
Regarding running CI with minimal optional deps, I’d say we could change this line:

https://github.com/scverse/scanpy/blob/86e2a35c1df2b61772e5f898bfcd11abb8d9fb2c/.azure-pipelines.yml#L46

… to be parametric like `pip install .[dev,test$(test_extras))]`, and run things once with `test_extras=''` and once with `test_extras=',leiden,magic,harmony,scrublet,scanorama,skmisc'`

we’d probably have to make a lot of tests optional with `@skipif(not find_spec('thing'), ...)` though, and of course remove some things from the `test` extra

**Comment by flying-sheep** [comment]
One important thing: pip supports self-depending. I’ve written dep lists like

```toml
[project]
name = 'myproj'

[project.optional-dependencies]
# myproj’s exported testing tools depend on those:
testing = ['pytest-postgresql']
# to run our package’s tests, we need:
test = ['pytest', 'myproj[testing]']
```

**Comment by ivirshup** [comment]
>  like pip install .[dev,test$(test_extras))], and run things once with test_extras='' and once with test_extras=',leiden,magic,harmony,scrublet,scanorama,skmisc'

Yeah, I was thinking something like this. Except we could just reduce `test` to include the barebones needed to make tests run, and separately have optional dependencies. The hard part here is structuring the tests so they can run without optional dependencies being present. We'd need to establish patterns for optional dependencies in fixtures and parameterized tests.

**Comment by flying-sheep** [comment]
That’s the way anyway. I think first step would be to rewrite our `test` extra in terms of a) what’s needed for testing and b) what really are scanpy features being tested:

```toml
test = [
    'pytest',
    'scanpy[dask]',
    'scanpy[zarr]',
]
```

then we can extra-by-extra make parts of our test suite optional.
