### ISSUE TITLE
Fix reference links in MyST docs

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#2216]
Links to references in docs are broken. I think we should probably switch over to [sphinxcontrib-bibtex](https://sphinxcontrib-bibtex.readthedocs.io/en/latest/) as recommended by [executable books](https://jupyterbook.org/content/citations.html).

**Comment by ivirshup** [comment]
Now, to go from some custom reference formatting scheme to bibtex 😭

**Comment by flying-sheep** [comment]
doc changes that weren’t backported make it hard to fix this in 1.9.4, so it’ll have to wait for 1.10.0

**Comment by flying-sheep** [comment]
Actually they aren’t broken in rST at all, only MyST:

https://scanpy.readthedocs.io/en/latest/generated/scanpy.tl.pca.html

![grafik](https://github.com/scverse/scanpy/assets/291575/f1c05c40-7152-4777-8847-fe77e615c346)
