### ISSUE TITLE
Getting scanpy to work on M1 Mac

### ISSUE THREAD

**Issue by watiss** [scverse/scanpy#2237]
Hi all.
I've been running into issues installing scanpy on M1 Mac (Apple Silicone) hardware. (It looks like something is wrong with numba?) I'm sure this is not new to you. I've seen a few issues on that here and there but it's not clear to me at this time:
1. whether there is any workaround to getting this to work? (I'm using M1 homebrew)
2. where can I track the status of the fix for this?  

The lack of scanpy is quite debilitating in my daily workflows, so it would be awesome if there is a way to get it to work even temporarily while waiting for the fix.

Thanks ahead!

**Comment by adamgayoso** [comment]
You should be able to install an experimental m1 native numba here:

https://numba.discourse.group/t/wheels-for-apple-silicon-m1/1282

**Comment by adamgayoso** [comment]
Issue here:

https://github.com/numba/llvmlite/issues/799

**Comment by watiss** [comment]
Awesome thanks!
