### ISSUE TITLE
Subsetting based on multiple clusters/indices

### ISSUE THREAD

**Issue by ghost** [scverse/scanpy#224]
I was trying to subset my dataset based on multiple louvain cluster IDs but it seems to only be possible with one cluster ID at a time.  I'm still new to python and scanpy but would there be a workaround or fix to this? To ease the process I'v inserted what I want to do.

`adata_subset = adata[adata.obs['louvain'] == '2', '3']`

**Comment by falexwolf** [comment]
Do
```
adata_subset = adata[adata.obs['louvain'].isin(['2', '3'])]
```
