### ISSUE TITLE
pixel coordinates from reading the 10X visium slide

### ISSUE THREAD

**Issue by YuanningEric** [scverse/scanpy#2251]
...

Hi,

I noticed that when scanpy reads the spatial information from the  "tisslue_position_list.csv" file  of the 10X visium data, the (x,y) coordinate for pixels is flipped:

        positions.columns = [
            'barcode',
            'in_tissue',
            'array_row',
            'array_col',
            'pxl_col_in_fullres',
            'pxl_row_in_fullres',
        ]

However, from here: [https://support.10xgenomics.com/spatial-gene-expression/software/pipelines/latest/output/images](url), the pxl_row is supposed to be ahead of pxl_col .

Is there any explanation for this?

**Comment by giovp** [comment]
hi @YuanningEric ,

this was also reported here https://github.com/scverse/squidpy/issues/599 and I have a PR that fixes in the squidpy reading function. I'd suggest to directly open an issue in squidpy!
