### ISSUE TITLE
show the mean of several genes in spatial scanpy figure

### ISSUE THREAD

**Issue by sophieRAIBAUD** [scverse/scanpy#2252]
...
Hello

I would like to plot the "log1p_total_counts" of a **visium transcriptomic dataset** (AnnData object with n_obs × n_vars) using sc.pl.spatial

**sc.pl.spatial(adatal, img_key="hires", color=["gene1", "gene2", "gene3"]) -**-> gives 3 images (the 3 genes are plotted stacked on 3 images)

But instead of  I would like to plot **the mean of the 3 genes on 1 image**

is it possible ??
I hope the question is clear :)
Manys thanks for your help
Sophie

**Comment by MertDemirdizen** [comment]
I am looking for the same thing. Did you find a way to do that?

**Comment by sophieRAIBAUD** [comment]
unfortunatly not :(

**Comment by MertDemirdizen** [comment]
Check this out.
It helped me a lot. 
https://github.com/Teichlab/limbcellatlas/issues/1#issuecomment-1146685471

**Comment by sophieRAIBAUD** [comment]
many thanks !!

**Comment by giovp** [comment]
hi @MertDemirdizen @sophieRAIBAUD 
sorry for late reply. This type of functionality is planned to be added to squidpy (there is an issue also there discussing the same). I'd close this here since the scanpy spatial plot will be deprecated, feel free to reopen/ping me in the squidpy repo directly

**Comment by sophieRAIBAUD** [comment]
OK thanks
@giovp when do you plan to add this new fonctionnality ?
@MertDemirdizen : I don't understand how to add the intensity according to the post (https://github.com/Teichlab/limbcellatlas/issues/1#issuecomment-1146685471)
could you help me ?
many thanks !
