### ISSUE TITLE
Spot coordinates in Spatial Transcriptomics

### ISSUE THREAD

**Issue by julie-jch** [scverse/scanpy#2253]
...

Hello, I hope I'm in the correct place. I was wondering, in Spatial Transcriptomics analyses, after loading data `adata = sc.read_visium`, where are the spot co-ordinates stored?

Example
spot          x       y
1x17x20	17	20	
1x17x21	17	21

**Comment by giovp** [comment]
in adata.obsm["spatial"], I'd suggest to plot these type of issues directly on squidpy, see this function for read visium
there this is explained https://squidpy.readthedocs.io/en/latest/api/squidpy.read.visium.html#squidpy.read.visium
