### ISSUE TITLE
How to extract expression matrix for all cells belonging to a cell type?

### ISSUE THREAD

**Issue by krishna-koundinya** [scverse/scanpy#226]
Hello, 
I am new to Scanpy. I have been using Seurat for sometime now and there is this function WhichCells which lets me extract cells belonging to a cluster - `WhichCells(object = pbmc, ident = "NK cells")`, and also the expression matrix of the entire cluster - `nk.raw.data <- as.matrix(x = pbmc@raw.data[, WhichCells(object = pbmc, ident = "NK cells")]`.
[https://satijalab.org/seurat/interaction_vignette.html]

Is there a similar function in Scanpy? If not, how can I work around to extract the expression matrix?
Also, is there a way to save the the expression matrix as a dense matrix?

**Comment by falexwolf** [comment]
Subset the AnnData object
```
adata_subset = adata[adata.obs['louvain'] == '1']
```

Get the expression matrix from an arbitrary AnnData object
```
adata.X
```

Get the raw expression matrix if you set the `.raw` attribute at some point
```
adata.raw.X
```

Convert the sparse expression matrix of an AnnData object to a dense array
```
adata.X.toarray()
```
on which you can call `np.savetxt`, for instance.

Easier: save the whole AnnData object as csvs: https://anndata.readthedocs.io/en/latest/anndata.AnnData.write_csvs.html
```
adata.write_csvs()
```

**Comment by falexwolf** [comment]
As we just had this in another issue, subset to multiple clusters:
```
adata_subset = adata[adata.obs['louvain'].isn(['1', '2', '3'])]
```

**Comment by aopisco** [comment]
subsetting doesn't work:
I've this object

```python
>>> tiss
```

    AnnData object with n_obs × n_vars = 29322 × 19860

```python
>>> tiss[tiss.obs['cell_ontology_class']=='B cell']
```

```pytb
IndexError                                Traceback (most recent call last)
<ipython-input-269-28b4524131cb> in <module>()
----> 1 tiss[tiss.obs['cell_ontology_class']=='B cell']

~/anaconda3/lib/python3.6/site-packages/anndata/base.py in __getitem__(self, index)
   1299     def __getitem__(self, index):
   1300         """Returns a sliced view of the object."""
-> 1301         return self._getitem_view(index)
   1302 
   1303     def _getitem_view(self, index):

~/anaconda3/lib/python3.6/site-packages/anndata/base.py in _getitem_view(self, index)
   1303     def _getitem_view(self, index):
   1304         oidx, vidx = self._normalize_indices(index)
-> 1305         return AnnData(self, oidx=oidx, vidx=vidx, asview=True)
   1306 
   1307     def _remove_unused_categories(self, df_full, df_sub, uns):

~/anaconda3/lib/python3.6/site-packages/anndata/base.py in __init__(self, X, obs, var, uns, obsm, varm, layers, raw, dtype, shape, filename, filemode, asview, oidx, vidx)
    662             if not isinstance(X, AnnData):
    663                 raise ValueError('`X` has to be an AnnData object.')
--> 664             self._init_as_view(X, oidx, vidx)
    665         else:
    666             self._init_as_actual(

~/anaconda3/lib/python3.6/site-packages/anndata/base.py in _init_as_view(self, adata_ref, oidx, vidx)
    713             raise KeyError('Unknown Index type')
    714         # fix categories
--> 715         self._remove_unused_categories(adata_ref.obs, obs_sub, uns_new)
    716         self._remove_unused_categories(adata_ref.var, var_sub, uns_new)
    717         # set attributes

~/anaconda3/lib/python3.6/site-packages/anndata/base.py in _remove_unused_categories(self, df_full, df_sub, uns)
   1318                     uns[k + '_colors'] = np.array(uns[k + '_colors'])[
   1319                         np.where(np.in1d(
-> 1320                             all_categories, df_sub[k].cat.categories))[0]]
   1321 
   1322     def rename_categories(self, key, categories):

IndexError: index 7 is out of bounds for axis 1 with size 7
```

even though it's part of the set:
```py
>>> set(tiss.obs['cell_ontology_class'])
{'B cell',
 'NA',
 'T cell',
 'dendritic cell',
 'macrophage',
 'natural killer cell'}
```

it does work for louvain though:

```python
>>> tiss[tiss.obs['louvain']=='0']`
```

    View of AnnData object with n_obs × n_vars = 5862 × 19860`

**Comment by fidelram** [comment]
It should work. Since what fails is some clean up of annData categories,
you may want to check that `tiss.obs['cell_ontology_class']` is set as
categorical. Also check `'B cell' in
tiss.obs['cell_ontology_class'].cat.categories` to avoid a typo.

**Comment by fidelram** [comment]
It should work. Since what fails is some clean up of annData categories,
you may want to check that `tiss.obs['cell_ontology_class']` is set as
categorical. Also check `'B cell' in
tiss.obs['cell_ontology_class'].cat.categories` to avoid a typo.

Finally, I think that I had a similar issue which I resolved by removing a adata.uns elements that end in `_colors`. In your case I think you would need to do  `del tiss.uns['cell_ontology_class_colors]`
