### ISSUE TITLE
Cannot find tutorial for regressing out cell cycle genes

### ISSUE THREAD

**Issue by ntanmayee** [scverse/scanpy#2260]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
---
Hello, I am trying to find the tutorial to regress out cell cycle genes, and all the links in the documentation are broken. 

1. The documentation for `scanpy.tl.score_genes_cell_cycle` has a link to an example, which is [broken](https://github.com/scverse/scanpy_usage/tree/master/180209_cell_cycle)
2. The [tutorials](https://scanpy.readthedocs.io/en/latest/tutorials.html) page in the documentation has another link which is also [broken](https://nbviewer.org/github/scverse/scanpy_usage/blob/master/180209_cell_cycle/cell_cycle.ipynb)

Is this intentional? Could someone please help? 

Thanks in advance!

**Comment by naity2** [comment]
I have the same question. Would someone from the development team help take a look at this issue? Thanks!

**Comment by davidmckinnon** [comment]
See here: https://nbviewer.org/github/theislab/scanpy_usage/blob/master/180209_cell_cycle/cell_cycle.ipynb

**Comment by Zethson** [comment]
Thank you @davidmckinnon !

**Comment by Zethson** [comment]
Actually, reopening this to ensure that we fix the broken links.

**Comment by ivirshup** [comment]
@Zethson, do you think we should move those to scverse?

**Comment by Zethson** [comment]
> @Zethson, do you think we should move those to scverse?

Do you mean to this page? https://scverse.org/learn/

Or generally all of them? We might require stronger filtering options then because with all tools combined we would have a lot of vignettes.

Edit oh wait: I had no idea that we had this scanpy_usage repository. My answer is yes.

**Comment by ivirshup** [comment]
Oops, missed this.

Just moved. Should fix this issue.

**Comment by divyanshusrivastava** [comment]
(Minor) bug detected in the notebook shared above by @davidmckinnon 
The notebook performs `sc.pp.scale` followed by `sc.pp.score_genes_cell_cycle` <bold> with default parameters</bold>. 

In the default setting, `sc.pp.score_genes_cell_cycle` will take up the `.raw` layer of the anndata, if it exists. To be sure the scoring is performed on scaled counts, it should be done as 

`sc.tl.score_genes_cell_cycle(adata, s_genes=s_genes, g2m_genes=g2m_genes, use_raw=False)`
