### ISSUE TITLE
MemoryError for the v1.9.1

### ISSUE THREAD

**Issue by wubaosheng** [scverse/scanpy#2266]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [x] (optional) I have confirmed this bug exists on the master branch of scanpy.

------it is easy for v1.9.1 out of memory.
I have the same data(200000x20000), the RAM of my compute is 64 GB, and the v1.8 can cope it easy, but the v1.9.1 is easy to occur the memoryError from the sc.read('./xxx.h5ad').

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can copy&paste without having any data)
sc.read('./xxx.h5ad')
```python
# Your code here
```

```pytb
[Paste the error output produced by the above code here]
```

#### Versions
v1.9.1
<details>

[Paste the output of scanpy.logging.print_versions() leaving a blank line after the details tag]

</details>
![image](https://user-images.githubusercontent.com/50618480/170998448-db4300d9-54f0-4f03-b2be-7f6880006b29.png)

**Comment by Zethson** [comment]
@wubaosheng could you please ensure that the issue formatting is right? Then things are easier for us to read and discuss.
Do you have more details about the dataset? Is there a way to provide it to us?

**Comment by Zethson** [comment]
Feel free to reopen after you've provided the required information
