### ISSUE TITLE
pl.diffmap show and save issue

### ISSUE THREAD

**Issue by b-dawes** [scverse/scanpy#227]
I noticed that `pl.diffmap` interacts differently with the `show` and `save` options than most of the other plotting functions. Namely, if both `show` and `settings.autoshow` are true, `pl.diffmap` saves but does not show. Most of the other functions will both save and show.

I looked in the code a bit and it looks like this is because other plotting functions use `utils.savefig_or_show` versus `pl.diffmap` has some custom plotting logic (I assume because `pl.diffmap` allows multiple plots to be generated by passing a list to `components`).  Changing:
```python
if not settings.autosave and show: pl.show()
```
to just:
```python
if show: pl.show()
```
should make `pl.diffmap` more consistent with the other plotting functions.

**Comment by falexwolf** [comment]
Thank you, this obviously makes sense. I'll first merge another update on plotting functions and then get back to this.

**Comment by falexwolf** [comment]
Fixed it: https://github.com/theislab/scanpy/commit/22511ee048f0277f61f40554a4bc6f76aaf4bc1c

Thanks again! :smile:
