### ISSUE TITLE
dotplot external labels in notebook

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/scanpy#2270]
Hi,
I am using scanpy 1.9.1 following this tutorial: https://scanpy-tutorials.readthedocs.io/en/latest/plotting/core.html
I find that  scanpy cannot display the bar under each leiden number, the follwing is figures on the tutorial, but in fact the bar disappeared when I tried the code, and this is also the case in other plots on the tutorial
![plotting_core_59_0](https://user-images.githubusercontent.com/29703450/173169270-03e982a4-3658-4896-a57e-3f3b919d18a7.png)

**Comment by wangjiawen2013** [comment]
May be it's a bug of my jupyter notebook, nothing related with scanpy.

**Comment by ivirshup** [comment]
Can you share some plots of what you're generating? I can't reproduce what you're describing.

**Comment by wangjiawen2013** [comment]
Now it's ok, I thinks it's a bug of my jupternotebook and vscode.
