### ISSUE TITLE
quick sc.tl.louvain documentation fix

### ISSUE THREAD

**Issue by dfirer** [scverse/scanpy#2276]
- [x] Other?
Quick documentation fix, under sc.tl.louvain:
https://scanpy.readthedocs.io/en/stable/generated/scanpy.tl.louvain.html
The return info only includes `adata.obs['louvain']` and doesn't include `adata.uns['louvain']['params']`

**Comment by Zethson** [comment]
Would you mind filing up a PR for this?

Thank you!
