### ISSUE TITLE
Incompatible with conda?

### ISSUE THREAD

**Issue by dsm-72** [scverse/scanpy#2282]
- [x ] I have checked that this issue has not already been reported.
- [x ] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can copy&paste without having any data)

```python
# create new env
conda install -c pytorch pytorch
conda install -c pytorch cudatoolkit=11.3


conda install -c bioconda scanpy
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0

Your installed version is: 2.31
```

**Comment by ivirshup** [comment]
As noted in [the installation docs](https://scanpy.readthedocs.io/en/stable/installation.html), scanpy is not distributed via bioconda.

It should be installed with `conda install -c conda-forge scanpy`
