### ISSUE TITLE
superimpose plotting function for sc.pl.spatial

### ISSUE THREAD

**Issue by yjgeno** [scverse/scanpy#2284]
Is it possible to have one figure pf spatial gene expression stack over (superimpose) another? The following function will give me two subplots instead of an integrated one 
`sc.pl.spatial(ada, img_key="hires", color=["Gene1", "Gene2"])
`

**Comment by giovp** [comment]
what do you mean superimposed? Noevertheless, I'd suggest you to take a look at squidpy functionality: 
here: [squidpy.readthedocs.io/en/latest/examples.html#plotting](https://squidpy.readthedocs.io/en/latest/examples.html#plotting) and here: [squidpy.readthedocs.io/en/latest/api/squidpy.pl.spatial_scatter.html#squidpy.pl.spatial_scatter](https://squidpy.readthedocs.io/en/latest/api/squidpy.pl.spatial_scatter.html#squidpy.pl.spatial_scatter)

feel free to open an issue directly in squidpy for spatial plotting requests. I'll close this now for the moment.
