### ISSUE TITLE
why frameon is by default False now?

### ISSUE THREAD

**Issue by fidelram** [scverse/scanpy#229]
I noticed that commit 28f5034bea422494835cac883db812fdc26fe1db set  `frameon=False` in settings.

Is there a good reason to have frameon False? Notice that in the documentation for example for `pl.umap` still says that the default is `frameon=True`

**Comment by falexwolf** [comment]
Thanks for pointing out the error in the documentation.

This only affects the scatter plots. I observed that most people I interact with prefer the scatter plots without the frames. But we can change this back if it worries you. No problem. You have become the plotting expert for Scanpy, I'd say; so your opinion obviously counts a lot.

**Comment by fidelram** [comment]
I would suggest to put back  `frameon=False` by default. For several scatter plots it doesn't matter to much (eg. tsne, umap, but for some others is not so good e.g :

```python
sc.pl.scatter(adata, x='n_counts', y='percent_mito')
```
![image](https://user-images.githubusercontent.com/4964309/43883398-4d299d76-9bb3-11e8-8594-49127f4f21e9.png)

**Comment by falexwolf** [comment]
Yes, I also noticed this already and thought about distinguishing cases where there are informative axes labels and ticks and those where there are not... But you're right, it's cleaner to just set the default to `True` again. I'll do that along with merging your pull request... Just need a bit more time to go through it...
