### ISSUE TITLE
Problem in Spatial Umap Plot

### ISSUE THREAD

**Issue by lingxincheng08** [scverse/scanpy#2291]
I was trying the spatial tutorial by copy and paste the same code on the tutorial(https://scanpy-tutorials.readthedocs.io/en/latest/spatial/basic-analysis.html). 
However, when I run 

```py
plt.rcParams["figure.figsize"] = (4, 4)
sc.pl.umap(adata, color=["total_counts", "n_genes_by_counts", "clusters"], wspace=0.4)
```

I got figures like:

<img width="1029" alt="截屏2022-07-07 下午8 45 16" src="https://user-images.githubusercontent.com/103924215/177777042-080ebc5e-7e8b-46e9-9631-c72c6e8f9e81.png">

However the real result should be 

<img width="950" alt="截屏2022-07-07 下午8 45 53" src="https://user-images.githubusercontent.com/103924215/177777096-398b19c0-9b13-47a5-a506-480fcf5327ca.png">

I am not sure what is happening...
My version is scanpy 1.8.1. 
May I get some help on that? Thanks!

**Comment by giovp** [comment]
hi @lingxincheng08 can you check the solution posted here? https://github.com/IGS/gEAR/issues/386#issuecomment-1227212721 I believe the default might have changed

**Comment by eroell** [comment]
Hi @lingxincheng08,
did the above solution help you resolve the issue? :)

**Comment by eroell** [comment]
We will close the issue for now, hopefully you obtained the expected behaviour :)

However, please don't hesitate to reopen this issue or create a new one if you have any more questions or run into any related problems in the future.

Thanks for being a part of our community! :)
