### ISSUE TITLE
KeyError: 'dict' … Above error raised while reading key '/layers' of type <class 'h5py._hl.group.Group'>

### ISSUE THREAD

**Issue by brianpenghe** [scverse/scanpy#2297]
I'm using scanpy 1.8.2, anndata 0.8.0 and h5py 3.1.0

I got this error while reading an h5ad file:

```
adata=sc.read_h5ad('XXXX.h5ad')
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/opt/conda/lib/python3.8/site-packages/anndata/_io/utils.py in func_wrapper(elem, *args, **kwargs)
    155     if zarr and isinstance(elem, (zarr.Group, zarr.Array)):
--> 156         parent = elem.store  # Not sure how to always get a name out of this
    157     elif isinstance(elem, SparseDataset):

/opt/conda/lib/python3.8/site-packages/anndata/_io/h5ad.py in read_group(group)

/opt/conda/lib/python3.8/enum.py in __getitem__(cls, name)
    386     def __getitem__(cls, name):
--> 387         return cls._member_map_[name]
    388 

KeyError: 'dict'

During handling of the above exception, another exception occurred:

AnnDataReadError                          Traceback (most recent call last)
<ipython-input-15-a2632df74a34> in <module>
----> 1 adata=sc.read_h5ad('XXXX.h5ad')

/opt/conda/lib/python3.8/site-packages/anndata/_io/h5ad.py in read_h5ad(filename, backed, as_sparse, as_sparse_fmt, chunk_size)

/opt/conda/lib/python3.8/functools.py in wrapper(*args, **kw)
    873                             '1 positional argument')
    874 
--> 875         return dispatch(args[0].__class__)(*args, **kw)
    876 
    877     funcname = getattr(func, '__name__', 'singledispatch function')

/opt/conda/lib/python3.8/site-packages/anndata/_io/utils.py in func_wrapper(elem, *args, **kwargs)
    160         parent = elem.file.name
    161     return parent
--> 162 
    163 
    164 def report_read_key_on_error(func):

AnnDataReadError: Above error raised while reading key '/layers' of type <class 'h5py._hl.group.Group'> from /.
```

Any ideas?

**Comment by brianpenghe** [comment]
updating h5py to 3.6.0 seemed to have worked. Does it sound like right?

**Comment by TheBorgy** [comment]
Encountering the same error. Updating h5py did not seem to help. Any advice on this?

**Comment by livewei** [comment]
I was having the same problem. **conda update anndata** solved my problem.

**Comment by brianpenghe** [comment]
> Encountering the same error. Updating h5py did not seem to help. Any advice on this?

This might be useful to you:
https://github.com/scverse/scanpy/issues/1351#issuecomment-1198015945

**Comment by Jiayi-Zheng** [comment]
@brianpenghe Hi may I consult how you resolved the problem?

The comment says upgrade anndata to 0.8.0 but mine already is 0.8.0 and the error message remains.

**Comment by kinga322** [comment]
@Jiayi-Zheng Same for me.

**Comment by ktpolanski** [comment]
Have you rebooted the python after updating anndata? Can you paste the exact error you're seeing? Are you allowed to share the object you're having trouble loading?

OP's error is bizarre, e.g. the last part seems to be pointing to an empty line. Like the package was updated but the python was not restarted. I can't recreate the exact one he's seeing, but I've managed to get other disjoint errors along those lines by updating anndata to 0.8.0 in a second terminal while the python in question is still running.

**Comment by Jiayi-Zheng** [comment]
@ktpolanski I re-created a new conda env and installed scanpy so now it's working. I'm still not sure where the problem lies, though I did realize it starts jumping error after I install another package called stereopy, I'm guessing maybe that package updated something which got in conflict with normal scanpy setting.

**Comment by kinga322** [comment]
@ktpolanski I thought I had the newest anndata version, but turns out 0.8.0 is not in Ubuntu repositiories. I had to manually download and install Python 3.8, anndata 0.8.0 and h5py, now it works.

**Comment by ktpolanski** [comment]
> @ktpolanski I re-created a new conda env and installed scanpy so now it's working. I'm still not sure where the problem lies, though I did realize it starts jumping error after I install another package called stereopy, I'm guessing maybe that package updated something which got in conflict with normal scanpy setting.

https://github.com/BGIResearch/stereopy/blob/6345d2732772a58d60351e790058bd5da1301fb5/requirements.txt#L26

**Comment by Marwansha** [comment]
updaing anndata from 0.7.6 to anndata 0.8  solved it for me

**Comment by yasinkaymaz** [comment]
Seems like this is still an issue. I am getting this error below randomly. It disappears after trying sometime later with the exact code and files...

scanpy==1.9.4 anndata==0.9.2 umap==0.5.3 numpy==1.23.4 scipy==1.11.2 pandas==2.1.4 scikit-learn==1.3.0 statsmodels==0.14.0 igraph==0.10.6 louvain==0.8.1 pynndescent==0.5.10

`adata=sc.read_h5ad('foo.h5ad')`
Error:
`AnnDataReadError: Above error raised while reading key '/X' of type <class 'h5py._hl.group.Group'> from /.`

**Comment by Jiayi-Zheng** [comment]
I'm not sure what is the cause of the problem and how to resolve it. But it I remove everything in the metadata aside from index and genecount/genenumber the error does not come up. So one solution is to save metadata to a csv and save the adata without too much metadata info.

**Comment by flying-sheep** [comment]
> anndata==0.9.2

Anndata is currently at 0.10.4. Please use the newest version if you want to check if a bug still exists.

**Comment by edoumazane** [comment]
Running `0.10.3` here.

I had a similar error message, originating in a **mismatch of the indices of the obs-like dataframes** of the `AnnData` object. Although it was not exactly the same (sorry i don't have it here), maybe this can be a hint.

Here is how i solved the issue.

```python
### Have a look at the indices
for key, obs_matrix in adata.obsm.items():
    if hasattr(obs_matrix, "index"):
        print(key)
        print(obs_matrix.index)
print(adata.obs_names)
print(adata.obs.index)

### If there's a mismatch, you can fix by running something like:
for key, obs_matrix in adata.obsm.items():
    if hasattr(obs_matrix, "index"):
        obs_matrix.index = adata.obs_names
```

I also had a similar error message when there was a mismatch in the _name_ of the index, or if the name of the index was also the _name of a column_


Note that if there is a mismatch, the `adata.write_h5ad` function _does not_ crash.

While reading the saved file with `ad.read_h5ad` _will crash_.

Suggestion for developers: When the `AnnData.write_h5ad` method is called, check the homogeneity of the indices, and raise an exception if there is a mismatch.

Suggestion for users: make sure all the index are the same, have the same name, and that no column has the same name.

**Comment by houruiyan** [comment]
Hi , there is also another problem. The h5ad file may have some problem. Please double check that.

**Comment by flying-sheep** [comment]
@edoumazane this can no longer happen in the newest version: https://github.com/scverse/anndata/blob/0024b82c0f161daed3b40b4712c2ab13d84e5804/src/anndata/_io/specs/methods.py#L848-L852

**Comment by LYT-academic** [comment]
Hello I met the same question. 
```bash
TypeError: argument should be a str or an os.PathLike object where fspath returns a str, not 'NoneType' 
Error raised while writing key 'donor' of <class 'h5py._hl.group.Group'> to /??
```
And in my case, the problem is caused by **obs.index.name and var.index.name**

## 1. Two ways I tried and failed to solving this problem:
- update the version mentioned in above answers -> I used latest version, not this reason
- check the adata.var["gene_ids"].dtype mentioned in this [answer](https://github.com/scverse/anndata/issues/615) -> My dtype is 'object', and when I did not add adata.obs["donor"]=donor and directly save, everything will be ok, so not caused by adata.var

## 2. My issue and solution
After trying every part of my codes, I find the issue part. Here is how I discovered this issue.
### checking other persons correct h5ad files
I checked other persons correct .h5ad files and noticed that their var_names or obs_names did not contain `name`, but only `dtype` and `length`
```python
h5ad_data.var_names
>>>Index(['FO538757.2', 'SAMD11', 'NOC2L', 'KLHL17', 'PLEKHN1', 'PERM1', 'HES4',
       'ISG15', 'AGRN', 'RNF223',
       ...
       'FTCD', 'SPATC1L', 'LSS', 'MCM3AP', 'YBEY', 'C21orf58', 'PCNT', 'DIP2A'],dtype='object', length=17695)
```
However my var_names or obs_names contains `name`
```python
adata.obs_names
>>>Index(['AAACCTGAGAAAGTGG-1', 'AAACCTGAGCGAGAAA-1', 'AAACCTGCAAGTCTGT-1',
       'AAACCTGCACCCATTC-1', 'AAACCTGGTACTTCTT-1', 'AAACCTGGTAGATTAG-1',
       'AAACCTGGTAGCACGA-1', 'AAACCTGGTATGAAAC-1', 'AAACCTGGTGACTACT-1',
       'AAACCTGTCAGATAAG-1',
       ...
       'TTTGTCACAGCCACCA-1', 'TTTGTCACAGCTCCGA-1', 'TTTGTCAGTAATCGTC-1',
       'TTTGTCAGTAATTGGA-1', 'TTTGTCAGTGAGGGTT-1', 'TTTGTCAGTGGTAACG-1',
       'TTTGTCATCAAAGTAG-1', 'TTTGTCATCCCGACTT-1', 'TTTGTCATCTATCCCG-1',
       'TTTGTCATCTCTGTCG-1'],
      dtype='object', name='', length=6327)

adata.var_names
>>>Index(['RP11-34P13.3', 'FAM138A', 'OR4F5', 'RP11-34P13.7', 'RP11-34P13.8',
       'RP11-34P13.14', 'RP11-34P13.9', 'FO538757.3', 'FO538757.2',
       'AP006222.2',
       ...
       'AC004556.1', 'AC233755.2', 'AC233755.1', 'AC240274.1', 'AC213203.1',
       'FAM231B', 'CCR7_TotalSeqC', 'CD45RA_TotalSeqC', 'CD4_TotalSeqC',
       'CD8_TotalSeqC'], dtype='object', name='', length=33698)
```
### Issue caused by index.name!
**So I find the issue part of my code, and changed  obs.index.name from `""` to `None`**
```python
# My issue code
def read_mtx_file(mtx_path, barcodes_path, features_path):
    obs = pd.read_csv(barcodes_path, header=None, index_col=0, sep="\t")
    var = pd.read_csv(features_path, header=None, index_col=1, sep="\t", usecols=[0, 1])
    obs.index.name = ""  # issue part
    var.index.name = ""  # issue part
    var.columns = ["gene_ids"]
    # print(var.head())
    mtx = mmread(mtx_path)
    mtx = mtx.T
    mtx = csr_matrix(mtx)
    adata = sc.AnnData(mtx, obs=obs, var=var)
    adata.var_names_make_unique()
    return adata
```
```python
# Revised code
def read_mtx_file(mtx_path, barcodes_path, features_path):
    obs = pd.read_csv(barcodes_path, header=None, index_col=0, sep="\t")
    var = pd.read_csv(features_path, header=None, index_col=1, sep="\t", usecols=[0, 1])
    obs.index.name = None
    var.index.name = None
    var.columns = ["gene_ids"]
    # print(var.head())
    mtx = mmread(mtx_path)
    mtx = mtx.T
    mtx = csr_matrix(mtx)
    adata = sc.AnnData(mtx, obs=obs, var=var)
    adata.var_names_make_unique()
    return adata

>>>Save F012.h5ad done!  # Wow! Solved! 😆
```

I would be happy if anyone could answer why index.name cause this issue:)
