### ISSUE TITLE
Strange behaviour when plotting with groups

### ISSUE THREAD

**Issue by fbnrst** [scverse/scanpy#231]
I realized a strange behaviour of scanpy when using plotting with groups (e.g. `sc.pl.umap(adata, color='blobs', groups='Zero')`)

Take the following example:

```python
import scanpy.api as sc
adata = sc.datasets.blobs()
sc.pp.neighbors(adata)
sc.tl.umap(adata)

# this works
sc.pl.umap(adata, color='blobs', groups='0')
adata.obs['blobs'] = adata.obs['blobs'].cat.rename_categories({'0': 'Zero'})

# this also works
sc.pl.umap(adata, color='blobs', groups=['Zero'])

#this does not
sc.pl.umap(adata, color='blobs', groups='Zero')
```
which gives as an output

```pytb
... storing 'blobs' as categorical

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-47-a9cdfcb56f9d> in <module>()
     13 
     14 #this does not
---> 15 sc.pl.umap(adata, color='blobs', groups='Zero')

~/software/scanpy/scanpy/plotting/tools/embedding.py in umap(adata, color, use_raw, edges, edges_width, edges_color, arrows, arrows_kwds, sort_order, alpha, groups, components, projection, legend_loc, legend_fontsize, legend_fontweight, color_map, palette, frameon, right_margin, size, title, show, save, ax)
    290         show=False,
    291         save=False,
--> 292         ax=ax)
    293     if edges: utils.plot_edges(axs, adata, basis, edges_width, edges_color)
    294     if arrows: utils.plot_arrows(axs, adata, basis, arrows_kwds)

~/software/scanpy/scanpy/plotting/anndata.py in scatter(adata, x, y, color, use_raw, sort_order, alpha, basis, groups, components, projection, legend_loc, legend_fontsize, legend_fontweight, color_map, palette, frameon, right_margin, left_margin, size, title, show, save, ax)
    104             show=show,
    105             save=save,
--> 106             ax=ax)
    107     elif x is not None and y is not None:
    108         if ((x in adata.obs.keys() or x in adata.var.index)

~/software/scanpy/scanpy/plotting/anndata.py in _scatter_obs(adata, x, y, color, use_raw, sort_order, alpha, basis, groups, components, projection, legend_loc, legend_fontsize, legend_fontweight, color_map, palette, frameon, right_margin, left_margin, size, title, show, save, ax)
    409                     raise ValueError('"' + name + '" is invalid!'
    410                                      + ' specify valid name, one of '
--> 411                                      + str(adata.obs[key].cat.categories))
    412                 else:
    413                     iname = np.flatnonzero(adata.obs[key].cat.categories.values == name)[0]

ValueError: "Z" is invalid! specify valid name, one of Index(['Zero', '1', '2', '3', '4'], dtype='object')
```
The last call `sc.pl.umap` gives and error but I would expect it to work. It seems that scanpy iterates over the string `'Zero'` in the last call of `sc.pl.umap`. Of course, it is easy to work around by explicitly passing a list with one element as in the second call, but it took me a while to figure this out.

`sc.logging.print_versions()` prints `scanpy==1.2.2+96.g28f5034 anndata==0.6.4 numpy==1.15.0 scipy==1.1.0 pandas==0.23.0 scikit-learn==0.19.2 statsmodels==0.9.0 python-igraph==0.7.1 louvain==0.6.1`

**Comment by falexwolf** [comment]
Hm, very strange.

Generally: `groups` is somehow reminiscent of times when AnnData didn't have views. Today, I'd say one should simply pass a subsetted AnnData (by default a view). What about deprecating the `groups` parameter?

**Comment by fbnrst** [comment]
For me the difference between passing a subsetted AnnData to using groups would be that when using groups all other cells are plotted but greyed out. I find that usefull sometimes. So I would like to retain the feature.

**Comment by fidelram** [comment]
umap expects a list as group, so it will work if you do:

```python
sc.pl.umap(adata, color='blobs', groups=['Zero'])
````

the improvement that I would consider is to automatically convert a string into a list to avoid the error message.

**Comment by falexwolf** [comment]
Thanks, Fidel. The automatic conversion was indeed missing. I've added it here: https://github.com/theislab/scanpy/commit/9ad11aa4911bd3665b27e32b5a822f3c41274b5a

**Comment by grimwoo** [comment]
> umap expects a list as group, so it will work if you do:
> 
> ```python
> sc.pl.umap(adata, color='blobs', groups=['Zero'])
> ```
> 
> the improvement that I would consider is to automatically convert a string into a list to avoid the error message.

hi, I wonder how could I get the pca figure with the sample marked by different color.
my previous code related is as following :
_adata001 = sc.read_10x_mtx(
adata002=...
...
adata = adata001.concatenate(adata002, adata003, batch_key='sample')
...
sc.pl.pca(adata, color='CST3', save='-6.png', components='1,3', groups='sample)_

However, the figure of this code has no difference compared to "_sc.pl.pca(adata, color='CST3', save='-6.png', components='1,3')_", which means the different samples are not marked by different colors. could you please help me?
