### ISSUE TITLE
scanpy having trouble reading anndata object

### ISSUE THREAD

**Issue by johnjeang** [scverse/scanpy#2310]
---

Hello, I have been working locally with scanpy where everything works well; I can save anndata objects as `.h5ad` files and read them later.  However, when sharing this file with a colleague on a remote server she was unable to read in the file (a file that I have confirmed that I can read in locally) using scanpy.  After some troubleshooting I was unable to identify the problem.

If I had to guess I think one of 2 things could be going wrong--though they both seem unlikely to me

1) She is having issues because her environment is slightly different.  (unlikely because packages look comparable)
2) The file is not getting copied to the server properly and getting corrupted. (unlikely because file size looks correct)

Below I have both the error and the different packages installed in both environments.

Thank you for your time and patience!

```python
adata = sc.read_h5ad('/base/lab/student/acb/sc_labeled.h5ad')
```

```pytb
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/.local/lib/python3.8/site-packages/anndata/_io/utils.py in func_wrapper(elem, *args, **kwargs)
    176         try:
--> 177             return func(elem, *args, **kwargs)
    178         except Exception as e:

~/.local/lib/python3.8/site-packages/anndata/_io/h5ad.py in read_group(group)
    526     if encoding_type:
--> 527         EncodingVersions[encoding_type].check(
    528             group.name, group.attrs["encoding-version"]

/broad/software/free/Linux/redhat_7_x86_64/pkgs/anaconda3_2020.07/lib/python3.8/enum.py in __getitem__(cls, name)
    343     def __getitem__(cls, name):
--> 344         return cls._member_map_[name]
    345 

KeyError: 'dict'

During handling of the above exception, another exception occurred:

AnnDataReadError                          Traceback (most recent call last)
<ipython-input-2-2626ee07d023> in <module>
----> 1 sc.read_h5ad('/xchip/beroukhimlab/michelle/jjeang_plgg/sc_labeled.h5ad')

~/.local/lib/python3.8/site-packages/anndata/_io/h5ad.py in read_h5ad(filename, backed, as_sparse, as_sparse_fmt, chunk_size)
    419                 d[k] = read_dataframe(f[k])
    420             else:  # Base case
--> 421                 d[k] = read_attribute(f[k])
    422 
    423         d["raw"] = _read_raw(f, as_sparse, rdasp)

/broad/software/free/Linux/redhat_7_x86_64/pkgs/anaconda3_2020.07/lib/python3.8/functools.py in wrapper(*args, **kw)
    873                             '1 positional argument')
    874 
--> 875         return dispatch(args[0].__class__)(*args, **kw)
    876 
    877     funcname = getattr(func, '__name__', 'singledispatch function')

~/.local/lib/python3.8/site-packages/anndata/_io/utils.py in func_wrapper(elem, *args, **kwargs)
    181             else:
    182                 parent = _get_parent(elem)
--> 183                 raise AnnDataReadError(
    184                     f"Above error raised while reading key {elem.name!r} of "
    185                     f"type {type(elem)} from {parent}."

AnnDataReadError: Above error raised while reading key '/layers' of type <class 'h5py._hl.group.Group'> from /.
```

#### Versions

The following is my colleague's package version list (the one that isn't working)

<details>

-----
anndata     0.7.8
scanpy      1.8.2
sinfo       0.3.4
-----
PIL                 7.2.0
backcall            0.2.0
bottleneck          1.3.2
cffi                1.14.0
cloudpickle         1.5.0
colorama            0.4.3
cycler              0.10.0
cython_runtime      NA
cytoolz             0.10.1
dask                2022.7.1
dateutil            2.8.1
decorator           4.4.2
fsspec              2022.01.0
google              NA
h5py                3.6.0
igraph              0.9.9
ipykernel           5.3.2
ipython_genutils    0.2.0
jedi                0.17.1
jinja2              2.11.2
joblib              0.16.0
kiwisolver          1.2.0
leidenalg           0.8.0
llvmlite            0.38.1
louvain             0.7.0
markupsafe          1.1.1
matplotlib          3.5.2
mpl_toolkits        NA
natsort             8.1.0
numba               0.55.2
numexpr             2.7.1
numpy               1.21.6
packaging           21.3
pandas              1.4.0
parso               0.7.0
pexpect             4.8.0
pickleshare         0.7.5
pkg_resources       NA
prompt_toolkit      3.0.5
psutil              5.7.0
ptyprocess          0.6.0
pyarrow             8.0.0
pygments            2.6.1
pyparsing           2.4.7
pytoml              NA
pytz                2020.1
scipy               1.5.0
setuptools_scm      NA
six                 1.14.0
sklearn             1.0.2
sphinxcontrib       NA
storemagic          NA
tables              3.6.1
tblib               1.6.0
texttable           1.6.4
threadpoolctl       2.1.0
tlz                 0.10.1
toolz               0.10.0
tornado             6.0.4
traitlets           4.3.3
typing_extensions   NA
wcwidth             0.2.5
yaml                5.3.1
zmq                 19.0.1
zope                NA
-----
IPython             7.16.1
jupyter_client      6.1.6
jupyter_core        4.6.3
jupyterlab          2.1.5
notebook            6.0.3
-----
Python 3.8.3 (default, Jul  2 2020, 16:21:59) [GCC 7.3.0]
Linux-3.10.0-1160.76.1.el7.x86_64-x86_64-with-glibc2.10
52 logical CPU cores, x86_64
-----
</details>

The following is my package version list

<details>

-----
anndata     0.8.0
scanpy      1.7.0
sinfo       0.3.4
-----
OpenSSL                     21.0.0
PIL                         8.4.0
absl                        NA
anyio                       NA
appdirs                     1.4.4
appnope                     0.1.2
attr                        21.2.0
babel                       2.9.1
backcall                    0.2.0
beta_ufunc                  NA
binom_ufunc                 NA
bioservices                 1.9.0
bottleneck                  1.3.2
brotli                      NA
bs4                         4.10.0
bson                        NA
cairo                       NA
cattr                       NA
certifi                     2021.10.08
cffi                        1.14.6
chardet                     4.0.0
charset_normalizer          2.0.4
cloudpickle                 2.0.0
colorama                    0.4.4
colorlog                    NA
cryptography                3.4.8
cycler                      0.10.0
cython_runtime              NA
cytoolz                     0.11.0
dask                        2021.10.0
dateutil                    2.8.2
debugpy                     1.4.1
decorator                   5.1.0
defusedxml                  0.7.1
deprecate                   0.3.1
dill                        0.3.5.1
docutils                    0.17.1
dunamai                     1.11.1
easydev                     0.12.0
entrypoints                 0.3
fsspec                      2021.08.1
get_version                 3.5.4
google                      NA
gridfs                      NA
gseapy                      0.10.8
h5py                        3.6.0
html5lib                    1.1
idna                        3.2
igraph                      0.9.11
importlib_metadata          NA
ipykernel                   6.4.1
ipython_genutils            0.2.0
ipywidgets                  7.6.5
itsdangerous                2.0.1
jedi                        0.18.0
jinja2                      2.11.3
joblib                      1.1.0
json5                       NA
jsonschema                  3.2.0
jupyter_server              1.4.1
jupyterlab_server           2.8.2
kiwisolver                  1.3.1
legacy_api_wrap             1.2
leidenalg                   0.8.9
llvmlite                    0.36.0
lxml                        4.6.3
markupsafe                  1.1.1
matplotlib                  3.4.3
matplotlib_inline           NA
mpl_toolkits                NA
natsort                     8.1.0
nbclassic                   NA
nbformat                    5.1.3
nbinom_ufunc                NA
numba                       0.53.0
numexpr                     2.7.3
numpy                       1.22.3
opt_einsum                  v3.3.0
packaging                   21.0
pandas                      1.4.3
parso                       0.8.2
pexpect                     4.8.0
pickleshare                 0.7.5
pkg_resources               NA
prometheus_client           NA
prompt_toolkit              3.0.20
psutil                      5.8.0
ptyprocess                  0.7.0
pvectorc                    NA
pyarrow                     8.0.0
pycparser                   2.20
pydev_ipython               NA
pydevconsole                NA
pydevd                      2.4.1
pydevd_concurrency_analyser NA
pydevd_file_utils           NA
pydevd_plugins              NA
pydevd_tracing              NA
pyexpat                     NA
pygments                    2.10.0
pylab                       NA
pymongo                     4.1.0
pyparsing                   3.0.4
pyro                        1.8.1
pyrsistent                  NA
pytorch_lightning           1.5.10
pytz                        2021.3
regex                       2.5.97
requests                    2.26.0
requests_cache              0.9.4
rich                        NA
scipy                       1.7.1
scvelo                      0.2.4
scvi                        0.12.0
send2trash                  NA
setuptools_scm              NA
six                         1.16.0
sklearn                     1.0.2
sniffio                     1.2.0
socks                       1.7.1
soupsieve                   2.2.1
sphinxcontrib               NA
storemagic                  NA
tables                      3.6.1
tblib                       1.7.0
tensorboard                 2.8.0
texttable                   1.6.4
threadpoolctl               2.2.0
tlz                         0.11.0
toolz                       0.11.1
torch                       1.11.0
torchmetrics                0.8.1
tornado                     6.1
tqdm                        4.62.3
traitlets                   5.1.0
typing_extensions           NA
ujson                       4.0.2
url_normalize               1.4.3
urllib3                     1.26.7
utils                       NA
wcwidth                     0.2.5
webencodings                0.5.1
wrapt                       1.12.1
yaml                        5.4.1
zipp                        NA
zmq                         22.2.1
zope                        NA
-----
IPython             7.29.0
jupyter_client      6.1.12
jupyter_core        4.8.1
jupyterlab          3.2.1
notebook            6.4.5
-----
Python 3.9.7 (default, Sep 16 2021, 08:50:36) [Clang 10.0.0 ]
macOS-10.16-x86_64-i386-64bit
10 logical CPU cores, i386

</details>

**Comment by FlorianBarkmann** [comment]
Hi, I think the problem is caused by the two different versions of anndata used. We had similar issues when using anndata 0.7 and 0.8 together. Try to upgrade the version to 0.8.

Best
Florian
