### ISSUE TITLE
Option for external.pp.harmony_integrate() to produce a new counts matrix? 

### ISSUE THREAD

**Issue by alexlenail** [scverse/scanpy#2314]
`sc.external.pp.harmony_integrate(adata, 'Batch')` only adds an obsm key `'X_pca_harmony'`. In order to analyze values for a specific gene after harmony, you would need to multiply `X_pca_harmony` by a loadings matrix, but `adata.varm` doesn't seem to get a `harmony_PCs` to accompany vanilla `adata.varm['PCs']`. 

Is there a method I'm missing to analyze a harmony-corrected counts matrix in scanpy? If so, I'd love to see it documented. If not, I'd love to see it added.

**Comment by alexlenail** [comment]
@esrice

**Comment by esrice** [comment]
Hi! Harmony does not adjust the counts matrix at all, or even read it. Rather, it takes principal components as input, adjusts them to correct for batch, and outputs a modified set of PCs.

Here is the paper that explains how it works: https://www.nature.com/articles/s41592-019-0619-0

(I wasn't involved in coming up with this method or implementing it, just making it interoperable with scanpy, for the record)

**Comment by alexlenail** [comment]
Thanks for getting back @esrice! 

I think I see now -- does that mean I should multiply the `X_pca_harmony` by the _original_ PC loadings to get the imputed counts?

**Comment by esrice** [comment]
No, there is no way to get any sort of correction of the counts with this method; it's just for correcting the principal components. You can use `X_pca_harmony` for downstream analyses that by default use `X_pca`, such as computing the neighbor graph.

**Comment by esrice** [comment]
Here's a paper that compares various integration methods, with some nice figures showing which ones output corrected counts vs. corrected projections:

https://www.nature.com/articles/s41592-021-01336-8

You could use one of the methods that outputs corrected counts if you need corrected counts for some reason.

**Comment by alexlenail** [comment]
Thanks for this clarification @esrice
