### ISSUE TITLE
Does `return_fig` in `sc.pl.spatial` work?

### ISSUE THREAD

**Issue by alam-shahul** [scverse/scanpy#2316]
- [ ] Additional function parameters / changed functionality / changed defaults?
- [ ] New analysis tool: A simple analysis tool you have been using and are missing in `sc.tools`?
- [x] New plotting function: A kind of plot you would like to seein `sc.pl`?
- [ ] External tools: Do you know an existing package that should go into `sc.external.*`?
- [ ] Other?

It seems like there is an argument in `sc.pl.spatial` to return the Matplotlib figure used for plotting. However, from inspecting the source code, I think that this doesn't really do that; it seems more like that argument just makes the function return the Matplotlib Axes instead? For context, I am using `sc.pl.spatial` + `sq.pl.extract` to plot many features on subplots, but I would like to add a "suptitle" to the whole figure.

**Comment by giovp** [comment]
@alam-shahul I'd suggest you to look into the squidpy plotting functionalities here: https://squidpy.readthedocs.io/en/latest/examples.html#plotting and here: https://squidpy.readthedocs.io/en/latest/api/squidpy.pl.spatial_scatter.html#squidpy.pl.spatial_scatter
they cointain an updated version of the scanpy plotting spatial, which will be deprecated. I'll close this comment and please re open one if relevant in squidpy

**Comment by flying-sheep** [comment]
See https://github.com/scverse/scanpy/issues/2331
