### ISSUE TITLE
Problem when plotting 'C3' gene expression

### ISSUE THREAD

**Issue by fbrundu** [scverse/scanpy#232]
Hi,
I have problem when plotting gene expression for the 'C3' gene. I think `scanpy` believes it is a categorical name and plots a single solid color.

Do you know how to solve or workaround this issue?

Thanks,
Francesco

![image](https://user-images.githubusercontent.com/697622/43921658-6427af72-9bea-11e8-920d-41e4aa38499e.png)

**Comment by falexwolf** [comment]
Scanpy only interprets categorical annotation and string annotation with a small number of categories as categorical data. It definitely doesn't do so for numerical data. Can you give a bit more details? I never observed your issue.

**Comment by wflynny** [comment]
@fbrundu Are you certain cells express that gene?  Something like
```{python}
adata[:, 'C3'].X.sum()
# or
adata.raw[:, 'C3'].X.sum()
```

**Comment by fbrundu** [comment]
Sorry for the late reply.
Yes cells express such gene:

```
In [10]: pd.Series(adata[:, 'C3'].X).describe(
    ...: )
Out[10]:
count    6297.000000
mean        4.374116
std         3.324011
min         0.000000
25%         0.000000
50%         5.107668
75%         6.598697
max        10.175991
dtype: float64

In [11]: adata[:, 'C3'].X.sum()
Out[11]: ArrayView(27543.812, dtype=float32)
```

Other possible issues?

**Comment by falexwolf** [comment]
I'm having a very hard time of understanding what should go wrong here. No clue whatsoever. 🙈

**Comment by jpreall** [comment]
For what it's worth, I and a few others have also run into this issue with this exact same gene...

**Comment by fidelram** [comment]
I can validate this problem. Actually, any value from C0 to C9 causes the problem but each case gets a different color.

![image](https://user-images.githubusercontent.com/4964309/44329411-a82ce700-a464-11e8-940c-c85a67bf579a.png)

**Comment by falexwolf** [comment]
Ok, good! Then this means that 'C0' is a valid `matplotlib` color string. I'll catch this case manually and then it will work! Thanks for the clarification everyone.

**Comment by falexwolf** [comment]
Is fixed via https://github.com/theislab/scanpy/pull/237.

**Comment by fbrundu** [comment]
Unfortunately, the fix is incomplete: for those specific genes the name of gene is missing from the plot (no title for the scatter).

**Comment by falexwolf** [comment]
Oh, damn, why did I miss this.
