### ISSUE TITLE
Size adjustment for dotplot

### ISSUE THREAD

**Issue by LeonHafner** [scverse/scanpy#2327]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.
---
Hi together,
I have a question/bug report regarding the `sc.pl.dotplot` function and the size of the plot.
Normally all my plots are adjusted by their size in my notebook after running `rcParams['figure.figsize'] = (X, X)` command, but this seems not to be true for the dotplot. In the minimal code sample the UMAP changes the size after running rcParams, the dotplot does not, even if stated like that in the scanpy API:

![Screenshot 2022-09-14 at 11 51 33](https://user-images.githubusercontent.com/60394289/190122470-1862b35f-1bf2-42a1-9b10-13f14005c987.png)

(Please also note the two typos in the API - "s" and one "'" is missing)

### Minimal code sample

```python
import sys
import scanpy as sc
from matplotlib import rcParams

adata = sc.datasets.pbmc3k_processed()

sc.pl.umap(adata)

sc.pl.dotplot(adata, var_names=adata.var_names[:20], groupby='louvain')

rcParams['figure.figsize'] = (10, 10)

sc.pl.umap(adata)

sc.pl.dotplot(adata, var_names=adata.var_names[:20], groupby='louvain')
```
Please let me know if scanpy behaves the same for you in this situation and if it is intended to be like this.

Thanks a lot!

#### Versions

<details>

-----
anndata     0.8.0
scanpy      1.9.1
-----
PIL                 8.0.1
backcall            0.2.0
cffi                1.14.3
cloudpickle         1.6.0
cycler              0.10.0
cython_runtime      NA
cytoolz             0.11.0
dask                2.30.0
dateutil            2.8.1
decorator           4.4.2
google              NA
h5py                3.7.0
igraph              0.9.11
ipykernel           5.3.4
ipython_genutils    0.2.0
jedi                0.17.2
joblib              0.17.0
kiwisolver          1.3.0
leidenalg           0.8.10
llvmlite            0.34.0
louvain             0.7.1
matplotlib          3.5.2
mpl_toolkits        NA
natsort             8.1.0
numba               0.51.2
numexpr             2.7.1
numpy               1.19.2
packaging           20.4
pandas              1.1.3
parso               0.7.0
pexpect             4.8.0
pickleshare         0.7.5
pkg_resources       NA
prompt_toolkit      3.0.8
psutil              5.7.2
ptyprocess          0.6.0
pygments            2.7.2
pyparsing           2.4.7
pytz                2020.1
scipy               1.5.2
session_info        1.0.0
six                 1.15.0
sklearn             1.0.2
storemagic          NA
tblib               1.7.0
texttable           1.6.4
threadpoolctl       2.1.0
tlz                 0.11.0
toolz               0.11.1
tornado             6.0.4
traitlets           5.0.5
typing_extensions   NA
wcwidth             0.2.5
yaml                6.0
zipp                NA
zmq                 19.0.2
-----
IPython             7.19.0
jupyter_client      6.1.7
jupyter_core        4.7.0
jupyterlab          2.2.6
notebook            6.1.4
-----
Python 3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]
Linux-5.15.0-47-generic-x86_64-with-debian-10.13

</details>

**Comment by jdime** [comment]
Hi @LeonHafner ,

In case you still need it, try passing parameter figsize `sc.pl.dotplot(..., figsize=(X,Y))`. It worked for me with Scanpy v1.9.6. Cheers.

**Comment by flying-sheep** [comment]
Good to hear that this is fixed! Sorry for not responding here in the first place
