### ISSUE TITLE
mnnpy using raw data

### ISSUE THREAD

**Issue by terooatt** [scverse/scanpy#233]
I sucessfully used mnn to correct batch effect for my datasets but I would like to know when and how can I create a copy so as to access the raw data which will be used for differential genes expression analysis for instance. In one of the scanpy tutorial it shows how to create a copy of the raw data that can be used for latter analysis by typing adata.raw = sc.pp.log1p(adata, copy=True) but when can I do that with mnn.

I used the following cmd to create the batch corrected files. How can I create the adata.raw copy?

corrected = sc.pp.mnn_correct(adata1,adata2,adata3,adata4, batch_categories=["ba1", "ba2","ba3","ba4"])
adata_corrected = corrected[0]

adata_corrected.write('./write1/mnn_corrected.h5ad')

Thank you very much.

**Comment by terooatt** [comment]
I figure it out. Never mind thanks.

**Comment by falexwolf** [comment]
Sorry about the late response and glad that you figured it out!
