### ISSUE TITLE
Leiden clustering not showing up in adata.obs

### ISSUE THREAD

**Issue by julie-jch** [scverse/scanpy#2330]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

I have the following anndata
```
AnnData object with n_obs × n_vars = 28752 × 22603
    obs: 'batch', 'cluster1_psc', 'all_fib_types', 'psc_batch_temp', 'batch_combined', 'overall', 'cluster1_kpc', 'kpc_batch_temp', 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt'
    var: 'gene_ids', 'feature_types', 'n_cells', 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts'
    uns: 'genome'
```

When I run leiden clustering it shows that the parameters were added

```computing PCA
    on highly variable genes
    with n_comps=30
    finished (0:01:25)
computing neighbors
    finished: added to `.uns['neighbors']`
    `.obsp['distances']`, distances for each pair of neighbors
    `.obsp['connectivities']`, weighted adjacency matrix (0:00:04)
computing UMAP
    finished: added
    'X_umap', UMAP coordinates (adata.obsm) (0:00:18)
running Leiden clustering
    finished: found 23 clusters and added
    'NoBatchCorr', the cluster labels (adata.obs, categorical) (0:00:04)
```
But when I check my anndata, none present. As such if I try to generate a umap image I get the following error
```
AnnData object with n_obs × n_vars = 28752 × 22603
    obs: 'batch', 'cluster1_psc', 'all_fib_types', 'psc_batch_temp', 'batch_combined', 'overall', 'cluster1_kpc', 'kpc_batch_temp', 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'Norm_Factor'
    var: 'gene_ids', 'feature_types', 'n_cells', 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection'
    uns: 'genome', 'log1p', 'hvg'
```

```
sc.pl.umap(adata,color=['overall'], palette=colors_list)
```
```pytb
    raise KeyError(f"Could not find '{basis}' or 'X_{basis}' in .obsm")

KeyError: "Could not find 'umap' or 'X_umap' in .obsm"
```

#### Versions

<details>

[-----
anndata     0.8.0
scanpy      1.9.1
-----
AlexFunctions                               NA
JonFunctions                                NA
PIL                                         9.2.0
PyQt5                                       NA
aa8f2297d25b4dc6fd3d98411eb3ba53823c4f42    NA
absl                                        NA
astunparse                                  1.6.3
atomicwrites                                1.4.1
autoreload                                  NA
backcall                                    0.2.0
beta_ufunc                                  NA
binom_ufunc                                 NA
brotli                                      NA
bs4                                         4.11.1
certifi                                     2022.09.14
cffi                                        1.15.1
chardet                                     5.0.0
charset_normalizer                          2.1.1
cloudpickle                                 2.2.0
colorama                                    0.4.5
cycler                                      0.10.0
cython_runtime                              NA
dateutil                                    2.8.2
debugpy                                     1.6.3
decorator                                   5.1.1
defusedxml                                  0.7.1
dill                                        0.3.5.1
entrypoints                                 0.4
flatbuffers                                 2.0
gast                                        0.5.3
google                                      NA
h5py                                        3.7.0
hypergeom_ufunc                             NA
idna                                        3.3
igraph                                      0.9.11
import_all                                  NA
ipykernel                                   6.15.3
jedi                                        0.18.1
joblib                                      1.2.0
keras                                       2.8.0
keras_preprocessing                         1.1.2
kiwisolver                                  1.4.4
leidenalg                                   0.8.10
llvmlite                                    0.38.1
louvain                                     0.7.1
lxml                                        4.9.1
matplotlib                                  3.5.3
matplotlib_inline                           0.1.6
mpl_toolkits                                NA
natsort                                     8.2.0
nbinom_ufunc                                NA
ncf_ufunc                                   NA
numba                                       0.55.2
numpy                                       1.22.4
opt_einsum                                  v3.3.0
packaging                                   21.3
pandas                                      1.4.4
params                                      NA
parso                                       0.8.3
pexpect                                     4.8.0
pickleshare                                 0.7.5
pkg_resources                               NA
plotly                                      5.10.0
prompt_toolkit                              3.0.31
psutil                                      5.9.2
ptyprocess                                  0.7.0
pycparser                                   2.21
pydev_ipython                               NA
pydevconsole                                NA
pydevd                                      2.8.0
pydevd_file_utils                           NA
pydevd_plugins                              NA
pydevd_tracing                              NA
pygments                                    2.13.0
pynndescent                                 0.5.7
pyparsing                                   3.0.9
pytz                                        2022.2.1
requests                                    2.28.1
scipy                                       1.9.1
seaborn                                     0.12.0
session_info                                1.0.0
setuptools                                  65.3.0
sip                                         NA
six                                         1.16.0
sklearn                                     1.1.2
socks                                       1.7.1
soupsieve                                   2.3.2.post1
sphinxcontrib                               NA
spyder                                      5.3.3
spyder_kernels                              2.3.3
spydercustomize                             NA
statsmodels                                 0.13.2
storemagic                                  NA
tensorboard                                 2.8.0
tensorflow                                  2.8.0
termcolor                                   1.1.0
texttable                                   1.6.4
threadpoolctl                               3.1.0
tornado                                     6.2
tqdm                                        4.64.1
traitlets                                   5.4.0
typing_extensions                           NA
umap                                        0.5.3
unicodedata2                                NA
urllib3                                     1.26.11
wcwidth                                     0.2.5
wrapt                                       1.14.1
wurlitzer                                   3.0.2
yaml                                        6.0
zipp                                        NA
zmq                                         24.0.0
-----
IPython             7.33.0
jupyter_client      7.3.5
jupyter_core        4.11.1
-----
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21) [GCC 10.3.0]
Linux-5.4.0-124-generic-x86_64-with-glibc2.31
-----
Session information updated at 2022-09-16 10:24]

</details>

**Comment by julie-jch** [comment]
I've been able to pin down the culprit.
Excluding this line ```adata = adata[:, adata.var.highly_variable]``` allows Leiden clustering to populate

**Comment by giovp** [comment]
hi @julie-jch whats the lines of code you used to generate that result?

**Comment by julie-jch** [comment]
This is what I'm running
```
bcType = 'NobatchCorr'
sc.pp.normalize_total(adata, target_sum=1e4, exclude_highly_expressed=True, key_added='Norm_Factor')
sc.pp.log1p(adata)
adata.raw = adata
sc.pp.highly_variable_genes(adata, n_top_genes=4000, batch_key='batch')
#adata = adata[:, adata.var.highly_variable]
sc.pp.scale(adata, max_value=10)
sc.pp.pca(adata, use_highly_variable=True, svd_solver='full', n_comps =n_pcs, random_state=10)
sc.pp.neighbors(adata, n_pcs=n_pcs, use_rep='X_pca', random_state=10)
sc.tl.umap(adata, random_state=10)
sc.tl.leiden(adata,resolution=resolution, key_added=bcType, random_state=10)
```
The code never fails, but Leiden parameters are not present in the adata as it should. Running
```
sc.pl.umap(adata,color=['overall'], palette=colors_list)
```
gives the above error, but if I comment out ```adata = adata[:, adata.var.highly_variable]``` it works, I'm unsure why atm.

**Comment by giovp** [comment]
hi @julie-jch , 
it could be the reason is that the anndata is a view. Try with 
```
adata = adata[:, adata.var.highly_variable].copy()
```

but also, for the subsequent functions you don't need to subset by high var genes since they have arguments taht specificy whether to use them or not. E.g. pca uses it by default: 

https://scanpy.readthedocs.io/en/stable/generated/scanpy.pp.pca.html#scanpy.pp.pca

**Comment by julie-jch** [comment]
Thank you, I guess I can compare the matrix after running copy() and after without and see how much different the two are.
