### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'location'

### ISSUE THREAD

**Issue by shashkat** [scverse/scanpy#2332]
---

Hello there, I am relatively new at scanpy, and am getting the following error upon trying to plot the PCA components. Even though I am getting a plot, it is accompanied by this error. Could someone explain what could be the reason behind it? Thanks!

### Minimal code sample (that we can copy&paste without having any data)

```python
# Your code here

# making a simple adata object
data = {'gene1':[1,2,3],
   'gene2':[3,2,2],
   'gene3':[1,4,1]}
df = pd.DataFrame(data)
dft = df.T
adata = anndata.AnnData(X= df.iloc[0:,0:],
                        obs= df.iloc[0:,0:1],
                        var= dft.iloc[0:,0:1])

# computing principal component analysis
sc.tl.pca(adata, svd_solver='arpack')
sc.pl.pca(adata, color='gene2')


```

```pytb
[Paste the error output produced by the above code here]

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-10-876f2bccfb2c>](https://localhost:8080/#) in <module>
----> 1 sc.pl.pca(adata, color='gene2')

5 frames
[/usr/local/lib/python3.7/dist-packages/scanpy/plotting/_tools/scatterplots.py](https://localhost:8080/#) in pca(adata, annotate_var_explained, show, return_fig, save, **kwargs)
    870     if not annotate_var_explained:
    871         return embedding(
--> 872             adata, 'pca', show=show, return_fig=return_fig, save=save, **kwargs
    873         )
    874     else:

[/usr/local/lib/python3.7/dist-packages/scanpy/plotting/_tools/scatterplots.py](https://localhost:8080/#) in embedding(adata, basis, color, gene_symbols, use_raw, sort_order, edges, edges_width, edges_color, neighbors_key, arrows, arrows_kwds, groups, components, dimensions, layer, projection, scale_factor, color_map, cmap, palette, na_color, na_in_legend, size, frameon, legend_fontsize, legend_fontweight, legend_loc, legend_fontoutline, colorbar_loc, vmax, vmin, vcenter, norm, add_outline, outline_width, outline_color, ncols, hspace, wspace, title, show, save, ax, return_fig, **kwargs)
    451         elif colorbar_loc is not None:
    452             pl.colorbar(
--> 453                 cax, ax=ax, pad=0.01, fraction=0.08, aspect=30, location=colorbar_loc
    454             )
    455 

[/usr/local/lib/python3.7/dist-packages/matplotlib/pyplot.py](https://localhost:8080/#) in colorbar(mappable, cax, ax, **kw)
   2007       =========  =======================================================
   2008 
-> 2009     .. rubric:: Footnotes
   2010 
   2011     .. [#] Rainbow colormaps, ``jet`` in particular, are considered a poor

[/usr/local/lib/python3.7/dist-packages/matplotlib/figure.py](https://localhost:8080/#) in colorbar(self, mappable, cax, ax, use_gridspec, **kw)
   2236         for ax in self.axes:
   2237             if not isinstance(ax, SubplotBase):
-> 2238                 # Check if sharing a subplots axis
   2239                 if isinstance(ax._sharex, SubplotBase):
   2240                     ax._sharex.update_params()

/usr/local/lib/python3.7/dist-packages/matplotlib/colorbar.py in colorbar_factory(cax, mappable, **kwargs)

[/usr/local/lib/python3.7/dist-packages/matplotlib/colorbar.py](https://localhost:8080/#) in __init__(self, ax, mappable, **kw)
   1228         they will need to be customized again.  However, if the norm only
   1229         changes values of *vmin*, *vmax* or *cmap* then the old formatter
-> 1230         and locator will be preserved.
   1231         """
   1232 

TypeError: __init__() got an unexpected keyword argument 'location'

```

#### Versions

<details>

[Paste the output of scanpy.logging.print_versions() leaving a blank line after the details tag]

anndata     0.8.0
scanpy      1.9.1

PIL                         7.1.2
astor                       0.8.1
backcall                    0.2.0
beta_ufunc                  NA
binom_ufunc                 NA
cached_property             1.5.2
certifi                     2022.06.15
cffi                        1.15.1
cloudpickle                 1.5.0
cycler                      0.10.0
cython_runtime              NA
dask                        2022.02.0
dateutil                    2.8.2
debugpy                     1.0.0
decorator                   4.4.2
fsspec                      2022.8.2
google                      NA
h5py                        3.1.0
httplib2                    0.17.4
ipykernel                   5.3.4
ipython_genutils            0.2.0
jinja2                      2.11.3
joblib                      1.1.0
kiwisolver                  1.4.4
llvmlite                    0.39.1
markupsafe                  2.0.1
matplotlib                  3.2.2
mpl_toolkits                NA
natsort                     5.5.0
nbinom_ufunc                NA
numba                       0.56.2
numexpr                     2.8.3
numpy                       1.21.6
packaging                   21.3
pandas                      1.3.5
pexpect                     4.8.0
pickleshare                 0.7.5
pkg_resources               NA
portpicker                  NA
prompt_toolkit              2.0.10
psutil                      5.4.8
ptyprocess                  0.7.0
pyarrow                     6.0.1
pydev_ipython               NA
pydevconsole                NA
pydevd                      2.0.0
pydevd_concurrency_analyser NA
pydevd_file_utils           NA
pydevd_plugins              NA
pydevd_tracing              NA
pygments                    2.6.1
pyparsing                   3.0.9
pytz                        2022.2.1
scipy                       1.7.3
session_info                1.0.0
sitecustomize               NA
six                         1.15.0
sklearn                     1.0.2
socks                       1.7.1
sphinxcontrib               NA
storemagic                  NA
tblib                       1.7.0
threadpoolctl               3.1.0
tlz                         0.12.0
toolz                       0.12.0
tornado                     5.1.1
traitlets                   5.1.1
typing_extensions           NA
wcwidth                     0.2.5
yaml                        6.0
zipp                        NA
zmq                         23.2.1

IPython             7.9.0
jupyter_client      6.1.12
jupyter_core        4.11.1
notebook            5.3.1

Python 3.7.14 (default, Sep  8 2022, 00:06:44) [GCC 7.5.0]
Linux-5.10.133+-x86_64-with-Ubuntu-18.04-bionic

Session information updated at 2022-09-16 19:14

</details>
![error](https://user-images.githubusercontent.com/72993520/190715283-6ae522e3-dd86-4179-956b-196f3f2c845b.png)

**Comment by HaniceSun** [comment]
I just had the same issue because I downgraded my matplotlib elsewhere.
So it should work if you upgrade your matplotlib.

**Comment by moonbyul-99** [comment]
It seems that you are using an online notebook. I also received this error on Colab. But when I ran the same code on the PC terminal, everything went well.

**Comment by shashkat** [comment]
Thanks for the suggestions and sorry for the late response. Yes, I was using google colab, and a newer version of matplotlib did the trick. I upgraded to the 3.5.3 version of matplotlib, and restarted the runtime, and that did the trick, thanks!
