### ISSUE TITLE
python-igraph 0.10 breaks leiden

### ISSUE THREAD

**Issue by xiasijian** [scverse/scanpy#2339]
sc.tl.leiden(adata,use_weights=False) ERROR
![image](https://user-images.githubusercontent.com/39158528/192767636-991ed282-cf6c-46be-841f-389007976b16.png)

**Comment by jamestwebber** [comment]
I also saw this with `python-igraph` version 0.10. Downgrading to `0.9.9` fixed the issue.

**Comment by xiasijian** [comment]
Thanks a lot.



---Original---
From: "James ***@***.***&gt;
Date: Thu, Sep 29, 2022 00:06 AM
To: ***@***.***&gt;;
Cc: "Sijian ***@***.******@***.***&gt;;
Subject: Re: [scverse/scanpy] sc.tl.leiden(adata,use_weights=False) (Issue#2339)




 
I also saw this with python-igraph version 0.10. Downgrading to 0.9.9 fixed the issue.

**Comment by aqlkzf** [comment]
Thanks for your help. It works fine now! I have tried several times this day, but end up with failure.  It works fine now following your method!

**Comment by erieslee** [comment]
Same error occurred when using the default leiden with weights as well; downgrading python-igraph to 0.9.11 fixed the issue.
leidenalg is dependent on python-igraph (0.10.0 for my conda) and igraph (0.9.10), and I suppose the version discrepancy caused the problem.

Or you can replace tl.leiden with leiden algorithm in python-igraph:

adjacency = sc._utils._choose_graph(adata, obsp=None, neighbors_key=None)
g = sc._utils.get_igraph_from_adjacency(adjacency)
clustering = g.community_leiden(objective_function='modularity', weights='weight', resolution_parameter=0.5)
adata.obs['leiden_igraph_weight'] = pd.Series(clustering.membership, dtype='category', index=adata.obs.index)

sc.pl.umap(adata, color='leiden_igraph_weight')

**Comment by flying-sheep** [comment]
Fixed in leidenalg 0.9.0: https://github.com/vtraag/leidenalg/issues/112

**Comment by handesome** [comment]
![image](https://github.com/scverse/scanpy/assets/56467838/aa14c824-0d86-467c-a8e3-8e8dab2cc4a7)
could anyone give some advice？the versions are below
leidenalg                 0.8.1
igraph                    0.9.9
python-igraph             0.9.9。
Thanks

**Comment by flying-sheep** [comment]
the newest versions of leidenalg and igraph should be compatible with each other. update both, e.g. `pip install -U leidenalg igraph`

`python-igraph` is no longer necessary, you can remove it.

**Comment by handesome** [comment]
> the newest versions of leidenalg and igraph should be compatible with each other. update both, e.g. `pip install -U leidenalg igraph`
> 
> `python-igraph` is no longer necessary, you can remove it.

Thanks for your help!that‘s works！！！
