### ISSUE TITLE
module 'scanpy' has no attribute 'tl'

### ISSUE THREAD

**Issue by coffeei1i** [scverse/scanpy#2343]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [x] (optional) I have confirmed this bug exists on the master branch of scanpy.

---
module 'scanpy' has no attribute 'tl'

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can copy&paste without having any data)

```python
# Your code here
```
adata_sc=diopy.input.read_h5(file ='/home/shpc_100862/xyh_desktop/2022918mouse_data/Reference/st_CTXmd.h5')
scanpy.tl.rank_genes_groups(adata_sc,groupby="annotation",use_raw=False)
markers_df=pd.DataFrame(adata_sc.uns["rank_genes_groups"]["names"]).iloc[0:100,:]
markers=list(np.unique(markers_df.melt().value.values))
```pytb
[Paste the error output produced by the above code here]
```
AttributeError                            Traceback (most recent call last)
Input In [18], in <cell line: 4>()
      8 adata_st=diopy.input.read_h5(file = path)
      9 adata_sc=diopy.input.read_h5(file ='/home/shpc_100862/xyh_desktop/2022918mouse_data/Reference/st_CTXmd.h5')
---> 10 scanpy.tl.rank_genes_groups(adata_sc,groupby="annotation",use_raw=False)
     11 markers_df=pd.DataFrame(adata_sc.uns["rank_genes_groups"]["names"]).iloc[0:100,:]
     12 markers=list(np.unique(markers_df.melt().value.values))

AttributeError: module 'scanpy' has no attribute 'tl'
#### Versions
1.9.1
<details>

[Paste the output of scanpy.logging.print_versions() leaving a blank line after the details tag]
AttributeError: module 'scanpy' has no attribute 'logging'
</details>

**Comment by Zethson** [comment]
How did you import scanpy?

**Comment by Zethson** [comment]
Reopen if more info is available, please.
