### ISSUE TITLE
logistic regression paramater in rank genes groups

### ISSUE THREAD

**Issue by jayypaul** [scverse/scanpy#235]
```
sc.tl.rank_genes_groups(adata,groupby='louvain', method='logreg')
```
ranking genes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scanpy/tools/rank_genes_groups.py", line 191, in rank_genes_groups
    scores = scores_all[igroup]
IndexError: index 1 is out of bounds for axis 0 with size 1

Have tried finding similar situations online but can't seem to debug this one. 
Sorry if I'm on this issues page a lot, but I'm using scanpy relentlessly lately :P 

Any suggestions appreciated.

**Comment by jayypaul** [comment]
The default method does work however ...

**Comment by falexwolf** [comment]
Hm, sorry for the late response. I can't reproduce this. Does it work for you in the standard clustering tutorial?

**Comment by jayypaul** [comment]
Sorry for my late response as well. I reloaded dataset and tried again. It worked, sometimes this is the case. 

Thanks!
