### ISSUE TITLE
Can I use X_pca_harmony instead of X_pca for sc.tl.ingest? 

### ISSUE THREAD

**Issue by melancholy12** [scverse/scanpy#2351]
If I used the X_pca_harmony, it gave us the error.

![image](https://user-images.githubusercontent.com/97800939/195247592-f02e1342-5d29-4654-9c59-1ec35dd21913.png)

**Comment by melancholy12** [comment]
The error happened because the ingest cannot use neighbors generated from harmony.

**Comment by hyjforesight** [comment]
do this in prior
`adata.obsm['X_pca']=adata.obsm['X_pca_harmony']`
