### ISSUE TITLE
rapids method for leiden clustering

### ISSUE THREAD

**Issue by YubinXie** [scverse/scanpy#2358]
- [x] Additional function parameters / changed functionality / changed defaults?
- [ ] New analysis tool: A simple analysis tool you have been using and are missing in `sc.tools`?
- [ ] New plotting function: A kind of plot you would like to seein `sc.pl`?
- [ ] External tools: Do you know an existing package that should go into `sc.external.*`?
- [ ] Other?

hi scanpy team,

it is great to have rapids/gpu version of knn and umap that it has made my millions cell analysis much faster. however clustering is still very slow. i wonder if scanpy can support rapids leiden clustering. thanks!

**Comment by YubinXie** [comment]
it seems NVDIA has the codes ready and it would be great to have that in scanpy ecosystem.

https://github.com/NVIDIA-Genomics-Research/rapids-single-cell-examples/blob/master/notebooks/rapids_scanpy_funcs.py

**Comment by Zethson** [comment]
@YubinXie would you be able to submit a PR for this?

**Comment by hyjforesight** [comment]
looking forward to it!

**Comment by YubinXie** [comment]
hi, it is actually just one line code. here it is:
ad['leiden'] = rapids_scanpy_funcs.leiden(ad)

rapids_scanpy_funcs.leiden can be downloaded from the link
