### ISSUE TITLE
"Segmentation fault (core dumped)" Error for step "sc.pp.neighbors"

### ISSUE THREAD

**Issue by JuneMeng** [scverse/scanpy#2361]
Is it because I have too many cells? But no memory error is reported

```pycon
>>> adata
AnnData object with n_obs × n_vars = 1493240 × 4489
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'percent.mt', 'nCount_nFeature_ratio', 'brain_area', 'batch'
    var: 'features', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'brain_area_colors', 'hvg', 'pca'
    obsm: 'X_pca'
    varm: 'PCs'
```

```python
topPC = 40
n_neigbor = 15
resolution = 0.3
sc.pp.neighbors(adata, n_neighbors=n_neigbor, n_pcs=topPC)
```

```pytb
computing neighbors
    using 'X_pca' with n_pcs = 40
Segmentation fault (core dumped)
### error file: core.212911
```

#### Versions

<details>

WARNING: If you miss a compact list, please try `print_header`!
-----
anndata     0.7.8
scanpy      1.8.2
sinfo       0.3.1
-----
PIL                         8.4.0
anndata                     0.7.8
asciitree                   NA
attr                        21.2.0
backcall                    0.2.0
beta_ufunc                  NA
binom_ufunc                 NA
cffi                        1.15.0
cloudpickle                 2.0.0
colorama                    0.4.4
concurrent                  NA
cycler                      0.10.0
cython_runtime              NA
dask                        2021.11.1
dateutil                    2.8.0
debugpy                     1.5.1
decorator                   5.1.0
defusedxml                  0.7.1
encodings                   NA
entrypoints                 0.3
fasteners                   NA
fsspec                      2021.11.0
genericpath                 NA
h5py                        3.4.0
idna                        3.1
igraph                      0.9.8
ipykernel                   6.5.0
ipython_genutils            0.2.0
ipywidgets                  7.6.5
jedi                        0.18.0
jinja2                      3.0.3
joblib                      1.1.0
jsonschema                  4.2.1
kiwisolver                  1.3.2
leidenalg                   0.8.8
llvmlite                    0.36.0
louvain                     0.7.0
markupsafe                  2.0.1
matplotlib                  3.4.3
mpl_toolkits                NA
natsort                     8.0.0
nbformat                    5.1.3
nbinom_ufunc                NA
ntpath                      NA
numba                       0.53.1
numcodecs                   0.9.1
numexpr                     2.7.3
numpy                       1.21.4
opcode                      NA
packaging                   21.0
pandas                      1.3.4
parso                       0.8.2
pexpect                     4.8.0
pickleshare                 0.7.5
pkg_resources               NA
posixpath                   NA
prometheus_client           NA
prompt_toolkit              3.0.22
psutil                      5.8.0
ptyprocess                  0.7.0
pvectorc                    NA
pyarrow                     9.0.0
pydev_ipython               NA
pydevconsole                NA
pydevd                      2.6.0
pydevd_concurrency_analyser NA
pydevd_file_utils           NA
pydevd_plugins              NA
pydevd_tracing              NA
pydoc_data                  NA
pyexpat                     NA
pygments                    2.10.0
pyparsing                   3.0.6
pyrsistent                  NA
pytz                        2021.3
scanpy                      1.8.2
scipy                       1.7.2
seaborn                     0.11.2
send2trash                  NA
setuptools_scm              NA
sinfo                       0.3.1
six                         1.16.0
sklearn                     1.0.1
sphinxcontrib               NA
sre_compile                 NA
sre_constants               NA
sre_parse                   NA
statsmodels                 0.13.1
tables                      3.6.1
terminado                   0.12.1
texttable                   1.6.4
threadpoolctl               3.0.0
tlz                         0.11.2
toolz                       0.11.2
tornado                     6.1
traitlets                   5.1.1
typing_extensions           NA
wcwidth                     0.2.5
xmlrpc                      NA
yaml                        6.0
zarr                        2.10.2
zmq                         22.3.0
-----
IPython             7.29.0
jupyter_client      7.0.6
jupyter_core        4.9.1
notebook            6.4.5
-----
Python 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46) [GCC 9.4.0]
Linux-4.18.0-80.7.1.el8_0.x86_64-x86_64-with-glibc2.17
224 logical CPU cores, x86_64
-----
Session information updated at 2022-10-24 15:07

</details>

**Comment by lemonysoft** [comment]
I always got a kernel restart when run:

`sc.pp.neighbors(adata, n_neighbors=10, n_pcs=40)`

Also my memory is enough. This error comes from pbmc3k.ipynb file.

**Comment by Zethson** [comment]
Could be related to https://github.com/scverse/scanpy/issues/2359 ?

**Comment by mbuttner** [comment]
Do you happen to use an Apple Mac computer with an Apple Silicon CPU? Then the following [issue](https://github.com/tensorflow/tensorflow/issues/52845) might be related.

**Comment by stela2502** [comment]
I have a similar problem. And this does not seam to be related to any python package version as I have 4 data sets loaded from CellRanger h5 files.
With two of these files the neighbors function works and with two it fails with likely a seg fault as a cpp_abort_hook process takes over. This is REALLY annoying as I also get this problem with a random number of different single cell data sets. I assume there is some issue with a dataset that results in a cpp error.
I do not want to debug that as cpp errors are a pain. Can you guess what the problem might be?
The cpp breaks after the multiprocessor step. The Python process has used my 10 processors to the max for some time, but then fallen back to 100%. So it seams it might be after collecting whatever has been produced in the first multiprocessor step.
Can you tell me what that could be so I can implement a test into my scripts? It also probably would be a good idea if you could implement that test into your package. I'll check the two other links, too. If I do not come back here assume both links were not helpful.

**Comment by stela2502** [comment]
As expected the two other links here were of no use.
I also replictaed the problem in Python (not Jupyter) and get this unhepful message:

scanpy.pp.neighbors(adatas[1])
WARNING: You\u2019re trying to run this on 19151 dimensions of `.X`, if you really want this, set `use_rep='X'`.
         Falling back to preprocessing with `sc.pp.pca` and default params.
Segmentation fault (core dumped)

I know cpp is like this. But I can not even find the core.dump anywhere. Please help!

**Comment by stela2502** [comment]
```
scvelo==0.2.4
loompy==3.0.6
scanpy==1.8.2
igraph==0.9.9
phate==1.0.7
pandas==1.5.0.dev0+268.gbe8d1ec88
re==2.2.1
numpy==1.21.6
h5py==3.7.0
pynndescent==0.5.6
```

**Comment by JuneMeng** [comment]
I have solved the problem with add this code below into "~/.bashrc" file
export OMP_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1

Maybe you can try it!

**Comment by hjrichter** [comment]
I'm having the same issue using pp.neighbors for a slightly different clustering purpose. It seems to handle ~200k data points just fine but above ~300k gives `Segmentation fault (core dumped)` no matter how much memory I allocate to the job. 
The quick fix with threads above did not work for me.

**Comment by stela2502** [comment]
Sad that the c(pp) problem is never discussed here. The only 'fix' was to not run muti process analysis. Has anybody looked into the summation step after the multi process step? To just restrict both OMP and OPENBLAS to only one core can not be the only solution here...

**Comment by jr-leary7** [comment]
I'm having this issue as well -- code that used to run perfectly well is now resulting in segfaults specifically when running `sc.pp.neighbors`. Memory is not the issue, as my dataset is really small (<1k cells).

**Comment by flying-sheep** [comment]
OK, as I wrote here: https://github.com/scverse/scanpy/issues/2359#issuecomment-1909651108

> We have no native code in Scanpy, so we don’t cause segfaults. If there’s anything we can mitigate, we will, if someone demonstrates a reproducible problem with up-to-date dependencies

Reinstalling your environment often helps. If not, please give us a way to completely reproduce this just from copyable code, i.e. 

1. a lockfile (environment.yaml or requirements.txt) containing the exact versions of everything in your environment
2. a block of code that throws the error when run in that environment (code should download the data necessary to reproduce the issue)

Then we can help

**Comment by jr-leary7** [comment]
Below is code that reproduces the error. What I've already tried is 1) updating all the packages 2) reverting to the versions I had prior and 3) creating a new virtual environment and reinstalling everything. None of them worked. 

```
# import libraries
import numpy as np
import pandas as pd
import scanpy as sc
import scvelo as scv
# download data
adata = scv.datasets.pancreas()
# preprocess 
sc.pp.filter_cells(adata, min_counts=200)
sc.pp.filter_genes(adata, min_cells=10)
adata.raw = adata
sc.pp.highly_variable_genes(
    adata, 
    n_top_genes=3000, 
    flavor='seurat_v3', 
    subset=True
)
sc.tl.pca(adata)
# find neighbors -- this is the bit that errors
sc.pp.neighbors(
    adata, 
    n_neighbors=20,
    n_pcs=30,  
    metric='cosine', 
    random_state=312
)
```

The error is below: 

```
OMP: info #276: omp_set_nested_routine is deprecated, please use omp_set_max_active_levels instead. 
```
The output of `pip freeze` detailing all of my package versions is attached. My Python version is 3.11.6, and I'm using a 2020 Intel MacBook Pro running Sonoma v14.3. 
[requirements.txt](https://github.com/scverse/scanpy/files/14074316/requirements.txt)

**Comment by jr-leary7** [comment]
Any update on this ? I'm still getting the same error even with the development version.
