### ISSUE TITLE
When reading in a .xlsx file with sc.read_excel() it says the sheet I asked to load in does not exist.

### ISSUE THREAD

**Issue by ghost** [scverse/scanpy#2371]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [x] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can copy&paste without having any data)

```python
adata = sc.read_excel(filename = '/Users/dan/Documents/Graduate_School/Bioinformatics_MS/BF550/Project/muscle_expression_.xlsx', sheet = 'expression')
```

```pytb
[/Users/dan/opt/anaconda3/lib/python3.9/site-packages/openpyxl/reader/workbook.py:88: UserWarning: File contains an invalid specification for expression. This will be removed
  warn(msg)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/var/folders/f1/7pq3lkn50cb7mtfkxrk9fnfh0000gn/T/ipykernel_3372/1224090119.py in <module>
----> 1 adata = sc.read_excel(filename = '/Users/dan/Documents/Graduate_School/Bioinformatics_MS/BF550/Project/muscle_expression_.xlsx', sheet = 'expression')

~/opt/anaconda3/lib/python3.9/site-packages/anndata/_io/read.py in read_excel(filename, sheet, dtype)
     73     from pandas import read_excel
     74 
---> 75     df = read_excel(fspath(filename), sheet)
     76     X = df.values[:, 1:]
     77     row = dict(row_names=df.iloc[:, 0].values.astype(str))

~/opt/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py in wrapper(*args, **kwargs)
    309                     stacklevel=stacklevel,
    310                 )
--> 311             return func(*args, **kwargs)
    312 
    313         return wrapper

~/opt/anaconda3/lib/python3.9/site-packages/pandas/io/excel/_base.py in read_excel(io, sheet_name, header, names, index_col, usecols, squeeze, dtype, engine, converters, true_values, false_values, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, parse_dates, date_parser, thousands, decimal, comment, skipfooter, convert_float, mangle_dupe_cols, storage_options)
    463 
    464     try:
--> 465         data = io.parse(
    466             sheet_name=sheet_name,
    467             header=header,

~/opt/anaconda3/lib/python3.9/site-packages/pandas/io/excel/_base.py in parse(self, sheet_name, header, names, index_col, usecols, squeeze, converters, true_values, false_values, skiprows, nrows, na_values, parse_dates, date_parser, thousands, comment, skipfooter, convert_float, mangle_dupe_cols, **kwds)
   1456             DataFrame from the passed in Excel file.
   1457         """
-> 1458         return self._reader.parse(
   1459             sheet_name=sheet_name,
   1460             header=header,

~/opt/anaconda3/lib/python3.9/site-packages/pandas/io/excel/_base.py in parse(self, sheet_name, header, names, index_col, usecols, squeeze, dtype, true_values, false_values, skiprows, nrows, na_values, verbose, parse_dates, date_parser, thousands, decimal, comment, skipfooter, convert_float, mangle_dupe_cols, **kwds)
    632 
    633             if isinstance(asheetname, str):
--> 634                 sheet = self.get_sheet_by_name(asheetname)
    635             else:  # assume an integer if not a string
    636                 sheet = self.get_sheet_by_index(asheetname)

~/opt/anaconda3/lib/python3.9/site-packages/pandas/io/excel/_openpyxl.py in get_sheet_by_name(self, name)
    543 
    544     def get_sheet_by_name(self, name: str):
--> 545         self.raise_if_bad_sheet_by_name(name)
    546         return self.book[name]
    547 

~/opt/anaconda3/lib/python3.9/site-packages/pandas/io/excel/_base.py in raise_if_bad_sheet_by_name(self, name)
    568     def raise_if_bad_sheet_by_name(self, name: str) -> None:
    569         if name not in self.sheet_names:
--> 570             raise ValueError(f"Worksheet named '{name}' not found")
    571 
    572     def parse(

ValueError: Worksheet named 'expression' not found]
```

#### '1.9.1'

<details>

[-----
anndata     0.8.0
scanpy      1.9.1
-----
PIL                         9.2.0
PyObjCTools                 NA
appnope                     0.1.2
backcall                    0.2.0
beta_ufunc                  NA
binom_ufunc                 NA
bottleneck                  1.3.5
cffi                        1.15.1
cloudpickle                 2.0.0
colorama                    0.4.5
cycler                      0.10.0
cython_runtime              NA
cytoolz                     0.11.0
dask                        2022.7.0
dateutil                    2.8.2
debugpy                     1.5.1
decorator                   5.1.1
defusedxml                  0.7.1
entrypoints                 0.4
fsspec                      2022.7.1
h5py                        3.7.0
hypergeom_ufunc             NA
igraph                      0.10.2
ipykernel                   6.15.2
ipython_genutils            0.2.0
jedi                        0.18.1
jinja2                      2.11.3
joblib                      1.1.0
jupyter_server              1.18.1
kiwisolver                  1.4.2
leidenalg                   0.9.0
llvmlite                    0.38.0
louvain                     0.8.0
lxml                        4.9.1
lz4                         3.1.3
markupsafe                  2.0.1
matplotlib                  3.5.2
mkl                         2.4.0
mpl_toolkits                NA
natsort                     8.2.0
nbinom_ufunc                NA
ncf_ufunc                   NA
numba                       0.55.1
numexpr                     2.8.3
numpy                       1.21.5
openpyxl                    3.0.10
packaging                   21.3
pandas                      1.4.4
parso                       0.8.3
pexpect                     4.8.0
pickleshare                 0.7.5
pkg_resources               NA
plotly                      5.9.0
prompt_toolkit              3.0.20
psutil                      5.9.0
ptyprocess                  0.7.0
pydev_ipython               NA
pydevconsole                NA
pydevd                      2.6.0
pydevd_concurrency_analyser NA
pydevd_file_utils           NA
pydevd_plugins              NA
pydevd_tracing              NA
pygments                    2.11.2
pyparsing                   3.0.9
pytz                        2022.1
scipy                       1.9.1
session_info                1.0.0
setuptools                  63.4.1
six                         1.16.0
sklearn                     1.0.2
snappy                      NA
sphinxcontrib               NA
storemagic                  NA
tblib                       1.7.0
texttable                   1.6.7
threadpoolctl               2.2.0
tlz                         0.11.0
toolz                       0.11.2
tornado                     6.1
traitlets                   5.1.1
typing_extensions           NA
wcwidth                     0.2.5
xlrd                        2.0.1
yaml                        6.0
zipp                        NA
zmq                         23.2.0
zope                        NA
-----
IPython             7.31.1
jupyter_client      7.3.4
jupyter_core        4.11.1
jupyterlab          3.4.4
notebook            6.4.12
-----
Python 3.9.13 (main, Aug 25 2022, 18:29:29) [Clang 12.0.0 ]
macOS-10.16-x86_64-i386-64bit
-----
Session information updated at 2022-11-26 11:30]

</details>
When trying to read-in the .xlsx file, I get the error that the sheet does not exist. A screen shot of the excel file is attached.

<img width="1399" alt="Screenshot 2022-11-26 at 11 33 18 AM" src="https://user-images.githubusercontent.com/119125018/204099054-96ba4b72-815b-45fa-8bdc-a9f7d91ba662.png">

**Comment by eroell** [comment]
Just came across this, sorry for being slow here and thanks for your interest in scanpy!
Is this still an issue for you?

If yes, is there a way you could supply an example I could check for such an Excel file, e.g. via a Link for a small public dataset?
Just tried with an own dummy file (scanpy 1.9.5) and it seemed to work
