### ISSUE TITLE
PyDESeq2 in scanpy

### ISSUE THREAD

**Issue by kvshams** [scverse/scanpy#2385]
- [ ] Additional function parameters / changed functionality / changed defaults?
- [ ] New analysis tool: A simple analysis tool you have been using and are missing in `sc.tools`?
- [ ] New plotting function: A kind of plot you would like to seein `sc.pl`?
- [X] External tools: Do you know an existing package that should go into `sc.external.*`?
- [ ] Other?

...
Is it possible to impliment [PyDESeq2](https://github.com/owkin/PyDESeq2) in `scanpy`
Thanks,
Shams

**Comment by Zethson** [comment]
Please have a look at https://github.com/owkin/PyDESeq2/issues/15
