### ISSUE TITLE
umap failed to cluster the cells

### ISSUE THREAD

**Issue by danli349** [scverse/scanpy#2386]
Hello

I tried umap visualization by:

```
sc.pp.normalize_total(adata, target_sum=1e6)
sc.pp.log1p(adata, base=2)
sc.pp.highly_variable_genes(adata, flavor='cell_ranger', n_top_genes=400)


sc.pp.scale(adata, zero_center=True, max_value=None, copy=False, layer=None, obsm=None)
sc.pp.pca(adata, n_comps=50, use_highly_variable=True, svd_solver='arpack')
sc.pp.neighbors(adata, n_neighbors=50)

sc.tl.umap(adata, min_dist=0.5, spread=1.0)
sc.pl.umap(adata, color='fullname', use_raw=False, save='samples_umap.pdf')
```
But the cells can't separate well
![image](https://user-images.githubusercontent.com/33963919/209233854-db64fddd-4266-4f87-805b-dced45b1547f.png)

version
```
anndata     0.7.5
scanpy      1.6.1
```

I tried another small dataset with `scanpy` using the same parameters as before:
![1](https://user-images.githubusercontent.com/33963919/209387824-3a5b1037-f226-49c8-9222-f54c04a62155.jpg)

`sc.tl.umap` still failed to down dimension the data properly.

Then I tried the original [`umap` package](https://umap-learn.readthedocs.io/en/latest/plotting.html) using the same data set:

```
import umap
import umap.plot
mapper = umap.UMAP().fit(adata.X)
umap.plot.points(mapper)
```

Now the original `umap` package can do down dimension very well:
![2](https://user-images.githubusercontent.com/33963919/209387903-0161dfa6-0ca5-48cc-8661-465930e23fef.jpg)

I think there may be something wrong with the `umap` function in `scanpy`

Can anyone please let me know the reason?
Thanks a lot.

**Comment by michael-swift** [comment]
Hi danli249, 

what dataset are you using? If this is your own dataset, can you instead replicate this behavior on a public dataset? e.g. the clustering tutorial https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html?

without much needed context, this looks like some oversight in the preprocessing, for example not normalizing your data or not log-transforming it

Michael

**Comment by danli349** [comment]
Hi Michael:

I compare the `umap` in `scanpy` with the original [`umap`](https://umap-learn.readthedocs.io/en/latest/plotting.html) (https://umap-learn.readthedocs.io/en/latest/plotting.html)  using the same dataset, the original `umap` works well, I think the problem is in `scanpy`. I edited my question to include this.
Do you have some suggestions?
Thanks

Dan

**Comment by michael-swift** [comment]
Hi Dan, 

When you perform the umap calculation using sc.tl.umap, the default matrix used is adata.obsm['X_pca']. Given this, you wouldn't expect the same embedding the way you've done it. if instead you did this

`mapper = umap.UMAP().fit(adata.obsm['X_pca'])` 

you'd likely find a very similar embedding to the ones you've shown scanpy producing. As such, I'm guessing there is problem with how you've preprocessed the data, such that the PCA space is not behaving as expected. 

why don't you attempt running this notebook " wget https://github.com/scverse/scanpy-tutorials/raw/master/pbmc3k.ipynb" with your current installation, and let us know if you can reproduce the tutorial. Then I would suggest adding your data, changing else, and reporting back.

**Comment by danli349** [comment]
Hi Michael:

Thanks for your suggestion, I run the tutorial without changing anything: https://github.com/scverse/scanpy-tutorials/raw/master/pbmc3k.ipynb, 
![image](https://user-images.githubusercontent.com/33963919/209399067-2287268f-a77c-4f12-ba5b-d56e4370b2f2.png)

My `scanpy` can't do down dimension correctly in the `pbmc3k` data.
![image](https://user-images.githubusercontent.com/33963919/209398837-d2f77dfa-5855-4bf7-9c7d-33625909af09.png)
Can you please let me know what is wrong?

**Comment by michael-swift** [comment]
This does seem more like a bug now. I noticed you're using a pretty old version of scanpy. can you update to a more current version, e.g. 1.9*  so that we can understand if it is reproducible on the distribution that people are using?

**Comment by danli349** [comment]
I upgrade `scanpy` to `1.9.1`, and now `sc.tl.umap` works as expected:

![image](https://user-images.githubusercontent.com/33963919/209405851-2798000b-0e90-4b3f-982c-f0de196489c5.png)

Thanks

**Comment by michael-swift** [comment]
great! good luck out there. can you close the issue?

best

**Comment by danli349** [comment]
Hi Michael

For my own data, 
I compared `scanpy` `umap` with the original `umap`
The original `umap` output is:
```
import umap
import umap.plot
mapper = umap.UMAP().fit(adata.X)
umap.plot.points(mapper, labels=adata.obs['batch'])
```
![image](https://user-images.githubusercontent.com/33963919/209409453-578ce08c-3eed-4b42-a0c9-e3165d5859cc.png)

```
mapper2 = umap.UMAP().fit(adata.obsm['X_pca'])
umap.plot.points(mapper2, labels=adata.obs['batch'])
```
![image](https://user-images.githubusercontent.com/33963919/209409492-9559fc2e-817e-4003-b8e2-560a5687b241.png)

The `scanpy` output is:
```
sc.pp.filter_cells(adata, min_counts = 100)
adata = adata[adata.obs['mt_frac'] < 0.2]
sc.pp.filter_cells(adata, min_genes = 1)
sc.pp.filter_genes(adata, min_cells=1)

import doubletdetection
clf = doubletdetection.BoostClassifier(
    n_iters=10, 
    use_phenograph=False, 
    standard_scaling=True
)
doublets = clf.fit(adata.X).predict(p_thresh=1e-16, voter_thresh=0.5)
doublet_score = clf.doublet_score()
adata.obs["doublet"] = doublets
adata = adata[adata.obs["doublet"] == 0.0] # filter out doublets 

sc.pp.normalize_total(adata, target_sum=1e6)
sc.pp.log1p(adata, base=2)

sc.pp.highly_variable_genes(adata, min_mean=0.0125, max_mean=3, min_disp=0.5, 
                            flavor='cell_ranger')
sc.pp.scale(adata, max_value=10)
sc.pp.pca(adata, svd_solver='arpack')

sc.pp.neighbors(adata, n_neighbors=15)
sc.tl.umap(adata, min_dist=0.5, spread = 1.0)
sc.pl.umap(adata, color='batch', use_raw=False, save='batch_umap.pdf')

```

![image](https://user-images.githubusercontent.com/33963919/209409864-0c0c0207-c3af-40f3-8af4-c3448f9ca0f1.png)

If I do not run pca, then run `sc.tl.umap` I will get:

![image](https://user-images.githubusercontent.com/33963919/209410266-efca8967-c8d0-4253-b273-3a048ae27653.png)


1. What should I do to get more compact clusters?
2. Why the output so different between `scanpy.tl.umap` and the orignal `umap`?
3. Should I use PCA for umap or not?
4. Should I use less  highly_variable_genes in `n_top_genes ` parameter when I run `scanpy.pp.highly_variable_genes` to get higher explained variance in `scanpy.pp.pca` and `adata.uns['pca']['variance_ratio']` ? If yes, how much percent explained variance is good?
Thanks
Dan

**Comment by michael-swift** [comment]
Hi Dan, 

These are good questions. I'm not sure this is the appropriate venue for this dialogue. Issues are meant to reporting bugs or discuss feature requests for scanpy. Maybe we can move this to a forum like this instead https://discourse.scverse.org/c/help/27 ?

**Comment by Zethson** [comment]
What @michael-swift says. Thank you very much!
