### ISSUE TITLE
Scanpy analysis for a combined species. I have tried following the normal pipeline to work with the data, but it fails to find MT/mt genes in single cell dataset aligned to both mouse & human genes. 

### ISSUE THREAD

**Issue by echoo07** [scverse/scanpy#2393]
- [ ] I have checked that this issue has not already been reported.
- [ ] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can copy&paste without having any data)

```python
# Your code here
```

```pytb
[Paste the error output produced by the above code here]
```

#### Versions

<details>

[Paste the output of scanpy.logging.print_versions() leaving a blank line after the details tag]

</details>

**Comment by LuckyMD** [comment]
I guess you probably converted all of your gene names to the genes from 1 specie to be able to put them in the same anndata object, no? In that case your problem is solved. Otherwise, I would recommend to at least harmonize the mitochondrial gene names to run this analysis.

**Comment by echoo07** [comment]
Hi thank you so much for you reply. Initially I didn't understand your former statement, but looking at the features table, I understand what you mean now, it's strange that cellranger mixed species alignment adds mm10 or GRCh38 infront of the gene symbols as well which wasn't letting it find the mito-genes on following the scanpy pipeline at the pre-filtering mito genes steps.
![Screenshot 2023-01-05 at 15 41 09](https://user-images.githubusercontent.com/122033428/210822795-0eb1f9c8-cf9f-4949-a3cf-33dd07a20b03.png)
![Screenshot 2023-01-05 at 15 43 50](https://user-images.githubusercontent.com/122033428/210822805-3b292da8-35d0-4e4a-a600-12eeff38ac7b.png)
.

**Comment by LuckyMD** [comment]
I'm glad you found the issue then! I do understand why this is prefixed though... it would be quite confusing having a data object with mixed genes from mice and humans and this not immediately being obvious. I often catch myself looking up which specie was capitalized and which wasn't ;).

**Comment by LuckyMD** [comment]
Can this issue then be closed?

**Comment by Zethson** [comment]
Glad you figured it out and thanks @LuckyMD for helping out.

In any case, please ask usage questions here: https://discourse.scverse.org/
