### ISSUE TITLE
OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.

### ISSUE THREAD

**Issue by LTXu123** [scverse/scanpy#2404]
- [ ] I have checked that this issue has not already been reported.
- [ ] I have confirmed this bug exists on the latest version of scanpy.

---
**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

### Minimal code sample (that we can copy&paste without having any data)

```python
import scanpy as sc
...
...
test_data = sc.pp.regress_out(test_data,['n_count'], copy=True)
sc.pp.scale(test_data)
sc.tl.pca(test_data,n_comps=30, use_highly_variable=True)
sc.pp.neighbors(test_data,n_neighbors=20)

```

```output print

...storing 'feature_types' as categorical
OMP: Info #276:omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.

```

#### Versions

my python version is 3.8
and the versions of scanpy I have tried were 1.8.2 and 1.9.1

I guess that the reason inducing the errors was the version of python is too high. 

How can I solve the problem?

**Comment by Zethson** [comment]
Duplicate https://github.com/scverse/scanpy/issues/2359

Please search existing issues next time.
