### ISSUE TITLE
AttributeError: module 'scanpy' has no attribute 'utils'

### ISSUE THREAD

**Issue by yanwuanxin** [scverse/scanpy#2410]
when run sc.utils.sanitize_anndata(adata), it returns:
AttributeError: module 'scanpy' has no attribute 'utils'

I didn't find any information about `sanitize_anndata()` under the path of scanpy, does anyone encounter a similar error?
the version of scanpy which i use is 1.8.2

**Comment by yanwuanxin** [comment]
`sc._utils.sanitize_anndata(adata)` will work

**Comment by Zethson** [comment]
So is this still an issue?
