### ISSUE TITLE
Matplotlib lower bound causes issues in google colab

### ISSUE THREAD

**Issue by adamgayoso** [scverse/scanpy#2413]
https://github.com/scverse/scanpy/blob/d26be443373549f26226de367f0213f153556915/pyproject.toml#L57

Colab has 3.2.2 installed and installing scanpy requires restarting the runtime. I also can't find a great reason why 3.4 was chosen

https://github.com/scverse/scanpy/pull/2212/

based on this 3.2.2 should be fine?

**Comment by flying-sheep** [comment]
#2733 bumps the minimum version **up** to 3.6 and adds two good reasons why that exact minimum version requirement is chosen:

1. matplotlib’s maintenance schedule drops support for 3.5 in a little bit
2. we use a feature from 3.5

If some piece of infrastructure doesn’t allow bumping versions of client libraries, that piece of infrastructure needs improvement. Jupyter allows distinct environments for kernels and the server for a reason. So while colab should be able to pin and use whatever they need on the server, there’s zero reason why colab should dictate any version of anything other than `ipykernel` for the user environment.

**Comment by ivirshup** [comment]
Default matplotlib in colab seems to be 3.7 now also
