### ISSUE TITLE
'AnnData' object has no attribute 'tl'

### ISSUE THREAD

**Issue by Jiayi-Zheng** [scverse/scanpy#2423]
Hi, I was doing DE for a processed dataset. However, when I did `sc.tl.rank_genes_groups(adata,'Celltypes',method='wilcoxon')` after `adata = sc.read_h5ad('mydata.h5ad')` it tells me `'AnnData' object has no attribute 'tl'`. 

My AnnData is version 0.8.0 and scanpy 1.9.1, I'm not sure how I should check for the error? Thank you!

`View of AnnData object with n_obs × n_vars = 1358 × 1147

    obs: 'Celltypes', 'Celltypes_master_high', 'Celltypes_master_higher', 'Celltypes_master_higher_immune', 'Celltypes_master_2', 'Celltypes_master_3', 'Loc_true', 'Material', 'scsn', 'Donor', 'Donor_ID_2', 'Gender', 'Sample', 'ID', 'Protocol_plot', 'Version', 'Study', 'PoolDon', 'DonorPool', 'scDonor_snBatch', 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt'

    var: 'mt', 'gene_ids-0', 'n_cells-0', 'n_cells_by_counts-0', 'mean_counts-0', 'pct_dropout_by_counts-0', 'total_counts-0', 'gene_ids-1', 'n_cells-1', 'n_cells_by_counts-1', 'mean_counts-1', 'pct_dropout_by_counts-1', 'total_counts-1', 'feature_types-1', 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection', 'mean', 'std'

    uns: 'Celltypes_colors', 'Celltypes_int_F_colors', 'Celltypes_int_colors', 'Celltypes_int_updB_colors', 'Celltypes_master_high_colors', 'ID_colors', 'Loc_true_colors', 'hvg', 'leiden', 'leiden_colors', 'neighbors', 'pca', 'scDonor_snBatch_colors', 'scsn_colors', 'umap'

    obsm: 'X_pca', 'X_pca_hm', 'X_umap', 'X_umap_BBKNN_scDonor_snBatch', 'X_umap_Harmony_Donor_n_Material', 'X_umap_Harmony_Material', 'X_umap_Harmony_scDonor_snBatch'

    varm: 'PCs'

    obsp: 'connectivities', 'distances'`

**Comment by alam-shahul** [comment]
If I had to guess, it seems like you are overwriting the name `sc` as an `AnnData` object at some point?

**Comment by Jiayi-Zheng** [comment]
@alam-shahul
Thank you very much! I did that as abbreviation of single cell to distinguish from single nuclei dataset and completely forgot about the package thing... 

Thanks a lot.
