### ISSUE TITLE
feat(docs): tag `scanpy` versions on readthedocs

### ISSUE THREAD

**Issue by aryarm** [scverse/scanpy#2425]
Thank you for creating `scanpy`! It's such a useful tool!

## Overview of request
Is there any chance that you can start tagging versions of your documentation on readthedocs? Currently, the only available versions are **stable** and **latest**. That makes it easy to view the current documentation but difficult to view docs from old releases of `scanpy`.

## Desired behavior
I would like to be able to...
1. Click on `v: stable` in the flyout menu at the bottom-left corner of the page
![image](https://user-images.githubusercontent.com/23412689/220255767-3fbf84e9-ccf5-420b-b067-7a4054aed047.png)
2. Click on the version of the documentation tagged for the older release of `scanpy` that I'm using

## Resources
- [How to version RTD documentation](https://docs.readthedocs.io/en/stable/versions.html)
- [How to automatically maintain versions upon creating new git tags](https://docs.readthedocs.io/en/stable/automation-rules.html#activate-all-new-tags)
- [Automated versioning](https://docs.readthedocs.io/en/stable/integrations.html#automated-versioning) as part of continuous documentation deployment

## An example
As an example of versioned documentation, take a look at [Snakemake's documentation](https://snakemake.readthedocs.io/).

![image](https://user-images.githubusercontent.com/23412689/220255676-39e9eee9-e658-4866-b8b9-63a6174577ba.png)

**Comment by Zethson** [comment]
Thank you. I agree, this is something that we should start doing. We'll have this on our roadmap.

**Comment by aryarm** [comment]
ok, thanks! it should be relatively easy

The admin of the readthedocs project just needs to add an [_automation rule_](https://docs.readthedocs.io/en/stable/automation-rules.html) in the settings for the project

**Comment by aryarm** [comment]
@Zethson just checking back in. Is this still on the roadmap?

**Comment by Zethson** [comment]
Yes, but not immediately. Please remain patient.

**Comment by aryarm** [comment]
I'm going to close this now because it seems like the issue has been addressed. Thanks for doing that!

![image](https://github.com/user-attachments/assets/bb53ffac-48b2-4f48-80b0-c4d8ea6627f8)
