### ISSUE TITLE
Ploting the n_counts/per cell on umap

### ISSUE THREAD

**Issue by terooatt** [scverse/scanpy#243]
Hi,

Is there a way to visualize the n_counts or n_genes for each cells in a tsne or umap plot much like you do in cellranger html outputs (see attachment)?

![screen shot 2018-08-27 at 17 35 25](https://user-images.githubusercontent.com/13950799/44649717-a1334500-aa1f-11e8-8f5f-020084049f08.png)

Thanks for your help.

**Comment by terooatt** [comment]
Never mind, that was silly easy sorry.

**Comment by falexwolf** [comment]
Good you found it! :)
