### ISSUE TITLE
TypeError when RandomState object passed to sc.tl.leiden

### ISSUE THREAD

**Issue by wakelin-g** [scverse/scanpy#2431]
- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

The leiden function is supposed to accept a RandomState object but raises a TypeError when one is passed. This doesn't happen with any other function that accepts a RandomState object. 

```python
import scanpy as sc
import anndata as ad
import numpy as np
from scipy.sparse import csr_matrix

adata = ad.AnnData(csr_matrix(np.random.poisson(1, size(100, 100)), dtype=np.float32))
rs = np.random.RandomState(1)

sc.pp.pca(adata, random_state=rs)
sc.pp.neighbors(adata, random_state=rs)
sc.tl.leiden(adata, random_state=rs)

```

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/griffen/mambaforge/envs/scanpy-1.9.2/lib/python3.9/site-packages/scanpy/tools/_leiden.py", line 144, in leiden
    part = leidenalg.find_partition(g, partition_type, **partition_kwargs)
  File "/home/griffen/mambaforge/envs/scanpy-1.9.2/lib/python3.9/site-packages/leidenalg/functions.py", line 89, in find_partition
    optimiser.set_rng_seed(seed)
  File "/home/griffen/mambaforge/envs/scanpy-1.9.2/lib/python3.9/site-packages/leidenalg/Optimiser.py", line 244, in set_rng_seed
    _c_leiden._Optimiser_set_rng_seed(self._optimiser, value)
TypeError: an integer is required (got type numpy.random.mtrand.RandomState)
```

#### Versions

<details>

-----
anndata     0.8.0
scanpy      1.9.2
-----
PIL                 9.4.0
beta_ufunc          NA
binom_ufunc         NA
cffi                1.15.1
colorama            0.4.6
cycler              0.10.0
cython_runtime      NA
dateutil            2.8.2
defusedxml          0.7.1
h5py                3.8.0
hypergeom_ufunc     NA
igraph              0.10.4
importlib_resources NA
invgauss_ufunc      NA
joblib              1.2.0
kiwisolver          1.4.4
leidenalg           0.9.1
llvmlite            0.39.1
matplotlib          3.7.0
mpl_toolkits        NA
natsort             8.2.0
nbinom_ufunc        NA
ncf_ufunc           NA
nct_ufunc           NA
ncx2_ufunc          NA
numba               0.56.4
numpy               1.23.5
packaging           23.0
pandas              1.5.3
pkg_resources       NA
psutil              5.9.4
pycparser           2.21
pynndescent         0.5.8
pyparsing           3.0.9
pytz                2022.7.1
scipy               1.10.1
session_info        1.0.0
setuptools          67.4.0
six                 1.16.0
skewnorm_ufunc      NA
sklearn             1.2.1
texttable           1.6.7
threadpoolctl       3.1.0
tqdm                4.64.1
typing_extensions   NA
umap                0.5.3
wcwidth             0.2.6
yaml                6.0
zipp                NA
zoneinfo            NA
-----
Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03) [GCC 11.3.0]
Linux-6.1.12-arch1-1-x86_64-with-glibc2.37
-----
Session information updated at 2023-02-25 19:07

</details>

**Comment by Zethson** [comment]
Thank you! Would you be willing to file up a PR for this?

**Comment by wakelin-g** [comment]
> Thank you! Would you be willing to file up a PR for this?

Sorry, I don't have a CS background. Do you mean in the leidenalg repo?

**Comment by Zethson** [comment]
No worries. I meant here: https://github.com/scverse/scanpy/blob/master/scanpy/tools/_leiden.py

**Comment by wakelin-g** [comment]
> No worries. I meant here: https://github.com/scverse/scanpy/blob/master/scanpy/tools/_leiden.py

Sorry I still don't really know what to do. After the RandomState object is passed to leiden, it passes it to igraph, which raises an error because igraph wants an int to initialize [it's own rng system](https://igraph.org/c/doc/igraph-Random.html). It seems to me like there's no easy way to fix this, no?

Maybe I should just give it an int instead? I'd just like my clustering to be reproducible.

**Comment by wakelin-g** [comment]
Closing this as it appears (to me personally) that not much can actually be done from the scanpy side and this is more of a leidenalg/igraph issue.
