### ISSUE TITLE
Dotplot for merged group of genes 

### ISSUE THREAD

**Issue by aterceros** [scverse/scanpy#2439]
Hello,

I was wondering how I could make a dot plot where instead of showing single genes on the x axis, I could show a one group at time of merged group of genes (i.e. markers for a cell type merged as 1 list) and its average expression in each cluster. Something like on the diagram below:
![IMG_8599](https://user-images.githubusercontent.com/99988924/223526039-7fa72170-fe6e-475b-9f8c-2391e19c8825.JPG)

Thank you!

**Comment by Zethson** [comment]
Please post this question in the scverse discourse: https://discourse.scverse.org/
