### ISSUE TITLE
cannot read file data

### ISSUE THREAD

**Issue by ghost** [scverse/scanpy#2441]
- [ y] I have checked that this issue has not already been reported.
- [ y] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

Hi all, 

I encountered a problem that it keeps saying : "Please install skmisc package via `pip install --user scikit-misc",  but I have checked pip/conda and it is already installed. 

I followed the instructions here:
[#2073](https://github.com/scverse/scanpy/issues/2073#issuecomment-996270340)

checked the ouput of "from skmisc.loess import loess". 

Does anyone know how to solve this problem?

Thanks!

### Minimal code sample (that we can copy&paste without having any data)

```python
from skmisc.loess import loess
```

```pytb
sc.pp.highly_variable_genes(all_exp_merged_bins_ad, n_top_genes=2000, flavor='seurat_v3', span=1.0)
  File "/ldfssz1/ST_BI/USER/ywu/.conda/envs/scs/lib/python3.9/site-packages/scanpy/preprocessing/_highly_variable_genes.py", line 419, in highly_variable_genes
    return _highly_variable_genes_seurat_v3(
  File "/ldfssz1/ST_BI/USER/ywu/.conda/envs/scs/lib/python3.9/site-packages/scanpy/preprocessing/_highly_variable_genes.py", line 55, in _highly_variable_genes_seurat_v3
    raise ImportError(
ImportError: Please install skmisc package via `pip install --user scikit-misc


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wyu/.local/lib/python3.9/site-packages/skmisc/loess/__init__.py", line 51, in <module>
    from ._loess import (loess, loess_model, loess_inputs, loess_control,
ImportError: /home/wyu/.local/lib/python3.9/site-packages/skmisc/loess/../../scikit_misc.libs/libopenblasp-r0-085ca80a.3.9.so: cannot read file data
```

#### Versions

<details>

WARNING: If you miss a compact list, please try `print_header`!
-----
anndata     0.7.5
scanpy      1.8.2
sinfo       0.3.1
-----
PIL                 9.4.0
anndata             0.7.5
beta_ufunc          NA
binom_ufunc         NA
cffi                1.15.1
colorama            0.4.6
cycler              0.10.0
cython_runtime      NA
dateutil            2.8.2
defusedxml          0.7.1
google              NA
h5py                3.8.0
hypergeom_ufunc     NA
joblib              1.2.0
kiwisolver          1.4.4
llvmlite            0.39.1
matplotlib          3.5.0
mpl_toolkits        NA
natsort             8.3.1
nbinom_ufunc        NA
numba               0.56.4
numexpr             2.8.3
numpy               1.22.4
packaging           23.0
pandas              1.5.3
pkg_resources       NA
psutil              5.9.4
pyexpat             NA
pyparsing           3.0.9
pytz                2022.7.1
scanpy              1.8.2
scipy               1.8.0
setuptools_scm      NA
sinfo               0.3.1
six                 1.16.0
sklearn             1.0.1
skmisc              0.1.4
tables              3.6.1
threadpoolctl       3.1.0
typing_extensions   NA
yaml                6.0
-----
Python 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46) [GCC 9.4.0]
Linux-3.10.0-1127.el7.x86_64-x86_64-with-glibc2.17
8 logical CPU cores, x86_64

</details>

**Comment by Zethson** [comment]
Could you please open this issue here? https://github.com/has2k1/scikit-misc
