### ISSUE TITLE
Problems with scv.utils.merge function

### ISSUE THREAD

**Issue by VivianeSchulz** [scverse/scanpy#2443]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

I am trying to run a velocity analysis, however whenever I try to merge my data with my loom files I get an error (code and error attached).
I've tried it on a file for which this command previously worked (but now it no longer does) as well as trying to merge two loom files, which also gives me this error. So I believe it's to do with a package version rather than the files themselves, but I cannot seem to figure out which packages are responsible and which versions I would need instead.
Any help would be greatly appreciated!

My code:
adata_vel = scv.utils.merge(adata, adatal)

This is my error:
<img width="844" alt="Screenshot 2023-03-09 at 11 43 11" src="https://user-images.githubusercontent.com/85882727/224000508-fb6a0e9a-c49d-4186-a531-88233f3cfc82.png">

#### Versions

-----
anndata     0.8.0
scanpy      1.9.3
-----
OpenSSL                                     20.0.1
PIL                                         8.2.0
aa8f2297d25b4dc6fd3d98411eb3ba53823c4f42    NA
absl                                        NA
anndata2ri                                  1.0.6
annoy                                       NA
anyio                                       NA
appnope                                     0.1.2
asttokens                                   NA
astunparse                                  1.6.3
attr                                        21.4.0
babel                                       2.9.0
backcall                                    0.2.0
backports                                   NA
boto3                                       1.26.7
botocore                                    1.29.7
bottleneck                                  1.3.2
brotli                                      NA
certifi                                     2020.12.05
cffi                                        1.14.6
chardet                                     4.0.0
cloudpickle                                 1.6.0
colorama                                    0.4.4
cryptography                                3.4.7
cycler                                      0.10.0
cython_runtime                              NA
cytoolz                                     0.11.0
dask                                        2021.04.0
dateutil                                    2.8.1
debugpy                                     1.5.1
decorator                                   5.0.6
dot_parser                                  NA
dunamai                                     1.6.0
executing                                   0.8.2
fbpca                                       NA
flatbuffers                                 NA
fsspec                                      0.7.4
gast                                        0.5.3
get_version                                 3.5
google                                      NA
gprofiler                                   1.0.0
h5py                                        3.7.0
idna                                        2.10
igraph                                      0.10.2
importlib_resources                         NA
intervaltree                                NA
ipykernel                                   6.8.0
ipython_genutils                            0.2.0
ipywidgets                                  7.6.3
jedi                                        0.17.2
jinja2                                      3.0.2
jmespath                                    1.0.1
joblib                                      1.0.1
json5                                       NA
jsonschema                                  3.2.0
jupyter_server                              1.4.1
jupyterlab_server                           2.4.0
keras                                       2.8.0
keras_preprocessing                         1.1.2
kiwisolver                                  1.3.1
leidenalg                                   0.7.0
llvmlite                                    0.36.0
louvain                                     0.7.0
markupsafe                                  2.0.1
matplotlib                                  3.7.1
matplotlib_inline                           NA
mpl_toolkits                                NA
natsort                                     7.1.1
nbclassic                                   NA
nbformat                                    5.1.3
numba                                       0.53.1
numpy                                       1.22.0
opt_einsum                                  v3.3.0
packaging                                   20.9
pandas                                      1.2.5
parso                                       0.7.0
pexpect                                     4.8.0
pickleshare                                 0.7.5
pkg_resources                               NA
prometheus_client                           NA
prompt_toolkit                              3.0.17
psutil                                      5.8.0
ptyprocess                                  0.7.0
pure_eval                                   0.2.2
pvectorc                                    NA
pycparser                                   2.20
pydev_ipython                               NA
pydevconsole                                NA
pydevd                                      2.6.0
pydevd_concurrency_analyser                 NA
pydevd_file_utils                           NA
pydevd_plugins                              NA
pydevd_tracing                              NA
pydot                                       1.4.2
pygments                                    2.8.1
pynndescent                                 0.5.4
pyparsing                                   2.4.7
pyrsistent                                  NA
pytz                                        2021.3
requests                                    2.25.1
rpy2                                        3.4.2
ruamel                                      NA
scanorama                                   1.7.1
scipy                                       1.6.2
scrublet                                    NA
scvelo                                      0.2.5
seaborn                                     0.11.1
send2trash                                  NA
session_info                                1.0.0
six                                         1.15.0
sklearn                                     0.24.1
sniffio                                     1.2.0
socks                                       1.7.1
sortedcontainers                            2.3.0
sparse                                      0.13.0
sphinxcontrib                               NA
stack_data                                  0.1.4
statsmodels                                 0.12.2
tblib                                       1.7.0
tensorboard                                 2.8.0
tensorflow                                  2.8.0
termcolor                                   1.1.0
texttable                                   1.6.4
tlz                                         0.11.0
toolz                                       0.11.1
tornado                                     6.1
traitlets                                   5.1.1
typing_extensions                           NA
tzlocal                                     NA
umap                                        0.5.1
urllib3                                     1.26.4
wcwidth                                     0.2.5
wrapt                                       1.12.1
yaml                                        5.4.1
zipp                                        NA
zmq                                         20.0.0
zope                                        NA
-----
IPython             8.0.1
jupyter_client      6.1.12
jupyter_core        4.7.1
jupyterlab          3.0.14
notebook            6.3.0
-----
Python 3.8.8 (default, Apr 13 2021, 12:59:45) [Clang 10.0.0 ]
macOS-10.15.7-x86_64-i386-64bit

**Comment by Zethson** [comment]
Please submit this issue at scvelo
