### ISSUE TITLE
How to read in the Spatial dataset directly from gene count matrix (.mtx) file and related images (without HDF5 files)?

### ISSUE THREAD

**Issue by ElyasMo** [scverse/scanpy#2448]
How to read in the Spatial object directly from gene count matrix (.mtx) file and related images (without HDF5 file)?
- [ +] Additional function parameters / changed functionality / changed defaults?

I am working on a publicly available dataset which only has provided the gene count (matrix.mtx), features (features.tsv) and barcodes (barcodes.tsv) in addition to the spatial folder (the output of spaceranger). How should I read in this dataset using scanpy?

Thank you very much in advance
...

**Comment by Zethson** [comment]
Please ask in the scverse discourse: https://discourse.scverse.org/
