### ISSUE TITLE
sc.settings.plot_use_prefix

### ISSUE THREAD

**Issue by dsm-72** [scverse/scanpy#2450]
- [x] Additional function parameters / changed functionality / changed defaults?
- [ ] New analysis tool: A simple analysis tool you have been using and are missing in `sc.tools`?
- [x] New plotting function: A kind of plot you would like to seein `sc.pl`?
- [ x] External tools: Do you know an existing package that should go into `sc.external.*`?
- [ ] Other?

...

1. exposed a setting to prevent `sc.pp.<fn>` from saving with a "prefix" (default filename) if `type(save) == str`.

Why?
I don't want my files having that prefix. 

2. please add PHATE and magic-impute to embedding options :)

**Comment by Zethson** [comment]
1. is a duplicate and already tracked elsewhere
2. Please create another issue for PHATE and magic-impute.
