### ISSUE TITLE
scanpy.read_visium 

### ISSUE THREAD

**Issue by Biometeor** [scverse/scanpy#2462]
Will the api of “scanpy.read_visium” be upgraded to be compatible with the new space information file name  tissue_positions.csv which was previously named tissue_positions_list.csv ，after Space Ranger 2.0?

**Comment by Zethson** [comment]
Yes! Please wait for the next release. Please also checkout squidpy.

**Comment by Biometeor** [comment]
您好，我已经收到你的邮件
