### ISSUE TITLE
Incorrect clustering on PBMC tutorial.

### ISSUE THREAD

**Issue by bi-glitch** [scverse/scanpy#2471]
- [ X] I have checked that this issue has not already been reported.
- [ X] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

### Minimal code sample (that we can copy&paste without having any data)

```python
sc.pp.neighbors(adata, n_neighbors=10, n_pcs=40)
sc.tl.umap(adata)
sc.pl.umap(adata, color=['CST3', 'NKG7', 'PPBP'])
sc.tl.leiden(adata)
sc.pl.umap(adata, color=['leiden', 'CST3', 'NKG7'])

```

```pytb
The output does not match the clustering of the PBMC3k tutorial. I've downloaded the PBMC notebook from github and my output has clusters 4 and 5 switched., see my output below. How can I rectify this?
```

#### Versions

<details>

-----
anndata     0.9.1
scanpy      1.9.3
-----
PIL                         9.0.1
asttokens                   NA
backcall                    0.2.0
beta_ufunc                  NA
binom_ufunc                 NA
bottleneck                  1.3.4
cffi                        1.15.0
cloudpickle                 2.0.0
colorama                    0.4.4
cycler                      0.10.0
cython_runtime              NA
cytoolz                     0.11.0
dask                        2022.02.1
dateutil                    2.8.2
debugpy                     1.5.1
decorator                   5.1.1
defusedxml                  0.7.1
executing                   0.8.3
fsspec                      2022.02.0
google                      NA
h5py                        3.6.0
igraph                      0.10.4
ipykernel                   6.9.1
ipython_genutils            0.2.0
ipywidgets                  7.6.5
jedi                        0.18.1
jinja2                      2.11.3
joblib                      1.1.0
jupyter_server              1.13.5
kiwisolver                  1.3.2
leidenalg                   0.9.1
llvmlite                    0.38.0
markupsafe                  2.0.1
matplotlib                  3.5.1
matplotlib_inline           NA
mkl                         2.4.0
mpl_toolkits                NA
natsort                     8.3.1
nbinom_ufunc                NA
nt                          NA
ntsecuritycon               NA
numba                       0.55.1
numexpr                     2.8.1
numpy                       1.21.5
packaging                   21.3
pandas                      1.4.2
parso                       0.8.3
patsy                       0.5.2
pickleshare                 0.7.5
pkg_resources               NA
plotly                      5.6.0
prompt_toolkit              3.0.20
psutil                      5.8.0
pure_eval                   0.2.2
pycparser                   2.21
pydev_ipython               NA
pydevconsole                NA
pydevd                      2.6.0
pydevd_concurrency_analyser NA
pydevd_file_utils           NA
pydevd_plugins              NA
pydevd_tracing              NA
pygments                    2.11.2
pynndescent                 0.5.8
pyparsing                   3.0.4
pythoncom                   NA
pytz                        2021.3
pywintypes                  NA
ruamel                      NA
scipy                       1.7.3
seaborn                     0.11.2
session_info                1.0.0
setuptools                  61.2.0
six                         1.16.0
sklearn                     1.0.2
snappy                      NA
sphinxcontrib               NA
stack_data                  0.2.0
statsmodels                 0.13.2
tblib                       1.7.0
texttable                   1.6.7
threadpoolctl               2.2.0
tlz                         0.11.0
toolz                       0.11.2
tornado                     6.1
tqdm                        4.64.0
traitlets                   5.1.1
typing_extensions           NA
umap                        0.5.3
wcwidth                     0.2.5
win32api                    NA
win32com                    NA
win32security               NA
yaml                        6.0
zipp                        NA
zmq                         22.3.0
zope                        NA
-----
IPython             8.2.0
jupyter_client      6.1.12
jupyter_core        4.9.2
jupyterlab          3.3.2
notebook            6.4.8
-----
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Windows-10-10.0.17763-SP0
</details>

-----
Session information updated at 2023-04-18 14:50
![image-tr](https://user-images.githubusercontent.com/80623801/232782829-c209af87-b1de-41c1-9a00-f11529a24bcd.JPG)

**Comment by Zethson** [comment]
Hi,

different versions of dependencies can lead to such changes. This is nothing major, don't worry about this. The general embedding structure will always be very similar though.
