### ISSUE TITLE
Violin plot - subset vs. all cells

### ISSUE THREAD

**Issue by GeoffSCollins** [scverse/scanpy#2485]
FYI I made a post on the scverse discourse (https://discourse.scverse.org/t/violin-plot-subset-vs-all-cells/1399) but figured I would add it here as well.

I’ve been using `sc.pl.violin()` a lot lately, but have not been able to figure out how to make a violin plot with two groups where the first is a specific subset and the second is all cells. An example use case of this is making a violin plot for a specific UMAP cluster against the rest. I am familiar with the `groupby` parameter to split based on a metadata factor, but this doesn’t allow selection of one specific metadata factor. Is there a way to do this with scanpy or do we need to build out a custom plotting function? If there is enough demand for this and it is not currently supported, I could look into making a PR.

**Comment by VladimirShitov** [comment]
Hi, @GeoffSCollins ! To do that, you need to add new columns to `adata.obs` table. A column should contain one value (e.g. `True`) for the group of interest and another value (e.g. `False`) for all the other groups. This is how you can create such columns for each of the values of column `leiden`:

```python
import pandas as pd

adata.obs = pd.concat([
    adata.obs,
    pd.get_dummies(adata.obs["leiden"], prefix="is_cell_type").astype(bool).astype("category"),
], axis=1)
```

Then you can build a violin plot:

```python
sc.pl.violin(adata, keys="total_counts", groupby="is_cell_type_NK")
```
![download-8](https://user-images.githubusercontent.com/35199218/236865939-768d759a-a581-4ba9-acb9-0104cbf16efd.png)

I hope this is useful! Also, a small note: "UMAP cluster" is not a correct term. Clusters are obtained completely independently of UMAP by running leiden clustering algorithm. UMAP is just a nice visualisation (which is, however, built ignorant of cluster information).

**Comment by GeoffSCollins** [comment]
Hi @VladimirShitov 

Thank you for the help (and the information about leiden vs UMAP).

I think the code provided shows something slightly different. You are plotting False vs True here, but we would want something like False vs all. So, the True violin plot would be a little different. Regardless, I am just going to down this route :D
