### ISSUE TITLE
Add approximate nearest neighbor backend

### ISSUE THREAD

**Issue by flying-sheep** [scverse/scanpy#2519]
Goals:

- flexibility in creation
- Neighbor querying API
- Harmonize storage of backends’ querying indices

	- use it in doublet detection and scanorama reimplementations

Current solution: `method` arg.

https://github.com/scverse/scanpy/blob/ed8e1401d39068782f2435d258b33fce4f7b4a9e/scanpy/neighbors/__init__.py#L32

- if `use_dense_distances`: [`sklearn.metrics.pairwise_distances`](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise_distances.html)
- if `method == 'rapids'`: [`cuml.neighbors.NearestNeighbors`](https://docs.rapids.ai/api/cuml/stable/api/#cuml.neighbors.NearestNeighbors)
- otherwise: [`umap.umap_.nearest_neighbors`](https://umap-learn.readthedocs.io/en/latest/api.html#umap.umap_.nearest_neighbors)
- if `method == 'gauss'`: use umap distances, overwrite its connectivities

## Evaluating options

See [ann-benchmarks.com](https://ann-benchmarks.com/index.html#datasets).

Build time vs query time is not straightforward, see https://github.com/erikbern/ann-benchmarks/issues/207#issuecomment-1180389432 and https://github.com/erikbern/ann-benchmarks/issues/207#issuecomment-1180747770

> If, however, you are simply interested in knn-graph construction then you can get that from pynndescent in less time than even the index construction time (since the prepare phase isn't required, but is a non-trivial part of the index construction time).

Plots for index building are on individual dataset pages, like [glove-100-angular](https://ann-benchmarks.com/glove-100-angular_10_angular.html).

<details>
<summary>Used metrics</summary>

https://github.com/scverse/scanpy/blob/ed8e1401d39068782f2435d258b33fce4f7b4a9e/scanpy/neighbors/__init__.py#L35-L56

</details>

Interesting:

Name | Demo | wheels: Platforms | wheels: Python | Search speed | Index build
--- | --- | --- | --- | --- | ---
[NMSLIB](https://github.com/nmslib/nmslib) | [6 notebooks](https://github.com/nmslib/nmslib/blob/master/python_bindings/notebooks/README.md) | [Linux wheels](https://pypi.org/project/nmslib/2.1.1/#files) |[Outdated (3.9)](https://github.com/nmslib/nmslib/issues/529) | top | slow
[ScaNN](https://github.com/google-research/google-research/tree/master/scann#readme) | [notebook](https://github.com/google-research/google-research/blob/master/scann/docs/example.ipynb) | [All wheels](https://pypi.org/project/scann/1.2.9/#files) | [Slightly outdated (3.10)](https://github.com/google-research/google-research/issues/1590) | very fast | middling
[Faiss](https://github.com/facebookresearch/faiss) | [wiki](https://github.com/facebookresearch/faiss/wiki/Getting-started) | –* | –* | middling to very fast | faiss-ivf: top

*no official package on PyPI

**Comment by adamgayoso** [comment]
faiss was reasonably easy to install via conda and has fairly easy to use gpu support which is nice

**Comment by flying-sheep** [comment]
We’re thinking about making the backend configurable through something like https://github.com/frankier/sklearn-ann (that specific one doesn’t seem maintained though). A recipe for this is found here: https://scikit-learn.org/stable/auto_examples/neighbors/approximate_nearest_neighbors.html#sphx-glr-auto-examples-neighbors-approximate-nearest-neighbors-py

Faiss does seem nice as an option, but a hard dependency on something that isn’t on PyPI is out of the question.
