### ISSUE TITLE
sc.pl.rank_genes_groups with filtering by condition

### ISSUE THREAD

**Issue by zhouzhendiao** [scverse/scanpy#2550]
### What kind of feature would you like to request?

Additional function parameters 

### Please describe your wishes

Recently I ran `sc.tl.rank_genes_groups(adata_t, 'leiden_res1', method='wilcoxon', pts=True)` on my datasets, then I plot `sc.pl.rank_genes_groups(adata_t, n_genes=25, sharey=False, ncols=3, )`. 

I found ribo genes rank top in some groups. Then I want to filtering results by logfoldchanges, pvals_adj, like Seurat's `FindAllMarkers` did, so I ran `sc.get.rank_genes_groups_df(adata_t, group=None, pval_cutoff=0.01, log2fc_min=1)`, and the ribo genes are filtered successfully.

 Can function `sc.pl.rank_genes_groups` add filtering params lilke pvals_adj, pct_nt_group, pct_nz_reference which are really useful to filter meaningless genes?

**Comment by flying-sheep** [comment]
I’m not 100% up to date, but if you want more fancy differential expression analysis than what `rank_genes_groups` provides, you should give https://github.com/theislab/diffxpy a shot!

@davidsebfischer it’s maintained, right?

I’m going to close this unless I’m wrong and we want to enhance `rank_genes_groups` after all

**Comment by zhouzhendiao** [comment]
> I’m not 100% up to date, but if you want more fancy differential expression analysis than what `rank_genes_groups` provides, you should give https://github.com/theislab/diffxpy a shot!
> 
> @davidsebfischer it’s maintained, right?
> 
> I’m going to close this unless I’m wrong and we want to enhance `rank_genes_groups` after all

Hi Philipp, I will try diffxpy. Thanks!
