### ISSUE TITLE
How to import GEO dataset?

### ISSUE THREAD

**Issue by xiasijian** [scverse/scanpy#2557]
### What kind of feature would you like to request?

Additional function parameters / changed functionality / changed defaults?

### Please describe your wishes

Thank you for your excellent software, now I need to analyse pubulic data from GEO, but I do not know how to import them. Can you give me some suggestion? Thanks!
![image](https://github.com/scverse/scanpy/assets/39158528/74e8b4ed-7593-42fa-8f07-6459d33ace10)

**Comment by flying-sheep** [comment]
GEO has all kinds of datasets on it. The one screenshotted is a 10x one. Use [`read_10x_mtx`](https://scanpy.readthedocs.io/en/stable/generated/scanpy.read_10x_mtx.html)

Please ask questions like this on https://discourse.scverse.org/

**Comment by xiasijian** [comment]
Ok, Thanks, I think it lack the scalefactor file.
