### ISSUE TITLE
Why do the image have a red?

### ISSUE THREAD

**Issue by xiasijian** [scverse/scanpy#2558]
### What kind of feature would you like to request?

Additional function parameters / changed functionality / changed defaults?

### Please describe your wishes

![image](https://github.com/scverse/scanpy/assets/39158528/44931b7b-ae5a-4483-9ec9-c76ed7206d72)

**Comment by flying-sheep** [comment]
The only red I can see is from the image data. We don’t influence that, so it must be in the initial image you added.

If that is not what you wanted to know, please explain. I’m going to close this for the time being. Happy to re-open if this is not solved.

**Comment by xiasijian** [comment]
Yes, you are right, thanks!
