### ISSUE TITLE
Get rid of logging module and use our own

### ISSUE THREAD

**Issue by flying-sheep** [scverse/scanpy#256]
We should replace the whole logging module with

```py
import logging

root_logger = logging.getLogger('scanpy')
root_logger.setLevel('INFO')
root_logger.propagate = False  # Don’t pass log messages on to the root logger and its handler

handler = logging.StreamHandler(sys.stderr)  # Why did we use stdout?
handler.setFormatter(logging.Formatter('%(message)s'))
handler.setLevel('INFO')
root_logger.addHandler(handler)

def get_logger(name):
   return root_logger.getChild(name)
```

and in all submodules just do

```py
from .logging import get_logger

logger = get_logger(__name__)
```

**Comment by falexwolf** [comment]
Yes, fine with me. I didn't do it for Scanpy in the beginning as the formatting I wanted requires quite a few lines. I then closely mimicked Scanpy's logging using Python's logging for another package here: https://github.com/NDKoehler/DataScienceBowl2017_7th_place/blob/638542c3cde5af45bf34d0391695ab0e54ce78b8/dsb3/pipeline.py#L373-L430

What do you think?

**Comment by flying-sheep** [comment]
Sounds good! And that code doesn’t look much longer than what we have right now
