### ISSUE TITLE
produce NaN when running UMAP with min_dist=0.1

### ISSUE THREAD

**Issue by zacharylau10** [scverse/scanpy#257]
Hi,
    I encountered a wired problem when I run UMAP with min_dist=0.1
       `sc.tl.pca(adata_f,n_comps=250)`
        `adata_f.obsm['X_pca'] *= -1 `
        `sc.pp.neighbors(adata_f, n_neighbors=10)`
        `scv.pp.moments(adata_f,renormalize=True,mode='connectivities')`
        `sc.tl.umap(adata_f,min_dist=0.1)`
    error is about produce NaN, and then I checked `adata_f.obs['X_umap']`, all NaN in array.
    However, when I use min_dist=0.2, everything seems well. 
    Could you help me to figure it out? Thank you~

**Comment by falexwolf** [comment]
Sorry, this seems to be a UMAP issue. To really dig down to this, you'd probably run this using the UMAP package and submit a bug report there.

**Comment by falexwolf** [comment]
PS: 250 PCs are a lot! I imagine that you'll get a weird output from that...

**Comment by zacharylau10** [comment]
the umap result of 250 PCs and min_dist=0.2 seems ok, and I will check the source of umap. 
Thank you~
