### ISSUE TITLE
Transparent spots for spatial plot

### ISSUE THREAD

**Issue by cathalgking** [scverse/scanpy#2584]
### What kind of feature would you like to request?

Additional function parameters / changed functionality / changed defaults?

### Please describe your wishes

Maybe it is already possible. I would like to have transparent spots for spots that have zero counts (or near zero). I am using the function `scanpy.pl.spatial` An example shown below for a 10x Visium dataset. Can this be done?

 
<img width="516" alt="Screen Shot 2023-08-02 at 7 48 59 pm" src="https://github.com/scverse/scanpy/assets/32261323/00b4f62f-6808-4226-93f9-d973f01274bd">

**Comment by flying-sheep** [comment]
It’s possible, just use `na_color`. Any [matplotlib color](https://matplotlib.org/stable/tutorials/colors/colors.html) should be supported

**Comment by cathalgking** [comment]
@flying-sheep This doesn't seem to work. I tried with two matplotlib colours, 'w' and 'C1' using the code
`sc.pl.spatial(A1, img_key="hires", color=["Lag3"], bw=True, na_color='w')`

I know that a lot of these spots contain zero counts. I just want zero counts to be transparent. Should I try it a different way?

![Screen Shot 2023-08-11 at 2 27 22 pm](https://github.com/scverse/scanpy/assets/32261323/fa0d88ef-d7da-43d6-ac47-b229d27f8a8c)

**Comment by flying-sheep** [comment]
Ah, you also need to set the spots that you want to be that color to `NaN`.

Furthermore, for transparency, you need to use an RGBA color (the “A” stands for alpha channel, which is how opaque a color is).

You can also use something like [`matplotlib.colors.to_rgba('C1', .3)`](https://matplotlib.org/stable/api/_as_gen/matplotlib.colors.to_rgba.html#matplotlib.colors.to_rgba) to make an opaque color transparent.
