### ISSUE TITLE
read_visium() for newer SpaceRanger versions

### ISSUE THREAD

**Issue by deckerlin** [scverse/scanpy#2598]
### What kind of feature would you like to request?

Additional function parameters / changed functionality / changed defaults?

### Please describe your wishes

When using SpaceRanger Versions 2.0 and higher, the output no longer contains a tissue_positions_list.csv file. Instead, this file is named tissue_positions.csv. Therefore, it is no longer compatible with scanpy's read_visium() function.
Currently, the issue can be fixed by manually renaming the SpaceRanger Output before running the read_visium() function. However, in the long term, I would love for scanpy to be up to date with current SpaceRanger Outputs or to give the user the opportunity to define the name of their tissue positions file. Thank you!

**Comment by flying-sheep** [comment]
fixed in #2424, reported many times. please use the search function.

we’ll do a release soon!
