### ISSUE TITLE
sc.tl.rank_genes_groups finds upregulated genes (lfc > 1.5) with pts 0

### ISSUE THREAD

**Issue by noamharel161** [scverse/scanpy#2628]
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

### What happened?

I defined groups of cells with a custom filter. After I run rank_gene_groups with pts=True in order to get the precent of cells infected, the results don't make sense: 
upregulated genes with lfc values and adjusted pvalues that make sense, have a pts value of 0 - which does not make sense because if this gene is upregulated in this group, it has to exist in more than 0 cells.

I would appreciate any help with his, thank you in advance

![image](https://github.com/scverse/scanpy/assets/36629785/55431851-9836-44e3-a9f9-a4680ddc9d96)

### Minimal code sample

```python
sc.tl.rank_genes_groups(adata, method='t-test', groupby='barcodes', groups=['infected', 'unknown'], reference='uninfected', key_added='group_DE_results', pts=True)

results = adata.uns["group_DE_results"]

groups = results['names'].dtype.names
result = pd.DataFrame(
    {group + '_' + key: results[key][group]
    for group in groups for key in ['names', 'pvals', 'pvals_adj', 'logfoldchanges', 'pts']})


de_results = []
for i in groups:
    group = result[[c for c in result.columns.tolist() if c.startswith(str(i) + '_')]]
    group = group.rename(columns={f'{i}_names':'names', f'{i}_pvals':'pvals', f'{i}_pvals_adj':'pvals_adj', f'{i}_logfoldchanges':'lfc', f'{i}_pts':'pts', f'{i}_pts_rest':'pts_rest'})
    group['group'] = i
    de_results.append(group)
de_results = pd.concat(de_results)

de_results.reset_index(drop=True, inplace=True)
de_results
```

### Versions

<details>

```

```

</details>

**Comment by eroell** [comment]
Hi, 

Thank you for your interest in scanpy and for raising your question here!

It looks like you are interested in getting the results of `sc.tl.rank_genes_groups`.
For this, we recommend using `sc.get.rank_genes_groups` - you can find more about scanpy’s getters [here](https://scanpy.readthedocs.io/en/stable/api.html#module-scanpy.get).

This might look for example like this:

```py
import scanpy as sc

pbmc = sc.datasets.pbmc68k_reduced()
sc.tl.rank_genes_groups(pbmc, groupby="louvain", pts=True, use_raw=True)

dedf = sc.get.rank_genes_groups_df(pbmc, group="0")
```

By accessing the `.uns` as you outlined, just using the ordering of the pts column might not match the ordering of the sorted genes.
This behaviour is subject to updates in the future - in any case `sc.get.rank_genes_groups` is the way to go here :)

I hope this helps?
