### ISSUE TITLE
Improve settings documentation

### ISSUE THREAD

**Issue by GirayEryilmaz** [scverse/scanpy#2630]
### What kind of feature would you like to request?

Other?

### Please describe your wishes

Hello Scanpy team!

In scanpy api documentation I see [some settings](https://scanpy.readthedocs.io/en/stable/generated/scanpy._settings.ScanpyConfig.html#scanpy._settings.ScanpyConfig), however I don't understand how we are supposed to use n_job and max_memory settings. I would like scanpy to use whatever is available. How can I do that?

**Comment by Zethson** [comment]
Think that for `n_job` it's generally `-1` to use all cores and concerning the `max_memory` I vaguely remember that the setting isn't really used so you can ignore it.

**Comment by Zethson** [comment]
We might want to document that a bit better. I fatfingered.
