### ISSUE TITLE
Issue with writing to h5ad/ hdf5 and plotting functions after concatenating datasets

### ISSUE THREAD

**Issue by dparmaksiz16** [scverse/scanpy#2645]
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

### What happened?

I am trying to concatenate multiple datasets. I have Anndata's of 4 runs that I'm trying to analyze together. I tried the plotting functions (e.g. sc.pl. violin) and saving to h5ad files on individual Anndata's and it works. When I merge them via ad.concat I keep getting a Type Error due to Anndata calling sanitize and strings_to_categoricals when I try to save or use plotting functions. I thought it might be because I'm adding new obs before merging but then I tried to just merge without any manipulation of individual Anndata's and it still gave the same error. Then I tried to manually merge the Anndata's by saving X as dataframe and obs as separate dataframes, merging them as dataframes and then creating a new Anndata object. I still keep getting these errors.  The error message says that I'm trying to manipulate a view of the Anndata object although I'm not subsetting it and when I do adata.is_view it says False. 

I'm not sure how to provide a code sample that can be replicated without data in this case. 

### Minimal code sample

```python
samples= [ <list of 4 hdf5 files>]
all_adata = []
i = 0
for s in samples:
    curr_adata = sc.read_h5ad(f"/mnt/d/Labmembers/Deniz/aging_data/{s}")
    curr_adata.var_names_make_unique()
    all_adata.append(curr_adata)
adata= ad.concat(all_adata)
#I get the same type error when I try to do
adata.write('trial.hdf5') 
#or
sc.pl.violin(adata, 'volume')
```

### Error output

```pytb
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[8], line 1
----> 1 sc.pl.violin(adata, 'volume')

File /home/denizparmaksiz/anaconda3/envs/scanpy/lib/python3.9/site-packages/scanpy/plotting/_anndata.py:749, in violin(adata, keys, groupby, log, use_raw, stripplot, jitter, size, layer, scale, order, multi_panel, xlabel, ylabel, rotation, show, save, ax, **kwds)
    645 """\
    646 Violin plot.
    647 
   (...)
    745 pl.stacked_violin
    746 """
    747 import seaborn as sns  # Slow import, only import if called
--> 749 sanitize_anndata(adata)
    750 use_raw = _check_use_raw(adata, use_raw)
    751 if isinstance(keys, str):

File /home/denizparmaksiz/anaconda3/envs/scanpy/lib/python3.9/site-packages/scanpy/_utils/__init__.py:406, in sanitize_anndata(adata)
    404 def sanitize_anndata(adata):
    405     """Transform string annotations to categoricals."""
--> 406     adata._sanitize()

File ~/.local/lib/python3.9/site-packages/anndata/_core/anndata.py:1228, in AnnData.strings_to_categoricals(self, df)
   1226 if len(c.categories) >= len(c):
   1227     continue
...
   1232         "AnnData, not on this view. You might encounter this"
   1233         "error message while copying or writing to disk."
   1234     )

TypeError: reorder_categories() got an unexpected keyword argument 'inplace'
```

### Versions

<details>

```
anndata     0.7.8
scanpy      1.9.3
-----
PIL                 10.0.0
asttokens           NA
backcall            0.2.0
clustergrammer2     0.18.0
comm                0.1.4
cycler              0.10.0
cython_runtime      NA
dateutil            2.8.2
debugpy             1.6.7.post1
decorator           5.1.1
executing           1.2.0
google              NA
h5py                3.9.0
igraph              0.10.6
importlib_resources NA
ipykernel           6.25.1
ipywidgets          8.1.0
jedi                0.19.0
joblib              1.3.2
kiwisolver          1.4.4
leidenalg           0.9.0
...
Python 3.9.12 (main, Jun  1 2022, 11:38:51) [GCC 7.5.0]
Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.31
```

</details>

**Comment by dparmaksiz16** [comment]
I noticed I'm on scanpy 1.9.3 and upgraded to scanpy 1.9.4 as well and tried again and have the same issue

**Comment by dparmaksiz16** [comment]
After 4 whole days of trying to figure this out I was able to do it via manual merging of datasets and changing indexes to categorical via pd.CategoricalIndex

**Comment by flying-sheep** [comment]
Good to hear! I know the feeling of figuring out things myself right after filing an issue report. It’s the public version of https://rubberduckdebugging.com/
