### ISSUE TITLE
Integration across SmartSeq2 and 10X Datasets

### ISSUE THREAD

**Issue by Teich2233** [scverse/scanpy#2662]
### What kind of feature would you like to request?

Additional function parameters / changed functionality / changed defaults?

### Please describe your wishes

Hello,

I am trying to integrate some datasets that were generated with SmartSeq2 and 10X platforms. For the SmartSeq2 datasets, I only got the TPM data, while for the 10x data,I got raw counts matrix. How to merge and integrate SmartSeq2 and 10X Datasets? Can the TPM and raw counts be merged for analysis?

Thank you in advance for your assistance.

**Comment by Zethson** [comment]
Please ask usage questions here: https://discourse.scverse.org/

You should not integrate normalized and unnormalized counts. Consider getting the raw counts or integrating on the normalized counts

**Comment by Teich2233** [comment]
@Zethson  Thank you for your help. I know what to do.
