### ISSUE TITLE
is it not suitable for python2.7

### ISSUE THREAD

**Issue by worker000000** [scverse/scanpy#268]
![image](https://user-images.githubusercontent.com/25199946/45993589-2878e480-c0c2-11e8-86de-683c7d103218.png)

**Comment by flying-sheep** [comment]
Correct. This is listed on the project page:

![grafik](https://user-images.githubusercontent.com/291575/45997197-12a5f800-c09f-11e8-925a-262ac41750cb.png)

I added `python_requires='>3.5'` in 6d93f91c37b5bba5628a29082b45ab7e65912cc5, now there should be no confusion.

If you want a reason why: Python 2 has at the time of writing about [15 months to live](https://pythonclock.org/), after which it will be dead and unsupported. The scientific world is [sunsetting it a bit before that](https://python3statement.org/). This has been known for years and people had more than enough time to prepare. Making a project Python 2 compatible these days is basically self-flagellation.
