### ISSUE TITLE
reset sc.pl.DotPlot defaults

### ISSUE THREAD

**Issue by c-westhoven** [scverse/scanpy#2708]
### What kind of feature would you like to request?

Additional function parameters / changed functionality / changed defaults?

### Please describe your wishes

Hi,

I'm wondering if it would be possible to implement a "reset_to_defaults" function. In my specific use case, that would be in `sc.pl.DotPlot`. I reset quite a few of the different default parameters, but only wanted to use those for a couple plots, but not all. 
It would be nice not to have to reset them all again individually, when plotting the remaining dotplots.

Thanks!

**Comment by flying-sheep** [comment]
Hi! What do you mean with `reset`? Do you mean you set parameters in `matplotlib.rcParams` or … ?

**Comment by c-westhoven** [comment]
Hi, thanks for responding!
I mean the default attributes you can set for scanpy.pl.DotPlot:

> DEFAULT_CATEGORY_HEIGHT  
> DEFAULT_CATEGORY_WIDTH  
> DEFAULT_COLORMAP 
> DEFAULT_COLOR_LEGEND_TITLE 
> DEFAULT_COLOR_ON 
> DEFAULT_DOT_EDGECOLOR 
> DEFAULT_DOT_EDGELW 
> DEFAULT_DOT_MAX 
> DEFAULT_DOT_MIN 
> DEFAULT_LARGEST_DOT 
> DEFAULT_LEGENDS_WIDTH 
> DEFAULT_PLOT_X_PADDING 
> DEFAULT_PLOT_Y_PADDING 
> DEFAULT_SAVE_PREFIX 
> DEFAULT_SIZE_EXPONENT 
> DEFAULT_SIZE_LEGEND_TITLE 
> DEFAULT_SMALLEST_DOT 
> DEFAULT_WSPACE 
> MAX_NUM_CATEGORIES 
> MIN_FIGURE_HEIGHT

once I set them in a script, I need to know the original default value in order to "reset" them.

**Comment by c-westhoven** [comment]
The closest I could get would be by setting dotplot.style() in order to get the defaults. But it doesn't reset that attributes, just adds its own style. And then I need to remember to add that to every dotplot I make within a script.

**Comment by flying-sheep** [comment]
They are capitalized, which means they are treated as constants and shouldn’t be modified. They *are* the original default value you want to refer to, so if you change them, you can’t do that anymore.

So yes, `style` or the parameters in `def dotplot` are the correct way to do this. If you want a customized version, just do:

```py
my_style = dict(...)  # resusable customizations

sc.pl.dotplot(..., **my_style)
```

or

```py
from functools import wraps

@wraps(sc.pl.dotplot)
def my_dotpot(*args, return_fig: bool = False, **kw):
    dp = sc.pl.dotplot(*args, **kw, return_fig=True)
    dp.style(...)  # customize here
    if return_fig:
        return dp
    dp.show()
```
