### ISSUE TITLE
Reordering categories leads to issues with `sc.tl.rank_genes_groups` when using `method='logreg'`

### ISSUE THREAD

**Issue by fbnrst** [scverse/scanpy#273]
Hi,

Reordering the categories of groups in obs leads to shuffling of marker genes to the wrong groups when using `sc.tl.rank_genes_groups`. Interestingly, this only happens if I use `method='logreg`. It works fine with `method='t-test`. I am not sure how relevant this is. Maybe, one should not reorder categories. However, this was helpful to me when I wanted to plot the categories in a certain order. Here comes a minimal example:

```
import pandas as pd
import scanpy.api as sc

adata = sc.datasets.blobs(640, 3)
sc.tl.pca(adata)
sc.pp.neighbors(adata)
sc.tl.louvain(adata)

method='logreg'

sc.tl.rank_genes_groups(adata, 'louvain', method=method)
print(pd.DataFrame(adata.uns['rank_genes_groups']['names']).head(1))

adata.obs['louvain'].cat.reorder_categories(['2', '1', '0'], inplace = True)

sc.tl.rank_genes_groups(adata, 'louvain', method=method)
print(pd.DataFrame(adata.uns['rank_genes_groups']['names']).head(1))
```
The result looks like this:
```python
     0   1    2
0  570  63  126
     2   1    0
0  570  63  126
```
The expected result would be that the marker genes end up in the same groups as above (watch the change in the lowest row):
```python
     0   1    2
0  570  63  126
     2   1    0
0  126  63  570
```

**Comment by fbnrst** [comment]
The same issue happens when renaming categories with the built-in rename categories function. I think, this definitely should not happen. Example:

```python
import pandas as pd
import scanpy.api as sc

adata = sc.datasets.blobs(640, 3)
sc.tl.pca(adata)
sc.pp.neighbors(adata)
sc.tl.louvain(adata)

method='logreg'

sc.tl.rank_genes_groups(adata, 'louvain', method=method)
print(pd.DataFrame(adata.uns['rank_genes_groups']['names']).head(1))

adata.rename_categories('louvain', ['Zero', 'One', 'Two'])

sc.tl.rank_genes_groups(adata, 'louvain', method=method)
print(pd.DataFrame(adata.uns['rank_genes_groups']['names']).head(1))
```
gives
```python
     0   1    2
0  570  63  126
  Zero  One  Two
0   63  126  570
```

**Comment by falexwolf** [comment]
Thank you very much for the super clean examples here! Is fixed via https://github.com/theislab/scanpy/commit/0ed304a64038f7d2c11b36fe5883ab9765ffba57 (@yugeji, you fed a pandas series into scikit learn, which is generally a bad idea :wink: ).

**Comment by mtvector** [comment]
Whew thanks for fixing this... I ran into the same problem and thought I was going crazy.
