### ISSUE TITLE
Tutorial bug at Clustering 3k PBMCs following a Seurat Tutorial

### ISSUE THREAD

**Issue by Xparx** [scverse/scanpy#275]
I found a minor bug in this tutorial
[Clustering 3k PBMCs following a Seurat Tutorial](https://nbviewer.jupyter.org/github/theislab/scanpy_usage/blob/master/170505_seurat/seurat.ipynb). I hope this is the correct venue to post to regarding this.

I'm currently going through this to learn how to use scanpy.

In the first section
```
path = './data/pbmc3k_filtered_gene_bc_matrices/hg19/'
adata = sc.read(path + 'matrix.mtx', cache=True).T  # transpose the data
genes = pd.read_csv(path + 'genes.tsv', header=None, sep='\t')
adata.var_names = genes[1]
adata.var['gene_ids'] = genes[0]  # add the gene ids as annotation of the variables/genes
adata.obs_names = pd.read_csv(path + 'barcodes.tsv', header=None)[0]
```

Due to how pandas dataframes indexes this part
```
genes = pd.read_csv(path + 'genes.tsv', header=None, sep='\t')
adata.var_names = genes[1]
adata.var['gene_ids'] = genes[0]  # add the gene ids as annotation of the variables/genes
```
does not yield the expected results. As `var_names` becomes the index of `var` adding `genes[0]` will try to merge a data frame with unmatching index resulting in a `NaN` column in `var` for `'gene_ids'`.

The solution should be either
```
genes = genes.set_index(1)
adata.var = genes
```
or
```
adata.var_names = genes[1]
genes = genes.set_index(1)
adata.var['gene_ids'] = genes[0]  # add the gene ids as annotation of the variables/genes
``` 

It does probably not have any effect on the tutorial but I thought I'd mention it.

**Comment by falexwolf** [comment]
Thank you for pointing it out, it is fixed in the current version and will be updated online soon. You're right that it didn't have any effect on the tutorial otherwise.
