### ISSUE TITLE
sc.pp.filter_genes runs out of memory

### ISSUE THREAD

**Issue by huangdanqi** [scverse/scanpy#2754]
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

### What happened?

hello, why dose my code "sc.pp.filter_genes(adata, min_cells=3)" error after running "sc.pp.filter_cells(adata, min_genes=200)"?

### Minimal code sample

```python
sc.pp.filter_cells(adata, min_genes=200)
sc.pp.filter_genes(adata, min_cells=3)
```

### Error output

```pytb
ERROR:

/root/anaconda3/envs/c2s/lib/python3.11/site-packages/scanpy/preprocessing/_simple.py:250: ImplicitModificationWarning: Trying to modify attribute .var of view, initializing view as actual.
/root/anaconda3/envs/c2s/lib/python3.11/site-packages/anndata/_core/views.py:79: ImplicitModificationWarning: Trying to modify attribute .var of view, initializing view as actual.
____________________________________________________________________________________________________
AND the process is out of memory

[17371499.406473] Out of memory: Killed process 465550 (python) total-vm:132596812kB, anon-rss:129055148kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:253640kB oom_score_adj:0
```

### Versions

<details>
scanpy                    1.9.5
python                    3.11.6

</details>

**Comment by flying-sheep** [comment]
Seems like you ran out of memory. Maybe you only have enough memory to run store your data once, but for calculating this, a second copy has to be made.

If you think this is a bug and scanpy uses much more memory than it should here, please tell us and we will reopen this issue.

**Comment by huangdanqi** [comment]
您好，您的邮件我已收到。 祝好！

**Comment by huangdanqi** [comment]
Thanks for your answer！
I will spend time finding where the problem is.
^-^



---Original---
From: "Philipp ***@***.***&gt;
Date: Thu, Nov 16, 2023 16:49 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [scverse/scanpy] sc.pp.filter_genes runs out of memory (Issue#2754)




 
Seems like you ran out of memory. Maybe you only have enough memory to run store your data once, but for calculating this, a second copy has to be made.
 
If you think this is a bug and scanpy uses much more memory than it should here, please tell us and we will reopen this issue.
