### ISSUE TITLE
Broken search results on the website

### ISSUE THREAD

**Issue by VladimirShitov** [scverse/scanpy#2763]
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [X] (optional) I have confirmed this bug exists on the master branch of scanpy.

### What happened?

When you print something in the search bar on the [documentation website](https://scanpy.readthedocs.io/en/stable/index.html), sometimes suggested links are broken. See the example for `sc.pl.umap` below.

Using google, I was able to find a correct page. Here is the correct and the broken link:
- Broken: https://scanpy.readthedocs.io/en/latest/generated/scanpy.pl.umap.html#scanpy-pl-umap
- Correct: https://scanpy.readthedocs.io/en/stable/generated/scanpy.pl.umap.html#scanpy-pl-umap

The difference is in latest/stable part. I tried searching for other functions as well, but did not notice any pattern. Here are some other links from search suggestion that are broken:
- https://scanpy.readthedocs.io/en/latest/generated/scanpy.external.tl.phenograph.html
- https://scanpy.readthedocs.io/en/latest/generated/scanpy.pl.rank_genes_groups_dotplot.html
- Same for other visualizations of rank_genes_group. `tl.rank_genes_groups` works, though

And a related issue. Why doesn't scanpy have a custom 404 page? 😄 

### Minimal code sample

Here's an example with looking for umap plot:
- Search suggests a page:
 
<img width="514" alt="image" src="https://github.com/scverse/scanpy/assets/35199218/893b7a60-d30d-40a2-bc8f-0fbb46b25ce0">

- First link (to the tool) is correct, but by clicking on the second one (for plotting) user gets 404:

<img width="907" alt="image" src="https://github.com/scverse/scanpy/assets/35199218/f56fefd4-ec7c-4afc-953a-96a5832b848c">

### Versions

I was at the "stable" version on the website. Current scanpy version is 1.9.6

**Comment by flying-sheep** [comment]
In https://github.com/scverse/scanpy/pull/2220, DocSearch was removed from the `latest` docs.

Our current theme would probably support it, so we could re-introduce it (https://github.com/pydata/pydata-sphinx-theme/issues/795). @ivirshup how do I get access to our DocSearch account?

PS: There’s more discussion about search plugins supported by our theme here: https://github.com/pydata/pydata-sphinx-theme/issues/202
