### ISSUE TITLE
Is there a `Jitter` parameter in `scanpy.pl.umap` to reduce overlap?

### ISSUE THREAD

**Issue by danli349** [scverse/scanpy#2768]
### What kind of feature would you like to request?

Additional function parameters

### Please describe your wishes

Hello:

Is it possible to borrow the `seaborn.objects.Jitter` function to reduce the overlapping dots in `scanpy.pl.umap`?
[https://seaborn.pydata.org/generated/seaborn.objects.Jitter.html](https://seaborn.pydata.org/generated/seaborn.objects.Jitter.html)
Thanks

**Comment by michael-swift** [comment]
UMAP is a scatterplot, thus the X and Y dimension both carry information, jitter would distort the data (beyond what UMAP already does) 
  
If you're concerned about overplotting, you can try changing the size and alpha or downsampling: 
 `sc.pl.umap(adata, size = 5, alpha = 0.5)`

**Comment by Gabi86** [comment]
Not sure if you've found this yet but you can adjust the calculated and plotted distances with the `sc.tl.umap` parameters `min_dist=0.5, spread=1.0`  [readthedocs](https://scanpy.readthedocs.io/en/stable/generated/scanpy.tl.umap.html)

**Comment by ivirshup** [comment]
I'd agree with @michael-swift, I don't think we'd want to add a jitter parameter for these kinds of plots.
