### ISSUE TITLE
Scipy getnnz deprecation?

### ISSUE THREAD

**Issue by gjhuizing** [scverse/scanpy#2773]
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [X] (optional) I have confirmed this bug exists on the master branch of scanpy.

### What happened?

Hi!

My recent PR (https://github.com/scverse/scanpy/pull/2772) made me realize that `.getnnz(axis=xx)` is used in several places in the codebase.

From the Scipy docs for sparse arrays:
> Deprecated since version 1.11.0: This method will be removed in SciPy 1.13.0. Use X.nnz instead. The axis argument will no longer be supported; please let us know if you still need this functionality.

From what I understand, sparse *matrices* should be fine. Can we assume that an AnnData contains a sparse matrix and not a sparse array? If not, it may be good to do one or more of the following:
- Preventively put scipy < 1.13 in the requirements
- Signal to Scipy that the `axis` argument is important to this widely used package. Pinging @dschult again for that
- At some point move to `.nnz`

Best,

GJ

(edited because I originally confused `csr_array` and `csr_matrix`)

### Minimal code sample

```python
N/A
```

### Versions

<details>

```
latest
```

</details>

**Comment by flying-sheep** [comment]
We only support matrices so far, and as far as I know, only one spot uses the `axis` parameter. And we can support this use case in a different way.

the use case is a fast conversion from nearest neighbors csr_matrix to a pair of index/distance matrices. an alternative implementation is something like

```diff
-if is_constant(nns.getnnz(axis=1)):
+if is_constant(np.diff(nns.indptr)):
```

or so.
