### ISSUE TITLE
`highly_variable_genes(flavor='seurat')` results differ from Seurat’s HVG results

### ISSUE THREAD

**Issue by carversh** [scverse/scanpy#2780]
### What kind of feature would you like to request?

Additional function parameters / changed functionality / changed defaults?

### Please describe your wishes

If these methods are supposed to be similar, and I am normalizing and taking the log of the count matrices in both cases to produce the same log-normalized count matrix, then why am I getting super different results?

**Comment by flying-sheep** [comment]
@giovp @adamgayoso you had thoughts on this, right?

**Comment by adamgayoso** [comment]
I only know about the issue with how genes are aggregated over batches with `flavor='seurat_v3'`. See ~~#2088~~ #1733.

I vaguely remember older issues with comparisons of the cellranger and original seurat flavors

**Comment by flying-sheep** [comment]
I’m talking about [this private thread](https://scverse.zulipchat.com/#narrow/stream/315186-core-team/topic/Lior.2C.20again/near/386542660).

**Comment by giovp** [comment]
@flying-sheep I think in that thread we were discussing about differential expression and not feature selection. I _think_ some of those pints were addressed during the hackathon.

Regarding inconsistency, I think there has been some work here https://github.com/scverse/scanpy/pull/1732 but admittedly there were still discrepancies. 

More generally, I think it would be useful to understand how much is the discrepancy there is right now, @carversh would you be able to provide some stats?

**Comment by carversh** [comment]
Yes, I'll send an example in a bit, recovered variable genes seem wildly discrepant. I can get to this tomorrow! Thanks for your quick response

**Comment by carversh** [comment]
Hi everyone, here is the way I extracted the top 500 most variable gees in seurat: 
![Screen Shot 2023-12-22 at 11 58 39 AM](https://github.com/scverse/scanpy/assets/65792233/5b59b6d1-696e-4695-a7df-ad8f74d6412f)

**Comment by carversh** [comment]
Here is the way I extracted the most variable genes in scanpy: 
![Screen Shot 2023-12-22 at 11 59 13 AM](https://github.com/scverse/scanpy/assets/65792233/97be237d-eff8-4910-b858-163d301c2bf6)

**Comment by carversh** [comment]
And out of the 500 genes identified, only 138 overlap between the sets: 
![Screen Shot 2023-12-22 at 11 59 35 AM](https://github.com/scverse/scanpy/assets/65792233/7d2459b2-a167-45cb-8107-9433aae6aac4)

**Comment by carversh** [comment]
Even when using the Seurat flavor in scanpy, the differences seem pretty drastic. Any guidance on this would be appreciated.

**Comment by carversh** [comment]
any update on this?

**Comment by flying-sheep** [comment]
We’re all on Christmas holidays, we’ll come back in January :wink:

**Comment by carversh** [comment]
Hi, just wanted to ask again if there was any update on this. Thanks in advance!

**Comment by flying-sheep** [comment]
Yes: While working on #2792, @eroell has discovered that seurat’s gene ordering doesn’t match their definition in the paper. The one in the paper makes most sense, as it’s stable (`hvg(..., n_top_genes=n) == hvg(..., n_top_genes=n+i)[:n]`).  

We now want to
1. Figure out if they’re aware. @eroell, I think you wanted to ask them if they consider the gene order in their implementation a bug?
2. If they consider it a bug and consider the paper version correct, we’d make sure that specifying `seurat_v3` will result in the (future) correct ordering. Otherwise we’ll provide a way to select between multiple orderings.

**Comment by carversh** [comment]
This means that the implementation in scanpy is according to the method in the paper? And the implementation in Seurat uses some other method. Thanks!

**Comment by flying-sheep** [comment]
If you wait a little bit, then scanpy and Seurat should agree and have the version from the paper, I assume.

**Comment by carversh** [comment]
Thanks, will do! Please keep me posted.

**Comment by flying-sheep** [comment]
We’ll update this issue when we merge the PR. You can subscribe to scanpy releases on GitHub to be notified when we release something!

**Comment by eroell** [comment]
Hi,

Thanks @carversh for opening the discussion!

Trying to get things a bit into order here, as at the moment some wrong impressions are around I think:

**1. Incorrect comparisons done here**
To my current knowledge,
- `sc.pp.highly_variable_genes(…, flavor=“seurat”)` mimics `FindVariableFeatures(…, method=“mean.var.plot”)`, operating on count-normalised, log1p-ed data.
- `sc.pp.highly_variable_genes(…, flavor=“seurat_v3”)` mimics `FindVariableFeatures(…, method=“vst”)` operating on raw gene counts (from the [Stuart et al. 2019 Seurat Version 3 paper](https://www.cell.com/cell/pdf/S0092-8674(19)30559-8.pdf))

@flying-sheep, lets put something like this into the doctstring in #2792? Will add a suggestion for you to check there. Think this is very useful information super hard to find atm.

These are 2 different methods, which scanpy implements.

> Even when using the Seurat flavor in scanpy, the differences seem pretty drastic. Any guidance on this would be appreciated.

Guidance:
In your example, you are comparing two different methods, that produce different results (like really just perform different computations). Notice `flavor=“seurat”` is default in `sc.pp.highly_variable_genes`, but `method="vst"` is default in `FindVariableFeatures`. (I see this can be confusing, we'll try to make this as clear as possible in the doc)

**2. Incorrect assumption about Seurat**
> This means that the implementation in scanpy is according to the method in the paper? And the implementation in Seurat uses some other method. Thanks!

This is not correct. There are 2 options of Seurat mixed up in this conversation here, causing quite some confusion. Seurat is giving the selected features based on what they write to the best of my knowledge.

**3. Open question on small detail**
> Yes: While working on #2792, @eroell has discovered that seurat’s gene ordering doesn’t match their definition in the paper. The one in the paper makes most sense, as it’s stable (hvg(..., n_top_genes=n) == hvg(..., n_top_genes=n+i)[:n]).

Need to emphasise this is
- a) only a question currently open (I am really not particularly an expert in R with limited bandwidth to check things there so waiting for their answer).
- b) Even if true, this does not affect our examples here. It comes into play when we try to further be as consistent with Seurat and their textual description as possible.

Yes, this is confusing :) Hope I did not confuse something myself here, checked but consider it a to-the-best-of-my-current-knowledge guidance towards a working solution for you rather than peer-reviewed ground truth ;)

**Comment by eroell** [comment]
In my trials, comparing `flavor=“seurat_v3”` compares well to `method=“vst”`: *
```py
import scanpy as sc
import pandas as pd

pbmc = sc.datasets.pbmc3k()
sc.pp.filter_cells(pbmc, min_genes=200) 
sc.pp.filter_genes(pbmc, min_cells=3)

# default settings in scanpy seurat_v3 are the same as for FindVariableFeatures
sc.pp.highly_variable_genes(pbmc, flavor="seurat_v3")

FindVariableGenes_vst = pd.read_csv(
    "seurat_hvg_v3.csv",
    index_col=0,
)

# for a brief visual: check the top 10 genes from both
top10_seurat = FindVariableGenes_vst.sort_values(
    "variance.standardized", ascending=False
).head(10)
print(top10_seurat)

top10_scanpy = pbmc.var.sort_values("variances_norm", ascending=False).iloc[:10, :]
print(top10_scanpy[["means", "variances", "variances_norm"]])
```

```
             mean     variance  variance.expected  variance.standardized
PPBP     0.245185     9.577506           0.588857              11.172765
S100A9   6.046667   278.681037          34.896905               7.985838
IGLL5    0.279259     8.894938           0.692948               7.965360
LYZ     10.246667   564.108825          70.849271               7.962098
GNLY     1.574074    45.239046           6.037842               7.492585
FTL     27.667407  2008.688897         278.996838               7.199683
PF4      0.110741     2.722449           0.213907               7.093215
FTH1    21.237407  1204.317459         192.712657               6.249291
FCER1A   0.110000     1.925280           0.212015               5.555439
GNG11    0.061481     0.725378           0.102475               5.554752
            means    variances  variances_norm
index                                         
PPBP     0.245185     9.577506       11.172765
S100A9   6.046667   278.681037        7.985838
IGLL5    0.279259     8.894938        7.965360
LYZ     10.246667   564.108825        7.962098
GNLY     1.574074    45.239046        7.492585
FTL     27.667407  2008.688897        7.199683
PF4      0.110741     2.722449        7.093215
FTH1    21.237407  1204.317459        6.249291
FCER1A   0.110000     1.925280        5.555439
GNG11    0.061481     0.725378        5.554752
```

And comparing `flavor=“seurat”` compares well to `method=“mean.var.plot”`:
```py
import scanpy as sc
import pandas as pd

pbmc = sc.datasets.pbmc3k()
sc.pp.filter_cells(pbmc, min_genes=200)
sc.pp.filter_genes(pbmc, min_cells=3)

# default settings in scanpy are the same as for Seurat
sc.pp.normalize_total(pbmc, target_sum=1e4)
sc.pp.log1p(pbmc)
sc.pp.highly_variable_genes(pbmc, flavor="seurat")

FindVariableGenes_meanvarplot = pd.read_csv(
    "seurat_hvg_mvp.csv", index_col=0
)

# for a brief visual: check the top 10 genes from both
top10_seurat = FindVariableGenes_meanvarplot.sort_values(
    "mvp.dispersion.scaled", ascending=False
).head(10)
print(top10_seurat)

top10_scanpy = pbmc.var.sort_values("dispersions_norm", ascending=False).iloc[:10, :]
print(top10_scanpy[["means", "dispersions", "dispersions_norm"]])
```

```
              mvp.mean  mvp.dispersion  mvp.dispersion.scaled
CEP128        0.151130        5.858001               7.996479
DOK3          0.272308        5.838402               7.958147
ARVCF         0.129909        5.807068               7.896862
YPEL2         0.242922        5.806298               7.895355
UBE2D4        0.254622        5.778868               7.841706
FAM210B       0.266598        5.724431               7.735234
CTB-113I20.2  0.126570        5.654503               7.598463
GBGT1         0.177501        5.604167               7.500014
LRRIQ3        0.098048        5.437717               7.174459
MTIF2         0.220279        5.371215               7.044389
                 means  dispersions  dispersions_norm
index                                                
CEP128        0.151130     5.858001          7.996479
DOK3          0.272308     5.838402          7.958147
ARVCF         0.129909     5.807068          7.896862
YPEL2         0.242923     5.806298          7.895356
UBE2D4        0.254622     5.778868          7.841706
FAM210B       0.266598     5.724431          7.735234
CTB-113I20.2  0.126570     5.654503          7.598464
GBGT1         0.177501     5.604167          7.500014
LRRIQ3        0.098048     5.437717          7.174459
MTIF2         0.220279     5.371215          7.044389
```

To generate seurat_hvg_mvp.csv, I used
```R
library(dplyr)
library(Seurat)
library(patchwork)

################################################################################
### FindVariableFeatures (no batch covariate)

# Load the PBMC dataset - load the data from the link above!
# pbmc.data <- Read10X(data.dir = "<INSERT_PATH_TO_DATA_HERE>/filtered_gene_bc_matrices/hg19/")
pbmc.data <- Read10X(data.dir = "/Users/eljas.roellin/Documents/R_stuff/filtered_gene_bc_matrices/hg19/")


# Initialize the Seurat object with the raw (non-normalized data).
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)
pbmc <- NormalizeData(pbmc, normalization.method="LogNormalize", scale.factor=10000)

pbmc <- FindVariableFeatures(pbmc, selection.method = "mean.var.plot")

hvf_info <- HVFInfo(pbmc)

write.csv(hvf_info, "seurat_hvg_mvp.csv")
```

And to generate seurat_hvg_v3.csv, I used
```R
################################################################################
### FindVariableFeatures (no batch covariate)

# Load the PBMC dataset - load the data from the link above!
# pbmc.data <- Read10X(data.dir = "<INSERT_PATH_TO_DATA_HERE>/filtered_gene_bc_matrices/hg19/")
pbmc.data <- Read10X(data.dir = "/Users/eljas.roellin/Documents/R_stuff/filtered_gene_bc_matrices/hg19/")

# Initialize the Seurat object with the raw (non-normalized data).
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)
pbmc

pbmc <- FindVariableFeatures(pbmc,  mean.function=ExpMean, selection.method = 'vst', nfeatures = 2000)

hvf_info <- HVFInfo(pbmc)

write.csv(hvf_info, "seurat_hvg_v3.csv")
```

*unless when using `batches`, a bug we are currently solving.


Nevertheless, implementation details, choices for numeric stability and numerics of the underlying libraries are indeed a challenge and do cause some discrepancies - surely interested how your comparison looks @carversh if you give these suggestions here a try!

**Comment by carversh** [comment]
Thanks so much, this is super helpful!

**Comment by flying-sheep** [comment]
> To my current knowledge,
>
> `sc.pp.highly_variable_genes(…, flavor="seurat")` mimics `FindVariableFeatures(…, method="mean.var.plot")`, operating on count-normalised, log1p-ed data.
> `sc.pp.highly_variable_genes(…, flavor="seurat_v3")` mimics `FindVariableFeatures(…, method="vst")` operating on raw gene counts (from the [Stuart et al. 2019 Seurat Version 3 paper](https://www.cell.com/cell/pdf/S0092-8674(19)30559-8.pdf))
>
> @flying-sheep, lets put something like this into the docstring in https://github.com/scverse/scanpy/pull/2792? Will add a suggestion for you to check there. Think this is very useful information super hard to find atm.

definitely!

Also I talked with @ivirshup about how to proceed with that PR, see https://github.com/scverse/scanpy/pull/2792#issuecomment-1893265335

**Comment by flying-sheep** [comment]
OK, #2792 is merged. In the next scanpy version, you can use `flavor='seurat_v3_paper'` to get the HVG ordering that perfectly matches the version they describe in the paper.
