### ISSUE TITLE
Is Louvain supposed to find more clusters with increasing resolution?

### ISSUE THREAD

**Issue by fbrundu** [scverse/scanpy#279]
Hi,
I was making the assumption that, giving more resolution to the louvain clustering, it would provide more clusters. It always worked like that, but today I find a specific dataset in which, with an increase of resolution, I found fewer clusters (figure attached).
Is it a normal behavior, or an issue?

Thanks,
Francesco

[tsne.louvain.resolution.pdf](https://github.com/theislab/scanpy/files/2439685/tsne.louvain.resolution.pdf)

**Comment by LuckyMD** [comment]
This is really interesting behaviour. Generally your expectation is correct. My guess is that it is related to the random seed. The ordering of nodes for consideration in these runs is probably different. Could you set the `random_state` to a few different values to confirm you always get more clusters in the lower resolution?

**Comment by fbrundu** [comment]
Apparently [louvain](https://scanpy.readthedocs.io/en/latest/api/scanpy.api.tl.louvain.html#scanpy.api.tl.louvain) has a default value for `random_state` (0). I tried both with 0 and 42 as `random_state` just to be sure that 0 had not a special meaning (i.e. no default random state). Interestingly, with 0 I have the same behavior, and with 42 too - although for different values of resolution. So I think we can rule out the `random_state` initialization.

I am not completely familiar with the internals of louvain, but may that be related to tie resolution during aggregation of points?

**Comment by LuckyMD** [comment]
My hunch would be that both runs just find different local minima: one being further away from the global minimum than the other. As Louvain is just a heuristic solution to an NP-hard problem, this is not surprising. Just use a random number generator for the random seed and run it 100 times for each resolution, it would probably show the expected picture again for the average number of clusters detected. 

I'm not sure if the tie breaking rule is deterministic or not. But you'd get different ties in both cases anyway I assume.

**Comment by dawe** [comment]
AFAIK this is not an issue. Louvain method optimizes global modularity but, as other methods, may miss some “true” communities. Communities in Louvain method are not intended in hierarchical way.
I suspect that what you observed applies to many scRNA data at, at least, one resolution value.

**Comment by LuckyMD** [comment]
I guess one could calculate the multi-resolution moduliarity score of both partitions with both resolutions and see if the lower number of communities is actually a more optimal modularity score than the higher number that is found. If that's the case, it's just about imperfect optimization, which is expected.
