### ISSUE TITLE
Use correct reading functions for datasets

### ISSUE THREAD

**Issue by Zethson** [scverse/scanpy#2795]
### What kind of feature would you like to request?

Additional function parameters / changed functionality / changed defaults?

### Please describe your wishes

```
  /home/zeth/miniconda3/envs/pertpy/lib/python3.11/site-packages/anndata/__init__.py:51: FutureWarning: `anndata.read` is deprecated, use `anndata.read_h5ad` instead. `ad.read` will be removed in mid 2024.
    warnings.warn(
```

They raise warnings in downstream frameworks. Some are catching the Futurewarning, but some are not

**Comment by flying-sheep** [comment]
Already fixed in https://github.com/scverse/scanpy/pull/2779
