### ISSUE TITLE
HDF5 serialization format

### ISSUE THREAD

**Issue by flying-sheep** [scverse/scanpy#28]
hi, we want to converge our HDF5 representation with SingleCellExperiment’s.

`SummarizedExperiment` already [has a HDF5 repr](https://github.com/Bioconductor/SummarizedExperiment/blob/RELEASE_3_5/R/saveHDF5SummarizedExperiment.R)

cc @davismcc @LTLA

**Comment by jorvis** [comment]
Link above is broken

**Comment by flying-sheep** [comment]
fixed, thanks. seems like Bioconductor has turned off the mirror, but put their packages in a github organization

**Comment by falexwolf** [comment]
Well, I guess the solutions via `.loom` and `.h5ad` are things that people started liking... both are investigated within the Human Cell Atlas and there will be a consensus solution at some point... No need to discuss this here anymore...
