### ISSUE TITLE
Inconsistency detected by ld.so

### ISSUE THREAD

**Issue by ar-baya** [scverse/scanpy#280]
Hi, I am reproducing this tutorial https://nbviewer.jupyter.org/github/theislab/scanpy_usage/blob/master/170503_zheng17/zheng17.ipynb

the line  sc.pp.neighbors(adata) produces the following error:

Inconsistency detected by ld.so: dl-version.c: 205: _dl_check_map_versions: Assertion `needed != NULL' failed!

Ubuntu 18.04
Python 3.6.6

scanpy==1.3.1 anndata==0.6.10 numpy==1.15.2 scipy==1.1.0 pandas==0.23.4 scikit-learn==0.19.2 statsmodels==0.9.0 python-igraph==0.7.1 louvain==0.6.1 

Can you help me? Thank You

**Comment by fidelram** [comment]
How did you installed scanpy?

Try:

conda install --file requirements.txt

this may install all the right versions of the packages that you need.

**Comment by ar-baya** [comment]
First I installed scanpy using sudo and pip as any python package. But, now I followed your advice and installed it using Bioconda, and it solved the issue.

Thank you.

**Comment by fidelram** [comment]
@ar-baya Great to hear that the advice was helpful.

**Comment by dilawar** [comment]
Same issue here. Using `pip` +pyhton3.7 and not conda to install from pypi. Is there a way to resolve it without installing using conda?

Logs:

```
[dilawars@chamcham scanpy_exp]$ python planaria.py 
/home1/dilawars/.local/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
scanpy==1.3.1 anndata==0.6.10 numpy==1.15.2 scipy==1.1.0 pandas==0.23.4 scikit-learn==0.20.0 statsmodels==0.9.0 python-igraph==0.7.1 
... storing 'clusters' as categorical
computing tSNE
    using data matrix X directly
    using the 'MulticoreTSNE' package by Ulyanov (2017)
    finished (0:02:53.98)
saving figure to file ./figures/tsne_full.pdf
computing neighbors
    using data matrix X directly
Inconsistency detected by ld.so: dl-version.c: 205: _dl_check_map_versions: Assertion `needed != NULL' failed!
```

**Comment by fidelram** [comment]
That error is not specific to scanpy. It would be good to know which
library is causing the problem such that it can be updated but most likely
is either numpy, scipy, matplotlib or sklearn. Maybe try to update those
packages and see if the error goes away or try to google the error to find
some solution.

**Comment by dilawar** [comment]
Its an issue with numba. See here https://github.com/jmschrei/apricot/blob/98693788ca315ceceeb2eb0f4ce8526f40e0049b/README.md

*Update* Quoting from the REAME above

> If you get an error that looks like
> 
> Inconsistency detected by ld.so: dl-version.c: 224: _dl_check_map_versions: Assertion `needed != NULL' failed!
> 
> or a segmentation fault when importing apricot for the first time then you should try reinstalling numba through conda using
> 
> conda install numba.
> 
> or
> 
> pip install numba==0.39.0
> 
> The issue appears to be with the most recent verson of numba, v0.40.0. Downgrading to numba v0.39.0 should solve the issue. 
> 

That means numba should be frozen to v0.39.0 .

**Comment by dilawar** [comment]
I confirm that with `numba==0.39.0' the problem goes away.
