### ISSUE TITLE
Contribution of scripts to scanpy main repo

### ISSUE THREAD

**Issue by pcm32** [scverse/scanpy#281]
Hi there! Thanks for such a great tool.

We are working with a group of people at EBI, Sanger, U. of Freiburg, Earlham (Norwich), the US and Australia in trying to bring different single cell analysis tools to Galaxy and other workflow environments. For tools like Seurat, SC3 or Scanpy, which are normally used as libraries, we are writing an scripting layer for each of these to facilitate their use directly from the shell for well defined functionality (to be called then from whatever workflow environment people want to use). You can get an idea based on what we have here for Seurat for instance https://github.com/ebi-gene-expression-group/r-seurat-scripts. We normally make a conda package out of this called \<tool\>-scripts. This probably fits well in the initial development phase where we want to be agile in the generation of these, but in the mid and definitely longer term, we would really like to contribute those scripts to the main tool repos, so that they are distributed and installed with them. Would you welcome such contribution (a set of scripts for high level functionality that can be used as executables from a shell) in this git repo?

This is where we are discussing things a bit with this community:
https://github.com/galaxyproject/tools-iuc/issues/2057

Current WIP for scanpy scripts (see feature branches):
https://github.com/ebi-gene-expression-group/scanpy-scripts/tree/feature/read10x

**Comment by falexwolf** [comment]
Cool!

Initially, Scanpy came with a built-in command-line interface. But I threw it out after a couple of months as it was hard to maintain both the interface and the library at the same time, I also expected a bit too much from the command-line interface at the time, I guess.

I'd really like to support your much better efforts for generating command line interfaces. But I'm a bit hesitant to maintain it here in the main repo - already the library is already so much to take care of and other libraries typically don't involve a "script-wrapper", too.

What about a PyPI package `scanpy-scripts`, which directly advertise from the Scanpy main docs, we could also have a little tutorial there. Similar to that, there will be interactive visual interfaces to scanpy, again as separate packages. I tend to think that this would be the better option. But if I miss something fundamental, please convince me of the opposite.

**Comment by pcm32** [comment]
Yes, we can continue with the scanpy-scripts separate package if you prefer, and make sure that things are properly linked.

**Comment by falexwolf** [comment]
If you think this is a viable option without great disadvantages I have to admit that I'd prefer that. 🙂

**Comment by freeman-lab** [comment]
hey all! fun discussion. as an FYI, over on the `cellxgene` project we're proposing a little standalone CLI that does some basic preprocessing of data with `scanpy` for the purpose of then being visualized (includes some basic filtering, pca, neighbors, umap, etc.)

current PR is here https://github.com/chanzuckerberg/cellxgene/pull/358

in general, really like @falexwolf 's idea of a `scanpy-scripts` CLI, and would be happy to contribute to that discussion, and potentially use / reuse some of what we're doing if useful

**Comment by pcm32** [comment]
Hi @freeman-lab, we have now quite a number of modules:

https://github.com/ebi-gene-expression-group/scanpy-scripts

And, as our other seurat-scripts, sc3-scripts and scater-scripts, it is bioconda installable (or in the way to be). We would be happy to accept your module, although it would be good to see how much it overlaps or not with existing parts already there, to find the best way to integrate it.

**Comment by flying-sheep** [comment]
I have an idea. We provide a base `scanpy` command here.

It works the same as the `jupyter` binary, i.e. it searches for commands named `scanpy-something` in the `$PATH`. Once one installs `scanpy-scripts`, there will be many commands like `scanpy-filter-genes` (without `.py`, I can assist in making that happen via entry-points and publishing it to PyPI)

Calling `scanpy` without arguments will then list all those commands, and `scanpy filter-genes` (note the space) will call the respective command.

**Comment by pcm32** [comment]
Sounds good, we are currently hosting the whole scanpy-scripts as a bioconda package, but we could look into having it as pip installable as well. Does this means that scanpy administrators are happy to have the scanpy-scripts code poured here to make them pip installable, or that you want to contribute the pip packaging to the repo where we currently have scanpy-scripts? We have travis testing for our scripts layer, that would make maintenance easier on your side, as it would detect any changes on scanpy that break the scripts layers (taking you to only break API if extremely necessary - in turn making your tool more stable for external users).

**Comment by flying-sheep** [comment]
> Does this means that […] that you want to contribute the pip packaging to the repo where we currently have scanpy-scripts?

I meant the quoted alternative, alex was against the other alternative if I understand him correctly.

**Comment by pcm32** [comment]
Sure, by all means, open a PR at https://github.com/ebi-gene-expression-group/scanpy-scripts with the directory reformatting and needed metadata files for pip installation.

**Comment by flying-sheep** [comment]
Maybe a better name for the project would then be “Scanpy CLI” or so.

And you mean https://github.com/ebi-gene-expression-group/scanpy-scripts, right?

**Comment by pcm32** [comment]
Sorry, pasted wrong link, see now ^^^^

**Comment by falexwolf** [comment]
@flying-sheep Thanks for fielding all this! You never wrote what thought about having the CLI layer in the scanpy repo... my main reason is that I simply think that I cannot maintain a layer that I'm not actively using (at least right now) and that the library maintenance and development is already quite some work...

**Comment by flying-sheep** [comment]
Exactly, this is why I think it’s a great solution to advertise that repo in the scanpy docs and make scanpy provide a wrapper binary

I added ebi-gene-expression-group/scanpy-scripts#24, let me hear what you think

**Comment by flying-sheep** [comment]
Hi @pcm32 I finally got around to this. In the next scanpy version, you should be able to invoke your scripts via e.g `scanpy filter-cells`, and `scanpy -h` and `scanpy settings` will do something too.

**Comment by nh3** [comment]
Hi @flying-sheep, just saw your updates here. I was slowly working on a re-structured scanpy-scripts that has a sub-command interface i.e `scanpy-cli read`, `scanpy-cli filter` etc and with some added functionality for convenience (https://github.com/ebi-gene-expression-group/scanpy-scripts/pull/40). I'll try change the interface back to make it compatible with yours.

**Comment by flying-sheep** [comment]
damn, sorry I took so long that you now made all this effort for nothing!

if you have any ideas on how the main scanpy command can be improved, please share them!

**Comment by nh3** [comment]
it's ok, what it takes is just changing the entry points. I need this re-structure anyway for a lot of other reasons, and it's nice to have the scanpy executable in scanpy so that many others can contribute cli, so no worries at all!

**Comment by nh3** [comment]
Just tested, works perfectly with the main command. Brilliant job @flying-sheep!

**Comment by flying-sheep** [comment]
great to hear!
