### ISSUE TITLE
error in sc.tl.rank_genes_groups

### ISSUE THREAD

**Issue by kamanso** [scverse/scanpy#2821]
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

### What happened?

Hi all.  I was having issues generating rank gene groups. The error is as below. When I used the "Manuscript_Identity" group,  I got such error message, but when I used another group "CellType_Category", it worked. These two groups are in the same type. Could you tell me how to fix it?
Look forward to your response, thanks a lot!

### Minimal code sample

```python
sc.tl.rank_genes_groups(adata_sc, groupby="Manuscript_Identity", use_raw=False)

adata_sc.obs['CellType_Category'].cat.categories
Index(['Endothelial', 'Epithelial', 'Lymphoid', 'Multiplet', 'Myeloid',
       'Stromal'],
      dtype='object')
adata_sc.obs['Manuscript_Identity'].cat.categories
Index(['ATI', 'ATII', 'Aberrant_Basaloid', 'B', 'B_Plasma', 'Basal',
       'Ciliated', 'Club', 'DC_Langerhans', 'DC_Mature', 'Fibroblast',
       'Goblet', 'ILC_A', 'ILC_B', 'Ionocyte', 'Lymphatic', 'Macrophage',
       'Macrophage_Alveolar', 'Mast', 'Mesothelial', 'Multiplet',
       'Myofibroblast', 'NK', 'PNEC', 'Pericyte', 'SMC', 'T', 'T_Cytotoxic',
       'T_Regulatory', 'VE_Arterial', 'VE_Capillary_A', 'VE_Capillary_B',
       'VE_Peribronchial', 'VE_Venous', 'cDC1', 'cDC2', 'cMonocyte',
       'ncMonocyte', 'pDC'],
      dtype='object')
```

### Error output

```pytb
WARNING: Default of the method has been changed to 't-test' from 't-test_overestim_var'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/udd/rekso/.conda/envs/rekso_tangram_env/lib/python3.9/site-packages/scanpy/tools/_rank_genes_groups.py", line 592, in rank_genes_groups
    test_obj = _RankGenes(adata, groups_order, groupby, reference, use_raw, layer, pts)
  File "/udd/rekso/.conda/envs/rekso_tangram_env/lib/python3.9/site-packages/scanpy/tools/_rank_genes_groups.py", line 106, in __init__
    raise ValueError(
ValueError: Could not calculate statistics for groups Ionocyte since they only contain one sample.
```

### Versions

<details>

```
setuptools                  69.0.3
shapely                     2.0.2
six                         1.16.0
skimage                     0.20.0
sklearn                     1.3.2
socks                       1.7.1
spatial_image               0.3.0
spatialdata                 0.0.15
squidpy                     1.3.1
stack_data                  0.6.2
statsmodels                 0.14.1
sympy                       1.12
tangram                     1.0.4
tblib                       3.0.0
texttable                   1.7.0
threadpoolctl               3.2.0
tifffile                    2023.12.9
tlz                         0.12.0
toolz                       0.12.0
torch                       2.1.2+cu121
torchgen                    NA
tqdm                        4.66.1
traitlets                   5.14.1
typing_extensions           NA
umap                        0.5.5
urllib3                     2.1.0
validators                  0.22.0
wcwidth                     0.2.13
xarray                      2023.12.0
xarray_dataclasses          1.7.0
xarray_schema               0.0.3
xrspatial                   0.3.7
yaml                        6.0.1
zarr                        2.16.1
zipp                        NA
zoneinfo                    NA
-----
Python 3.9.18 | packaged by conda-forge | (main, Dec 23 2023, 16:33:10) [GCC 12.3.0]
Linux-4.18.0-477.15.1.el8_8.x86_64-x86_64-with-glibc2.28

```

</details>

**Comment by Zethson** [comment]
Do you have more than one sample for this group?

> ValueError: Could not calculate statistics for groups Ionocyte since they only contain one sample.

Generally, please post usage questions in the [scverse discourse](https://discourse.scverse.org)

**Comment by kamanso** [comment]
> Do you have more than one sample for this group?
> 
> > ValueError: Could not calculate statistics for groups Ionocyte since they only contain one sample.
> 
> Generally, please post usage questions in the [scverse discourse](https://discourse.scverse.org)

Yes, this group has 39 categories:

[2992 rows x 17 columns]
>>> adata_sc.obs['Manuscript_Identity']
010I_AAACCTGAGAAGCCCA       Macrophage
010I_AAACCTGAGTCGAGTG       Macrophage
010I_AAACGGGGTCATACTG       Macrophage
010I_AAACGGGGTTGGACCC                T
010I_AAAGATGAGAACTGTA                B
                             ...
8CO_TGGGCGTTCTTAGCCC         cMonocyte
8CO_TGGTTCCGTCTCACCT              ATII
8CO_TTGACTTGTCGGCTCA     Myofibroblast
8CO_TTGTAGGTCCAGATCA         cMonocyte
8CO_TTTATGCGTAGGCTGA         VE_Venous
Name: Manuscript_Identity, Length: 78081, dtype: category
Categories (39, object): ['ATI', 'ATII', 'Aberrant_Basaloid', 'B', ..., 'cDC2', 'cMonocyte',
                          'ncMonocyte', 'pDC']

**Comment by eroell** [comment]
I am not sure what code you used to generate the above output? In any case

> Could not calculate statistics for groups Ionocyte since they only contain one sample.

The issue seems to be related to Ionocytes.

so `adata_sc.obs['Manuscript_Identity'].value_counts()` or so would be needed to check that indeed more than 1 Ionocyte is present.

**Comment by kamanso** [comment]
> I am not sure what code you used to generate the above output? In any case
> 
> > Could not calculate statistics for groups Ionocyte since they only contain one sample.
> 
> The issue seems to be related to Ionocytes.
> 
> so `adata_sc.obs['Manuscript_Identity'].value_counts()` or so would be needed to check that indeed more than 1 Ionocyte is present.

I ran the code you sent to me, hers is the result: 
'Manuscript_Identity
Macrophage             14051
T_Cytotoxic            10739
T                       9941
Macrophage_Alveolar     9938
NK                      7997
cMonocyte               5508
B                       4506
ncMonocyte              2291
Multiplet               1300
Myofibroblast           1153
Ciliated                1055
Mast                     987
cDC2                     867
T_Regulatory             809
Lymphatic                677
VE_Capillary_B           571
VE_Peribronchial         556
Fibroblast               527
ILC_A                    392
B_Plasma                 379
ATII                     364
Club                     362
Pericyte                 309
VE_Arterial              309
pDC                      289
ILC_B                    288
SMC                      284
VE_Capillary_A           276
ATI                      268
cDC1                     249
VE_Venous                244
Basal                    172
DC_Mature                149
Mesothelial              109
Goblet                   103
Aberrant_Basaloid         32
DC_Langerhans             20
PNEC                       9
Ionocyte                   1
Name: count, dtype: int64
'

So I just need to remove "Ionocyte"  group, it could be work,right?

**Comment by eroell** [comment]
Since `sc.tl.rank_genes_groups` computes e.g. the variance within groups, there has to be more samples per group than 1, yes.
What cells you want remove during your analysis can be a tricky question, (e.g. maybe a strict preprocessing kicks out many cells) - but if you want to use this method on your data you seem to use here, the single Ionocyte has to be removed.

Hope this helps!

Quick hint: as mentioned above, ideally you raise such a question here: [scverse discourse](https://discourse.scverse.org/)
This way, other users who encounter the same problem as you will also find the answer, easier than here :)

**Comment by eroell** [comment]
I will close the issue for now, as based on the provided information and the discussion so far, it seems that the question has been addressed and hopefully resolved :)

However, please don't hesitate to start user questions on [scverse discourse](https://discourse.scverse.org/), or software & maintenance releated things here. Or reopen the issue if you think I missed your point!

Thanks for being a part of our community! :)
