### ISSUE TITLE
Fix plotting warnings raised in tutorial notebooks

### ISSUE THREAD

**Issue by ilan-gold** [scverse/scanpy#2839]
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [X] (optional) I have confirmed this bug exists on the master branch of scanpy.

### What happened?

Many different calls in scanpy emit warnings that are currently suppressed by our testing framework (I think).  

### Minimal code sample

I discovered this unrelatedly by editing the notebooks, see for example: https://github.com/scverse/scanpy-tutorials/blob/master/spatial/integration-scanorama.ipynb

@flying-sheep mentioned that the scanpy tests filter out warnings and indeed you can reproduce these by e.g.,:
```sh
pytest -W error::FutureWarning -n auto scanpy/tests/test_plotting.py
```

### Error output

- [x] `…/scanpy/plotting/_tools/scatterplots.py:401:`

  > UserWarning: No data for colormapping provided via 'c'. Parameters 'cmap' will be ignored

- [x] `…/scanpy/plotting/_tools/__init__.py:1269:`

   > FutureWarning: The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.  
  > `_ax = sns.violinplot(`

- [x] `…/scanpy/preprocessing/_simple.py:274:`

  > ImplicitModificationWarning: Trying to modify attribute `.var` of view, initializing view as actual.
  > `adata.var["n_cells"] = number`

- [x] `…/scanpy/plotting/_stacked_violin.py:503: FutureWarning:`

  > Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect. 
  > `row_ax = sns.violinplot(`

### Versions

<details>

```
-----
anndata     0.10.4
scanpy      1.10.0.dev191+gf7f5d5c6
-----
IPython             8.20.0
PIL                 10.2.0
asciitree           NA
asttokens           NA
cffi                1.16.0
cloudpickle         3.0.0
cycler              0.12.1
cython_runtime      NA
dask                2024.1.0
dateutil            2.8.2
decorator           5.1.1
defusedxml          0.7.1
executing           2.0.1
fasteners           0.19
h5py                3.10.0
igraph              0.10.8
iniconfig           NA
jedi                0.19.1
jinja2              3.1.3
joblib              1.3.2
kiwisolver          1.4.5
legacy_api_wrap     NA
leidenalg           0.10.1
llvmlite            0.41.1
markupsafe          2.1.3
matplotlib          3.8.2
mpl_toolkits        NA
msgpack             1.0.7
natsort             8.4.0
numba               0.58.1
numcodecs           0.12.1
numpy               1.26.3
packaging           23.2
pandas              2.1.4
parso               0.8.3
pexpect             4.9.0
pluggy              1.3.0
prompt_toolkit      3.0.43
psutil              5.9.7
ptyprocess          0.7.0
pure_eval           0.2.2
py                  NA
pygments            2.17.2
pyparsing           3.1.1
pytest              7.4.4
pytz                2023.3.post1
scipy               1.11.4
session_info        1.0.0
setuptools          68.2.2
setuptools_scm      NA
sitecustomize       NA
six                 1.16.0
sklearn             1.3.2
sparse              0.15.1
stack_data          0.6.3
tblib               3.0.0
texttable           1.7.0
threadpoolctl       3.2.0
tlz                 0.12.0
toolz               0.12.0
traitlets           5.14.1
typing_extensions   NA
wcwidth             0.2.13
yaml                6.0.1
zarr                2.16.1
zipp                NA
-----
Python 3.11.6 (main, Nov  2 2023, 04:39:43) [Clang 14.0.3 (clang-1403.0.22.14.1)]
macOS-13.6.1-arm64-arm-64bit
-----
Session information updated at 2024-01-30 16:40
```

</details>

**Comment by ilan-gold** [comment]
Apologies for the bug but this didn't seem like an enhancement and strikes me as something close to a bug.

**Comment by flying-sheep** [comment]
The `ImplicitModificationWarning` should just be fixed in the notebook:

```diff
-adata_merfish = counts[coordinates.index, :]
+adata_merfish = counts[coordinates.index, :].copy()
 adata_merfish.obsm["spatial"] = coordinates.to_numpy()
```

/edit: done
