### ISSUE TITLE
Use of fast_matrix_market library to read mtx files

### ISSUE THREAD

**Issue by IreneRobles** [scverse/scanpy#2846]
### What kind of feature would you like to request?

Additional function parameters / changed functionality / changed defaults?

#### Summary
Integration of the `polars` and `fast_matrix_market` libraries into Scanpy's data loading functions, specifically `scanpy.read_10x_mtx` and `scanpy.read_mtx`. This will improve the loading speed of `.mtx` and `.csv` files, which is crucial for handling large-scale single-cell datasets more efficiently.

#### The problem
The current data loading mechanisms in Scanpy, while effective for small to medium datasets, could be substantially optimized for speed when dealing with larger datasets.

#### Expected Impact
- Reduced loading times
- Improving the user experience
- Enhanced scalability

#### Code snipped

```
import fast_matrix_market
import os
import scanpy as sc
import scipy as sp

def read_10x_faster(
   path: str
   )-> sc.AnnData:
    """
    Read a sparse matrix in Matrix Market format and two CSV files with gene and cell metadata
    into an AnnData object.
    
    Args:
        path: Path to the directory containing the matrix.mtx, genes.tsv, and barcodes.tsv files.
        
    Returns:
        An AnnData object with the matrix, gene metadata, and cell metadata.

    """
    mtx_file = os.path.join(path, "matrix.mtx")
    gene_info = os.path.join(path, "genes.tsv")
    cell_metadata = os.path.join(path, "barcodes.tsv")
    
    # Read the .mtx file into a sparse matrix using the fast_matrix_market package (faster than scanpy, uses multiprocessing)
    mtx = fast_matrix_market.mmread(mtx_file)

    # Convert the sparse matrix to a CSR matrix
    # Otherwise you will not be able to use it with scanpy
    if isinstance(mtx, sp.sparse.coo.coo_matrix):
        mtx = mtx.tocsr()
    
    # Create an AnnData object
    adata = sc.AnnData(X=mtx.T)

    # Polars is faster than pandas reading csv files
    # Read the gene names and cell names into the AnnData object
    adata.var = pl.read_csv(gene_info, separator= '\t', has_header=False).to_pandas()
    
    # Read the cell names and cell metadata into the AnnData object
    adata.obs = pl.read_csv(cell_metadata, separator= '\t', has_header=False).to_pandas()
    return adata
```

**Comment by ivirshup** [comment]
Thanks for opening an issue!

I believe scipy's `mmread` (which is being used under the hood) recently switched to using `fast_matrix_market` as of scipy `1.12`

* https://github.com/alugowski/fast_matrix_market/issues/22
* https://github.com/scipy/scipy/pull/18631

So I'm sure any action here is needed. Please let me know if this isn't behaving as expected with the newest scipy release.
