### ISSUE TITLE
only for python3?

### ISSUE THREAD

**Issue by worker000000** [scverse/scanpy#285]
I tried seveal times in both win and linux， python2 can not install scany, si there a solution for python2, thanks a lot

**Comment by falexwolf** [comment]
python 2 is not supported as evident from the docs and pypi.

**Comment by gokceneraslan** [comment]
The main reason is that Python 2 is getting obsolete really soon, therefore we do not think allocating resources for maintaining it is worthwhile. See https://python3statement.org/ for more details. Another reason is that there are many nice Python3-only features that are being used in Scanpy such as function annotations.

**Comment by worker000000** [comment]
> The main reason is that Python 2 is getting obsolete really soon, therefore we do not think allocating resources for maintaining it is worthwhile. See https://python3statement.org/ for more details. Another reason is that there are many nice Python3-only features that are being used in Scanpy such as function annotations.

thanks a lot.

**Comment by worker000000** [comment]
> python 2 is not supported as evident from the docs and pypi.

thanks a lot.
