### ISSUE TITLE
sc.pp.subsample, allow for sampling with replacement

### ISSUE THREAD

**Issue by AlexAdrian-Hamazaki** [scverse/scanpy#2854]
### What kind of feature would you like to request?

Additional function parameters / changed functionality / changed defaults?

### Please describe your wishes

Currently sc.pp.subsample does not allow for sampling with replacement.

When n_obs is provided, and it is larger than the size of the adata object, an error message from numpy.random.choice is given.
"obs_indices = np.random.choice(old_n_obs, size=new_n_obs, replace=False)"

It seems like replace is automatically set to False.

It would be great if sc.pp.subsample provided a paramater to change the np.random.choice's 'replace' parameter to True.

**Comment by ivirshup** [comment]
It looks like there is an old stalled PR for this. 

* https://github.com/scverse/scanpy/pull/943

Would you want to pick that up?
