### ISSUE TITLE
Rename master -> main

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#2869]
### What kind of feature would you like to request?

Other?

### Please describe your wishes

Once we branch for the 1.10 release series we should do the branch renaming.

Some docs about this:

* https://github.com/github/renaming

**Comment by flying-sheep** [comment]
why wait? is there anything blocking doing that right now?

**Comment by ivirshup** [comment]
It requires all open PRs to do something, and we are going to have to wait for at least one round of CI after we do this.

**Comment by flying-sheep** [comment]
no it doesn’t, they get automatically switched. The CI think is true though.

**Comment by ivirshup** [comment]
Done, but people with existing clones will need to run:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

I'm going to pin this for a bit to make it more visible
