### ISSUE TITLE
Export figures in full vector mode

### ISSUE THREAD

**Issue by juugii** [scverse/scanpy#287]
Hello,
Is it possible to save/export figures in full vector graphic mode ? For now it is possible to save figures by adding:

`sc.pl.tsne(..., save='_myfigure.svg')`

but it gives only partial vector graphic outputs, with only titles and axis in vector graphics, and cells or other graph elements (dots) being incorporated as compressed images (not filled vector circles). Exporting to .pdf extension doesn't works either. Full vector graphics figures are much easier to post-process (eg. if one wants to unify the color codes of several outputs for publication-grade purposes without having to recode 'manually' them within scripts).
Thanks.

**Comment by falexwolf** [comment]
Yes, see https://scanpy.readthedocs.io/en/latest/api/scanpy.api.set_figure_params.html#scanpy.api.set_figure_params.

**Comment by juugii** [comment]
Problem solved. Thanks a lot!

**Comment by brianpenghe** [comment]
> Yes, see https://scanpy.readthedocs.io/en/latest/api/scanpy.api.set_figure_params.html#scanpy.api.set_figure_params.

The link is broken

**Comment by HHAHAXY** [comment]
Suggest this one is correct https://scanpy.readthedocs.io/en/stable/api/scanpy.set_figure_params.html
