### ISSUE TITLE
More in depth example for `neighbors(transformer=...)`

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#2871]
### What kind of feature would you like to request?

Additional function parameters / changed functionality / changed defaults?

### Please describe your wishes

It would be nice to have a more in depth usage example for the new transformer feature for `neighbors`

In particular it would be nice to show how a faster backend can be used. This could be stand alone, and not part of the usage docs.

**Comment by flying-sheep** [comment]
Done in #2903 and scverse/scanpy-tutorials#87
