### ISSUE TITLE
Out of Memory filtering returns TypeError

### ISSUE THREAD

**Issue by fratajcz** [scverse/scanpy#2894]
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the main branch of scanpy.

### What happened?

Hi!

I am new to scanpy and I am facing some trouble reading my data in an appropriate way. I noticed that anndata objects in memory require roughly 4x the space they require on disk, so working with large datasets (>50GB on disk) is prohibitive in most scenarios. The USP of h5 files, however, is that you can index and slice them on disk as if they were in memory. This way I could greatly reduce the data size before loading it into memory. However, when I attempt to filter on a backed anndata object, I encounter a TypeError. The case of gene filtering should be just a column-sum, comparing it against a threshold and then saving it as a boolean index mask. It seems like the case that the data is backed and not in memory - which should be the default when dealing with h5 files - is not considered in the scanpy API. Am I simply missing something here?

### Minimal code sample

```python
from urllib.request import urlretrieve
import scanpy as sc


# We are downloading a small dataset here, 43MB.

url = "https://datasets.cellxgene.cziscience.com/7fb8b010-50bd-4238-a466-7c598f16d061.h5ad"
filename = "testfile.h5ad"

urlretrieve(url, filename)

adata = sc.read_h5ad(filename, backed="r+")

sc.pp.filter_genes(adata, min_cells=100)
```

### Error output

```pytb
Traceback (most recent call last):
  File "/home/ubuntu/test_scanpy.py", line 11, in <module>
    sc.pp.filter_genes(adata, min_cells=100)
  File "/mnt/storage/anaconda3/envs/scanpy/lib/python3.12/site-packages/scanpy/preprocessing/_simple.py", line 237, in filter_genes
    filter_genes(
  File "/mnt/storage/anaconda3/envs/scanpy/lib/python3.12/site-packages/scanpy/preprocessing/_simple.py", line 258, in filter_genes
    X if min_cells is None and max_cells is None else X > 0, axis=0
                                                      ^^^^^
TypeError: '>' not supported between instances of 'CSRDataset' and 'int'
```

### Versions

<details>

```
Matplotlib is building the font cache; this may take a moment.
-----
anndata     0.10.5.post1
scanpy      1.9.8
-----
PIL                 10.2.0
colorama            0.4.6
cycler              0.12.1
cython_runtime      NA
dateutil            2.8.2
h5py                3.10.0
igraph              0.11.4
joblib              1.3.2
kiwisolver          1.4.5
leidenalg           0.10.2
llvmlite            0.42.0
matplotlib          3.8.3
mpl_toolkits        NA
natsort             8.4.0
numba               0.59.0
numpy               1.26.4
packaging           23.2
pandas              2.2.1
psutil              5.9.8
pyparsing           3.1.1
pytz                2024.1
scipy               1.12.0
session_info        1.0.0
six                 1.16.0
sklearn             1.4.1.post1
texttable           1.7.0
threadpoolctl       3.3.0
typing_extensions   NA
wcwidth             0.2.13
-----
Python 3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:50:58) [GCC 12.3.0]
Linux-5.4.0-165-generic-x86_64-with-glibc2.31
-----
Session information updated at 2024-03-05 10:07
```

</details>

**Comment by ilan-gold** [comment]
The broader issue here is what we do and don't support with `backed` mode.  As our dask support grows, that will likely be the recommended route going forward.  Thus, it would make sense to come up with concrete recommendations for that so we have "officially supported" out of core functionality.
