### ISSUE TITLE
conda installation?

### ISSUE THREAD

**Issue by hkoohy** [scverse/scanpy#29]
Hi Guys,
Thanks for developing such a wonderful tool in python.
Do you mind to point me on how to install scanpy under anaconda environment? currently "conda search scanpy"  doesn't find it?!
Thanks
Hashem

**Comment by falexwolf** [comment]
Just use `pip` as comes with a minimal conda environment (see `conda list`) and follow the steps in the README. I myself am also using anaconda on many occasions.

**Comment by falexwolf** [comment]
PS: If you have a conda environment for Python 3, you do not need to use `pip3`; simply use `pip`.

**Comment by hkoohy** [comment]
Hi Alex,
Thanks for your very prompt reply. The problem is solved.
Looking forward using it.
Hashem

**Comment by flying-sheep** [comment]
i don’t like anaconda, it brings its own versions of libraries, which is a constant pain. and with wheels there’s zero advantage in having it.

@falexwolf it’s super easy to upload a release for the latest tag. you can put this in a script or makefile or so:

```bash
(
  set -e
  tag=$(git describe --abbrev=0)
  git checkout $tag
  python3 setup.py bdist_wheel
  twine upload dist/scanpy-$tag-*.whl
)
git checkout master
```

**Comment by hkoohy** [comment]
Now I am getting confused, Shall I go ahead with the pip installation (Alex suggestion) which is  under my default conda environment or shall I go as flying-sheep suggests with its own environment?

**Comment by falexwolf** [comment]
If you use anaconda just do what I suggested. If you ever think about not using anaconda anymore, you can still do what I suggested. `pip` works in both cases.

**Comment by flying-sheep** [comment]
sorry for spreading confusion!

alex is right: i didn’t recommend using some environment, and `pip`-installed packages will work with your anaconda installation.

but for new systems i recommend just installing python (not anaconda), and using exclusively `pip` for python package management.

**Comment by flying-sheep** [comment]
hi, sorry for the confusion. i removed the comments not relevant to the issue.

for the record:

- continuum inc. is responsible for providing packages installable with `conda`, we can’t influence that IIRC. they will probably eventually include scanpy.
- python comes with `pip` by default, and `pip` can be used to install all packages on [the python package index](https://pypi.python.org)
- the only advantage of anaconda is that it comes with preinstalled packages, but installing scanpy via `pip` will always be just as fast as it will eventually be with `conda`.

**Comment by k3yavi** [comment]
Hi guys,
Scanpy is really awesome and fast !!
Just wanted to add here Bioconda could be an alternative way to distribute scanpy but pip too works just fine.

**Comment by falexwolf** [comment]
Yes, as anndata already is on bioconda, that is something we might consider. But it's not a priority right now.
