### ISSUE TITLE
Return type of aggregate is inconsistent

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#2930]
```python
import scanpy as sc
adata = sc.datasets.pbmc68k_reduced()
sc.get.aggregate(adata, by="louvain", func="mean")
```

```
AnnData object with n_obs × n_vars = 11 × 765
    obs: 'louvain'
    var: 'n_counts', 'means', 'dispersions', 'dispersions_norm', 'highly_variable'
    layers: 'mean'
```

```python
sc.get.aggregate(adata.obsm["X_umap"], by=adata.obs["louvain"].array, func="mean")
```

```
{'mean': array([[ -6.18019123,  -6.12846152],
        [ -3.10995685,   8.4991954 ],
        [  6.30307056,  -2.15245383],
        [ -4.72268065,  -3.24033642],
        [-11.94002487,  -5.39480163],
        [ -1.39242794,   6.6239316 ],
        [  4.3991326 ,  -0.16749119],
        [  4.847834  ,  -9.30549509],
        [-10.41891144,  -1.15700949],
        [ -7.91249486,  -4.06782072],
        [  1.12418592,  -6.94506866]])}
```

So it returns an `AnnData` when an `AnnData` is passed, but a dict when a less structured object is passed.

This is probably because it's `singledispatched` under the hood, but IDK that this behaviour is great.

I think it could make more sense for this to either:

* Always return an `AnnData`
* Throw an error if something other than an AnnData is passed in

A third option is that we document this behaviour, but I generally don't love it.

There are other places that we do something like this, i.e. return a different type depending on the input. However, I feel like there's more of a loss of information here and less of an obvious return type.

Maybe in future this could get a `return_type: type[AnnData] | type[Dict] | type[xr.Dataset] = AnnData` argument that controls what is returned?

WDYT @ilan-gold @Intron7?

**Comment by Intron7** [comment]
I think we should return `AnnData`. Its better than a dict IMO.

**Comment by ivirshup** [comment]
And leave in the ability to pass arrays directly?

**Comment by Intron7** [comment]
I think we can remove that. But I never support passing a matrix in RSC, so I'm biased.

**Comment by ilan-gold** [comment]
> Throw an error if something other than an AnnData is passed in

I am in favor of this (so it seems like @Intron7  and I agree on this).  And then using some sort of `key` arguments to specify where to fetch the aggregatable data from.

> Maybe in future this could get a return_type: type[AnnData] | type[Dict] | type[xr.Dataset] = AnnData argument that controls what is returned?

I would also be in favor of this if we want to leave the option of getting a `dict` back.

**Comment by flying-sheep** [comment]
I agree, I always thought that using singledispatch isn’t the right tool when the function has vastly different signatures for each of the cases.

The non-anndata case should just be a private helper function instead.
