### ISSUE TITLE
Dependency on `legacy-api-wrap` prevents 1.10 conda release

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#2966]
No recent version of legacy-api-wrap has been uploaded to conda. So, we can't make a conda release of scanpy 1.10.

* https://github.com/conda-forge/scanpy-feedstock/pull/15

Since it's a single file with a single function, I'm very up for vendor-ing it:

* https://github.com/scverse/anndata/issues/1301

cc: @flying-sheep

**Comment by flying-sheep** [comment]
Fixed https://anaconda.org/conda-forge/legacy-api-wrap
