### ISSUE TITLE
`title` is no longer acting like "vectorized" argument for scatter plots

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#298]
As an example, the following code produces different outputs in scanpy `v1.3.1` and 80e635d:

```python
import scanpy.api as sc
import numpy as np

N = 1000
M = 2000

adata = sc.AnnData(X=np.random.random_sample((N, M)))

sc.pp.pca(adata)
sc.pl.pca(adata, color=["1","2","3"], title=["a", "b", "c"])
```

In `v1.3.1` this shows:

![pca_scatterprevious_titles](https://user-images.githubusercontent.com/8238804/46931190-e0802880-d095-11e8-8f94-78e3cc71f2d4.png)

In 80e635d this shows:

![pcacurrent_titles](https://user-images.githubusercontent.com/8238804/46931205-f261cb80-d095-11e8-8160-50997c16d35a.png)

**Comment by fidelram** [comment]
I didn't know this was possible before! I Will fix that.
