### ISSUE TITLE
Scatter plots no longer like np.arrays for color argument

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#299]
Comparing `v1.3.1` and 80e635d (current master) on the following code:

```python
import scanpy.api as sc
import numpy as np

N = 1000
M = 2000

adata = sc.AnnData(X=np.random.random_sample((N, M)))

sc.pp.pca(adata)
sc.pl.pca(adata, color=np.array(["1","2","3"]))
```

In `v1.3.1` this shows:

![pca_scatter_prev_colorarray](https://user-images.githubusercontent.com/8238804/46932091-ce07ee00-d099-11e8-8002-f4921e30849c.png)

In 80e635d this shows:

![pca_cur_colorarray](https://user-images.githubusercontent.com/8238804/46932109-e1b35480-d099-11e8-9baa-a8fcf67496f7.png)

If the argument to color is a `list`, they show similar plots.

**Comment by fidelram** [comment]
I the argument has to be a list not a numpy array. I don't know why the
colorbars are repeated when a numpy array is passed. I will add a PR to fix
this.

**Comment by fidelram** [comment]
@ivirshup Did the last PR solved your issue?

**Comment by ivirshup** [comment]
Thanks! Looks like this and #298 are solved.

But now I'm getting some strange layout behavior. I'll dig into that a bit and open a new issue.
