### ISSUE TITLE
eliminate jet

### ISSUE THREAD

**Issue by flying-sheep** [scverse/scanpy#3]
everyone agrees it’s objectively bad 😉

therefore the characters “jet” should only appear in the commit message “jettisoned bad colormap defaults”

* https://jakevdp.github.io/blog/2014/10/16/how-bad-is-your-colormap/
* http://cresspahl.blogspot.de/2012/03/expanded-control-of-octaves-colormap.html
* http://stats.stackexchange.com/questions/223315/why-use-colormap-viridis-over-jet
* https://eagereyes.org/basics/rainbow-color-map
* https://courses.washington.edu/engageuw/why-you-should-dump-the-rainbow/
* http://researchweb.watson.ibm.com/people/l/lloydt/color/color.HTM

i’ll do it if you want, and i’ll make sure contrast and distinction is preserved in all figures

**Comment by falexwolf** [comment]
that would be nice! :) but give it another day.

for the categorical case, as is very important, for example, here 
https://github.com/falexwolf/collab_alex/blob/master/scanpy/examples/nestorowa16.md
i'm not sure whether one can actually do better than jet. but ok, you will know better. :)

**Comment by flying-sheep** [comment]
haha with ease. you can observe the inhomogeneous contrast distribution with C2 and C10 there: the colors are indistinguishable dark blue while C7 and C8 go from snot green all the way to orange.

that would be horrible for continuous data, but merely makes C2 and C10 indistinguishable for categorical colors and unnecessarily reduces contrast there (as it’s a color map and no palette).

**Comment by flying-sheep** [comment]
check out e.g. color brewer’s “paired”, which has 12 easily distinguishable colors (although that yellow is a bit light for a white background):

![color brewer qual](http://moderndata.plot.ly/wp-content/uploads/2015/04/qual-500x127.jpg)

**Comment by falexwolf** [comment]
looks good, let's take one these. but before integrating it, the scatter plot of dpt should invoke `plotting.plot_tool` as well. then it's going to be just a one line change.

**Comment by falexwolf** [comment]
so, https://github.com/theislab/scanpy/commit/d5d2a099a5b2d6f34144f331c5074df386048100 uses now a smart choice of color maps and plotting layout, though i still didn't get good results for the example above with the categorical palettes

**Comment by falexwolf** [comment]
now also dpt calls plotting.plot_tool, so if you want to improve the choice of color maps, go ahead! you'll only have to do it in there. :)

**Comment by flying-sheep** [comment]
OK 😋
