### ISSUE TITLE
Normalization in scanpy.preprocessing

### ISSUE THREAD

**Issue by Koncopd** [scverse/scanpy#301]
Need a file `normalization.py` in `scanpy.preprocessing`. In that, there should be cleaned-up versions of `normalize_per_cell` and `normalize_per_cell_weinreib17` without any recursive calls and no calls to `filter_cells`. The new names of these function should be `normalize_total` and `normalize_quantile`. There should be a backup version of `normalize_per_cell` that behaves exactly as it currently does for backwards compatibility, which wraps `filter_cells` and `normalize_per_cell`. In the ideal case, `normalize_total` would wrap `normalize_quantile(quantile=1)`.

**Comment by falexwolf** [comment]
Responding to your email, here: yes, `max_fraction` should correspond to `quantile`. And yes, the code is correct, only the genes contributing less than the chosen quantile should be the basis for the normalization, so that very highly expressed genes (potential outliers) do not confound the normalization constant estimate.

**Comment by Koncopd** [comment]
Ok, got it, thanks.

**Comment by Koncopd** [comment]
@falexwolf 
Another question - now [normalize_per_cell_weinreb16_deprecated](https://github.com/theislab/scanpy/blob/b4c2479eed302707a4d098f8f3c85037c82f07ca/scanpy/preprocessing/simple.py#L579) doesn't filter anything, just divides by sums of chosen genes, this normalization looks strange
```
X = np.array([[1, 0, 1], [3, 0, 1], [5, 6, 1]])
normalize_per_cell_weinreb16_deprecated(X, max_fraction=0.7)
array([[1.        , 0.        , 1.        ],
       [3.        , 0.        , 1.        ],
       [0.71428571, 0.85714286, 0.14285714]])
```
Should it be this way?

**Comment by Koncopd** [comment]
for now i have this [norml branch](https://github.com/theislab/scanpy/tree/norml)
But i'm not sure if filtering of genes is needed and how to use `materialize_as_ndarray `properly here.

**Comment by falexwolf** [comment]
Why does normalize_per_weinreb look strange? We can skype, I think it makes sense. There should be no filtering whatsoever in the new functions, I'd say.

**Comment by falexwolf** [comment]
Why don't you make a PR and then we can use the commenting and reviewing tools of GitHub? I'm currently going through your code and would have a few comments.

**Comment by falexwolf** [comment]
But in large parts, it looks very good! :smile:

**Comment by Koncopd** [comment]
Ok, got it, no filtering. I'll remove filtering and make a PR.
