### ISSUE TITLE
Update Preprocessing functions with numba

### ISSUE THREAD

**Issue by Intron7** [scverse/scanpy#3011]
### What kind of feature would you like to request?

Additional function parameters / changed functionality / changed defaults?

### Please describe your wishes

It would be useful to switch from array operations to `numba` kernels in for most of the preprocessing. I would start writing those.

**Comment by ivirshup** [comment]
Which specific functions were you thinking about?

**Comment by Intron7** [comment]
at least `_get_mean_var`, some stuff in `hvg_seurat_v3`, `scale` and `normalize_total`. I'll do one PR for each function.
