### ISSUE TITLE
sc.tl.leiden with `flavor='igraph'` raises an (ignored by igraph) “ValueError: high is out of bounds for int32”

### ISSUE THREAD

**Issue by hl324** [scverse/scanpy#3028]
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the main branch of scanpy.

### What happened?

When I run the code, it doesn't stop running, just repeatedly returns the error code below into the box (I have to shut down the kernel to get the code to stop running and repeating the error). I've tried changing random_state=0 several times. `numpy.random.randint(0, high=2**32-2, dtype=numpy.int32)` and `numpy.random.randint(0, high=5, dtype=numpy.int32)` gave me the same error as below, except the second file referenced line 2881 instead of line 1423. Also, `numpy.random.randint(0, high=2**32-2, dtype=numpy.int32)` returns the error more normally (i.e. the code stops running and returns the normal error box, though the error is the same). `random_state=numpy.random.randint(0, high=2**32-2, dtype=numpy.int64)` and `numpy.random.randint(0, high=5, dtype=numpy.int64)` also gave me the same error as below. `print(numpy.int_)` returns `<class 'numpy.int32'>`. I've tried numpy versions 1.26.3 and 1.24.4 as well. I've also tried uninstalling and reinstalling scanpy, jupyter notebook, and (consequently) other packages used in the tutorials (igraph, leidenalg, etc.). `numpy.random.test(label='full', verbose=2)` returned True, but noted 1322 passed, 6 skipped in 30.78s.

### Minimal code sample

```python
sc.tl.leiden(
    adata, 
    resolution=0.9,
    random_state=0,
    flavor="igraph",
    n_iterations=2,
    directed=False,
)
```

### Error output

```pytb
Exception ignored in: <class 'ValueError'>
Traceback (most recent call last):
  File "numpy\\random\\mtrand.pyx", line 780, in numpy.random.mtrand.RandomState.randint
  File "numpy\\random\\_bounded_integers.pyx", line 1423, in numpy.random._bounded_integers._rand_int32
ValueError: high is out of bounds for int32
```

### Versions

<details>

```
anndata     0.10.7
scanpy      1.10.1
-----
PIL                         10.3.0
anyio                       NA
arrow                       1.3.0
asttokens                   NA
attr                        23.2.0
attrs                       23.2.0
babel                       2.14.0
bottleneck                  1.3.7
brotli                      1.0.9
certifi                     2024.02.02
cffi                        1.16.0
charset_normalizer          2.0.4
colorama                    0.4.6
comm                        0.2.2
cycler                      0.12.1
cython_runtime              NA
dateutil                    2.9.0
debugpy                     1.8.1
decorator                   5.1.1
defusedxml                  0.7.1
executing                   2.0.1
fastjsonschema              NA
fqdn                        NA
h5py                        3.11.0
idna                        3.4
ipykernel                   6.29.3
isoduration                 NA
jedi                        0.19.1
jinja2                      3.1.3
joblib                      1.4.0
json5                       0.9.25
jsonpointer                 2.1
jsonschema                  4.21.1
jsonschema_specifications   NA
jupyter_events              0.10.0
jupyter_server              2.14.0
jupyterlab_server           2.26.0
kiwisolver                  1.4.5
legacy_api_wrap             NA
llvmlite                    0.42.0
markupsafe                  2.1.5
matplotlib                  3.8.4
mpl_toolkits                NA
natsort                     8.4.0
nbformat                    5.10.4
numba                       0.59.1
numexpr                     2.8.7
numpy                       1.26.4
overrides                   NA
packaging                   23.1
pandas                      2.2.1
parso                       0.8.4
pickleshare                 0.7.5
platformdirs                3.10.0
prometheus_client           NA
prompt_toolkit              3.0.42
psutil                      5.9.8
pure_eval                   0.2.2
pydev_ipython               NA
pydevconsole                NA
pydevd                      2.9.5
pydevd_file_utils           NA
pydevd_plugins              NA
pydevd_tracing              NA
pygments                    2.17.2
pyparsing                   3.1.2
pythoncom                   NA
pythonjsonlogger            NA
pytz                        2024.1
pywin32_system32            NA
pywintypes                  NA
referencing                 NA
requests                    2.31.0
rfc3339_validator           0.1.4
rfc3986_validator           0.1.1
rpds                        NA
ruamel                      NA
scipy                       1.13.0
send2trash                  NA
session_info                1.0.0
six                         1.16.0
sklearn                     1.4.2
sniffio                     1.3.1
socks                       1.7.1
stack_data                  0.6.2
threadpoolctl               3.4.0
tornado                     6.4
traitlets                   5.14.3
uri_template                NA
urllib3                     1.26.18
wcwidth                     0.2.13
webcolors                   1.13
websocket                   1.7.0
win32api                    NA
win32com                    NA
win32con                    NA
win32trace                  NA
winerror                    NA
yaml                        6.0.1
zmq                         26.0.2
-----
IPython             8.22.2
jupyter_client      8.6.1
jupyter_core        5.7.2
jupyterlab          4.1.6
notebook            7.1.3
-----
Python 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]
Windows-10-10.0.22631-SP0
-----
Session information updated at 2024-04-24 08:28
```

</details>

**Comment by glycoaddict** [comment]
I'm getting this too. This could be a problem with numpy's random: 
https://github.com/DLR-RM/stable-baselines3/issues/1579 
https://github.com/SimonBlanke/Gradient-Free-Optimizers/issues/11

I'm seeing if I can specify explicitly the random state or seed.

Found where the problem happens:

_leiden.py
Line 185    
`part = g.community_leiden(**clustering_args)`

calls the following

community.py
Line 442
```
    membership, quality = GraphBase.community_leiden(
        graph,
        edge_weights=weights,
        node_weights=node_weights,
        resolution=resolution,
        normalize_resolution=(objective_function == "modularity"),
        beta=beta,
        initial_membership=initial_membership,
        n_iterations=n_iterations,
    )
```

The debugger doesn't step into the `Graphbase.community_leiden` function any further, but this is where the loop with the error occurs.

https://igraph.org/python/doc/api/igraph.Graph.html#community_leiden

**Update:**
Funnily enough, the Leiden clustering still executes correctly (took about 1 hour for me). How I did it was to create a simple .py file that loads the h5ad, just runs the leiden clustering, then writes a new h5ad, then ends. Ran that from a powershell window and just let it throw the warnings (which do not break the code execution). What I found is that I cannot run the leiden clustering in a notebook because the output gets overwhelmed and hangs VSCode.

**Comment by flying-sheep** [comment]
Hm, that’s probably the doing of [`sklearn.utils.check_random_state`][]:

https://github.com/scverse/scanpy/blob/c3cfa74b1316d780568411175316cd9f139efb22/scanpy/_utils/__init__.py#L71-L72

@ilan-gold seems like using the legacy RandomState class wasn’t ideal. The new [`Generator`](https://numpy.org/doc/stable/reference/random/generator.html) actually emits 64 bit ints by default and I bet has other advantages.

[`sklearn.utils.check_random_state`]: https://scikit-learn.org/stable/modules/generated/sklearn.utils.check_random_state.html

**Comment by flying-sheep** [comment]
@hl324 @glycoaddict can you try the fix here? https://github.com/scverse/scanpy/pull/3041

```
pip install 'scanpy @ git+https://github.com/scverse/scanpy@modern-rng'
```

**Comment by hl324** [comment]
@flying-sheep I tried running `pip install 'scanpy @ git+https://github.com/scverse/scanpy@modern-rng' ` in anaconda prompt and got ERROR: Invalid requirement: "'scanpy".

**Comment by flying-sheep** [comment]
Seems like some shell shenanigans. For some reason you passed `'scanpy` as a first parameter instead of the whole thing as a string.

In any case, I either need someone to confirm that the fix works, or better, a reproducible example that we can derive a test case from.

**Comment by flying-sheep** [comment]
A I missed #2969

duplicate of #2969, please subscribe to that one

**Comment by Lucyyang1991** [comment]
I have this problem too!
