### ISSUE TITLE
When importing Scanpy 1.9.1, if you're using matplotlib version below 3.7, you might encounter a metaclass error.

### ISSUE THREAD

**Issue by 12hsk** [scverse/scanpy#3029]
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [X] (optional) I have confirmed this bug exists on the main branch of scanpy.

### What happened?

导入scanpy1.9.1时，matplotlib在3.7版本以下然后发生元类错误

### Minimal code sample

```python
import scanpy as sc
```

### Error output

```pytb
Traceback (most recent call last):
  File "G:/stmgcn-main/stmgcn-main/STMGCN/DLPFC.py", line 15, in <module>
    from util import *
  File "G:\stmgcn-main\stmgcn-main\STMGCN\util.py", line 1, in <module>
    import scanpy as sc
  File "E:\Anaconda3\envs\stmgcn\lib\site-packages\scanpy\__init__.py", line 16, in <module>
    from . import plotting as pl
  File "E:\Anaconda3\envs\stmgcn\lib\site-packages\scanpy\plotting\__init__.py", line 1, in <module>
    from ._anndata import (
  File "E:\Anaconda3\envs\stmgcn\lib\site-packages\scanpy\plotting\_anndata.py", line 28, in <module>
    from . import _utils
  File "E:\Anaconda3\envs\stmgcn\lib\site-packages\scanpy\plotting\_utils.py", line 35, in <module>
    class _AxesSubplot(Axes, axes.SubplotBase, ABC):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

进程已结束,退出代码1
```

### Versions

You can't get to on account of the crash.scanpy.logging.print_versions()

**Comment by flying-sheep** [comment]
@ivirshup time to set minimum versions for scanpy? I can help this time, you don’t have to go through this alone again

**Comment by 12hsk** [comment]
> 是时候为 ScanPy 设置最低版本了吗？这次我可以帮忙，你不必再独自经历这件事了

How to solve this problem?

**Comment by flying-sheep** [comment]
- Either upgrade Scanpy to 1.10 (this PR has the fix for your problem): https://github.com/scverse/scanpy/pull/2414
- or upgrade Matplotlib to 3.8

**Comment by 12hsk** [comment]
> * Either upgrade Scanpy to 1.10 (this PR has the fix for your problem): [matplotlib 3.7 compat #2414](https://github.com/scverse/scanpy/pull/2414)
> * or upgrade Matplotlib to 3.8

My Anaconda prompts that I can't install Scanpy above 1.10 or Matplotlib above 3.8.

**Comment by flying-sheep** [comment]
Both are available on conda forge. I might be able to help if you show me

1. the command and environment file you used
2. the output (in English: you can use e.g. `env LANG=C conda ...` for that)

Please format everything as a code block and don’t just paste it into the comment box, [see here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)

**Comment by frederikziebell** [comment]
Dear scverse authors (@flying-sheep, @LucaMarconato et al.), because of issues like these, maybe think about a sophisticated staging environment a la Bioconductor to ensure that packages are compatible with each other. If you do a `conda install scanpy` that finishes without any error, it cannot be that `import scanpy` fails with an error resulting from an incompatible matplotlib version.

**Comment by flying-sheep** [comment]
What you describe doesn‘t need to happen, and you can fix this!

1. go to https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/
2. make a PR that patches conda’s dependency data to include this constraint
3. the problem is gone

**Comment by frederikziebell** [comment]
For me, it was a different combination of versions, I guess Scanpy 1.9.8 and matplotlib 3.8 that caused the error. It's not about fixing specific instances but the problem of version mismatches of complex interacting software packages in general. And this has to run in an automated fashion.

**Comment by LucaMarconato** [comment]
@frederikziebell thanks for the feedback, we will discuss this in the next core meeting. An automated cross-package CI could be a solution.
