### ISSUE TITLE
umap dot size

### ISSUE THREAD

**Issue by justinesjw** [scverse/scanpy#307]
Hi, 

I am trying to separate my umap according to some observation.
I'm sure I've have missed it but is there a parameter in sc.pl.umap() to control the dot size?

Thank you,
Justine :)

**Comment by fidelram** [comment]
use the `size` parameter. Eg. `size=10`

**Comment by falexwolf** [comment]
Should be in the docstring, now: https://github.com/theislab/scanpy/commit/21f100e80b5d7763fe30c001b2f62ffe8b6cb58a
