### ISSUE TITLE
Only show the genes that have significant statistics

### ISSUE THREAD

**Issue by ngvananh2508** [scverse/scanpy#3077]
### What kind of feature would you like to request?

New plotting function: A kind of plot you would like to seein `sc.pl`?

### Please describe your wishes

I wonder that whether pl method filter the genes that have p_adjusted values < 0.05 before plotting figures? If not, could you please add one more method to do this?
Thank you very much.

**Comment by flying-sheep** [comment]
You can just filter the `AnnData` object itself, right?

`sc.pl.*(adata[:, adata.var['p_adjusted'] < 0.05], ...)`

Please comment if I’m missing something and we can reopen this.

**Comment by ngvananh2508** [comment]
But the figures come from an uns layer of adata. Specifically, I want to plot the result coming from the rank_genes_group method of scanpy. So do I need to add a var column to do like you did above?
