### ISSUE TITLE
I have always had a question: do I need to scale my adata before running sc.tl.score_genes?

### ISSUE THREAD

**Issue by christophechu** [scverse/scanpy#3080]
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [X] (optional) I have confirmed this bug exists on the main branch of scanpy.

### What happened?

I have always had a question: do I need to scale my adata before running sc.tl.score_genes?

### Minimal code sample

```python
sc.tl.score_genes_cell_cycle(adata_hvg, layers='scaled', s_genes=s_genes, g2m_genes=g2m_genes)
```

### Versions

<details>

```

```

</details>

**Comment by flying-sheep** [comment]
Hi, this issue tracker is better suited for bugs or enhancement request. Please ask e.g. here: https://discourse.scverse.org/
