### ISSUE TITLE
OSError between tissue_positions_list.csv and tissue_positions.csv

### ISSUE THREAD

**Issue by alexanderchang1** [scverse/scanpy#3085]
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the main branch of scanpy.

### What happened?

I'm getting an OSerror when reading in visium data because my folder only has tissue_positions.csv

OSError: Could not find '/bgfs/alee/shared/alee_rfe4_wam30/Lee_Visium_GEX-PEX_2_2024_Neil/SpaceRanger_OUT/MWS-7945/outs/spatial/tissue_positions_list.csv'

This is caused by a change in SpaceRanger output - as seen here:

tissue_positions.csv: This text file contains a table with rows that correspond to spots. From Space Ranger v2.0 onwards this file, which was previously named tissue_positions_list.csv, is renamed and includes a header column. 

I think the code would be best fixed by an or check for either file name. 

### Minimal code sample

```python
adata = sc.read_visium(path, count_file='filtered_feature_bc_matrix.h5', load_images=True, )
```

### Error output

```pytb
OSError                                   Traceback (most recent call last)
Cell In[2], line 6
      4 #path = '/bgfs/alee/LO_LAB/General/Lab_Data/20240510_Neil_SpatialSequencing_AgePatients/Lee_Visium_GEX-PEX_2_2024_Neil/SpaceRanger_OUT/MWS19-10502/outs'
      5 path = '/bgfs/alee/shared/alee_rfe4_wam30/Lee_Visium_GEX-PEX_2_2024_Neil/SpaceRanger_OUT/MWS-7945/outs'
----> 6 adata = sc.read_visium(path, count_file='filtered_feature_bc_matrix.h5', load_images=True)

File /bgfs/alee/LO_LAB/Personal/Alexander_Chang/alc376/envs/SpatialSequencing/lib/python3.8/site-packages/scanpy/readwrite.py:392, in read_visium(path, genome, count_file, library_id, load_images, source_image_path)
    387             logg.warning(
    388                 f"You seem to be missing an image file.\n"
    389                 f"Could not find '{f}'."
    390             )
    391         else:
--> 392             raise OSError(f"Could not find '{f}'")
    394 adata.uns["spatial"][library_id]["images"] = dict()
    395 for res in ["hires", "lowres"]:

OSError: Could not find '/bgfs/alee/shared/alee_rfe4_wam30/Lee_Visium_GEX-PEX_2_2024_Neil/SpaceRanger_OUT/MWS-7945/outs/spatial/tissue_positions_list.csv'
```

### Versions

<details>

```
1.10.1
```

</details>

**Comment by flying-sheep** [comment]
SpaceRanger 2 support has been added in 1.10.0 via #2424

If you see what you see, `path / "spatial/tissue_positions.csv"` doesn’t exist, otherwise it would have been found.
