### ISSUE TITLE
Plotting layout behavior at repl

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#309]
As mentioned in #299, I'm getting some strange layout behavior when plotting at the repl.

Using the setup:

```python
import scanpy.api as sc
import numpy as np

N = 1000
M = 2000

adata = sc.AnnData(X=np.random.random_sample((N, M)))

sc.pp.pca(adata)
```

I get outputs that look like the following 

```python
sc.pl.pca(adata, color=list("123"))
```

<img width="1552" alt="screen shot 2018-10-18 at 4 46 46 pm" src="https://user-images.githubusercontent.com/8238804/47133668-72d23780-d2f5-11e8-9630-f6e676a146ca.png">

```python
sc.pl.pca(adata, color=list("1234"))
```

<img width="1552" alt="screen shot 2018-10-18 at 4 47 37 pm" src="https://user-images.githubusercontent.com/8238804/47133696-909f9c80-d2f5-11e8-8482-eab30e84fe46.png">

```python
sc.pl.pca(adata, color=list("12"), ncols=1)
```

<img width="839" alt="screen shot 2018-10-18 at 4 50 11 pm" src="https://user-images.githubusercontent.com/8238804/47133806-17547980-d2f6-11e8-97ad-6d9528ea280b.png">

I get similar results with the MacOSX and GR backends (haven't checked others).

I think the issue is due to the implicit `bbox_inches="tight"` occurring with the matplotlib inline backend, and its explicit usage for `scanpy.plotting.utils.savefig`.  In the cases here, the bounding box is not being trimmed.

**Comment by fidelram** [comment]
thanks for the report! if you type plt.tight_layout() do you get better
images?

**Comment by ivirshup** [comment]
I get this warning:

```python
/usr/local/lib/python3.6/site-packages/matplotlib/figure.py:2362: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  warnings.warn("This figure includes Axes that are not compatible "
```

and the same layout.

**Comment by fidelram** [comment]
Does this problem also happens with the previous code? this is just to guide me on a solution.

**Comment by ivirshup** [comment]
On a6165678, there are still larger margins on the right, but much less extreme:

![figure_1](https://user-images.githubusercontent.com/8238804/47275093-1d996d00-d5f8-11e8-9373-fd8e3a16ea18.png)

**Comment by fidelram** [comment]
Found the problem. PR coming.

**Comment by ivirshup** [comment]
Great, thanks!

Kind of unrelated, but I just noticed I can do:

```python
sc.pl.pca(adata, components=["1,2", "2,3"], color=["sample_type", "total_features_by_counts"], ncols=2)
```

Which is awesome, thanks for that!

**Comment by fidelram** [comment]
Yes, that is possible. I think I added this probably after one of your
issues.
