### ISSUE TITLE
scanpy legacy and not legacy about scale

### ISSUE THREAD

**Issue by asmlgkj** [scverse/scanpy#3095]
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the main branch of scanpy.

### What happened?

Thanks a lot
when I read docs in 
https://scanpy.readthedocs.io/en/stable/tutorials/basics/clustering-2017.html (legacy, used pp.scale)
https://scanpy.readthedocs.io/en/stable/tutorials/basics/clustering.html#nearest-neighbor-graph-constuction-and-visualization ( not used pp.scale)

so does it mean in scanpy, not matther single-cell rna-seq or spatial data, both not need the pp.scale

### Minimal code sample

```python
no code
```

### Versions

<details>

```
[
<img width="968" alt="Snipaste_2024-06-04_22-02-31" src="https://github.com/scverse/scanpy/assets/50854682/6c232732-bbc9-47b2-8f44-5ccbe63cd891">
](url)
```

</details>

**Comment by flying-sheep** [comment]
Please ask questions on https://discourse.scverse.org/

See the Note in the 2017 tutorial:

> [!NOTE]
> 
> If you don’t proceed below with correcting the data with `sc.pp.regress_out` and scaling it via `sc.pp.scale`, you can also get away without using `.raw` at all.
> 
> The result of the previous highly-variable-genes detection is stored as an annotation in `.var.highly_variable` and auto-detected by PCA and hence, `sc.pp.neighbors` and subsequent manifold/graph tools. In that case, the step actually do the filtering below is unnecessary, too.

Since data sizes these days are big enough that a sparse .X is all but necessary (`pp.scale` densifies data), and methods exist that work with unscaled expression values and therefore don‘t need scaling, people tend to not do it these days.

**Comment by asmlgkj** [comment]
but we still need to deal with many old singcell data, which may bot contain that many cells or not tat big enough, so can I scale all the time, no matter it is big or small
