### ISSUE TITLE
scanpy.pl.spatial plotting square pixels

### ISSUE THREAD

**Issue by HaikuoLi** [scverse/scanpy#3096]
### What kind of feature would you like to request?

Additional function parameters / changed functionality / changed defaults?

### Please describe your wishes

Hello!

I wonder if there is a way to plot pixels as squares (now they are rounds) with scanpy.pl.spatial. Thanks!

Best,
Haikuo

**Comment by flying-sheep** [comment]
Yes, but not if you use `scale_factor`, see here:

https://github.com/scverse/scanpy/blob/706d4ef65e5d65e04b788831e7fd65dbe6b2a61f/scanpy/plotting/_tools/scatterplots.py#L356-L361

If you don’t use it, `marker` should be respected!
