### ISSUE TITLE
dpt_timeseries with adata.n_var > 50

### ISSUE THREAD

**Issue by zacharylau10** [scverse/scanpy#31]
Hi,
    when I use dpt_timeseries function with adata.n_var > 50, there is no output or any hint and just empty. 
    I saw the source code and there is a comment `# only if number of genes is not too high`
    Does it mean this function could not deal with n_var > 50? 
    I think there would be a hint when n_var > 50, if not it will confuse others. Thank you~

**Comment by falexwolf** [comment]
Hi Zachary,
thank you for your remark. Yes, I agree, there should be a hint that tells the user to provide a set of selected genes; I've done this many times already but it didn't end up in the function definition. I'll add a hint and a possibility to select a subset of genes very soon.
Cheers,
  Alex

**Comment by falexwolf** [comment]
In the new version (0.2.7), this is resolved.
