### ISSUE TITLE
`pl.scatter`: 

### ISSUE THREAD

**Issue by bebatut** [scverse/scanpy#311]
Hi,

I am testing `pl.scatter` and it seems that:
- `color` cannot be a list (contrary to what the documentation mentions)
- `components='all'` raises the error: `ValueError: invalid literal for int() with base 10: 'all'`

Any idea how to fix that?

Bérénice

**Comment by fidelram** [comment]
Dear Bérénice, thanks for reporting these issues. Recently, I replaced most of the functions related to scatter so I think that what you report refers to the previous code. Can you maybe post the command that you used.

**Comment by bebatut** [comment]
Hi @fidelram, good to see you :smile:

I was working on the Galaxy integration. I tested that with the `1.3.2` version from Bioconda. I tested with adata from krumsiek11

- For colors, I tried with `sc.pl.scatter(adata=adata, x='EKLF', y='Cebpa', color=['EgrNab', 'cJun']) and I got the error:

   ```
   ...
   and (color is None or color in adata.obs.keys() or color in adata.var.index)):
   File "path/to/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2035, in __contains__
    hash(key)
   TypeError: unhashable type: 'list'
   ```

- For components: the command was 

   ```
   sc.pl.scatter(
    adata=adata,
    x='EKLF',
    y='Cebpa',
    color='EgrNab',
    layers=('X', 'X', 'X'),
    use_raw=False,
    sort_order=True,
    components='all',
    projection='2d',
    legend_loc='right margin',
    legend_fontsize=1,
    legend_fontweight='normal',
    palette='viridis',
    frameon=True,
    right_margin=1.0,
    size=1.0,
    show=False,
    save='.png')
   ```
   and the error:

   ```
   components = np.array(components).astype(int) - 1
   ValueError: invalid literal for int() with base 10: 'all'
   ```

Did I put the parameters in a wrong way?

**Comment by falexwolf** [comment]
Yes, `1.3.2` might contain still a few bugs on the scatter side (I should have made this a prerelease); I wanted to release `1.3.3` quickly so that the fixes are there but I think there still remain small issues. There will be more bug-free release soon.

You can just go back to `1.3.1`, which is working fine.

**Comment by fidelram** [comment]
@falexwolf Do you think that these errors come from the code that I modified? I think I didn't touch the function that @bebatut is using.

**Comment by falexwolf** [comment]
Ah right, we now have to separate scatter functions, which isn't a good situation. @bebatut `components` does only make sense if you provide `basis` as an argument. a list-like `color` was also only meant for that case. both is now deprecated as @fidelram wrote a whole new scatter backend; however, which for now, misses the `x` and `y` parameters...

In any case, `pl.scatter` should continue to work with the canonical calls and also with non-list-like color.

**Comment by fidelram** [comment]
I think that the best is to have separate scatter functions. For the
remaining use cases of scatter a much simpler version can be devised. But
meanwhile,  @bebatut <https://github.com/bebatut> why did you try that
combination of parameters? Is this in some tutorial?

**Comment by falexwolf** [comment]
Yes, you are right! We should reduce the complexity of the current `sc.pl.scatter` now that it's no longer used for the embeddings...

**Comment by fbrundu** [comment]
Hi all,
any update on this? I'm on version 1.4 and even if in the documentation the color parameter is defined as string or list of strings, I'm still unable to pass to the scatter method a list of strings as value.
Thanks

**Comment by fidelram** [comment]
@fbrundu can you help me by posting an example hopefully using the datasets included in scanpy?

**Comment by fbrundu** [comment]
Hi @fidelram,
One way in which I'd like to do it is like the following:

```python
sc.pl.scatter(adata, x='<gene1>', y='<gene2>', color=['Mki67', 'Pclaf'],
              save=False, use_raw=False)
```

to show the relationship between two genes (i.e. gene1 and gene2), and one third gene (in this case Mki67 in one subplot, Pclaf in the second).
One of the subplots could be like the following:

![test](https://user-images.githubusercontent.com/697622/52814026-1e538480-3069-11e9-9af5-ef7a4761ff25.png)


Hope this is clear.

Thanks

**Comment by flying-sheep** [comment]
I’m pretty sure this is fixed by now, please reopen if I’m wrong.
