### ISSUE TITLE
Investigate SquidPy tools used in scRNAseq-only analyses

### ISSUE THREAD

**Issue by flying-sheep** [scverse/scanpy#3137]
### What kind of feature would you like to request?

New analysis tool: A simple analysis tool you have been using and are missing in `sc.tools`?

### Please describe your wishes

LigRec and so on

cc @Intron7

**Comment by Rafael-Silva-Oliveira** [comment]
Methods to calculate spatial connectivities would also be nice to have (slowly expanding scanpy for spatial analysis as well); A LigRec method that is possible to be used on HD data (such as Visium HD) without memory issues;

**Comment by ilan-gold** [comment]
Most interesting things would be (from Severin's conversations) would be autocorrelation (via NN graph).

Current workflow is to just use squidpy by it would be simple to add/port from squidpy.

**Comment by flying-sheep** [comment]
Severin & Tim say there’s nothing but gearys_c and morans_i, see scverse/fast-array-utils#82
