### ISSUE TITLE
expression table

### ISSUE THREAD

**Issue by terooatt** [scverse/scanpy#314]
Hi,

Is it possible to generate a gene expression table with scanpy and save as a csv file?
I can make it with cellranger and seurat but not with scanpy.

              cell1 .  cell2 .  cell3 .  etc..
gene1    
gene2 
gene3

The cmd adata.write.csvs(..) doesnt give such table. I also understand this can be huge data if many cells were used.

Thank you very much for your help.

**Comment by falexwolf** [comment]
Using `adata.T.write_csvs(skip_data=False)` gives you this. If you only want the data matrix, you can also do `adata.to_df().to_csv()` using pandas. The last call will soon be available in a release.

**Comment by maximilianh** [comment]
Hi @terooatt how are you writing the matrix in Seurat? I can't find a function... https://www.rdocumentation.org/packages/Seurat/versions/2.3.4

@falexwolf thanks! had no idea. adata.to_df() sounds relatively slow and an unnecessary conversion to pandas.
