### ISSUE TITLE
Change the size of gene symbol labels on x axis

### ISSUE THREAD

**Issue by ngvananh2508** [scverse/scanpy#3149]
### What kind of feature would you like to request?

Additional function parameters / changed functionality / changed defaults?

### Please describe your wishes

Hi, I want to change the size of gene symbol label (CCNT2P1, ...) of the rank_genes_groups_matrixplot method. I try to use plt.rcParams but it did not work. I wonder that whether another way to do this task.

![image](https://github.com/scverse/scanpy/assets/130348585/aa3d69c9-5cd7-46ed-bd3b-edcce51af667)
Thank you so much

**Comment by flying-sheep** [comment]
You can use `mp = rank_genes_groups_matrixplot(..., show=False, return_fig=True)` and then use `mp.get_axes()` to get a dict of axes you can manipulate, e.g. by accessing the xtickmarks!
