### ISSUE TITLE
pl.pca_loadings fails if `subset=False` when computing highly variables genes.

### ISSUE THREAD

**Issue by fidelram** [scverse/scanpy#315]
After the highly variable genes information was added to .var  `pl.pca_loadings`  no longer works.

This is an example that reproduces the problem:
```PYTHON
import scanpy.api as sc
import numpy as np
import pandas as pd

N = 1000
M = 2000

adata = sc.AnnData(
    X=np.random.random_sample((N, M))
)

sc.pp.filter_genes_dispersion(adata, subset=False)
sc.tl.pca(adata)
sc.pl.pca_loadings(adata)
```

If  ` subset=True` then the pca_loadings works as expected.

**Comment by falexwolf** [comment]
@VolkerBergen could you please look into this?

**Comment by VolkerBergen** [comment]
Thanks for pointing that out! Fixed now.

**Comment by falexwolf** [comment]
Thank you, Volker!
