### ISSUE TITLE
All plotting tests failing, mostly trivially

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#317]
All of the plotting tests are failing for me. Largely this seems based on font rendering.

![highest_expr_genes-failed-diff](https://user-images.githubusercontent.com/8238804/47278908-46c9f580-d618-11e8-99c0-ac5512994ea3.png)

Though there might be something more with the violin plots.

![master_violin_multi_panel-failed-diff](https://user-images.githubusercontent.com/8238804/47278943-990b1680-d618-11e8-8e04-8e987c40b90e.png)

Is there some setup required to get these tests to pass? My `matplotlibrc` is empty, so I don't think that's the issue.

**Comment by fidelram** [comment]
The only solution so far is to increase the tolerance threshold of the tests! I don't know where those differences come from. Is always a problem. I will be very glad if you find a better solution.

**Comment by ivirshup** [comment]
I don't remember getting these errors before. Are you not getting them now, and did you get them before?

Also, where did the images in the repo get generated?

**Comment by fidelram** [comment]
I think that differences in underlying libraries and in matplotlib versions cause this small changes.

**Comment by falexwolf** [comment]
Hm, the tests work for me. And I never set up a specific environment. Obviously, they also run through on Travis.

**Comment by ivirshup** [comment]
Could you send me some info about your environment so I can try to diagnose this? I'm thinking matplotlib version, matplotlibrc, and os info.

[Here's my current pipfile](https://gist.github.com/ivirshup/6de8273535e3f5ec9734e5a3efc5df6a).

**Comment by ivirshup** [comment]
I've been able to get the tests to pass on a different machine (this one running linux). I can get rid of most of the discrepancies between plots between the two machines by replacing:

```python
mpl.use("agg")
```

with

```python
from matplotlib.testing import setup
setup()
```

However violin plots still get a large RMS value.

**Comment by falexwolf** [comment]
For me, exactly the opposite happens; adding
```
from matplotlib.testing import setup
setup()
```
makes almost all tests fail.

If I use it from the beginning and produce all test images with it, then, of course, it works.

**Comment by falexwolf** [comment]
Hm, I've wanted to add a PAGA notebook to the tests and I'm struggling to get it to run on travis. The tests run through for me on a MacBook and on a remote linux machine, but travis seems even to be able to produce differently-shaped output images: https://travis-ci.org/theislab/scanpy/jobs/450416143

My current suspicion is that networkx does something strange as it really only affects the graph plot... I'll investigate further, but if you've seen this already, a hint would be very welcome! 🙂

**Comment by ivirshup** [comment]
Ah, yeah that's what I meant. If I use `setup()`, the tests on the linux server fail. However, the images generated are similar (RMSD < 10) to images made on my MacBook after running `setup()`.

On the PAGA notebook, I saw errors like that when I was playing around with the dpi. Maybe fig size or dpi is being changed?

**Comment by falexwolf** [comment]
OK! Thanks! @fidelram Should we simply regenerate all images using `matplotlib.testing.setup()`, which seems to be the most stable way to go and in the future restrict ourselves to that? I guess this is closer to a reliable test setup for all the images than the current solution via `mpl.use("agg")`. Also the name suggests that matplotlib does it this way. But you did some research at the time when introducing the first tests, right?

Thanks for the comment on the PAGA notebook, too, @ivirshup. I'll make sure that I didn't hard-code anything into the plotting functions that might collide with anything else happening on travis... but it's astonishing... In the meanwhile I work-around with a data-base test.

**Comment by falexwolf** [comment]
PS: @ivirshup, I'm adding you to the author list. ;)

**Comment by ivirshup** [comment]
Awesome, thanks!

**Comment by fidelram** [comment]
I didn't know about `testing.setup()` I will take a look. Seems very promising.

**Comment by ivirshup** [comment]
No longer getting errors on plotting tests. Was this being actively worked on? I think it's ready to close otherwise.

**Comment by fidelram** [comment]
Indeed the tests have been modified and now `testing.setup` is being used. Thanks for the tip. You can close this issue.

**Comment by ivirshup** [comment]
Great, thanks for fixing that!

**Comment by falexwolf** [comment]
Yeah, @fidelram added it in this PR: https://github.com/theislab/scanpy/pull/369. :smile: It's awesome, tests run through for me, too, everywhere... 

PS: Only thing that remains is the unnecessarily long runtime due to too-large test data in a couple of instances. I'll take care of it very soon.
