### ISSUE TITLE
update source field on docs website

### ISSUE THREAD

**Issue by MishalAshraf** [scverse/scanpy#3219]
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of scanpy.
- [X] (optional) I have confirmed this bug exists on the main branch of scanpy.

### What happened?

When reading docs from the readthedocs website, clicking the "source" link will navigate to the wrong spot. I think the structure was changed slightly in a commit since these were updated. The locations are still obtainable by manually walking the tree, but they are no longer what is pointed to in those [source] links. I am happy to try my hand at a fix, I just need some direction in terms of whether this is would be helpful, and how the docs are updated. 
This is where I am navigated to when i click the link for scanpy.pp.calculate_qc_metrics.
<img width="690" alt="image" src="https://github.com/user-attachments/assets/1cd8f7ba-a54b-49c4-9f00-a19633d5e606">

### Minimal code sample

```python
no code, UI fix.
```

### Versions

<details>

```

```

</details>

**Comment by ejarmand** [comment]
Just a quick follow up it seems this primarily comes from changing the dir structure from `scanpy/scanpy/*/source_file.py` to `scanpy/src/scanpy/*/source_file.py` although line numbers may or may not also require correction. Also happy to help

**Comment by flying-sheep** [comment]
Thanks, good catch!

This is already fixed in #3194, we just need to cut a release.
