### ISSUE TITLE
Differences between umap representations for `sc.pp.pca(adata, use_highly_variable=True)`, and HVG subsetted data

### ISSUE THREAD

**Issue by LuckyMD** [scverse/scanpy#324]
To elaborate a bit on my comment on pull request #284 that `sc.pp.pca(adata, use_highly_variable=True)` does not reproduce the same umap embedding as subsetting the genes.

I have done the following:

```
disp_filter = sc.pp.filter_genes_dispersion(adata.X, flavor='cell_ranger', n_top_genes=4000, log=False)
adata_hvg = adata.copy()
adata_hvg = adata_hvg[:, disp_filter['gene_subset']]
sc.pp.filter_genes_dispersion(adata, flavor='cell_ranger', n_top_genes=4000, log=False, subset=False)

sc.pp.pca(adata, n_comps=50, use_highly_variable=True, svd_solver='arpack')
sc.pp.neighbors(adata)
sc.tl.umap(adata)

sc.pp.pca(adata_hvg, n_comps=50, svd_solver='arpack')
sc.pp.neighbors(adata_hvg)
sc.tl.umap(adata_hvg)

sc.pl.umap(adata, color='n_counts', use_raw=False)
sc.pl.umap(adata_hvg, color='n_counts', use_raw=False)
```

The umap output is:
![screen shot 2018-10-25 at 10 37 36](https://user-images.githubusercontent.com/13019956/47487680-29c53a80-d843-11e8-8535-de3c84f3a3b3.png)

There is clearly a difference between the two cases also in the tsne, draw_graph and diffmap visualisations. Only pca seems to be consistent judging by eye.

**Comment by LuckyMD** [comment]
@VolkerBergen any idea why this might be?

**Comment by LuckyMD** [comment]
So I've been sitting offline with @VolkerBergen trying to get to the bottom of this. It seems that the precision of `adata.X` is reduced after subsetting. This is the case when using either of:

```
adata_hvg = adata_hvg[:, disp_filter['gene_subset']]
adata_hvg._inplace_subset_var(disp_filter['gene_subset'])
```

Either way `adata[:,disp_filter['gene_subset']].X` gives a higher precision than `adata_hvg.X`

**Comment by falexwolf** [comment]
Are you manually setting the precision of `adata.X` to 'float64'? I can't reproduce the problem with the default 'float32'. I get exactly the same result for the last digit.

If I set the precision of `adata.X` to 'float64', I can reproduce the problem. It's due to the call of `.copy` which used the default precision 'float32' and not the one of the actual object... 🙈 

It's fixed here: https://github.com/theislab/anndata/commit/ff509e32c985f5fc96a99fe6762149ac89a373ce

**Comment by LuckyMD** [comment]
I have not set the precision to float64 manually anywhere. It may however be the case that ComBat batch correction automatically uses float64. I will test and let you know.

**Comment by LuckyMD** [comment]
So it seems ComBat outputs np.float64 😐. I assume with the anndata fix that should be fine now though? I will update and rerun...

**Comment by falexwolf** [comment]
Yes, with the most recent AnnData (0.6.13), there won't be any unexpected changes of precision after the object has been created.
