### ISSUE TITLE
How to integrate the snRNA seq data generated by `scanpy` with the snATAC seq data generated by `ArchR` ?

### ISSUE THREAD

**Issue by danli349** [scverse/scanpy#3273]
### What kind of feature would you like to request?

Additional function parameters / changed functionality / changed defaults?

### Please describe your wishes

Hello: 

I have multiome snRNA+snATAC data and the snRNA seq data were analyzed with `scanpy`. 
How to integrate the snRNA seq data generated by `scanpy` with the snATAC seq data generated by `ArchR` ?
From the documents https://www.archrproject.com/bookdown/cross-platform-linkage-of-scatac-seq-cells-with-scrna-seq-cells.html
How to generate the `RangedSummarizedExperiment` data set ? Is it possible to convert the `anndata` used by `scanpy` to `RangedSummarizedExperiment` data?
Thanks a lot

**Comment by Zethson** [comment]
Could you please ask usage questions on https://discourse.scverse.org/? This is also relevant for @gtca https://github.com/scverse/muon and https://github.com/scverse/mudata
