### ISSUE TITLE
 ValueError: k must be between 1 and min(A.shape)

### ISSUE THREAD

**Issue by jorvis** [scverse/scanpy#331]
I'm doing the same pathway I've done on hundreds of datasets but this particular one fails when I try to calculate PCA with:

```
/opt/Python-3.7.0/lib/python3.7/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py in svds(A, k, ncv, tol, which, v0, maxiter, return_singular_vectors)
   1768 
   1769     if k <= 0 or k >= min(n, m):
-> 1770         raise ValueError("k must be between 1 and min(A.shape), k={0}, A.shape={1}".format(k, A.shape))
   1771 
   1772     if isinstance(A, LinearOperator):

ValueError: k must be between 1 and min(A.shape), k=50, A.shape=(48, 2066)
```
Looking into this, I looped through adata.var['n_cells'] and no values were greater than 48, so I'm not sure why this is happening.

Dropbox link with both the input test [H5AD file and notebook here](https://www.dropbox.com/sh/t2qb7ffz5msyc5e/AAD256Vs6HqLwNBjcBeCsGVGa?dl=0).

Am I missing as simple error?

**Comment by falexwolf** [comment]
Sorry for the late response, Joshua! Could it be that your dataset has less than 50 cells or variables  or something like this?

I believe that you're stating this. Computing a 50 dimensional PCA with less than 50 observations is probably not possible.
