### ISSUE TITLE
Issue with paga paths subplots in scanpy 1.3.2

### ISSUE THREAD

**Issue by Donovan-CG** [scverse/scanpy#333]
After updating scanpy to the v 1.3.2 I got this error when doing the subplots as in the "PAGA for hematopoiesis in mouse" tutorial:
_, axs = pl.subplots(ncols=6, figsize=(16, 30), gridspec_kw={'wspace': 0.05, 'left': 0.12})
pl.subplots_adjust(left=0.05, right=0.98, top=0.82, bottom=0.2)
for ipath, (descr, path) in enumerate(paths):
    _, data = sc.pl.paga_path(
        adata, path, gene_names_3,                         
        show_node_names=False,
        ax=axs[ipath],
        ytick_fontsize=12,
        left_margin=0.15,
        n_avg=50,
        annotations=['distance'],
        show_yticks=True if ipath==0 else False,
        show_colorbar=False,
        color_map='Greys',
        color_maps_annotations={'distance': 'viridis'},
        title='{} path'.format(descr),
        return_data=True,
        show=False)
    #data.to_csv('./write/paga_path_{}.csv'.format(descr))
#pl.savefig('./figures/paga_path.png')
pl.show()

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-c59dfbccf885> in <module>()
     16         title='{} path'.format(descr),
     17         return_data=True,
---> 18         show=False)
     19     #data.to_csv('./write/paga_path_{}.csv'.format(descr))
     20 #pl.savefig('./figures/paga_path.png')

~\Anaconda3\lib\site-packages\scanpy\plotting\tools\paga.py in paga_path(adata, nodes, keys, use_raw, annotations, color_map, color_maps_annotations, palette_groups, n_avg, groups_key, xlim, title, left_margin, ytick_fontsize, title_fontsize, show_node_names, show_yticks, show_colorbar, legend_fontsize, legend_fontweight, normalize_to_zero_one, as_heatmap, return_data, show, save, ax)
    932             idcs = idcs[idcs_group]
    933             if key in adata.obs_keys(): x += list(adata.obs[key].values[idcs])
--> 934             else: x += list(adata_X[:, key].X[idcs])
    935             if ikey == 0:
    936                 groups += [group for i in range(len(idcs))]

~\Anaconda3\lib\site-packages\anndata\base.py in __getitem__(self, index)
   1301     def __getitem__(self, index):
   1302         """Returns a sliced view of the object."""
-> 1303         return self._getitem_view(index)
   1304 
   1305     def _getitem_view(self, index):

~\Anaconda3\lib\site-packages\anndata\base.py in _getitem_view(self, index)
   1305     def _getitem_view(self, index):
   1306         oidx, vidx = self._normalize_indices(index)
-> 1307         return AnnData(self, oidx=oidx, vidx=vidx, asview=True)
   1308 
   1309     # this is used in the setter for uns, if a view

~\Anaconda3\lib\site-packages\anndata\base.py in __init__(self, X, obs, var, uns, obsm, varm, layers, raw, dtype, shape, filename, filemode, asview, oidx, vidx)
    667             if not isinstance(X, AnnData):
    668                 raise ValueError('`X` has to be an AnnData object.')
--> 669             self._init_as_view(X, oidx, vidx)
    670         else:
    671             self._init_as_actual(

~\Anaconda3\lib\site-packages\anndata\base.py in _init_as_view(self, adata_ref, oidx, vidx)
    724             self._X = None
    725         else:
--> 726             self._init_X_as_view()
    727 
    728         self._layers = AnnDataLayers(self, adata_ref=adata_ref, oidx=oidx, vidx=vidx)

~\Anaconda3\lib\site-packages\anndata\base.py in _init_X_as_view(self)
    751             shape = (
    752                 get_n_items_idx(self._oidx, self._adata_ref.n_obs),
--> 753                 get_n_items_idx(self._vidx, self._adata_ref.n_vars)
    754             )
    755             if np.isscalar(X):

~\Anaconda3\lib\site-packages\anndata\utils.py in get_n_items_idx(idx, l)
    141         return 1
    142     else:
--> 143         return len(idx)

TypeError: object of type 'numpy.int64' has no len()

**Comment by lkmklsmn** [comment]
I am getting the same error in a much more basic setting:
```
paul=sc.datasets.paul15()
sc.pl.scatter(paul, x=paul.var_names[0], y=paul.var_names[1])
```
...
> TypeError: object of type 'numpy.int64' has no len()

**Comment by lkmklsmn** [comment]
Forgot to mention my versions: 

> scanpy==1.3.2 anndata==0.6.11 numpy==1.14.6 scipy==1.1.0 pandas==0.23.4 scikit-learn==0.20.0 statsmodels==0.9.0 python-igraph==0.7.1+4.bed07760

**Comment by falexwolf** [comment]
Everything runs fine on the current master branch, I uploaded the current version of the notebook: https://nbviewer.jupyter.org/github/theislab/paga/blob/master/blood/paul15/paul15.ipynb

I'll release either 1.3.3 or 1.4 very soon and if there should have been a bug at some point, it seems to have been fixed at some point.

Finally, PAGA is also in the continuous integration tests, so no bugs in the future anymore for this. ;)

**Comment by lkmklsmn** [comment]
I updated to 1.3.3 but the error still persists. One important thing I didnt mention before: I am running python/scanpy on a Windows machine. @Donovan-CG do you also use Windows?

**Comment by lkmklsmn** [comment]
This is probably related to some Windows "weirdness" as discussed here: https://stackoverflow.com/questions/36278590/numpy-array-dtype-is-coming-as-int32-by-default-in-a-windows-10-64-bit-machine

**Comment by Donovan-CG** [comment]
@lkmklsmn Yes, I'm also using Windows.
