### ISSUE TITLE
scanpy installation on colab without any GPU's

### ISSUE THREAD

**Issue by CRISTIANJULIOCESAR** [scverse/scanpy#3345]
### Please make sure these conditions are met

- [x] I have checked that this issue has not already been reported.
- [ ] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the main branch of scanpy.

### What happened?

There's an issue with the installation of scanpy in Colab when working without GPUs, only using the CPU, which is my intention to avoid consuming computational units. This doesn't allow me to import scanpy; I get the following error:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/cupy/__init__.py](https://localhost:8080/#) in <module>
     16 try:
---> 17     from cupy import _core  # NOQA
     18 except ImportError as exc:

10 frames
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

ImportError                               Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/cupy/__init__.py](https://localhost:8080/#) in <module>
     17     from cupy import _core  # NOQA
     18 except ImportError as exc:
---> 19     raise ImportError(f'''
     20 ================================================================
     21 {_environment._diagnose_import_error()}

ImportError: 
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
================================================================

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

### Minimal code sample

!pip install scanpy
import scanpy as sc

### Versions

<details>

```

```

</details>

**Comment by eroell** [comment]
This is an issue with anndata 0.11.0 https://github.com/scverse/anndata/issues/1749

**Comment by ilan-gold** [comment]
@CRISTIANJULIOCESAR https://github.com/scverse/anndata/issues/1749#issuecomment-2467696125

**Comment by flying-sheep** [comment]
closing as duplicate. please check out the linked issue for workarounds.
