### ISSUE TITLE
Getting rankinged genes in list, e.g. from sc.pl.rankings

### ISSUE THREAD

**Issue by Xparx** [scverse/scanpy#338]
I'm looking in to sc.pl.pca_loadings and sc.pl.rankings.

I want to retrieve the list of highest scoring genes for my pcs. However both these methods are designed for plotting and rankings is a bit hard to interpret. Is there or could there be a nice way to retrieve list of rankings in the same way as sc.pl.rankings is doing it but get the list rather than a figure?

How would I go about this within the context of scanpy?

**Comment by falexwolf** [comment]
Hm, how about simply ranking things yourself, like 
```
sort_idcs = np.argsort(adata.var['PCs'][:, 0])
genes_ranked_by_loading_in_PC1 = adata.var_names[sort_idcs]
```
This is what the plotting functions do internally.
