### ISSUE TITLE
Aspect ratio of scatter plots

### ISSUE THREAD

**Issue by fbnrst** [scverse/scanpy#339]
Is there a way to set the aspect ratio of scatter plots in scanpy?

For me, the aspect ratio changes in ways that I cannot fully control. For instance, in the following example the aspect ratio of a PCA plot is changed when I set the dpi:

```python
import scanpy.api as sc
adata = sc.ådatasets.blobs()
sc.tl.pca(adata, svd_solver='arpack')
```
```python
sc.pl.pca(adata)
```
![image](https://user-images.githubusercontent.com/7300030/47845493-808fbe80-ddc5-11e8-8e69-30bf9b37803a.png)
```python
sc.set_figure_params(dpi=80)
sc.pl.pca(adata)
```
![image](https://user-images.githubusercontent.com/7300030/47845511-8c7b8080-ddc5-11e8-81a5-90ac2af77cba.png)

**Comment by falexwolf** [comment]
`set_figure_params` does a whole bunch of stuff is `scanpy=True`: https://scanpy.readthedocs.io/en/latest/api/scanpy.api.set_figure_params.html#scanpy.api.set_figure_params

Simply set your favorite `matplotlib.rcParams` directly after calling the function; or don't call the function at all (or with `scanpy=False`) and set all the rcParams yourself.

**Comment by fbnrst** [comment]
Thanks!
