### ISSUE TITLE
Give the option for rank genes group to directly return a dataframe

### ISSUE THREAD

**Issue by LinearParadox** [scverse/scanpy#3391]
### What kind of feature would you like to request?

Additional function parameters / changed functionality / changed defaults?

### Please describe your wishes

Give the option for rank genes group to directly return a dataframe instead of modifying the anndata object. This would be particularly helpful for using these functions in other packages. This way, we wouldn't have to modify user objects or make copies of the anndata (which can be memory intensive).

**Comment by flying-sheep** [comment]
Already possible with `copy=True`, and we’ll address this more completely in #2583

If you want this more quickly, PRs welcome!
