### ISSUE TITLE
`certifi` not declared as dependency in `pyproject.toml`

### ISSUE THREAD

**Issue by jeskowagner** [scverse/scanpy#3395]
`certifi` is used in [`_download`](https://github.com/scverse/scanpy/blob/main/src/scanpy/readwrite.py#L1020), but not declared as dependency in `pyproject.toml` and can thus fail to be installed as dependency, such as in [this](https://github.com/edbiomedai/scmorph/actions/runs/12235132448/job/34125768942#step:7:1575) CLI run.

**Comment by ilan-gold** [comment]
I am assigning Phil to this but in general, I would think perhaps the answer is then "install certifi" but I am not sure the intention here so I'll leave this to Phil.

**Comment by jeskowagner** [comment]
I have added `certifi` to my dependencies now, but just wanted to flag this might be an issue for users if they do not have certifi in their installed packages.

**Comment by ilan-gold** [comment]
Thanks @jeskowagner I agree we should have some sort of solution for this, just not sure what that is.  Maybe editing the warning.

**Comment by flying-sheep** [comment]
@jeskowagner please don’t open blank issues. Use issue templates instead

**Comment by jeskowagner** [comment]
Sorry about that, I wasn't sure whether this would fall under enhancement or bug. Will try and pick one next time.

**Comment by flying-sheep** [comment]
You’re right, it’s a bit ambiguous. I should add a “improve documentation or error message” category in the enhancement issue template.

/edit: done
