### ISSUE TITLE
Error when filtering: AttributeError: 'Series' object has no attribute 'is_dtype_equal'

### ISSUE THREAD

**Issue by alexisboukouvalas** [scverse/scanpy#34]
Hi, I hit this error when trying to filter genes.
A minimal working example is included below.

Any help appreciated.

```
def paul15_raw():
    filename = 'data/paul15/paul15.h5'
    backup_url = 'http://falexwolf.de/data/paul15.h5'
    adata = sc.read(filename, 'data.debatched', backup_url=backup_url)
    # each row has to correspond to a sample, therefore transpose                                                                                                               
    adata = adata.transpose()    # cluster assocations identified by Paul et al.
    clusters = sc.read(filename, 'cluster.id', return_dict=True)['X'].flatten()
    # names reflecting the cell type identifications from the paper
    cell_types = {i: 'Ery' for i in range(1, 7)}
    cell_types[7] = 'MEP'
    cell_types[8] = 'Mk'
    cell_types[9] = 'GMP'
    cell_types[10] = 'GMP'
    cell_types[11] = 'DC'
    cell_types[12] = 'Baso'
    cell_types[13] = 'Baso'
    cell_types[14] = 'Mo'
    cell_types[15] = 'Mo'
    cell_types[16] = 'Neu'
    cell_types[17] = 'Neu'
    cell_types[18] = 'Eos'
    cell_types[19] = 'Other'
    adata.smp['paul15_clusters'] = [str(i) + cell_types[i] for i in clusters.astype(int)]
    infogenes_names = sc.read(filename, 'info.genes_strings', return_dict=True)['X']
    # just keep the first of the two equivalent names per gene                                                                                                                       
    adata.var_names = np.array([gn.split(';')[0] for gn in adata.var_names])
    # remove 10 corrupted gene names                                                                                                                                                 
    infogenes_names = np.intersect1d(infogenes_names, adata.var_names)
    # restrict the data to the 3461 informative genes                                                                                                                              
    adata = adata[:, infogenes_names]
    adata.add['iroot'] = np.flatnonzero(adata.smp['paul15_clusters']  == '7MEP')[0]
    return adata
    
 adata = paul15_raw()
 afilter = sc.pp.recipe_zheng17(adata, n_top_genes=1000, zero_center=True, plot=True, copy=True)
```

or 
```
afilter = sc.pp.filter_genes_dispersion(adata, n_top_genes=1000)
```

both fail with 
```AttributeError: 'Series' object has no attribute 'is_dtype_equal'```
when computing the dispersion norm (line 207, simple.py)
```
    207         df['dispersion_norm'] = (df['dispersion'].values  # use values here as index differs
--> 208                                  - disp_mean_bin[df['mean_bin']].values) \
    209                                  / disp_std_bin[df['mean_bin']].values
```

Running Scanpy version 0.2.6 on 2017-08-23 14:35.

**Comment by alexisboukouvalas** [comment]
Ok I think this is a bug - notebooks paul15.ipynb fails with the same error - see Section 
### Using a preprocessing recipe

adata = paul15_raw()
sc.pp.recipe_zheng17(adata)

**Comment by falexwolf** [comment]
Hi Alexis,
sorry about that. I made substantial changes to set up and build the [docs](https://scanpy.readthedocs.io) remotely just in the past days and for that had to experiment on the master branch. I'm fixing everything tonight running tests on all example notebooks. I will also incude more tests in the future so that stuff like this doesn't happen anymore.
Cheers,
  Alex

**Comment by falexwolf** [comment]
I let you know as soon as there is a stable release back on github. 0.2.5 should be stable [as well](https://github.com/theislab/scanpy_usage), but has some other drawbacks. Things are still progressing fast.

**Comment by alexisboukouvalas** [comment]
Thanks @falexwolf 
I have fixed my local file with
~ln 209
```
        df['dispersion_norm'] = (df['dispersion'].values - disp_mean_bin[df['mean_bin'].values].values) / disp_std_bin[df['mean_bin'].values].values
```
and
~ln 220
```
        df['dispersion_norm'] = (df['dispersion'].values - disp_median_bin[df['mean_bin'].values].values) / disp_mad_bin[df['mean_bin'].values].values
```

Also plot=True  
```
afilter = sc.pp.recipe_zheng17(a, n_top_genes=1000, zero_center=True, plot=True, copy=True)
```
fails with
```
AttributeError: module 'scanpy.plotting' has no attribute 'filter_genes_dispersion'
```

**Comment by alexisboukouvalas** [comment]
You could use the notebooks as part of your tests - see [GPflow notebook tests](https://github.com/GPflow/GPflow/blob/master/testing/test_notebooks.py) as an example.

**Comment by falexwolf** [comment]
Thanks for the suggestions and that concrete implementation! :smile: @flying-sheep has been suggesting this for quite some time already, but has not yet found the time to implement it. The difficulty will be to replace the visual inspection of all the plots from version to version with something testable.

**Comment by falexwolf** [comment]
Now, there is a nice overview of all examples [here](https://scanpy.readthedocs.io/en/latest/examples.html). Also, I ran through all example notebooks with the new version 0.2.7 just now: https://github.com/theislab/scanpy_usage and it worked; unfortunately, going through all examples, I didn't experience the bug that you are reporting. Are you maybe using a very old Pandas version?

**Comment by falexwolf** [comment]
Regarding your other bug: `scanpy.plotting` used to have the attribute and `scanpy.api.plotting` would simply import the module. To make the [overview of the API](https://scanpy.readthedocs.io/en/latest/api.html) work, I had to introduce a [dummy module](https://github.com/theislab/scanpy/blob/master/scanpy/api/pl.py). In order to avoid duplication, I removed all exports from `scanpy.plotting.__init__`.

I readded it to fix the bug on the development branch, but I need to think of a better solution.

**Comment by falexwolf** [comment]
See this [overview of the API](https://scanpy.readthedocs.io/en/latest/api.html).

**Comment by falexwolf** [comment]
OK; now I have more time. The error thrown at 
```
    207         df['dispersion_norm'] = (df['dispersion'].values  # use values here as index differs
--> 208                                  - disp_mean_bin[df['mean_bin']].values) \
    209                                  / disp_std_bin[df['mean_bin']].values
```
astonishes me. The line has been working for me on pandas 0.19.2 and 0.20.3 and for others for other versions for many months already. Do you have an old pandas version? The line should work as `disp_mean_bin` has been computed from `disp_grouped = df.groupby('mean_bin')['dispersion']` [here](https://github.com/theislab/scanpy/blob/65503d34d6b9d0a1d23e831d6daeba86856b3eee/scanpy/preprocessing/simple.py#L215); i.e., the Series 'mean_bin' was used to initialize the index of `disp_mean_bin`. Hence, you should be able to index with 'mean_bin'.
