### ISSUE TITLE
regress out unwanted principal components.

### ISSUE THREAD

**Issue by Xparx** [scverse/scanpy#341]
I'm preprocessing a dataset and want to regress_out selected principal components.
Is there a built in way in scanpy for this task.
Some way to use regress-out to accomplish this?

**Comment by falexwolf** [comment]
You can do this via `X.obs['PC2'] = X.obsm['X_pca'][:, 1]`, when you don't like PC 2 (when the first component is "PC1" and not "PC0").

`regress_out` accepts as many uni-variate observation annotations as you want, so you can combine this with anything else and as much PCs as you like.

**Comment by Xparx** [comment]
Thanks for the quick answer. This was the solution I was looking at.
