### ISSUE TITLE
How to add adata.layers information for running scvelo?

### ISSUE THREAD

**Issue by PattF** [scverse/scanpy#342]
Hi,
I'm attempting to run scvelo on my scanpy processed 10x data.
Initially I provided the .h5ad file from scanpy as the input file for scvelo but ran into error KeyError: 'unspliced', I'm assuming unspliced data can't be found and also that "adata.layers" doesn't exist in my scanpy processed .h5ad file.
I also attempted providing the unprocessed data directly into scvelo but again came up with the error KeyError: 'unspliced'.
I've attempted adata.layers.keys() which returns odict_keys([]) and scv.pp.show_proportions(adata) which returns Abundance of []: []. (Currently running version 1.3.2 of scanpy and 0.1.11 of scvelo).
My adata file doesn't seem to contain adata.layers information, is there a way to add this information via scanpy?

**Comment by falexwolf** [comment]
Please, can you file this in the scvelo repo? Thank you! 🙂
