### ISSUE TITLE
Dendrogram feature

### ISSUE THREAD

**Issue by coh-racng** [scverse/scanpy#344]
It seems like the dendrogram feature has been merged into the master branch according to this thread #308  and it is documented in the API. However, after updating my scanpy to 1.3.2, I still cannot access the dendrogram feature and get the following error when I set `dendrogram=True` when using `sc.pl.heatmap`:
`AttributeError: Unknown property dendrogram`

Here are the versions that I am using:
scanpy==1.3.2 anndata==0.6.10 numpy==1.14.3 scipy==1.1.0 pandas==0.23.0 scikit-learn==0.19.1 statsmodels==0.9.0 python-igraph==0.7.1 louvain==0.6.1

Do you plan on releasing the dendrogram feature? Which package version currently has it?

**Comment by LuckyMD** [comment]
You may need to install from github rather than wait for new pypi versions.

**Comment by falexwolf** [comment]
It's in 1.3.3, which is out on PyPI. The docs shows the latest version from GitHub by default (`latest`).
