### ISSUE TITLE
Reproducibility of tSNE

### ISSUE THREAD

**Issue by fbnrst** [scverse/scanpy#345]
I am having issues with the reproducibility of tSNE but they are subtle. This might be a duplicate of #203. 

Here is an example notebook: http://nbviewer.jupyter.org/gist/fabianrost84/5839b9d913de7560339d9251d1a49dae

In the notebook, the first tSNE plot is different from the second. Interestingly, the second and the third tSNE plot are exactly the same. To reproduce the behaviour it is important to restart the kernel and then run all cells. If you run all cells again without restarting the kernel, all tSNE plot look the same for me. I only have this issue if I use the MulticoreTSNE package.

**Comment by wangjiawen2013** [comment]
I asked this question before. Now I use umap and force directed plot instead. Seurat has also set umap as it's default method.

**Comment by falexwolf** [comment]
I'm sorry but I'm not going to investigate this, it seems that it's highly related to usage `MulticoreTSNE`. Quite generally: UMAP and graph drawing should are the only recommended visualization algorithms these days, given that tSNE tears apart your data and doesn't scale well.
