### ISSUE TITLE
Differential Expression with a fixed reference

### ISSUE THREAD

**Issue by Marius1311** [scverse/scanpy#346]
When I run `sc.tl.rank_genes_groups` and I set the `reference` argument to one of my groups I am testing, I get the error

```pytb
     91         groups_order = [str(n) for n in groups_order]
     92     if reference != 'rest' and reference not in set(groups_order):
---> 93         groups_order += [reference]
     94     if (reference != 'rest'
     95         and reference not in set(adata.obs[groupby].cat.categories)):

TypeError: must be str, not list
```

That's because 'groups_order'  is not a list at this point of the code when the argument `groups` is at its default `all`. When I change this and I pass a list, e.g. ['0', '1'], then the error vanished, because `groups order` will then be a list that we can add to. This should be changed, because the setting 'all' is the default value.

**Comment by falexwolf** [comment]
Why not simply as in the [tutorial](https://nbviewer.jupyter.org/github/theislab/scanpy_usage/blob/master/170505_seurat/seurat.ipynb)?
```
sc.tl.rank_genes_groups(adata, 'louvain', groups=['0'], reference='1')
```
Or am I missing your problem? A few lines of code documenting your call wouldn't hurt.

**Comment by Marius1311** [comment]
Hi Alex!

Sorry for this long delay, I just forgot completely.
Maybe I wasn't clear enough in my original post, here is where the issue lies:
 
When I run 

```py
sc.tl.rank_genes_groups(adata_f, groupby = 'ClusterName', groups = 'all')
```

everything is fine and I get my desired result. However, when I just change the reference setting

```py
sc.tl.rank_genes_groups(adata_f, groupby = 'ClusterName', reference='CA', groups = 'all')
```

then I get the following error

```pytb
    100         groups_order = [str(n) for n in groups_order]
    101     if reference != 'rest' and reference not in set(groups_order):
--> 102         groups_order += [reference]
    103     if (reference != 'rest'
    104         and reference not in set(adata.obs[groupby].cat.categories)):

TypeError: must be str, not list
```

I absolutely understand how to solve this - as you said, I can just use the tutorial call and select groups explicilty

```py
sc.tl.rank_genes_groups(adata_f, groupby = 'ClusterName', reference='CA', groups = ['OPC', 'Granule'])
```

and then it works again. I was just wondering whether this is the desired behavior - most users will leave the `groups` attribute at it's default setting when they change the `reference` attribute and wonder why it does not work - at least that was my idea. Maybe I am wrong.

**Comment by falexwolf** [comment]
Thank you for pointing it out, that's obviously a bug!

**Comment by CaibinSh** [comment]
I got the same issue recently, could I ask if you have fixed the bug, please?

**Comment by michael-swift** [comment]
I also had this issue with scanpy 1.6.0, which is fixable in the way mentioned by Marius1311, but I agree it is not the expected behavior
