### ISSUE TITLE
Adding sub-cluster to original Louvain clustering

### ISSUE THREAD

**Issue by ltosti** [scverse/scanpy#347]
Hi there,

I tried to refine the Louvain clustering results and in particular I re-ran the clustering on a specific bigger cluster that was initially identified. 
After this analysis, the original cluster was split in two and this makes sense considering the biological system we are studying. What is the easiest way to add this information to the original Louvain clustering results? 

My naive approach of using something like:

```adata.obs.louvain[adata.obs.index.isin(adata_sub.obs.index)] = '10' ```

Doesn't seem to be the correct one? 

Thank you!

**Comment by falexwolf** [comment]
Hey! So you used `restrict_to = ('louvain', ['1'])` if you wanted to recluster '1'? You'll have a new clustering variable `louvain_R` in this case, which you can rename anything you like... checkout the documentation: https://icb-scanpy.readthedocs-hosted.com/en/latest/api/scanpy.api.tl.louvain.html

I guess that this is what you want.

**Comment by ltosti** [comment]
It works perfectly, don't know how I missed that in the documentation...thank you!
