### ISSUE TITLE
Rearranging adata.obs

### ISSUE THREAD

**Issue by jayypaul** [scverse/scanpy#352]
The indices of adata.obs are the barcodes to the cells. I've calculated adata.obsm['X_umap'], but I want to rearrange the barcodes so that the adata.obsm['X_umap'] array will still correspond to the barcodes afterward. However, after sorting the indices based on sort_value or sort_indices, the adata.obsm['X_umap'] array doesn't change along with it. 

Any thoughts on how to properly go about this?

**Comment by falexwolf** [comment]
It should definitely have changed along with it. What was the problem?
