### ISSUE TITLE
Removing specific genes from the data before normalization

### ISSUE THREAD

**Issue by ashwinikumarkulkarni** [scverse/scanpy#353]
I want to remove mitochondrial genes from the data before normalization. I already have used mitochondrial genes to calculate "pct_counts_mito", but I don't want them to be in the data for downstream analysis. Is there a function to achieve this in scanpy.api? Thanks!

**Comment by falexwolf** [comment]
Simply use standard slicing. The most elegant way in this case would be something like [this](https://github.com/theislab/scanpy/blob/7de1f5159c91d6d2243bb7866d9495ee6747c750/scanpy/datasets/__init__.py#L108-L109), I guess. 🙂

**Comment by fidelram** [comment]
I also do
```python
# if mito_genes is a list of gene names
adata = adata[:, ~adata.var.names.isin(mito_genes)].copy()
```

or 
```python
not_mito_genes =~adata.var_names.str.startswith("MT-")
#not_mito_genes is a boolean
adata = adata[:, not_mito_genes].copy()
````

**Comment by LuckyMD** [comment]
Can I ask you guys why you remove mitochondrial genes?
