### ISSUE TITLE
fix github links for functions in docs

### ISSUE THREAD

**Issue by flying-sheep** [scverse/scanpy#36]
i found pointers about the “Edit on GitHub” button [here](https://github.com/sphinx-doc/sphinx/issues/2386), and [this](https://github.com/rtfd/sphinx_rtd_theme/blob/728d5da2e4e8f5fb2c964217d55299d00332e359/sphinx_rtd_theme/breadcrumbs.html#L41-L46) is the relevant template code.

maybe we can set `meta['github_url']` [like this](http://www.sphinx-doc.org/en/stable/markup/misc.html#file-wide-metadata), but [this approach](https://stackoverflow.com/a/11746519/247482) does nothing:

```py
def process_docstring(app, what, name, obj, options, lines):
    nm = name.replace('.', '/').replace('api/pp', 'preprocessing')

    lines[:0] = [f':github_url: https://https://github.com/theislab/scanpy/tree/master/{nm}.py', '']


def setup(app):
    app.connect('autodoc-process-docstring', process_docstring)
```

maybe we can get inspiration from the [viewcode](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/viewcode.py) extension

**Comment by falexwolf** [comment]
Very cool that this works! :smile:
