### ISSUE TITLE
Error using rank_genes_groups

### ISSUE THREAD

**Issue by Puumanamana** [scverse/scanpy#365]
Hi,

I have been Scanpy for a short time and I find it really great!
However, I tried recently to use it for differential expression using rank_genes_groups and I could not make it work. I have a single-cell RNA-seq dataset with cell types.
When running `rank_genes_groups(adata, groupby="celltype")`, I get the following error:

```
~/.py3Env/lib/python3.5/site-packages/scanpy/tools/rank_genes_groups.py` in rank_genes_groups(adata, groupby, use_raw, groups, reference, n_genes, rankby_abs, key_added, copy, method, corr_method, **kwds)
    374     adata.uns[key_added]['names'] = np.rec.fromarrays(
    375         [n for n in rankings_gene_names],
--> 376         dtype=[(rn, 'U50') for rn in groups_order_save])
    377
    378     if method in {'t-test', 't-test_overestim_var', 'wilcoxon'}:

~/.py3Env/lib/python3.5/site-packages/numpy/core/records.py in fromarrays(arrayList, dtype, shape, formats, names, titles, aligned, byteorder)
    632     # populate the record array (makes a copy)
    633     for i in range(len(arrayList)):
--> 634         _array[_names[i]] = arrayList[i]
    635
    636     return _array

ValueError: setting an array element with a sequence
```

Do you have any idea of what could cause this error?

Thank you

**Comment by falexwolf** [comment]
Are your cell types labeled with lists or something? Can you show the categories of the `'celltype'` annotation: `adata.obs['celltype'].cat.categories`?

**Comment by Puumanamana** [comment]
They are annotated with a list of length the number of cells.
Here is what I have for `adata.obs['celltype'].cat.categories`:
`Index(['Group1', 'Group2', 'Group3'], dtype='object')`

**Comment by aopisco** [comment]
@Puumanamana I was having a similar issue when using `sc.pl.clustermap`, I've solved it by pulling the latest version from github

**Comment by falexwolf** [comment]
> They are annotated with a list of length the number of cells.
Here is what I have for adata.obs['celltype'].cat.categories:
Index(['Group1', 'Group2', 'Group3'], dtype='object')

This is perfectly the canonical way it should look like - I thought that instead of 'Group1', you'd have a list.

Could you print `groups_order_save` before line 376 in `~/.py3Env/lib/python3.5/site-packages/scanpy/tools/rank_genes_groups.py`? I don't know how it can happen that it stores strange things, but there seems to be a bug there.

**Comment by Puumanamana** [comment]
I get the same in the list format:
`groups_order_save`
`> ['Group1', 'Group2', 'Group3']`

**Comment by falexwolf** [comment]
This is all looks fine and should work perfectly. I'd need an example with some data and the lines of code that produce the error.

**Comment by Puumanamana** [comment]
I can do that. I have a pickled object that I can share with you (how?).
Here is how you reproduce the error:
```
import scanpy.api as sc
import pickle

# Load the object
with open("example.pkl","rb") as handle:
    adata = pickle.load(handle)

# Run Scanpy
sc.tl.rank_genes_groups(adata,groupby="celltype")
```

**Comment by falexwolf** [comment]
Cool! By email is fine: alex.surname@helmholtz-muenchen.de, by surname is wolf. Thank you! :)

**Comment by falexwolf** [comment]
PS: You can of course also simply upload here on GitHub in a comment, as you want. 
PPS: The canonical way of saving AnnData's is via `.write('myfile.h5ad')`. 🙂

**Comment by Puumanamana** [comment]
How, I did not see you could just drag and drop. I'll do that instead then.
Here it is:
[example.pkl.gz](https://github.com/theislab/scanpy/files/2601534/example.pkl.gz)

**Comment by falexwolf** [comment]
Your observations index contains tuples, which is, kind of weird:
![image](https://user-images.githubusercontent.com/16916678/48802882-7125d600-ecde-11e8-84ce-cb0d5eea1f71.png)
Let me look further...

**Comment by Puumanamana** [comment]
That was it, it works! It's weird because everything worked beside rank_genes_group (recipe_seurat, Louvain, ...). The problem was the way I created my AnnData object. When filling the obs_name and var_names, the input were data frames, not lists.

Thanks a lot for your help.

**Comment by falexwolf** [comment]
But the error comes from your variable names being tuples. The following fixes it.
```
adata.var_names = [i[0] for i in adata.var_names]
```

Let me think where it would be best to output a warning. I'm not quite sure where else it would lead to collisions. Do you need tuples in the index?

**Comment by wangjiawen2013** [comment]
do you have any references on t-test_overestim_var ? I cannot find papers on this test method. what's the difference from t-test ? @falexwolf

**Comment by falexwolf** [comment]
No, there aren't any references. It's most easy to understand from this: https://github.com/theislab/scanpy/blob/662f66a4c2bc9a254990792f570cc971a444c575/scanpy/tools/_rank_genes_groups.py#L191

We had quite some material before (@tcallies, where did it go?), but we're now moving away from it and will set a different default test in the future.

**Comment by genecell** [comment]
> do you have any references on t-test_overestim_var ? I cannot find papers on this test method. what's the difference from t-test ? @falexwolf

I am also interested in formal descriptions about t-test_overestim_var or related publications, thank you!
