### ISSUE TITLE
Nadia single cell loading in scanpy

### ISSUE THREAD

**Issue by manarai** [scverse/scanpy#366]
Hi 

We have purchased the Nadia dolomite machine which is the automated version of dropseq. I am using the dropseqpipe pipeline for demultiplexing and generate count matrix. Analysis with Seurat is fine but how do you load a count matrix in scanpy?

**Comment by falexwolf** [comment]
Anything that helps here: https://scanpy.readthedocs.io/en/latest/api/index.html#reading?

**Comment by manarai** [comment]
Thanks it worked

![screen shot 2018-11-20 at 5 51 30](https://user-images.githubusercontent.com/39877296/48734284-5aed2b00-ec88-11e8-8e2b-0660526a62c2.png)
