### ISSUE TITLE
legend of subfigures overlapping

### ISSUE THREAD

**Issue by Hoeze** [scverse/scanpy#368]
I've got some problems with overlapping legends:

```python3
sc.pl.umap(adata_pp, color=["treatment", "mixture_assignment"])
```
![grafik](https://user-images.githubusercontent.com/1200058/48719273-60f9f200-ec1d-11e8-8cab-08434ad02411.png)

Is there something I can do about this?

**Comment by fidelram** [comment]
You can increase the distance between plots by setting `wspace=0.3`
(default is 0.1). Otherwise you can do:  `ncols=1` or  `legend_loc='on
data`.

**Comment by Hoeze** [comment]
@fidelram Thanks for your help, `wspace=0.3` perfectly solves this problem :+1:
