### ISSUE TITLE
use_raw=True has no effect for plotting.

### ISSUE THREAD

**Issue by Xparx** [scverse/scanpy#370]
scanpy.pl.tsne or any of the variants only distinguish use_raw=None and other.
All other values than None results in using the processed X matrix rather than the assigned raw data even if using use_raw=True

**Comment by falexwolf** [comment]
That's quite a bug... Let me check, it can only have stayed unnoticed as the default shows the *raw* data, if `.raw` has been set.

**Comment by Xparx** [comment]
I should add.
scanpy version = '1.3.2'
Python 3.6.6

**Comment by Xparx** [comment]
I upgraded to 1.3.3 and the bug persists. 

PS: I accidentally closed the issue for some reason.

**Comment by fidelram** [comment]
I can reproduce the problem. Very strange. I will submit a PR to fix it.
