### ISSUE TITLE
umap legends overlap with axis when decreasing legend fontsize

### ISSUE THREAD

**Issue by sophiamaedler** [scverse/scanpy#374]
Here is a minimal example to recreate the issue I am describing:

```
import scanpy.api as sc
adata = sc.datasets.pbmc68k_reduced()
sc.tl.pca(adata)
sc.pp.neighbors(adata)
sc.tl.umap(adata)
```

when you plot the umap of the bulk labels contained in adata.obs without specifying any further settings (i.e. `sc.pl.umap(adata, color = ['bulk_labels'])` ) everything looks fine. 

![image](https://user-images.githubusercontent.com/15019107/48847064-efe34780-eda0-11e8-8d51-b503d7912d1e.png)

But as soon as you try and adjust the legend font size (`sc.pl.umap(adata, color = ['bulk_labels'], legend_fontsize = 4)`) to a value that is smaller than the default font size it selects for your legend, the legend overlaps with the right edge of the plot. 

![image](https://user-images.githubusercontent.com/15019107/48847096-04274480-eda1-11e8-9bac-dceb31aba155.png)

For me this sometimes leads to issues that I can no longer export figures with my desired fontsize for presentations, etc. without it overlapping the plot in an ugly way.

**Comment by fidelram** [comment]
This is caused by an adjustment that tries to keep the legends closer to
the figure compared to the default placing. Clearly, there is some
dependency with the font size that I was not aware of. I will prepare a fix
soon.

**Comment by falexwolf** [comment]
Thank you, @fidelram!

**Comment by sophiamaedler** [comment]
Thank you both for fixing this!
