### ISSUE TITLE
Changing scale for plotting functions

### ISSUE THREAD

**Issue by ltosti** [scverse/scanpy#377]
Hello there,

Is it possible to customise the expression range scale when using for example ```pl.umap```?  I thought I could try ```use_raw=True```, but got the same issue as in #370.

Thank you for your help!

**Comment by fidelram** [comment]
you can use `vmin` and `vmax` to control the scale range. You can also change the colormap using `cmap`. For example: 
````PYTHON
rcParams['figure.figsize'] = 4,4
adata = sc.datasets.pbmc68k_reduced()
sc.pl.umap(adata, color=['CD3D'], use_raw=False, cmap='bwr', vmin=-3, vmax=3)
````
![image](https://user-images.githubusercontent.com/4964309/48904466-bffa7980-ee5e-11e8-94ac-bd29a4552152.png)

**Comment by ltosti** [comment]
Thank you @fidelram !

**Comment by ltosti** [comment]
@fidelram, just wanted to add that I still cannot use the ```use_raw=False``` parameter, for example I keep getting an error when try to visualise my data with ```sc.pl.rank_genes_groups_heatmap``` or ```sc.pl.rank_genes_groups_matrixplot```.

**Comment by falexwolf** [comment]
Should be solved via: https://github.com/theislab/scanpy/pull/372#issuecomment-441022399

Sorry for being slow.

Thank you, @fidelram!

**Comment by alejandro-jimenezsanchez** [comment]
Is there a way to have different `vmin` and `vmax` with different UMAPs? For example:

```
rcParams['figure.figsize'] = 4,4
adata = sc.datasets.pbmc68k_reduced()
sc.pl.umap(adata, color=["CD3D", "TP53"], use_raw=False, cmap='bwr', vmin=[-3,-1], vmax=[3,4])
```

**Comment by fidelram** [comment]
We are discussing that at the moment. See https://github.com/theislab/scanpy/issues/775
