### ISSUE TITLE
Prettify `Union` in docs (`Union[A, B]` → `A, B`)

### ISSUE THREAD

**Issue by flying-sheep** [scverse/scanpy#379]
Part of #373

**Comment by falexwolf** [comment]
Cool!

**Comment by flying-sheep** [comment]
Fixed in bc1cbce14545f5d8dd8a8e16d77e04714a1859c9. That was easy.

Only problem: When a Union now appears inside of other things (e.g. `Tuple[X, Union[A,B]]`), this will look wrong. (I.e. `Tuple[X, A, B]`)

Any ideas?

**Comment by falexwolf** [comment]
Thank you! Let me go through a few examples for the more tricky cases. We'll find a solution.
