### ISSUE TITLE
sc.pl.paga value error

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/scanpy#381]
Dear, 
When I use sc.pl.paga(adata) to show my single cell data with 16 clusters, it works well. However, when I show another data with only 4 cluster, the following error occurs:

ValueError                                Traceback (most recent call last)
~/bin/miniconda3/lib/python3.6/site-packages/matplotlib/axes/_axes.py in scatter(self, x, y, s, c, marker, cmap, norm, vmin, vmax, alpha, linewidths, verts, edgecolors, **kwargs)
   4226                     valid_shape = False
-> 4227                     raise ValueError
   4228             except ValueError:

ValueError: 

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-29-c0e8bf06937e> in <module>()
----> 1 sc.pl.paga(adata,color=['louvain','ID'])

~/bin/miniconda3/lib/python3.6/site-packages/scanpy/plotting/tools/paga.py in paga(adata, threshold, color, layout, layout_kwds, init_pos, root, labels, single_component, solid_edges, dashed_edges, transitions, fontsize, fontweight, text_kwds, node_size_scale, node_size_power, edge_width_scale, min_edge_width, max_edge_width, arrowsize, title, left_margin, random_state, pos, cmap, cax, colorbar, cb_kwds, frameon, add_pos, export_to_gexf, use_raw, colors, groups, show, save, ax)
    396             single_component=single_component,
    397             arrowsize=arrowsize,
--> 398             pos=pos)
    399         if colorbars[icolor]:
    400             bottom = panel_pos[0][0]

~/bin/miniconda3/lib/python3.6/site-packages/scanpy/plotting/tools/paga.py in _paga_graph(adata, ax, layout, layout_kwds, init_pos, solid_edges, dashed_edges, transitions, threshold, root, colors, labels, fontsize, fontweight, text_kwds, node_size_scale, node_size_power, edge_width_scale, title, pos, cmap, frameon, min_edge_width, max_edge_width, export_to_gexf, cax, colorbar, use_raw, cb_kwds, single_component, arrowsize, random_state)
    746         sct = ax.scatter(
    747             pos_array[:, 0], pos_array[:, 1],
--> 748             c=colors, edgecolors='face', s=groups_sizes, cmap=cmap)
    749         if fontsize is None:
    750             fontsize = rcParams['legend.fontsize']

~/bin/miniconda3/lib/python3.6/site-packages/matplotlib/__init__.py in inner(ax, data, *args, **kwargs)
   1803                         "the Matplotlib list!)" % (label_namer, func.__name__),
   1804                         RuntimeWarning, stacklevel=2)
-> 1805             return func(ax, *args, **kwargs)
   1806 
   1807         inner.__doc__ = _add_data_doc(inner.__doc__,

~/bin/miniconda3/lib/python3.6/site-packages/matplotlib/axes/_axes.py in scatter(self, x, y, s, c, marker, cmap, norm, vmin, vmax, alpha, linewidths, verts, edgecolors, **kwargs)
   4232                         "acceptable for use with 'x' with size {xs}, "
   4233                         "'y' with size {ys}."
-> 4234                         .format(nc=n_elem, xs=x.size, ys=y.size)
   4235                     )
   4236                 # Both the mapping *and* the RGBA conversion failed: pretty

ValueError: 'c' argument has 14 elements, which is not acceptable for use with 'x' with size 4, 'y' with size 4.

It seems that there are something wrong with the cmap parameter of matplotlib's plt.scatter() function. please refer to this issue:
https://github.com/matplotlib/matplotlib/issues/11919

**Comment by falexwolf** [comment]
Did you recompute using `tl.paga` in between?

You're passing something from the 14 cluster calculation to the 4-cluster call, as is evident from 
> 'c' argument has 14 elements, which is not acceptable for use with 'x' with size 4, 'y' with size 4.

It has nothing to do with anything in matplotlib.

If the docs aren't clear enough, please let me know.

**Comment by wangjiawen2013** [comment]
Thanks, I rerun my data, and paga works well now. I don't know what happened yesterday.

**Comment by falexwolf** [comment]
Good to read!

**Comment by wangjiawen2013** [comment]
I think I find the reason. When run sc.tl.louvain(adata), louvain_colors will be saved in adata.uns, sc.pl.paga will use louvain_colors. But, when run sc.tl.louvain(adata) again with another resolution and then rerun sc.tl.paga, louvain_colors will not be updated, and the error occurs!

**Comment by wangjiawen2013** [comment]
And leiden_colors has the same case.

**Comment by SamueleSoraggi** [comment]
I had the same issue and was suggested to use the 'palette' options.
colours will not change when you get less clusters than the time before!

tir. 22. jan. 2019 5.06 AM skrev jiawen wang <notifications@github.com>:

**Comment by falexwolf** [comment]
Oh, thank you for sharing the reason! This was indeed a bug. It's fixed here: https://github.com/theislab/scanpy/commit/9ee2ac25c1df171286beffdcc835567e8cf00e7f
