### ISSUE TITLE
Automatic gene symbols lookup in plotting

### ISSUE THREAD

**Issue by falexwolf** [scverse/scanpy#385]
In plotting functions: Why not automatically lookup gene symbols from `.var['gene_symbols']` if it's  present? Then we don't have to add and check for a `gene_symbols` parameter everywhere...

**Comment by LuckyMD** [comment]
While I think this is a good idea for most applications there are a few issues I see with this:

1. As far as I'm aware there is no other functionality that automatically looks for a column in `.var` or `.obs` that doesn't have a matching function that puts that column there. So here you would rely on the user to spell `'gene_symbols'` exactly as you expect without the user necessarily knowing that the functions are looking for this.
2. There are cases where someone may want to plot other IDs than gene symbols even when that person has gene symbols stored (For example: isoform expression)

For this to work, I think one would need a `sc.pp.store_gene_symbols()` function. However, then you end up with functions for everything which makes the whole thing more complicated than it should be. Also, you would need to be able to turn the gene symbol lookup off. In that case you have the same number of parameters compared to just adding a `gene_symbols` parameter.

**Comment by grst** [comment]
Personally, I don't like it because
* Explicit is better than implicit
* there could be cases where I would like to plot Ensembl/Entrez or whatever identifier I have in `var_names` directly, even if I have a `gene_symbols` column available.

**Comment by falexwolf** [comment]
Addressing a few issues:
- The convention that gene symbols should be stored as `'gene_symbols'` would be broadly advertised in the docs. It's the convention used by `read_10x_h5` and `read_10x_mtx` already.
- The parameter `gene_symbols` would still exist but would rarely be used. If used, it can be used to point to the index and to arbitrary fields. But its default value `gene_symbols=None` would trigger lookup of a column `'gene_symbols'` if it exists, and lookup of the index if it doesn't. That's the same behavior as for `.raw`.

There would not be any additional function.

**Comment by grst** [comment]
That sounds good. On the other hand, do we need all that if the argument `gene_symbols` exists anyway?

**Comment by LuckyMD** [comment]
I wasn't aware of `read_10x_h5` creating a `.var['gene_symbols']` column. In that case it's quite an elegant solution for people who read in 10x data directly. There will probably be more people who use `read_10x_h5` and `read_10x_mtx` than people who do not want to plot gene symbols. In that case I guess the convenience of the many outweighs the needs of the few.

Maybe output something to say that the `gene_symbols` column in `var` is being used for plotting when it is found. Then it's not like some magic is happening in the background of which the user is ignorant.

**Comment by ivirshup** [comment]
Should the scatter plots accept `gene_symbols`? I'd like to not have to reset my `var_names` to have easy marker plotting. However, I could imagine namespace issues between `adata.obs.columns` and gene symbols, especially for programatic usage.

**Comment by falexwolf** [comment]
I guess this should be clarified with your PR, @ivirshup, right?

**Comment by ivirshup** [comment]
Yeah, I decided just to go for it 🤠. I'd be happy to update the code if there ends up being a `gene_symbols` flag.

**Comment by falexwolf** [comment]
Thank you! That's the way to go! 😎

**Comment by ivirshup** [comment]
Oops, mis-click. However, I feel like this has been resolved?

**Comment by flying-sheep** [comment]
Seems like it!
