### ISSUE TITLE
Adopt colorblind-friendly default color cycle

### ISSUE THREAD

**Issue by flying-sheep** [scverse/scanpy#387]
Matplotlib 3 came and went without https://github.com/matplotlib/matplotlib/issues/9460 being fixed. @ftheis still can’t properly distinguish clusters made by scanpy.

The two designated colorblind-friendly colormaps in matplotlib look [like this](https://gist.github.com/flying-sheep/5172a1f1f9757d4ece239e742ba41b08). An alternative would be to push red or green to the end of the current color cycle, so it only appears for 10+ clusters.

@mpetroff created a [neat tool](https://colorcyclepicker.mpetroff.net/) that could help to design a custom one if we decide the available ones are too ugly.

**Comment by falexwolf** [comment]
We're using a custom color map in scanpy by default, anyways: https://github.com/theislab/scanpy/blob/master/scanpy/plotting/palettes.py#L22.

It would, of course, be easy to change this, but then everything changes for everyone and many people will wonder why everything looks different now ("where is my green cluster?"). If we do it, we only exchange green with another color, so that at least all other colors will be unaffected...

I would have liked to wait until a major update, because I consider this breaking backward consistency, though...

**Comment by fidelram** [comment]
I am partial color blind as well. So I second any initiative in this
direction.

**Comment by flying-sheep** [comment]
I don’t consider this breaking backwards compatibility. Everything is still in the same place, still has the same labels. Only the default color of the labels is different.

If we only switch the green or red color with another, most people won’t even notice.

**Comment by ftheis** [comment]
> I don’t consider this breaking backwards compatibility. Everything is still in the same place, still has the same labels. Only the default color of the labels is different.
> 
> If we only switch the green or red color with another, most people won’t even notice.

how about making green just a bit brighter/less bright to make it discernible from red for color-blind people? should not break much
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

---
Fabian Theis
Institute of Computational Biology - http://icb.helmholtz-muenchen.de
Helmholtz Zentrum München and Depts. Mathematics&Life Sciences, TU München

Helmholtz Zentrum Muenchen
Deutsches Forschungszentrum fuer Gesundheit und Umwelt (GmbH)
Ingolstaedter Landstr. 1
85764 Neuherberg
www.helmholtz-muenchen.de
Aufsichtsratsvorsitzende: MinDirig.in Petra Steiner-Hoffmann
Stellv.Aufsichtsratsvorsitzender: MinDirig. Dr. Manfred Wolter
Geschaeftsfuehrer: Prof. Dr. med. Dr. h.c. Matthias Tschoep, Heinrich Bassler, Dr. rer. nat. Alfons Enhsen
Registergericht: Amtsgericht Muenchen HRB 6466
USt-IdNr: DE 129521671

**Comment by LuckyMD** [comment]
> how about making green just a bit brighter/less bright to make it discernible from red for color-blind people? should not break much

I guess that would be best done by switching the green with another green somewhere down the list to not mess with the color map entirely. Not sure this is a general purpose fix for all types of colorblindness though, no?

**Comment by flying-sheep** [comment]
try it yourself :smile: https://addons.mozilla.org/de/firefox/addon/let-s-get-color-blind/

**Comment by falexwolf** [comment]
I'm fine with such rather small changes. This should indeed not bother people. Tell me when you decided on a green that satisfies @ftheis. We don't want to make this change multiple times... :wink:

**Comment by flying-sheep** [comment]
Some colors of that cycle are too close for people with deuteranomaly (by far the most common type):

`#1f77b4` `#ff7f0e` `#2ca02c` `#d62728` `#9467bd` `#8c564b` `#e377c2` `#7f7f7f` `#bcbd22` `#17becf`

Normal | Deuteranomaly
--- | ---
![Normal](https://user-images.githubusercontent.com/291575/49573631-6605b380-f936-11e8-9629-68b177e59043.png) | ![Deuteranomaly](https://user-images.githubusercontent.com/291575/49573600-52f2e380-f936-11e8-9729-67ec0dde0aaf.png)

- red and green
- blue and purple
- orange and kakhi

Playing around a bit, it’s easy to get a version that works, e.g.

`#1f77b4` `#ff7f0e` `#279e68` `#d62728` `#aa40fc` `#8c564b` `#e377c2` `#7f7f7f` `#b5bd61` `#17becf`

Normal | Deuteranomaly
--- | ---
![Normal](https://user-images.githubusercontent.com/291575/49574129-926dff80-f937-11e8-8fad-58e89cceebf0.png) | ![Deuteranomaly](https://user-images.githubusercontent.com/291575/49574155-a285df00-f937-11e8-84ba-c1b1ae28ee99.png)

I think the changes are subtle enough that we *can* adopt it now and change it a little later if we want.

**Comment by ftheis** [comment]
thanks Phil - as discussed before can you just change the red and green i.e. #ff7f0e #2ca02c which look virtually the same to people with deuteranomaly (incl me) by the two colors you suggested?

> Am 06.12.2018 um 10:17 schrieb Philipp A. <notifications@github.com>:
> 
> Some colors of that cycle are too close for people with deuteranomaly (by far the most common type):
> 
> #1f77b4 #ff7f0e #2ca02c #d62728 #9467bd #8c564b #e377c2 #7f7f7f #bcbd22 #17becf
> 
> Normal	Deuteranomaly
> 	
> 	• red and green
> 	• blue and purple
> 	• orange and kakhi
> Playing around a bit, it’s easy to get a version that works, e.g. #1f77b4 #ff7f0e #279e68 #d62728 #aa40fc #8c564b #e377c2 #7f7f7f #b5bd61 #17becf
> 
> Normal	Deuteranomaly
> 	
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

---
Fabian Theis
Institute of Computational Biology - http://icb.helmholtz-muenchen.de
Helmholtz Zentrum München and Depts. Mathematics&Life Sciences, TU München

Helmholtz Zentrum Muenchen
Deutsches Forschungszentrum fuer Gesundheit und Umwelt (GmbH)
Ingolstaedter Landstr. 1
85764 Neuherberg
www.helmholtz-muenchen.de
Aufsichtsratsvorsitzende: MinDirig.in Petra Steiner-Hoffmann
Stellv.Aufsichtsratsvorsitzender: MinDirig. Dr. Manfred Wolter
Geschaeftsfuehrer: Prof. Dr. med. Dr. h.c. Matthias Tschoep, Heinrich Bassler, Dr. rer. nat. Alfons Enhsen
Registergericht: Amtsgericht Muenchen HRB 6466
USt-IdNr: DE 129521671

**Comment by flying-sheep** [comment]
I just changed one color in each of the named pairs (i.e. the green, the purple, and the kakhi). Are the swatches in the lower pictures distinguishable for you? Then the mathematical model for color closeness matches your vision and we should adopt something like it.

**Comment by LuckyMD** [comment]
@ftheis So `#ff7f0e` and `#2ca02c` is the problem, rather than `#d62728` and `#2ca02c`? The `#ff7f0e` is an orange which appears distinguishable from the rest (except `#b5bd61`) in the deuteranomaly simulated colours above.

**Comment by flying-sheep** [comment]
when you use the firefox extension I quoted above, you’ll see that the orange and green are very similar for people with *protanomaly*, not deuteranomaly. so i guess fabian has the former, more rare thing. confirmed by fabian and the simulation, my changed colors seem to work well for both types.

so I assume the webtool can be used to design this. the only change from default in the parameters I made was that i removed the minimum lightness distance (making the colors not suited for completely color blind people, but having no cone cells, their vision is probably too bad to see our plots anyway.)

PS: please use backticks around colors, like `#fe57a1` so we can see little swatches on github! I edited your post for this @LuckyMD

**Comment by LuckyMD** [comment]
cool... I didn't know backticks made that possible.

**Comment by flying-sheep** [comment]
Fixed in 58fae77cc15893503c0c34ce0295dd6f67af2bd7

![grafik](https://user-images.githubusercontent.com/291575/49696239-acae1480-fba7-11e8-8801-10c9ac825481.png)
