### ISSUE TITLE
vmin, vmax kwargs are ignored by sc.pl.dotplot()

### ISSUE THREAD

**Issue by timrandg** [scverse/scanpy#388]
First, very nice job on this package! It is a welcome replacement to seurat for python programmers! Yay!

I have a suggestion to improve sc.pl.dotplot().

I would like to be able to adjust the limits of the color_map used for sc.pl.dotplot(). The documentation states that kwargs get passed to matplotlib.pyplot.scatter(). But the dotplot does not change when vmin and vmax are included as kwargs. In the source code for anndata.dotplot includes the following lines:

    import matplotlib.colors
    normalize = matplotlib.colors.Normalize(vmin=min(mean_flat), vmax=max(mean_flat))
    colors = [cmap(normalize(value)) for value in mean_flat]

I believe these lines are the issue. Because vmin and vmax are calculated from the mean_flat variable the vmin and vmax provided as parameters are ignored. Perhaps rather than determining the scale using mean_flat, the vmin and vmax should be used when provided by the user. This would allow the user to set the color_bar scale as they need. Currently, there is no way to change the color_bar and the documentation is misleading, since it suggests that it can be done.

**Comment by timrandg** [comment]
Here is a patch that fixes the above problem...

    import matplotlib.colors

    #if user defined, then use the vmax, vmin keywords, else use data to generate them...
    if ('vmax' in kwds) and ('vmin' in kwds):
        _vmax = kwds['vmax']
        _vmin = kwds['vmin']
    else:    
        _vmax = max(mean_flat)
        _vmin = min(mean_flat)    

    #normalize = matplotlib.colors.Normalize(vmin=min(mean_flat), vmax=max(mean_flat))    
    normalize = matplotlib.colors.Normalize(vmin=_vmin, vmax=_vmax)

I'll submit a pull request.

**Comment by fidelram** [comment]
The change is quite useful. Please go ahead and add a PR.

**Comment by timrandg** [comment]
Hi Fidel,
Please note new pull request
dotplot can take vmin vmax arguments from user
<https://github.com/theislab/scanpy/pull/390>
Tim

**Comment by timrandg** [comment]
mmmm...
looks like there are some difficulties here.
The decorator sitting ontop of dotplot() causes a weird error for kwds
dictionary lookups. If I leave the decorator in place, then I get a
keywords error when, vmin is left out as a parameter. If I take the
decorator off the method, it works. error is coming from the

@doc_params()

decorator. But 1. it looks like this function only purpose in life it to
ensure that the __doc__ string starts with a '\' character. And in the case
of dotplot() it already does. When I comment out the decorator, the code
works.

This error is too strange for me to understand. I don't often use
decorators, and it seems to be the problem here.
Tim

**Comment by timrandg** [comment]
mmmm #2...
The previous email regarding decorator issue, may have been a problem from
namespace shadowing in a jupyter notebook. I think the previous pull
request works--but suggest testing with and without vmin vmax arguments.
I'll update you as I do more testing myself.
Tim

**Comment by falexwolf** [comment]
`@doc_params` is used to add keyword argument descriptions that are shared among many functions to a specific docstring. it has so far not posed any problems. In the case of `dotplot`, it adds, e.g., the `{common_plot_args}`.

**Comment by timrandg** [comment]
Yes, sorry about the confusion--I reneged the post about the decorator
(@doc_params). So I believe the pull request improves the dotplot function.
Tim
