### ISSUE TITLE
Plot of ranking genes does not accept 'ncols' graphical option

### ISSUE THREAD

**Issue by SamueleSoraggi** [scverse/scanpy#389]
Hej,
I have a minor plotting issue.

when using the following command `sc.pl.rank_genes_groups(all_data, n_genes=20, sharey=True, ncols=5)`, I cannot get the subplots in groups of five panels on each row, even though this option is present in the documentation :)

It might be that it needs a fix.

Cheers,
Samuele

**Comment by falexwolf** [comment]
Hm, the [code](https://github.com/theislab/scanpy/blob/21adc0c9a31fb1eebb16579aa4f41700bc939aa2/scanpy/plotting/tools/__init__.py#L180-L188) for this looks fine: do you have less than 5 groups?
```
n_panels_x = min(n_panels_per_row, len(group_names))
```

**Comment by fidelram** [comment]
It is working fine for me and is part of the testing. Which version do you
have? maybe you need to use `n_panels_per_row`.

**Comment by SamueleSoraggi** [comment]
It was indeed that. Sorry for the long time for checking, I forgot about it (Christmas holiday party effect).
