### ISSUE TITLE
colouring of highly variable genes on pl.filter_genes_dispersion

### ISSUE THREAD

**Issue by jcamunas** [scverse/scanpy#39]
I was trying to reproduce the results in Example 1 on notebook
https://github.com/theislab/scanpy_usage/tree/master/170505_seurat

I'm getting two problems in the filtering steps in cell 9:
1) although genes seem to be filtered (there are 1838 genes left versus 13714 before), the plot does not show a different colour for 'highly variable' and 'other' genes. Both appear black (see attached figure). I've both tried it in a jupyter notebook and ipython. I'm running python in a conda environment with matplotlib 4.3.2.25.py35_0 and seaborn 0.8_py35

2) There's also the following warning message, that seems to complain of a divide by zero on the mean:
/anaconda/lib/python3.5/site-packages/scanpy/preprocessing/simple.py:193: RuntimeWarning: invalid value encountered in true_divide
  dispersion = var / mean
Is 
![figure_10](https://user-images.githubusercontent.com/10065683/30990958-f0e3dec6-a457-11e7-9921-f1b6b9f72861.png)

Thanks!

**Comment by falexwolf** [comment]
Hi and sorry for the very late response!

1. Hm, this seems to be related to your matplolib version and I've never seen this before. The code for the plotting function is [here](https://github.com/theislab/scanpy/blob/a17e9f4bac124547fec1c373da8d12b679c84bcc/scanpy/plotting/preprocessing.py#L11-L46). Try installing matplotlib 2.0.0.

2. The warning can be ignored, in my experience. Soon, we'll catch that case explicitly.

**Comment by jcamunas** [comment]
using matplotlib 2.0 solves the issue. thanks!

**Comment by falexwolf** [comment]
Cool! :)
