### ISSUE TITLE
`rank_genes_groups_gene_names` is no longer here.

### ISSUE THREAD

**Issue by flying-sheep** [scverse/scanpy#392]
correlation_matrix:

https://github.com/theislab/scanpy/blob/21adc0c9a31fb1eebb16579aa4f41700bc939aa2/scanpy/tools/top_genes.py#L58

exploratory_rank_analysis:

https://github.com/theislab/scanpy/blob/02e78bb025f9cd8d02cf6d39256fea008ec51d7f/scanpy/plotting/top_genes_visual.py#L109

also correlation_matrix is not included in the docs, and the recommendations alex made on 573519e524815fd2c227c876da26e283939a3012 aren’t implemented.

generally, please don’t just commit low quality and unfinished code to master @tcallies. that’s what PRs are for.

**Comment by falexwolf** [comment]
Both of these modules are not in the docs and not referenced in any tutorial and I never considered them mature code... I always planned on fixing these... but my bandwidth for this is limited...

I should not have merged them into master, that's my fault... Won't happen again...

**Comment by flying-sheep** [comment]
Oh, there was a PR? I missed that. I thought it was just committed directly to master.

I think it’s even OK to merge in unstable functions as long as we don’t reexport them in `scanpy.api`.
