### ISSUE TITLE
Paga coordinates from phate plot

### ISSUE THREAD

**Issue by PattF** [scverse/scanpy#395]
Is there a way to plot a paga plot based off the coordinates from a phate plot?
No issue in doing it from an fa plot, just wondering if its possible from a phate plot as well?

**Comment by falexwolf** [comment]
You should be able to call `paga_compare(adata, basis='phate')`. Let me know if there are problems with this.

**Comment by PattF** [comment]
Perfect, that worked great!
I'll close the thread.
