### ISSUE TITLE
Dot plot scaling issue/request

### ISSUE THREAD

**Issue by a-munoz-rojas** [scverse/scanpy#396]
It would be great to be able to adjust the frequency scale of the dot size to the min-max values of the data set, instead of 0-100% of total cells. This is particularly important to visualize expression of genes that is rare in some subpopulations, that are otherwise impossible to see because the dots are too small. As a side note, Seurat does this scaling automatically and it works well. Thanks!

**Comment by fidelram** [comment]
Can you give me a visual example of what you want to see if I am following
you?

**Comment by a-munoz-rojas** [comment]
Sure - this is an output from a Seurat analysis. You can see that the scale of the dot size goes from 10% to 60%, such that the group with 60% expressing cells is scaled to the max dot size:

<img width="246" alt="pastedgraphic-3" src="https://user-images.githubusercontent.com/37122760/50017697-d9dd3700-ff9a-11e8-8c28-fb6cd7f064e7.png">

As a comparison, this is a (different) output from scanpy that automatically scales to 100% and causes the dots to be too small:
![dotplotex](https://user-images.githubusercontent.com/37122760/50019765-df8a4b00-ffa1-11e8-9b49-30d5057898bb.png)

Please let me know if this makes sense!

**Comment by fidelram** [comment]
Thanks, now is becoming clearer. Can you specify the maximum percentage
value or this is taken from the data?

What would be a nice name for a parameter to add to the function?
`max_fraction` ?

I would not be able to work on this for the next days but at least we can
throw some ideas. The change is the code is probably quite simple.

**Comment by a-munoz-rojas** [comment]
The maximum percentage value is automatically taken from the data, and the Seruat function also has parameters to let the user scale these values (similar to vmin and vmax for heatmaps). I think it would be nice to have this option in this function as well.

For parameter names, a suggestion could be 'dot_min' and 'dot_max'. Maybe it would be best if the default behavior is to scale automatically to the max and min values in the data plotted (default such that dot_min and dot_max=None). This way the user can specify specific values if they want (0% to 100% for example), but otherwise the scale should be proportional to their data.

Let me know what you think!

**Comment by fidelram** [comment]
PR #401 addresses the issue. I would be great if you can give it a try.

**Comment by falexwolf** [comment]
The PR is merged, so I'm closing this issue.

**Comment by a-munoz-rojas** [comment]
Sorry I forgot to reply! I gave it a quick try and it looked great. Thank you very much Fidel!
