### ISSUE TITLE
annotating anndata object with clusters and tnse info from .csv file

### ISSUE THREAD

**Issue by manarai** [scverse/scanpy#399]
Dear,

Thanks for this fantastic package. I saved one of my analysis to get .csv files output using the cmd adata.write_csv('./ouput').  I modified some of these files (the obs.csv and obsm) for pecific purposes related to a collaborative project while respecting the dimensions and the order of the cells. How can I reload back these files into an anndata object? 

adata = sc.read_csv('./ouput/*') ??

**Comment by flying-sheep** [comment]
[The documentation for `AnnData.write_csvs`](https://anndata.readthedocs.io/en/latest/anndata.AnnData.write_csvs.html) tells you

> It is not possible to recover the full AnnData from the output of this function. Use write() for this.

Sorry for that! We thought that not having a function to read back those CSVs, we won’t lull people into the false security that the AnnData object can be safely restored from CSVs.

But if you have nothing else but those files, you can of course try to use [`pandas.read_csv`](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html) to read the `.obs` and `.var` dataframes and do something like

```py
adata = AnnData(
    pd.read_csv('output/X.csv').asarray(),
    pd.read_csv('output/obs.csv'),
    pd.read_csv('output/var.csv'),
    { # adata.uns
        'some_thing': pd.read_csv('output/some_thing.csv'),
    },
    pd.read_csv('output/obsm.csv'),
    pd.read_csv('output/varm.csv'),
)
```

You might have to fiddle with parameters to `pandas.read_csv`, like `index_col`, and obsm/varm might not be able to be specified as data frames.

**Comment by manarai** [comment]
From a gene matrix, tsne and cluster .csv files obtained from cell ranger output I was able to load these into scanpy and display a tsne plot that look exactly like the output of cellranger cloupe file. This is great thanks!

![screen shot 2018-12-18 at 14 32 39](https://user-images.githubusercontent.com/39877296/50134113-eaaae700-02d1-11e9-96db-8c2a3393724b.png)
