### ISSUE TITLE
Allow plotting genes not used in a dimension reduction

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/scanpy#41]
Looking forward to plot genes that are not used in pca/tsne analysis while exist in the raw data!

**Comment by falexwolf** [comment]
OK! We will try to add this as soon as possible.

Currently, you can work around this by adding all genes that you find interesting as annotation, for example, following code similar to
```
    # TC (Nat Im review 2014 Yui)
    tc_surface_receptors = ['Flt3', 'Cd44', 'Il2ra', 'Il7r', 'Cd3e', 'Cd4', 'Cd8a']
    tc_markers = [
        'Gata2', 'Hoxa9', 'Meis1', 'Lmo2', 'Mef2c', 'Gfi1b', 'Lyl1', 'Spi1', 'Bcl11a', 'Hhex', 'Mycn', 'Erg', 'Tcf3',
        'Ikzf1', 'Tcf12', 'Notch1', 'Runx1', 'Gfi1', 'Myb', 'Myc', 'Gata3', 'Tcf7', 'Ets1', 'Hes1', 'Ahr', 'Tcf12',
        'Bcl11b', 'Notch3', 'Spib', 'Ets2', 'Lef1', 'Rorc', 'Id3',
    ]
    # DC, NK (Abcam poster)
    dc_markers = ['Itgax', 'Cd24a', 'Ptprc']
    nk_markers = ['Itgam', 'Il2rb', 'Klrb1', 'Ncr1']
    all_markers = tc_surface_receptors + tc_markers + dc_markers + nk_markers
    adata.smp[all_markers] = adata[:, all_markers].X
```

**Comment by wangjiawen2013** [comment]
Do you plan to publish scanpy on a high impact factor journal later? Some people argue that bioAxiv is not a serious journal and we are a little worried. After all, it will take us much time to follow scanpy.

**Comment by falexwolf** [comment]
Scanpy will very soon be published in a high impact journal (we're currently in the revision). I'll let you know about this.

**Comment by falexwolf** [comment]
We're still hesitant about making AnnData more complex, for these reasons:
* It is not inefficient to load multiple versions of the full data into AnnData.
* It is not straightforward to determine the point of the preprocessing at which one would want to save a version of the raw data (probably after filtering out cells and taking the logarithm, but this might change in the future).
As the second point implies that some manual intervention would be necessary, anyway, we tend to leave it to the user to keep track of one, two or more versions of the data; each with annotations that can easily be exchanged.

Specifically, would you be happy to proceed as in differential expression tests, see e.g., https://github.com/theislab/scanpy_usage/blob/master/170505_seurat/seurat.ipynb? You keep track of two versions of the data, one for doing all the machine learning inference and another one for doing statistics and plotting.

Using the linked example: for plotting, you would simply need to add the visualization basis to the AnnData that stores the raw data. Then you call `sc.pl.tsne`.
```
adata_corrected = sc.read('pbmc3k_corrected')
adata_raw = sc.read('pbmc3k_filtered_raw_log')
adata_raw.smpm['X_tsne'] = adata_corrected.smpm['X_tsne']
adata_raw.smpm['X_pca'] = adata_corrected.smpm['X_pca']
sc.pl.tsne(adata_raw, color='NKG7')
```

**Comment by falexwolf** [comment]
Finally, we could solve this elegantly without sacrificing a scalable design, as shown in the [tutorial](https://github.com/theislab/scanpy_usage/blob/master/170505_seurat/seurat.ipynb).

Also, Scanpy is accepted in Genome Biology and will soon be published.

Merry Christmas! :)
  Alex

**Comment by wangjiawen2013** [comment]
Can you extend scanpy functions so that I can show gene expression level on plot generated by sc.pl.diffmap? just like that monocle2 does.

**Comment by wangjiawen2013** [comment]
And, in which step should I execute MNN batch effect correction ? Is it still necessary to regress out some variables ( n_counts, percent_mito et al.,) when I execute MNN ?

**Comment by maximilianh** [comment]
Sorry, how does Monocle do it? Do you have a link to an example?

**Comment by falexwolf** [comment]
Is clarified in https://github.com/theislab/scanpy/issues/168.

**Comment by maximilianh** [comment]
Oh so wangjiawen2013 means to color in genes that were not filtered out? I see that makes sense. I was wondering if monocle can color by multiple genes in the same plot, but apparently I was completely on the wrong track here.
