### ISSUE TITLE
Message from highly_variable_genes

### ISSUE THREAD

**Issue by SamueleSoraggi** [scverse/scanpy#411]
Hi,

when using the command 
```python
sc.preprocessing.highly_variable_genes.highly_variable_genes(all_data,n_top_genes=5000)
```

I get this informative message:
```
--> added
    'highly_variable', boolean vector (adata.var)
    'means', boolean vector (adata.var)
    'dispersions', boolean vector (adata.var)
    'dispersions_norm', boolean vector (adata.var)
```

Even though not all of them are booleans! I guess it is just a copy-paste residue from implementation :)
Cheers,
Samuele

**Comment by falexwolf** [comment]
Thank you! Fixed via https://github.com/theislab/scanpy/commit/9c1bc7e0b565727530487d6067a0711c76fac549.
