### ISSUE TITLE
to_df method does not appear to be working correctly

### ISSUE THREAD

**Issue by cornhundred** [scverse/scanpy#417]
I'm trying to export a Pandas DataFrame from the adata object using the example notebook pbmc3k and I'm getting a weird result shown below: 

<img width="1079" alt="screen shot 2019-01-09 at 3 52 51 pm" src="https://user-images.githubusercontent.com/8352840/50927784-d1a3da80-1426-11e9-9b01-fef15bdf2e2d.png">

I could not find documentation on the `to_df` method in the documents.

**Comment by cornhundred** [comment]
I think I figured it out, just had to convert the matrix (`adata.X`) todense in order to get the DataFrame I wanted:  
<img width="1102" alt="screen shot 2019-01-09 at 4 09 20 pm" src="https://user-images.githubusercontent.com/8352840/50928530-f00ad580-1428-11e9-97f3-37cd6aa8b4d6.png">

I'm trying to export a DataFrame for use with [clustergrammer2](https://github.com/ismms-himc/clustergrammer2). See example notebook on nbviewer: https://nbviewer.jupyter.org/github/ismms-himc/scanpy-batch-correct/blob/export_df/notebooks/1.0_Batch_Correction_Example.ipynb

Is there a way to export a dense DataFrame directly from adata?

**Comment by falexwolf** [comment]
Thank you for pointing out that bug.

It's fixed here: https://github.com/theislab/anndata/commit/2d11f9fb1cb9059a178c7d11ffa595b49b742342

Documentation is here: https://anndata.readthedocs.io/en/latest/anndata.AnnData.to_df.html
