### ISSUE TITLE
Plotting ax and figure manipulation, e.g. fig.tight_layout() and other related workflow issues.

### ISSUE THREAD

**Issue by Xparx** [scverse/scanpy#418]
scanpy version 1.3.7

NOTE!: During typing this issue out i figured out how to solve it and save figures with all elements showing with the help of 
`fig1.savefig("name.svg" bbox_inches='tight')`, which solves 90% of the issue I had. I also noticed that these functions have a built in save function where I found the answer. I added a question at the bottom which is still of interest to me. However, feel free to rank this as non essential.
--------------------------------------

First of all, the new figure plotting functions looks amazing.
I just have a few issues that I hope I can get some help with.
I seem to often get the behavior of figures from scanpy after I plot that the elements like xtick labels and other important features are hidden due to figure boarders or that boarders are extended far beyond the plotting are. Due to the way the axes is constructed I can't simply do a fig.tight_layout(). Even with the grid_spec specific tight_layout https://matplotlib.org/users/tight_layout_guide.html#use-with-gridspec I get the same result.
I get the sense that the figures looks ok in a notebook, perhaps, where these elements can be seen, but that does unfortunate not translate to my workflow of manually saving figures and plotting with qt or tk backends to be able to get a quick overview.

Below is an example of a fig.savefig("test.png")
for the command
```
sc.pl.matrixplot(adata, var_names=genes_ranked_by_loading_in_PC[:topg], groupby='hpf', use_raw=None, cmap='RdBu_r', swap_axes=True)
```
![test](https://user-images.githubusercontent.com/715716/50937406-77644300-1441-11e9-8713-8bebdf94c26b.png)

The over extending bounders can't be seen here due to the white background but the missing x-tics are clear. (Note I realized how to at least save figures with a 'tight' bounding box so that issue is solved.)

Q: Is it possible to get an interactive figure (as in plotting with qt or tk) where elements are visible as with fig.tight_layout() for ordinary axes using your plotting functions? @fidelram tagging you here as I assume you might be able to know this.

**Comment by fidelram** [comment]
@Xparx Thanks for reporting the problem an a potential solution. 

Each plotting function has a save parameter which does:
```
pl.savefig(filename, dpi=dpi, bbox_inches='tight')
```
So, instead of calling `fig.savefig()`, what you can do in your example is to add `save='test.png'`:

```
sc.pl.matrixplot(adata, save='test.png', var_names=genes_ranked_by_loading_in_PC[:topg], groupby='hpf', use_raw=None, cmap='RdBu_r', swap_axes=True)
```

**Comment by falexwolf** [comment]
Cool! :smile:

The only thing to add to this, you can change the directory where you want figures to end up here: https://scanpy.readthedocs.io/en/latest/api/index.html#settings

**Comment by Xparx** [comment]
Didn't know about the setting settings! I will try to use that.  I noticed the `save` figure argument but couldn't connect it to saving where I wanted and how to incorporate it in to my workflow. With the settings functionality it is probably doable. 
Thanks for your responses.
