### ISSUE TITLE
All plotting functions could return an ax and/or fig handle.

### ISSUE THREAD

**Issue by Xparx** [scverse/scanpy#419]
scanpy version 1.3.7,

I noticed that some figures does not return an ax handle.
Specifically rank_genes_groups_heatmap does not return an axis becouse _rank_genes_groups_plot does not return an axis from the matrix plot. Only tracksplot and stacked_violin seems to return an axis in [_rank_genes_groups_plot](https://github.com/theislab/scanpy/blob/master/scanpy/plotting/_tools/__init__.py#L258).

Also I'm wondering why not all plotting functions return an axes handle (list) always.
It's easy to capture in a variable if not wished to print to screen and easier to keep track of than having to both capture and determine the show=False state, and it would mirror behavior of other figure packages. Any specific reason you do not do this?

**Comment by fidelram** [comment]
All plotting functions should return an ax or an ax list if `show=False`.   `_rank_genes_groups_plot` returns whatever the internally called function returns (which could be tracksplot or heatmap etc). However, I don't recall testing this output in all cases. 

Can you provide a non working example using the test data? Here you can see how to use one of the test datasets: https://scanpy-tutorials.readthedocs.io/en/latest/visualizing-marker-genes.html

I think that @falexwolf can comment on the original reason to set `show=False` to return the axes. 

I agree with @Xparx that is more standard to always return the axes as you usually don't dig into the parameter list for this functionality.  However, changing this behaviour now could break some code so I don't know if the benefits are greater than the drawbacks.

**Comment by Xparx** [comment]
Hi thinks for the answer and thanks for the link on the test data and visualization, I will try to use that going forward.

I will cook up a non working example if needed, however just looking at the code https://github.com/theislab/scanpy/blob/master/scanpy/plotting/_tools/__init__.py#L302 there is missing return statements for a few of the plotting functions in the `_rank_genes_groups_plot` unless I missed something they will then not return an axes?

The [heatmap]( https://github.com/theislab/scanpy/blob/master/scanpy/plotting/_anndata.py#L1044) function itself return an axis but there is no return statement from the `_rank_genes_groups_plot`.

**Comment by fidelram** [comment]
I will take a look.

**Comment by falexwolf** [comment]
Hey! Thank you for the thoughtful considerations!

Yes, by default, Scanpy plotting functions return `None`, other than in other packages. Scanpy's plotting should be seen as being even more high-level, than, say Seaborn. A single one-line function call should display a publication-quality visualization in a notebook and no ugly string representation of a returned Axes should clutter the output. This is why `settings.autoshow` defaults to `True` and any plotting function automatically calls `pl.show()`, other than Seaborn... If you don't want that, you can either pass `show=False` in the function or globally set [`settings.autoshow=False`](https://scanpy.readthedocs.io/en/latest/api/index.html#settings). In that case, every plotting function should return an Axes or a collection of Axes. 

Typically, the Scanpy plotting functions are so high level that you don't even need to postprocess a returned axis object. And if you really want to, calling functions on the `matplotlib.pyplot` namespace comes usually handier. If you then really need the axes, you can also get it via `ax = pl.gca()`.

Does it make sense?

**Comment by Xparx** [comment]
@falexwolf Thanks for the explanation.
I see now that it's an issue of how the package should be used, i.e. the philosophy behind your api, and I seem to have tried to use it in a different perhaps more low level way. I will look in to using more low level functions/modules if I need it and work with your original intended workflow which i think make sense. I have missed the whole settings functionality which seems really useful to avoid some of the issues I have had.

**Comment by fidelram** [comment]
Nevertheless, some of the plotting functions are returning ax by default. I
will need to change that.

**Comment by falexwolf** [comment]
Thanks, guys! 🙂
