### ISSUE TITLE
Mismatching between colours and clusters in Leiden

### ISSUE THREAD

**Issue by SamueleSoraggi** [scverse/scanpy#420]
Hi,

when I run a command like this

```python
sc.tools.leiden.leiden(all_data, resolution=0.35, use_weights=True )
sc.plotting.tools.scatterplots.umap(all_data, color=['leiden'])
```

trying out different resolution, the vector `all_data.uns['leiden_colors']` happens to have a number of colors for the Leiden clusters that is not matching the number of Leiden clusters found the last time I ran the command above. Maybe the function that append the color vector to the annData object could be changed so that it checks if the vector of colors already exists, and overwrite it?

**Comment by fidelram** [comment]
I think that the `all_data.uns['leiden_colors']` list is only updated if the new number of clusters is bigger than the previous cluster number as the goal is to avoid missing colors. 

In you use the the `palette` argument, the color list will always be updated.

**Comment by falexwolf** [comment]
Yes, the 'leiden_colors' field in `.uns` will only be updated if needed, i.e., if the number of categories in the `leiden` field in `.obs` exceeds the number of available colors. As Fidel mentions, passing `palette` will automatically trigger resetting the colors according to the chosen palette.

**Comment by SamueleSoraggi** [comment]
Thanks for the hint. Someone else asked a similar question and answered to him.
