### ISSUE TITLE
Behaviour of `percent_top=None or []` in `calculate_qc_metrics()` inconsistent to documentation

### ISSUE THREAD

**Issue by nh3** [scverse/scanpy#421]
The documentation says:

> percent_top : Container[int], optional (default: (50, 100, 200, 500))
> Which proportions of top genes to cover. If empty or None don’t calculate.

However, supplying `percent_top=None` or `percent_top=[]` leads to index-out-of-bounds error, due to `proportions = top_segment_proportions(X, percent_top)` being always executed and `top_segment_proportions()` not handling a None or empty second argument.

**Comment by falexwolf** [comment]
@ivirshup Could you field this one?

**Comment by ivirshup** [comment]
@falexwolf, can do.

@nh3, just taking a look into this now. I think I've found the bug, but could you post a reproducible example so I can make sure?

**Comment by nh3** [comment]
Just load any data, e.g. pbmc3k, then do `sc.pp.calculate_qc_metrics(adata, percent_top=[])` which gives the following: (this is on v1.3.7, haven't tested on earlier versions)

```
In [5]: sc.pp.calculate_qc_metrics(adata, percent_top=[])                                                                                                                                                                            
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-385-66af52bcd3f3> in <module>
----> 1 sc.pp.calculate_qc_metrics(adata, percent_top=[])

~/miniconda2/envs/py3/lib/python3.6/site-packages/scanpy/preprocessing/qc.py in calculate_qc_metrics(adata, expr_type, var_type, qc_vars, percent_top, inplace)
     70     obs_metrics["log1p_total_{expr_type}"] = np.log1p(
     71         obs_metrics["total_{expr_type}"])
---> 72     proportions = top_segment_proportions(X, percent_top)
     73     # Since there are local loop variables, formatting must occur in their scope
     74     # Probably worth looking into a python3.5 compatable way to make this better

~/miniconda2/envs/py3/lib/python3.6/site-packages/scanpy/preprocessing/qc.py in top_segment_proportions(mtx, ns)
    182         if not isspmatrix_csr(mtx):
    183             mtx = csr_matrix(mtx)
--> 184         return top_segment_proportions_sparse_csr(mtx.data, mtx.indptr, ns)
    185     else:
    186         return top_segment_proportions_dense(mtx, ns)

IndexError: index -1 is out of bounds for axis 0 with size 0
```

Not sure if there are other impacts, but I think perhaps basically one just need to check `percent_top` before calling `top_segment_proportions()` at line 72.

**Comment by ivirshup** [comment]
Just checking to make sure we're working with the same data, since there could be different errors coming from that. The PR should do the right thing on `pbmc3k`. Could you check if it works for you?

**Comment by nh3** [comment]
Yes it works great. Thanks!

**Comment by ivirshup** [comment]
No problem, thanks for the bug report!
