### ISSUE TITLE
heatmap plot can't handle groupby integer categoricals

### ISSUE THREAD

**Issue by Xparx** [scverse/scanpy#422]
scanpy.__version__ : '1.3.7'

I'm trying to visualize my data with a heatmap and ran in to the following issue (title) and thought I note it,

The code I try to run:
```
component = [0,1,2,3,4,5,6]
topg = 30
dendrogram=False
for c in component:
    sort_idcs = np.argsort(adata.varm['PCs'][:, c])[::-1]
    genes_ranked_by_loading_in_PC = adata.var_names[sort_idcs]
    
    sc.pl.heatmap(adata, var_names=genes_ranked_by_loading_in_PC[:topg], groupby='hpf', use_raw=None, cmap='RdBu_r', swap_axes=True, dendrogram=dendrogram)
    fig = plt.gcf()
```
and I get the flollowing traceback
```
TypeErrorTraceback (most recent call last)
<ipython-input-641-33e0c59aae76> in <module>
     10     cells_ranked_by_loading_in_PC = adata.obs_names[sort_cell]
     11 
---> 12     sc.pl.heatmap(adata, var_names=genes_ranked_by_loading_in_PC[:topg], groupby='hpf', use_raw=None, cmap='RdBu_r', swap_axes=True, dendrogram=dendrogram)
     13     fig1 = plt.gcf()
     14     # sc.pl.heatmap(adata, var_names=genes_ranked_by_loading_in_PC[:topg], groupby='louvain', use_raw=None, cmap='RdBu_r', swap_axes=True, dendrogram=dendrogram)

~/.virtualenvs/default/lib/python3.6/site-packages/scanpy/plotting/anndata.py in heatmap(adata, var_names, groupby, use_raw, log, num_categories, dendrogram, var_group_positions, var_group_labels, var_group_rotation, layer, swap_axes, show_gene_labels, show, save, figsize, **kwds)
   1274             groupby_ax = fig.add_subplot(axs[2, 0])
   1275             ticks, labels, groupby_cmap = _plot_categories_as_colorblocks(groupby_ax, obs_tidy, colors=groupby_colors,
-> 1276                                                                           orientation='bottom')
   1277             # add lines to main heatmap
   1278             line_positions = np.cumsum(obs_tidy.index.value_counts(sort=False))[:-1]

~/.virtualenvs/default/lib/python3.6/site-packages/scanpy/plotting/anndata.py in _plot_categories_as_colorblocks(groupby_ax, obs_tidy, colors, orientation, cmap_name)
   2382         if len(labels) > 1:
   2383             groupby_ax.set_xticks(ticks)
-> 2384             if max([len(x) for x in labels]) < 3:
   2385                 # if the labels are small do not rotate them
   2386                 rotation = 0

~/.virtualenvs/default/lib/python3.6/site-packages/scanpy/plotting/anndata.py in <listcomp>(.0)
   2382         if len(labels) > 1:
   2383             groupby_ax.set_xticks(ticks)
-> 2384             if max([len(x) for x in labels]) < 3:
   2385                 # if the labels are small do not rotate them
   2386                 rotation = 0

TypeError: object of type 'int' has no len()
```

It seems like the function `_plot_categories_as_colorblocks` expects the len function to be applied to each category to be able to place it properly. However my categories are time stamps and therefore I have them in integer format.

Changing to str categorical fixes the issue.

**Comment by falexwolf** [comment]
Scanpy expects string categories in a couple of places. Didn't you get a warning at some point when trying to set integer categories?

**Comment by Xparx** [comment]
I did notice this warning in later versions of scanpy but only for index of `var` and `obs` not the table columns themselves. The loom file i'm loading contains this variable as an integer int64 type. I simply load the data and convert to categorical. 

```
adata = sc.read_loom(lf)
adata.obs.columns = ["cellid", "hpf"]
adata.obs["hpf"] = adata.obs["hpf"].astype('category')
```
This does not raise a warning, which seems like it would be hard to catch as I work on the dataframe directly.
Setting a dataframe with an integer index raises a warning as you mentioned.

However if this is intended then I can understand this error.

**Comment by falexwolf** [comment]
OK, thank you for the explanation! Let us think about it. There are a couple of sanity checks running in the background, which are easy to call at the beginning of the plotting functions, for instance, if they don't cost performance. E.g., there was a standard `adata._sanitize()` call in all the plotting functions. Is it still there, @fidelram? If not, no problem... We should have a solution that essentially doesn't require writing new code.

Also, what are your thoughts, @flying-sheep?

**Comment by flying-sheep** [comment]
You mean regarding “should we allow integer indexes”?

**Comment by ivirshup** [comment]
This seems to be working now. As these seem equivalent enough:

```python
import scanpy as sc, pandas as pd

pbmc = sc.datasets.pbmc3k_processed().raw.to_adata()
genes = list(pbmc.uns["rank_genes_groups"]["names"][0])

pbmc.obs["louvain_int"] = pd.Categorical(pbmc.obs["louvain"].cat.codes)
sc.pl.heatmap(pbmc, genes, groupby="louvain_int")
sc.pl.heatmap(pbmc, genes, groupby="louvain")
```

Not sure if this ever got a test case though.
