### ISSUE TITLE
Save a matrix in an annData object

### ISSUE THREAD

**Issue by SamueleSoraggi** [scverse/scanpy#426]
Hi

I am trying to use the package MAGIC-IMPUTE on the annData object on which I am working with scanpy. I do something of this type

```python
import magic
magic_op = magic.MAGIC()
all_data.magic = magic_op.fit_transform(all_data, genes='all_genes')
```

I then save the annData object on my hard drive to reopen it in another python notebook. But when I read the h5ad file, I cannot anymore find all_data.magic. Am I doing something wrong?

Cheers,
Samuele

**Comment by flying-sheep** [comment]
Yeah, AnnData doesn’t serialize arbitrary attributes to disk.

I assume the output of `fit_transform` is cell×gene? Then you could do `all_data.layers['magic'] = ...`. If the output is `cell×y` with `y != n_genes` then you should do `all_data.obsm['magic'] = ...`

**Comment by fidelram** [comment]
FYI, you can use magic within scanpy using `sc.pp.magic`
