### ISSUE TITLE
pbmc3k dataset has NaNs for gene_ids

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#428]
Possibly related to #275. The provided `sc.datasets.pbmc3k` does not have values for `"gene_ids"`. It'd be useful to have a standard dataset with ensembl ids and gene symbols for testing visualization functions with the `gene_symbols` argument.

```python
In [1]: import scanpy.api as sc 
   ...: sc.datasets.pbmc3k().var.head()                                                             
Out[1]: 
             gene_ids
index                
MIR1302-10        NaN
FAM138A           NaN
OR4F5             NaN
RP11-34P13.7      NaN
RP11-34P13.8      NaN

In [2]: import h5py 
   ...: with h5py.File("./data/pbmc3k_raw.h5ad") as f: 
   ...:     print(repr(f["var"][:])) 
   ...:                                                                                             
array([(b'MIR1302-10', -1), (b'FAM138A', -1), (b'OR4F5', -1), ...,
       (b'CU459201.1', -1), (b'AC002321.2', -1), (b'AC002321.1', -1)],
      dtype=[('index', 'S19'), ('gene_ids', 'i1')])
```

However, if I download the source files, everything works out fine:

```python

In [3]: !wget http://cf.10xgenomics.com/samples/cell-exp/1.1.0/pbmc3k/pbmc3k_filtered_gene_bc_matrices.tar.gz                                                                      
...
In [4]: !tar xzf pbmc3k_filtered_gene_bc_matrices.tar.gz
...
In [5]: sc.read_10x_mtx("./filtered_gene_bc_matrices/hg19").var.head()  
Out[5]: 
                     gene_ids
MIR1302-10    ENSG00000243485
FAM138A       ENSG00000237613
OR4F5         ENSG00000186092
RP11-34P13.7  ENSG00000238009
RP11-34P13.8  ENSG00000239945
```

Which makes me think the file hosted at `http://falexwolf.de/data/pbmc3k_raw.h5ad` was created when there was a bug in the `read_10x_mtx` code.

**Comment by falexwolf** [comment]
Thank you very much for pointing me to this! What you assume is absolutely right! I just replaced the file. The previous file was created when there wasn't even a function `read_10x_mtx`... I added a section to the docstring describing how the file was produced: https://github.com/theislab/scanpy/commit/fcd125252c307b5ecc077ad0e69fa9d6a1106ebb

See the updated docs: https://scanpy.readthedocs.io/en/latest/api/scanpy.datasets.pbmc3k.html
