### ISSUE TITLE
Error installing scanpy through pip

### ISSUE THREAD

**Issue by pwl** [scverse/scanpy#43]
I'm trying to install scanpy through `pip install scanpy` but I'm getting this weird error
```
$ pip install scanpy
Collecting scanpy
  Downloading scanpy-0.2.9.1.tar.gz (208kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lbk_t73k/scanpy/setup.py", line 39, in <module>
        readme = readme_f.read()
      File "/opt/conda/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 296: ordinal not in range(128)
```

That's with pip version `9.0.1` and python 3.6.  I'm getting similar errors for older versions of scanpy, including 0.2.1.  Perhaps this is a bug in pip but I'm not sure, I installed a bunch of other unrelated packages without any issues.

**Comment by pwl** [comment]
It turned out that this is definitely something wrong with my system setup. After I circumvented the bug above by clearing `README.rst` I found another package that spits out the same error (`louvain`).

**Comment by flying-sheep** [comment]
did you try using `pip3`?

**Comment by pwl** [comment]
Yes, with the same outcome.

**Comment by flying-sheep** [comment]
ah, i missed the part where it said `/opt/conda/lib/python3.6`.

but i’m confident now that [this](https://stackoverflow.com/questions/23917729/switching-to-python-3-causing-unicodedecodeerror) is your system’s problem!

**Comment by pwl** [comment]
So actually, I run a test on a fresh docker image (with this [Dockerfile](https://gist.github.com/pwl/005c781cbe19f5e961b59366f738caaf)) and it still fails to install scanpy with the same error.  I had some success with changing the default python encoding to utf-8 as shown in the Dockerfile but it only works when calling python3 directly and not for pip3.

However, it worked with python2.  I guess python3 is not supported by scanpy, is that correct?

**Comment by flying-sheep** [comment]
The other way round. Python 2 isn’t. But we need to find the root cause for this problem…

**Comment by pwl** [comment]
Weird, so is my Dockerfile example supposed to work or not?

How about explicitly adding an encoding option to `open`, like so `open(readme, "rt", encoding="utf-8")`?

If this is not system related after all I'll re-open the issue.

**Comment by flying-sheep** [comment]
it should definitely work. on a properly configured system (including docker images), the encoding should be UTF-8.

you’re right, we should probably do it. the only reason we didn’t yet is that we open quite a few files in the codebase, and if one of those open calls expects UTF-8, it’ll break again, but this time deeper down and harder to reproduce.

**Comment by pwl** [comment]
How about [changing the encoding globally](https://stackoverflow.com/questions/2276200/changing-default-encoding-of-python#17628350)?  Would that break anything?  Also, there is the same bug with the package you rely on, `louvain`.

As for the properly configured system, ubuntu:17.10 is the most generic and recent system I can think of, shouldn't it be properly configured out of the box?  If not, is there a way to configure the system so that the encoding is globally set to utf-8?

**Comment by flying-sheep** [comment]
i just learned that OSX sends its locale per default when connecting to a server.

so is it a local ubuntu or on a server?

what does `locale` (executed from a terminal) return?

**Comment by pwl** [comment]
I managed to get past the error by adding
```
RUN locale-gen en_US.UTF-8
ENV LC_ALL en_US.UTF-8
```
to the [Dockerfile](https://gist.github.com/pwl/a26726fda94ac7f4cbfb57e4fe98bf28).  Before that the default locale was set to `POSIX`, which caused all of these problems.  This is a weird choice of defaults as clearly python code doesn't work as expected.

Thanks for helping out @flying-sheep!

EDIT: just to clarify, this dockerfile is not an example of how to install scanpy, it's just a demonstration of how to circumvent the issues with locales.  In particular, several libraries are missing and scanpy does not complete the installation.  Feel free to update this Dockerfile or add one to the scanpy repository.

**Comment by flying-sheep** [comment]
Thanks for the info!

I was about to rant that this is weird and broken, but locales are literally the first section in the Ubuntu image docs, so I can’t blame them (too much): https://hub.docker.com/_/ubuntu. They probably use `POSIX` as `C.UTF-8` isn’t standard. ([blame the C standard consortium](https://github.com/mpv-player/mpv/commit/1e70e82baa9193f6f027338b0fab0f5078971fbe))

They recommend `ENV LANG C.UTF-8` though, maybe that works for you. (otherwise installing `locales` and your instructions work too)

**Comment by flying-sheep** [comment]
@falexwolf @pwl i used this one, works fine: https://gist.github.com/flying-sheep/0e003ae3398dd543638955a55c031c8d

i wonder why you didn’t have to install the dev packages though.

**Comment by pwl** [comment]
I somehow missed the documentation section, my bad.  I didn't install the dev packages because I only needed a minimal setup to recreate the bug, scanpy actually fails to install without the dev packages, as expected, but that comes later on, after the initial bug.

**Comment by flying-sheep** [comment]
don’t worry, i think they should really default to a better locale: many people will get their Dockerfiles by adapting existing ones instead of finding that specific doc site, i think.

**Comment by pwl** [comment]
@flying-sheep what do you think about mentioning the Dockerfile somewhere in the docs of scanpy or adding it to the scanpy repository?  Perhaps even adding a jupyter notebook to the image, this way new users could easily try the package out and run the examples from https://github.com/theislab/scanpy_usage.

**Comment by flying-sheep** [comment]
Yeah, i just talked to Alex about it. I think that’s a good idea!
