### ISSUE TITLE
Error in pca_loadings when components > 5

### ISSUE THREAD

**Issue by briangottfried** [scverse/scanpy#431]
Hi,

I am getting an error when the list of components is greater than 5 in `sc.pl.pca_loadings`. The error is a NamedError, `NameError: name 'count' is not defined`, coming from [this line](https://github.com/theislab/scanpy/blob/master/scanpy/plotting/_anndata.py#L554).

**Comment by falexwolf** [comment]
Thank you! Should be fixed via: https://github.com/theislab/scanpy/commit/16c160f5ab67f9834502a0ec37e173d2e72dfc1b
