### ISSUE TITLE
Information about scores

### ISSUE THREAD

**Issue by ghost** [scverse/scanpy#436]
Hello, I would like to know how the scores are calculated in the case of the differential expression analysis using the wilcoxon's test.
This is what I found in the code of the function _rank_genes_groups.py:
`scores = (scores - (n_active * (n_active + m_active + 1) / 2)) / sqrt(
                    (n_active * m_active * (n_active + m_active + 1) / 12))
scores[np.isnan(scores)] = 0
pvals = 2 * stats.distributions.norm.sf(np.abs(scores))` 

Is this the version of the test that works with not paired samples?
Thank you.

**Comment by ghost** [comment]
Maybe I got it. Scores are the z scores used to calculate the p-values and are also the scores that are also the scores of each gene given the results. Is it right?
Thanks

**Comment by falexwolf** [comment]
Yes, you're right, they are the z-scores used to calculate the p-values! I added a note in the docs to clarify this: https://scanpy.readthedocs.io/en/latest/api/scanpy.tl.rank_genes_groups.html
