### ISSUE TITLE
sc.pl color threshold

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/scanpy#443]
Dear,
Sometimes we need to set a threshold for the gene expression value to make a distinction between positive and negative cells. So how to set a threshold to the sc.pl colorbar so that negative cells (gene expressing value under the threshold) will be shown as grey (or other color), and positive cells (gene expressing value higher than the threshold) will be shown as usual ?

**Comment by wangjiawen2013** [comment]
It's like what cellranger and seurat does

**Comment by fidelram** [comment]
Can you post an example? Or a link to a page were this functionality is
shown?

**Comment by wangjiawen2013** [comment]
A similar function corresponding to sc.pl in scanpy is FeaturePlot function in Seurat. The detailed parameters of this function are as follows:
FeaturePlot (object, features.plot, min.cutoff = NA, max.cutoff = NA, cols.use = c("grey", "blue")). expresssion value under min.cutoff will be shown as grey, higher than max.cutoff will be shown as gradually changing blue color.

here is an example:
![seurat](https://user-images.githubusercontent.com/29703450/51781961-775f8500-215b-11e9-9da3-87586b388bcb.png)

**Comment by wangjiawen2013** [comment]
And here is the hyperlink:
https://satijalab.org/seurat/pbmc3k_tutorial.html
we can get information about negative cells and positive cells in such a plot. Now we can only show positive cells using sc.pl....

**Comment by wangjiawen2013** [comment]
@fidelram vmin and vmax parameters in sc.pl.umap() can meet my needs, there is no need to modify the function. sorry to trouble you.

**Comment by flying-sheep** [comment]
OK, great!

**Comment by falexwolf** [comment]
Great to read that!
