### ISSUE TITLE
Warning about setting `obs` to categorical when that's already been done

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#448]
On current master (f428848ece1d7a4794), every time I try to plot a scatter plot I get warnings about setting columns of `obs` to categorical, even though it's already been done. Here's an example:

![screen shot 2019-01-27 at 6 05 40 pm](https://user-images.githubusercontent.com/8238804/51797863-94c94780-225e-11e9-82db-2f170518a977.png)

**Comment by aopisco** [comment]
it started happening only a couple of days ago. @falexwolf is it because of pandas 0.2.4?

**Comment by ivirshup** [comment]
Fixed via https://github.com/theislab/anndata/pull/107.

It looks like it was pandas `v0.24.0`. Now `is_string_dtype` returns `True` for `Series` with categorical `dtype`.

**Comment by falexwolf** [comment]
Thank you guys for identifying and fixing this! :smile:
