### ISSUE TITLE
mnn batch correction recommended number of genes and negative gene values

### ISSUE THREAD

**Issue by cornhundred** [scverse/scanpy#449]
Hi, the documentation describes running MNN batch correction on a set of highly variable genes - how many genes are recommended? 

* I tried running with the top 10,000 variable genes. Is this a good number.

* Also, does selecting for these highly variable genes effectively permanently filter the dataset for only these genes?

* I noticed that the minimum gene expression level for some genes was less than zero after batch correction, is this expected?

**Comment by LuckyMD** [comment]
Hi @cornhundred,

While I can't speak for the intention of the authors of MNN, typically one would use 3000-6000 highly variable genes in scRNA-seq data analysis. That tends to cover the most important sources of variation. If you have a very deeply sequenced dataset from a sensitive scRNA-seq protocol (Smart-seq2/mcSCRB-seq?) with a lot of heterogeneity, you could make an argument for using more. Generally, 10,000 is a lot though. I would probably use fewer genes.

The new `highly_variable_genes()` function does not subset the genes anymore, but instead creates a `.var['highly_variable']` column which stores a boolean variable indicating which genes are highly variable and which are not. You should be able to use this column to subset adata.var_names as an input to `sce.mnn_correct()` via the `var_index` and `var_subset` parameters. Using these inputs should not subset your `AnnData` object.

Batch correction can create negative gene expression levels. People tend to deal with this differently. Some people force pre-batch-correction zeros to remain zero, others cast negative values to zero, and others again ignore it. I don't think there's a best approach to this. In the end you will probably get similar results in terms of embedding and trajectory inference. You just have to be careful how you interpret the gene expression values themselves. I have so far ignored it.

By the way, I've written a bit about these topics in my best practices tutorial. The case study that goes with the manuscript (currently under review) is publicly available [here](https://github.com/theislab/single-cell-tutorial)

**Comment by cornhundred** [comment]
Hi @LuckyMD, thanks for the recommendations we (@SharkieJones) will try lowering the number of variable genes (we ranked based on variance) and will look through the tutorials.

**Comment by LuckyMD** [comment]
No problem. If you would like to have a copy of the manuscript that goes with the tutorial, I can send it to you if you send me an email.

**Comment by cornhundred** [comment]
Thanks, I'll email you.
