### ISSUE TITLE
Windows compatibility issues with dependencies

### ISSUE THREAD

**Issue by stefanpeidli** [scverse/scanpy#454]
Hi!
As someone else posted on [stackoverflow](https://stackoverflow.com/questions/54366505/importerror-dll-load-failed-while-file-is-in-working-directory/54441575#54441575), there seem to be problems with the tables dependencies for windows users resulting in the following error when importing scanpy:

```pytb
>>> import scanpy
...
File "C:\Miniconda3\envs\py36\lib\site-packages\scanpy\readwrite.py", line 9, in
import tables
File "C:\Miniconda3\envs\py36\lib\site-packages\tables__init__.py", line 131, in
from .file import File, open_file, copy_file
File "C:\Miniconda3\envs\py36\lib\site-packages\tables\file.py", line 35, in
from . import hdf5extension
ImportError: DLL load failed: The specified procedure could not be found.
```

I've also posted an answer suggestion there. Maybe you could require h5py to have a fixed older version like 2.8 to avoid this problem for other windows users. Downgrading to that version worked for me.

**Comment by flying-sheep** [comment]
hmm, I’m not sure if it’s possible to require versions depending on the platform.

where’s the h5py issue about this?

**Comment by stefanpeidli** [comment]
I think the issue on h5py closest to this might be [this](https://github.com/h5py/h5py/issues/1142). 
I have not opened a seperate issue there yet. Do you think it is caused by scanpy or h5py?

**Comment by flying-sheep** [comment]
definitely in pytables or h5py.

**Comment by VolkerBergen** [comment]
Same issue with OSX python 3.7, solved simply with `conda install pytables`.

**Comment by flying-sheep** [comment]
Pytables is in requirements.txt (the PyPI package is called “tables”), how did y’all get Scanpy installed without all its dependencies?

https://github.com/theislab/scanpy/blob/f252d3a84200cc76060a786ef0589405fc5c9c12/requirements.txt#L7

**Comment by VolkerBergen** [comment]
`conda install` (not `pip`). Perhaps, that is due to pytables' conda dependencies (such as hdf).

**Comment by VolkerBergen** [comment]
Just checked.. same thing applies for windows. It returns an error until you `conda install pytables`.

**Comment by flying-sheep** [comment]
Hm. the conda package doesn’t list availability for windows: https://anaconda.org/bioconda/scanpy, just “conda install linux-64  v1.3.7,  osx-64  v1.3.7”

**Comment by VolkerBergen** [comment]
`conda install` meant to be related to `pytables`, not `scanpy`. `scanpy` runs easily via `pip`, only the tables dependency complains..

**Comment by Spruce-tone** [comment]
I had a same issue

My environment is
```
windows10
python3.8.8 (conda env)
```

scanpy installation 
`conda install -c conda-forge -c bioconda scanpy`

It looks work well on command prompt, but it wasn't work on jupyterlab(3.0)

To solve this, I just  installed all packages using pip, not conda.
here is my install procedure

```
conda create -n test python=3.8
pip install ipykernel
pip install jupyterlab
pip install scanpy
pip install python-igraph
pip install leidenalg
pip install fa2
```

I tired a lot of install and environment combination, but always there was a problem with conda.

**Comment by tagaler** [comment]
> 
> 
> I had a same issue
> 
> My environment is
> 
> ```
> windows10
> python3.8.8 (conda env)
> ```
> 
> scanpy installation
> `conda install -c conda-forge -c bioconda scanpy`
> 
> It looks work well on command prompt, but it wasn't work on jupyterlab(3.0)
> 
> To solve this, I just installed all packages using pip, not conda.
> here is my install procedure
> 
> ```
> conda create -n test python=3.8
> pip install ipykernel
> pip install jupyterlab
> pip install scanpy
> pip install python-igraph
> pip install leidenalg
> pip install fa2
> ```
> 
> I tired a lot of install and environment combination, but always there was a problem with conda.


Thanks! my scanpy was working but stopped reinstalling everything in a new environment again with pip got it working as you suggested

**Comment by stefanpeidli** [comment]
In case anyone has this error again, here is what worked for me:

- go to https://www.lfd.uci.edu/~gohlke/pythonlibs/ and download a .whl file for h5py. For python 3.6 on a 64bit windows OS this is the file h5py‑2.10.0‑cp36‑cp36m‑win_amd64.whl
- with your conda environment activated, install that wheel file using `python -m pip install --user --force-reinstall h5py‑2.10.0‑cp36‑cp36m‑win_amd64.whl` (change the file name to the one you downloaded).
- scanpy should work now

This worked on mine and also on a colleagues windows laptop.

I guess the problem is that you need a C++ compiler to build the necessary H5DF libraries. This works fine in UNIX based OS (Mac and Linux), but in windows you would need to download the most recent C++ compiler from some microsoft build tools website or alongside Visual Studio. So installing a prebuildt wheel for windows circumwents that problem. I wonder when h5py people will ever fix this for us poor Windows users.

**Comment by solenbanson** [comment]
> In case anyone has this error again, here is what worked for me:
> 
> * go to https://www.lfd.uci.edu/~gohlke/pythonlibs/ and download a .whl file for h5py. For python 3.6 on a 64bit windows OS this is the file h5py‑2.10.0‑cp36‑cp36m‑win_amd64.whl
> * with your conda environment activated, install that wheel file using `python -m pip install --user --force-reinstall h5py‑2.10.0‑cp36‑cp36m‑win_amd64.whl` (change the file name to the one you downloaded).
> * scanpy should work now
> 
> This worked on mine and also on a colleagues windows laptop.
> 
> I guess the problem is that you need a C++ compiler to build the necessary H5DF libraries. This works fine in UNIX based OS (Mac and Linux), but in windows you would need to download the most recent C++ compiler from some microsoft build tools website or alongside Visual Studio. So installing a prebuildt wheel for windows circumwents that problem. I wonder when h5py people will ever fix this for us poor Windows users.

this is the only way I solve my error. I tried every else except reinstall system.
thx!!

**Comment by ghost** [comment]
Had this issue again recently using python 3.7, and the solution above wasn't enough to solve it. Turns out I also needed to download the tables .whl file: `pip install .\h5py-2.10.0-cp37-cp37m-win_amd64.whl .\tables-3.6.1-cp37-cp37m-win_amd64.whl numpy==1.20.0 --user --force-reinstall`

**Comment by jliu678** [comment]
> In case anyone has this error again, here is what worked for me:
> 
> * go to https://www.lfd.uci.edu/~gohlke/pythonlibs/ and download a .whl file for h5py. For python 3.6 on a 64bit windows OS this is the file h5py‑2.10.0‑cp36‑cp36m‑win_amd64.whl
> * with your conda environment activated, install that wheel file using `python -m pip install --user --force-reinstall h5py‑2.10.0‑cp36‑cp36m‑win_amd64.whl` (change the file name to the one you downloaded).
> * scanpy should work now
> 
> This worked on mine and also on a colleagues windows laptop.
> 
> I guess the problem is that you need a C++ compiler to build the necessary H5DF libraries. This works fine in UNIX based OS (Mac and Linux), but in windows you would need to download the most recent C++ compiler from some microsoft build tools website or alongside Visual Studio. So installing a prebuildt wheel for windows circumwents that problem. I wonder when h5py people will ever fix this for us poor Windows users.

this helped me out as well

**Comment by jliu678** [comment]
i encountered this error when using a new conda env in pycharm after install scannpy in cmd line according to scannpy manual. 

I don;t know why but I didn't experience the error any longer if I set up new conda env and install scannpy in cmd line, and call spyder to run the same codes to import python packages.

**Comment by mezwick** [comment]
I also encountered this h5py dll error on a Windows 10 machine when trying to install scanpy. Fixed following these instructions, followed by `pip install numpy==1.20` due to a subsequent numpy version conflict with numba.

> > In case anyone has this error again, here is what worked for me:
> > 
> > * go to https://www.lfd.uci.edu/~gohlke/pythonlibs/ and download a .whl file for h5py. For python 3.6 on a 64bit windows OS this is the file h5py‑2.10.0‑cp36‑cp36m‑win_amd64.whl
> > * with your conda environment activated, install that wheel file using `python -m pip install --user --force-reinstall h5py‑2.10.0‑cp36‑cp36m‑win_amd64.whl` (change the file name to the one you downloaded).
> > * scanpy should work now
> > 
> > This worked on mine and also on a colleagues windows laptop.
> > I guess the problem is that you need a C++ compiler to build the necessary H5DF libraries. This works fine in UNIX based OS (Mac and Linux), but in windows you would need to download the most recent C++ compiler from some microsoft build tools website or alongside Visual Studio. So installing a prebuildt wheel for windows circumwents that problem. I wonder when h5py people will ever fix this for us poor Windows users.
> 
> this helped me out as well
