### ISSUE TITLE
Documentation for pl.scatter

### ISSUE THREAD

**Issue by bebatut** [scverse/scanpy#458]
Hi,

Some of the parameters documented online for `pl.scatter` are not accepted by the method: `ncols`, `wspace`, `hspace`. And some are not documented: `right_margin`, `left_margin`.

The difference seems to come from the parameters described in `{scatter_bulk}` and used for `pl.scatter` documentation.

What should be fixed `scatter_bulk` or inputs for `pl.scatter`?

Bérénice

**Comment by fidelram** [comment]
Hi Bérénice, ncols, wspace and hspace should work although they are only
meaningful when more than one plot is present. I think that right_margin
and left_margin were used in the initial implementation but no longer.

**Comment by bebatut** [comment]
`right_margin` and `left_margin` are still listed as parameters for `pl.scatter`: 

https://github.com/theislab/scanpy/blob/c15a5e8763097082c82cd8ef6fee697954c487dc/scanpy/plotting/_anndata.py#L49

And `ncols`, `wspace` and `hspace` are not accepted (with the current version on conda) 😟

**Comment by fidelram** [comment]
I think that there is no up to date Conda installation. Only Pip. The current version is 1.3.7

**Comment by falexwolf** [comment]
We're not maintaining the bioconda version, but it looks as if it was up to date: https://bioconda.github.io/recipes/scanpy/README.html

How is it working, anyways? Does somebody know? Does it automatically pull from PyPI?

**Comment by flying-sheep** [comment]
We have the ![](https://img.shields.io/badge/install%20with-bioconda-brightgreen.svg) badge. I think we should remove that if we’re not actually recommending installation that way. If there’s a “[On ]bioconda” badge to put next to the PyPI badge, I’d prefer that.

/edit: The badges are custom, we can control the text. I replaced it to match the PyPI badge, except that we can’t get a version, so I put a cute snake: ![](https://img.shields.io/pypi/v/scanpy.svg) ![](https://img.shields.io/badge/bioconda-🐍-blue.svg)

**Comment by flying-sheep** [comment]
> How is it working, anyways? Does somebody know? Does it automatically pull from PyPI?

yes: bioconda/bioconda-recipes#12958

> This pull request was automatically generated by [bioconda-utils](https://github.com/bioconda/bioconda-utils).

**Comment by falexwolf** [comment]
Thanks! Makes sense! (Both the badge and the automatic update from PyPI).

**Comment by fbnrst** [comment]
I also just realised that `pl.scatter` does not take `ncols` as an argument.  I am also using scanpy v1.4 from bioconda. The online documentation also does not mention ncols as an argument:
`scanpy.pl.scatter(adata, x=None, y=None, color=None, use_raw=None, layers='X', sort_order=True, alpha=None, basis=None, groups=None, components=None, projection='2d', legend_loc='right margin', legend_fontsize=None, legend_fontweight=None, color_map=None, palette=None, frameon=None, right_margin=None, left_margin=None, size=None, title=None, show=None, save=None, ax=None)` (copy-paste from https://icb-scanpy.readthedocs-hosted.com/en/latest/api/scanpy.pl.scatter.html), but it does mention `ncols` below in the description.

**Comment by falexwolf** [comment]
`pl.scatter` is, unfortunately, not in the best shape anymore. Since Fidel rewrote a large part of the plotting API, it's not used by any of the frequently used embeddings scatters anymore and would need to be simplified a lot, before actually adding new functionality (like `ncols`).

Would you mind correcting the docs? What are you using `pl.scatter` for?

**Comment by fbnrst** [comment]
Sure, I can have a look at the docs. I've been using it because of the `layers` argument since `pl.umap` does not seem to have it.

**Comment by fidelram** [comment]
@fabianrost84 The 'layers' were not added to anndata until recently and had not been implemented in all functions. However, adding this functionality to the different scatter plot functions is straightforward.

Let me prepare a quick PR.

**Comment by fbnrst** [comment]
As @bebatut pointed out, `pl.scatter` uses `doc_scatter_bulk` for the documentation. It does not seem to make sense to remove `ncols` from `doc_scatter_bulk` as it is used for `pl.umap` and so on.
How should the docs for `pl.scatter` be corrected? Should we remove `doc_scatter_bulk` and copy-paste the relevant documentation from `doc_scatter_bulk` to the `pl.scatter` doc string? At least until `pl.scatter` is in good shape again.

**Comment by fidelram** [comment]
@fabianrost84 The best would be to remove `doc_scatter_bulk`  and copy paste the relevant documentation.

**Comment by flying-sheep** [comment]
> copy paste

please never say those words when speaking about code again :stuck_out_tongue_winking_eye: 

No but seriously: There’s at least 6 reasons not to do that and to introduce a second (temporary) variable instead: https://github.com/theislab/scanpy/pull/557#issuecomment-476512533
