### ISSUE TITLE
Conversion to/from ExpressionSet (R)?

### ISSUE THREAD

**Issue by ONeillMB1** [scverse/scanpy#463]
Great package! 

Since the AnnData class structure is similar to R's ExpressionSet and many single-cell programs are developed in R, I am wondering if there is an EASY way to read/write the objects from python to R and vice versa.

**Comment by grst** [comment]
Have a look at https://satijalab.org/seurat/conversion_vignette.html

**Comment by ivirshup** [comment]
You could also go through a `loom` file or use [anndata2ri](https://github.com/theislab/anndata2ri).

**Comment by LuckyMD** [comment]
For a quick example of going between Seurat and Anndata via anndata2ri you can check out [this](https://github.com/LuckyMD/Code_snippets/blob/master/Seurat_to_anndata.ipynb).
