### ISSUE TITLE
sc.pl.stacked_violin and rank_genes_groups_stacked_violin `column_palette`

### ISSUE THREAD

**Issue by alexmascension** [scverse/scanpy#465]
Hi,

When using the sc.pl.stacked_violin and sc.pl.rank_genes_groups_stacked_violin functions, would it be possible to implement a `column_palette` option? Currently the `row_palette` plots colors according to the genes, which is really helpful to colorize genes by sets. Still, it would be interesting to plot the violin colors according to the groups using a `column_palette` option. I guess that one option should override the other.

**Comment by fidelram** [comment]
if you use swap_axes then the columns becomes the rows and you can use the
row_palette. Would that work for you?

**Comment by alexmascension** [comment]
Hi,

We get this error without swapping axes:

The code is 
```
genes = ["DES", "CD34", "COL1A1"]
sc.pl.stacked_violin(adata, genes, groupby = "leiden_0.1", )
```
The error is 
```
IndexError                                Traceback (most recent call last)
<ipython-input-35-8f09494e5255> in <module>
----> 1 sc.pl.stacked_violin(adata, genes, groupby = "leiden_0.1")

~/anaconda3/lib/python3.6/site-packages/scanpy/plotting/anndata.py in stacked_violin(adata, var_names, groupby, log, use_raw, num_categories, figsize, dendrogram, var_group_positions, var_group_labels, var_group_rotation, layer, stripplot, jitter, size, scale, order, swap_axes, show, save, row_palette, **kwds)
    929             axs_list.append(ax)
    930             ax = sns.violinplot('variable', y='value', data=df, inner=None, order=order,
--> 931                                 orient='vertical', scale=scale, ax=ax, color=row_colors[idx], **kwds)
    932 
    933             if stripplot:

IndexError: list index out of range
```

However, I would still consider the addition because in many cases where the amount of genes is considerable, if the user wants the genes to be in the rows, `swap_axes = True` should be necessary, and they would not be able to color the violins according to the clusters of cells.

**Comment by fidelram** [comment]
This is solved in PR #425 (which also includes other enhancements)

**Comment by alexmascension** [comment]
Hi,

I'm sorry but I fail to see how would PR #425 solve the problem. Could you give me a hint on this?

**Comment by fidelram** [comment]
the last commit solves the problem: https://github.com/theislab/scanpy/pull/425/commits/c31c0aedf3dbe4c53009b0ce66ea95a2bc9ebdc6

**Comment by ivirshup** [comment]
I feel like the behavior around this has since (a) changed a lot (especially defaults), and (b) now does the expected thing when you want to color by cluster. Closing.
