### ISSUE TITLE
scanpy cannot be reloaded (and this slows development)

### ISSUE THREAD

**Issue by timrandg** [scverse/scanpy#468]
Hi Alex, 

Here is an interesting bug with scanpy. For developers, it is useful to be able to reload a previously imported module within the environment containing useful variables and data for testing (a sample scRNA dataset) after changing scanpy's source code. However, scanpy cannot be reloaded. This means that to test, one has to stop the kernel, restart, reload all of the data needed for a plot and then test a plotting function that was just modified (for instance). 

Here is a way to demonstrate the reload failure easily:
1. open utils.py and add the print statement to track the descend_classes_and_funcs() function

```py
#utils.py
def annotate_doc_types(mod: ModuleType, root: str):
    for c_or_f in descend_classes_and_funcs(mod, root):
        print(c_or_f)                #added line to track descend_classes_and_funcs() function--TR
        c_or_f.getdoc = partial(getdoc, c_or_f)
```

2. open ipython

```py
import scanpy as sc
# prints out a bunch of function names from the descend_classes_and_funcs() function

import importlib
importlib.reload(sc)
# endless loop of function names from the descend_classes_and_funcs() function
# due to recursive yield statement
```

So what is the purpose of this function? And can it be altered to allow reload? It is called when __init__.py is run by sc.annotate_doc_types(sys.modules[__name__], 'scanpy'). 

```py
#utils.py

def descend_classes_and_funcs(mod: ModuleType, root: str):
    for obj in vars(mod).values():
        if not getattr(obj, '__module__', getattr(obj, '__qualname__', getattr(obj, '__name__', ''))).startswith(root):
            continue
        if isinstance(obj, Callable):
            yield obj
            if isinstance(obj, type):
                yield from (m for m in vars(obj).values() if isinstance(m, Callable))
        elif isinstance(obj, ModuleType):
            yield from descend_classes_and_funcs(obj, root)
```

_________________________________________________________

It is possible to remove the scanpy manually by:

```py
import sys
sys.modules.pop('scanpy')
```

and then import scanpy from scratch. Is that the preferred way to re-import scanpy for developers working to enhance scanpy package?

Thank you for your work on scanpy!

**Comment by flying-sheep** [comment]
Well, of course it should play nice with `importlib.reload`!

It was an easy fix, I just needed to make sure that the function doesn’t cycle.

**Comment by timrandg** [comment]
This did fix the recursion issue, thanks. But imortlib.reload(sc) still didn't allow updated source to take effect. I don't know why. Maybe the import tree for this package too complex for importlib.reload???

But the following worked for me. 
```
ipython
In [1]: %load_ext autoreload
In [2]: %autoreload 2
ln [3]: import scanpy as sc
ln [4]: sc.plotting._tools.scatterplots.tr_test()
[does nothing as expected, then change source to print something out]
ln [5]: sc.plotting._tools.scatterplots.tr_test()
hellya!!!

```

**Comment by flying-sheep** [comment]
I think autoreload does indeed do more than importlib.reload:

https://ipython.readthedocs.io/en/stable/config/extensions/autoreload.html#caveats

> Functions and classes imported via ‘from xxx import foo’ are upgraded to new versions when ‘xxx’ is reloaded.
