### ISSUE TITLE
Wilcoxon in rank_gene_group ignores genes on chunk borders

### ISSUE THREAD

**Issue by ahsv** [scverse/scanpy#469]
Using `method=wilcoxon` in the `rank_genes_groups` function chunks the genes into groups (to avoid using too much memory).  The scores for the genes on the endpoints of these chunks are never computed, however.

This can easily be observed by looking at a dataset containing 5000 genes (so that the chunk size is 2000) and setting `rankby_abs=True`.  The genes with indices 2000, 4000, 6000, .... will all be selected as marker genes with p-values of 0.  This is due to the fact that the rank-sums for these genes are left at 0 (they are never computed), which is then judged to be EXTREMELY significant.  

I will submit a PR with a fix for this in a minute :)

**Comment by ivirshup** [comment]
@ahsv and @a-munoz-rojas, has this been fixed? It looks like you've fixed it, but I haven't had a chance to check yet.

**Comment by falexwolf** [comment]
Yes, it should be fixed!

**Comment by ivirshup** [comment]
Great!
