### ISSUE TITLE
Facecolor of scatter plots for categorical data fail to be non-transparent.

### ISSUE THREAD

**Issue by yyoshiaki** [scverse/scanpy#473]
Hi,

Even when we set `sc.settings.set_figure_params(transparent=False)` the scatter plot for **CATEGORYCAL** data is transparented.
(ex. `sc.pl.umap(adata, color='louvain')` )
Continuous data goes well, so I think it is a bug.

When you switch Jupyterlab's theme into dark, it will be easy to check.

Best,
Yoshiaki

**Comment by fidelram** [comment]
Can you post an example showing the problem that we could reproduce? scanpy
includes some datasets that can be used for this cases.

**Comment by LuckyMD** [comment]
Is this related to having white in the color palette for plotting? I have noticed this as well. You can always create your own color palettes using `matplotlib.colors` and the `color_map` parameter. Although I'm not sure how this works with categorical data.

**Comment by yyoshiaki** [comment]
Thank you for your kind replies, and sorry for my poor descriptions.

This is what happend on my env.

![image](https://user-images.githubusercontent.com/19543497/52568903-597c6a80-2e53-11e9-8d9a-3e530bd6f991.png)

And now I solved by just adding this,

```python
import matplotlib as mpl
mpl.rcParams['figure.facecolor'] = 'white'
```

I verified the same thing on another environment, but it didn't happen.
So this might be critically relating to my personal environment.
I apologize that I didn't verify on another computer before the issue.

Lastly, this is a simple example for the thing.

```python
%matplotlib inline

# 2 lines below solved the facecolor problem.
# import matplotlib as mpl
# mpl.rcParams['figure.facecolor'] = 'white'

import scanpy as sc

adata = sc.datasets.paul15()

sc.pp.recipe_zheng17(adata)
sc.tl.pca(adata, svd_solver='arpack')
sc.pl.pca(adata, color='paul15_clusters', legend_loc='on data')
```

**Comment by yyoshiaki** [comment]
Sorry for opening an issue over and over.
I noticed that the declear below is inconpatible with `set_figure_params`.

```python
import matplotlib as mpl
mpl.rcParams['figure.facecolor'] = 'white'
```

If possible, I hope facecolor setting parameter is added https://github.com/theislab/scanpy/blob/master/scanpy/settings.py#L85-L136

Best,

**Comment by flying-sheep** [comment]
What do you mean? In which way is it incompatible?

In matplotlib/matplotlib#9698 it’s said that

> The goal is to ultimately replace setting `savefig.transparent` by
`figure.facecolor = (0, 0, 0, 0)`.

So we should add a `facecolor` parameter and deprecate `transparent` (with a nice message to point people to `set_figure_params(facecolor=(0, 0, 0, 0))`)

**Comment by yyoshiaki** [comment]
I was wrong, it worked well...

```python
%matplotlib inline

import scanpy as sc
import matplotlib as mpl

# 2 lines below solved the facecolor problem.
mpl.rcParams['figure.facecolor'] = 'white'
sc.settings.set_figure_params(dpi=80, color_map='viridis', transparent=False)

adata = sc.datasets.paul15()
sc.pp.recipe_zheng17(adata)
sc.tl.pca(adata, svd_solver='arpack')
sc.pl.pca(adata, color='paul15_clusters', legend_loc='on data')
```
![screenshot from 2019-02-13 12-42-06](https://user-images.githubusercontent.com/19543497/52685380-d9f2b680-2f8c-11e9-8ca2-692b083116ee.png)

Anyway, 

> So we should add a `facecolor` parameter and deprecate `transparent` (with a nice message to point people to `set_figure_params(facecolor=(0, 0, 0, 0))`)

sounds a good solution. Expliciting that 'white', 'w' or (1,1,1) are also applicable may be kind.
Of course, you can add theme like Seurat's one though I'm not sure how many people are requiring it.

- https://satijalab.org/seurat/mca.html
- https://matplotlib.org/gallery/style_sheets/style_sheets_reference.html#sphx-glr-gallery-style-sheets-style-sheets-reference-py

**Comment by flying-sheep** [comment]
> Expliciting that 'white', 'w' or (1,1,1) are also applicable may be kind.

Definitely! Good docs are everything.
