### ISSUE TITLE
UMAP color pallet when plotting a gene

### ISSUE THREAD

**Issue by tsotnech** [scverse/scanpy#476]
Hi guys, 

I can't change the color palette when plotting a gene with sc.pl.umap functions. 
if I plot louvain or certain categories, it does change the color scheme
e.g.
`sc.pl.umap(adata, color=['louvain'], palette='tab20') `

but If I plot a gene 
`sc.pl.umap(adata, color=['NANOG'], palette='plasma')`

it doesn't change the color scheme and I always get 'viridis' color palette. 

Is there any way I can adjust this? 

Thanks a lot,

Tsotne

**Comment by aditisk** [comment]
@tsotnech I ran into the same issue a few months ago but found a fix by using the sc.pl.scatter() function instead. I have pasted the command here and it worked for me.

from matplotlib import pyplot as plt
sc.pl.scatter(adata,color='NANOG',legend_loc='none',color_map=plt.cm.Reds,size=5,basis='umap')

Hopefully this works for you too.
-Aditi

**Comment by tsotnech** [comment]
awesome, thanks a lot @aditisk, that works well

**Comment by ivirshup** [comment]
Continuous color schemes are given with the `color_map` argument, categorical schemes are given with `palette`. All the scatter plots (`scatter`, `pca`, `tsne`, `umap`, etc...) share these arguments.  Here's an example:

```python
import scanpy as sc
import matplotlib as mpl
adata = sc.datasets.pbmc68k_reduced()
sc.pl.umap(adata, color=["louvain", "HES4"])
sc.pl.umap(adata, color=["louvain", "HES4"], palette="Set2", color_map=mpl.cm.Reds)
```

It's not that clearly documented for `umap`, and is pretty easy to miss.

**Comment by jlehrer1** [comment]
This is still not documented.
