### ISSUE TITLE
scatter plot array size argument gives inconsistent behavour

### ISSUE THREAD

**Issue by Xparx** [scverse/scanpy#478]
I'm trying to use an array for the size argument to my umap/scatterplot with the following code
```
import scanpy.api as sc
import numpy as np
sc.settings.figdir = "testdir"
sc.settings.file_format_figs = "png"
sc.logging.print_versions()
```
With these libraries
`scanpy==1.3.7 anndata==0.6.16 numpy==1.16.1 scipy==1.2.0 pandas==0.23.4 scikit-learn==0.20.2 statsmodels==0.9.0 python-igraph==0.7.1 louvain==0.6.1 `

Running the following code bit. I use some dummy variable for size.
```
somedata = sc.datasets.paul15()
sc.pp.pca(somedata)
sc.pp.neighbors(somedata, n_neighbors=4, n_pcs=20)
sc.tl.umap(somedata, spread=1, min_dist=0.1, random_state=42)
sc.tl.leiden(somedata, resolution=0.5, random_state=42)
z = np.abs(somedata.obsm['X_pca'][:,0])**1
sc.pl.umap(somedata, color=['1110007C09Rik'], size=z, cmap='viridis', save='continuous_expr.png')
sc.pl.umap(somedata, color=['leiden'], size=z, cmap='viridis', save='group_value.png')
```
I get the following two figure as output
![umapcontinuous_expr](https://user-images.githubusercontent.com/715716/52612879-951a3300-2e59-11e9-9dad-a8afc60a4b54.png)
![umapgroup_value](https://user-images.githubusercontent.com/715716/52612880-95b2c980-2e59-11e9-9a44-81dd84e3274d.png)

I would expect to see a similar size allocation/distribution but they are very different. I Could not really find a cause for this looking at the scatter plot function so it might be somewhere deeper. 

I'm need help with getting some grasp on how to interpret this issue and if possible how to map the size argument to the same data points over different plots.

**Comment by fidelram** [comment]
I think the problem is the option `sort_order` which is True by default for
numerical data.  This changes the ordering of the dots and thus it messes
up with your own sizes. Setting `sort_order=False` should fix the problem.

**Comment by Xparx** [comment]
Yes, that seems to fix the issue. Thank you for the quick reply.

**Comment by flying-sheep** [comment]
great, thank you for the help @fidelram
