### ISSUE TITLE
multimodal analysis

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/scanpy#479]
Dear,
Now users can analyze and explore multi-modal data with Seurat, are there any equivalent methods in Scanpy ? Cellranger3 adds some new features and now supports multi-modal data too.

Using Seurat with multi-modal data: https://satijalab.org/seurat/multimodal_vignette.html

here is an related issue: https://github.com/theislab/scanpy/issues/351

**Comment by ivirshup** [comment]
In theory I think we can do most of that. In practice, I got some errors.

I think it would be worth formalizing what the supported interface for doing multimodal analysis is. I'd really like it to be uniform. I could see it being based on keys in `.var`:

```python
adata.var["gex"] = adata.var["expression_type"] == "Gene Expression"
sc.pl.pca(adata, var_key="gex")
sc.pl.pca(adata, color=["Protein1", "Protein2"])
# This also has the nice feature that it could abstract out the current `use_highly_variable` argument
```

View based:

```python
gex_view = adata[:, adata.var["expression_type"] == "Gene Expression"]
sc.pp.pca(gex_view) # Calculate pca on gene expression
sc.pl.pca(adata, color=["Protein1", "Protein2"])
```

Different expression types could be put under `.obsm` (probably the closest "analogy" to `SingleCellExperiment`'s `assays()`). But this raises questions of what counts as a variable, and I think would take more work to implement.

Of course, there are many other ways this could be done as well. As it could impact APIs throughout `scanpy`, I think input from @falexwolf and @flying-sheep is important here.

**Comment by wangjiawen2013** [comment]
Could epiScanpy be used as a multi-modal analysis tool ? @falexwolf

**Comment by LuckyMD** [comment]
>Could epiScanpy be used as a multi-modal analysis tool ? @falexwolf

I think this is a question that is best asked in the episcanpy forum:
https://github.com/colomemaria/epiScanpy/issues

They have used it for multiple epigenomics modalities. Not sure if integrated though.

**Comment by flying-sheep** [comment]
Most discussion happens on theislab/anndata#237

**Comment by Zethson** [comment]
We are trying to develop new scverse packages which handle specific modalities such as [scirpy](https://github.com/scverse/scirpy) for AIRR, [muon](https://github.com/scverse/muon) for ATAC/CITE, and [squidpy](https://github.com/scverse/squidpy) for spatial data
