### ISSUE TITLE
sc.pl.tracksplot tracks do not align with the clusters

### ISSUE THREAD

**Issue by tsotnech** [scverse/scanpy#480]
Hi guys,

sorry for opening so many issues, I really love using tracksplot for visualizing the expression in different clusters, but the small issue I have is that tracks actually never align well with the clusters "timeline" at the bottom. especially the first and last tracks are always misaligned. I couldn't find the list of arguments that I can pass through sc.pl.tracksplot command maybe just changing margins or size of the plot might make it better. 
![tracksplotin_final](https://user-images.githubusercontent.com/43454880/52679490-1f11dc80-2eea-11e9-8a6e-511beefb4c1d.png)

in this example, cluster 0, 8,9,10 tracks are misaligned to the timeline below. 

Thanks a lot,

Tsotne

**Comment by fidelram** [comment]
Thanks for reporting. I will take a look.

**Comment by fidelram** [comment]
I can not reproduce the problem.

Does this works for you?
```
pbmc = sc.datasets.pbmc68k_reduced()
marker_genes = ['S100A8', 'GNLY', 'NKG7', 'KLRB1', 'FCGR3A', 'FCER1A', 'CST3']
ax = sc.pl.tracksplot(pbmc,marker_genes, groupby='louvain')
```
![image](https://user-images.githubusercontent.com/4964309/52697496-dc93e280-2f71-11e9-8d01-65305c5d3c5d.png)

What is your version of matplotlib?

**Comment by tsotnech** [comment]
I have matplotlib 2.2.2. 


Update!
I just updated my matplotlib to the latest version and it works well there is no misalignment any more! 

thanks again

**Comment by fidelram** [comment]
Glad that it worked, and thanks for reporting the issue.  I realized that the requirement for scanpy was `matplotlib>=2.2.2`. I updated it  to 3.0.0.

**Comment by raman91** [comment]
Hey, what are the values on the right most column in tracks plot? Thanks
