### ISSUE TITLE
Why n_genes is not equal to the number of genes with non-zero expression?

### ISSUE THREAD

**Issue by picrin** [scverse/scanpy#488]
I find this behaviour surprising:
```
>> sc.pp.filter_cells(adata, min_genes=200)
>> sc.pp.filter_genes(adata, min_cells=100)
>> list(np.sum(adata.X.toarray() != 0, 1))[:10]
[814, 1410, 3580, 3514, 1456, 856, 795, 2154, 671, 4051]
>> adata.obs["n_genes"].tolist()[:10]
[869, 1513, 4058, 4251, 1580, 908, 840, 2458, 695, 4708]
```
I would expect both lists to be equal, not "mostly equal". Is there any good explanation for this behaviour?

**Comment by ivirshup** [comment]
`n_genes` was calculated when you filtered cells. I agree that this implicit behavior can be confusing.

btw, if your expression is in a sparse matrix, this would be a more efficient way to count the number of expressed genes:

```python
adata.X.eliminate_zeros() # Removes explicit zeros
n_genes = adata.X.getnnz(axis=1) # Counts explicit values

# or, slightly less efficient but still more efficient than making a dense array
np.ravel((adata.X != 0).sum(axis=1))
```

**Comment by picrin** [comment]
Oh, thank you. When I comment out the filter genes step I get sensible counts. It completely makes sense!

**Comment by ivirshup** [comment]
No problem!
