### ISSUE TITLE
[Suggestion] Expression atlas datasets?

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#489]
I've written up a little script for making an `AnnData` given an accession for the EBI single cell expression atlas ([gist](https://gist.github.com/ivirshup/e7f0c435474d9b06b622c63d4221afe6)), and was wondering if it'd be useful to add under `sc.datasets`. It could be nice to make it easier to try out methods/ have examples which weren't for pbmcs.

**Comment by flying-sheep** [comment]
Sure, that seems like a great idea!

**Comment by falexwolf** [comment]
Awesome idea! :)

Sorry that I haven't merged all your other PRs, yet. I got back to work on Scanpy yesterday or so after being sick for 2 weeks and another 2 weeks of complete chaos (sick babies)... ;)

You'll get feedback very soon, but at first sight, all of them looked fine, anyway. :)
