### ISSUE TITLE
Setup on osx (both pip and from source)

### ISSUE THREAD

**Issue by ktpolanski** [scverse/scanpy#49]
Hello,

I've tried setting up your package via pip, as instructed. This crashed out very quickly:

	mib111492i:~ kp9$ pip install scanpy
	Collecting scanpy
	  Downloading scanpy-0.2.9.1.tar.gz (208kB)
		100% |################################| 215kB 2.8MB/s 
		Complete output from command python setup.py egg_info:
		Traceback (most recent call last):
		  File "<string>", line 1, in <module>
		  File "/private/tmp/pip-build-cx2i4lbu/scanpy/setup.py", line 39, in <module>
			readme = readme_f.read()
		  File "/Users/kp9/anaconda3/lib/python3.6/encodings/ascii.py", line 26, in decode
			return codecs.ascii_decode(input, self.errors)[0]
		UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 296: ordinal not in range(128)
	
		----------------------------------------
	Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-cx2i4lbu/scanpy/

The offender seems to be the stylised README file, so I downloaded the source code, got rid of it, and proceeded with the installation. I'm unsure how representative the following encountered issues are of an ideal pip installation, but I figured I'd bring them to your attention anyway just in case they're relevant:

- h5py crashed out on account of not having hdf5 available. This was remedied via `brew install hdf5`, and it seems like the most likely of these issues to affect other users.
- The installer ignored my 2.1.0 setup of matplotlib, tried to install 2.0.0 in some weird way and crashed out. Installing 2.0.0 via pip (absolutely painlessly, mind you - what was that weird installer that crashed the thing out?) allowed the setup to proceed past this point. This might be an isolated incident, but it seemed weird enough to alert you of just in case.
- As is, louvain crashes immediately and uninformatively when attempts are made to pip it in. Installing from the GitHub source code still works fine though. I'll notify the louvain team of this situation, but this may be of relevance to you too.

Thanks!

**Comment by falexwolf** [comment]
Thank you for this report!

We know about the first issue. It's due to a misconfigured system. The readme is just plain text.

Here is the issue: https://stackoverflow.com/questions/23917729/switching-to-python-3-causing-unicodedecodeerror

And here a solution:
```
export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8
```
Or, on Mac, edit `/etc/ssh/ssh_config` and change
```
Host *
   SendEnv LANG LC_*
```
to
```
Host *
#   SendEnv LANG LC_*
```

**Comment by ktpolanski** [comment]
I have just managed to install successfully (kind of, more details on things going wrong to come in the other repository) with pip without actually doing any of this, so I'm not sure what was actually going on here. One way or the other, this seems to have gone away now somehow on its own.
