### ISSUE TITLE
How to infer biological meaning from sub-clusters seen on UMAP ?

### ISSUE THREAD

**Issue by aditisk** [scverse/scanpy#491]
Is there a metric I can use to prove similarity/differences between sub-clusters on a UMAP plot ? For example, is there a way to prove that cells in cluster 1 are/are not biologically similar to cells in cluster 2 ? Or another thing I would like to know is how similar/different is cluster 1 to all other clusters in this data-set and I wanted to know what metric (some sort of distance metric?) can help prove this ?

Also, if I see 5 sub-clusters of cells for a set of samples, is it okay to interpret this as 5 biologically different populations or is that reading too much into the clustering output ?

Thank you.

**Comment by LuckyMD** [comment]
Hi,
Your question is actually quite difficult to answer. It depends on how you define cell identity. For example, depending on how you set the resolution parameter for your clustering you can get a very different number of clusters. As clusters often have super- and sub-structure, you cannot easily say when a sub- or superstructure is not meaningful (e.g., T-cells vs CD4+ and CD8+ T-cells). Unfortunately many clustering techniques do not incorporate an assessment of uncertainty to tell you when you are fitting noise. And even when they do, this is based on a model of what a cell cluster should look like, which does not have to conform to the biological reality. The heuristic that tends to be used is that if you can biologically interpret your clusters based on marker genes and other signatures, then they are meaningful. That does however not mean that sub- or superstructures involving these clusters are not also meaningful. Sorry, I can't give a clearer answer than that.

In terms of assessing differences between clusters, this is a somewhat related problem. An approach that you could use is to look at the distribution of Euclidean distances in gene- or PCA-space. However, that comes with the caveat that Euclidean distance does not take into account the biological manifold on which the cells lie (and on which distances will be more informative). You can try to use pseudotime as a measure for distance over this manifold, however that would require you to have sampled enough of the manifold to fit it in your data.

**Comment by aditisk** [comment]
@LuckyMD Thanks for your detailed reply. I will try some of the approaches mentioned in the 2nd paragraph and see if that helps us answer our question.

Thanks.
