### ISSUE TITLE
Annotating cells help

### ISSUE THREAD

**Issue by Leprechaun777** [scverse/scanpy#495]
How were the bulk labels generated then assigned to cells in the pbmc68k dataset? I'm trying to do the same on my data.
Ideally I would like to use my own list to label cells. For example a cell has Gene X and Gene Y, then the 'bulk_label' in .obs is loaded with a string 'Cell Z'.

Thank you

**Comment by Zethson** [comment]
Please ask usage questions here: https://discourse.scverse.org/
