### ISSUE TITLE
Calculate qc metrics with sns.jointplot

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/scanpy#499]
Dear,
When I Calculate qc metrics for visualization according to the example in https://scanpy.readthedocs.io/en/latest/api/scanpy.pp.calculate_qc_metrics.html#scanpy.pp.calculate_qc_metrics:

```py
>>> adata = sc.datasets.pbmc3k()
>>> sc.pp.calculate_qc_metrics(adata, inplace=True)
>>> sns.jointplot(adata.obs, "log1p_total_counts", "log1p_n_genes_by_counts", kind="hex")
```

The following error occurred:
AttributeError: 'str' object has no attribute 'get'
It seems that sns.jointplot are not compatible well with adata.obs, anybody who can help me ?

**Comment by ivirshup** [comment]
Oh, I totally wrote that call to `seaborn` wrong. Should be:

```python
sns.jointplot("log1p_total_counts", "log1p_n_genes_by_counts", adata.obs, kind="hex")
```

**Comment by flying-sheep** [comment]
Should be fixed!
