### ISSUE TITLE
Arrays for row_attrs or col_attrs

### ISSUE THREAD

**Issue by VincentGardeux** [scverse/scanpy#507]
Hey,

I just stumbled into an issue with scanpy.
If I have an gene or cell annotation that is not 1-dimensional (I store ERCCs as a M x 92 float matrix in col_attrs), it generates an error:
"Exception: Data must be 1-dimensional"

However, it is allowed by the loompy nomenclature to have multiple dimensions. 
And actually loompy package accepts it.

Could it be corrected, so it can be accepted as a valid Loom file/annotation?

Thanks in advance

**Comment by ivirshup** [comment]
Sorry about the late response!

I think this might fit under the `.obsm` attribute of an `AnnData` object. Looking at [the docs](https://anndata.readthedocs.io/en/latest/anndata.AnnData.html), it's meant to store two dimensional annotations.  

That said, I've personally put ERCCs in the expression matrix, then filtered them out for parts of the analysis where they are confounding.

**Comment by flying-sheep** [comment]
Definitely both valid. Since they’re not real genes (but measured like them), I’d slightly prefer the `.obsm` solution as that can’t result in problems if you forget the ERCCs are there.

**Comment by gokceneraslan** [comment]
@VincentGardeux Related issue: Arrays in row_attrs/col_attrs attribute of loom files are now directly stored into obsm/varm: https://github.com/theislab/anndata/pull/127 So if you use AnnData from master branch you can read/write such arrays from/to loom files.
