### ISSUE TITLE
Error in sc.pp.highly_varaible_genes

### ISSUE THREAD

**Issue by jhu99** [scverse/scanpy#509]
adata = sc.read_10x_mtx(input_file)
sc.pp.highly_variable_genes(adata)
-------------------------------------------------------------------------
Output:

ValueError: Bin edges must be unique: array([          -inf, 9.99999996e-13, 9.99999996e-13, 9.99999996e-13,
       9.99999996e-13, 9.99999996e-13, 9.99999996e-13, 9.99999996e-13,
       3.46620451e-04, 6.93240901e-04, 2.42634304e-03, 7.27903098e-03,
       1.97573602e-02, 4.47139777e-02, 8.52686986e-02, 1.50433296e-01,
       2.66013424e-01, 5.22116709e-01, 1.29667579e+00, 4.65706696e+02,
                  inf]).
You can drop duplicate edges by setting the 'duplicates' kwarg

**Comment by LuckyMD** [comment]
Hi!

It looks like you have too many 0 count genes in your dataset. I would filter genes and cells before calculating highly variable genes.

In case you're interested, I've been working on a tutorial for single-cell RNA-seq analysis. It's available [here](www.github.com/theislab/single-cell-tutorial)

**Comment by aditya-sarkar441** [comment]
I am still getting this error even after doing filtering. This was my code for filtering : 

sc.pp.filter_cells(adata, min_genes=200)
sc.pp.filter_genes(adata, min_cells=1)

Can you please help me with this ?

**Comment by jambler24** [comment]
Encountered this same error, not clear what is causing it. 

```    
    sc.pp.normalize_total(adata, target_sum=1e4)
    sc.pp.log1p(adata)
    adata.raw = adata
    sc.pp.scale(adata, max_value=10)
    sc.pp.filter_genes(adata, min_cells=2)
    sc.pp.highly_variable_genes(adata, flavor='cell_ranger', n_top_genes=2000)
                                
```
With the same error:

```
    File "/opt/venv/lib/python3.7/site-packages/pandas/core/reshape/tile.py", line 400, in _bins_to_cuts
      f"Bin edges must be unique: {repr(bins)}.\n"
  ValueError: Bin edges must be unique: array([           -inf, -4.47034836e-08, -2.98023224e-08, -2.98023224e-08,
         -1.49011612e-08, -8.38190317e-09,  1.00000000e-12,  1.00000000e-12,
          1.00000000e-12,  1.00000000e-12,  1.00000000e-12,  4.09781933e-09,
          1.49011612e-08,  1.49011612e-08,  1.49011612e-08,  1.49011612e-08,
          2.98023224e-08,  4.47034836e-08,  4.47034836e-08,  5.96046448e-08,
                     inf]).
  You can drop duplicate edges by setting the 'duplicates' kwarg
```

Very possibly an input error, but the output doesn't point to anything useful as a starting point to debug.
