### ISSUE TITLE
memory requirements

### ISSUE THREAD

**Issue by ShobiStassen** [scverse/scanpy#511]
Hi,
I am trying to run the full 1.3M 10X mouse cell dataset (using the 1M_neurons_filtered_gene_bc_matrices_h5.h5 file from 10X website).
I have 126GB RAM and Intel® Xeon(R) W-2123 CPU @ 3.60GHz × 8 which is above the requirements you mention needed to run the full cluster.py method without subsampling. (https://github.com/theislab/scanpy_usage/tree/master/170522_visualizing_one_million_cells)
I get a memory error at the normalization and filter_genes_dispersion stage, should i modify the code in anyway? (without subsampling)
Thanks,Shobi

**Comment by falexwolf** [comment]
It should definitely run through with these resources, and I and many other people ran it already. @Koncopd, could you check whether everything behaves still normally? I don't know how we can test this, but I also can't see who we might have broken it.

**Comment by ShobiStassen** [comment]
hi Alex, I'm not sure how to test this either. I tried to run in a new clean conda environment but cant use more than 50% of the cells in pre-processing (otherwise the process is killed at even the normalization stage, "pp.normalize_ per_cell" and uses over 120GB RAM)
The file from 10X i'm using is the link to "1M_neurons aggr - Gene / cell matrix HDF5 (filtered)" from https://support.10xgenomics.com/single-cell-gene-expression/datasets/1.3.0/ 
This is what i type into the terminal
$ python cluster_mouse_brain.py 1M_neurons_filtered_gene_bc_matrices_h5.h5
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
reading 1M_neurons_filtered_gene_bc_matrices_h5.h5 (0:01:19.78)
running recipe zheng17
filtered out 3983 genes that are detected in less than 1 counts
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Killed

**Comment by Koncopd** [comment]
@falexwolf 
Yes, i will run through it and check the memory usage and so on.

**Comment by ShobiStassen** [comment]
I also just tried to run on a Windows machine (to make sure it was not just something to do with the memory management in my Linux machine which has 128GB RAM) with 64GB RAM and 6 cores @3.6GHz and also get Memory error at the normalization step when trying to process the 1.3M neuron file.

**Comment by falexwolf** [comment]
Sergei (@Koncopd) tested it out and will get back to you. He also found a peak memory usage of 121 GB. I have to admit that I never made checks with that degree of detail and I fear that for now, I'll simply update the documentation stating that peak memory usage can go up to ~120 GB. I'm still puzzled by that, and maybe some efficiency found it's way into the code which wasn't there (simple guess: is everything in `float32`?). But we'll need some time to work it out.

**Comment by falexwolf** [comment]
Just updated the readme https://github.com/theislab/scanpy_usage/blob/master/170522_visualizing_one_million_cells/.

**Comment by Koncopd** [comment]
Hi, @ShobiStassen.
As @falexwolf said, i tested the memory usage in the step where you have the problem.
https://github.com/Koncopd/anndata-scanpy-benchmarks/blob/master/cluster_1m_neurons.ipynb
The peak usage is around 121 GB, but it should still be possible to run with 126 GB RAM. Maybe another process took some serious amount of memory?

**Comment by ShobiStassen** [comment]
hi Koncopd, ive tried running your exact lines of code and my memory increment is the same as yours for reading the file and filtering the genes by count. Once i hit the normalization function, my memory shoots above 120 and crashes. in your case, your peak memory usage during normalization is around 92GB and only during filter_genes_variable do you hit 121GB
I dont have any other processes that are being triggered so it's very puzzling why my usage is different from yours... hmmm

**Comment by Koncopd** [comment]
Ok, so the first problem is normalization for some reason.
@falexwolf , it seems we should just use new normalize_total when the pull request is accepted, it is more memory efficient.
![image](https://user-images.githubusercontent.com/3065736/54003760-9afeed80-4153-11e9-9187-8e474a2fa03e.png)

**Comment by falexwolf** [comment]
Cool, @Koncopd! I'll rewrite a recipe for this with the new functions, which should be a lot more memory effective.
