### ISSUE TITLE
Color cells from only 1 cluster at a time

### ISSUE THREAD

**Issue by aditisk** [scverse/scanpy#513]
Is there a way to color cells belonging only to a certain cluster on the UMAP plot ? For example, can I have only cells in cluster 0 in a dark color and everything else as grey colored dots in the background ?

I would also like to do the same with other adata observations like Patient ID etc. 

Thank you.

**Comment by LuckyMD** [comment]
Hi @aditisk,

You can always make a dummy `.obs` variable for cluster membership. Something like this:
`adata.obs['cluster_dummy'] = adata.obs['louvain'] == adata.obs['louvain'].cat.categories[0]`

By iterating over the last index (currently at 0), you can create dummy variables to visualize via `sc.pl.umap(adata, 'cluster_dummy')`

Hope that helps!

**Comment by falexwolf** [comment]
Thanks, @LuckyMD!

In some cases, the `groups` parameter of the scatter plot might also do the job for you... But it's more limited than what Malte suggests.

**Comment by aditisk** [comment]
Thanks a lot @LuckyMD and @falexwolf.
