### ISSUE TITLE
Update setup.py to update dependent packages

### ISSUE THREAD

**Issue by shayanhoss** [scverse/scanpy#518]
After updating to the most recent version of scanpy, I had to separately update anndata, louvain, and leidenalg packages that are dependancies. Any dependent package updates of these types should just happen when the newest version is installed.

**Comment by falexwolf** [comment]
They should if you call
```
pip install scanpy[louvain] -U
```
anndata will also update if you call
```
pip install scanpy -U
```

The fact that we have `[igraph]` and `[louvain]` not in the default install is that they take quite a while.

If the docs are unclear about it, happy to have you point us to it: https://scanpy.readthedocs.io/en/latest/installation.html :)

**Comment by Zethson** [comment]
Closing because I consider the issue solved.
