### ISSUE TITLE
scvi integration

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/scanpy#520]
https://github.com/YosefLab/scVI/issues/206

**Comment by gokceneraslan** [comment]
I can help with that, too. I spent some time with scvi recently.

**Comment by falexwolf** [comment]
I'd love to have scVI integration! :)

**Comment by flying-sheep** [comment]
Should be super easy now that YosefLab/scVI#289 is merged

**Comment by LuckyMD** [comment]
We have SCVI working on anndata objects for data integration in our benchmarking study.
