### ISSUE TITLE
heatmap cluster-color bar 

### ISSUE THREAD

**Issue by ShobiStassen** [scverse/scanpy#521]
Hi,
I would like to set the scatterplot color palette and the heatmap cluster-color bar palette to be the same so that the clusters in the scatterplot are the same as those in the heatmap cluster-color-bar. I am using matplotlib to plot a scatterplot (using some other embedding) and need the cluster colors to match those in the automatic colorbar on the heatmap clusterbar.
If i globally set the palette using sc.set_figure_params() then the values of the heatmap plot also become the global cmap (rather than a gradient of red-blue or existing default)
Thanks for your help
Shobi

**Comment by fidelram** [comment]
In principle the scatter plot and the the heatmap use the same colors. See for example: https://scanpy-tutorials.readthedocs.io/en/latest/visualizing-marker-genes.html#Heatmaps 

The colors on the left are the same colors stored for the scatter plot clusters.

**Comment by ivirshup** [comment]
If the issue is continuous color maps, that can be specified with the `cmap` parameter.
