### ISSUE TITLE
adata.concatenate() only merges certain genes

### ISSUE THREAD

**Issue by tsotnech** [scverse/scanpy#529]
Hi guys,

I was trying to merge two different data sets from different experiments. 
adata1.X.shape (244, 5038)
adata2.X.shape (2218, 2007)
with adata.concatenate() 

I end up with 
adata3.X.shape (2462, 822)

It merges all the cells but removes lots of genes after concatenation. Just to double check, 
adata.concatenate only merges the genes that are present in both datasets? I know that certain genes are expressed in adata1 and not in adata2 data sets, but after merging I can't plot those genes cause they are removed. Is there a way to keep all the genes from both datasets and if certain gene isn't present in one of them just to assign 0 I guess? I don't know if this would be a right way...

Thanks a lot,

Tsotne

**Comment by gokceneraslan** [comment]
You can use join='outer' option of concatenate function to use the union of genes in the merged dataset.

**Comment by falexwolf** [comment]
Thanks Gökcen!
