### ISSUE TITLE
Getting Error Variable names are not unique when using .read_10x_h5 function

### ISSUE THREAD

**Issue by knapii-developments** [scverse/scanpy#534]
Good Evening,

My goal here is to get either a Gene barcode or dense matrix from a .h5 file from 10x. I'm currently trying to use the .read_10x_h5() function to help me achieve this. To my understanding I just need to input the file name into the function. When I run my code (See below), I get an error stating that "Variable names are not unique. To make them unique, call `.var_names_make_unique`."  From the documentation I don't see a way that I can call .var_names_make_unique(). Is there some preprocessing that I'm missing?

```python
user_input = input("Enter the path of your file: ")
def convert_h5_to_adata(filename):
    filename = str(filename)
    if os.access(filename, os.R_OK):
        sc.read_10x_h5(filename)
        return
convert_h5_to_adata(user_input)
```

**Comment by LuckyMD** [comment]
Hi @knapii-developments,

You are missing a return value for the `sc.read_10x_h5()` function. That function will return your anndata object. You can call `.var_names_make_unique` on that object like this:
```
adata = sc.read_10x_h5(filename)
adata.var_names_make_unique()
```

**Comment by knapii-developments** [comment]
Thanks @LuckyMD.

When I ran the script, I noticed that the output of adata.X is 0 based and not 1 based. Is that expected? When [reading](https://kb.10xgenomics.com/hc/en-us/articles/115000794686-How-is-the-MEX-format-used-for-the-gene-barcode-matrices-) about the MEX format, 10X does mention that the index in the MEX file is 1-based. It was surprising to see when I ran the function against a [sample dataset](https://support.10xgenomics.com/single-cell-gene-expression/datasets/3.0.0/pbmc_1k_protein_v3) from 10x to see 0s  in anndata.X. Can you provide your thoughts?

**Comment by zhenghy** [comment]
I got this same problem, how to doing?
