### ISSUE TITLE
Argument tab completion for sc.pl.umap-like functions?

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#535]
It'd be nice if some level of tab completion of argument names could be maintained for functions like `sc.pl.umap`. This came up recently in #455, and I find myself frequently misspelling (mostly mis-pluralizing) argument names like `color/ colors` and `gene_name/ gene_names`. I've given this a shot using `functools.wraps`, but no luck yet.

Any ideas on if we could do this @flying-sheep?

**Comment by flying-sheep** [comment]
I think to preserve the signature like that we could easily do a subset of what `update_wrapper` (and therefore `wraps`) does:

```py
def wraps_plot_scatter(wrapper):
    wrapper.__annotations__ = {
        k: v for k, v in plot_scatter.__annotations__.items()
        if k != 'basis'
    }
    wrapper.__wrapped__ = plot_scatter
    return wrapper

@wraps_plot_scatter
def umap(adata, **kwargs):
    """..."""
    return plot_scatter(adata, basis='umap', **kwargs)
```

but first: what did you try and why did it fail?

**Comment by ivirshup** [comment]
Here's pretty much what I've tried:

```python
import scanpy as sc
from functools import wraps, partial

pca = wraps(sc.pl.scatter)(partial(sc.pl.scatter, basis="pca"))
pca( #tried tab completion here
```

Tab completion shows:

<img width="597" alt="image" src="https://user-images.githubusercontent.com/8238804/54574990-8e796f80-4a46-11e9-8ad4-ae5aeead9604.png">

As opposed to:

<img width="598" alt="image" src="https://user-images.githubusercontent.com/8238804/54580161-fdf95a00-4a5a-11e9-9b51-8eeec17babfc.png">

**Comment by flying-sheep** [comment]
Hmm, doesn’t seem to work with `functools.partial`. It works if I do almost the same, but with a lambda:

```py
import scanpy as sc
from functools import wraps, partial

pca = wraps(sc.pl.scatter)(lambda *args, **kw: sc.pl.scatter(*args, basis="pca", **kw))
```

But I think the custom solution above is better anyway! `wraps` is if you really want to pose as the wrapped function, while we only want to inherit its signature.

**Comment by falexwolf** [comment]
Just wanted to mention that this would add much convenience. Since Fidel rewrote the plotting API, I saw that it was the right thing to do to reduce all the code in the almost-identical function headers, but  I was missing the autocomplete, which had obviously disappeared.

**Comment by flying-sheep** [comment]
The PR is in motion, seems to work well!
