### ISSUE TITLE
Scatter plot of numerical observation with missing data

### ISSUE THREAD

**Issue by fbnrst** [scverse/scanpy#536]
I have a dataset for which I have an observation that is only available for some cells. When I make a scatter plot that I color code for this observation not all cells are plotted:
```python
import random
import scanpy as sc

adata = sc.datasets.blobs()
adata.obs['property'] = 630 * [float("nan")] + 10 * [1] 

sc.tl.pca(adata)
sc.pl.pca(adata, color='property', size=50)
```
While this should plot 10 cells it only shows one cell:
![image](https://user-images.githubusercontent.com/7300030/54540172-caa1c700-4997-11e9-946e-01c1e04dd2d2.png)
I can get the plot I want by filtering cells first:
```python
sc.pl.pca(adata[adata.obs['property'] == 1], color='property', size=50)
```
![image](https://user-images.githubusercontent.com/7300030/54540221-e60cd200-4997-11e9-9b53-e9917bd01c59.png)
Would you agree that scanpy should plot all cells that have a valid observation?

**Comment by fidelram** [comment]
That's very strange. I will take a look

**Comment by fbnrst** [comment]
I just add the versions I used:
```python
sc.logging.print_versions()

scanpy==1.4 anndata==0.6.18 numpy==1.15.4 scipy==1.2.0 pandas==0.24.2 scikit-learn==0.20.2 statsmodels==0.9.0 python-igraph==0.7.1 louvain==0.6.1 
```

**Comment by fidelram** [comment]
the problem is that at some point the code calls np.argsort on a
pandas.Series and this returns -1 for NaN values. I will submit a PR to fix
this. Meanwhile, simpy plot as follows: sc.pl.pca(adata, color='property',
size=50, sort_order=False)
