### ISSUE TITLE
Updating scanpy

### ISSUE THREAD

**Issue by roshan9128** [scverse/scanpy#537]
I see that some functions have been deprecated and replaced by new ones. What is the simplest way to update Scanpy using conda?

**Comment by falexwolf** [comment]
There is no new release with these changes, yet. You'd need to install from github if you want them. However, these updates aren't critical and you can continue using the old functions without any bad conscience. A new release is obviously pushed to GitHub, PyPI and BioConda, and announced on twitter (https://twitter.com/falexwolf).
