### ISSUE TITLE
Issue using new features in the visualizing marker genes tutorial

### ISSUE THREAD

**Issue by aditisk** [scverse/scanpy#544]
Hello, I am trying to use the visualize marker genes tutorial to make some plots. I am importing scanpy in the new way (import scanpy as sc) as suggested in the tutorial but I am getting an error message:

AttributeError                            Traceback (most recent call last)
<ipython-input-5-dfc1e4d9ed06> in <module>()
----> 1 ax = sc.pl.correlation_matrix(adata, 'cell_types')

AttributeError: module 'scanpy.plotting' has no attribute 'correlation_matrix'

Here are the versions of all the packages I am using:
scanpy==1.4 anndata==0.6.17 numpy==1.16.0 scipy==1.2.0 pandas==0.23.4 scikit-learn==0.20.2 statsmodels==0.9.0 python-igraph==0.7.1 louvain==0.6.1 

Am I missing something ?

Thanks.

**Comment by fidelram** [comment]
I think that correlation matrix is only in the latest master version. You can install it using:
```
pip install git+https://github.com/theislab/scanpy.git
```

Also, be sure to load scanpy as 'import scanpy as sc'. If you use the old method (`import scanpy.api as sc`) it will not work.

**Comment by aditisk** [comment]
@fidelram thanks for letting me know. I am using the command you suggested and still getting an error:

CCBR-KULKAMILT:~ kulkarnia2$ pip install git+https://github.com/theislab/scanpy.git
Collecting git+https://github.com/theislab/scanpy.git
  Cloning https://github.com/theislab/scanpy.git to /private/var/folders/56/g1b462hs0d3816ktcj6twm8hmsw5ch/T/pip-req-build-o4lkd6tp
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Command "git clone -q https://github.com/theislab/scanpy.git /private/var/folders/56/g1b462hs0d3816ktcj6twm8hmsw5ch/T/pip-req-build-o4lkd6tp" failed with error code 1 in None

**Comment by aditisk** [comment]
I downloaded the folder from GitHub and then installed Scanpy and it worked for me.
