### ISSUE TITLE
heatmap does not have return_fig parameter

### ISSUE THREAD

**Issue by david758** [scverse/scanpy#545]
Hi,

the heatmap function treats return_fig as a kwarg parameter and raises "AttributeError: Unknown property return_fig". Does heatmap not actually support returning the figure even though the documentation states that function has this parameter? If so, how do I go about saving my heatmaps?

Thanks.

**Comment by flying-sheep** [comment]
Hi! Sorry, my bad. That parameter was undocumented, and I added it to the wrong docstring building block.

It’s available in all scatterplots for dimension reductions, like `pca`, `tsne` and so on.

**Comment by fidelram** [comment]
To save your heatmaps use the `save` argument.
