### ISSUE TITLE
Could not use Scanpy 0.4 to load AnnData file generated by v0.2.8

### ISSUE THREAD

**Issue by bli25wisc** [scverse/scanpy#56]
Recently I installed scanpy 0.4. However, with this new version I could not correctly load result files generated by an old version (v0.2.8). In particular, I could not load the old add_keys as uni_keys.

Any suggestions?

**Comment by falexwolf** [comment]
Dear Bo, sorry for the late response. I just became the father of twins a few days ago and couldn't respond earlier. If you still need an answer, I will look into this tomorrow. If you have `h5ls` installed on the command line, it would be great to show me the output of running `h5ls your_file.h5`.

**Comment by bli25wisc** [comment]
@falexwolf , congratulations!   I have already found a workaround. But if you want to support v0.2.8 format, I'm happy to provide the information you asked.

**Comment by falexwolf** [comment]
Thanks for the wishes! :)

If it's not much work for you: could you paste your workaround here? In my tests, the reading of old AnnData backing files worked fine, but I only tested from version to version... 0.2.8 is already quite old for the speed with which Scanpy evolves, so I probably missed something. In principle, Scanpy should be fully backward compatible; several people have written pipelines and stored files that still have to run with more recent versions of Scanpy.
