### ISSUE TITLE
pip installation - missing tools?

### ISSUE THREAD

**Issue by ltosti** [scverse/scanpy#560]
Hi there,

I was trying do dig down to understand the problem in #559 , and I found out that in my ```plotting/_anndata.py``` [these lines](https://github.com/theislab/scanpy/blob/f33924011f7d0a7924fada933e1a20d7b5ceaac3/scanpy/plotting/_anndata.py#L828-L837) and all the ones related to ```standard_scale``` are missing. So I created a new conda environment and tried to install a new version of scanpy, but this did not solve the issue (i.e. the problem is not with my old environment) as these lines are still missing. 

When I tried to replace the file and re-run my heatmap I got a different error:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-49e0357ed731> in <module>
----> 1 sc.pl.matrixplot(pbmc, marker_genes, groupby='bulk_labels', dendrogram=True, standard_scale='var')

/anaconda3/envs/test/lib/python3.6/site-packages/scanpy/plotting/_anndata.py in matrixplot(adata, var_names, groupby, use_raw, log, num_categories, figsize, dendrogram, gene_symbols, var_group_positions, var_group_labels, var_group_rotation, layer, standard_scale, swap_axes, show, save, **kwds)
   1644                                                            var_names=var_names,
   1645                                                            var_group_labels=var_group_labels,
-> 1646                                                            var_group_positions=var_group_positions)
   1647 
   1648         var_group_labels = dendro_data['var_group_labels']

/anaconda3/envs/test/lib/python3.6/site-packages/scanpy/plotting/_anndata.py in _reorder_categories_after_dendrogram(adata, groupby, dendrogram, var_names, var_group_labels, var_group_positions)
   2332     """
   2333 
-> 2334     key = _get_dendrogram_key(adata, dendrogram, groupby)
   2335 
   2336     dendro_info = adata.uns[key]

/anaconda3/envs/test/lib/python3.6/site-packages/scanpy/plotting/_anndata.py in _get_dendrogram_key(adata, dendrogram_key, groupby)
   2406 
   2407     if dendrogram_key not in adata.uns:
-> 2408         from ..tools._dendrogram import dendrogram
   2409         logg.warn("dendrogram data not found (using key={}). Running `sc.tl.dendrogram` "
   2410                   "with default parameters. For fine tuning it is recommended to run `sc.tl.dendrogram` "

ModuleNotFoundError: No module named 'scanpy.tools._dendrogram'
```
And indeed, in my scanpy this dendrogram tool is missing. 

Is the PyPi version missing something?

Thank you!

**Comment by gokceneraslan** [comment]
These are the features that are added recently in the development version of scanpy and therefore not in any released version. You can either install the development version from github using `pip install git+https://github.com/theislab/scanpy -U` or by following the instructions here https://scanpy.readthedocs.io/en/latest/installation.html#development-version. Note that the development version is more likely to be unstable.

Alternatively, you can browse the documentation of stable (released) version of scanpy (which is what you get when scanpy is installed via pip or conda) by selecting the `stable version` on the documentation page from the menu at the bottom left:

![image](https://user-images.githubusercontent.com/1140359/55020552-7026ed00-4fcd-11e9-8302-02a4f8f973ed.png)

**Comment by gokceneraslan** [comment]
@falexwolf @flying-sheep Do you guys think it makes sense to switch to "stable" in the documentation by default similarly to TensorFlow, PyTorch and Pandas which use stable by default?

**Comment by ltosti** [comment]
Thank you and sorry about the confusion, I remembered this was an option present in earlier releases, but I was wrong!

**Comment by falexwolf** [comment]
@gokceneraslan We had it switched to stable by default for some time already. I'm fine doing this again; I switched it back because I found some typos, etc., some missing explanation that I wanted to become immediately available...

**Comment by flying-sheep** [comment]
After another user had problems, I switched it over.
