### ISSUE TITLE
Cannot import scanpy in jupyter notebook with python 3.5.2

### ISSUE THREAD

**Issue by ontsilla** [scverse/scanpy#561]
Hello,

I'm having troubles with importing scanpy in my jupyter notebook. I am working on a server which has python 3.5.2 installed, and unfortunately I cannot update it.

I am getting this issue:

```pytb
import scanpy as sc
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-111-0074c9bc0b31> in <module>()
----> 1 import scanpy as sc

~/.local/lib/python3.5/site-packages/scanpy/__init__.py in <module>()
     29 
     30 # the actual API
---> 31 from . import tools as tl
     32 from . import preprocessing as pp
     33 from . import plotting as pl

~/.local/lib/python3.5/site-packages/scanpy/tools/__init__.py in <module>()
      8 from ._rank_genes_groups import rank_genes_groups
      9 from ._dpt import dpt
---> 10 from ._leiden import leiden
     11 from ._louvain import louvain
     12 from ._sim import sim

~/.local/lib/python3.5/site-packages/scanpy/tools/_leiden.py in <module>()
     29     n_iterations: int = -1,
     30     partition_type: Optional[Type[MutableVertexPartition]] = None,
---> 31     copy: bool = False,
     32     **partition_kwargs
     33 ) -> Optional[AnnData]:

/usr/lib/python3.5/typing.py in __getitem__(self, arg)
    647     def __getitem__(self, arg):
    648         arg = _type_check(arg, "Optional[t] requires a single type.")
--> 649         return Union[arg, type(None)]
    650 
    651 

/usr/lib/python3.5/typing.py in __getitem__(self, parameters)
    550             parameters = (parameters,)
    551         return self.__class__(self.__name__, self.__bases__,
--> 552                               dict(self.__dict__), parameters, _root=True)
    553 
    554     def __eq__(self, other):

/usr/lib/python3.5/typing.py in __new__(cls, name, bases, namespace, parameters, _root)
    510                 continue
    511             if any(isinstance(t2, type) and issubclass(t1, t2)
--> 512                    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
    513                 all_params.remove(t1)
    514         # It's not a union if there's only one type left.

/usr/lib/python3.5/typing.py in <genexpr>(.0)
    510                 continue
    511             if any(isinstance(t2, type) and issubclass(t1, t2)
--> 512                    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
    513                 all_params.remove(t1)
    514         # It's not a union if there's only one type left.

/usr/lib/python3.5/typing.py in __subclasscheck__(self, cls)
   1075                     return True
   1076                 # If we break out of the loop, the superclass gets a chance.
-> 1077         if super().__subclasscheck__(cls):
   1078             return True
   1079         if self.__extra__ is None or isinstance(cls, GenericMeta):

/usr/lib/python3.5/abc.py in __subclasscheck__(cls, subclass)
    223                 return True
    224         # Check if it's a subclass of a subclass (recursive)
--> 225         for scls in cls.__subclasses__():
    226             if issubclass(subclass, scls):
    227                 cls._abc_cache.add(subclass)

TypeError: descriptor '__subclasses__' of 'type' object needs an argument
```

I am also getting the same issue with import scanpy.api as sc. I believe this is a common issue with python 3.5.2 but unfortunately I cannot change the python version.

Thank you so much!
Olga

**Comment by ivirshup** [comment]
@ontsilla We can take a look at this, but I'm not sure if there will be a solution soon. Have you tried using [conda](https://conda.io/en/latest/miniconda.html) on this system? I think it might be your best bet here.

@flying-sheep I can recreate with:

```
conda create -yn testenv python=3.5.2
conda activate testenv
pip install scanpy
python -c "import scanpy" 
```

It looks like there were a lot of bug fixes to python's `typing` module between v3.5.2 and v3.5.4 ([changelog](https://docs.python.org/3.5/whatsnew/changelog.html#python-3-5-4rc1)). I don't get this error with v3.5.4. Are pre-bugfix versions of python supported?

**Comment by flying-sheep** [comment]
If someone figures out a simple workaround and submits a PR, we'll merge it, but we only support the newest bugfix releases ourselves.

You should definitely tell your sysadmin to update to Python 3.5.4, there are security holes in your version as well.

**Comment by ontsilla** [comment]
Thank you so much for the feedback!
I'll definitely talk to the admin, but I am not sure he would update.

Considering conda, I've tried using 
conda create -n scanpy python=3.6 scanpy
conda activate scanpy

It creates the environment, but then apparently I need to run a jupyter notebook from the terminal for the environment to be activated.  When trying to do it, I am getting a "Jupyter Notebook requires JavaScript" error, and I can't figure out how to solve it while connecting through ssh, because running "jupyter notebook --no-browser" generates a token I can use only on the local machine.

**Comment by ivirshup** [comment]
Hmm, that's strange. I use the generated token to connect to remote notebook servers pretty frequently. Any ideas why it isn't working for you?

Here's the workflow I follow. First, on the machine you'd like to work on, in the conda environment you want to use:

```
jupyter notebook --no-browser --port=8889
```

This will start the notebook server and report the security token. On my machine I create an ssh tunnel to the server with the following command (replacing `<remote_user>` and `<remote_host>` with your info):

```
ssh -N -L 8889:localhost:8889 <remote_user>@<remote_host>
```

Now I point my browser to `localhost:8889` and will be connected to the remote server, where it'll ask for the token. After pasting that in I'm connected.

**Comment by flying-sheep** [comment]
>  I'll definitely talk to the admin, but I am not sure he would update.

An admin that doesn’t take security risks seriously isn’t doing their job properly.

---

> Jupyter Notebook requires JavaScript

that probably means that Jupyter notebook tries to run lynx or www or sone other text-only browser. `jupyter notebook --no-browser` is correct and the tokens aren’t machine-specific.

[I set up stuff differently](https://jupyter-notebook.readthedocs.io/en/stable/public_server.html#automatic-password-setup), but @ivirshup’s setup should work perfectly as well.

**Comment by LuckyMD** [comment]
Just an extra idea... In case you have docker installed, you could use a dockerized scanpy. The guys running SCENIC have a dockerized version of it in their workflow. Maybe you could ask them nicely for their docker image?

**Comment by flying-sheep** [comment]
There’s also https://github.com/FASTGenomics/base_image_alpine_scanpy, but it hasn’t been updated in a while. Should be no big problem to update it though.

**Comment by ontsilla** [comment]
Thank you so much for all the suggestions and help! I finally managed to get it working with the conda environment.

**Comment by ivirshup** [comment]
No problem!
