### ISSUE TITLE
rank_genes_groups broken when `not use_raw`

### ISSUE THREAD

**Issue by flying-sheep** [scverse/scanpy#57]
`adata_comp` is only defined in the if branch:

https://github.com/theislab/scanpy/blob/61f3fe4b8ef16933750d6358c86bc15104d951a4/scanpy/tools/rank_genes_groups.py#L91-L93

**Comment by falexwolf** [comment]
thank you! is fixed in a4baaaf6c29b8da4f3d9026552719039d2600ca9, which is version 0.4.1
