### ISSUE TITLE
Purpose of the “stable” branch

### ISSUE THREAD

**Issue by flying-sheep** [scverse/scanpy#571]
Since we don’t have a chatroom yet, I’ll announce this with an issue.

I created the branch stable to have the 1.4 docs without development features, but also the scanpy logo:

```console
$ git checkout 1.4 -b stable
$ git cherry-pick 4b1504c c78de5b  # the logo commits
```

Once 1.4.1 comes along, we can simply delete it and readthedocs/stable will point to the 1.4.1 tag again

**Comment by falexwolf** [comment]
@flying-sheep, can you reset that stable points to 1.4 so that it automatically points to 1.4.1, now?

**Comment by flying-sheep** [comment]
sure, but it’s really easy, one can just delete the branch at https://github.com/theislab/scanpy/branches

```bash
git checkout stable
git reset --hard 1.4.1
git push -f
```

**Comment by falexwolf** [comment]
Thanks!
