### ISSUE TITLE
Docs Enhancements

### ISSUE THREAD

**Issue by falexwolf** [scverse/scanpy#58]
- [x] It would be better to refer to the anndata docs for the AnnData class (http://anndata.readthedocs.io/en/latest/anndata.AnnData.html) whenever `:class:~scanpy.api.AnnData` appears. `:class:AnnData <http://anndata.readthedocs.io/en/latest/anndata.AnnData.html>` has the correct css style, but does not hyperlink. Probably a solution via http://www.sphinx-doc.org/en/1.5.1/ext/extlinks.html together with the definition of an `:extclass:` role that inherits the `:class:` properties would be the correct way to do it.
- [x] A few references, like "[Traag1723]" are not rendered correctly... Who knows what's going on there. I couldn't figure it out with a few tests... Let's see.
- [x] the Neighbors class docstring doesn't render properly
- [ ] changing to the slim docstring style from the numpy docstring style messes up readability when calling the docstring lookup in jupyter or other IDEs, hence I'd advocate for maintaining this information

## AnnData
- [x] `__init__` method appears in `AnnData`
- [x] `attributes` appear after `methods`

**Comment by falexwolf** [comment]
@flying-sheep 

As just discussed, I'm listing a few strange things in the docs in addition to the two above. (see firt post)

**Comment by flying-sheep** [comment]
Fixed stuff:

- [02e78bb025f9cd8d02cf6d39256fea008ec51d7f] Used intersphinx for links to `anndata.AnnData`
- [ead51644fb700b9d40c48a44e7eb53c678d872dd] Put the references first in the toctree to make the dodgy references resolve (i’d be happy if we didn’t have to do that. maybe a hidden toctree before the real one?)
- [8b612743b796f045da3fe7af57763c0a995aefdf] Fixed the [Neighbors class](http://scanpy.readthedocs.io/en/latest/api/scanpy.api.Neighbors.html) by removing the sections and incorporating a sphinx bugfix

- [theislab/anndata@828d7eb503863df8ec1926190da37c931daa5dd5] no idea about the attribute order in anndata: from what i can puzzle together, that order should be everywhere, as [the template](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/autosummary/templates/autosummary/class.rst) lists methods before attributes. so the question is: why isn’t the order like anndata’s in scanpy, numpy, scipy, …?
