### ISSUE TITLE
test_marker_overlap failing occasionally on travis

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#580]
The test `test_marker_overlap` keeps failing on the travis build for python 3.5. This seems to happen on the first build from a PR, but if the build is restarted it passes. Given that my `n=3` for this, it could also be random.

Grabbed the error log from #579 (build [1735.1](https://travis-ci.org/theislab/scanpy/jobs/514097606)):

```
_____________________________ test_marker_overlap ______________________________
    def test_marker_overlap():
        # Test all overlap calculations on artificial data
        test_data = sc.AnnData(X = np.ones((9,10)))
        test_data.uns['rank_genes_groups'] = dict()
        test_data.uns['rank_genes_groups']['names'] = np.rec.fromarrays(
            [['a', 'b','c','d','e'], ['a','f','g','h','i']])
        test_data.uns['rank_genes_groups']['pvals_adj'] = np.rec.fromarrays(
            [[0.001, 0.01, 0.02, 0.05, 0.6], [0.001, 0.01, 0.02, 0.05, 0.6]])
    
        marker_genes = {'type 1':{'a','b','c'}, 'type 2':{'a','f','g'}}
    
        t1 = sc.tl.marker_gene_overlap(test_data, marker_genes)
        t2 = sc.tl.marker_gene_overlap(test_data, marker_genes, normalize='reference')
        t3 = sc.tl.marker_gene_overlap(test_data, marker_genes, method='overlap_coef')
        t4 = sc.tl.marker_gene_overlap(test_data, marker_genes, method='jaccard')
        t5 = sc.tl.marker_gene_overlap(test_data, marker_genes, top_n_markers=2)
        t6 = sc.tl.marker_gene_overlap(test_data, marker_genes, adj_pval_threshold=0.01)
    
>       assert t1.iloc[1,1] == 3.0
E       assert 1.0 == 3.0
scanpy/tests/test_marker_gene_overlap.py:22: AssertionError
```

Here's a [gist](https://gist.github.com/ivirshup/6965ebe2530c4eac67aebf41c3961959) of the full output.

Any idea what's up @LuckyMD?

**Comment by LuckyMD** [comment]
I'm as puzzled as you are... We've been discussing this a bit here: #549 

I didn't really change anything of note when Travis started failing. And I have no idea why the test would result in a `1.0`. Do you know if there are any instructions on how to rebuild the test environment in conda? Is it just python 3.5 and scanpy from github?

**Comment by ivirshup** [comment]
@LuckyMD, I think you can get the docker environment travis uses.

* [Docker image for travis python env](https://hub.docker.com/r/travisci/ci-python)
* [Guide on running it](https://andy-carter.com/blog/setting-up-travis-locally-with-docker-to-test-continuous-integration)

I did this a couple years ago, but I know travis has changed a bunch since then. Another good first step would be to figure out if it only fails on the first build, and if caches are being used in any way.

Also, do the builds ever fail for forks? I don't think they've been failing [for me](https://travis-ci.org/ivirshup/scanpy/builds).

**Comment by LuckyMD** [comment]
Thanks for the docker image. I'll take a look at that when I can. I thought I had pinpointed the error via print statements in the tests and fixed it, but it's back now and when I put print statements the error is gone :/. Might try to experiment with Travis a bit by just pushing to #583.

I don't know much about Travis, so not sure how cache comes into play here... or how Travis builds work. I guess it'll be a bit of reading later.

Haven't tried forking to check what happens... good idea.

**Comment by ivirshup** [comment]
Yeah, I've definitely spent more time than I care to admit debugging travis by remote. Good luck!

Do you mind if I restart some of your old builds? I want to try and diff the outputs to see if the setup is different.

**Comment by LuckyMD** [comment]
I'm not entirely sure what you mean by restarting the old building (restarting travis from old commits?), but go ahead... anything that might help!

**Comment by ivirshup** [comment]
For builds on your fork there should be a button that lets you make travis just run a build again. Here's an example:

![image](https://user-images.githubusercontent.com/8238804/55601220-9148c400-57ab-11e9-94b3-8ec016e7b801.png)

**Comment by LuckyMD** [comment]
I see... thanks for the heads up. At the moment I'm working on branches of the main repo... but it's probably better practice to develop on my own fork.
