### ISSUE TITLE
`sc.pp.scale` returning matrix of nan?

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#581]
```python
import scanpy as sc
print(sc.__version__)  #  1.4+222.gdd052ed
a = sc.datasets.pbmc3k()
b = sc.pp.scale(a, copy=True)
# /Users/isaac/github/scanpy/scanpy/preprocessing/_simple.py:1105: RuntimeWarning: invalid value encountered in true_divide
#  X /= scale
a.X.data
# array([1., 1., 2., ..., 1., 1., 3.], dtype=float32)
b.X
# array([[nan, nan, nan, ..., nan, nan, nan],
#        [nan, nan, nan, ..., nan, nan, nan],
#        [nan, nan, nan, ..., nan, nan, nan],
#        ...,
#        [nan, nan, nan, ..., nan, nan, nan],
#        [nan, nan, nan, ..., nan, nan, nan],
#        [nan, nan, nan, ..., nan, nan, nan]], dtype=float32)
```

Seems off. Even if I've log-ed it or do it inplace the same thing happens.

**Comment by falexwolf** [comment]
Hm. Strange. This shouldn't have been touched. Let me look into this. Presumably due to non-filtering...

**Comment by ivirshup** [comment]
Probably is, I think the `nan`s are for all zero genes. But I think there's a better solution than a procedural warning and data that causes errors downstream.

**Comment by falexwolf** [comment]
The nans (with a proper warning) would be the right way but having data that causes downstream is not an option. As an intermediate solution, I added a note to the docs and made them zeros:
https://github.com/theislab/scanpy/commit/dce2be194a6ff865ecaeb939f3c990f6c3b0e244

**Comment by falexwolf** [comment]
Quick question to you @ivirshup, can't we simply replace all the `adata_neighbors` stuff with `scanpy.datasets.pbmc68k_reduced`? It already has the neighbor graph etc. in it and is smaller, that is, would speed up tests considerably.

**Comment by ivirshup** [comment]
Yeah, I was thinking even an error. Something that says "this operation doesn't really make sense with genes with no counts, so we're doing {}". On the other hand, I figure you can't go that wrong just doing what `sklearn` does, which is zeroes.

For sure! I'm trying to remember why I went with pbmc3k in the first place. I think I was getting a failure for pbmc3k but not the smaller one? In any case, this should be covered by `test_pbmc3k.py` notebook now.

Two quick related asides:

* It would be good to have tests that actually hit the parts of `neighbors` where non-pairwise distances are found (>4096 cells I think). 
* I've been pretty successful at speeding up the tests by just running them in parallel. Stuff like this might be good to have in some dev docs. Is there a place for that kind of thing right now?

**Comment by falexwolf** [comment]
Great!

I'll replace the dataset in the tests in that case.

> It would be good to have tests that actually hit the parts of neighbors where non-pairwise distances are found (>4096 cells I think).

We're just completely migrating to a shallow wrapper of umap there, where this is tested. I talked to Leland and he said it should be stable. At some point, we might move to `pynndescent` (when it get's introduced into umap). Long story short, I don't think we need to test the neighbors module within scanpy beyond testing the interface.

> I've been pretty successful at speeding up the tests by just running them in parallel. Stuff like this might be good to have in some dev docs. Is there a place for that kind of thing right now?

No, happy to have you put some dev docs in a location that you find sensible. :)

**Comment by falexwolf** [comment]
OK, the large dataset and processing is gone in `test_clustering`: https://github.com/theislab/scanpy/commit/fc24dfc62c049a0d0c9cc491d4647d03b52bfb10
