### ISSUE TITLE
Getting cell counts for cells with more than 1 label

### ISSUE THREAD

**Issue by aditisk** [scverse/scanpy#584]
Hello,

How can I get a count of cells that have multiple labels assigned to them ? For example, from cluster 9 (louvain label) I want to pick out just the cells that came from female patients (another adata.obs I have created) ? 

I also want to be able to do this with multiple labels and get counts for different groups of cells (having 5-6 labels attached to them) and I am not sure how to do this.

Any help is appreciated, thanks a lot.

**Comment by ivirshup** [comment]
If you want to get the number of cells, try something like:

```python
adata.obs.groupby(["louvain", "donor_sex"]).apply(len)
```

If you want the expression for that subset:

```python
cell_ids = (
    adata.obs
         .loc[lambda x: x["louvain"] == "9"]
         .loc[lambda x: x["donor_sex"] == "female"]
    ).index
adata[cell_ids, :]
```

**Comment by LuckyMD** [comment]
For just two covariates I find `pd.crosstab()` quite helpful as well.

**Comment by aditisk** [comment]
Thanks a lot @ivirshup and @LuckyMD. I will try these methods out.

**Comment by aditisk** [comment]
@LuckyMD is this the correct way of using pd.crosstab() ? I am getting an error as seen below:

adata_fibro.crosstab("patient_id","louvain", rownames=['louvain'], colnames=['patient_id'])

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-95-d09a5110597d> in <module>()
----> 1 adata_fibro.crosstab("patient_id","louvain", rownames=['louvain'], colnames=['patient_id'])

AttributeError: 'AnnData' object has no attribute 'crosstab'

**Comment by aditisk** [comment]
@ivirshup as you suggested I tried using this function for getting counts of # of cells in each cluster for each patient.
But in my case I have 17 patients and 8 clusters so I am losing some information in the middle and at the end of the list. I thought it was a caveat of printing to the console in my iPython notebook so I tried to save the output and then write it to a file but I am still missing some values. Do you know if there is some kind of limit on this type of calculation ?

**Comment by ivirshup** [comment]
`pd.crosstab` is a function from `pandas`, and would only work on a pandas dataframe. You can find some documentation on that [here](http://pandas.pydata.org/pandas-docs/stable/user_guide/reshaping.html#cross-tabulations).

I'm not sure why you would be losing any info. I'd also note this seems less related to scanpy, and more related to pandas, since `adata.obs` is just a pandas dataframe. Have you tried looking through the [pandas user guide](https://pandas.pydata.org/pandas-docs/stable/) to figure out how to do what you want?

**Comment by LuckyMD** [comment]
@ivirshup already answered on how to use `pd.crosstab()`, but just to give a quick example for your case:
`pd.crosstab(adata_fibro.obs['patient_id'], adata_fibro.obs['louvain'])`
should work.

**Comment by aditisk** [comment]
@ivirshup Thanks for your input and suggestion. I was looking more into Scanpy documentation rather than pandas but I will check that out in the future.

@LuckyMD thanks for the example, it works for me now and using pd.crosstab() is very handy so thanks a lot for the suggestion.
