### ISSUE TITLE
color persistence in violin plot fails when keys not present in all batch groups

### ISSUE THREAD

**Issue by JuHey** [scverse/scanpy#589]
Observation:  `sc.pl.violin(adata.obs['batch'] == 'batch_no'], keys = 'gene_of_interest', groupby = 'desc_0.8', palette = 'Set2')` gives inconsistent color mapping when comparing plots between different batch_no and especially if a gene_of_interest (GOI) is absent in a cluster; that seems to upset the color registration.

<img width="290" alt="image" src="https://user-images.githubusercontent.com/36309128/55530566-a0792600-5674-11e9-8088-89c0029847b2.png">

versus:

<img width="301" alt="image" src="https://user-images.githubusercontent.com/36309128/55530580-aa9b2480-5674-11e9-927c-6acda646cf7c.png">

In the upper plot, cluster -6- is skipped as possibly no value is generated for the GOI/batch combination that was interrogated. In contrast, the bottom plot shows the result of a different batch slice with the same GOI. There, distributions for the GOI are present in all clusters. Noticeably, skipping cluster six in the top plot, brings the color mapping out of order when compared with the plot below.

This is annoying if one likes to compare the output of many violin plots of that sort.

Is there a way to 'hard-code' the desired association between color value and in this case the cluster number (0 to 13 here). As there is no adata.uns['desc_0.8_colors'], I am afraid that I do not know where to start here.

**Comment by ivirshup** [comment]
This was a bug in anndata, which should be fixed now. Sorry about the late response!
