### ISSUE TITLE
Identify optional dependencies

### ISSUE THREAD

**Issue by flying-sheep** [scverse/scanpy#59]
E.g. matplotlib is only necessary when plotting, and for e.g. Docker images, it would be useful to have a slim scanpy core.

An idea would be to do it like Jupyter:

- A `scanpy-core` PyPI package with just the essentials.
- A `scanpy` metapackage, which depends on `scanpy-core` and most (or all) of the optional dependencies.

Users doing `pip install scanpy` will get the full package, with no annoying runtime errors, and packagers needing flexibility get `scanpy-core` and can slim everything down as needed.

cc @hensing

**Comment by falexwolf** [comment]
Sounds like a great idea! Currently, `pip install scanpy` avoids installing the C++ dependencies, which give some users trouble: `louvain` and `python-igraph`. I think that these should still remain optional dependencies: users should be able to do some basic analysis with plotting without having to install C++ dependencies. They can then continue to install optional dependencies, if they like.

**Comment by flying-sheep** [comment]
so you would want three installations, right?

- full (by manually installing all optional dependencies)
- uncomplicated but limited
- super barebones

since `scanpy` is already the second version, we don’t lose anything this way.

in the future maybe we can achieve that `scanpy` becomes the full installation (once the C++ dependencies start shipping wheels)

**Comment by falexwolf** [comment]
Yes, I think that would be the best solution for the time during which we rely on packages which do not ship proper wheels... 

I agree that in the future, `scanpy` could become the full installation.

Why not `scanpy-core`, `scanpy`, `scanpy-full`? I don't think it will bother anyone if we stop supporting `scanpy-full` at some point and only use `scanpy`.

Given how Scanpy is set up and used, I could also imagine that, upon growing, it will become in some parts even more a thin wrapper for packages that should be optionally installed (it is already a thin wrapper  for `igraph`, `louvain` and `MulticoreTSNE`, where Scanpy simply makes the usage more convenient by unifying visualization etc. and efficient by reusing input parameters that have previously been computed and used in other parts of Scanpy - right now, essentially all the preprocessing, the neighborhood relations and graph stuff). 

What do you think?

**Comment by flying-sheep** [comment]
sure!

as long as the last version of `scanpy-full` does nothing but depend on `scanpy`, nobody will suffer any consequences if it becomes obsolete one day.
