### ISSUE TITLE
All-zero genes show up as white columns in matrixplots if standard_scale='var' is given

### ISSUE THREAD

**Issue by gokceneraslan** [scverse/scanpy#590]
Looks like this:

![image](https://user-images.githubusercontent.com/1140359/55589119-7ddf1f80-56fd-11e9-9496-a4da41ec2e50.png)

Not that it's wrong but it'd be prettier to show as regular as a regular grid.

**Comment by flying-sheep** [comment]
Hmm, I think it’s a nice visual indicator that there’s just nothing at all. Don’t you agree?

**Comment by gokceneraslan** [comment]
I'm not sure really, it's also all white in other colormaps. The reason actually is a bug:

`mean_obs /= mean_obs.max(0).fillna(0)`

This doesn't fill NAs. It should be 

`mean_obs = (mean_obs / mean_obs.max(0)).fillna(0)`

😄

**Comment by flying-sheep** [comment]
Is is possible to give NAs their own color instead? I mean, they probably mean 0 in many cases, but not always, right?

**Comment by fidelram** [comment]
@gokceneraslan Can you add a PR with the fix?
@flying-sheep Any good idea on how to set a color for NAs without having to add one more parameter to the visualizations (this problem is probably shared by matrixplot and dotplot)

**Comment by flying-sheep** [comment]
heatmap passes additional kwargs to [`imshow`](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.imshow.html) which accepts `cmap`. You can pass a [ColorMap](https://matplotlib.org/api/_as_gen/matplotlib.colors.Colormap.html#matplotlib.colors.Colormap) you’ve called [`set_bad`](https://matplotlib.org/api/_as_gen/matplotlib.colors.Colormap.html#matplotlib.colors.Colormap.set_bad) on.

**Comment by gokceneraslan** [comment]
> @gokceneraslan Can you add a PR with the fix?

Done, see #597 .
