### ISSUE TITLE
how can  it been installed if linux env dose not have a GUI and Tkinner, and I only have a user account

### ISSUE THREAD

**Issue by SeqCrafter** [scverse/scanpy#595]

**Comment by ivirshup** [comment]
You could use conda ([relevant docs](https://scanpy.readthedocs.io/en/stable/installation.html#bioconda)).

Not having a GUI shouldn't matter, but I'm not sure if Tkinter is an installation dependency for `matplotlib`. If you're getting an error related to an interactive backend when you try to plot, you can switch the [matplotlib backend](https://matplotlib.org/faq/usage_faq.html#what-is-a-backend).

**Comment by flying-sheep** [comment]
Yes, switching the backend should definitely work. Pay attention to the infos in @ivirshup’s link, specifically:

> If you use the use() function, this must be done before importing matplotlib.pyplot. Calling use() after pyplot has been imported will have no effect.

which also applies to importing scanpy, seaborn, and so on.

**Comment by ivirshup** [comment]
@panxiaoguang, did this help solve your problem?

**Comment by SeqCrafter** [comment]
> @panxiaoguang, did this help solve your problem?

Thank you very much ,it worked.

**Comment by ivirshup** [comment]
No problem, thanks for the quick response!
