### ISSUE TITLE
filter cells by a specific gene value

### ISSUE THREAD

**Issue by koalap-2018** [scverse/scanpy#599]
Hi guys,

I would like to filter cells by an arbitrary threshold set on the expression of a specific gene (elav) at the very begging of the pipeline. I am new to scanpy and relatively new to python. 

this is what I do at the begining but I am having trouble getting it to work (see third command) with setting the corresponding threshold:

#filtering by n_genes and percent mito
adata = adata[adata.obs['n_genes'] < 3500, :]
adata = adata[adata.obs['percent_mito'] < 0.5, :]

#filtering by elav
adata = adata[adata.var['elav'] > 0.5, :]

This last part doesn't seem to work. All help appreciated!

**Comment by Xparx** [comment]
Try

```
adata = adata[adata[: , 'elav'].X > 0.5, :] 
```

`var` only contain the metadata for the genes. The expression is housed in `X`, just as the metadata for the observations (cells) are stored in `obs`.

And you should be able to index adata with gene names directly as `adata[:, <list of names>]`. if they exist in the `var_names` list, `adata.var_names`.

**Comment by chansigit** [comment]
For me,
adata[(adata[:,'elav'].X>0).flatten(), : ] works

otherwise, it gives error.

**Comment by ivirshup** [comment]
This issue has been mentioned on **Scanpy**. There might be relevant details there:

https://scanpy.discourse.group/t/filtering-cells-by-expression-of-specific-gene/256/2

**Comment by jackbrougher** [comment]
Is there a way to filter for a set of genes, where if any  one of the genes in a list are expressed, those cells will be plotted? I've tried switching Xparx's solution to a list, but receive the error "ValueError: Buffer has wrong number of dimensions (expected 1, got 0)"

I've also tired chansigit's method, but find that flatten returns as not found?
