### ISSUE TITLE
latest version error

### ISSUE THREAD

**Issue by vladie0** [scverse/scanpy#601]
Dear developers, 

in an attempt to instal the latest version of scanpy from GitHub (Master branch), I receive the following error:

Traceback (most recent call last):
  File "/home/vladie/PycharmProjects/PY3/RPE_MYCN_10X.py", line 4, in <module>
    import scanpy.external as sce
  File "/usr/local/lib/python3.6/dist-packages/scanpy/__init__.py", line 33, in <module>
    from . import datasets, logging, queries, external
  File "/usr/local/lib/python3.6/dist-packages/scanpy/external/__init__.py", line 1, in <module>
    from . import tl
  File "/usr/local/lib/python3.6/dist-packages/scanpy/external/tl.py", line 4, in <module>
    from ._tools._palantir import palantir
ModuleNotFoundError: No module named 'scanpy.external._tools'

I would like to run palentir through Scanpy, is this already possible ? 
Kind regards,
Vladie0

**Comment by ivirshup** [comment]
Looks like the same error hit in #585, as well as https://github.com/theislab/scanpy/pull/493#issuecomment-477674448.

@flying-sheep I haven't been able to reproduce, but maybe we should just throw an `__init__.py` in there, since it fixes this for @fbrundu, before the `v1.4.1` release?

**Comment by flying-sheep** [comment]
Sure, why not? It’s not a bug though :wink:

**Comment by ivirshup** [comment]
@vladie0, would you mind pulling again and checking if it works now?

@flying-sheep if at least four people can't install the package (including in a clean conda environment on a lab mate's machine), what do you call it? I don't think it's our fault, but I think there's a bug somewhere.

**Comment by flying-sheep** [comment]
Of course, sorry: It’s not *our* bug. I think the bug label means “we have/had a bug and need(ed) to fix it” and not “we’re catching and working around bugs in people’s setups”
