### ISSUE TITLE
Remove white margins from heatmap

### ISSUE THREAD

**Issue by evafast** [scverse/scanpy#606]
Hi!

I recently upgraded to scanpy 1.4 and did not encounter this issue in previous versions. I am trying to generate a heatmap using the following function:
sc.pl.rank_genes_groups_heatmap(adata, n_genes=4, use_raw=True, swap_axes=True)

For some reason I am getting white margins on the right and left side which results in misalignment of the colormap identifying my clusters on the bottom and the above heatmap.

![image](https://user-images.githubusercontent.com/7358001/56063815-58c26080-5d3e-11e9-8935-258760c1b0eb.png)

I get the same result if I just use sc.pl.heatmap and do a groupby with the clusters. 

Any idea how to fix this issue would be most appreciated!

Thanks!!!

Eva

scanpy==1.4 anndata==0.6.19 numpy==1.15.4 scipy==1.1.0 pandas==0.23.4 scikit-learn==0.19.2 statsmodels==0.9.0 python-igraph==0.7.1 louvain==0.6.1 
matplotlib == 2.2.3

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.0.final.0
python-bits: 64
OS: Windows
OS-release: 8.1
machine: AMD64
processor: Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.4
pytest: 3.8.0
pip: 19.0.3
setuptools: 40.2.0
Cython: 0.28.5
numpy: 1.15.4
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.5.0
sphinx: 1.7.9
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.8
feather: None
matplotlib: 2.2.3
openpyxl: 2.5.6
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.1.0
lxml: 4.2.5
bs4: 4.6.3
html5lib: 1.0.1
sqlalchemy: 1.2.11
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

**Comment by fidelram** [comment]
Do you also get the problem when trying the examples here: https://scanpy-tutorials.readthedocs.io/en/latest/visualizing-marker-genes.html?

Can you make a small example to reproduce the problem?

**Comment by evafast** [comment]
Hi, 
I tried several things, including updating matplotlib. The problem is gone for both with the example data and my own. Thanks for your help!
Eva
