### ISSUE TITLE
single molecule sequencing

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/scanpy#607]
Dear,
Scanpy are winning more and more popularity since it's first release in single cell sequencing field. Now single molecule sequencing is growing fast, do you plan to develop a python package for single molecule sequencing analysis (both Nanopore and PacBio) ?

**Comment by flying-sheep** [comment]
Why would a separate package be necessary? If you use it for transcriptome analysis, the only difference should be that the counts are (in theory) more accurate and there’s e.g. no need for methods that are adapted for zero-inflation.
