### ISSUE TITLE
AnnData cannot be row-sliced after tl.diffmap

### ISSUE THREAD

**Issue by hjp34** [scverse/scanpy#62]
I want to split AnnData after tl.diffmap according to each cell's library. But it appears that row-slicing AnnData after diffmap, dpt, or louvain gives the error message `AttributeError: 'AnnData' object has no attribute '_n_obs'`.  But AnnData.X and AnnData.obs can be sliced. Could you please give me advice?

```py
>>> adata = sc.read_10x_h5('filtered_gene_bc_matrices_h5.h5', 'mm10')
>>> scanpy.api.tl.diffmap(adata)
>>> adata_diffmap[:, 0]
View of AnnData object with n_obs × n_vars = 5000 × 1
>>> adata_diffmap[0, :] 
AttributeError: 'AnnData' object has no attribute '_n_obs'
```

**Comment by falexwolf** [comment]
Sorry about this bug in AnnData views, which have only recently been introduced. Is fixed in anndata 0.4.4 `pip install anndata --upgrade` and on the master branch: https://github.com/theislab/anndata/commit/ba9b3eed381ce427920ec67e13331d5423a5d9b3.
