### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by Khalid-Usman** [scverse/scanpy#627]
Hi, 
I am using weighted sampling data as input of 

> scanpy , but i didn't find any help when i have a distinct weight for each observation. So I modified few of the 

> scanpy

 files. 

`use_weights` is a boolean parameter either your data is weighted or not, if weighted then it will calculated weighted mean and weighted variance, in other case it will be same as previous. `Default is False`

`weights` is a 1D weight vector, where each row is weight of observation in original matrix. `Default is None`

I have attached the updated files and tested with well. But you can test again for adding into your tool. 

Thanks
[Weighted_Sampling.zip](https://github.com/theislab/scanpy/files/3134213/Weighted_Sampling.zip)

**Comment by flying-sheep** [comment]
Hi! Thank you for your contribution!

Maintaining scanpy is a lot of work, so we like to rely on GitHub to help us here. Please read up on how to use github so you can [create a pull request](https://help.github.com/en/articles/creating-a-pull-request) with your changes.

**Comment by Khalid-Usman** [comment]
Thanks for your reply.

I have modified code and sent a pull request, but it seems that test is
failed, but i don't know why test is failed. I have double check my code,
its fine.

Thanks ,
Waiting for your reply.

Regards,
Khalid
