### ISSUE TITLE
Error in tl.rank_genes_groups

### ISSUE THREAD

**Issue by hjp34** [scverse/scanpy#63]
I found that running the function 'tl.rank_genes_groups' gives the error the following error message:
UnboundLocalError: local variable 'adata_comp' referenced before assignment.

![scanpy api tl rank_genes_groups_error](https://user-images.githubusercontent.com/35155633/34642043-0191dce0-f305-11e7-847f-37b1ff34a77d.png)

**Comment by falexwolf** [comment]
thank you! the bug was fixed in https://github.com/theislab/scanpy/commit/a4baaaf6c29b8da4f3d9026552719039d2600ca9 and release 0.4.1: `pip install scanpy --upgrade`
