### ISSUE TITLE
scanpy.pp.normalize_total

### ISSUE THREAD

**Issue by ghost** [scverse/scanpy#631]
Hello, I used the method normalized_total with a sparse matrix and inplace=False but it returned always None.
I think that the problem is this command in the function _normalize_data: 
X = sparsefuncs.inplace_row_scale(X, 1/counts)

this should be replaced with:

sparsefuncs.inplace_row_scale(X, 1/counts)

is it correct?
Thank you.

**Comment by falexwolf** [comment]
@Koncopd, could you look into this?

**Comment by Koncopd** [comment]
@rbioinfo yes, you are right, thank you for noticing this.
@falexwolf fixed.

**Comment by ghost** [comment]
No problem, I think that the change is not present in the version 1.4.2, I tried the github code and also the pip version.
Thank you.

**Comment by Koncopd** [comment]
It should work if you install from github.
https://github.com/theislab/scanpy/commit/fe2580cb58e2ad6312ea989b0c9a40351510051a

**Comment by ghost** [comment]
Thanks

**Comment by falexwolf** [comment]
Thanks!
