### ISSUE TITLE
Losing transcripts during analyses

### ISSUE THREAD

**Issue by kt6k** [scverse/scanpy#634]
This may already have been discussed elsewhere...

It appears that I am loosing a bunch of genes/transcripts during the Velocyto analysis, and I am trying to figure out what is going on. After running Velocyto, there are approximately 5000 final filtered transcripts (presumably ones used for the vector calculation). However, several genes/transcripts of interest that should be highly expressed in most cells (seen using software like Seurat) are not listed in the final filtered genes. Thus, I am suspecting that many genes/transcripts are, for some reason, being lost during Velocyto calculation.

Does Velocyto filter out genes that are not differentially expressed (namely, genes/transcripts that are not useful to plot vector)?

My cells are captured using Fluidigm.

Very much appreciated.

**Comment by gokceneraslan** [comment]
Sorry, are you referring to https://github.com/theislab/scvelo? Scanpy does not have any builtin function regarding RNA velocity.

**Comment by ivirshup** [comment]
Closing as this seems specific to velocyto
