### ISSUE TITLE
sc.pl.heatmap doesn't align boundaries well

### ISSUE THREAD

**Issue by brianpenghe** [scverse/scanpy#637]
I ran this:
`ax=sc.pl.heatmap(Mouse10Xdata[NewIndex3,:], sorted_unique_marker_genes, groupby='ident',
              use_raw=False, vmin=-3, vmax=3, cmap='bwr',show=True,swap_axes=True,figsize=(10,7),
              var_group_rotation=0, dendrogram=True, save='ClusterMap.png')`

But the image has something weird. Here are the snapshots:
![image](https://user-images.githubusercontent.com/4110443/57493149-b5705700-72bb-11e9-8d2d-e02c083aeda2.png)
The lines don't align well with the heatmap. 

Additionally, the lines don't align well with the group ID colors, either
![image](https://user-images.githubusercontent.com/4110443/57493206-e94b7c80-72bb-11e9-9bd8-80cdaa8c0754.png)

And the ID colors seem to be not aligned well with the heatmap either.

Any thoughts?

**Comment by fidelram** [comment]
There was a similar report not so long ago but I have not been able to reproduce the issue. 

Seems to be related with the matplotlib version used. Maybe you can try to update to the latest version.

**Comment by brianpenghe** [comment]
> There was a similar report not so long ago but I have not been able to reproduce the issue. Seems to be related with the matplotlib version used. Maybe you can try to update to the latest version.
> […](#)
> On 10 May 2019, at 01:38, brianpenghe ***@***.***> wrote: I ran this: ax=sc.pl.heatmap(Mouse10Xdata[NewIndex3,:], sorted_unique_marker_genes, groupby='ident', use_raw=False, vmin=-3, vmax=3, cmap='bwr',show=True,swap_axes=True,figsize=(10,7), var_group_rotation=0, dendrogram=True, save='ClusterMap.png') But the image has something weird. Here are the snapshot: The lines don't align well with the heatmap. Additionally, the lines don't align well with the group ID colors, either And the ID colors seem to be not aligned well with the heatmap either. Any thoughts? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

I have been using matplotlib 3.0.3 and I believe it's the latest version already. My Scanpy version was 1.4.1.  
Can it be an issue about duplicated gene names/make unique?

**Comment by fidelram** [comment]
In your heat map the lines are separating categorical groups right? In other words genes are rows. 

In your command you are doing a selection over a larger dataset. Have you tried to make a copy of the adata object?

adata = Mouse10Xdata[NewIndex3,:].copy()

I ask in case the categories reported in the selection that you are doing create a mismatch, which may be solved by doing a copy.

**Comment by fidelram** [comment]
Any update?

**Comment by brianpenghe** [comment]
> Any update?

I tried that but it's still giving me exactly the same tree : (

**Comment by wangjiawen2013** [comment]
I met the same issue too. I have to adjust the lines manually with Adobe Illustrator.

**Comment by brianpenghe** [comment]
> I met the same issue too. I have to adjust the lines manually with Adobe Illustrator.

You can't do that, because the columns are messed up and don't align with the column labels. It's a three-body problem.

**Comment by fidelram** [comment]
In the tests that I have the heatmap seems to be ok. See https://scanpy-tutorials.readthedocs.io/en/latest/visualizing-marker-genes.html#Visualize-marker-genes-using-heatmap

Do you think that the problem occurs when lot of cells/genes are plotted?

**Comment by brianpenghe** [comment]
> In the tests that I have the heatmap seems to be ok. See https://scanpy-tutorials.readthedocs.io/en/latest/visualizing-marker-genes.html#Visualize-marker-genes-using-heatmap
> 
> Do you think that the problem occurs when lot of cells/genes are plotted?

It's possible.

**Comment by wangjiawen2013** [comment]
The test is not good neither. If you look carefully at the heatmap generated with sc.pl.rank_genes_groups_heatmap(pbmc, n_genes=3, standard_scale='var'), you would find it is not aligned perfectly, especially for the local magnified heatmap. @fidelram @brianpenghe 
![Figure_1](https://user-images.githubusercontent.com/29703450/62337090-c4a32180-b505-11e9-8757-73bc248d7754.png)
![1](https://user-images.githubusercontent.com/29703450/62337095-c66ce500-b505-11e9-8391-74b7b9948ab2.png)

**Comment by fidelram** [comment]
The lines should be aligned now. They were are centered now with respect to the boundary.
