### ISSUE TITLE
Plotting signature genes

### ISSUE THREAD

**Issue by bioguy2018** [scverse/scanpy#638]
Dear all,
I am  very interested to set my own set of markers and see the expression of those markers in my umap. So I basically want to see expression of multiple signature genes in one plot. since I am new to python and scanpy I am not sure how can it be done and if there is already a function for that.
In R I had a similar situation in which I just took the avg expression of those cells and treated them as on feature and plotted them but here I am not how can it be efficiently done!

Any help would be very appreciated thanks!

**Comment by tilofrei** [comment]
Hi @bioguy2018, if I understand you correctly a similar question was asked [here before](https://github.com/theislab/scanpy/issues/532). To sum it up you would need:

````
# calculate score: option 1
sc.tl.score_genes(adata, gene_list, score_name='my_score') 
# option 2
adata.obs['my_score'] = adata.X[:,my_genes].sum(1) # as a more common alternative use mean()

# drawing graph
sc.pl.umap(adata, color='my_score').

**Comment by bioguy2018** [comment]
Thanks a lot!

**Comment by tilofrei** [comment]
Hi, thanks for the feedback! Another interesting option is [AUCell](https://github.com/aertslab/pySCENIC/blob/master/src/pyscenic/aucell.py) from the [SCENIC workflow](https://www.nature.com/articles/nmeth.4463) that does the comparison based on ranked gene expression - haven't tried it myself though. Best wishes

**Comment by bioguy2018** [comment]
@tilofreiwald Thanks a lot! I will try it out and will write my experience here soon!
