### ISSUE TITLE
sc.pp.scale(adata) generates NaN error

### ISSUE THREAD

**Issue by hjp34** [scverse/scanpy#64]
I encountered this error when using data with a relatively small number of cells (~2,600). I have not encountered this error with my previous data with more cells (>10,000).

![sc pp scale_error](https://user-images.githubusercontent.com/35155633/34744836-6f325a80-f586-11e7-963f-34d14c1e1399.png)

**Comment by falexwolf** [comment]
Sorry about me having totally forgot about this. This is probably due to the fact that you're trying to scale genes that have zero standard deviation. If you do some very basic filtering, you should never  run into this problem.
