### ISSUE TITLE
Error after normalization with scran

### ISSUE THREAD

**Issue by SamueleSoraggi** [scverse/scanpy#641]
Hej

I have been looking at the single-cell-tutorial repository and tried the `scran` normalization with `R`.
After calculating the size factors in `scran`, I use them to normalize cell-wise my data matrix following the tutorial commands:

```
adata.X /= adata.obs['size_factors'].values[:,None]
sc.pp.log1p(adata)
```
When I look for highly expressed genes with

`sc.preprocessing.highly_variable_genes(adata, n_top_genes=5000)`

I get this error (the error does not show up when I use the normalization command from `scanpy` instead of the normalization with size factors from `scran`):

```
LinAlgError                               Traceback (most recent call last)
<ipython-input-97-96c692867dde> in <module>
----> 1 sc.preprocessing.highly_variable_genes(adultAll, n_top_genes=10000, flavor='cellranger')

~/miniconda3/envs/scRNA/lib/python3.6/site-packages/scanpy/preprocessing/_highly_variable_genes.py in highly_variable_genes(adata, min_disp, max_disp, min_mean, max_mean, n_top_genes, n_bins, flavor, subset, inplace)
    101     X = np.expm1(adata.X) if flavor == 'seurat' else adata.X
    102 
--> 103     mean, var = materialize_as_ndarray(_get_mean_var(X))
    104     # now actually compute the dispersion
    105     mean[mean == 0] = 1e-12  # set entries equal to zero to small value

~/miniconda3/envs/scRNA/lib/python3.6/site-packages/scanpy/preprocessing/_utils.py in _get_mean_var(X)
     16             mean_sq = np.multiply(X, X).mean(axis=0)
     17         # enforece R convention (unbiased estimator) for variance
---> 18         var = (mean_sq - mean**2) * (X.shape[0]/(X.shape[0]-1))
     19     else:
     20         from sklearn.preprocessing import StandardScaler

~/miniconda3/envs/scRNA/lib/python3.6/site-packages/numpy/matrixlib/defmatrix.py in __pow__(self, other)
    226 
    227     def __pow__(self, other):
--> 228         return matrix_power(self, other)
    229 
    230     def __ipow__(self, other):

~/miniconda3/envs/scRNA/lib/python3.6/site-packages/numpy/linalg/linalg.py in matrix_power(a, n)
    600     a = asanyarray(a)
    601     _assertRankAtLeast2(a)
--> 602     _assertNdSquareness(a)
    603 
    604     try:

~/miniconda3/envs/scRNA/lib/python3.6/site-packages/numpy/linalg/linalg.py in _assertNdSquareness(*arrays)
    213         m, n = a.shape[-2:]
    214         if m != n:
--> 215             raise LinAlgError('Last 2 dimensions of the array must be square')
    216 
    217 def _assertFinite(*arrays):

LinAlgError: Last 2 dimensions of the array must be square
```

Do you have any hints? I am trying to find the error but so far I have been unsuccessful.

**Comment by LuckyMD** [comment]
Hi,

This bug report may be better placed in the single-cell-tutorial repo as you're having issues with how the tools are chained.

A few things to check:
- Are you using sparse matrices in your data?
- are the size factors you get all real numbers (not `NaN`)?

I've seen this error before... just can't remember what the issue was. I think it was sparse matrices.

**Comment by SamueleSoraggi** [comment]
Hi,

I just made a test and it seems that it is indeed a problem of non-sparse matrix. How can I render the matrix sparse again from one that is dense? Is there something similar to the `adata.X.todense()` command?

**Comment by SamueleSoraggi** [comment]
Hi again,

after normalizing with an external tool I resparsified the matrix as it follows:
`adata.X = scipy.sparse.csr_matrix(adata.X)`

and everything works.
Thanks for help. Cheers.

**Comment by LuckyMD** [comment]
So for future reference. `scran` and other `R` tools don't work on sparse matrices. Whenever you need to do batch correction, that doesn't matter anyway, as you'll probably have to densify your matrix for batch correction anyway (or it will be dense after batch correction).

Edit: This is referring to the use of `scran` and other `R` tools in the `single-cell-tutorial` case study notebook (up to version 1904). The `R` tools themselves of course work with sparse matrices. Also, the newer version of the tutorial notebook allows for sparse matrix conversion as well.

**Comment by flying-sheep** [comment]
scran works on sparse stuff, maybe not all its tools yet

**Comment by LuckyMD** [comment]
The above comment was referring to the old `rpy2`/`anndata2ri` implementation of the `single-cell-tutorial` notebook. The newer version of the notebook (Version 1906) indeed does allow for sparse matrix conversion into `SingleCellExperiment` objects.
