### ISSUE TITLE
Exporting result after cell cycle score

### ISSUE THREAD

**Issue by RaffaellaP** [scverse/scanpy#645]
Hi,
I'm encountering an error when trying to write result file, after perform cell cycle score.
After normalizing, I import cell cycle file and perform the score:

`cc_genes=[gene.strip() for gene in open('[my_cell_cycle_genes]')]
s_genes=[g for g in cc_genes[:43] if g in adata.var_names]
g2m_genes=[g for g in cc_genes[43:] if g in adata.var_names]
sc.tl.score_genes_cell_cycle(adata, s_genes=s_genes, g2m_genes=g2m_genes)
`

The field 'phase' of the obs. matrix is of type object:
`adata.obs.phase.dtypes
dtype('O')`

When I write the annData object, I got the error:
`adata.write(results_file)
... storing 'phase' as categorical
TypeError: Categorical is not ordered for operation max
you can use .as_ordered() to change the Categorical to an ordered one`

and now the field 'phase' is categorical:
`adata.obs.phase.dtypes
CategoricalDtype(categories=['G1', 'G2M', 'S'], ordered=False)`

I can modify it as suggested, but it's converted into categorical when writing file again.
Following my version packages:
`sc.logging.print_versions()
scanpy==1.4.2 anndata==0.6.17 umap==0.3.7 numpy==1.16.3 scipy==1.2.1 pandas==0.24.2 scikit-learn==0.20.3 statsmodels==0.9.0 python-igraph==0.7.1 louvain==0.6.1`

My annData, also on a subset of variables, is too big to attach here, but I could send you by email if you need it.

Thanks a lot!
Raffaella

**Comment by LuckyMD** [comment]
Hi,

I think it would help if you updated anndata to 0.6.19. there was a change in 0.6.18 that wrote unordered categoricals, where before categoricals were changed to ordered by default.

Hope that helps.

**Comment by RaffaellaP** [comment]
Yes, it works!

Thanks again!
