### ISSUE TITLE
Documentation request, import formats

### ISSUE THREAD

**Issue by jorvis** [scverse/scanpy#65]
I've been able to successfully use scanpy for MEX-formatted datasets, and the documentation here was great in the Jupyter notebooks.

Many of our other datasets are in a simple tab format where the first column is gene symbol and the rest are in GROUP--CELLID format, like this:

```
Gene_symbol	lymph_1--cell_avg	lymph_1--Cell_1	lymph_1--Cell_10
A1BG.AS1	13.9085855833156	0	54.3778851449283
A2M.AS1	10.2185780428145	0	0
A2MP1	0	0	0
AADACL2	0	0	0
AAGAB	136.889472532613	0	0
AAR2	76.3090843598131	0	0
AATF	360.127068564485	0	0
AATK	2.93980819712579	0	0
AATK.AS1	0	0	0
```

These contain up to 30,000 rows and (so far) 400,000 columns.  

I'd love to see more use cases for how to absorb different formats of data into scanpy.  I'd be happy to help write it, but so far have only got MEX data to work.

**Comment by falexwolf** [comment]
Hi Jorvis! This should be very easy. Use the text file reader:
```
adata = sc.read_text(filename).transpose()
```
or use the general purpose reader that writes cache files automatically
```
adata = sc.read(filename, ext='txt').transpose()  # 'tab', 'data', 'tsv' mean the same
```
see the [API docs](https://scanpy.readthedocs.io/en/latest/api/index.html)

The 'tsv' file ending is not yet in the latest release, I just commited that: https://github.com/theislab/scanpy/commit/884c5f8a6a39c43aef27c7398ec9c195b977a3d3

Hope this helps.

**Comment by falexwolf** [comment]
Ah, ok see the problem... your example is no standard 'csv'/'table' format, as far as I see, as the first line contains the name of the index (the gene names).

In this case,

```py
adata = sc.read_text(filename, first_column_names=True).transpose()
```

or 

```py
adata = sc.read(filename, ext='txt', first_column_names=True).transpose()
```

should do the job.

**Comment by falexwolf** [comment]
But actually, if the first column consists in strings, passing `first_column_names` should not be necessary, and everything should work as explained in my response above. The second response should also work, but is a bit verbose.

See the code [here](https://github.com/theislab/anndata/blob/eba3080e51fab9d21c73b746a32cb74284ff2e46/anndata/readwrite/read.py#L243-L255)

**Comment by jorvis** [comment]
OK, I'll try looking through that.  And, to clarify, the first *column* contains the gene names - the first *row* contains the cell names.  Thanks for taking the time to respond.

**Comment by falexwolf** [comment]
Does this work for you?

**Comment by jorvis** [comment]
Yes, thanks
