### ISSUE TITLE
Scanpy not working correctly with scikit-learn 0.21.1

### ISSUE THREAD

**Issue by danielStrobl** [scverse/scanpy#654]
Hey!

Scanpy does not seem to work correctly together with scikit-learn 0.21.1.
When running the PBMC clustering tutorial (https://github.com/theislab/scanpy-tutorials/blob/master/pbmc3k.ipynb), the produced UMAP plots look very different to the reference.
![wrong_umap](https://user-images.githubusercontent.com/50872326/58096076-92577880-7bd4-11e9-9383-dda48c4efeac.png)

By downgrading scikit-learn to 0.20.0, everything works fine.
The problem seems to arise already at the computation of the neighborhood graph, as the clustering is also different.

**Comment by LuckyMD** [comment]
Just to add to this, PCA plots look fine with the newer `scikit-learn` I believe. Maybe it's the umap neighbourhood graph function depending on sklearn for something?

**Comment by gokceneraslan** [comment]
Oh that's reaaaally bad. I did a quick git bisect on sklearn:

![image](https://user-images.githubusercontent.com/1140359/58111323-40582800-7bbf-11e9-8905-e7f3a73cd057.png)

Here is the commit that broke our umaps: https://github.com/scikit-learn/scikit-learn/pull/13554

**Comment by LuckyMD** [comment]
Should this be relayed to scikit-learn then? If so, that should probably be done by someone who knows where in the `sc.pp.neighbors()` function this is breaking...

**Comment by LuckyMD** [comment]
@flying-sheep mentioned this was known and already fixed though?

**Comment by gokceneraslan** [comment]
OK, seems to be fixed in sklearn master branch (probably https://github.com/scikit-learn/scikit-learn/pull/13910), but this is such a huge bug and it has been going on since May 9th :( We could have blacklisted sklearn versions 0.21.0 and 0.21.1 if it was known, no? Some colleagues mentioned weird UMAP results with scanpy actually, it turns out they upgraded their sklearn...

**Comment by flying-sheep** [comment]
> @flying-sheep mentioned this was known and already fixed though?

I meant the other breakage due to the scipy update, sorry.

> We could have blacklisted sklearn versions 0.21.0 and 0.21.1 if it was known, no?

We should do that now. We can do `sklearn >= 0.19.1, != 0.21.0, != 0.21.1` I think.

**Comment by gokceneraslan** [comment]
Thanks!
