### ISSUE TITLE
sandbag docs inconsistent

### ISSUE THREAD

**Issue by fbnrst** [scverse/scanpy#657]
`sc.external.tl.sandbag` mentions `categories` as a paramter but `annotation` should be given according to the function signature. According to the [pypairs documentation](https://pypairs.readthedocs.io/en/latest/pypairs.pairs.sandbag.html#pypairs.pairs.sandbag) annotation should not be passed if data is an AnnData object. Instead, pypairs expects this information in `data.vars['category']`. So, I do not know how to fix this best. If you have an idea, I can add it to #656.

**Comment by flying-sheep** [comment]
The function actually accepted `annotation` all along, yes.

The docs say that it’s not *required* if there’s an AnnData object passed, but it can be specified: https://github.com/rfechtner/pypairs/blob/7e35292260f65c7598bc335b1a85de149d06f1e0/pypairs/utils.py#L214-L216

Fixed in #814
