### ISSUE TITLE
scanpy.pp.regress_out(adata) scipy issue

### ISSUE THREAD

**Issue by FelixGiraud** [scverse/scanpy#660]
Hello, 

I have an issue using this function. It was working perfectly until today. Now, when i try to run regress_out i have an issue with scipy:

--> from scipy.misc import factorial

cannot import name 'factorial'

Any idea to solve this problem ? 
Thank you. 

![image](https://user-images.githubusercontent.com/47348139/58240057-737af280-7d4a-11e9-9df5-aaa8b8da432c.png)

**Comment by falexwolf** [comment]
There is an issue with the new Scipy. `statsmodels` is conflicting with it. Either downgrade scipy or upgrade statsmodels as soon as they fixed it.

**Comment by FelixGiraud** [comment]
Ok thank you for your answer !
