### ISSUE TITLE
Error message in tl.diffmap / why n_comps must be > 2 

### ISSUE THREAD

**Issue by lsiraj** [scverse/scanpy#668]
Hi, 

 I'm using your package tl.diffmap in my analysis, and I'm having some difficulties. I have a dataframe I have converted into an anndata object adata. I run the following lines to prepare it for tl.diffmap:

`pp.pca(adata,n_comps=50)`
`pp.neighbors(adata, knn = False, method = 'gauss', n_neighbors = 20)`

I then perform the diffmap:

`tl.diffmap(adata, n_comps = 3)`

and I get the following error:

![Screen Shot 2019-05-15 at 6 11 47 PM](https://user-images.githubusercontent.com/43049941/58586913-25725d00-822a-11e9-930a-9165efdf60f9.png)

I am not sure what I am doing incorrectly here, and I was hoping you could help!

Furthermore, I was wondering why n_comps must be greater than 2?

**Comment by flying-sheep** [comment]
I think I see what’s going wrong. Scipy sparse matrices have the [**method** `<matrix class>.count_nonzero(self, ...)`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.count_nonzero.html) while numpy’s ndarrays don’t. One would use the [static function `numpy.count_nonzero(a, ...)`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.count_nonzero.html) for that.

I.e. the `neighbors` code assumes `self._connectivities` is a sparse matrix, while it isn’t in your case. Seems like `neighbors(..., method='gauss')` stores a dense matrix under some circumstances, while parts of the code assume a sparse one. Will fix!

**Comment by flying-sheep** [comment]
Fixed in d44d5f7351719643bd21042d560355b83188b9e5
