### ISSUE TITLE
Proper way to calculate differential gene expression after batch alignment?

### ISSUE THREAD

**Issue by tilofrei** [scverse/scanpy#669]
Hi, 

I was wondering what is a good/accepted way to calculate differential gene expression after batch alignment of multiple datasets?

After reading into it, it seems to me that the DEG are calculated on the raw (=non batch corrected values) and after all some batch correction algorithms don't even transform the data matrix (I don't understand why). See: [Mnn correct docs](https://icb-scanpy.readthedocs-hosted.com/en/stable/api/scanpy.external.pp.mnn_correct.html), [Seurat issue](https://github.com/satijalab/seurat/issues/1224#issuecomment-473416336), [Harmony preprint](https://www.biorxiv.org/content/biorxiv/early/2018/11/05/461954.full.pdf)

But that means I would need to include _batch_ as an interaction in the DEG calculation, therefore I could use _logistic regression_ in scanpy with:
`scanpy.tl.rank_genes_groups(adata, use_raw=True, method='logreg')`
I am struggling though to find out how to add interactions to sklearns logistic regression via scanpy. When using sklearn directly it should work through [patsy or PolynomialFeatures()](https://stackoverflow.com/questions/45828964/how-to-add-interaction-term-in-python-sklearn). [Others](https://github.com/theislab/scanpy/issues/95) seem to use sklearn without the wrapper.
Or maybe I don't need to add interactions if the biological difference between the samples is bigger than the batch effect?

Do you think this is the right way to do this and could you point me in the right direction to solve this?
I think this might actually be not an _issue_ of scanpy but more a matter of understanding how to properly do this and how to use the tool so no worries if you decide to close this.

Thanks!

**Comment by LuckyMD** [comment]
Hi,

You are correct that DE testing should be performed on raw or normalized data, but not on batch-corrected data. `sc.tl.rank_genes_groups()` doesn't let you include covariates, but there are plenty of methods that do. You could look into `diffxpy` for this, which is also based on AnnData and is easily integrated into a scanpy script. Otherwise, I have a case study for a best practices workflow, which uses MAST. You could reuse code from there as well. You can find the case study [here](https://www.github.com/theislab/single-cell-tutorial).

**Comment by tilofrei** [comment]
Thanks a lot @LuckyMD!
MAST seems to be what I was looking for. An alternative might be the logistic regression with covariates Seurat offers within their FindMarkers function.

**Comment by lijxug** [comment]
Hi. Thanks a lot for your advices @LuckyMD . However, the link to the case study seems failed. Could you please reattach it?

**Comment by LuckyMD** [comment]
I edited the link. It works now.
