### ISSUE TITLE
log_transformed parameter seems to not be used in rank_genes_groups

### ISSUE THREAD

**Issue by fbrundu** [scverse/scanpy#671]
Hi,
the parameter `log_transformed` looks as it's not used inside the method.
Is it a stub or is it used in other ways?

https://github.com/theislab/scanpy/blob/9b71dab77768fe0eb8b86aed473bee76b3aefd8e/scanpy/tools/_rank_genes_groups.py#L28

**Comment by falexwolf** [comment]
You are absolutely right; it's removed: https://github.com/theislab/scanpy/commit/c319ac0699937278e2a231988e72e432c8950c0a

The function expects logarithmized data.
