### ISSUE TITLE
PAGA using Seurat Clusters

### ISSUE THREAD

**Issue by MediciPrime** [scverse/scanpy#680]
Hello, 

I have managed to get my Seurat object converted into Loom and then read into Scanpy.  Now my main objective is to use the clusters identified using Seurat in order to create a PAGA trajectory map.  I was able to do a similar thing for Seurat -> Monocle by integrating the Seurat clusters and allow Monocle to perform a trajectory analysis on them.  

I have the following Scanpy object:
![scanpy_adata](https://user-images.githubusercontent.com/11708268/58907732-7a075380-86d4-11e9-9f2a-4c539ea58c80.png)

All the cluster information along with cell ids are present in the obs part of the Scanpy object.  Is there anyway to use that information in order to perform a PAGA trajectory analysis?

Thank you,
Behram

**Comment by MediciPrime** [comment]
UPDATE:  
So after running `sc.pp.neighbors(adata, n_neighbors=15, n_pcs=40)` I was able to run PAGA w/ Seurat clusters using:
 `sc.tl.paga(adata, groups='seurat_clusters')`.  

Would you guys say this is a legal move to make statistically speaking? 

 I am visualizing the trajectory inferences using `scanpy.pl.paga(adata)`.

**Comment by LuckyMD** [comment]
sounds to me like you know what you're doing. Where do you get your PCA from? Seurat? Otherwise I would consider running `sc.pp.pca(adata, svd_solver='arpack')` with the highly variable gene set and your pre-processed data from Seurat.

Also, for the future, an easier way to go between Seurat and Scanpy might be [anndata2ri](https://www.github.com/flying-sheep/anndata2ri). I have an example notebook for that [here](https://www.github.com/LuckyMD/Code_snippets).

**Comment by MediciPrime** [comment]
Wow well that certainly makes things a lot easier, thank you for creating that code snippet!  It seems as though Scanpy was smart enough to realize I hadn't performed PCA and thus did it for me using the default settings.  However as you have suggested I should be using 'arpack' to make my results reproducible, will do!  

Thank you for your reply!

**Comment by qimiaonnegliguo** [comment]
> UPDATE: So after running `sc.pp.neighbors(adata, n_neighbors=15, n_pcs=40)` I was able to run PAGA w/ Seurat clusters using: `sc.tl.paga(adata, groups='seurat_clusters')`.
> 
> Would you guys say this is a legal move to make statistically speaking?
> 
> I am visualizing the trajectory inferences using `scanpy.pl.paga(adata)`.

Hi thank you very much for your information. I'm running the same purpose, using the Seurat object with clustering information for Scanpy trajectory analysis. May I ask why your adata object has so much information inside. Mine is: 
![image](https://github.com/scverse/scanpy/assets/82354685/ef2554df-a067-45f5-8e4f-8527540a7994)

What I do is reading the h5ad file and running sc.tl.paga(adata, groups='seurat_clusters'). May I ask if it is correct or not. Thanks again for your kind help.
