### ISSUE TITLE
How to plot with paga_path, sorted by pseudo_time

### ISSUE THREAD

**Issue by fbrundu** [scverse/scanpy#682]
I would like to use the plotting API of `paga_path()` like in [this tutorial (last figure)](https://nbviewer.jupyter.org/github/theislab/paga/blob/master/blood/simulated/simulated.ipynb).
However, I noticed that cells are being sorted intra-clusters. I would like to sort only by "distance" (pseudotime), but keeping the "clusters" annotation.
Is it possible?

**Comment by falexwolf** [comment]
There is no convenience function for that, I fear. You can look at the code by clicking on the _Edit on GitHub_ button of its [doc page](https://scanpy.readthedocs.io/en/latest/api/scanpy.pl.paga_path.html#scanpy.pl.paga_path).

**Comment by eroell** [comment]
Just came across this, thanks again for bringing up this issue!

We will close the issue soon, as based on the provided information and the discussion so far, it seems that the question has been addressed and hopefully resolved :)

However, please don't hesitate to reopen this issue or create a new one if you have any more questions or run into any related problems in the future.

Thanks for being a part of our community! :)
