### ISSUE TITLE
scipy.misc factorial is depreciated

### ISSUE THREAD

**Issue by Gibbsdavidl** [scverse/scanpy#687]
Hi there.  Love the package.

I was working in a google colab notebook, and installed scanpy as 'pip install scanpy'.

Then when using the method: sc.pp.regress_out(adata, ['n_counts', 'percent_mito'])

I got this error:
----------------------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-54-c0d016811ded> in <module>()
----> 1 sc.pp.regress_out(adata, ['n_counts', 'percent_mito'])

5 frames
/usr/local/lib/python3.6/dist-packages/statsmodels/distributions/edgeworth.py in <module>()
      5 import numpy as np
      6 from numpy.polynomial.hermite_e import HermiteE
----> 7 from scipy.misc import factorial
      8 from scipy.stats import rv_continuous
      9 import scipy.special as special

ImportError: cannot import name 'factorial'
----------------------------------------------------------------------------------------

Seems that scipy.misc.factorial is depreciated and is now under scipy.special.factorial

Thanks!

**Comment by slieped** [comment]
I have replicated the error using local installation with 'pip3 install scanpy'
When I run the  regress_out code on a jupyter notebook, same error appears.

**Comment by flying-sheep** [comment]
That’s statsmodels/statsmodels#5759. We already require compatible versions from everything.

try installing scanpy from git and it should work
