### ISSUE TITLE
Untyped global name 'nearest_neighbors'

### ISSUE THREAD

**Issue by rcannood** [scverse/scanpy#688]
With the most recent version of scanpy, I'm getting the above mentioned warning, which causes the [`dynverse/ti_paga`](https://travis-ci.org/dynverse/ti_paga/builds/544731805) builds to fail. 

The problem can be replicated by building the `dynverse/ti_paga` container manually and trying to run it. For the sake of simplicity, I have built the container for you and pushed it to `dynverse/ti_paga_issue`.

### Minimum reproducible example
Inside terminal:
```bash
# fetch newest dynverse/ti_paga container in which this problem occurs
docker pull dynverse/ti_paga_issue

# enter the container 
docker run --entrypoint bash -it dynverse/ti_paga_issue

# create an example dataset and save it at /input.h5
/code/example.sh /input.h5

# enter python
python
```
Inside python
```python
import dynclipy
task = dynclipy.main(["--dataset", "/input.h5", "--output", "/output.h5"])

import scanpy.api as sc
import anndata

counts = task["counts"]

adata = anndata.AnnData(counts)
sc.pp.recipe_zheng17(adata, n_top_genes=101)
sc.tl.pca(adata, n_comps=50)
sc.pp.neighbors(adata, n_neighbors=15)
```
Which generates the following warning:
```
/usr/local/lib/python3.7/site-packages/umap/umap_.py:349: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "fuzzy_simplicial_set" failed type inference due to: Untyped global name 'nearest_neighbors': cannot determine Numba type of <class 'function'>

File "usr/local/lib/python3.7/site-packages/umap/umap_.py", line 467:
def fuzzy_simplicial_set(
    <source elided>
    if knn_indices is None or knn_dists is None:
        knn_indices, knn_dists, _ = nearest_neighbors(
        ^

  @numba.jit()
/usr/local/lib/python3.7/site-packages/numba/compiler.py:725: NumbaWarning: Function "fuzzy_simplicial_set" was compiled in object mode without forceobj=True.

File "usr/local/lib/python3.7/site-packages/umap/umap_.py", line 350:
@numba.jit()
def fuzzy_simplicial_set(
^

  self.func_ir.loc))
/usr/local/lib/python3.7/site-packages/numba/compiler.py:734: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "usr/local/lib/python3.7/site-packages/umap/umap_.py", line 350:
@numba.jit()
def fuzzy_simplicial_set(
^

  warnings.warn(errors.NumbaDeprecationWarning(msg, self.func_ir.loc))
```

**Comment by rcannood** [comment]
@falexwolf @flying-sheep @fidelram @ivirshup Kind reminder. Due to this problem the PAGA builds as part of dyno are failing. Are you able to reproduce my problem? Do you need any more information?

**Comment by flying-sheep** [comment]
All of this happens in umap and has nothing to do with scanpy, right?

**Comment by rcannood** [comment]
Makes sense, thanks for clarifying. This issue is then related to lmcinnes/umap#252.

@flying-sheep @lmcinnes Is there any way I can turn these specific warnings off?

**Comment by flying-sheep** [comment]
https://docs.python.org/3/library/warnings.html#temporarily-suppressing-warnings

```py
import numba
import warnings

with warnings.catch_warnings():
    warnings.simplefilter('ignore', numba.errors.NumbaDeprecationWarning):
    do_thing()
```

**Comment by rcannood** [comment]
Thanks @flying-sheep! I will suppress the warning this way.

**Comment by andynkili** [comment]
@rcannood,

I have the same issue while using PAGA_tree  from the dyno wrapper.
Do you know where I can add the chunk of code that @flying-sheep suggested to remove the warnings?
My first guess would be to change the python files in the container built from PAGA_tree, however the latter (from dyno) builds a new container every time it is called.

How should I procedd?

Best,
Andy
