### ISSUE TITLE
UMAP: no available 'use_rep' parameter for tool.umap() 

### ISSUE THREAD

**Issue by genecell** [scverse/scanpy#689]
Hi,

I found there is 'use_rep' for tool.tsne(), but not for tool.umap().
Is there any solution to perform umap on a selected anndata's obsm?

Thanks in advance,
BP

**Comment by Koncopd** [comment]
Hi, to run umap, you need to run pp.neighbors at first, and neighbors have use_rep. tool.umap use representation that pp.neighbors used.

**Comment by genecell** [comment]
Hi,
Problem solved! Thanks a lot.
I am new to scanpy and now find it flexible and well designed. Thanks!
