### ISSUE TITLE
Warning sc.pl.scatter

### ISSUE THREAD

**Issue by ghost** [scverse/scanpy#690]
Hi I got this warning when I used sc.pl.scatter:
```
.../scanpy/plotting/_anndata.py:311: DeprecationWarning: Use obs_vector instead of _get_obs_array, _get_obs_array will be removed in the future.
  x_arr = adata._get_obs_array(x, use_raw=use_raw, layer=layers[0])
.../anndata/base.py:1618: FutureWarning: In a future version of AnnData, access to `.X` by passing `layer='X'` will be removed. Instead pass `layer=None`.
  FutureWarning
```

I would like to know if the plots generated with this warning are correct.
Thanks.

**Comment by LuckyMD** [comment]
These are deprecation warnings, so there's no issue with the code for now. The plots should be generated as you expect.

**Comment by flying-sheep** [comment]
We should fix the code throwing those, though.

**Comment by ivirshup** [comment]
@rbioinfo this should now be fixed on master
