### ISSUE TITLE
Single color on sc.pl.scatter plotts

### ISSUE THREAD

**Issue by Xparx** [scverse/scanpy#692]
It seems like the default color for scatterplots are gray. I think I read somewhere that it's the middle color for the gray color sale from matplotlib.

Is there a way to plot a scatterplot with a single color given as an argument to `sc.pl.scatter`?

**Comment by flying-sheep** [comment]
Actually the gray is hardcoded:

https://github.com/theislab/scanpy/blob/b3dc34a57ccaa6ac9a4ac8718fe9f128c967e3dc/scanpy/plotting/_anndata.py#L303

But you can simply use a color-like string to specify your favourite color (Unless you happend to have an `.obs` column named `#fe57a1` or so :grin:):

https://github.com/theislab/scanpy/blob/b3dc34a57ccaa6ac9a4ac8718fe9f128c967e3dc/scanpy/plotting/_anndata.py#L384-L386

**Comment by flying-sheep** [comment]
Documented in 5ab9def681264a95acd48aeda45b46ad0b86fee8

**Comment by Xparx** [comment]
Thanks for the answer and for your suggestion @flying-sheep.

I can't make this work though. The color choice does not work while also using scatter plot to plot `x` and `y` values.
The suggested code only works when `basis is not None`. However using the plain basis function e.g. `sc.pl.umap` will fail earlier than this for inputting a color.

### In summary,

this will not work:
```
sc.pl.umap(adata, color=#fe57a1)
```
this will work
```
sc.pl.scatter(adata, basis='umap', color=#fe57a1)
```
this will not work (what I actually want to do)
```
sc.pl.scatter(adata, x='dpt_pseudotime', y='SOMEGENE', color=#fe57a1)
```
For the last command the code makes a check already before passing the color argument to the plotting function
https://github.com/theislab/scanpy/blob/5ab9def681264a95acd48aeda45b46ad0b86fee8/scanpy/plotting/_anndata.py#L121


EDITED so it links to the correct code line.

**Comment by Xparx** [comment]
Simply adding the matplotlib `is_color_like` seems to do the trick
```
and (color is None or color in adata.obs.keys() or color in adata.var.index or is_color_like(color))):
```

**Comment by mbernste** [comment]
@Xparx I had this issue as well. Your modification worked for me, thanks!

**Comment by flying-sheep** [comment]
Right, thank you. I made #1060 to fix it

**Comment by Xparx** [comment]
Great that it works!
I should have made a PR but i have no idea how. Glad it could be fixed.
