### ISSUE TITLE
Development roadmap

### ISSUE THREAD

**Issue by dawe** [scverse/scanpy#697]
Hi all, this is not really an issue, but is there a development roadmap for scanpy? What features are going to be added? What data will be supported? Is github the right place to discuss this?

**Comment by flying-sheep** [comment]
I think it is! We could start using GitHub’s projects feature: https://github.com/theislab/scanpy/projects

The closest thing we have rn is #453

**Comment by flying-sheep** [comment]
Also there’s #45
