### ISSUE TITLE
Development branch

### ISSUE THREAD

**Issue by pwl** [scverse/scanpy#7]
Hi, I was just trying to use the package but it seems that somebody is working on the master branch right now.  Would it be possible to set up a development branch and maybe add a few tags for the working versions so that people could download a particular release instead of an in-progress master branch?  I also noticed that the notebooks disappeared right after I cloned the repository.  It seems like there are some big changes going on, so sorry if the timing for this issue is not right and you are just cleaning up the repository.

**Comment by falexwolf** [comment]
Hi Pawel, sorry for the confusion, yes, we just did a major revision. The package is still in the testing phase even though everything should work fine. Any comments from your side would be greatly appreciated!

Packaging will start soon. Development will happen on a development branch from now on.

The notebooks are currently being migrated to another repo, links will be updated tomorrow or day after tomorrow.

**Comment by pwl** [comment]
Nice!  Could you please write here once you're done with the major changes?  I'm looking forward to using this package.

**Comment by flying-sheep** [comment]
sure, we’ll do that.

**Comment by falexwolf** [comment]
Hi Pawel, we now reached a state in which the package structure will not be fundamentally reorganized anymore. We will actively develop the package further on development branches. Versioning will hopefully start soon, too.

If you have any questions, I'm happy to answer them!

**Comment by pwl** [comment]
Thanks!  Hopefully I'll find some time to test it out this week, I'll get back to you once I do that.

**Comment by pwl** [comment]
So I just tried to install the package from the master branch by running

```
pip install git+https://github.com/theislab/scanpy.git
```
(by the way, you can update the Installation section of the README.md because the above line is equivalent to cloning the repository and running pip install on that.)  The installation failed with
```
Collecting git+https://github.com/theislab/scanpy.git
  Cloning https://github.com/theislab/scanpy.git to /tmp/pip-203inirx-build
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/scanpy.egg-info
    writing pip-egg-info/scanpy.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/scanpy.egg-info/dependency_links.txt
    writing entry points to pip-egg-info/scanpy.egg-info/entry_points.txt
    writing requirements to pip-egg-info/scanpy.egg-info/requires.txt
    writing top-level names to pip-egg-info/scanpy.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/scanpy.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    error: package directory 'scanpy/exs' does not exist
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-203inirx-build/
The command '/bin/sh -c pip install --upgrade --no-cache-dir     git+https://github.com/theislab/scanpy.git' returned a non-zero code: 1
```

**Comment by falexwolf** [comment]
Sorry for that, fixed this bug.

I think there is no way to make 
```
pip install git+https://github.com/theislab/scanpy.git
```
work if you want to install using symbolic links (to your local clone of the git repo). Until versioning starts, it's good to be able to type `git pull` in the local clone and by that automatically update the `scanpy` installation without having to do anything else.

But you're right, this is should just be a temporary solution.

**Comment by pwl** [comment]
Thanks, the example works perfectly well now.

**Comment by falexwolf** [comment]
Good! Looking forward to reading about your experience.
