### ISSUE TITLE
Documentation request: Iterating a DataFrame

### ISSUE THREAD

**Issue by jorvis** [scverse/scanpy#70]
I'd be happy to add this once I could figure it out.  I've been able to load my tabular text files, store them as h5ad, then load them back again.  I cannot see how to iterate over rows, then columns so that I can access all values of the dataframe with an awareness of which row/column each belongs to.

My wishful code example:

```py
adata = sc.read_h5ad(filename)
selected = adata[:, adata.var_names.isin({'AAR2', 'ECT2'})]

## this line spews information on the columns like:
#  Empty DataFrameView
#  Columns: []
# Index: [Cancer--Cell_1, Cancer--Cell_10, Cancer--Cell_100, Cancer--Cell_1000, Cancer--Cell_1001
#print(selected.obs)

## this line gives the row information:
# Empty DataFrameView
# Columns: []
#Index: [AAR2, ECT2]
#print(selected.var)
    
# Nothing happens here at all
#for i, row in selected.obs.iteritems():
#    print(i, row)

for gene_name, row in selected.var.iterrows():
    # this prints like: Series([], Name: AAR2, dtype: float64)
    print(row)

    # Nothing happens here
    for cell_name, val in row.iteritems():
        print("{0}\t{1}\t{2}".format(gene_name, cell_name, val))
```

**Comment by jorvis** [comment]
Attaching an example file.  I know zip is useless for h5 but it was required in order to attach here.
[fig1.h5.zip](https://github.com/theislab/scanpy/files/1643111/fig1.h5.zip)

**Comment by jorvis** [comment]
I also [put this on StackOverflow](https://stackoverflow.com/questions/48326579/unable-to-iterate-over-pandas-dataframe-loaded-from-tabular-data)

**Comment by jorvis** [comment]
For anyone else who comes across this, here is an example of how it's done:

```py
adata = sc.read_h5ad(filename)

# this is for the cancer dataset
selected = adata[:, adata.var_names.isin({'AAR2', 'ECT2'})]

# this version only works if I'm using a sparse matrix
cx = adata.X.tocoo()    
for cell, gene, value in zip(adata.obs_names[cx.row], adata.var_names[cx.col], cx.data):
    print(cell, gene, value)

# This works for full matrix
for g, gene in enumerate(selected.var_names):
    for c, cell in enumerate(selected.obs_names):
        print(cell, gene, selected.X[c, g])
```

**Comment by falexwolf** [comment]
Thank you for answering this yourself. As you know, I've become a bit busy lately. ;)

**Comment by jorvis** [comment]
No kidding - congrats on the twins!

**Comment by falexwolf** [comment]
Thank you! :smile:

**Comment by flying-sheep** [comment]
now you missed the sweet stackoverflow reputation, alex 😈
