### ISSUE TITLE
Merge dataset workflow? 

### ISSUE THREAD

**Issue by Seandelao** [scverse/scanpy#702]
Hi All, 

Not really an issue, but I'm very new to SCANPY (Seurat user before this) and was wondering what the general workflow/commands would be for merging and batch correcting multiple datasets together? For example, something like this (but for SCANPY, of course, and including info on merging and batch correcting):

https://satijalab.org/seurat/essential_commands.html

Thank you!

**Comment by LuckyMD** [comment]
Hi @Seandelao,

You can find tutorials and the description of the commands for scanpy in the documentation [here](https://scanpy.readthedocs.io/). If you're interested in our best-practices workflow, which is based on scanpy (but not only), you can find that [here](https://www.github.com/theislab/single-cell-tutorial).

**Comment by Seandelao** [comment]
Great, thank you!

**Comment by grimwoo** [comment]
> Great, thank you!

hi, did you find the "merge" or "integrate" commond in scanpy?

**Comment by LuckyMD** [comment]
Hi @grimwoo,

The data integration methods MNN and BBKNN are implemented in scanpy externals, which you can find [here](https://scanpy.readthedocs.io/en/stable/external/index.html#batch-effect-correction). You can also use combat correction, which is a simpler, linear batch effect correction approach implemented as `sc.pp.combat()`.

**Comment by grimwoo** [comment]
> Hi @grimwoo,
> 
> The data integration methods MNN and BBKNN are implemented in scanpy externals, which you can find [here](https://scanpy.readthedocs.io/en/stable/external/index.html#batch-effect-correction). You can also use combat correction, which is a simpler, linear batch effect correction approach implemented as `sc.pp.combat()`.

Thanks you so much~

**Comment by grimwoo** [comment]
> Hi @grimwoo,
> 
> The data integration methods MNN and BBKNN are implemented in scanpy externals, which you can find [here](https://scanpy.readthedocs.io/en/stable/external/index.html#batch-effect-correction). You can also use combat correction, which is a simpler, linear batch effect correction approach implemented as `sc.pp.combat()`.

sorry to bother you again. 
I want to merge adata001, adata002, and adata003 into adata.combined, with mark "001", "002", and "003" respectively. I looked into the help-information of "help(combat)", but still don't know how to do so.

In Seurat (R), it can be done like: 
adata001$Sample <- "001"
adata002$Sample <- "002"
adata002$Sample <- "003"
adata.anchors <- FindIntegrationAnchors(object.list = list(adata001, adata002, adata003), dims = 1:11)
adata.combined <- IntegrateData(anchorset = adata.anchors, dims = 1:11)

**Comment by LuckyMD** [comment]
Just concatenate the datasets first and then use Combat. Something like:
```
adata_merge = adata001.concatenate(adata002, adata003, batch_key='sample')
sc.pp.combat(adata_merge, batch='sample')
```

Double check with the documentation... i'm not sure those are the exact parameters. Also note that Combat is a simple batch correction method that performs a linear correction of the batch effect. It assumes that you have the same cell identities in all datasets. MNN and BBKNN are more appropriate for scenarios with less similar batches. Scanorama is also implemented on top of the AnnData framework and is easily usable with scanpy.

**Comment by grimwoo** [comment]
> Just concatenate the datasets first and then use Combat. Something like:
> 
> ```
> adata_merge = adata001.concatenate(adata002, adata003, batch_key='sample')
> sc.pp.combat(adata_merge, batch='sample')
> ```
> 
> Double check with the documentation... i'm not sure those are the exact parameters. Also note that Combat is a simple batch correction method that performs a linear correction of the batch effect. It assumes that you have the same cell identities in all datasets. MNN and BBKNN are more appropriate for scenarios with less similar batches. Scanorama is also implemented on top of the AnnData framework and is easily usable with scanpy.

Thanks for your early reply and kind suggestion~

**Comment by dhairya02** [comment]
HI, I tried to do what you suggested but I am getting an error saying `ValueError: only one regex group is supported with Index`.
I have multiple h5ad files with varying n_obs × n_vars. Here is my code:
```adatas = [an.read_h5ad(filename) for filename in filenames]
batch_names = []
for i in range(len(adatas)):
  adatas[i].var_names_make_unique()
  batch_names.append(filenames[i].split('.')[0])
  print(i,adatas[i])

adata = adatas[0].concatenate(adatas[1:],
                              batch_key = 'ID',
                              uns_merge="unique",
                              index_unique=None,
                              batch_categories=batch_names)
``` 

and this produces the above error. Can anyone help?
