### ISSUE TITLE
Still OOBError in rank_genes_groups

### ISSUE THREAD

**Issue by flying-sheep** [scverse/scanpy#71]
After remembering the originally specified number of genes:

https://github.com/theislab/scanpy/blob/ce15a2c5d5ef45c8eb0c041b1513f768a02a5299/scanpy/tools/rank_genes_groups.py#L73-L74

We set `n_genes` to `X.shape[1]`, …twice:

https://github.com/theislab/scanpy/blob/ce15a2c5d5ef45c8eb0c041b1513f768a02a5299/scanpy/tools/rank_genes_groups.py#L99-L100

https://github.com/theislab/scanpy/blob/ce15a2c5d5ef45c8eb0c041b1513f768a02a5299/scanpy/tools/rank_genes_groups.py#L105

Afterwards, we still use, `n_genes_user`, even though `np.argpartition` can only handle at most `X.shape[1]` genes.

https://github.com/theislab/scanpy/blob/ce15a2c5d5ef45c8eb0c041b1513f768a02a5299/scanpy/tools/rank_genes_groups.py#L145

It’s not clear to me what `n_genes` is supposed to hold, and what the parameter to `np.argpartition` should be, but the current code crashes if `X.shape[1] < 100` (or the user-specified `n_genes`)

**Comment by falexwolf** [comment]
@tcallies do you know what's happening? I'm not sure whether this is due to your changes or me having introduced the `.raw` attribute in a rush... I will only be able to look into this a bit later...

**Comment by falexwolf** [comment]
`n_genes_user` is supposed to limit the length of the returned tables

however, one still needs to search all genes `n_genes` (`== X.shape[1]`) in order to get the top-scoring ones

this is the rationale behind the two variables and the naming

**Comment by falexwolf** [comment]
maybe it's just that a check that `n_genes_user` < `n_genes = X.shape[1]` misses?

```
if n_genes_user > X.shape[1]:
    n_genes_user = X.shape[1]
```

it seems to me that this should be the solution...

**Comment by flying-sheep** [comment]
Yes, seems like it!

**Comment by falexwolf** [comment]
https://github.com/theislab/scanpy/commit/3696de14ec8ecaf34acc98492b81f7f6279d3a39 should fix it

I think you Phil, introduced the OoB check at some point that was then duplicate and had no effect - now it's for `n_genes_user` as it should be...

**Comment by flying-sheep** [comment]
nah, that was @tcallies 😉

https://github.com/theislab/scanpy/commit/fb7a588ad92603d0440c249ba7586bca613877dd#diff-984967ad3b25f43cc1f050d993b62415
