### ISSUE TITLE
an issue with negative values in loom files

### ISSUE THREAD

**Issue by lila167** [scverse/scanpy#712]
Hi,

I realized that the negative values are not read properly (mostly changed to 0) using scanpy "read_loom". 
However, using loompy directly, the negative values are read properly.

**Comment by VolkerBergen** [comment]
This has been an issue with loompy, resolved [here](https://github.com/linnarsson-lab/loompy/commit/2e620d2db8f203462dbd0ee8df08ed9fc6b8b0d7). However, one would need to check why it still fails with anndata's `read_loom` while running well with loompy directly.

For me, it works after the latest loompy commit. Could you provide a minimal example?

**Comment by VolkerBergen** [comment]
Just checked on this example
```
adata = sc.AnnData(np.array([[1, 2],[-1, 2]]))
adata.write_loom('test.loom')
adata = sc.read('test.loom', sparse=True)
```
and it looks fine, with retaining the negative value, for both sparse and non-sparse read-in.

**Comment by lila167** [comment]
Thanks, I haven't try the latest loompy yet. With the older version, I could still read the negative values using loompy directly.

**Comment by ivirshup** [comment]
@lila167, have you had a chance to try this again?
