### ISSUE TITLE
Contour plot

### ISSUE THREAD

**Issue by arnavm** [scverse/scanpy#720]
Hi,

Is there a way to plot UMAP/tSNE/PCA/etc. projections as contour plots instead of dot plots? Looking at the code, there does not seem to be an easy way to support this. Ideally it could be a parameter passed to the respective plotting function, e.g. sc.pl.umap(*args, contour = True)

**Comment by fidelram** [comment]
What is that you want to plot? do you have some example in mind that we can take a look?

Have you tried [embedding_density](https://icb-scanpy.readthedocs-hosted.com/en/stable/api/scanpy.pl.embedding_density.html)

**Comment by arnavm** [comment]
I haven't tried embedding_density yet; let me give that a try.

The example I have in mind is reminiscent of contour plots from flow cytometry data, as an alternative to the standard dot plots.
