### ISSUE TITLE
Don’t call _normalize_index with non-categorical/string names

### ISSUE THREAD

**Issue by jefferyUstc** [scverse/scanpy#727]
```
df = pd.read_csv('data/dropout/dropout1/counts.csv', index_col=0)
genes = df.index.values
barcodes = df.columns
adata = sc.AnnData(np.transpose(df.values), var=pd.DataFrame(genes), obs=pd.DataFrame(barcodes))
adata.var_names_make_unique()
sc.pp.filter_genes(adata, min_cells=5)
adata.raw = adata
sc.pp.normalize_per_cell(adata, counts_per_cell_after=1e4)  # Err occur==>Don’t call _normalize_index with non-categorical/string names
```

**Comment by ivirshup** [comment]
Thanks for the bug report. Could you make an example we can reproduce? There's some guides to this in the [contributing doc](https://github.com/theislab/scanpy/blob/master/CONTRIBUTING.md). It's hard to tell what's going on when we don't know what's in your file. Also version info would be helpful.

**Comment by jefferyUstc** [comment]
Thank you~ Firstly, it's an AssertionError in sc.pp.normalize_per_cell step ; secondly , toy example csv data is presented as below:

```
Group,Group1,Group1,Group3,Group6,Group5
Gene1,11,0,0,14,0
Gene2,12,17,9,34,11
Gene3,0,0,0,0,2
```

so, u can test this error locally by:

```python
df = pd.read_csv('data/dropout/dropout1/counts.csv', index_col=0)
genes = df.index.values
barcodes = df.columns
adata = sc.AnnData(np.transpose(df.values), var=pd.DataFrame(genes), obs=pd.DataFrame(barcodes))
adata.var_names_make_unique()
sc.pp.filter_genes(adata, min_cells=1)
adata.raw = adata
sc.pp.normalize_per_cell(adata, counts_per_cell_after=1e4)
```
lastly, the version is 1.4.3.

**Comment by ivirshup** [comment]
@jefferyUstc I can't reproduce this with `scanpy 1.4.3` and `anndata v0.6.21 `. Here's what I ran on my machine:

```python
from io import StringIO
import pandas as pd
import numpy as np
import scanpy as sc

csv = """
Group,Group1,Group1,Group3,Group6,Group5 
Gene1,11,0,0,14,0 
Gene2,12,17,9,34,11 
Gene3,0,0,0,0,2
"""

df = pd.read_csv(StringIO(csv), index_col=0)
genes = df.index.values
barcodes = df.columns
adata = sc.AnnData(np.transpose(df.values), var=pd.DataFrame(genes), obs=pd.DataFrame(barcodes))
adata.var_names_make_unique()
sc.pp.filter_genes(adata, min_cells=1)
adata.raw = adata
sc.pp.normalize_per_cell(adata, counts_per_cell_after=1e4)
```

Could you try that? If the error still occurs, could you post the traceback?

**Comment by jefferyUstc** [comment]
problem solved, just update `anndata` from `v0.6.19` to `v0.6.21`, Thank you!

**Comment by ivirshup** [comment]
No problem!

**Comment by wdg118** [comment]
Hi,

I get the same error that OP posted. I have the latest versions of both scanpy and anndata. When I run it locally on my Jupyter notebook there is no error and it works but when I run it on Jupyter lab I get that error. How should I go about fixing this ?

Thanks!
