### ISSUE TITLE
Plotting difference in png file vs. Jupyter output

### ISSUE THREAD

**Issue by jorvis** [scverse/scanpy#73]
I assume I'm missing something here, but when I try a simple example of plotting a gene dispersion I get two plots 'normalized' and 'not normalized' version in Jupyter, but when I use the save argument to sc.pl.filter_genes_dispersion() I get an image with only one of these.  Screenshot attached.   Just in case, I tried also passing the multi_panel argument but that caused an error. 

Also, is it no possible to specify the path where the files should be stored when using the save arguments to the plotting methods?  I want to point to a directory where it should place them, but it seems "./figures/" is hard-coded and you can only modify the end of that.

Thanks

The attached screenshot shows the dual image within Jupyter, but only the single plot which appears in the PNG file exported.

![screenshot from 2018-01-30 12-34-56](https://user-images.githubusercontent.com/330899/35584410-945d7bb6-05ba-11e8-89fc-14f615a9c6a6.png)

**Comment by falexwolf** [comment]
The figures directory can be set using - I will add this to the documentation...
```
sc.settings.figdir = 'whateverpathyoulike'
```
The default is './figures/'.

You only get to save the non-normalized version as this is what Cell Ranger and Seurat allow you to visualize. Do you need the other version? I can easily add this...

**Comment by jorvis** [comment]
Great info about the figdir, thank you.

I think it would be good to be able to access/save both plots, yes.  I want this sort of pipeline script to be able to generate the same output for inspection as if the user were running the commands within Jupyter, and both display there.  I don't think it's a critical thing though.

**Comment by falexwolf** [comment]
How images are saved has also improved in Scanpy 1.0 and produces less white space etc.. In addition, you can set `sc.settings.autosave = True` and this will automatically save all images instead of showing them, see [here](https://github.com/theislab/scanpy_usage/blob/3ba68ab52ee4e5db39da13f449b575402f404df4/170522_visualizing_one_million_cells/cluster.py#L7).
