### ISSUE TITLE
Showing obs_names instead of names of `groupby` in heatmap

### ISSUE THREAD

**Issue by wenweiliang** [scverse/scanpy#732]
Hi,
I am wondering can obs_names pass along within heatmap function and be shown in heatmap? Thanks!

![Screen Shot 2019-07-08 at 2 55 56 PM](https://user-images.githubusercontent.com/15947971/60838635-c42a9b80-a190-11e9-8ca5-0ff979e91ddf.png)

**Comment by fidelram** [comment]
From your example it seems that you want to rename clusters 1,2 and 3, and maybe only plot those samples. If that is the case you can do:

```PYTHON
sel = adata[adata.obs.louvain.isin(['1', '2', '3']).copy()
sel.obs.louvain.rename(columns={'1': 'SampleA', '2': 'SampleB', '3': 'SampleC'})
sc.pl.heatmap(sel, .......)
```

btw, your image may improve if you add `standard_scale='var'` to `sc.pl.dotplot`

**Comment by wenweiliang** [comment]
Hi @fidelram,
Thanks for your prompt reply! Sorry I didn't make my question clear. 
I would like to show the sample name of each row instead of cluster name. For example:

![Screen Shot 2019-07-10 at 11 53 30 AM](https://user-images.githubusercontent.com/15947971/60989163-ce70a500-a30a-11e9-9559-9a56d9efb88b.png)

PS. I have add `standard_scale='var'` in my heatmap. Thanks!

**Comment by fidelram** [comment]
for that you just need to rename the clusters using pandas rename:
```PYTHON
adata.obs.louvain.rename(columns={'1': 'SampleA', '2': 'SampleB', '3': 'SampleC' ......})
```
