### ISSUE TITLE
sc.pl.heatmap doesn't recognize a dictionary of genes and show `IndexError`

### ISSUE THREAD

**Issue by wenweiliang** [scverse/scanpy#735]
Hi, 
In the [tutorial](https://scanpy-tutorials.readthedocs.io/en/latest/visualizing-marker-genes.html#Heatmaps) `sc.pl.heatmap` take genes_dict as input, but I have `IndexError` when I use genes_dict. It was working for me before so I am wondering if there is a bug. Thanks.

![image](https://user-images.githubusercontent.com/15947971/60994831-e2220880-a316-11e9-9bd0-706bae059d1c.png)

BTW a flatten list works for sc.pl.heatmap in my dataset
![image](https://user-images.githubusercontent.com/15947971/60994955-27ded100-a317-11e9-943a-6ffdb20db75d.png)

**Comment by fidelram** [comment]
The use of a dict for genes was recently introduced. If is not working for your this is most likely because of an older version of scanpy

**Comment by WellJoea** [comment]
scanpy 1.4.6 also have this problem !!!

**Comment by WellJoea** [comment]
scanpy 1.4.6 also have this problem when using sc.pl.rank_genes_groups_heatmap plot with the parameter "use_raw=False"  !!!
