### ISSUE TITLE
TSNE Drawing Problem

### ISSUE THREAD

**Issue by jefferyUstc** [scverse/scanpy#736]
when i use `sc.pl.tsne` to draw a TSNE plot, saved in PDF format. It does works, but when open the PDF with adobe illustrator, something unusual happened as follow:
![image](https://user-images.githubusercontent.com/44384930/61019375-8ca83300-a3cc-11e9-8a29-bc64916bd7ef.png)

the title in the image is single charater with a single text box. and other text also has this problem，for one more axample:
![image](https://user-images.githubusercontent.com/44384930/61019597-5323f780-a3cd-11e9-8d03-2e2044330e30.png)

The right one should be:
![image](https://user-images.githubusercontent.com/44384930/61019513-02ac9a00-a3cd-11e9-8ed7-bdba3feece7b.png)

code:
```
from os.path import basename
sc.pl.tsne(adata, color=['GCG', 'INS', 'PPY', 'SST',
                                 'PRSS1'], ncols=2, color_map=cm, save=basename(file)[:-4])
```

**Comment by fidelram** [comment]
This should be related to `matplotlib`. What is happening is that text is being saved as paths. You can probably control this using `rcParams`.
