### ISSUE TITLE
Problem adding sample annotation by pd.dataframe 

### ISSUE THREAD

**Issue by elimereu** [scverse/scanpy#74]
Hi Alex, thank you for this amazing package. I would like to use it for my analysis, but I cannot figure it out why I'm getting this error when I try to include more annotation on my samples.  
Basically, I was following your example here: 

import pandas as pd
anno = pd.read_csv(filename_sample_annotation)
adata.obs['cell_groups'] = anno['cell_groups'] 

However, when I tried with my cvs file, I got Nan for each row and I don't understand. 
The pd data frame is fine, but then the data.var['key'] = NaN NaN NaN ... everywhere..
I post here my code: 

**import pandas as pd

anno = pd.read_csv(path+'sample_anno.csv',header=0)
anno.head()
adata.var['pools']= anno['pools']
adata.var**
![updated_adata var](https://user-images.githubusercontent.com/20638667/35852492-59e9806c-0b2b-11e8-94e2-103c18792cbb.png)
![anno_dataframe](https://user-images.githubusercontent.com/20638667/35852504-5f5a04d6-0b2b-11e8-9c91-0e0d61da3810.png)

Thank you in advance, 

Elisabetta

**Comment by falexwolf** [comment]
Hi Elisabetta,

this is related to automatic matching of indices in dataframes. If the indices don't match, you'll not assign anything. This is the generic behavior of pandas.

If your `anno` dataframe has a different index as compared to the `adata.obs` dataframe, then you cannot meaningfully assign values.

An easy work around is to call
```
adata.obs['cell_groups'] = anno['cell_groups'].values
```
as then, the index is ignored.

Or you do the following directly:
```
adata.obs = anno
```

Or you init the index of `adata.obs` with the cell names in `anno`: either via `adata.obs.index` or `adata.obs_names`. It's the same thing...

Hope this helps.

Let me know if our convention for building the indices of AnnData is not a good one...

Cheers,
  Alex

**Comment by elimereu** [comment]
Thanks! It works! I used your first suggestion. I'm mostly an R user, but in the past I worked on python. I haven't used it for ages and the first thing of R I'm really missing is the help. Here, I can google commands and errors for standard libraries but for example, in the case of new tools, I can just rely on few examples or tutorials.. Or it would be nice for example, also have a list of all the functions in scanpy, with explanation of inputs, outputs and explanation of them. Your documentation is really helpful and well-structured, but I feel a bit limited by that aspect. 
Cheers, 
Elisabetta

**Comment by falexwolf** [comment]
You can google everything in Python as well, you should end up on the following pages... at least if you add "pandas" or "numpy" to your search term...
http://pandas.pydata.org/pandas-docs/stable/
https://docs.scipy.org/doc/numpy-1.13.0/reference/

Don't you get there? The docs there should be at least as good as the Scanpy docs...

PS: In Jupyter notebooks, you can also get help by pressing "Shift + Tab" twice.

**Comment by elimereu** [comment]
Yes, I know that.. but I was referring to new libraries such as your scanpy.

**Comment by dpcook** [comment]
I suspect Elisabetta's concern was more about the general differences in documentation standards between Python packages and R packages (at least within genomics). It can definitely make the transition from R to Python more difficult (I can attest, as I'm going through it right now :P). R packages just tend to come with very thorough vignettes, documenting how the package is supposed to be used end-to-end, highlighting special use-cases, etc. I think [Seurat](http://satijalab.org/seurat/get_started.html), [Monocle](http://cole-trapnell-lab.github.io/monocle-release/), or really any Bioconductor package (eg. [Scater](https://bioconductor.org/packages/release/bioc/vignettes/scater/inst/doc/vignette-intro.html)) are great examples.

Jupyter notebooks are fantastic for helping get an idea of how to use a package, but sometimes the documentation within them is lacking, making it hard to understand what's going on at each step without having to dive into source code. I find Scanpy's straight forward to follow though.

I really appreciate the modular design of Scanpy. At least if you're familiar with single-cell analysis, you can recognize the steps quite easily and just string together the appropriate functions for your analysis pipeline. Some other packages are bit trickier. For example, I found Velocyto (which I love btw) incredibly hard to navigate. There are functions that are used in some analysis notebooks but not all of them, so it becomes unclear what the standard analysis pipeline with it should be. Obviously you can dive into the paper, understand the statistical guts of the method, go through all the source code and see what's there, but then it starts becoming a barrier to newer users adapting it. 

Anyway, this is just a general thing I also noticed moving from R to Python. Not saying that it's something that necessarily needs changing, but it does create a little bit of friction to newer users, so it may be worth thinking about as a community. I suspect this will improve as the genomics user-base of Python increases, and as all these packages have more time to develop. Also, I understand that this is more of a "community" chat and may not belong in the scanpy/issues page anymore, so feel free to close it ;)

**Comment by elimereu** [comment]
Agree! My feeling is also that one to be bound by these tutorials. Pity!

**Comment by flying-sheep** [comment]
> Jupyter notebooks are fantastic for helping get an idea of how to use a package, but sometimes the documentation within them is lacking, making it hard to understand what's going on at each step without having to dive into source code.

that’s a cultural observation, not a technical one. nothing prevents people from writing great notebook-based vignettes (as alex proves)!

**Comment by falexwolf** [comment]
Thank you for these thoughts!

I guess the high documentation quality in R stems from the Bioconductor project, which really set some standards. Nothing like this exists in Python - everyone just does what he or she wants. There are few people thinking about setting up something similar to Bioconductor for Python - but this will likely take some time...

With Scanpy, we try to provide documentation at the Standards of the big packages: numpy, scipy, statsmodels, seaborn, scikit-learn, h5py, pytables, etc. There are many more and all of them have great docs.

I think, with Scanpy, one can still do a lot better. Tuturials tend to be too short. Also, there should be a properly rendered html output of the notebooks - with a button where you can simply download it and then run it yourself to start playing around with it. Hope we will have this in a couple of weeks.

And yes, other packages maybe just need to take time. But I'd guess that this will get much better soon...

**Comment by flying-sheep** [comment]
OK, so we want to build and upload the notebooks. With a bit of convincing, we can get readthedocs to do that for us. But (for a good reason) `scanpy_usage` is a different repo. This means:

1. Changing something there should trigger a rebuild, not changing the scanpy repo
2. We probably need to put them on https://scanpy_usage.readthedocs.io
3. We can convince sphinx to create an index entry for the docs in the navigation sidebar that leads to the scanpy_usage site.

Then it would look like this:

https://scanpy.readthedocs.io:

- Examples → Converted to a fake index entry that is a link to https://scanpy_usage.readthedocs.io
- Basic Usage → …/basic_usage.html
- Installation → …/installation.html
- API → …/api/index.html
- References → …/references.html

https://scanpy_usage.readthedocs.io:

- Examples → /index.html
- Basic Usage → Fake index extry to https://scanpy.readthedocs.io/…/basic_usage.html
- Installation → Fake index extry to https://scanpy.readthedocs.io/…/installation.html
- API → Fake index extry to https://scanpy.readthedocs.io/…/api/index.html
- References → Fake index extry to https://scanpy.readthedocs.io/…/references.html

**Comment by falexwolf** [comment]
Yes, one could think about doing it that way.

I had in mind slowly transitioning to notebooks that download data and run through automatically. One can build docs with them https://nbsphinx.readthedocs.io and possibly use them for testing. In these notebooks, there won't be any images... so it would be fine to add them to the scanpy repo.

It's essentially the same thing as in the numpy etc. tutorials... only that not writing this in .rst but in notebook form gives the user the neat feature of being able to download an executable notebook.

For now, everything is built via https://nbviewer.jupyter.org/. Maybe you haven't yet realized the new layout of https://scanpy.readthedocs.io/en/latest/examples.html... But this is still too manual...

No hurry with these things, though...

**Comment by dpcook** [comment]
Fantastic that this is all getting thought about! :)

Obviously this isn't an overnight thing, it's just something worth thinking about if the hope is to draw in new users (ie. those with minimal computational skills and limited knowledge of scRNA-Seq analysis). I think much of Monocle and Seurat's popularity owes to their comprehensive documentation. I've seen many people with little-to-no programming experience pick these packages up and give them a shot. No reason why Scanpy can't be a new "gold standard" for the field :)

**Comment by flying-sheep** [comment]
> Maybe you haven't yet realized the new layout of https://scanpy.readthedocs.io/en/latest/examples.html... But this is still too manual...

i’ve seen it, it looks really nice! but yes, automation would be cool!

Then we’d never forget to add a new notebook to the list, or get outdated info somewhere and so on.

**Comment by jedjoy** [comment]
> Hi Elisabetta,
> 
> this is related to automatic matching of indices in dataframes. If the indices don't match, you'll not assign anything. This is the generic behavior of pandas.
> 
> If your `anno` dataframe has a different index as compared to the `adata.obs` dataframe, then you cannot meaningfully assign values.
> 
> An easy work around is to call
> 
> ```
> adata.obs['cell_groups'] = anno['cell_groups'].values
> ```
> 
> as then, the index is ignored.
> 
> Or you do the following directly:
> 
> ```
> adata.obs = anno
> ```
> 
> Or you init the index of `adata.obs` with the cell names in `anno`: either via `adata.obs.index` or `adata.obs_names`. It's the same thing...
> 
> Hope this helps.
> 
> Let me know if our convention for building the indices of AnnData is not a good one...
> 
> Cheers, Alex

Hi! I am not sure if this forum is still open or not, but I had a similar question about my code. 
Basically, my indices (rows) do not have a "name" and I am trying to subset off it. Is there anyway to do this? Thanks!
![Screen Shot 2022-01-16 at 10 21 19 PM](https://user-images.githubusercontent.com/97864137/149703124-497ef65e-4d3a-4c45-bd12-45ef67f5d543.png)
![Screen Shot 2022-01-16 at 10 21 31 PM](https://user-images.githubusercontent.com/97864137/149703138-aa2ae8bf-4506-47ba-9bc1-8f5f25e8ad7d.png)


Hi! I am not sure if this forum is still open or not, but I had a similar question about my code.
