### ISSUE TITLE
how to perform analysis to get bulk_labels, S_score, G2M_score, phase?

### ISSUE THREAD

**Issue by grimwoo** [scverse/scanpy#745]
how to perform analysis to get bulk_labels, S_score, G2M_score, phase?

After following the tutorial "[Clustering 3K PBMCs](https://icb-scanpy-tutorials.readthedocs-hosted.com/en/latest/pbmc3k.html)", I got the object "adata" with following description:
_>>> adata
AnnData object with n_obs × n_vars = 691 × 4549
    **obs: 'n_genes', 'percent_mito', 'n_counts', 'louvain'**
    var: 'gene_ids', 'feature_types', 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'louvain', 'louvain_colors', 'neighbors', 'pca', 'rank_genes_groups'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'_ 

however, the tutorial "[Visualizing marker genes](https://icb-scanpy-tutorials.readthedocs-hosted.com/en/latest/visualizing-marker-genes.html?highlight=%27bulk_labels%27)" use the object "pbmc" with following description:
_>>> pbmc
AnnData object with n_obs × n_vars = 700 × 765
    **obs: 'bulk_labels', 'n_genes', 'percent_mito', 'n_counts', 'S_score', 'G2M_score', 'phase', 'louvain'**
    var: 'n_counts', 'means', 'dispersions', 'dispersions_norm', 'highly_variable'
    uns: 'bulk_labels_colors', 'louvain', 'louvain_colors', 'neighbors', 'pca', 'rank_genes_groups'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'_

i want to process my data according those two tutorials and got the figures. but without those information (obs: 'bulk_labels', 'S_score', 'G2M_score', 'phase'), i cannot continue the tutorial from "Clustering 3K PBMCs" to  "Visualizing marker genes"

**Comment by LuckyMD** [comment]
Hi,

Please take a look at the [cell cycle scoring tutorial](https://nbviewer.jupyter.org/github/theislab/scanpy_usage/blob/master/180209_cell_cycle/cell_cycle.ipynb) to find how to generate cell cycle phase scores.

If you'd like a more comprehensive scRNA-seq analysis tutorial that is not based only on scanpy, you can take a look at our single-cell analysis tutorial [here](https://github.com/theislab/single-cell-tutorial). The paper that goes with it can be found [here](http://msb.embopress.org/lookup/doi/10.15252/msb.20188746).

**Comment by grimwoo** [comment]
> Hi,
> 
> Please take a look at the [cell cycle scoring tutorial](https://nbviewer.jupyter.org/github/theislab/scanpy_usage/blob/master/180209_cell_cycle/cell_cycle.ipynb) to find how to generate cell cycle phase scores.
> 
> If you'd like a more comprehensive scRNA-seq analysis tutorial that is not based only on scanpy, you can take a look at our single-cell analysis tutorial [here](https://github.com/theislab/single-cell-tutorial). The paper that goes with it can be found [here](http://msb.embopress.org/lookup/doi/10.15252/msb.20188746).

Thanks a lot.
