### ISSUE TITLE
deep logging not showing up

### ISSUE THREAD

**Issue by ktpolanski** [scverse/scanpy#746]
Hello,

I tried to swap BBKNN over to the new logging, and while the timing aspect of it is functional, the `deep` refuses to cooperate. I checked with `sc.pp.neighbors()` just to make sure I'm not screwing things up massively, and it turns out that its deep also doesn't work.

<img width="940" alt="Screen Shot 2019-07-23 at 09 37 10" src="https://user-images.githubusercontent.com/14993986/61696691-b434bf00-ad2d-11e9-83db-1092dcc61fea.png">

Any idea what's going on here? I'm on python 3.6.7 on Bionic, jupyter 1.0.0, and all this:

    scanpy==1.4.4 anndata==0.6.22.post1 umap==0.3.9 numpy==1.16.4 scipy==1.3.0 pandas==0.25.0 scikit-learn==0.21.2 statsmodels==0.10.1 python-igraph==0.7.1 louvain==0.6.1

**Comment by ktpolanski** [comment]
Just took a look at pbmc3k, your logging still has fractions of a second in there. This logging does not capture times with that accuracy anymore. I tried updating `datetime` in case that's secretly responsible, as you seem to use it internally for time tracking. It was not secretly responsible, the timing discrepancy and lack of deep persists.

**Comment by flying-sheep** [comment]
> your logging still has fractions of a second in there

Shouldn’t be possible, in 709bafb8ed600daf5f9ee995a0dc845ac1e7e605 I set the microseconds to 0, and in `timedelta.__str__`, microseconds [only get added](https://github.com/python/cpython/blob/83cec020ba177fa27727330ba4ccf60eebc22a54/Lib/datetime.py#L596-L597) if they’re >0.

> I tried updating datetime in case that's secretly responsible, as you seem to use it internally for time tracking.

How so? It’s a stdlib module, you can’t update it without updating Python itself.

**Comment by ktpolanski** [comment]
Check `In[20]` [here](https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html), it still shows the fractions. This may no longer be accurate, but the public-facing tutorial still shows it.

EDIT: apparently the tutorial's quite antiquated, version-wise, and was generated on 1.3.7 scanpy. Disregard this sentiment then.

So yeah, stdlib or not, is there some way to overcome this and have the deep come online that you know of?

**Comment by flying-sheep** [comment]
Hi, sorry! deep was nonfunctional, I fixed it in 1.4.4.post1 (just released)

**Comment by ktpolanski** [comment]
Thanks! :)

**Comment by flying-sheep** [comment]
Np, sorry it took so long! I replied only to the fractional-seconds part before and missed your new comment :crying_cat_face:

**Comment by ktpolanski** [comment]
Can confirm everything's operational now, so all's well that ends well.
