### ISSUE TITLE
sc.pp.scale(...,copy=True) returns original adata object

### ISSUE THREAD

**Issue by sophietr** [scverse/scanpy#75]
`adata_scale = sc.pp.scale(adata, copy=True)` seems not to work. `adata_scale.X` contains the original (non-scaled values)

Working alternative:

```py
adata_scale = adata.copy()
sc.pp.scale(adata_scale)
```

**Comment by falexwolf** [comment]
Thank you! :-)

Is fixed in https://github.com/theislab/scanpy/commit/d85810654835bd6c96fffded1e5cba7e5dfa7db7
