### ISSUE TITLE
_rank_genes_groups.py, gene names are trimmed down to 50 characters. 

### ISSUE THREAD

**Issue by BuysDB** [scverse/scanpy#753]
When using long gene names the rank_genes_groups function does not work properly anymore as long gene names are trimmed down to 50 characters, which makes it difficult to look them up again in the adata object. I think the problem is caused on this line:
https://github.com/theislab/scanpy/blob/c5c32f2277ad3f9c5388fc5d0a602151f3bab42b/scanpy/tools/_rank_genes_groups.py#L401 where the gene names are casted to an unicode array with 50 elements.

```
np.array(['LOOONG','SHORT'],dtype='U5')
> array(['LOOON', 'SHORT'], dtype='<U5')
```

**Comment by ivirshup** [comment]
This is a consequence of our rec-arrays where we have to specify the length of strings. I think it would be safe to calculate the maximum length of a gene name instead of using a hard coded value.

**Comment by flying-sheep** [comment]
Is it? Will concatenating indices/columns like this work?

**Comment by ivirshup** [comment]
It'll take a little doing, but it's certainly do-able. Something like this should do it:

```python
import numpy as np
from functools import reduce

def concat(arrays: "list[np.recarray]"):
    names = arrays[0].dtype.names
    dtypes = [dict(a.dtype.descr) for a in arrays]
    assert all(arrays[0].dtype.names == a.dtype.names for a in arrays[1:]), "All arrays should have same names"
    
    offset = 0
    out_dtypes = {}
    for k in names:
        out_dtype = reduce(np.result_type, (dtype[k] for dtype in dtypes))
        out_dtypes[k] = (out_dtype, offset)
        offset += out_dtype.alignment

    out_recarray = np.recarray(sum(map(len, arrays)), dtype=out_dtypes)    
    np.concatenate(arrays, out=out_recarray)
    
    return out_recarray
```

Maybe the solution should happen upstream though. 

Do we concatenate recarrays often?

**Comment by ivirshup** [comment]
Oh, or:

```python
from numpy.lib import recfunctions
recfunctions.stack_arrays(arrays, autoconvert=True, usemask=False)
```

**Comment by flying-sheep** [comment]
Easy enough. And the recarray in question is in `.uns` anyway, so this shouldn’t come up anyway.
