### ISSUE TITLE
'concatenate not found

### ISSUE THREAD

**Issue by corticaltone** [scverse/scanpy#760]
Hi
I am trying to concatenate two anndata objects(adata = adata1.concatenate(adata3, join='inner')), but get an error message informing me that concatenate is not found. Any idea what might cause this behavior? Here is what I have installed:scanpy==1.4.3 anndata==0.6.22.post1 umap==0.3.9 numpy==1.16.2 scipy==1.2.1 pandas==0.24.2 scikit-learn==0.20.3 statsmodels==0.9.0 python-igraph==0.7.1 louvain==0.6.1

and here is the error:
AttributeError                            Traceback (most recent call last)
<ipython-input-187-32c3eda3cdc8> in <module>
----> 1 adata = adata1.concatenate(adata3, join='inner')

~/anaconda3/envs/scenv/lib/python3.6/site-packages/scipy/sparse/base.py in __getattr__(self, attr)
    687             return self.getnnz()
    688         else:
--> 689             raise AttributeError(attr + " not found")
    690 
    691     def transpose(self, axes=None, copy=False):

AttributeError: concatenate not found
Thanks!

**Comment by ivirshup** [comment]
Could you check the type of `adata1`? I'm suspecting it's not an AnnData object.

If it is, could you post a reproducible example of how you got that object?
