### ISSUE TITLE
sc.pl.umap "legend_loc" does not incorporate matplotlib.legend options

### ISSUE THREAD

**Issue by wong-nw** [scverse/scanpy#761]
I'd like to shift a legend with long labels into the upper right corner of the UMAP projection, but going through the code, it appears that any value for legend_loc that is not "right margin" or "on data" becomes "no legend." 

sc.pl.umap(adata,color="samples",legend_loc="upper_right")

**Comment by jlehrer1** [comment]
This is still the case as of the latest version.
