### ISSUE TITLE
sc.pl.heatmap row clustering

### ISSUE THREAD

**Issue by jphe** [scverse/scanpy#766]
Hi,

I want to draw a heatmap to show a group of genes that we interested in in which gropup of cells, However, seems sc.pl.heatmap can only do clustering for cell groups, has no function for the row clustering for genes?

Like the attached heatmap, there are some genes are specific to some groups, does there any method or can add the method for row clustering in scanpy?

Thanks,
Jphe

[heatmap.sepcific-Genes.pdf](https://github.com/theislab/scanpy/files/3464747/heatmap.sepcific-Genes.pdf)

**Comment by gokceneraslan** [comment]
You are looking for [sc.pl.clustermap](https://icb-scanpy.readthedocs-hosted.com/en/stable/api/scanpy.pl.clustermap.html) I think.

**Comment by chansigit** [comment]
sc.pl.clustermap doesn't have any gene inputs.
