### ISSUE TITLE
Code of "converting Seurat object to loom format #652"

### ISSUE THREAD

**Issue by grimwoo** [scverse/scanpy#774]
Hi, thanks for your previous job. And I converted the Seurat.object using as.SingleCellExperiment() according to [this page](https://github.com/LuckyMD/Code_snippets/blob/master/Seurat_to_anndata.ipynb).

Sorry, I‘am a fresh man in this field. Now I wonder what kind of commond (such as write.csv or saveRDS) to use to save the "pbmc_sce" file, and how to read it in Scanpy.

**Comment by LuckyMD** [comment]
Hi,

This might be better posted on the page where you found the code. That way if anyone else has this question, they'll find it there as well. As that's my page, I'll answer here quickly though. `pbmc_sce` is a SingleCellExperiment object that is used e.g., by `scater`. As that's an R object you can use `saveRDS` and `readRDS` for file I/O. You would have to use these commands within the R magics jupyter notebook cells though. Those are the cells that start with `%%R`.
