### ISSUE TITLE
Accessing tSNE coordinates different between sliced and unsliced AnnData

### ISSUE THREAD

**Issue by briangottfried** [scverse/scanpy#778]
I am trying to access tSNE coordinates from a sliced AnnData object. `adata.obsm.X_tsne` works fine. But if I were to filter the AnnData object,`filtered_adata = adata[:, some_filter]`, and then run `filtered_adata.obsm.X_tsne`, I get the error `AttributeError: 'ArrayView' object has no attribute 'X_tsne'`. I can, however, access the coords with `filtered_adata.obsm['X_tsne']`. Is this desired behavior? I feel the API should be the same between the two.

**Comment by ivirshup** [comment]
Whoa, I had no idea you could have ever accessed elements of obsm and varm as attributes. That probably won't be the case for current and future versions of `anndata`, since `obsm` should be a `Mapping` subclass. What versions of scanpy and anndata are you using?

**Comment by briangottfried** [comment]
```
anndata==0.6.21
scanpy==1.4.3
```

**Comment by ivirshup** [comment]
If you update to more recent releases, you won't be able to access elements of `obsm` or `varm` like an attribute. It should all be through `.__getitem__` (e.g. `adata.obsm["X_tsne"]`).
