### ISSUE TITLE
Preparations for UMAP 0.4 release

### ISSUE THREAD

**Issue by gokceneraslan** [scverse/scanpy#779]
Hi, 

We might start testing scanpy with umap 0.4dev branch. Today I ran `sc.pp.neighbors` with umap 0.4dev branch accidentally and got the following exception:

![image](https://user-images.githubusercontent.com/1140359/62968014-29009380-bdd8-11e9-995f-4131ebcb19f5.png)

because `fuzzy_simplicial_set` function in UMAP returns a tuple, not a sparse matrix in 0.4: https://github.com/lmcinnes/umap/blob/0.4dev/umap/umap_.py#L528-L549.

It'd be great to write some tests and check if it's enough to fix this exception.

**Comment by flying-sheep** [comment]
Anything left that #784 didn’t fix?

**Comment by gokceneraslan** [comment]
Haven't tried again but I have a suggestion. Since umap (or pynndescent) is a critical component of scanpy, I think it'd be great to run our tests against both "stable" and "development" branches of umap. However in order for this to happen, umap needs proper naming for the development and stable branches. Right now, there are master, 0.3dev and 0.4dev, therefore the names are version-dependent. 

Does it make sense to file a bug report in umap repo? It'd be a lot easier to run test against two major branches of umap without changing the names in every major release. What do you think?

**Comment by ivirshup** [comment]
Do we know when UMAP 0.4 is due for a release? I wouldn't want to put too much effort into ensuring compatibility with something unstable. If it's really useful now, maybe it's worth it, but it could change again before something gets released.

**Comment by gokceneraslan** [comment]
I don't know when it's due, but if it's released tomorrow scanpy will stop working and that scares me 😑

**Comment by Koncopd** [comment]
@gokceneraslan i checked the changes in the relevant umap functions and i don't see any other problems.
