### ISSUE TITLE
Bug in score function

### ISSUE THREAD

**Issue by dawe** [scverse/scanpy#78]
I've just find out there's a little bug in the scoring function used to calculate cell cycle score. The random genes should be chosen from the same bins of gene_list, but now they are chosen from the whole dataset. The patch to make it work properly:

```
--- a/scanpy/tools/score_gene_lists.py
+++ b/scanpy/tools/score_gene_lists.py
@@ -79,7 +79,7 @@ def score_gene_list(
     control_genes = set()
 
     # now pick 100 genes from every cut
-    for cut in np.unique(obs_cut):
+    for cut in np.unique(obs_cut.loc[gene_list]):
         r_genes = np.array(obs_cut[obs_cut == cut].index)
         np.random.shuffle(r_genes)
         control_genes.update(set(r_genes[:ctrl_size]))  # if ctrl_size > len(r_genes) is not a problem for numpy...
```

**Comment by falexwolf** [comment]
Do you want to push it directly to the master branch?

**Comment by falexwolf** [comment]
Also, I continued our [pull request discussion](https://github.com/theislab/scanpy/pull/76)... :-)

**Comment by dawe** [comment]
Am I allowed to push in the master branch?

**Comment by falexwolf** [comment]
Go ahead!

**Comment by dawe** [comment]
Too late, you have a pull request

**Comment by flying-sheep** [comment]
Great, thank you!
