### ISSUE TITLE
get.rank_genes_groups() key argument not used

### ISSUE THREAD

**Issue by coh-racng** [scverse/scanpy#781]
`rank_genes_groups_df` takes    `key` as an argument and the docs says it is the  key differential expression groups were stored under. However, the function does not use that key and fetches DE results from the default 'rank_genes_groups' key.

line 55 under `rank_genes_groups_df() ` in scanpy/get.py
`d[k] = adata.uns["rank_genes_groups"][k][group]` should be changed to `d[k] = adata.uns[key][k][group]`

**Comment by ivirshup** [comment]
Thanks for catching that!
