### ISSUE TITLE
highly_variable_genes variance computation on dense matrix - Error

### ISSUE THREAD

**Issue by mumichae** [scverse/scanpy#785]
When calling highly_variable_genes on an adata object with dense matrix, I get

```pytb
LinAlgError: Last 2 dimensions of the array must be square
```
The problem seems to come from squaring the means in the  `_get_mean_var` function (`scanpy/preprocessing/_utils.py`)

```py
var = (mean_sq - mean**2) * (X.shape[0]/(X.shape[0]-1))
```
specifically the `mean**2`

**Comment by LuckyMD** [comment]
Hi, 

Please check #456 and #641 .
