### ISSUE TITLE
unable to install louvain on Windows

### ISSUE THREAD

**Issue by hihyein99** [scverse/scanpy#786]
Hi all,
I'm having a trouble in running a code: 
sc.tl.louvain(adata)
So, when I try to run the code, it has an error saying that
ERROR: Failed building wheel for louvain
I tried to install louvain in anaconda prompt, and I can't install it.
When I use:
pip install louvain
to install louvain, I have an error that 

```pytb
ERROR: Command errored out with exit status 1:
'c:\users\prince and jacky\anaconda3\python.exe' \
  -u \
  -c '
import sys, setuptools, tokenize
sys.argv[0] = ".../louvain/setup.py"
__file__=".../louvain/setup.py"
f=getattr(tokenize, "open", open)(__file__)
code=f.read().replace("\r\n", "\n")
f.close()
exec(compile(code, __file__, "exec"))
' \
  install \
  --record '.../install-record.txt' \
  --single-version-externally-managed \
  --compile
Check the logs for full command output.
```

I also tried to install using different codes such as:

```bash
conda install -c conda-forge louvain
```

There's an error saying that:
PackagesNotFoundError: The following packages are not available from current channels:

  - louvain

Can anyone help me with solving this issue? Thanks!

**Comment by Koncopd** [comment]
Hi, try installing python-igraph from the wheel here - https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-igraph
And after that install louvain via pip

**Comment by flying-sheep** [comment]
Yup, not a bug with scanpy, but a problem with installing louvain

**Comment by ivirshup** [comment]
I've talked to some other people who had trouble with this. If there's a better way to install it, I think we should mention it in the docs.

**Comment by flying-sheep** [comment]
Done in c959b8ec8f45eb2251875075de8b17a3604f9b7d
