### ISSUE TITLE
how to name each hdf5 file to find which original object any particular cell came from?

### ISSUE THREAD

**Issue by hihyein99** [scverse/scanpy#799]
Hi everyone, 
I'm having trouble to distinguish the original hdf5 file from the concatenated file.
I used below codes to concatenate 4 hdf5 files into one file:
----------------------------------------------------------------------------------------------------------
filenames = ['filename1','filename2','filename3','filename4']
adatas = [sc.read_10x_h5(filename, gex_only = True) for filename in filenames]
adata = adatas[0].concatenate(adatas[1:])

my concern is to use this code with original file after run filtering and other codes with the concatenated file, for example:
----------------------------------------------------------------------------------------------------------
sc.pl.umap(adata, color=['filename1'])
where filename1 is no longer same as the "actual" filename1, instead it is filtered and normalized

I searched and found that I can do it with Seurat in this way:
----------------------------------------------------------------------------------------------------------

pbmc4k.data <- Read10X(data.dir = "../data/pbmc4k/filtered_gene_bc_matrices/GRCh38/")
pbmc4k <- CreateSeuratObject(counts = pbmc4k.data, project = "PBMC4K")
pbmc8k.data <- Read10X(data.dir = "../data/pbmc8k/filtered_gene_bc_matrices/GRCh38/")
pbmc8k <- CreateSeuratObject(counts = pbmc8k.data, project = "PBMC8K")
pbmc.combined <- merge(pbmc4k, y = pbmc8k, add.cell.ids = c("4K", "8K"), project = "PBMC12K")

Is there any code that I can use for scanpy such as "add.cell.ids = c()" so that I can easily tell which original object any particular cell came from and use the data?

Thank you so much!

**Comment by fidelram** [comment]
check the documentation for AnnData concatenate: https://anndata.readthedocs.io/en/latest/anndata.AnnData.concatenate.html#anndata.AnnData.concatenate

You can add a label to each cell to know from which project it comes
```
adata = adatas[0].concatenate(adatas[1:], batch_key='filename', batch_categories=filenames)
```
