### ISSUE TITLE
create scanpy.object by "CreateSeuratObject(pbmc.matrix, meta.data = pbmc.MetaData)"

### ISSUE THREAD

**Issue by grimwoo** [scverse/scanpy#808]
sorry to start this issue, but i failed in all the methods i found to transport a seurat.object into scanpy, including loom file, SingleCellExperiment …

hence, i wonder if scanpy have the function like seurat that can create an object by `CreateSeuratObject(pbmc.matrix, meta.data = pbmc.MetaData)`.

because i can successfully export the matrix and meta.data from seurat.object, and the meta data is the key information i want to import into scanpy for further analysis.

**Comment by LuckyMD** [comment]
Hey! 
Check out [anndata2ri](https://github.com/theislab/anndata2ri) and how to use it to convert Seurat objects into scanpy on the fly in a Juptyer notebook [here](https://github.com/LuckyMD/Code_snippets/blob/master/Seurat_to_anndata.ipynb). This is the easiest way to convert between the two objects. However, going via loom files should also work. If you search the scanpy issues (also closed issues) you should find some examples.

You can of course also use the anndata creator `anndata.AnnData()` to create a new object. Note that the expression matrix needs to be transposed between R and python analysis tools though.

**Comment by grimwoo** [comment]
> anndata.AnnData()

Thank you for you suggestion! I failed all other methods, including anndata2ri. God know why I encounter so much error. And I've posted issue in the specific place.

**Comment by flying-sheep** [comment]
Great, so I assume this is fixed?
