### ISSUE TITLE
Colors in louvain/tSNE missing in legend

### ISSUE THREAD

**Issue by jorvis** [scverse/scanpy#81]
As we've used this more we've noticed that often the colors on the tSNE plot aren't actually in the legend.  I've attached a screenshot (with poor labeling on my part) to illustrate this.  There are five different pink shades at least in the plot, and only 3 identifiable ones in the legend.

![louvain_coloring](https://user-images.githubusercontent.com/330899/36014141-ebda0614-0d2d-11e8-9722-9ae8219b13d3.png)

**Comment by falexwolf** [comment]
Use the `right_margin` option in the plotting functions... You need more space on the right to display all the columns. Or use `legend_loc='on data'`.

Sorry, for that I still haven't figured out how to compute the white space needed to the left of the figure automatically. Ah, just now I'm having an idea for this. I'll soon fix this.
