### ISSUE TITLE
compute connectivity runtime

### ISSUE THREAD

**Issue by ShobiStassen** [scverse/scanpy#810]
Hi, do you have any analysis / approximate figures or examples for run time of pp.neighbors split into the time taking to find the neighbors (compute_neighbors_umap) and compute the connectivities (compute_connectivites_umap). 
Thanks

**Comment by ShobiStassen** [comment]
hi, it seems like the connectivity takes about 20-15 percent of total pp.neigbors() and drops as the n_samples increases

**Comment by flying-sheep** [comment]
Did you simply set the verbosity to a higher level to get timings or did you have to use profiling or modify the code? If the latter, it might be helpful for more people to do more fine-grained timings.

**Comment by ivirshup** [comment]
My intuition would be neighbor finding would take more time as dataset size increases. What exact fraction of the time will depend a lot on number of samples, number of features, and possibly distance metric. If you're investigating yourself, I think trying `line_profiler`'s `%lprun` on `umap.UMAP.fit` would be a good bet.

I'd also bet that they'd have a better idea over at `UMAP` or Pynndescent.

**Comment by flying-sheep** [comment]
I’ll close this so the issue tracker isn’t blown up too much, but we’ll continue to reply

**Comment by ShobiStassen** [comment]
hi, I just tested a few runs where I added a few lines of code within the compute_neighbors() and compute_connectivites() functions and get the following (in seconds) (thanks for the suggestion using line_profiler, i'll give that a shot later:
![image](https://user-images.githubusercontent.com/35950152/64389655-20694900-d076-11e9-8b39-e0ee75c36db9.png)

**Comment by flying-sheep** [comment]
That’s useful, thank you!

We should probably add those lines ourselves.
