### ISSUE TITLE
Memory issue running zheng17 on ~1M cells

### ISSUE THREAD

**Issue by tomwhite** [scverse/scanpy#811]
Running https://github.com/theislab/scanpy_usage/blob/master/170522_visualizing_one_million_cells/cluster.py on the latest released Scanpy (1.4.4.post1) gives a memory error:

```
reading 1M_neurons_filtered_gene_bc_matrices_h5.h5
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
 (0:01:39)
running recipe zheng17
filtered out 3983 genes that are detectedin less than 1 counts
Killed
```

This is running with 60GB of memory (n1-standard-16), but also occurs with 104GB (n1-highmem-16). It looks like there has been a regression somewhere since this used to run OK. I think the error may be happening in anndata.

**Comment by Koncopd** [comment]
Hm, seems the same as https://github.com/theislab/scanpy/issues/511
So i'm not sure it was ok before.

**Comment by flying-sheep** [comment]
Thank you for the fix @Koncopd!
