### ISSUE TITLE
rank_genes_groups wrong gene name

### ISSUE THREAD

**Issue by jphe** [scverse/scanpy#817]
Hi,

I have sliced some candidate genes (according to my pre-knowledge) from adata, and do sc.tl.rank_genes_groups for adata to check those genes are enriched in which group of cells.  But the output rank gene names is wrong, many of the ouptput genes names are not the in adata.var.index after my selection, which should be already excluded by my candidate genes selection.

Bellow is my code, seems still use the genes before selection? Can you help me?

Thanks,
Jphe

```py
adata_raw =  adata.copy()
df = pd.read_table('/public/home/jphe/omicsdata/genome/mm10/scTE/atac/candidates.txt', header=None)
genes = list(df[0])
genes = [k for k in genes if k in adata.var.index ]
adata = adata[:, genes] # only have ~1000 genes in adata after selection

sc.tl.rank_genes_groups(adata, 'leiden_r0.5', n_genes=20)
sc.pl.rank_genes_groups(adata, n_genes=20, show=True)

adata
```
```
AnnData object with n_obs × n_vars = 53165 × 1080 
    obs: 'batch', 'n_counts', 'n_genes', 'time', 'log_counts', 'mt_frac', 'size_factors', 'leiden_r1', 'leiden_r0.5', 'leiden_r0.1'
    var: 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'leiden', 'neighbors', 'pca', 'time_colors', 'leiden_r0.5_colors', 'rank_genes_groups'
    obsm: 'X_pca', 'X_tsne', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
```

**Comment by ivirshup** [comment]
Do you have values in `adata.raw`? Raw can have a different set of variables than `adata.var`, which could be causing the issue.

**Comment by LuckyMD** [comment]
Hi @jphe,

Just replace the line:
```py
sc.tl.rank_genes_groups(adata,'leiden_r0.5', n_genes=20)
```
with 
```py
sc.tl.rank_genes_groups(adata,'leiden_r0.5', n_genes=20, use_raw=False)
```

**Comment by jphe** [comment]
Yes, it is the adata.raw issues, fixed for set use_raw-False.
Thanks for your help.

**Comment by flying-sheep** [comment]
Great!
