### ISSUE TITLE
interactive visualization

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/scanpy#818]
Dear,

Could scanpy provide some interactive visulaization tools ? So that non-bioinformaticans can also look up the results outuputed by scanpy, just like the following link:

https://scDissector.org/martin

**Comment by LuckyMD** [comment]
@Marius1311 might be able to tell you some more about his [interactive plotting library](https://github.com/theislab/interactive_plotting). This is however more targeted at interactive plotting in notebooks rather communicating with collaborators via servers. [Cellxgene](https://github.com/chanzuckerberg/cellxgene) from CZI is also worth taking a look at for communicating results to non-bioninformaticians.

**Comment by Marius1311** [comment]
@wangjiawen2013 feel free to check out our interactive plotting package for scanpy mentioned by @LuckyMD above (https://github.com/theislab/interactive_plotting) and let me know if you have any questions.

**Comment by gokceneraslan** [comment]
There is already a discussion at https://github.com/theislab/scanpy/issues/253. I think we can close this issue.
