### ISSUE TITLE
Stimulated vs Control analysisi

### ISSUE THREAD

**Issue by sygongcode** [scverse/scanpy#821]
Hello, scanpy developers, 
Firstly, thank you so much for your pipeline scanpy. It is very useful to me.  Secondly, I want to ask a question. Are you going to support Stimulated vs Control analysis? Thank you.
Sincerely yours,
Shangyu

**Comment by LuckyMD** [comment]
Hi @sygongcode,

Are you referring to differential expression testing between conditions? You can do that with `sc.tl.rank_genes_groups()` or in a more advanced way using `diffxpy`, which is easily integrated with `scanpy`. You can find it [here](https://github.com/theislab/diffxpy)

**Comment by sygongcode** [comment]
> Hi @sygongcode,
> 
> Are you referring to differential expression testing between conditions? You can do that with `sc.tl.rank_genes_groups()` or in a more advanced way using `diffxpy`, which is easily integrated with `scanpy`. You can find it [here](https://github.com/theislab/diffxpy)

Yes, that is what I want to do. Thank you so much.
