### ISSUE TITLE
scanpy.api.tl.diffmap documentation

### ISSUE THREAD

**Issue by veghp** [scverse/scanpy#827]
Please consider mentioning explicitly in the documentation of [`scanpy.api.tl.diffmap`](https://scanpy.readthedocs.io/en/stable/api/scanpy.api.tl.diffmap.html#scanpy.api.tl.diffmap) that _"the 0-th column is the steady-state solution, which is non-informative in diffusion maps",_ as mentioned here: https://github.com/theislab/single-cell-tutorial/blob/master/latest_notebook/Case-study_Mouse-intestinal-epithelium_1906.ipynb. Also that it's not plotted by default, cf. https://github.com/theislab/scanpy/issues/675.

It is very important for those who want to use these coordinates (`adata.obsm["X_diffmap"]`).

**Comment by ivirshup** [comment]
This issue has been mentioned on **Scanpy**. There might be relevant details there:

https://scanpy.discourse.group/t/how-are-the-diffusion-plots-generated/400/2
