### ISSUE TITLE
ValueError when using projection = '3d'

### ISSUE THREAD

**Issue by ghost** [scverse/scanpy#829]
Dear Theis lab,
I get the following error:
`ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (0,4) and requested shape (3255,4)`
when running `sc.pl.diffmap(adata, color='leiden', projection='3d', save='_diff_3d.pdf')`

I hope you guys can help me with this.
regards

**Comment by flying-sheep** [comment]
See #663 and #787

**Comment by ghost** [comment]
Thank you!
