### ISSUE TITLE
subgrouping error?

### ISSUE THREAD

**Issue by kevyu27** [scverse/scanpy#833]
I'm trying to take subgroups from the AnnData object as such:
`adata_1 = adata[adata.obs['louvain'] == '0']`
which works but if I want to get the inverse
`adata_1 = adata[adata.obs['louvain'] != '0']`
it sometimes throws this error only on the second line.
'IndexError: index 8 is out of bounds for axis 0 with size 8'
After some debugging, it seems like this occurs when you try run louvain clustering at different resolutions (ie doing it more than once). 

Is there something real elementary that I am missing here? Or is there a better way of doing what I need? Thanks, Kevin

**Comment by kevyu27** [comment]
I think I found a way around it. The issue here is the error is thrown when the new louvain groups are created by the adata.obs['louvain_colors'] are not updated until the plotting sc.pl function is run. Therefore, when you try to slice anything, it throws out an index out of bounds error.

**Comment by flying-sheep** [comment]
Thank you! If you add a few more details we can fix this quickly: Which call will update the groups but not the color and which call will error out with which stack trace? Please add the the traceback to your comment this:

````md
```python
sc.tl.something(adata)
```

```pytb
XError                                Traceback (most recent call last)
....
XError: some message.
```
````

**Comment by ivirshup** [comment]
Possibly related to/ fixed by https://github.com/theislab/anndata/pull/168

**Comment by eroell** [comment]
Thank you for bringing up this issue!

We will close the issue for now, hopefully the expected behaviour is reached here :)

However, please don't hesitate to reopen this issue or create a new one if you have any more questions or run into any related problems in the future.

Thanks for being a part of our community! :)
