### ISSUE TITLE
export the gene list of PCA

### ISSUE THREAD

**Issue by grimwoo** [scverse/scanpy#836]
![image](https://user-images.githubusercontent.com/49429496/64786892-18dbff80-d5a2-11e9-9685-0295e31385f9.png)

Hi, how could I export those genes of PCA into csv? I need the gene list of pc1 to pc9.
it would be better if I can keep the ranking information.

**Comment by davidhbrann** [comment]
Scanpy stores the loadings for each PC in the `adata.varm['PCs']` slot. The order is the same is `obs_names`, but you can use pandas functions like `sort_values` to look at the top genes or do something like `np.argsort` or `scipy.stats.rankdata` on the columns (the PCs) to get their ranks.

```python
import scanpy as sc
import numpy as np

pbmc = sc.datasets.pbmc68k_reduced()
sc.tl.pca(pbmc, svd_solver='arpack', random_state=0)
# Get loadings for each gene for each PC
df_loadings = pd.DataFrame(pbmc.varm['PCs'], index=pbmc.var_names)
# get rank of each loading for each PC
df_rankings = pd.DataFrame((-1 * df_loadings.values).argsort(0).argsort(0), index=df_loadings.index, columns=df_loadings.columns)
# c.f. with df_loadings.apply(scipy.stats.rankdata, axis=0)
# evaluate 
print("Top loadings for PC1...")
print(df_loadings[0].sort_values().tail())
print("Rank of PTPRCAP for first 5 PCs...")
print(df_rankings.loc["PTPRCAP"].head())
sc.pl.pca_loadings(pbmc)

# alternatively, you can do SVD or PCA manually with scipy, numpy, sklearn, etc.
# from sklearn.decomposition import PCA
# pc = PCA(n_components=50, svd_solver='arpack', random_state=0).fit(pbmc.X)
# pc.components_.T has the loadings
```

**Comment by grimwoo** [comment]
it works! thank you so much @dhb2128 

i add a little code in the end to export the name of genes to csv.

`df_loadings[0].sort_values().tail(30).to_csv('/home/PC1.csv')`
