### ISSUE TITLE
Inconsistent results with groups parameter in rank_genes_groups

### ISSUE THREAD

**Issue by fbrundu** [scverse/scanpy#842]
I get inconsistent results when I use the parameter groups in `rank_genes_groups`. What I want to achieve is to focus on some groups for the DE genes computation. However, the results I get using the parameter groups, to select a subset of groups, are the same, in terms of DE genes, with respect to using the full set of groups.

For example, l get different results if I run the following two snippets of code (which should provide instead the same set of DE genes).
``` python
# Subsetting should be done by method
sc.tl.rank_genes_groups(
    adata=adata,
    groupby='leiden',
    use_raw=False,
    method='t-test',
    groups=['1', '2'],
)
```

``` python
# Explicit subsetting
adata_f = adata[adata.obs['leiden'].isin(['1','2'])].copy()
sc.tl.rank_genes_groups(
    adata=adata_f,
    groupby='leiden',
    use_raw=False,
    method='t-test',
)
```

**Comment by ivirshup** [comment]
What's happening is in the first test you're still comparing each group to all other cells.

Here's a quick example of that:

```python
import scanpy as sc
import numpy as np

adata = sc.datasets.pbmc68k_reduced()
adata.X = adata.raw.X.copy()
sc.tl.leiden(adata)
a = sc.tl.rank_genes_groups( 
    adata=adata, 
    groupby='leiden', 
    use_raw=False, 
    method='t-test', 
    groups=['1', '2'], 
    n_genes=adata.shape[1], 
    copy=True 
)
b = sc.tl.rank_genes_groups( 
    adata=adata, 
    groupby='leiden', 
    use_raw=False, 
    method='t-test', 
    # groups=['1', '2'], 
    n_genes=adata.shape[1], 
    copy=True 
)

assert np.all(sc.get.rank_genes_groups_df(a, "1") == sc.get.rank_genes_groups_df(b, "1"))
```

**Comment by fbrundu** [comment]
Thanks, however I think the [documentation](https://scanpy.readthedocs.io/en/stable/api/scanpy.tl.rank_genes_groups.html#scanpy.tl.rank_genes_groups) is not perfectly clear about it:

> groups : str, Iterable[str]
Subset of groups, e.g. ['g1', 'g2', 'g3'], to which comparison shall be restricted, or 'all' (default), for all groups.

What do you think?

**Comment by flying-sheep** [comment]
Sorry about that. Any idea how we can be clearer?

**Comment by fbrundu** [comment]
No worries. It can be something like:

> Subset of groups, e.g. ['g1', 'g2', 'g3'], for which the list of DE genes should be computed. Each group of cells is always compared to the remaining cells, even if they don't belong to the subset of groups.

However, it would be probably more useful to change the API and to implement subsetting of the groups through the 'groups' parameter. I think this would be more intuitive, also together with the use of the 'reference' parameter.
In particular, because retrieving of DE genes for specific groups can be more easily done with the [get](https://scanpy.readthedocs.io/en/stable/api/scanpy.get.rank_genes_groups_df.html#scanpy.get.rank_genes_groups_df) interface.
But there may be other use cases I haven't considered in which the actual implementation may be useful.
