### ISSUE TITLE
Numba error in calculate_qc_metrics on a windows machine

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy#843]
Numba issue: https://github.com/numba/numba/issues/4529

The issue seems to come from `np.array(..., dtype=np.int)` and `sparse.csr_matrix(...).indptr.shape - 1` not having equivalent dtypes.

I'm unable to reproduce on my machine, so I'm guessing this is coming from @fkoegel being on a windows machine.

**Comment by ivirshup** [comment]
It looks like the underlying issue (`np.zeros` was being called with a heterogeneous `shape` tuple) has been marked to be resolved in the next numba release. We could implement a workaround here where we force the dtype, though numba does have a pretty fast release cadence.

@fkoegel, if we implemented a fix here would you be able to test it for us on master branches?

**Comment by pati-ni** [comment]
@ivirshup I am getting same numba errors on windows 10 machine. I can test the workaround if you provide a fix. Currently to make the function working I set `percent_top=None`

**Comment by ivirshup** [comment]
I think I've come up with a fix upstream in numba (https://github.com/numba/numba/pull/4729). What's your comfort level with using a development branch of that? It would require a bit of compilation.

Otherwise I can open a quick fix branch here. Basically all that would include would be is changing this line:

https://github.com/theislab/scanpy/blob/e6e08e51d63c78581bb9c86fe6e302b80baef623/scanpy/preprocessing/_qc.py#L391

to:

```python
partitioned = np.zeros((indptr.size - 1, np.int64(maxidx)), dtype=data.dtype)
```

**Comment by ivirshup** [comment]
Fixed upstream
