### ISSUE TITLE
Documentation request: Violin plot example (cell-group based)

### ISSUE THREAD

**Issue by jorvis** [scverse/scanpy#85]
I see in the seurat notebook examples of violin plots grouped by genes.  I'm wanting to use scanpy to create them based on groups of cells like this:

![screenshot from 2018-02-12 13-37-24](https://user-images.githubusercontent.com/330899/36115848-edbb6d78-0ff9-11e8-96f8-c850751b30a9.png)

That one I created using seaborn and generating the needed data structure in memory, but this doesn't scale for the single cell datasets.  I see that scanpy's violin function does this directly from the H5AD file but I'm not sure how to define the cell groupings.  In the input file, the columns are like this:

```
Gene_symbol	SC--Cell_1	SC--Cell_1	HC--Cell_2
Xkr4	-0.0570836643241332	-0.0803735118467587	-0.195958388077514
Rp1	-0.0321529591027553	-0.0215917209771662	0.00422717000571775
Sox17	-0.0935010662698698	-0.0807672959542563	-0.034341176505057
Mrpl15	-0.574536220083904	-0.618070030422496	0.385746977543053
Lypla1	-0.429508492410599	-0.465495040843167	-0.491170048865423
```

So here the column convention is GROUP--CELLID.  I read this using scanpy and save as h5ad.  This code generates a plot, but only works on very small datasets.  Otherwise it takes hours.  I'd love to do it with scanpy directly.  Any help is greatly appreciated.

```
    headings = ['Expression', 'Location']
    edata = []

    adata = sc.read_h5ad(h5_path)
    selected = adata[:, adata.var_names.isin([gene.gene_symbol,])] 

    # This is for a complete matrix
    for g, gene in enumerate(selected.var_names):
        for c, cell in enumerate(selected.obs_names):
            if '--' in cell:
                cell = cell.split('--')[0]

            edata.append( [selected.X[c], cell] )
    
    if len(edata) > 0:
        df = pd.DataFrame( edata, columns=headings )

        ax = sns.violinplot(
            x="Location", y="Expression",
            data=df,
            bw=.3,
            scale="width",
            inner=None,
            linewidth=0.3
        )

        ax = sns.stripplot(x="Location", y="Expression", data=df, jitter=True, size=2, color="0")

        labels = []
        for l in ax.get_xticklabels():
            labels.append(l.get_text())

        ax.set_xticklabels(labels, rotation=45)
        ax.set(ylabel='Expression')
        # ax.set(ylim=(-0.5, 2.5))

        fig = ax.get_figure()
        fig.tight_layout()

        temp_image_file = "/tmp/{0}_violin.png".format(os.getpid())
        fig.savefig(temp_image_file, dpi=100)

```

**Comment by falexwolf** [comment]
Hi Joshua, can you upload an example dataset somewhere? So that I can reproduce the figure above? I'm confident that I can speed this up...
PS: Still consolidating all the gene correlation stuff... Everything works, but we do not want to expose things to the user that have not been checked 3 times... in particular the conventions need to be intuitive etc.
PPS: The new cell cycle example could interest you:
https://scanpy.readthedocs.io/en/latest/api/scanpy.api.tl.score_genes.html
https://scanpy.readthedocs.io/en/latest/api/scanpy.api.tl.score_genes_cell_cycle.html
Both link to the notebook in the "Examples" section
https://nbviewer.jupyter.org/github/theislab/scanpy_usage/blob/master/180209_cell_cycle/cell_cycle.ipynb

**Comment by jorvis** [comment]
Alex - Thanks for the links, I'll look them over.  And good news about the gene correlation work.

I've placed links to both the tab and h5ad files for an example dataset in a [folder on Dropbox](https://www.dropbox.com/sh/44i9jiy6h8ms9mc/AADOITmx9URHloDF7Yj6NTE2a?dl=0)

That's not the same as in the screenshot, which isn't a public dataset yet, but this one is the same idea.  Wanting to be able to rapidly generate a violin plot for any given gene.

**Comment by jorvis** [comment]
Thinking about this more I think ideally we wouldn't really on the obs column name "--" convention and rather place and filter this based on data put in .uns, right?  Just have to learn how to do that ....

**Comment by jorvis** [comment]
Checking in here again.  Welcome back.  This is our most critical "uh oh, it broke when we switched to anndata" thing at the moment.

**Comment by falexwolf** [comment]
Hi Joshua,

ok, first of all, you should store the group id as a field in the annotation of observations/cells (`.obs`).  Taking your AnnData, you'd do the following:
```
adata.obs['mygroups'] = [name.split('--')[0] for name in adata.obs_names]
```
You can then do 
```
sc.pl.violin(adata, 'mygene', group_by='mygroups')
```
as in the [standard example](https://nbviewer.jupyter.org/github/theislab/scanpy_usage/blob/master/170505_seurat/seurat.ipynb), box [32].

Instead of 'mygene', you can use any annotation key; for instance gene scores, as produced by `sc.pp.score_genes`. Or averages over genes `adata.obs['my_gene_set_avg'] = adata[:, gene_set].X.mean(axis=1)`.

Does this help or did I misunderstand something?

PS: As a principle rule for writing efficient python code: never loop over more than a 100 items... absolutely never use nested loops. :wink:

**Comment by falexwolf** [comment]
Maybe I misunderstood something, because your loop over genes
```
    for g, gene in enumerate(selected.var_names):
        for c, cell in enumerate(selected.obs_names):
            if '--' in cell:
                cell = cell.split('--')[0]
            edata.append( [selected.X[c], cell] )
```
doesn't seem to actually do something...

**Comment by falexwolf** [comment]
We'll figure this out. :smile:

What do you mean when you say "uh oh, it broke when we switched to anndata"; what did you use before? What are your suggestions for improving it.

**Comment by jorvis** [comment]
Thanks, that's all very helpful.  I'll work on getting these recommendations integrated.  One quick question, is this still the most efficient way to get the data for one gene for the violin plot?

selected = adata[:, adata.var_names.isin([gene.gene_symbol,])]

And before all the data was just in relational tables but, of course, the scale was a lot less.

EDIT: I just re-read and saw that it seems you can pass the gene name to the violin() call itself.  Beautiful magic.

**Comment by falexwolf** [comment]
Yes, you simply pass a single gene name to the violin plot... :smile:

**Comment by jorvis** [comment]
I wanted to report success here.  I had to change your references to var_names above to obs_names but got it working after that.  Now I just need to figure out how to access the plot customization methods so I can clean it up.  The labels are all blurred together, for example.
![screenshot from 2018-03-06 11-16-16](https://user-images.githubusercontent.com/330899/37047580-01c7b8e2-2131-11e8-9bb7-d060bfc6d0d6.png)

**Comment by jorvis** [comment]
I was following the documentation and kept getting failures when I tried to pass additional args to violin() via kwargs, and found that kwargs was only [added to violin 6 days ago](https://github.com/theislab/scanpy/blame/master/scanpy/plotting/anndata.py#L347).  Yay (and thanks) for the updates)

**Comment by falexwolf** [comment]
Great! More customization can be done when you pass `show=False` to `pp.violin` and operate on the returned `matplotlib.Axes` object. In your case you can just do `pl.xticks(rotation=90)`.

**Comment by falexwolf** [comment]
So I guess, this is fine, now. PS: In Scanpy 1.0, there is also a `rotation` parameter for the labels in the violin plot. The introductory [tutorial](https://nbviewer.jupyter.org/github/theislab/scanpy_usage/blob/master/170505_seurat/seurat.ipynb) shows how this works.
