### ISSUE TITLE
sc.pl.correlation_matrix `save` parameter broken

### ISSUE THREAD

**Issue by grimwoo** [scverse/scanpy#850]
I followed the “Plot correlation” of [tutorial](https://scanpy-tutorials.readthedocs.io/en/latest/visualizing-marker-genes.html) and I cannot save the figure.

ps: the previous code in that tutorial worked perfectly.

### My code:
```python
import numpy as np
import pandas as pd
import scanpy as sc
from matplotlib import rcParams
import matplotlib.pyplot as plt

fig = plt.figure()
sc.tl.dendrogram(adata, 'louvain', n_pcs=30)
sc.pl.correlation_matrix(adata, 'louvain', save='Correlation--57.png')
```
```console
[<matplotlib.axes._subplots.AxesSubplot object at 0x7fd3efc98390>,
 <matplotlib.axes._subplots.AxesSubplot object at 0x7fd3efa84dd8>,
 <matplotlib.axes._subplots.AxesSubplot object at 0x7fd3f0157320>]
```
```python
ax = sc.pl.correlation_matrix(adata, 'louvain', save='Correlation--57.png')
ax
```
```console
[<matplotlib.axes._subplots.AxesSubplot object at 0x7fd3efc98390>,
 <matplotlib.axes._subplots.AxesSubplot object at 0x7fd3efa84dd8>,
 <matplotlib.axes._subplots.AxesSubplot object at 0x7fd3f0157320>]
```
```python
fig.savefig('/public-supool/home/wuhaoda/Scanpy/figures/57.png')
```
### And I can only get "57.png" rather than "Correlation--57.png". More inportantly, the "57.png" is purely blank as attached.
![57](https://user-images.githubusercontent.com/49429496/65104442-029bcc80-da04-11e9-96e3-0563c4145af1.png)

**Comment by flying-sheep** [comment]
It’s hard to read … Please use markdown syntax for code:

````markdown
My code:

```python
<code here>
```
````

And signify which lines are code and which are output, e.g. by adding `#` in front of output lines

**Comment by grimwoo** [comment]
@flying-sheep sorry for the trouble, I have updated my code and output.

**Comment by flying-sheep** [comment]
Uh, you didn’t, otherwise it would have a light grey background and be typeset in a monospace font. you need to put ```` ```python```` in the line above your code and ```` ``` ```` in the line below. Also Python expressions are usually prefixed by `>>>`, not `$`, but that’s no problem.

**Comment by grimwoo** [comment]
I tried ">>>" before, and thought the grey front may make it difficult for you to read....and then change it to $..... I would use that next time.

**Comment by flying-sheep** [comment]
It’ll look fine. Please do it, it’s the way code is displayed in comments on GitHub.

**Comment by grimwoo** [comment]
mission complete :)

**Comment by flying-sheep** [comment]
Looks good, thank you. The reason I was so insistent is that it’s important here what the notebook cells are.

Jupyter notebook/lab does fancy stuff with matplotlib figures, so that might well be a factor here.

Am I right that each of the 3 code blocks is a separate cell in your notebook?

**Comment by grimwoo** [comment]
@flying-sheep  sorry, I didn't use Jupyter notebook. one is because i am a fresh man in python. second is that our engineer of the lab server told us that we don't have "??? some image software" due to the limited memory. (I think, he means we could use R, but we cannot see the figure like Rstudio. we have to save it, download it to our PC, and view the figure.) I would try Juputer tomorrow~

**Comment by flying-sheep** [comment]
Well, it makes working with all this easier, specifically if you can just see your figures inline instead of popup windows. You can try out jupyterlab here to get a small tutorial: https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/try.jupyter.org?urlpath=lab

If you think you’d like it, just `pip install jupyterlab` and start it with `jupyter lab`

**Comment by grimwoo** [comment]
@flying-sheep Thank you!!

**Comment by flying-sheep** [comment]
Sure! By the way: this is still a bug: `save` doesn’t seem to work at all!

```python
>>> import scanpy as sc
>>> adata = sc.datasets.pbmc68k_reduced()
>>> sc.tl.dendrogram(adata, 'louvain', n_pcs=30)
>>> sc.pl.correlation_matrix(adata, 'louvain', save='Correlation--57.png')
[<matplotlib.axes._subplots.AxesSubplot object at 0x7f7e4f5ab390>,
 <matplotlib.axes._subplots.AxesSubplot object at 0x7f7e5bfbd1d0>,
 <matplotlib.axes._subplots.AxesSubplot object at 0x7f7e4f55a8d0>]
```

I looked into the code and `correlation_matrix` doesn’t accept the `ax` parameter, but instead creates a figure. Your code doesn’t work because it won’t use your figure, therefore it stays empty!

What you can do now is:

```python
axes = sc.pl.correlation_matrix(adata, 'louvain')
axes[0].figure.savefig('57.png')
```
