### ISSUE TITLE
module 'scanpy' has no attribute 'get'

### ISSUE THREAD

**Issue by jkanche** [scverse/scanpy#851]
Hello, 

I am using scanpy version 1.4 from bioconda.

I am running one of the examples from the code to query datasets - 

```
import scanpy as sc

pbmc = sc.datasets.pbmc3k()
print(pbmc)
plotdf = sc.get.obs_df(
    pbmc,
    keys=["CD8B", "n_genes"],
    obsm_keys=[("X_umap", 0), ("X_umap", 1)]
)
plotdf.plot.scatter("X_umap0", "X_umap1", c="CD8B")
```

the library can read the dataset but errors out saying `scanpy` has no attribute `get`.

I even tried 

```File "test.py", line 2, in <module>
    from scanpy.get import obs_df
ModuleNotFoundError: No module named 'scanpy.get'
```

Did the API change for any of this ? Thanks!

**Comment by jkanche** [comment]
update on this, seems like this is an issue when the package is installed through conda,

reinstalled the package using pip and everything works!

**Comment by flying-sheep** [comment]
Great!

**Comment by gokceneraslan** [comment]
@flying-sheep do we benefit from the conda package at all? I have been hearing complaints about it being outdated. if it's not maintained as good as the pypi package why don't we drop it?

**Comment by flying-sheep** [comment]
We don’t support it, @bgruening and @epruesse seem to do it: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/scanpy/meta.yaml

**Comment by jkanche** [comment]
some of the datasets like pbmc68k-reduced also seem to have an issue loading in conda.

**Comment by grst** [comment]
Actually I've always been using the conda package and never had any issues. 
Github releases are watched by the bioconda-bot, so it should never be out of date, either.
