### ISSUE TITLE
AttributeError: module 'tables' has no attribute 'which_lib_version'

### ISSUE THREAD

**Issue by yuntianzhishang** [scverse/scanpy#853]
Hello,

I am a beginner in the bioinformatics field. I have been used scanpy for one year, and I really like it. But yesterday after I downloaded and installed the new developmental version from scanpy github, when I ran the first command "import scanpy as sc", it displayed errors :AttributeError: module 'tables' has no attribute 'which_lib_version'. I don't know how to deal with this error. Does the "module 'tables' " in the error message mean pytables? After I saw the message, I reinstalled both pytables and scanpy through conda channel. But the error is not fixed. I thus wish to get some suggestions. Thank you so much!

**Comment by flying-sheep** [comment]
Yes, the `tables` module is provided by the PyPI package `pytables`. That’s confusing so most PyPI packages are named the same as the Python packages they contain. Another notable exception is `Pillow`, which installs a module named `PIL`.

Please post the output of `scanpy.logging.print_versions()`

**Comment by yuntianzhishang** [comment]
Hello,

I just type "import scanpy", and it still shows the error message. 

Here is my code. 

```py
import scanpy
```

Here is what the computer showed after I ran this code:

```pytb
AttributeError                            Traceback (most recent call last)
<ipython-input-2-135279188441> in <module>
----> 1 import scanpy

~/Documents/scanpy/scanpy/scanpy/__init__.py in <module>
     34 # the actual API
     35 from ._settings import settings, Verbosity  # start with settings as several tools are using it
---> 36 from . import tools as tl
     37 from . import preprocessing as pp
     38 from . import plotting as pl

~/Documents/scanpy/scanpy/scanpy/tools/__init__.py in <module>
     15 from ._leiden import leiden
     16 from ._louvain import louvain
---> 17 from ._sim import sim
     18 from ._score_genes import score_genes, score_genes_cell_cycle
     19 from ._dendrogram import dendrogram

~/Documents/scanpy/scanpy/scanpy/tools/_sim.py in <module>
     23 
     24 from .. import _utils
---> 25 from .. import readwrite
     26 from .._settings import settings
     27 from .. import logging as logg

~/Documents/scanpy/scanpy/scanpy/readwrite.py in <module>
      7 import numpy as np
      8 import pandas as pd
----> 9 import tables
     10 import anndata
     11 from anndata import (

~/anaconda3/lib/python3.6/site-packages/tables/__init__.py in <module>
     91 
     92 # Necessary imports to get versions stored on the cython extension
---> 93 from .utilsextension import (
     94     get_pytables_version, get_hdf5_version, blosc_compressor_list,
     95     blosc_compcode_to_compname_ as blosc_compcode_to_compname,

tables/utilsextension.pyx in init tables.utilsextension()

~/anaconda3/lib/python3.6/site-packages/tables/tables/__init__.py in <module>
    122 from .flavor import restrict_flavors
    123 from .description import *
--> 124 from .filters import Filters
    125 
    126 # Import the user classes from the proper modules

~/anaconda3/lib/python3.6/site-packages/tables/tables/filters.py in <module>
     27 from tables.req_versions import min_blosc_bitshuffle_version
     28 
---> 29 blosc_version = LooseVersion(tables.which_lib_version("blosc")[1])
     30 
     31 

AttributeError: module 'tables' has no attribute 'which_lib_version'
```

I used Jupyter Notebook. Should I update any package? Thank you so much!

**Comment by flying-sheep** [comment]
well, generally updating everything could fix it, but another alternative is that you have a `tables.py` in your $PYTHONPATH (`sys.path`) which gets imported instead of the correct pytables version.

See https://github.com/pandas-dev/pandas/issues/26052#issuecomment-482116173

**Comment by yuntianzhishang** [comment]
Hello,

I uninstalled tables with pip, and it seems everything is working now. Thank you so much!

**Comment by flying-sheep** [comment]
Great!
