### ISSUE TITLE
Tutorial on quantification

### ISSUE THREAD

**Issue by k3yavi** [scverse/scanpy#856]
Hi team Scanpy,

Thanks for developing this awesome suite of library and above all actively maintaining it.
I found [this](https://scanpy.readthedocs.io/en/stable/tutorials.html) tutorial page very helpful to get started for exploring the world of single-cell in python, using one stop libraries of scanpy.

I am curious if you are interested in adding some tutorials related to quantification of the RNA-seq data i.e. in scanpy world it would be preprocessing step to generate the cell-v-gene counts. I am one of the author of the tool [alevin](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1670-y), we developed for quantifying 3' droplet based single cell data, somewhat in the line of Cellranger, although ours is a principled approach to consume the gene multi-mapping reads instead of dropping them all together. I have been writing some of the tutorials myself [here](https://combine-lab.github.io/alevin-tutorial/) but was wondering is there a way of supporting them directly in scanpy.

The default output format (cell-v-gene matrix) of alevin is a binary format but it would be interesting to check if we can directly dump or post process it to `annData`format. I have been doing some analysis comparing various output formats (h5, mtx, csv, loom Eds) through their disk size, loading time and memory usage [here](https://github.com/COMBINE-lab/EDS).

Looking forward to hearing back.

**Comment by fidelram** [comment]
Hi @k3yavi, I would be great to have a tutorial in which an alevin generated matrix is loaded into scanpy. Your suggestion is to have such a tutorial hosted by scanpy or you plan to add it to your list of tutorials?

**Comment by k3yavi** [comment]
Hi @fidelram ,

Thanks for the response.
I think either or both would be great. Excuse my ignorance, what's the efficient to interact with scanpy, I am guessing `annData` ? If `annData` I am again guessing that the object can be efficiently made given the CSR/CSC sparse matrix or is there already a support to import other binary matrix formats ?

Currently alevin dumps [EDS](https://github.com/COMBINE-lab/EDS) (a binary matrix format), and I wrote a small Rust library to convert it to other formats (h5, csv, mtx) and found EDS is faster to load and uses less memory, at least in R. We have a support of EDS in R world through Mike Love's awesome `tximport` package. Since scanpy provides great support and efficient implementation of various single-cell analyses for the python world, I'd love to make EDS import and alevin interaction for downstream processing as efficient as possible.

**Comment by fidelram** [comment]
@k3yavi The right place to ask those questions is on the AnnData repository where all the read and write functions are located. [Here](https://icb-anndata.readthedocs-hosted.com/en/stable/api.html#reading) you can find the available read options. You are welcome to contribute! Would be great if AnnData can read EDS files.

**Comment by k3yavi** [comment]
Sure, thanks for the pointer.
