### ISSUE TITLE
Integrate data from different treatments and perform differential gene expression analysis according to treatment and cell type

### ISSUE THREAD

**Issue by swokybio** [scverse/scanpy#859]
Hi, 

First of all, I would like to thank the developers for this awesome tool! I am new to Scanpy. I am migrating from Seurat to Scanpy as I would like to perform trajectory analysis in my data.

I have single cell sequencing data from 12 samples and 3 treatments (so 4 samples per treatment). I merged the samples from the same treatment in a single matrix using ‘cellranger’ software from 10x Genomics (so I have 3 matrixes from 3 different treatments to import to Scanpy). 

In ‘Seurat’, I can read the data from my three treatments separated, do quality control, and then integrate them using ‘FindIntegrationAnchors’ and ‘IntegrateData’ functions. Then, I perform cluster analysis in the integrated dataset, and test the effect of treatment on the transcriptome of each cluster. 

Is there a similar function in ‘Scanpy’ to integrate different datasets which are labeled in order to perform cluster analyses in the integrated dataset and test for the effect of treatment in the transcriptome of identified cell types? If so, is there a tutorial for that?

In ‘Scanpy’ I am able to import the data and perform quality control and cluster analysis. Thus, if there was a way of integrating the 3 different matrixes in one single object that would be helpful.

Any suggestions on how I should proceed to integrate my data and perform differential gene expression analysis according to treatment and cell type?

Thank you very much!

Joao

**Comment by flying-sheep** [comment]
Hi! Welcome to the community. For questions like this, https://scanpy.discourse.group/ would be the ideal place!

Generally: If you can’t find what you search in the regular anndata or scanpy API docs, you can always try [`scanpy.external`](https://icb-scanpy.readthedocs-hosted.com/en/stable/external/index.html), where you should e.g. find answers for your first question. I don’t think we have a tutorial for this yet, though.

For simply `concatenate`ing multiple `AnnData` objects, the anndata docs should help you out.

**Comment by LuckyMD** [comment]
Hi. While @flying-sheep is right that this is a question for the discourse group, I have a quick response here.

Check out the tutorials here:
https://scanpy.readthedocs.io/en/stable/tutorials.html

You can merge anndata objects with `anndata.concatenate()`, and if you're looking for data integration methods, there are a couple of them in `scanpy.external`. For example MNN (works better in `mnnpy` though), and BBKNN. Scanorama also has a nice scanpy interface... and I think `SCVI` also has a scanpy integration tutorial (but can be harder to use than scanorama).

**Comment by swokybio** [comment]
@LuckyMD 

Thank you very much for pointing me in the right direction!! I was able to merge the my anndata objects using ```anndata.concatenate()``` than I created the trajectory analysis for the identified clusters using ```sc.pl.paga```.

As explained in my initial post, I have data from 12 samples and 3 treatments. When I created my anndata object, I labeled the batch categories using the following command:

```adata_merged = adata_ESTRUS.concatenate(adata_DIESTRUS, adata_PROESTRUS,batch_categories=['ESTRUS','DIESTRUS','PROESTRUS'])```

Now, I would like choose a cell type (one specific identified clusters) to perform trajectory analysis according to treatment (in my case batch_category). Do you have any suggestions on how to do that?

Thanks again!!

Joao

**Comment by LuckyMD** [comment]
Hi Joao, 

These types of questions should be addressed in the discourse group. Please move there and ask again. We shouldn't continue a thread here that was closed due to wrong posting.

**Comment by swokybio** [comment]
Hi @LuckyMD,

Sounds good, will do!

Thanks, Joao
