### ISSUE TITLE
Getting eigenvalues of PCs

### ISSUE THREAD

**Issue by LucasESBS** [scverse/scanpy#86]
Hello everyone,

In order to get eigenvalues of the PCs after running PCA, I modified the simple.py code by adding a line to return pca_.explained_variance_ and store it in adata.uns in the pca function definition. This might be useful for users wanting to access eigenvalues of the PCs, which is not possible as far as I know with only the explained_variance_ratio. Would it be a good idea to open a pull request for that?

        else:
            logg.m('compute PCA with n_comps =', n_comps, r=True, v=4)
            result = pca(adata.X, n_comps=n_comps, zero_center=zero_center,
                         svd_solver=svd_solver, random_state=random_state,
                         recompute=recompute, mute=mute, return_info=True)
            X_pca, components, pca_variance_ratio, pca_eigenval = result
            adata.obsm['X_pca'] = X_pca
            adata.varm['PCs'] = components.T
            adata.uns['pca_eigenvalues']=pca_eigenval
            adata.uns['pca_variance_ratio'] = pca_variance_ratio
            logg.m('    finished', t=True, end=' ', v=4)

.......

    if False if return_info is None else return_info:

        return X_pca, pca_.components_, pca_.explained_variance_ratio_, pca_.explained_variance_
    else:
        return X_pca

Thank you!

**Comment by falexwolf** [comment]
Yes, sure! Go ahead and make a pull request! :smile:
