### ISSUE TITLE
n_genes and normal distribution

### ISSUE THREAD

**Issue by grimwoo** [scverse/scanpy#866]
Hi, I recently found that the parameter of filtering, n_genes, is determined arbitrarily. Hence, could we use the normal distribution and the threshold value (5% and 95%) to do the job?

The scanpy gives the violin plot for n_genes, but I really want a density plot (imagined as attached). Specifically, after the plot, it could automatically do the "shapiro test" to see if it fits the normal distribution and give the the threshold value of 5% and 95% respectively. And the users could decide whether they want to filter the data by these parameters through n_genes.

![imagine](https://user-images.githubusercontent.com/49429496/66399459-3752e080-ea12-11e9-8458-af332e620975.png)

**Comment by fidelram** [comment]
Are you talking about the filtering function that remove cells? If you want to contribute a PR for this please do it.

**Comment by grimwoo** [comment]
I'm asking for help, :)

**Comment by grimwoo** [comment]
I've wrote some code in R to remove (show the min and max of n_genes and percent_mito) by boxplot. It would read the metadata of the "obs.csv" and give the txt file which includes the result.

The following is the R code:

> 
> setwd("Z:/Scanpy/unofficial fig")
> library(stringr)
> library(ggplot2)
> 
> Total_Matrix <- read.csv("Z:/Scanpy/unofficial fig/Pre-Metadata/obs.csv", header = T)
> 
> Plot <- ggplot(Total_Matrix, aes(x = n_genes))
> png(filename = "Pre-Metadata - n_genes - Total.png")
> Plot + geom_density(color = "black", fill = "gray")
> dev.off()
> png(filename = "Pre-Metadata - n_genes - Batch.png")
> Plot + geom_density(aes(color = batch))
> dev.off()
> 
> Plot <- ggplot(Total_Matrix, aes(x = percent_mito))
> png(filename = "Pre-Metadata - percent_mito - Total.png")
> Plot + geom_density(color = "black", fill = "gray")
> dev.off()
> png(filename = "Pre-Metadata - percent_mito - Batch.png")
> Plot + geom_density(aes(color = batch))
> dev.off()
> 
> 
> sink("Normal distribution for filtering.txt")
> print("object: Total n_genes")
>   ob = Total_Matrix$n_genes
>   qb <- quantile(ob, probs = c(.25, .75), na.rm = TRUE)
>   rb <- 1.5 * IQR(ob, na.rm = TRUE)
>   nb <- subset(ob, ob > (qb[1] - rb) & ob < (qb[2] + rb))
>   print("The min and max:")
>   print(c(min(nb),max(nb)))
>   print(' ')
>   figurename <- paste("n_genes", "Original", "Total.png", sep = " - ")
>   png(filename = figurename, height = 700, width = 200)
>   boxplot(ob)
>   dev.off()
>   figurename <- paste("n_genes", "Filtered", "Total.png", sep = " - ")
>   png(filename = figurename, height = 300, width = 200)
>   boxplot(nb)
>   dev.off()
> 
> 
> batch_name <- row.names(as.matrix(summary(Total_Matrix$batch)))
> for (i in 1:length(batch_name)){
>   print(c("object: n_genes", batch_name[i]))
>   ob = Total_Matrix$n_genes[Total_Matrix['batch']==batch_name[i]]
>   qb <- quantile(ob, probs = c(.25, .75), na.rm = TRUE)
>   rb <- 1.5 * IQR(ob, na.rm = TRUE)
>   nb <- subset(ob, ob > (qb[1] - rb) & ob < (qb[2] + rb))
>   print("The min and max:")
>   print(c(min(nb),max(nb)))
>   print(' ')
>   figurename <- paste("n_genes", "Original", batch_name[i], ".png", sep = " - ")
>   png(filename = figurename, height = 700, width = 200)
>   boxplot(ob)
>   dev.off()
>   figurename <- paste("n_genes", "Filtered", batch_name[i], ".png", sep = " - ")
>   png(filename = figurename, height = 300, width = 200)
>   boxplot(nb)
>   dev.off()
> }
> 
> print(' ')
> print("object: Total percent_mito")
>   ob = Total_Matrix$percent_mito
>   qb <- quantile(ob, probs = c(.25, .75), na.rm = TRUE)
>   rb <- 1.5 * IQR(ob, na.rm = TRUE)
>   nb <- subset(ob, ob > (qb[1] - rb) & ob < (qb[2] + rb))
>   print("The max:")
>   print(max(nb))
>   print(' ')
>   figurename <- paste("percent_mito", "Original", "Total.png", sep = " - ")
>   png(filename = figurename, height = 700, width = 200)
>   boxplot(ob)
>   dev.off()
>   figurename <- paste("percent_mito", "Filtered", "Total.png", sep = " - ")
>   png(filename = figurename, height = 300, width = 200)
>   boxplot(nb)
>   dev.off()
> 
> batch_name <- row.names(as.matrix(summary(Total_Matrix$batch)))
> for (i in 1:length(batch_name)){
>   print(c("object: percent_mito", batch_name[i]))
>   ob = Total_Matrix$percent_mito[Total_Matrix['batch']==batch_name[i]]
>   qb <- quantile(ob, probs = c(.25, .75), na.rm = TRUE)
>   rb <- 1.5 * IQR(ob, na.rm = TRUE)
>   nb <- subset(ob, ob > (qb[1] - rb) & ob < (qb[2] + rb))
>   print("The max:")
>   print(max(nb))
>   print(' ')
>   figurename <- paste("percent_mito", "Original", batch_name[i], ".png", sep = " - ")
>   png(filename = figurename, height = 700, width = 200)
>   boxplot(ob)
>   dev.off()
>   figurename <- paste("percent_mito", "Filtered", batch_name[i], ".png", sep = " - ")
>   png(filename = figurename, height = 300, width = 200)
>   boxplot(nb)
>   dev.off()
> }
> sink()
>
