### ISSUE TITLE
sc.pp.normalize_total() got an unexpected keyword argument 'exclude_highly_expressed'

### ISSUE THREAD

**Issue by algaebrown** [scverse/scanpy#871]
```
# normalize, by excluding frequent gene to avoid distorting data
    sc.pp.normalize_total(d, exclude_highly_expressed=True, max_fraction=0.05, inplace=True)
```

I was trying to normalize_total and exclude highly expressed genes. But:
I got
TypeError: normalize_total() got an unexpected keyword argument 'exclude_highly_expressed'

**Comment by fidelram** [comment]
Can you check that you are using a recent version of scanpy? Older versions of scanpy may not have this parameter.

**Comment by algaebrown** [comment]
I am using 1.4.3. I tried to upgrade to 1.4.4 but I was having a lot of problem with dependencies. Wonder it 1.4.3 is recent enough? Thank you so much.
scanpy                    1.4.3                      py_0    bioconda

**Comment by flying-sheep** [comment]
Well, 1.4.3 doesn’t have that parameter, as seen in the 1.4.3 version of that file: https://github.com/theislab/scanpy/blob/1.4.3/scanpy/preprocessing/_normalization.py#L118-L119

**Comment by flying-sheep** [comment]
What dependency problems do you have? If you installed everything through conda, you should just be able to update it with conda…
