### ISSUE TITLE
Remove batch effect ("Integrate" in Seurat")

### ISSUE THREAD

**Issue by grimwoo** [scverse/scanpy#873]
![image](https://user-images.githubusercontent.com/49429496/66832622-df295a80-ef8c-11e9-8a5c-98a02069f8ae.png)

Recently, I tried `combat`, `bbknn`, and `mnn` to remove the batch effect. However, no visible impact was found after these three command even I customized the parameters.
But when using the Seurat, the sample 001, 002，and 009 were grouped together (about 70% of those 3 samples were located together in UMAP) as them shared the same biological condition.

Could you help me?

**Comment by flying-sheep** [comment]
you need to tell us which data and which code you used so we can see if it’s a bug or if you made a mistake.

**Comment by grimwoo** [comment]
I used the following code once in a time . however , no visible different could be found in the result (`sc.pl.umap(adata, color='batch')`).

```
sc.pp.combat(adata)

sce.pp.bbknn(adata, batch_key='batch')

from itertools import cycle
sce.pp.mnn_correct(adata, var_index=None, var_subset=None, batch_key='batch', index_unique='-', batch_categories=None, k=20, sigma=1.0, cos_norm_in=True, cos_norm_out=True, svd_dim=None, var_adj=True, compute_angle=False, mnn_order=None, svd_mode='rsvd', do_concatenate=True, save_raw=False, n_jobs=None)
#OR
import mnnpy
mnnpy.mnn_correct(adata)

sce.pp.magic(adata)

sce.tl.phate(adata)
```

Here，I attach the Integrate result from seurat based on same data. we can that most of the sample 001, 002，and 009 were grouped together on left , most part of sample 003 was on the right. 
![20191016EVE_UMAP_Integrate](https://user-images.githubusercontent.com/49429496/66911577-5f11fc00-f043-11e9-8be2-742a4ffaa7a3.png)

or this way (split by batch)
![20191016EVE_UMAP_Integrate_SplitByPatient](https://user-images.githubusercontent.com/49429496/66911623-79e47080-f043-11e9-8d5d-7769437831da.png)

**Comment by LuckyMD** [comment]
Hey!

You used the data integration methods incorrectly as far as I can see. Please read the documentation for the functions first. `mnnpy.mnn_correct()` takes all the batches as separate anndata objects as positional argument. So you need to do:
`mnnpy.mnn_correct(adata_batch1, adata_batch2, adata_batch3,...)` to run it.

For `sc.pp.combat()` you didn't specify where your batch information was stored. And I'm surprised BBKNN didn't work for you. Did you run a `sc.pp.pca()` first?

**Comment by grimwoo** [comment]
@LuckyMD  Thanks for you suggestion. But I definitely used `sc.pp.pca()` first and then used `bbknn`. However, the UMAP of batch have no significant change.

And now I am running the `mnnpy.mnn_correct()` as you suggested. Unfortunately, this code cost 12 hours to show "step 2 of 3" (step 1 took more than 2 hours). I don't know if it's normal, because I re-did `sc.pp.pca()` and got the UMAP, the wholw program of which only cost 30 minutes (including regress out cell cycle).
![微信截图_20191018084700](https://user-images.githubusercontent.com/49429496/67068198-e7131580-f1ab-11e9-962f-ddf2ebebac2c.png)

**Comment by grimwoo** [comment]
And for `combat`, the description claims that "key: `str`, optional (default: `"batch"`)", hence I didn't put the "key". I used `sc.pp.combat(adata, key="batch")`, and the result seems the same as before.

**Comment by LuckyMD** [comment]
MNN does take fairly long. There is a faster version of it, which runs on PCA I think though, but it's not in scanpy external. Before you didn't integrated anything, as the function thought you just have 1 batch the way you ran it.

I would report your issue with bbknn on the BBKNN github repo directly. You may get better suggestions there.

**Comment by grimwoo** [comment]
@LuckyMD I think I may fail in all possible methods~~

![1111](https://user-images.githubusercontent.com/49429496/67175536-1f5b6380-f3f9-11e9-90db-897bd465c746.png)
![222](https://user-images.githubusercontent.com/49429496/67175551-2b472580-f3f9-11e9-823b-31f4f3dd4b4e.png)
![33333](https://user-images.githubusercontent.com/49429496/67175540-24b8ae00-f3f9-11e9-97e5-c90364a79946.png)

**Comment by LuckyMD** [comment]
You just saw in your output line [7], that you get back a tuple from `mnn_correct()`. This is also what it says in the error you get. Thus, `adata[0]` is your anndata object.

**Comment by flying-sheep** [comment]
I think this is a case for https://scanpy.discourse.group/ if there’s more problems. Also please respond to and close issues that are resolved for you.

**Comment by Zifeng-L** [comment]
> @LuckyMD我想我可能在所有可能的方法上都失败了~~
> 
> ![1111](https://user-images.githubusercontent.com/49429496/67175536-1f5b6380-f3f9-11e9-90db-897bd465c746.png)
> ![222](https://user-images.githubusercontent.com/49429496/67175551-2b472580-f3f9-11e9-823b-31f4f3dd4b4e.png)
> ![33333](https://user-images.githubusercontent.com/49429496/67175540-24b8ae00-f3f9-11e9-97e5-c90364a79946.png)

Have you finally solved the problem? I have the same problem as you. Can we discuss about it?

**Comment by LuckyMD** [comment]
@Zifeng1995 Please read the comment above:
> Thus, `adata[0]` is your anndata object.

you have do use `adata = adata[0]` to get your `AnnData` object from the `mnnpy` output.

**Comment by Zifeng-L** [comment]
> @Zifeng1995 Please read the comment above:
> 
> > Thus, `adata[0]` is your anndata object.
> 
> you have do use `adata = adata[0]` to get your `AnnData` object from the `mnnpy` output.

Thanks for your help! My problem was that no visible impact was found after `mnnpy` compared with `CCA` in seurat. I did `computeSumFactors`  and `sc.pp.log1p` to normalize the data before mnnpy. After that I did pca and `sc.pp.neighbors`, the result was not OK. So I want to find out if I did something wrong.
My codes are as follows

> adata.obs['size_factors'] = size_factors
> adata.X /= adata.obs['size_factors'].values[:,None]
> sc.pp.log1p(adata)

> sc.pp.highly_variable_genes(adata, min_mean=0.0125, max_mean=3, min_disp=0.5, batch_key = 'sample')
> var_select = adata.var.highly_variable_nbatches > 1
> var_genes = var_select.index[var_select]

> ## split per batch into new objects.
> batches = ['TB','G10', 'G11', 'G16','G17']
> alldata = {}
> for batch in batches:
alldata[batch] = adata3[adata3.obs['sample'] == batch,]


> cdata =sc.external.pp.mnn_correct(alldata['TB'], alldata['G10'], alldata['G11'], alldata['G16'], alldata['G17'], svd_dim = 50,batch_key = 'sample', batch_categories = ['TB','G10','G11','G16','G17'],save_raw = True, var_subset = var_genes)
> corr_data = cdata[0][:,var_genes]
> sc.tl.pca(corr_data, svd_solver = 'arpack', use_highly_variable = False)
> sc.pp.neighbors(corr_data, n_pcs = 50, n_neighbors = 20)
> sc.tl.umap(corr_data)

**Comment by LuckyMD** [comment]
This looks fine to me... I'm just not sure if you use `save_raw = True` what the output of the function is then. Check the function documentation `sc.external.pp.mnn_correct()`.

**Comment by Zifeng-L** [comment]
> This looks fine to me... I'm just not sure if you use `save_raw = True` what the output of the function is then. Check the function documentation `sc.external.pp.mnn_correct()`.

I checked the function documentation. It didn't affect the output.
![image](https://user-images.githubusercontent.com/53402047/80896889-b9478580-8d25-11ea-8080-8c5ee851d184.png)
Then I check the tutorial of mnnpy. It did scale after the mnn_correct. Did that affect the outcome? Thanks again for you kind help.
![image](https://user-images.githubusercontent.com/53402047/80896975-a5505380-8d26-11ea-9839-30cc408b7bcf.png)

**Comment by LuckyMD** [comment]
I'm afraid I can't really answer detailed questions on the functionality of `mnnpy` as I didn't write it. Maybe these questions would be best asked to the authors of the method?

Why do you say it didn't work? Do you have an example output?
