### ISSUE TITLE
running scanpy.tl.tsne crashes my kernel

### ISSUE THREAD

**Issue by sophiamaedler** [scverse/scanpy#874]
This issue just came up recently when I tried re-running an older notebook of mine. Whenever I try and run my code in Jupyter notebook and execute any cell that uses scanpy.tl.tsne my kernel crashes. When I try and execute the same code from the terminal I get 
`Segmentation fault: 11`. 

This is the code I used to reproducibly get the error:
```
import scanpy as sc
adata = sc.datasets.pbmc3k()
sc.pp.pca(adata)
sc.pp.neighbors(adata)
sc.tl.tsne(adata)
```

<img width="629" alt="Screenshot 2019-10-16 at 14 39 09" src="https://user-images.githubusercontent.com/15019107/66920007-c2d7fd00-f022-11e9-93d6-560305d1cc50.png">

Any ideas what the issue could be and how I can fix this? The function used to work fine for me.

I am running scanpy in the following version:
`scanpy==1.4.4.post1 anndata==0.6.22.post1 umap==0.3.9 numpy==1.16.4 scipy==1.3.0 pandas==0.24.2 scikit-learn==0.21.2 statsmodels==0.10.0 python-igraph==0.7.1 louvain==0.6.1`

**Comment by flying-sheep** [comment]
Hi, how did you install everything? With conda or pip? Does reinstalling MulticoreTSNE and/or scikit-learn help?

This is most certainly not scanpy’s problem, we don’t have any compiled code.
