### ISSUE TITLE
sc.pl.tsne legend.loc = 'on_data'

### ISSUE THREAD

**Issue by LuckyMD** [scverse/scanpy#88]
I can't seem to plot the labels in the margin or on the data when plotting a t-SNE with louvain_groups labels. I am loosely following the scanpy seurat tutorial code with my own data at:
https://github.com/theislab/scanpy_usage/blob/master/170505_seurat/seurat.ipynb

When running:

`sc.pl.tsne(adata_bc, size=28, color='louvain_groups', legend_loc='on_data', legend_fontsize=12, legend_fontweight='bold')`

I get the error:

> anaconda3/lib/python3.6/site-packages/matplotlib/legend.py:326: UserWarning: Unrecognized location "on_data". Falling back on "best"; valid locations are
> 	best
> 	upper right
> 	upper left
> 	lower left
> 	lower right
> 	right
> 	center left
> 	center right
> 	lower center
> 	upper center
> 	center
> 
>   six.iterkeys(self.codes))))

putting the legend on the data or in the margin does not seem possible. I am using matplotlib version 2.0.0.

**Comment by LuckyMD** [comment]
Never mind... I just can't seem to read the difference between 'on_data' and 'on data'. The error didn't really help I guess.

**Comment by falexwolf** [comment]
:smile: Now this raises a proper error message: https://github.com/theislab/scanpy/commit/2490bec27c1c37e1388cb1da44369c81e176df6c

**Comment by LuckyMD** [comment]
Thanks... still feel like an idiot though ;)

**Comment by falexwolf** [comment]
No, the matplotlib error message was really confusing... the 'on data' and 'right margin' locations are scanpy features and should be in the error message... wanted to do this anyways. :wink:
