### ISSUE TITLE
Cannot subset 2 louvain from adata

### ISSUE THREAD

**Issue by grimwoo** [scverse/scanpy#885]
adata has many louvains. I want to subset other louvain rather than louvain 30 and 32.

hence i write 
```
adata1 = adata[adata.obs['louvain'] != '30', :]
adata2 = adata1[adata1.obs['louvain'] != '32', :]
#or
adata1 = adata[adata.obs['louvain'] != '32', :]
adata2 = adata1[adata1.obs['louvain'] != '30', :]
```
however , i got the result `IndexError: Item wrong length 36630 instead of 36708.`

and then i write
```
adata1 = adata[adata.obs['louvain'] not in ['30','32'], :]
#or
adata1 = adata[adata.obs['louvain'] != '30' or adata.obs['louvain'] != '32' , :]
```
i got `ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().`

and 
```
adata_temp = adata[adata.obs['louvain'] != '32', adata.obs['louvain'] != '30', :]
```
results in `ValueError: AnnData can only be sliced in rows and columns.`
 
could anyone help me ?

**Comment by flying-sheep** [comment]
please ask questions like this in https://scanpy.discourse.group/ or stackoverflow.

answer: `in`, `not in`, `and`, `or` are operations that can only return a single boolean. You want the “bitwise or” operator instead of `or` and `ndarray.in1d` instead of `in`.
