### ISSUE TITLE
'SparseDataset'  has no method mean 

### ISSUE THREAD

**Issue by M0hammadL** [scverse/scanpy#89]
https://github.com/theislab/scanpy/blob/0caaa9d2e684e2aa76acdf6672d71d7ac38b33cf/scanpy/preprocessing/simple.py#L822
it is not possible to calculate mean for  'SparseDataset' because it is not implemented.

**Comment by dawe** [comment]
Which version of numpy and scipy are you running?

**Comment by falexwolf** [comment]
Thanks Mohammad, we will resolve this! @dawe It's not related to numpy or scipy, as it only occurs when running AnnData in `backed` mode for out-of-memory computing; this becomes necessary only for >100K cells.

**Comment by falexwolf** [comment]
That's kind of a longer-term project and will not be directly solved by adding a method "mean" to SparseDataset... I'll close this for now.
