### ISSUE TITLE
Reorder Stacked_Violin Subplots

### ISSUE THREAD

**Issue by MediciPrime** [scverse/scanpy#890]
Hello @fidelram,

This is not an issue but I would really like some help with using the 'order' parameter in the stacked_violin plot function.  If I have cell type as the y-axis and the genes in the x-axis, how would I rearrange the order to the cell types in the y-axis.  

Providing the 'order' parameter with a list of cell types being used by the function doesn't seem to be working.  I am just really confused how else to interpret these instructions for the stacked_violin function:  order : list of str, optional (default: True)  

Thank you,
Behram

**Comment by fidelram** [comment]
I just tried and worked for me:

Default order:
![image](https://user-images.githubusercontent.com/4964309/67553457-7d47be00-f70d-11e9-9381-b323cc25a739.png)

Order changed: 
![image](https://user-images.githubusercontent.com/4964309/67553505-a0726d80-f70d-11e9-8a35-fe3ded5780ea.png)

If this is not working for you, please check that the old order and the new order has the same elements as this may be the problem.

FYI: The order of the cell type is given by the categorical order in `adata.obs['<column name>'] `. Thus, another way to change the order is to change the pandas categorical order was you want it. 

See this link on how to do it: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.CategoricalIndex.reorder_categories.html

**Comment by MediciPrime** [comment]
Thank you @fidelram!  I guess for me it wasn't working because I wasn't using the 'swap_axes=True' command so maybe the function didn't know what I wanted it to reorder.  However after using 'swap_axes' it started working.  Now I still wanted the cell types to be along the y-axis so I tried your second suggestion for reordering the pandas categorical order like so:

`g0_g1_ctrl_ifn.obs['cluster_id'].cat.reorder_categories(['Glomerular Epithelial Cells', 'Early GEC', 'Proximal and Distal Tubule',
                                                         'Endothelial Cells', 'Cycling Cells', 'Mesenchyme', 'Neuron'], inplace=True)`

And it worked!  Thank you again for your very helpful suggestions!

- Behram

**Comment by fidelram** [comment]
@MediciPrime I am also updating the underlying plotting code to fix the problem with `swap_axes=True`. After this is merged to master, you would not need to do the reordering of the categories.

**Comment by MediciPrime** [comment]
That's awesome thank you for fixing it so quickly @fidelram!
