### ISSUE TITLE
Plotting order in embedding plots with groups parameter 

### ISSUE THREAD

**Issue by gokceneraslan** [scverse/scanpy#891]
When we use the `groups` parameter of `sc.pl.umap` (and other embedding plots), plotting order of groups is random. This means that gray background group can be plotted over the groups of interest and obscure dots of other colors.

Here the top 2 plots are plotted with `groups=` and bottom ones are plotted manually via calling sc.pl.umap twice with subsetted anndata (e.g. adata[adata.obs.x != 'y'] and adata[adata.obs.x == 'y']):

![image](https://user-images.githubusercontent.com/1140359/67532602-da535d80-f694-11e9-9ed2-3d544013ff78.png)

**Comment by LuckyMD** [comment]
Wasn’t there recently a PR to introduce ordered categoricals? Or does that only affect legend order and not order of plotting?

**Comment by fidelram** [comment]
@LuckyMD The ordered categoricals with not solve the problem. The issue is with the order of the dots.  I will take a look.

**Comment by LuckyMD** [comment]
I see. Would it be a solution to link the order of plotting to the order of categories when categoricals are ordered?

**Comment by fidelram** [comment]
The solution that I proposed is that if 'groups' is set, then the dots corresponding to the selected groups are put on top. But also, sorting the cells according to the categories order should work.

**Comment by elo073** [comment]
On similar issue: is there a way to plot the cells in random order? So that no specific group would be on top, but randomly mixed.

**Comment by ivirshup** [comment]
You can pass `sort_order=False`, but then it should just be the order in AnnData object.

**Comment by elo073** [comment]
Thank you, that could be helpful. Then I'd have to shuffle the order of the cells in the AnnData object first. Is there any easy way to do this?

**Comment by ivirshup** [comment]
I can think of a couple ways:

```python
view = adata[np.random.choice(adata.n_obs, adata.n_obs, replace=False)]

new = sc.pp.subsample(adata, fraction=1., copy=True)
```

**Comment by elo073** [comment]
Thank you! This works
```
new = sc.pp.subsample(adata, fraction=1., copy=True)
sc.pl.umap(new, color=['scsn'], legend_loc='on data',  size=10, sort_order=False, legend_fontsize=15)
```

**Comment by leezx** [comment]
We can sort the adata itself. Like:
```adata = adata[adata.obs.group.sort_values().index,:]```
This can manually change the order of groups in a graph.
