### ISSUE TITLE
AttributeError: module 'scanpy.api.logging' has no attribute 'msg'

### ISSUE THREAD

**Issue by JuHey** [scverse/scanpy#895]
This error appears when using DESC autoencoder (github: eleozzr/desc) under scanpy 1.4.4. This was not an issue with earlier versions of scanpy. Is there a work-around available?

**Comment by flying-sheep** [comment]
As in most Python projects, functions that aren’t in the docs are considered private and not for use from different packages. This is therefore a bug in `desc`: eleozzr/desc#13

As a workaround, you can of course assign the function: `scanpy.api.logging.msg = lambda ...: ...`

**Comment by JuHey** [comment]
Got it. Thank you for offering a workaround!
