### ISSUE TITLE
cannot import scanpy in windows system

### ISSUE THREAD

**Issue by blueoceandata** [scverse/scanpy#900]
ImportError                               Traceback (most recent call last)
<ipython-input-1-b6c916879140> in <module>()
      1 import numpy as np
      2 import pandas as pd
----> 3 import scanpy as sc

~\Anaconda3-6\lib\site-packages\scanpy\__init__.py in <module>()
      1 # some technical stuff
      2 import sys
----> 3 from .utils import check_versions, annotate_doc_types
      4 from ._version import get_versions  # version generated by versioneer
      5 

~\Anaconda3-6\lib\site-packages\scanpy\utils.py in <module>()
     17 from pandas.api.types import CategoricalDtype
     18 
---> 19 from ._settings import settings
     20 from . import logging as logg
     21 import warnings

~\Anaconda3-6\lib\site-packages\scanpy\_settings.py in <module>()
      7 from typing import Tuple, Union, Any, List, Iterable, TextIO, Optional
      8 
----> 9 from . import logging
     10 from .logging import _set_log_level, _set_log_file, RootLogger
     11 

~\Anaconda3-6\lib\site-packages\scanpy\logging.py in <module>()
      7 from typing import Optional
      8 
----> 9 import anndata.logging
     10 
     11 

~\Anaconda3-6\lib\site-packages\anndata\__init__.py in <module>()
----> 1 from .core.anndata import AnnData, Raw
      2 from .readwrite import (
      3     read_h5ad, read_loom, read_hdf,
      4     read_excel, read_umi_tools,
      5     read_csv, read_text, read_mtx,

~\Anaconda3-6\lib\site-packages\anndata\core\anndata.py in <module>()
     46     LayersBase, Layers
     47 )
---> 48 from .. import h5py
     49 from .views import ArrayView, SparseCSRView, SparseCSCView, DictView, DataFrameView
     50 

~\Anaconda3-6\lib\site-packages\anndata\h5py\__init__.py in <module>()
     22    SparseDataset
     23 """
---> 24 from .h5sparse import File, Group, SparseDataset, _load_h5_dataset_as_sparse
     25 from h5py import Dataset, special_dtype
     26 

~\Anaconda3-6\lib\site-packages\anndata\h5py\h5sparse.py in <module>()
      4 from typing import Optional, Union, KeysView, NamedTuple
      5 
----> 6 import h5py
      7 import numpy as np
      8 import scipy.sparse as ss

~\Anaconda3-6\lib\site-packages\h5py\__init__.py in <module>()
     34 _errors.silence_errors()
     35 
---> 36 from ._conv import register_converters as _register_converters
     37 _register_converters()
     38 

h5py\h5r.pxd in init h5py._conv()

h5py\_objects.pxd in init h5py.h5r()

h5py\_objects.pyx in init h5py._objects()

ImportError: DLL load failed: The specified procedure could not be found.

**Comment by Koncopd** [comment]
This seems to be a problem related to h5py build.
You can install h5py from the wheel [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#h5py) or use conda package manager.
