### ISSUE TITLE
dimheatmap equlvalence

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/scanpy#904]
Dear,
Seurat's dimheatmap() draws a heatmap focusing on a principal component, while scanpy's sc.pl.heatmap focusing on the gene expression matrix. Could you develop a similar function ? I find it's very easy to draw a nice heamap with dimheatmap(), while it is hard in scany as the expression noise.
here is the link of dimheatmap:
https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html

And, here is the comparison ( dimheatmap):
![image](https://user-images.githubusercontent.com/29703450/68374317-a3df0d80-017f-11ea-8a7b-5a16204c5cd3.png)

here is heatmap genereated by scanpy (https://scanpy-tutorials.readthedocs.io/en/latest/visualizing-marker-genes.html)
![image](https://user-images.githubusercontent.com/29703450/68374417-dab52380-017f-11ea-9775-79a9a443bdd5.png)

Obviously, it's more nice with Seurat's dimheatmap().

**Comment by wangjiawen2013** [comment]
@flying-sheep @fidelram 
please neglect this issue. There is a related issue here:
https://scanpy.discourse.group/t/rank-cell-order-change-by-provided-gene-dictionary/56

**Comment by eroell** [comment]
Just came across this, thanks for letting us know - hope you obtained the desired behaviour in the end :)
