### ISSUE TITLE
Access UMAP Coordinates through API?

### ISSUE THREAD

**Issue by mfansler** [scverse/scanpy#911]
Are the UMAP coordinates stored anywhere in the object? I couldn't find it, so I ended up running `umap` with the `show=False` and then manually extracting it from the matplotlib Axes object.

If such functionality doesn't exist, then I suppose you can consider this a feature request.

**Comment by flying-sheep** [comment]
See **Returns** section of the [`sc.tl.umap`](https://scanpy.readthedocs.io/en/stable/api/scanpy.tl.umap.html)’s docs.
