### ISSUE TITLE
Gene Names/Identities are showing up as numbers when plotted with highest_expr_genes()

### ISSUE THREAD

**Issue by ArcusGears** [scverse/scanpy#914]
When processing the data in Scanpy I am unable to figure out why my plot of the Highest Expressed Genes shows up with numbers rather than gene names as the identifiers on the Y-axis.  
Example:
<img width="786" alt="Screen Shot 2019-11-12 at 5 16 15 PM" src="https://user-images.githubusercontent.com/9083834/68719284-411bb680-0571-11ea-8666-ce427fce74df.png">

I am worried that it may not be reading our file properly, but even when I converted from a txt file to a .loom file I still got the same problem.  I am unsure if this is an issue with our original input or if something it is being read improperly.  I will include some of my code below, and if there is somewhere you would like me to send copies of raw data to run it on let me know where to send it.

I am using the tutorial for Clustering on the Scanpy website as the basis for my code.  

```py
sc.settings.set_figure_params(dpi = 80)

day00a = sc.read_text("/alex_ryan/D0.1500.dge", first_column_names = True, delimiter = "\t")
day01 = sc.read_text("/alex_ryan/D1.txt.500.dge", first_column_names = True, delimiter = "\t")
day02 = sc.read_text("/alex_ryan/D2.txt.500.dge", first_column_names = True, delimiter = "\t")
day04 = sc.read_text("/alex_ryan/D4.txt.500.dge", first_column_names = True, delimiter = "\t")
day09 = sc.read_text("/alex_ryan/D9.txt.500.dge", first_column_names = True, delimiter = "\t")
day11 = sc.read_text("/alex_ryan/D11.txt.500.dge", first_column_names = True, delimiter = "\t")

day00a.obs['tech'] = 'Day 0'
day01.obs['tech'] = 'Day 1'
day02.obs['tech'] = 'Day 2'
day04.obs['tech'] = 'Day 4'
day09.obs['tech'] = 'Day 9'
day11.obs['tech'] = 'Day 11'

adata_list = [day01, day02, day04, day09, day11]
adata2 = day00a.concatenate(adata_list, join = 'outer')
adata = adata2

sc.pl.highest_expr_genes(adata, n_top = 20, save = True)
```

I am adding the extra .obs 'tech' tag so that I can identify the cells by day after they have been combined into one anndata object.  I don't think this is causing the issue, but if that is part of it, then please let me know if there is a work around.

**Comment by ivirshup** [comment]
Do you have the gene names you'd like to use in `adata.var_names`?

**Comment by ArcusGears** [comment]
The `adata.var_names` that I have are the unique barcodes that the DropSeq gives each cell.  I originally assumed that was right, should I have the gene names under there instead?  Even so that doesn't explain why I would get numbers as the barcodes are nucleotide and read as such.  

```
>>> adata.var_names
Index(['GTGCCATATTCN', 'TCGCAGCCTGCT', 'CTGTAGCCCCCA', 'TGTATGTTGCTT',
       'CAGTATCTCATN', 'AATCTATCACAN', 'CTCCCTTTTGCN', 'TTTGACACCGCC',
       'CGCGCCTTGTCA', 'AACCTTTGATGG',
       ...
       'GTGATTCATATC', 'GCCGTCGTCACG', 'AGGAGGGTTACT', 'AGAACGATTAAT',
       'ACGACTATCGTC', 'TGCCAGCCTGAA', 'TTAAACTCGGCT', 'GCAGACACCGGT',
       'GGGGCTCTTGGG', 'GCGACGACCTTG'],
      dtype='object', length=3971)
```

**Comment by ArcusGears** [comment]
I was able to fix the problem by reading in the files as .loom files (after converting them from text to loom in loompy)

```
day00a = sc.read_loom('/alex_ryan/scanpy/Day0.loom')
day01 = sc.read_loom('/alex_ryan/scanpy/Day01.loom')
day02 = sc.read_loom('/alex_ryan/scanpy/Day02.loom')
day04 = sc.read_loom('/alex_ryan/scanpy/Day04.loom')
day09 = sc.read_loom('/alex_ryan/scanpy/Day09.loom')
day11 = sc.read_loom('/alex_ryan/scanpy/Day11.loom')
```

**Comment by ivirshup** [comment]
So, in general `var_names` should be the gene ids and `obs_names` should be the cell ids. I'm interested in how you could have gone from any sort of string label to integers before. If you wouldn't mind, could you run this modified version of your previous example and showing the output?

```python
sc.settings.set_figure_params(dpi = 80)

day00a = sc.read_text("/alex_ryan/D0.1500.dge", first_column_names = True, delimiter = "\t")
day01 = sc.read_text("/alex_ryan/D1.txt.500.dge", first_column_names = True, delimiter = "\t")
day02 = sc.read_text("/alex_ryan/D2.txt.500.dge", first_column_names = True, delimiter = "\t")
day04 = sc.read_text("/alex_ryan/D4.txt.500.dge", first_column_names = True, delimiter = "\t")
day09 = sc.read_text("/alex_ryan/D9.txt.500.dge", first_column_names = True, delimiter = "\t")
day11 = sc.read_text("/alex_ryan/D11.txt.500.dge", first_column_names = True, delimiter = "\t")

day00a.obs['tech'] = 'Day 0'
day01.obs['tech'] = 'Day 1'
day02.obs['tech'] = 'Day 2'
day04.obs['tech'] = 'Day 4'
day09.obs['tech'] = 'Day 9'
day11.obs['tech'] = 'Day 11'

adata_list = [day01, day02, day04, day09, day11]

print(day00a.var_names)
print(all((adata00a.var_names == day_x.var_names).all() for day_x in adata_list))

adata2 = day00a.concatenate(adata_list, join = 'outer')
adata = adata2

print(adata.var_names, adata)

sc.pl.highest_expr_genes(adata, n_top = 20, save = True)
```

Thanks!

**Comment by ArcusGears** [comment]
@ivirshup 

I ran the code as you requested, the following output is what I got for the print calls

```
>>> print(day00a.var_names)
Index(['GTGCCATATTCN', 'TCGCAGCCTGCT', 'CTGTAGCCCCCA', 'TGTATGTTGCTT',
       'CAGTATCTCATN', 'AATCTATCACAN', 'CTCCCTTTTGCN', 'TTTGACACCGCC',
       'CGCGCCTTGTCA', 'AACCTTTGATGG',
       ...
       'TATCTGTAATCA', 'ATGGGTGAACAG', 'TCCGATAGTGGA', 'TTGTCAATCTCT',
       'CGGTGGCTGAGT', 'TCCATATCAGGG', 'TGGCGTTAGTAT', 'TTCTTCTGGTTT',
       'ACTATGGCTGGT', 'CGTGAACCCTGT'],
      dtype='object', length=1500)
>>> print(all((adata00a.var_names == day_x.var_names).all() for day_x in adata_list))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <genexpr>
NameError: name 'adata00a' is not defined
>>> print(adata.var_names, adata)
Index(['GTGCCATATTCN', 'TCGCAGCCTGCT', 'CTGTAGCCCCCA', 'TGTATGTTGCTT',
       'CAGTATCTCATN', 'AATCTATCACAN', 'CTCCCTTTTGCN', 'TTTGACACCGCC',
       'CGCGCCTTGTCA', 'AACCTTTGATGG',
       ...
       'GCCCAGGTGCCA', 'GACGAAACCATG', 'CCCGCCCAAGTT', 'GTGCGTTAAGTG',
       'TCCTACCTGTAC', 'CACACTGATGAT', 'CAGCATACTCCN', 'AGAAACCTTGGG',
       'GACATAAATCAG', 'AGGGGTGACGAC'],
      dtype='object', length=3971) AnnData object with n_obs × n_vars = 119446 × 3971 
    obs: 'batch', 'tech'
```
The `adata00a` threw some errors as it hadn't been defined yet, and I wan't totally sure what you were trying to reference there, but I tried with both just `adata` and `day00a` and it still threw errors (not defined and ValueError respectively)

Assuming that you just wanted the var_names for each day I just ran them separately and also got the cell barcodes:

```
>>> print(day01.var_names)
Index(['CCGTCATCTTCT', 'GATTCGATTTCC', 'TTTTGGCCGTTA', 'TGAGTTTTTATN',
       'CCGTCTCTACTN', 'ATAAGTTGCTTG', 'CCGTCGCAAGGT', 'ACACCTTGGAAA',
       'AGCCCGCCCAGN', 'GAAAATCGATCN',
       ...
       'AACCCGCCCAGN', 'CCCATCGACTGA', 'GCGGAAGGCGCT', 'TACTTGGTTTGC',
       'GTCTTGGTTACC', 'CTCGCGGCCGTT', 'CCCAAATTTCGT', 'CCGGAGGTTTAG',
       'CTAAACGGCTGT', 'GAAATGAGGATG'],
      dtype='object', length=500)
>>> print(day02.var_names)
Index(['AACCATCAGCGG', 'GTCCCACTACAT', 'CCCTTTCCGAGN', 'AGGGCACTTTGG',
       'CCTGAGAAGCGT', 'GGGGCTGTTGGG', 'ACTGACTTACCC', 'CAAGACTACTAT',
       'GCATTATGTCCC', 'TTCGGTGTCATG',
       ...
       'AGCAGCGTTATA', 'ATAGTGGGCGAG', 'TTTCCCCCCGTC', 'TTCGGTCTCATG',
       'CTGCATCTGCTG', 'GGGACTAATAGC', 'AAACATATTGAA', 'AAGGCCTAACTG',
       'CGACAACGTCCA', 'ATCCTGACTGAC'],
      dtype='object', length=500)
>>> print(day04.var_names)
Index(['ACGCAAGTACAA', 'TCTCCCACACAG', 'TCGGAATGCGCC', 'CTTGGCCAACTT',
       'ACTTTTAATTCC', 'CGACCGATCCCC', 'GCCTGAGACGAN', 'CACCCCGGTCAG',
       'AACTGGCTTGAN', 'TCGTATAACTAN',
       ...
       'CAACTTCCTATT', 'AAAGTAGTCCGC', 'TTGTGACGAGAA', 'GCCATGACCTGC',
       'GCCGAAATCTCC', 'GGTGCCACTCTT', 'CTAGTCTCAGCC', 'CACACCATGCAC',
       'CCCACTTCTCCT', 'AATTAGATCTCA'],
      dtype='object', length=500)
>>> print(day09.var_names)
Index(['ATCCCGCCGCGA', 'CTGGCATCCTCN', 'CATACAAATGTG', 'AATACCAGTATC',
       'TGGAACTATCGC', 'TTGGAGGATAGN', 'CGCCTCCCTTAN', 'TCAATCCTGCGN',
       'ACGAGATAATTC', 'ATTATGCAACGN',
       ...
       'CAGGGCTTCTGG', 'ATCTTTTACTTC', 'TACATCCGACAA', 'CGCTACTTAGTA',
       'TGGAGGATAGTG', 'TCACCCTATGCG', 'CTTGTGGGCATT', 'GCCTCTACTAAG',
       'TGGAGGATAGGG', 'AATCCGCCATCC'],
      dtype='object', length=494)
>>> print(day11.var_names)
Index(['GTGAAATACGTN', 'TCAATTGACCTN', 'ACAACCATAACT', 'TTTCAGCTGTAG',
       'CTCTGAATGAAA', 'AGCCAAGTTTCT', 'ATGACTTACGGN', 'CACGCGTGCGGN',
       'CCACCCTTCCAT', 'CGGCTCTTTCCN',
       ...
       'CCCGATCTCCAT', 'CATAGAATTGAC', 'CCCGCTCATTGG', 'ATCGATCGGAAT',
       'GGGGATGCTATC', 'TCAATCGCCCCA', 'GTCGACAATCAA', 'ATTCATCGACCC',
       'GAGGTGTCTCAT', 'GGGTATGCTATA'],
      dtype='object', length=500)
```



As for the graph it produced:
<img width="979" alt="Screen Shot 2019-11-14 at 11 07 07 AM" src="https://user-images.githubusercontent.com/9083834/68879435-03cd3b00-06cf-11ea-903e-c59f7da461b8.png">

**Comment by ivirshup** [comment]
Thanks for that. I did mean `adata00a`, whoops! I'm expecting the `ValueError` was due to the `.var_names` having different shapes?

I think the main issue here is that `AnnData.concatenate` expects the variables (`.var_names`) to be shared, and appends the objects along the observation axis. If your data is read in with observations in the `var` axis, you can use `AnnData.transpose` to fix that.

It looks like something different is happening in the snippet I sent than the one you posted before. I'm pretty sure I didn't modify any variables when I added the print statements to your snippet. Any idea why the results would be different?

**Comment by mosquitoCat** [comment]
Hi ivirshup,

I've recently run into a similar situation where the gene names appear to be numbers in the plot. I've checked the var_names and they are fine. I might be wrong here but my feeling is that the plot function picked up the index number of the gene rather than the gene name itself. I'm not very familiar with AnnData but I think a match and swap will do the job. Could you give me some advice on how to proceed please?

Many thanks,
Cass

**Comment by LuckyMD** [comment]
We've been having a similar issue in `scIB` recently @ivirshup. Were there some changes to the way pandas indexing works? We had to change some `.idxmin()` and `.argmin()` lines to make things work for ppl.

**Comment by mosquitoCat** [comment]
@ivirshup @LuckyMD 
I fixed the problem - the issue was in the original h5ad file converted from a Seurat object using SeuratDisk::Convert(). It seems the var data wasn't ported over properly for the assay I was using. I rebuilt the h5ad file using reticulate instead and that solved the problem.

**Comment by HKL-97** [comment]
> @ivirshup @LuckyMD
> I fixed the problem - the issue was in the original h5ad file converted from a Seurat object using SeuratDisk::Convert(). It seems the var data wasn't ported over properly for the assay I was using. I rebuilt the h5ad file using reticulate instead and that solved the problem.

I have encountered the same issue as @mosquitoCat .
Although adata.var_names still returns correct gene symbols, all my name IDs become numbers:
for example, sc.pl.umap(adata,color='GeneName') will return errors. but sc.pl.umap(adata,color='123') can be recognized.
 SeuratDisk::Convert() seems to cause some trouble here. Is there a way to fix it? @ivirshup

**Comment by Imevernoteva** [comment]
> @ivirshup @LuckyMD I fixed the problem - the issue was in the original h5ad file converted from a Seurat object using SeuratDisk::Convert(). It seems the var data wasn't ported over properly for the assay I was using. I rebuilt the h5ad file using reticulate instead and that solved the problem.

Hi, 

Would you mind sharing how you did this? Thanks

**Comment by mosquitoCat** [comment]
@Imevernoteva I had the issue 3 years ago and have checked that conversion from Seurat object to h5ad works well with the latest SeuratDisk package, with var data ported correctly.

**Comment by Imevernoteva** [comment]
> @Imevernoteva I had the issue 3 years ago and have checked that conversion from Seurat object to h5ad works well with the latest SeuratDisk package, with var data ported correctly.

Thanks for the info. I find that it works well with scRNA-seq data, but causes issues with Spatial (Visium) data. Would appreciate any tips! Cheers
