### ISSUE TITLE
When using umap with init_pos=paga, got strange result

### ISSUE THREAD

**Issue by dhtc** [scverse/scanpy#918]
When i use umap with the parameter init_pos='paga', I got a strange result.
![image](https://user-images.githubusercontent.com/20806068/68834273-5703b580-06f0-11ea-9d05-76a66ea9e943.png)

```python
sc.pl.umap(adata,color='louvain')
```

```pytb
no error
```

#### Versions:

> scanpy==1.4.4 anndata==0.6.22.post1 umap==0.3.9 numpy==1.17.3 scipy==1.3.1 pandas==0.25.0 scikit-learn==0.21.2 statsmodels==0.10.1 python-igraph==0.7.1 louvain==0.6.1

**Comment by ivirshup** [comment]
Could you provide some more details? It'd be useful to see a script that can reproduce this behavior from scratch. There are some guides on how to write this up in the [contributing section](https://github.com/theislab/scanpy/blob/master/CONTRIBUTING.md#before-filing-an-issue). Thanks!

**Comment by flying-sheep** [comment]
Yeah, you deleted the issue template that prompts you to do this. In the future we might just close issues when people do that, it’s rude.

**Comment by dhtc** [comment]
> Yeah, you deleted the issue template that prompts you to do this. In the future we might just close issues when people do that, it’s rude.

Sorry for deleting the issue template.
Here are details:
I just followed the example of PAGA for hematopoiesis in mouse (Paul et al., 2015) to cope with my data.I want to recomputing the umap embedding using PAGA-initialization.
![image](https://user-images.githubusercontent.com/20806068/69139814-41c9c500-0afc-11ea-9991-e21638db61c3.png)
![image](https://user-images.githubusercontent.com/20806068/69139884-64f47480-0afc-11ea-98dd-9e7430e94cfd.png)
I got strange umap embedding even though i have tried several different  parameters.
Thanks!

**Comment by flying-sheep** [comment]
Please post some code that will create `sp` in a way that reproduces the umap, as Markdown syntax highlighted code block as in the template, not as an image. Like:

```py
import scanpy as sc
sp = sc.read('sp.loom', backup_url='https://datastore.org/sp.loom')
sc.pp.XXX(sp)
...
sc.pl.paga(sp, ...)
```

**Comment by ivirshup** [comment]
@dhtc was that the same data as the previous plot?

Also, I have a suspicion about what's happening. Could you try calling `sc.tl.umap(sp, init_pos="paga")` instead of passing an array?

**Comment by dhtc** [comment]
@flying-sheep 
Because the paper have not been published, so i can't offer the data to reproduce this problem.
Here are the codes:
```python
import scanpy as sc
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import anndata
import matplotlib as mpl
import scipy
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

###settings###
sc.settings.verbosity = 1
sc.logging.print_versions()
results_file = './write/sp.h5ad'
sc.settings.set_figure_params(dpi=150)

sp=sc.read('sp_velo.loom')
sc.pp.normalize_total(sp,target_sum=1e6,key_added='norm_factor')
sc.pp.log1p(sp)
sp.raw=sp
sc.pp.highly_variable_genes(sp, n_top_genes=2000)
sc.pl.highly_variable_genes(sp)
sp = sp[:, sp.var['highly_variable']]
sc.pp.combat(sp,key='batch',covariates=['sample'])
sc.pp.scale(sp, max_value=10)
sc.tl.pca(sp, svd_solver='arpack')
sc.pl.pca_variance_ratio(sp, log=True)
sc.pp.neighbors(sp, n_neighbors=10, n_pcs=30)
sc.tl.diffmap(sp)
sc.pp.neighbors(sp, n_neighbors=20, use_rep='X_diffmap')
sc.tl.louvain(sp,resolution=1)
sc.tl.paga(sp)
_, axs = plt.subplots(ncols=1, figsize=(24, 10), gridspec_kw={'wspace': 0.05, 'left': 0.12})
sc.pl.paga(sp,color='louvain',layout='fa',pos=pos_coord,threshold=0.2,ax=axs)
from scanpy.tools._utils import get_init_pos_from_paga as init
sc.tl.umap(sp,init_pos=init(sp))
sc.pl.umap(sp,color='louvain')
```
Thanks!

**Comment by dhtc** [comment]
@ivirshup 
Yeah, it was the same data as the privious plot. I tried calling sc.tl.umap(sp, init_pos="paga") but meet an error. I just use the get_init_pos_from_paga function to solve this error as mention in #769 .Thanks!
```
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of type(CPUDispatcher(<function rdist at 0x7f90e19f58c8>)) with parameters (array(float64, 1d, C), array(float64, 1d, C))
Known signatures:
 * (array(float32, 1d, A), array(float32, 1d, A)) -> float32
 * parameterized
[1] During: resolving callee type: type(CPUDispatcher(<function rdist at 0x7f90e19f58c8>))
[2] During: typing of call at /datc/dh_data/.conda_env/scrna/lib/python3.6/site-packages/umap/umap_.py (797)


File "../../../../.conda_env/scrna/lib/python3.6/site-packages/umap/umap_.py", line 797:
def optimize_layout(
    <source elided>

                dist_squared = rdist(current, other)
                ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new

**Comment by ivirshup** [comment]
Thanks for posting that code, it's very helpful for figuring this stuff out.

I tried running that code on one of our example datasets, and wasn't able to reproduce your results (however, one of the variables `pos_coord` wasn't defined):

```python
import scanpy as sc
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import anndata
import matplotlib as mpl
import scipy

sc.logging.print_versions()
# scanpy==1.4.4.post1 anndata==0.6.22.post1 umap==0.3.10 numpy==1.17.3 scipy==1.3.1 
# pandas==0.25.3 scikit-learn==0.21.3 statsmodels==0.10.1 python-igraph==0.7.1 louvain==0.6.1

sp = sc.datasets.pbmc3k()
sc.pp.normalize_total(sp,target_sum=1e6,key_added='norm_factor')
sc.pp.log1p(sp)
sp.raw=sp
sc.pp.highly_variable_genes(sp, n_top_genes=2000)
sc.pl.highly_variable_genes(sp)
sp = sp[:, sp.var['highly_variable']]
sc.pp.scale(sp, max_value=10)
sc.tl.pca(sp, svd_solver='arpack')
sc.pl.pca_variance_ratio(sp, log=True)
sc.pp.neighbors(sp, n_neighbors=10, n_pcs=30)
sc.tl.diffmap(sp)
sc.pp.neighbors(sp, n_neighbors=20, use_rep='X_diffmap')
sc.tl.louvain(sp,resolution=1)
sc.tl.paga(sp)
_, axs = plt.subplots(ncols=1, figsize=(24, 10), gridspec_kw={'wspace': 0.05, 'left': 0.12})
# Modified this call because pos_coord wasn't defined:
# sc.pl.paga(sp,color='louvain',layout='fa',pos=pos_coord,threshold=0.2,ax=axs)  
sc.pl.paga(sp,color='louvain',layout='fa',threshold=0.2,ax=axs)
from scanpy.tools._utils import get_init_pos_from_paga as init
sc.tl.umap(sp,init_pos=init(sp))
sc.pl.umap(sp,color='louvain')
```

The final plot looks normal enough:

![image](https://user-images.githubusercontent.com/8238804/69206364-8c9d1880-0ba0-11ea-8180-3bbd0b8c825e.png)

Right now, there are a lot of variables in this script. There's a few things to try:

* Check if `pos_coord` is causing the issue
* I noticed your scanpy version wasn't the same as the current release, could you update that?
* If you run the script with the dataset I used, does your plot still have those strange rectangular layouts?
* Can you cut down the number of commands you used, and potentially even the amount of data? This will limit the number of variables that could be causing the behavior.

**Comment by eroell** [comment]
As we haven't heard back after the inputs above we will close the issue for now, hopefully you obtained the expected behaviour in the end :)

However, please don't hesitate to reopen this issue or create a new one if you have any more questions or run into any related problems in the future.

Thanks for being a part of our community! :)
