### ISSUE TITLE
Problem when using sc.tl.louvain

### ISSUE THREAD

**Issue by grojas-leitat** [scverse/scanpy#920]
Some kind of problem when clustering the neighbourhood graph with louvain. Some collisions with the igraph project
![Captura](https://user-images.githubusercontent.com/55575784/68854040-89ef7e80-06db-11ea-8994-0bef86e231c6.PNG)

**Comment by flying-sheep** [comment]
Old problem. If someone finds this: as seen in in the [installation instructions](https://scanpy.readthedocs.io/en/stable/installation.html#pypi-only) the package is called [python-igraph](https://pypi.org/project/python-igraph/), and you can e.g. do `pip install scanpy[louvain]`.
