### ISSUE TITLE
Create links between scanpy_tutorials and scanpy docs

### ISSUE THREAD

**Issue by flying-sheep** [scverse/scanpy#922]
https://scVelo.rtfd.io has links to its tutorials as external links in the sidebar, pretty nice!

@VolkerBergen did something cool with his scvelo_tutorials repo, by including it into the TOC tree of the main repo and vice versa:

scvelo.rtfd.io | scvelo-notebooks.rtfd.io
-------------- | ------------------------
![scvelo](https://user-images.githubusercontent.com/291575/68943962-f25a6080-07ac-11ea-9a0f-c5e424cba91c.png) | ![scvelo-notebooks](https://user-images.githubusercontent.com/291575/68944029-161da680-07ad-11ea-8d36-191fbd0bf8aa.png)

We can do that automatically by using intersphinx!

**Comment by LuckyMD** [comment]
could you do this for best practices as well? That would be a nice link between the two. Even if best practices is more than only scanpy. Still get a lot of questions in scanpy issues and discourse that best practices can help answer.

**Comment by flying-sheep** [comment]
We currently have scanpy_tutorials, scanpy_usage and single-cell-tutorial, right?

We shouldn’t include too many in the sidebar, but less than about 5 should be fine.

**Comment by flying-sheep** [comment]
Discussed in https://github.com/scverse/scanpy-tutorials/issues/64
