### ISSUE TITLE
log1p with different bases

### ISSUE THREAD

**Issue by gokceneraslan** [scverse/scanpy#929]
`log2(TP10K+1)` values are more interpretable than `log(TP10K+1)`, which uses natural logarithm, therefore it'd be great to have an option on the base of the log. It's one of the requests also here #45 .

Since neither of np.log or np.log1p accepts any base arguments(isn't this unbelievable), I did it with simple numba functions here: 

https://nbviewer.ipython.org/gist/gokceneraslan/2744cfeda702fb9b9e48d0216427372c?flush_cache=true

I won't have time to send a PR, but feel free to pursue further, adapt the notebook and merge (if you have time).

PS: Also see https://github.com/numpy/numpy/issues/14969.

**Comment by flying-sheep** [comment]
There are quite a few questions that need to be answered first:

1. What's the performance difference here?
2. Numpy only uses its internal code in the off chance that `#ifndef HAVE_LOG1P`: In which circumstances does accuracy suffer when using that naive implementation?
3. Does numba.vectorize handle sparse matrices?
