### ISSUE TITLE
no highly variable genes

### ISSUE THREAD

**Issue by brianpenghe** [scverse/scanpy#935]
I ran the newest Scanpy package's 
```
sc.pp.highly_variable_genes(adata, min_mean=0.0125, max_mean=3, min_disp=0.05,
                            batch_key='batch')
```

It indeed gave me information about highly_variable_nbatches etc. But all the genes were labelled as not variable ('False').

Any ideas?

**Comment by gokceneraslan** [comment]
@LuckyMD is your fix (https://github.com/theislab/scanpy/pull/824) in the released scanpy or still only on master?

**Comment by LuckyMD** [comment]
It's only on master, but I don't think that would change anything here. The fix was for cases where `sc.pp.highly_variable_genes()` outputs an error due to bin boundaries being duplicated as genes were unexpressed. 

I reckon this is not actually a bug. It's a possible scenario that no genes are highly variable in all batches, no? Is `highly_variable_intersection` `False` everywhere, or is `highly_variable_nbatches` somehow false? The former can be `False` if your batches are heterogeneous.

**Comment by brianpenghe** [comment]
Highly_variable_nbatches shows a lot of non-zero values. Or do you mean 'highly_variable' and 'highly_variable_intersection' are outputting the same thing?
My own solution for this is:
```
adata.var['highly_variable']=adata.var['highly_variable_nbatches']>0
```

**Comment by LuckyMD** [comment]
Yeah, so this is not a bug. It's just that there is no HVG that is shared between all of your batches. I would suggest selecting the number of HVGs that are shared by all batches but 1, and then go down to all batch but 2 if you want more HVGs.

For example:
`adata.var['highly_variable'] = adata.var['highly_variable_nbatches'] == adata.obs.batch.nunique()-1`

**Comment by brianpenghe** [comment]
But did you just mean that data.var['highly_variable'] is useless?

**Comment by LuckyMD** [comment]
No, not at all. It depends how you calculate highly variable genes. If you don't use the `batch` parameter, then it always works fine. If you use the `batch` parameter, it outputs `adata.var['highly_variable_genes_intersection']` and `adata.var['highly_variable_genes_nbatches']` which is information on how many batches a particular HVG is shared by. In the intersection field the genes are labelled as `True` that are shared by all batches. If no HVG is shared by all batches, this will be `False` for all genes. In that case you can define `adata.var['highly_variable']`  as you like... usually you would do that depending on the nbatches output.

**Comment by brianpenghe** [comment]
OK. So If I understand it correct, when batch_key is used, adata.var['highly_variable'] is just adata.var['highly_variable_genes_intersection'] ?

**Comment by LuckyMD** [comment]
I just checked again... and it's not exactly the same... if you select `n_top_genes` then, you will get the top genes shared by the most batches. If you select thresholds for mean and dispersion, you will use these thresholds against the mean dispersion and mean mean across all batches. And those can be lower than the thresholds if HVGs are not shared between many batches. So to be safe, you can go with selecting `n_top_genes`.
