### ISSUE TITLE
"Compare to a single cluster" can not work

### ISSUE THREAD

**Issue by AnatoleKing** [scverse/scanpy#94]
code:

```py
sc.tl.rank_genes_groups(adata, 'louvain_groups', groups=['13'], reference= '18' )

Error:
ValueError: reference = 18 needs to be one of group_by = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
```

I think the problem is the code comfuse str(18) and int(18).

could you solve it? Thanks

**Comment by falexwolf** [comment]
Hm, strange; how did you manage to obtain integer cluster names? Did you manually rename them? `adata.obs['louvain_groups'].cat.categories` should always be strings. If you use integers, you should also pass `reference=18` and not `reference='18'`. But the use of integers is strongly discouraged and probably not stable...

I only could reproduce a similar error when running `sc.tl.rank_genes_groups(adata, 'louvain_groups', groups=['0'], reference='9')` in the [clustering example notebook](https://nbviewer.jupyter.org/github/theislab/scanpy_usage/blob/master/170505_seurat/seurat.ipynb):

```pytb
ValueError: reference = 9 needs to be one of group_by = ['0', '1', '2', '3', '4', '5', '6', '7'].
```

PS: The error is raised by the following

```py
if (reference != 'rest'                                                                                                                                                          
    and reference not in set(adata.obs[group_by].cat.categories)):                                                                                                               
    raise ValueError('reference = {} needs to be one of group_by = {}.'                                                                                                          
                     .format(reference,                                                                                                                                          
                             adata.obs[group_by].cat.categories.tolist()))
```

**Comment by AnatoleKing** [comment]
Thanks. My 'louvain_groups' is prouduced by

```py
sc.tl.louvain(adata, n_neighbors=10, resolution=1.3, recompute_graph=True)
```

but it actually give int numbers:

```py
In [6]: adata.obs['louvain_groups'].cat.categories
Out[6]: Int64Index([
            0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  10, 11, 
            12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
        ], dtype='int64')
```

How can I fix that?

**Comment by AnatoleKing** [comment]
I solved the problem by

```py
adata.obs['louvain_groups'].cat.categories = [
    str(i) for i in adata.obs['louvain_groups'].cat.categories
]
```

I think you need check the function `sc.tl.louvain(adata, n_neighbors=10, resolution=1.3, recompute_graph=True)`, why it gives int number.

**Comment by falexwolf** [comment]
This is very strange... Do you have this issue also in the [standard tutorial](https://nbviewer.jupyter.org/github/theislab/scanpy_usage/blob/master/170505_seurat/seurat.ipynb)? Of course, the louvain function produces string-named categories, see [here](https://github.com/theislab/scanpy/blob/5299c6caaec6402513f1e0442186350787177d2c/scanpy/tools/louvain.py#L135) and has always done so. I'm puzzled that the `.astype('U')`, where the `'U'` stands for unicode-string, seems to have no effect in your version of Scanpy. Do you use the most recent version (0.4.4) and recent dependencies? If not, run `pip install --upgrade scanpy`.

**Comment by flying-sheep** [comment]
I got ints as well in the past, not now though:

```py
In [1]: import scanpy.api as sc
In [2]: sc.__version__
Out[2]: '0.4.4'
In [3]: m = sc.datasets.moignard15()
In [4]: sc.tl.louvain(m)
In [5]: m.obs.louvain_groups.cat.categories
Out[5]: Index(['0', '1', '2', '3', '4', '5', '6', '7'], dtype='object')
```

**Comment by falexwolf** [comment]
Thank you for this; maybe there was one version where this was inconsistent and I simply don't remember... @AnatoleKing have you used version 0.4.4?

**Comment by flying-sheep** [comment]
that was before 0.3 https://github.com/theislab/scanpy/commit/b8d6f39caa6eb290863462c142ff72f07e061cd5#diff-ecb9fc46551f2ad6280e784298851b65R125

**Comment by falexwolf** [comment]
no, should not have been, I think; see my comments in the code...

**Comment by flying-sheep** [comment]
oh, i see

**Comment by AnatoleKing** [comment]
@falexwolf , I used '0.4.2' version, I will update to the latest.
Thanks, scanpy is powerful tool for single cell RNASeq data.

**Comment by falexwolf** [comment]
Hope that these issues are solved, now...
