### ISSUE TITLE
Logistic Regression in scRNA

### ISSUE THREAD

**Issue by dawe** [scverse/scanpy#95]
Hi all, 
Following [this preprint](https://www.biorxiv.org/content/early/2018/02/14/258566) and the polemic [comment](https://liorpachter.wordpress.com/2018/02/15/watermans-egg/amp/?__twitter_impression=true) by its author, I wonder if Logistic Regression should be in scanpy environment.
I tried the `sklearn.linear_model.LogisticRegressionCV` classifier from scikit-learn. It is pretty fast and seems to do the job. Of course there is no urgent need to include in scanpy, as it can be used with two lines like

```
clf = sklearn.linear_model.LogisticRegressionCV()
clf.fit(adata.X, adata.obs[group])
```

among the returned elements, `clf.coef_` can be used to rank genes by their importance on each group, `clf.predict_proba` may be used to score the strength of cell/group association given the scored genes. 
Any thought?

**Comment by falexwolf** [comment]
Hi Davide,

I like the preprint and the blog post. I agree that differential expression testing deserves a classification perspective. Coincidentally, we (with @tcallies) were also working on a little paper that makes this point but used neither logistic regression nor TCCs as covariates... unfortunately, we still haven't updated our benchmarks, but I'd assume that what Lior Pachter does works best. :smile:

Anyways, yes, we should include it at some point but let's still collect some experience... Until then, people can use your two-line workaround. :wink:

Thanks!

**Comment by dawe** [comment]
Agreed. I don’t think we should rush and include everything into scanpy, especially when it would be a simple wrapper of something existing.
