### ISSUE TITLE
Ordering of selected discrete colors in scatter plots when using 'groups='

### ISSUE THREAD

**Issue by y22** [scverse/scanpy#954]
[x ] Additional function parameters / changed functionality / changed defaults?

When we have discrete colors for clusters or samples, scatter plots (and therefore umap, tsne plots etc.) using a command like this `sc.pl.scatter(adata, color='sample', groups=['A'])` can help emphasize them by plotting only selected colors and all other cells in gray (see attached). This is very useful. But much like with continuous coloring, the order of colors matters. And particularly here, it would be most useful if all cells with selected colors are "in front" of all gray cells. Currently some colored selected cells are often invisible behind gray cells, like in the attached example.
[umap-example.pdf](https://github.com/theislab/scanpy/files/3965139/umap-example.pdf)

**Comment by fidelram** [comment]
This was solved recently. Can you check that you are using the latest version from master?

**Comment by y22** [comment]
Yes, it works in the latest version, thank you!
