### ISSUE TITLE
Filter out specific clusters using their cluster number

### ISSUE THREAD

**Issue by annrosebright** [scverse/scanpy#958]
There is a certain cluster of cells that I would like to remove. They seem to mess up the pseudo time. Is it possible to do this? I know that we can filter cells based on gene counts. But in this case, I would like to remove them based on annotated cluster labels.

adata.obs[‘clusters’].cat.categories
Index([‘0’, ‘1’, ‘2’, ‘3’, ‘4’, ‘5’, ‘6’, ‘7’, ‘8’, ‘9’, ‘10’, ‘11’, ‘12’,
‘13’, ‘14’, ‘15’, ‘16’, ‘17’, ‘18’, ‘19’, ‘20’, ‘21’, ‘22’, ‘23’, ‘24’,
‘25’],
dtype=‘object’)

The cluster I wan to remove is 25.

Thanks in advance

**Comment by LuckyMD** [comment]
Hey @annrosebright!

I see you also asked this question the relevant forum on discourse. I answered it there :).

**Comment by Battamama** [comment]
May I ask where that question and answer would be?
