### ISSUE TITLE
t test with violin plot

### ISSUE THREAD

**Issue by shendong124** [scverse/scanpy#970]
Hi islab,

I was wondering if there is a way to get statistical significance for a given gene expression between 2 groups on a violin plot or make a calculation separately?

for example:
here is the expression of GZMB  between 2 groups and O would like to see if the difference is statistical significant with a simple t-test.

<img width="164" alt="image" src="https://user-images.githubusercontent.com/29153026/71746338-7631e000-2e21-11ea-95db-0aef5fe6dba7.png">

Thank you fore your help,
Shen

**Comment by LuckyMD** [comment]
Hi @shendong124,

This is a usage question that should probably be asked on the discourse server here: https://scanpy.discourse.group/ 

Just a quick answer:
Check out the function `sc.tl.rank_genes_groups()` here https://scanpy.readthedocs.io/en/stable/api/scanpy.tl.rank_genes_groups.html#scanpy.tl.rank_genes_groups

If you have any further questions, let's continue that on the discourse.
