### ISSUE TITLE
Fix docs

### ISSUE THREAD

**Issue by flying-sheep** [scverse/scanpy#972]
PR #966 broke the docs but we missed it because it set `nitpicky = False`. I restored the intentional behavior of docs failing when they’re broken, so we can now see the breakage caused by #966:

https://readthedocs.com/projects/icb-scanpy/builds/273340/

`/home/docs/checkouts/readthedocs.org/user_builds/icb-scanpy/checkouts/latest/scanpy/neighbors/__init__.py:docstring of scanpy.Neighbors:6:py:class reference target not found: anndata._core.anndata.AnnData`

This can easily be fixed by adding the right mapping to `qualname_overrides` in conf.py, or changing scanpydocs default for `qualname_overrides`.

I’m also pretty sure there were branch protection rules in place that prevented such changes happening to master. Why were they removed? I restored one that reflects what we agreed upon:

- 1 reviewer has to accept a PR
- Travis needs to succeed
- No merge commits

Please do not remove or change the branch protection rules before discussing that change.

**Comment by falexwolf** [comment]
Oh, this is what the `qualname_overrides` are for? Great! I will add this.

It was so hard to debug as locally, everything worked out perfectly.

**Comment by flying-sheep** [comment]
Yes, it maps the code location of classes/functions to their documented locations.

Hmm, I thought you use a newer anndata? `scanpydoc` by default contains a mapping for the old location of AnnData, which is why this fails with a new location.

**Comment by flying-sheep** [comment]
Fixed in 8a180ccbfaa2a0305684411bf6ab7f898508ad6f
