### ISSUE TITLE
Stochastic effects in violin plotting function with jitter

### ISSUE THREAD

**Issue by simoriva** [scverse/scanpy#977]
Hi all,

I am analysing some 10x samples generated in my lab and I noticed that there could be some problems with your `read_10x_mtx` function. So, I opened 4 times the `pbmc3k` dataset used in your tutorial by using the following lines of code:

`adata = sc.read_10x_mtx(sample, var_names='gene_symbols', cache=True)`
`adata.var_names_make_unique()`
`sc.pp.filter_cells(adata, min_genes=200)`
`sc.pp.filter_genes(adata, min_cells=3)`
`mito_genes = adata.var_names.str.startswith('MT-')`
`adata.obs['percent_mito'] = np.sum(adata[:, mito_genes].X, axis=1).A1 / np.sum(adata.X, axis=1).A1`
`adata.obs['n_counts'] = adata.X.sum(axis=1).A1`

I generated the violin plots showing the `n_genes`, `n_counts`, and `percent_mito` for each test and they are different in each test (see attached picture).

![Tests](https://user-images.githubusercontent.com/38785099/72088802-d7b2ec80-3302-11ea-91cd-db9d95698c00.gif)

Do you have any suggestions to solve this problem?

Thank you in advance,
Simone

**Comment by LuckyMD** [comment]
Hi,

I don't think the data is actually different. Only the jitter in the violin plot places the dots in different places (this is an inherent stochastic effect). The underlying value of `n_genes` (and others) is still the same. You can check if `adata.obs['n_counts']` is the same in the 4 objects you load.

**Comment by simoriva** [comment]
Hi,

Thank you for your prompt reply and suggestions.

I checked the `adata.obs["n_counts]` and `adata.X` comparing them among the different tests and they are actually identical.
I also identified why there was a stochastic effect in the jitter plots inside the violin plots.
It is due to the `numpy` random seed; indeed, if you call `numpy.random.seed(N)` before calling the `scanpy.pl.violin` function, you obtain the same violin plots.
Notice that you have to call it before every call of  `scanpy.pl.violin`.
It seems that the seed is reset somewhere in the code.

Best wishes,
Simone
