### ISSUE TITLE
Numba issues - and a potential fix

### ISSUE THREAD

**Issue by adamgayoso** [scverse/scanpy#981]
@flying-sheep I think this could likely be the issue

https://github.com/numba/numba/issues/5035

You could likely only allow versions before numba 0.47.0 and llvmlite 0.31.0.

It also seems like the newest versions are incompatible with mnn_correct (#974)

**Comment by flying-sheep** [comment]
Thank you! The bug you linked is about 0.4**6** + 0.31, though, while the newest versions (where the bugs happened for us) are 0.47 + 0.31. Anyway, I circumvented them already in #980
