### ISSUE TITLE
No grouping lines at top of dotplot

### ISSUE THREAD

**Issue by adamgayoso** [scverse/scanpy#998]
In the tutorial there are lines grouping the genes at the top of the dotplot.

<img width="667" alt="Screen Shot 2020-01-15 at 11 47 42 AM" src="https://user-images.githubusercontent.com/10859440/72465969-eb3fd680-378c-11ea-925a-4f6b9f8039ed.png">

A minimal example does not generate those lines...

![Screen Shot 2020-01-15 at 11 44 30 AM](https://user-images.githubusercontent.com/10859440/72465706-81bfc800-378c-11ea-9700-f2e4b4b69eac.png)

```python
scanpy==1.4.5.post2 anndata==0.6.22.post1 umap==0.3.10 numpy==1.18.0 scipy==1.3.1 pandas==0.25.1 scikit-learn==0.21.3 statsmodels==0.10.1 python-igraph==0.7.1 louvain==0.6.1
matplotlib==3.0.3
```

**Comment by fidelram** [comment]
For me is working properly with an earlier version of scanpy and the same matplotlib version. Can you downgrade and test if the problem is only happening in the last version.

Also, you can try to see if the problem is related to some matplotlib parameters by resetting them.
```PYTHON
matplotlib.rcdefaults()
```

**Comment by adamgayoso** [comment]
Resetting the matplotlib rc seemed to fix the problem. Perhaps the issue has something to do with me importing seaborn and doing `sns.set(context="notebook", font_scale=1.15, style="ticks")`? 

I'm not doing anything else special.

**Comment by fidelram** [comment]
Yes, seaborn changes the matplotlib defaults which can cause this problem.

**Comment by xuesoso** [comment]
Just want to leave a comment here that the relevant matplotlib parameter to change is "patch.edgecolor". The following should fix the missing grouping lines.

```python
matplotlib.rcParams['patch.edgecolor'] = 'black'
```

**Comment by NJNataren** [comment]
> Just want to leave a comment here that the relevant matplotlib parameter to change is "patch.edgecolor". The following should fix the missing grouping lines.
> 
> matplotlib.rcParams['patch.edgecolor'] = 'black'

So 5 years later, I was facing this issue and thanks to this one forum post, I now have a solution. Thank you @xuesoso, you have saved my sanity.
